▁Ini_ms ▁sebab nya_ms ▁kau_ms ▁meno lak ▁ke_ms du_ms du_ms kan_ms ▁di_ms ▁Ho s pita l ▁Da e je on ▁dan_ms ▁kem ari ?
▁Ray ▁sedang ▁bekerja .
▁Kamu ▁tak_ms ▁tahu_ms ▁dia_ms ▁takut kan_ms ▁a_ms pi ?
▁Ham pir ▁masa_ms ▁untuk_ms ▁makan ▁malam .
▁Kenapa ▁awak_ms ▁tak_ms ▁cas ▁i_ms a ?
▁- ▁Kelly ▁dah ▁u saha ▁ber_ms sungguh .
▁Ia ▁tidak_ms ▁boleh ▁dilakukan .
▁Papa r ▁kedua - du_ms a ▁ko lum ▁ta juk ▁dan_ms ▁ala mat
▁Sa li_ms _ n ▁Lo ka_ms si_ms ▁Pa u tan_ms ▁Audio
▁Har i ▁ini_ms ▁% l :% M ▁% p
▁- ▁Max ine .
▁Ta di_ms ▁kita_ms ▁seperti_ms ▁ter_ms bang .
▁Ja wa_ms b ▁so alan ▁aku_ms ▁du lu_ms
▁Aku_ms ▁akan_ms ▁meng hen ti_ms kan_ms ▁per_ms nika han_ms ▁ini_ms !
▁Kau_ms ▁dia_ms m . ▁saya_ms ▁bu leh ▁ka wal ▁sendiri
▁Awak ▁ingat ▁saya_ms ▁nak ▁per_ms angkap ▁awak_ms ▁lagi_ms ?
▁Tak_ms ▁boleh , ▁hari ▁si_ms buk .
▁- ▁Tak_ms nak .
▁Dia_ms ▁juga_ms ▁pe_ms mi_ms lik_ms ▁resto ran ▁ni ▁Tapi_ms ▁dia_ms ▁selalu ▁hi lang_ms .
▁Anda_ms ▁mengatakan ▁sesuatu_ms ▁seperti_ms ▁" A pa_ms ▁yang_ms ▁mungkin ▁anda ▁lakukan_ms ▁...
▁Har us_ms ▁ada_ms ▁kedua - du_ms a nya_ms .
▁Mari ▁ta nya_ms ▁dalam_ms ▁pan tri ▁dan_ms ▁kemudian ▁buat ▁ke_ms put us_ms an_ms .
▁Hey , ▁Harry , ▁saya_ms ▁dah ▁dapat_ms .
▁- ▁Kita_ms ▁sudah ▁sa ling ▁ken al_ms .
▁Wa jah mu_ms ▁tidak_ms ▁je_ms lek .
▁Mac am ▁mana_ms ▁mak ▁boleh ▁bercakap ▁tentang ▁dia_ms ▁begitu ?
▁Te mbo k ?
▁Jadi ▁jangan ▁jadi ▁terlalu ▁ge mu_ms k !
▁- ▁... ▁main ▁di_ms ▁se_ms ki_ms tar ▁di_ms ▁radio ▁ham ?
▁paper ▁size
▁Dengar ▁sini_ms ▁baik_ms - baik ▁jika_ms ▁awak_ms ▁tidak_ms ▁dengar ▁saya_ms ▁betul - be tul .
▁Ke_ms ja_ms p , ▁bi ar_ms ▁aku_ms ▁tun juk .
▁U ji ▁jika_ms ▁ daemon ▁win bind d ▁dija lan_ms kan_ms ▁bila ▁pa kej ▁di_ms pas ang_ms .
▁Peng guna an_ms : ▁m klo st + fo und
▁Tapi_ms ▁i_ms a ▁me_ms mpe son akan_ms ▁aku_ms .
▁- ▁Saya_ms ▁dalam_ms ▁keadaan ▁tel anja ng_ms .
▁Men gh ada pi ▁je_ms nis ▁M H OD ▁(% d ) ▁yang_ms ▁tidak_ms ▁di_ms keta hui ▁sem_ms asa_ms ▁meng hur ai ▁i_ms Tu nes DB . ▁Aba ikan_ms .
▁A ▁mu da_ms , ▁kan ak_ms - kan_ms ak_ms ▁yang_ms ▁can tik .
▁Maka ▁Allah_ms ▁menu run kan_ms ▁se_ms manga t ▁tena ng_ms ▁ten ter am ▁kepada_ms ▁( Na bi ▁Muhammad ) ▁dan_ms ▁mengu at_ms kannya ▁dengan_ms ▁bantuan ▁ten tera ▁( ma_ms la_ms ikat ) ▁yang_ms ▁kamu_ms ▁tidak_ms ▁melihat nya_ms . ▁Dan_ms ▁Allah_ms ▁menjadi_ms kan_ms ▁ser uan ▁( s yi rik ) ▁orang_ms - orang ▁kafir ▁ter_ms ke ba_ms wa_ms h ▁( ka_ms lah_ms ▁dengan_ms ▁se_ms hina - hina nya_ms ) , ▁dan_ms ▁Kal ima h ▁Allah_ms ▁( Is lam ) ▁ialah ▁yang_ms ▁ter_ms ting gi ▁( se_ms lama - lama nya_ms ) , ▁kerana ▁Allah_ms ▁Maha ▁Ku asa_ms , ▁lagi_ms ▁Maha ▁Bij aks ana .
▁Te ta_ms pi ▁ada_ms ▁cara ▁lain ▁untuk_ms ▁membuat ▁wa_ms ng_ms , ▁terlalu .
▁Men g gos ok nya_ms ▁semua_ms ▁sekali ▁li ang_ms - li_ms ang_ms ▁ku_ms lit ▁saya_ms , ▁dan_ms ▁an gin ▁antara ▁mata ▁saya_ms ▁menge tuk ▁ma du_ms ▁dalam_ms ▁si_ms kat ▁saya_ms .
▁Ra lat : ▁% s : ▁Bi langan ▁med an_ms ▁tidak_ms ▁men_ms cu kup i ▁dalam_ms ▁bar is ▁% u .
▁Ta man_ms ▁Sel atan ▁ke_ms ▁sun gai .
▁G n ect
▁Jo m ▁!
▁Kita_ms ▁berdua ▁tahu_ms ▁kalau ▁mereka_ms ▁sedang ▁ke_ms ▁sini_ms .
▁Tak_ms ▁dapat_ms ▁menu kar na_ms ma_ms ▁ime j :
▁Su nggu h ▁ kurang ▁a_ms jar .
▁Nama ▁saya_ms ▁A nak - H ong ▁Kong ...
▁Untuk ▁10 ▁bul an_ms ...
▁- ▁Baiklah ▁ , ▁anda ▁tidak_ms ▁si_ms u man_ms .
▁Aku_ms ▁kata ▁tem bak .
▁Th read - Id ▁% d , ▁[ state ] ▁running , ▁det ach ed
▁Aku_ms ▁katakan ▁kepada_ms mu_ms . ▁sebelum ▁fa jar ... ▁engkau ▁akan_ms ▁meny ang_ms kal ▁Aku_ms ▁ti ga_ms ▁kali .
▁Saya_ms ▁nampak ▁dia_ms ▁dalam_ms ▁ber_ms ita !
▁" Sa ya ▁tak_ms ▁boleh ▁lakukan_ms ▁ini_ms ▁tanpa ▁bantuan ▁dan_ms ▁kerja s ama ▁dari_ms ▁wa_ms kil ▁se_ms ki_ms an_ms - sek ian ▁di_ms ▁ja ba_ms tan_ms ▁polis ."
▁Saya_ms ▁um ur ▁20.
▁Ren te tan_ms ▁UTF -8 ▁tak_ms ▁sah ▁dalam_ms ▁fail ▁cor ak_ms ▁'% s ' .
▁saya_ms ▁tak_ms ▁mahu ▁men_ms jal ani ▁hidup ▁seperti_ms ▁masa_ms ▁lalu ▁lagi_ms .
▁Ne nek ▁baru ▁saja ▁di_ms ma_ms kam kan_ms ▁ke_ms mar in_ms !
▁" mah kama h ▁meng anggap ▁para ▁defend an_ms ' ▁ter_ms buk ti_ms ▁ada_ms ▁su mbang an_ms ."
▁Hei , ▁Ar ch !
▁Folder ▁& ▁Sa mpah
▁Saya_ms ▁tur ut_ms ▁menang ▁sebuah ▁pi ala .
▁Anda_ms ▁orang_ms ▁le mah ▁"
▁Ia nya_ms ▁bukan_ms ▁fakt a ▁yang_ms ▁dia_ms ▁ psi ko tik .
▁Masa ▁is teri ,
▁Ke_ms sala han_ms ▁dari_ms ▁Sar man_ms
▁- ▁Call ▁me_ms ▁fa tso .
▁Terima
▁Kalau ▁tak_ms , ▁dia_ms ▁akan_ms ▁ter_ms ima ▁an ca_ms man_ms ▁seperti_ms ▁Ra ke sh .
▁Fa il ▁se_ms ment ara ▁di_ms buka : ▁% s
▁J eneral , ▁la_ms por an_ms ▁a_ms wal ▁yang_ms ▁di_ms kel uar kan_ms ▁oleh ▁SHA EF ▁mengatakan ▁Di vis yen ▁ke_ms -10 1 ▁dah ▁berse pa_ms h .
▁# ▁J ing_ms le ▁ bell s , ▁Bat man_ms ▁sme ll s , ▁Robin ▁la_ms id ▁an ▁e gg !
▁Da lam ▁pada_ms ▁itu_ms ) ▁mereka_ms ▁adalah_ms ▁seperti_ms ▁bat ang_ms - ba_ms tang ▁ka yu ▁yang_ms ▁ter_ms san dar ▁( ti_ms dak ▁ter_ms paka i ▁kerana ▁tidak_ms ▁ada_ms ▁pada_ms nya_ms ▁kekuatan ▁yang_ms ▁di_ms ke hen daki ) . ▁Mereka ▁( ker ana ▁merasa i ▁ber_ms sa_ms lah_ms , ▁senti asa_ms ▁dalam_ms ▁keadaan ▁ce mas ▁sehingga ) ▁meny ang_ms ka_ms ▁ti ap - ti_ms ap ▁je_ms ritan ▁( ata u ▁ri uh_ms ▁rend ah_ms ▁yang_ms ▁mereka_ms ▁dengar ) ▁adalah_ms ▁untuk_ms ▁memba haya kan_ms ▁mereka_ms .
▁Men ang_ms ▁di_ms ▁An u ge rah_ms ▁Ne bula .
▁Apa_ms ▁kau_ms ▁rasa ▁dengan_ms ▁Kau_ms ▁yang_ms ▁" Ba ru " ▁ni ?
▁... ▁untuk_ms ▁bay angkan ▁dengan_ms ▁siapa ▁saya_ms ▁nak ▁hab is kan_ms ▁seu mur ▁hidup ▁saya_ms ▁ini_ms . .
▁Mungkin ▁ini_ms ▁orang_ms nya_ms .
▁Lihat lah_ms ▁... ▁foto ▁anda .
▁Itu_ms ▁ke_ms ▁yang_ms ▁awak_ms ▁katakan ?
▁Saya_ms ▁membawa ▁la_ms por annya .
▁Adakah ▁kita_ms ▁tetap ▁dengan_ms ▁wa_ms ng_ms ▁tun ai ▁?
▁Gu y , ▁dari_ms ▁mu la_ms ▁awak_ms ▁ber_ms lum ba_ms ▁di_ms ▁In dy ▁Light s , ▁pernah_ms kah_ms ▁awak_ms ▁ber_ms mi_ms mpi ▁akan_ms ▁ber_ms dir i ▁di_ms ▁pen_ms tas ▁ini_ms ?
▁Se_ms bab ▁ali en ▁itu_ms ▁datang ▁ke_ms ▁sini_ms ...
▁Dan_ms ▁( ing_ms at_ms lah_ms ) ▁Allah_ms ▁Maha ▁Ku asa_ms ▁atas ▁ti ap - ti_ms ap ▁sesuatu_ms .
▁Kau_ms ▁takkan ▁keluar ▁temu ja_ms nji ▁wa_ms lau ▁ny awa ▁kau_ms ▁ber_ms gan tung ▁pada_ms nya_ms .
▁Ke_ms cil
▁tapi ▁mungkin ▁ada_ms ▁satu_ms ▁pel u ang_ms ▁disini .
▁Pe ny_ms ele ng_ms gara
▁Sel agi ▁ba_ms dan ▁em as ▁Tuan ▁Gu ru ▁masih ▁ut uh_ms ...
▁Kamu ▁kena ▁ter_ms ima ▁saya_ms ▁di_ms ▁ha_ms da_ms pan_ms ▁seluruh ▁dunia
▁Ber_ms ikan_ms ▁kad
▁Per tahan kan_ms ▁Lord ▁Co ty s !
▁De e wan ▁Sa he b !
▁Tu kan_ms g ▁uru t ? ▁- ▁Ya_ms
▁Tuan , ▁kalau ▁di_ms ▁ ang_ms kas ale pas ▁pen_ms ▁found a in_ms ▁pen_ms ▁mata ▁bola ▁tak_ms ▁boleh ▁digunakan , ▁kenapa ▁ ang_ms kas a wan ▁tak_ms ▁gun akan_ms ▁pense l ▁je_ms ?
▁Ay uh_ms , ▁Che t .
▁Saya_ms ▁akan_ms ▁pada_ms m kan_ms ▁ingat an_ms ▁awak_ms ▁dan_ms ▁kembali kan_ms ▁awak_ms ▁ke_ms ▁jalan ▁betul .
▁[ Art hur ] ▁Anda_ms ▁dont ▁mempunyai ▁untuk_ms ▁menu lis ▁sesuatu_ms ▁bawah ▁menjadi_ms ▁seorang_ms ▁pe_ms nya_ms ir .
▁Ya_ms , ▁tetapi ▁saya_ms ▁bay angkan ▁saya_ms ▁sedang ▁du duk ▁di_ms ▁ha_ms da_ms pan_ms ▁anda , ▁dan_ms ▁jika_ms ▁saya_ms , ▁I . ▁..
▁Itu_ms lah_ms ▁ isti lah_ms ▁orang_ms ▁Amerika .
▁Awak ▁berada ▁di_ms ▁tempat ▁yang_ms ▁mena kut kan_ms ▁seperti_ms ▁yang_ms ▁saya_ms ▁bay angkan .
▁Mungkin ▁ini_ms ▁semua_ms ▁hanya_ms ▁peng_ms ali han_ms ▁per_ms hati an_ms .
▁- Se benar nya_ms ▁i_ms a ▁dalam_ms ▁ba_ms hu ▁saya_ms .
▁Dan_ms ▁telah_ms ▁me_ms lib atkan ▁beberapa ▁je_ms nis ▁masalah
▁- ▁Saya_ms ▁boleh ▁tuli s ▁pe_ms mbang kan_ms gan .
▁Hei ▁ , ▁anak ▁la_ms ki_ms ▁- ▁la_ms ki_ms ▁ , ▁jika_ms ▁ini_ms ▁adalah_ms ▁pen_ms dek atan ▁anda ▁untuk_ms ▁perempuan ▁ , ▁Anda_ms ▁tidak_ms ▁akan_ms ▁menjadi_ms ▁sangat_ms ▁jauh ▁ .
▁Kenapa ▁kamp ung ▁ini_ms ?
▁Awak ▁berdua ▁baik_ms ▁jangan ▁ga nggu ▁saya_ms ,
▁- ▁Kita_ms ▁tak_ms ▁tinggal ▁di_ms ▁Bu lan_ms !
▁- ▁Mereka ▁ga m bar ▁!
▁Di al_ms ▁9 99 ?
▁Jangan ▁de_ms kat ▁dengan_ms ▁a_ms we k ▁aku_ms !
▁Si mi_ms , ▁kamu_ms ▁dah ▁mu la_ms ▁menu lis ▁puis i ▁yang_ms ▁bagus , ... ▁.. dan ▁lelaki ▁itu_ms ▁macam ▁betul - be tul ▁w uju d .
▁Mari ▁kita_ms ▁men_ms ak_ms luk ▁dunia
▁Dan_ms ▁selamat ▁datang ▁ke_ms ▁Grand ▁Pa ngo lin ▁Ar ms .
▁Jesus ▁Christ . ▁saya_ms ▁tidak_ms ▁tahu_ms ▁di_ms mana ▁awak_ms ▁ambil ▁pen_ms didi kan_ms ▁awak_ms ▁ini_ms ▁bukan_ms lah_ms ▁dari_ms ▁e jen ▁yang_ms ▁pen_ms uh_ms ▁kad ang_ms - ka_ms dang ▁saya_ms ▁fikir ▁awak_ms ▁tau ▁banyak_ms
▁" I a ▁mungkin ▁salah ▁seorang_ms ▁kawan - ka_ms wan ▁kamu_ms ."
▁Anda_ms ▁selalu ▁me_ms mal ukan ▁saya_ms .
▁Aku_ms ▁sang ka_ms ▁i_ms a ▁dah ▁ter_ms ba_ms kar .
▁Oh , ▁i_ms a ▁bukan_ms ▁hanya_ms ▁sebuah ▁bu ku_ms .
▁W ise . T er ima ▁kasih .
▁Ber_ms ikan_ms ▁satu_ms ▁kad ▁dari_ms ▁de_ms k
▁Aku_ms ▁tak_ms ▁dapat_ms ▁beritahu ▁kau_ms ▁ber_ms apa_ms ▁kali ▁aku_ms ▁ber_ms mi_ms mpi ▁aku_ms ▁na ik ▁li ft ▁ni .
▁Se_ms baik ▁sahaja ▁dia_ms ▁pergi_ms , ▁anda ▁akan_ms ▁ter_ms per angkap ▁di_ms ▁sini_ms ▁selama ▁li ma_ms ▁tahun ▁lagi_ms .
▁Apa_ms ▁yang_ms ▁anda ▁lakukan_ms ?
▁Aku_ms ta_ms hu .
▁W ang_ms ▁yang_ms ▁p ember i ▁pi nja man_ms ▁akan_ms ▁mem bela ▁ke_ms ja_ms hi lan_ms
▁Apa_ms ▁aku_ms ▁ter_ms ti_ms dur ▁ta di_ms ?
▁Kau_ms ▁tak_ms ▁ada_ms ▁anak ▁ke_ms ?
▁katakan ▁tentang ▁mol ly ▁walk er .
▁Bak at_ms ▁yang_ms ▁kamu_ms ▁ada_ms ▁ sungguh ▁besar .
▁Har us_ms kah_ms ▁kita_ms ▁membunuh ▁wanita ▁ini_ms ▁atau ▁bagaimana ?
▁Seperti ▁yang_ms ▁dira nc ang_ms ▁oleh ▁Jo ng_ms ▁Ko ok , ▁Ji ▁Ho on ▁dis ing_ms kir kan_ms ▁kerana ▁buat ▁la_ms por an_ms ▁pal su .
▁A pro x ím ense ▁dan_ms ▁mu la_ms ▁sunt ikan_ms .
▁Kamu ▁telah_ms ▁berubah ▁a_ms rah_ms ▁banyak_ms ▁se_ms men jak ▁tu_ms .
▁Nam pak nya_ms ▁mereka_ms ▁dapat_ms i ▁kami_ms .
▁Itu_ms ▁dari_ms ▁bu ku_ms ▁Ma z mur .
▁/ ▁awak_ms ▁tahu_ms ▁bet apa_ms ▁pe_ms lik_ms nya_ms ▁ini_ms ▁?
▁De ka_ms ti_ms ▁J ANG ▁Do ng_ms - shi k ▁dan_ms ▁cari ▁tahu_ms ▁di_ms mana ▁du it ▁dia_ms .
▁aj ha ▁..
▁Per angkap ▁pela nc ong .
▁Ini_ms lah_ms ▁su mpah an_ms ▁terakhir ▁Victor ▁Frank en stein .
▁Aku_ms ▁mahu ▁kau_ms ▁pergi_ms ▁ambil ▁wa_ms ng_ms ▁itu_ms .
▁Dan_ms ▁tak_ms ▁seorang_ms ▁pun ▁ingin_ms ▁mengatakan ▁apa_ms ▁pun ▁di_ms ▁telefon .
▁Doktor , ▁jika_ms ▁kamu_ms ▁perlu kan_ms ▁se_ms bar ang_ms ▁per_ms ala tan_ms ▁atau ▁apa_ms ▁saja . . ▁.. ▁i_ms a ▁akan_ms ▁di_ms uru s kan_ms ▁ser ta_ms ▁mer ta_ms
▁Be liau ▁baru - bar u ▁ini_ms .
▁Kamu ▁semua_ms ▁datang ▁te_ms pat ▁pada_ms ▁masa_ms nya_ms .
▁Tapi_ms ▁itu_ms ▁tak_ms ▁ber_ms mak na_ms ▁kau_ms ▁perlu ▁biarkan ▁i_ms a ▁berlaku .
▁Dan_ms ▁waktu ▁sub uh_ms ▁apabila ▁i_ms a ▁ter_ms ang_ms - ben der ang_ms ,
▁Kom a nder . ▁/ ▁Re ally ?
▁- Sa ya ▁beritahu ▁lagi_ms . ▁Saya_ms ▁tak_ms ▁ber_ms fik ir .
▁Kir aan ▁berak hir .
▁En kri psi kan_ms ▁fail
▁Bagaimana ▁jika_ms ▁Pre as er ▁boleh ▁tahan ▁di_ms ▁ ping gir ▁jalan ?
▁Kes eron o kan_ms ▁pela jar ▁se_ms ma_ms kin ▁me_ms mun cak
▁Ia ▁hanya_ms ▁ko s me tik .
▁Semua ▁kereta ▁ke_ms bal ▁berhenti .
▁Day ung ▁ke_ms ▁kan an_ms !
▁Peng ika tan_ms ▁ ping gir ▁bila ▁di_ms ser u , ▁akan_ms ▁jalan kan_ms ▁p erintah ▁shell ▁yang_ms ▁di_ms ken al_ms pas ti_ms ▁oleh ▁command 10
▁Tunggu ▁di_ms sela mat kan_ms .
▁Yeah .
▁Kamu ▁mahu ▁saya_ms ▁mengha lau ▁awak_ms .
▁Maks ud ▁saya_ms , ▁s no kel ▁pun ▁dia_ms ▁tak_ms ▁pa nda i .
▁Ini_ms ▁ag ak_ms nya_ms ▁rumah ▁dia_ms .
▁" di_ms ▁rumah , ▁ber_ms bi sik ▁med an_ms ▁un - di_ms se_ms mai .
▁Aku_ms ▁tak_ms ▁kh awa tir ▁tentang ▁tidur ▁atau ▁makan an_ms ku_ms
▁La mpu ▁me_ms rah_ms ▁sedang ▁meny ala .
▁Seperti nya_ms ▁dia_ms ▁perlu kan_ms ▁bantuan ▁pak ar_ms ?
▁Yang ▁men_ms di_ms dik ▁secara ▁ra sional .
▁Tidak_ms ▁perlu ▁bi mbang .
▁Sa tu_ms ▁ke_ms hor ma_ms tan_ms ▁bagi ▁kamu_ms ▁sebagai ▁pe_ms ga_ms wa_ms i ▁polis , ▁hen ti_ms kan_ms ▁mereka_ms !
▁Saya_ms ▁akan_ms ▁membuat ▁anda ▁aka un .
▁Aku_ms ▁tak_ms ▁peduli ▁apa_ms ▁yang_ms ▁Kau_ms ▁ingin_ms kan_ms ▁tapi ▁Kau_ms ▁bersama ▁kami_ms ▁sekarang .
▁Tiada ▁ga m bar ... ▁Hanya ▁ini_ms .
▁Ayah mu_ms ▁adalah_ms ▁war is ▁tak_ms hta .
▁Maks ud ▁saya_ms , ▁kita_ms ▁ada_ms ▁Bord en , ▁Liz zy , ▁sehingga ▁ke_ms ▁Cra ne , ▁Ich ab od .
▁E SU ▁me_ms landa ▁ hang out ▁sebelum ▁sub uh_ms .
▁Kau_ms ▁tahu_ms ▁apa_ms ▁in s ting ku_ms ▁memberitahu ▁aku_ms ?
▁Mereka ▁kata ▁awak_ms ▁melakukan ▁hal ▁baik_ms , ▁bahawa ▁awak_ms ▁ada_ms ▁kekuatan ▁is time wa_ms .
▁Ma in_ms kan_ms ▁bun yi ▁bila ▁mes ej ▁ti ba_ms
▁tiada ▁just ifik asi just ification text attr
▁Adakah ▁mereka_ms ▁akan_ms ▁mem benar kannya ?
▁Ini_ms ▁adalah_ms ▁a_ms zi mat ▁lag enda ▁moj in_ms ,
▁Saya_ms ▁nak ▁minta ▁awak_ms ▁lakukan_ms ▁sesuatu_ms ▁yang_ms ▁mu dah .
▁Awak ▁fikir ▁ce rita ▁saya_ms ▁tip u ?
▁Tapi_ms ▁ak hir nya_ms ▁mereka_ms ▁dapat_ms ▁juga_ms .
▁Dan_ms ▁sekarang , ▁We mble y . ▁Aku_ms ▁juga_ms ▁yang_ms ▁melakukannya .
▁Data ng_ms ▁pada_ms . ▁Ia ▁bukan_ms ▁kesalahan ▁Gun ner , ▁manusia .
▁Saya_ms ▁belum ▁memba las ▁bu di_ms ▁papa ▁dan_ms ▁mama
▁Aku_ms ▁baru ▁sahaja ▁nak ▁beritahu ▁kau_ms , sa_ms yang ku_ms ▁dan_ms ▁kehilangan ▁semua_ms ▁orang_ms ku_ms
▁Kemudian ▁mengapa ▁awak_ms ▁ber_ms main ▁bi ngo ?
▁Saya_ms ▁percaya ▁dengan_ms ▁kebenaran , ▁te_ms man_ms ▁kita_ms ▁akan_ms ▁tahu_ms ▁itu_ms .
▁Kem bali , kem bali
▁Hanya ▁ada_ms ▁satu_ms ▁per_ms atura n : ▁Men gal ahkan ▁untuk_ms ▁di_ms pa_ms dan kan_ms .
▁Saya_ms ▁di_ms mak lum kan_ms ▁bahawa ▁bu aya ▁Man ▁mungkin ▁Mala ikat ▁Me mbu nu h
▁Ke_ms kej angan_ms ▁ot ot ▁pada_ms ▁bahagia n ▁atas ▁tu_ms bu h ▁dan_ms ▁ka ki_ms .
▁Fe e , ▁sy aba s .
▁Ini_ms ▁simbol ▁keluarga ▁Way ne .
▁T UN AI :
▁Aku_ms ▁memilih ▁mengha n cur kan_ms mu_ms .
▁Dan_ms ▁Rub y ▁mempunyai ▁satu_ms ▁sedikit .
▁Tur un , ▁Po ndo lem .
▁Jangan ▁beritahu ▁saya_ms ▁bahawa , ▁pada_ms ▁masa_ms ▁itu_ms ▁kita_ms ▁akan_ms ▁perlu ▁melihat
▁URI ▁S wi ft ▁ter_ms ben tuk ▁ter_ms uk .
▁Tak_ms ▁ada_ms ▁orang_ms ▁yang_ms ▁akan_ms ▁peduli kan_ms ▁cinta ▁kita_ms
▁J eneral , ▁saya_ms ▁tahu_ms ▁apa_ms ▁yang_ms ▁kamu_ms ▁buat ▁di_ms ▁National ▁City .
▁Man if old ▁ku_ms ant um . ▁Tak_ms ▁pernah_ms ▁dengar .
▁Kamu ▁adalah_ms ▁yang_ms ▁pa ling ▁tidak_ms ▁men_ms en tu_ms ▁ , ▁Dan_ms a , ▁tetapi ▁i_ms a ▁adalah_ms ▁kun ci .
▁Mari ▁kita_ms ▁war na_ms i ▁Rad ha
▁Yeah .
▁Awak ▁mungkin ▁I rish .
▁Barry , ▁kita_ms ▁perlu ▁cari ▁Wall y .
▁Dia_ms ▁pe_ms mi_ms mpi n ▁yang_ms ▁ter_ms uk .
▁dan_ms ▁Ram ▁dengan_ms ▁cepat ... ▁mele mpar ▁pe_ms mot ong ▁rum put ▁dan_ms ▁bo ng_ms ka_ms han_ms !
▁Se_ms ych elles , ▁Ru pe e
▁Sa pa_ms ▁kata ▁kita_ms ▁ber_ms ta_ms ma_ms dun ▁lagi_ms ?
▁Name
▁Tidak_ms ▁ada_ms ▁ja min an_ms ▁dalam_ms ▁kehidupan , ▁a_ms bang .
▁- ▁Tak_ms ▁apa_ms , ▁saya_ms ▁pergi_ms ▁pu kul ▁dia_ms .
▁- ▁Danny , ▁h ubung i ▁9 11 !
▁- ▁Ada ▁lagi_ms ▁ke_ms ?
▁Anda_ms ▁lihat , ▁James ▁dan_ms ▁saya_ms ▁kedua - du_ms a nya_ms ▁baru ▁di_ms be li_ms ▁li ma_ms ▁pintu ▁hat ch back ▁Jer man_ms .
▁Kita_ms ▁tak_ms ▁boleh ▁tinggal kan_ms ▁bi lik_ms ▁ini_ms .
▁Aku_ms ▁tidak_ms ▁perlu ▁se_ms hat ▁untuk_ms ▁me_ms mu_ms kul mu_ms .
▁Sa tu_ms , ▁mi mos a ▁tiada ▁alkohol ▁ini_ms ▁hanya_ms lah_ms ▁ju s ▁ oren , ▁dan_ms ▁dua , ▁saya_ms ▁tak_ms ▁boleh ▁minu m .
▁- ▁Saya_ms ▁nak ▁dia_ms ▁me_ms mah ami ...
▁- ▁Kau_ms ▁gi la_ms . ▁mari .
▁Ny ata kan_ms ▁le bar ▁default ▁( dalam ▁pik sel ) ▁bagi ▁not a ▁baru
▁Ra j , ▁orang_ms ▁yang_ms ▁saya_ms ▁suka ▁boleh ▁panggil ▁saya_ms ▁Chu t ki_ms
▁.. bila ▁mereka_ms ▁nampak ▁dik au .
▁/ ▁Ada ▁di_ms ▁di_ms ▁history ▁kau_ms . .
▁Aku_ms ▁juga_ms ▁buat ▁sele pas ▁aku_ms ▁tinggal kan_ms ▁N SA .
▁Ber_ms kela ku_ms an_ms ▁baik_ms ▁dengan_ms ▁pe_ms lang_ms gan .
▁Ka li_ms ▁pertama ▁Saya_ms ▁bertemu ▁dengan_ms ▁kamu_ms ▁kerana ▁saya_ms ▁meninggalkan ▁awak_ms , ▁awak_ms ▁tidak_ms ▁cinta ▁dengan_ms ▁sesiapa ▁sahaja ▁dan_ms ▁saya_ms .
▁Ker ja_ms ▁dah ▁bere s
▁- ▁Baiklah . ▁ay uh_ms .
▁Aku_ms ▁akan_ms ▁menjadi_ms ▁bang kai ▁jika_ms ▁me_ms luk akan_ms ▁ha_ms ti_ms ▁dia_ms ▁lagi_ms
▁Ang in_ms , ▁Aku_ms ▁mengg endo ng_ms mu_ms ▁lama . ▁Mengapa ▁kau_ms ▁tidak_ms ▁bisa ▁tur un ▁dan_ms ▁berjalan ▁dengan_ms ▁ayah .
▁Fakt a , ▁18 ▁bul an_ms ▁lalu ,
▁Dan_ms ▁sesiapa ▁yang_ms ▁memper se_ms kut ukan ▁Allah_ms ▁( den gan ▁sesuatu_ms ▁yang_ms ▁lain ) , ▁maka ▁sesungguhnya ▁i_ms a ▁telah_ms ▁melakukan ▁dos a ▁yang_ms ▁besar .
▁Ba wa_ms ▁juga_ms ▁sena pan_ms !
▁Ay uh_ms !
▁Mo tos i kal nya_ms ▁dah ▁tiada .
▁Bag i ▁kami_ms , ▁awak_ms ▁a_ms mat ▁mu lia .
▁Kamu ▁ter_ms je bak .
▁Jika ▁anda ▁mempunyai ▁apa_ms - apa_ms ▁idea , ▁i_ms ▁saya_ms ▁semua_ms ▁tel inga .
▁Ia ▁bukan_ms ▁apa_ms ▁yang_ms ▁awak_ms ▁dapat_ms ▁me_ms mbu kti kan_ms , ▁i_ms a ▁adalah_ms ▁apa_ms ▁yang_ms ▁orang_ms ▁kata ▁mereka_ms ▁ingat .
▁Aku_ms ▁hanya_ms ▁tidak_ms ▁peduli ▁mati .
▁Maaf ... ▁by e .
▁Mereka ▁pasti ▁lu pa_ms ▁tentang ▁ke_ms ma_ms langan ▁bot ▁itu_ms ▁dua ▁bul an_ms ▁le pas !
▁Kai ten ▁si_ms ap ▁se_ms dia . ▁Adakah ▁awak_ms ▁lan car kan_ms ▁kai ten ▁awak_ms ?
▁la_ms nya_ms ▁me_ms mbo ng_ms kar ▁isi ▁ha_ms ti_ms mu_ms .
▁Kau_ms ▁datang ▁untuk_ms ▁men_ms curi ▁per_ms ala tan_ms ?
▁Ama ran : ▁% s ▁dija lan_ms kan_ms ▁sebagai ▁peng_ms guna ▁"% s " ▁pada_ms ▁hos ▁"% s ". ▁Te ta_ms pi ▁x screen sa_ms ver ▁mengu rus ▁papa ran ▁"% s " ▁yang_ms ▁dija lan_ms kan_ms ▁peng_ms guna ▁"% s " ▁pada_ms ▁hos ▁"% s ". ▁O leh ▁kerana , ▁peng_ms guna ▁yang_ms ▁ber_ms be za , ▁i_ms a ▁tidak_ms ▁akan_ms ▁memba ca_ms / menu lis ▁fail ▁~ / . x screen sa_ms ver ▁yang_ms ▁sama , ▁jadi ▁% s ▁tidak_ms ▁dapat_ms ▁ber_ms fung si_ms ▁dengan_ms ▁baik_ms ▁Anda_ms ▁se_ms pat ut_ms nya_ms ▁sama ▁ada_ms ▁jalan - sem ula ▁% s ▁sebagai ▁"% s ", ▁atau ▁jalan - sem ula ▁x screen sa_ms ver ▁sebagai ▁"% s ". ▁Mul a ▁sem_ms ula ▁ daemon ▁x screen sa_ms ver ▁sekarang ?
▁Anda_ms ▁melakukan ▁hal ▁anda !
▁Ia ▁hidup ...
▁dan_ms ▁mele ng_ms ahkan ▁masa_ms ▁mereka_ms
▁Saya_ms ▁adalah_ms ▁seorang_ms ▁yang_ms ▁tidak_ms ▁si_ms u man_ms .
▁- ▁Maaf ▁ag ak_ms ▁lama . ▁- ▁Tidak_ms .
▁Anda_ms ▁tahu_ms , ▁pen_ms ja_ms ra_ms ▁tidak_ms ▁sele sa_ms .
▁Saya_ms ▁perlu kan_ms ▁bantuan ▁ke_ms wanga n .
▁Aku_ms ▁sangat_ms ▁si_ms buk ▁sekarang ▁ni .
▁In gin ▁anda ▁O RA Â  Ã I Ã ▁  ▁E , ▁H AR RY !
▁Ayah ▁saya_ms , ▁dia_ms ▁beritahu ▁saya_ms ▁kalau ▁dia_ms ▁dah ▁han cur kan_ms ▁band ar_ms ▁ini_ms .
▁Kau_ms ▁gadis ▁yang_ms ▁baik_ms , ▁bukan_ms ?
▁Dia_ms m lah_ms ▁kau_ms , ▁How l ▁tak_ms ▁akan_ms ▁datang
▁Ia nya_ms ▁pe_ms lik_ms ▁untuk_ms ▁beritahu ▁perkara ▁ini_ms ▁pada_ms ▁diri_ms ▁sendiri , ... ... ... . ... ▁tapi . .
▁Dia_ms ▁nom bor ▁satu_ms ▁ki pas ▁gi la_ms .
▁Dan_ms ▁uma t ▁ti ap - ti_ms ap ▁Rasul ▁tidak_ms ▁ber_ms pe ca_ms h ▁be lah_ms ▁dan_ms ▁berse lisi han_ms ▁( dalam ▁men_ms ja_ms lan_ms kan_ms ▁u gama ▁Allah_ms ) ▁melainkan ▁setelah ▁sampai ▁kepada_ms ▁mereka_ms ▁aj aran - aj aran ▁yang_ms ▁memberi ▁mereka_ms ▁mengetahui ▁( apa_ms ▁yang_ms ▁dis uru h ▁dan_ms ▁apa_ms ▁yang_ms ▁di_ms lar ang_ms ); ▁berlaku nya_ms ▁( per sel isi han_ms ▁yang_ms ▁demikian ) ▁se_ms mata - mata ▁kerana ▁has ad ▁de_ms ng_ms ki_ms ▁ses ama ▁sendiri .
▁Peng guna an_ms : ▁% s ▁[ OPTION ] ... ▁[ ▁[ CHAR S ET ] ▁_ BAR _ ▁RE QUE ST ▁[ FILE ] ... ▁]
▁Bukan ▁ta mba han_ms .
▁Sa iz ▁Jack et ▁40 , ▁ fung si_ms ▁biasa ▁dan_ms ▁gi gi ▁yang_ms ▁baik_ms . ▁Apakah ▁kedua ▁terbaik ▁pe_ms main ▁te_ms nis ▁kole j ▁dari_ms ▁Amerika ▁S yari kat .
▁Ya_ms , ▁saya_ms ▁keluar ▁dari_ms ▁ku_ms mpu lan_ms ▁saya_ms .
▁Tapi_ms ▁saya_ms ▁sudah ▁ada_ms ▁kereta . .
▁- ▁Ini_ms ▁adalah_ms ▁ay am ▁ oren ▁yang_ms ▁cukup ▁baik_ms . ▁- ▁Ya_ms , ▁i_ms a ▁dari_ms ▁Chan g .
▁Bagaimana ▁kalau ▁saya_ms ▁meno lak ?
▁Da rah_ms ▁dan_ms ▁segala - gala nya_ms ?
▁Awak ▁dah ▁selesai kan_ms ▁peng_ms inti pan_ms ?
▁Maka ▁kes uda han_ms ▁kedua nya_ms , ▁bahawa ▁mereka_ms ▁dit emp atkan ▁di_ms ▁dalam_ms ▁ne raka , ▁ke_ms kal ▁mereka_ms ▁di_ms ▁dalam_ms nya_ms .
▁Ele an_ms or , ▁ketika ▁aku_ms ▁mengambil ▁sesuatu_ms ▁dari_ms ▁seseorang , ▁Kap al_ms nya_ms , ▁u ang_ms nya_ms , ▁ny awa nya_ms ,
▁- ▁Se_ms rius ▁tu_ms an_ms , ▁saya_ms ▁cuma ▁perlu kan_ms ▁loka si_ms .
▁Awak ▁dah ▁berse tu_ms ju ▁bertemu ▁dengan_ms ▁saya_ms .
▁- ▁Mereka ▁akan_ms ▁mul akan_ms ▁per_ms ang_ms .
▁Saya_ms ▁percaya ▁se_ms ku_ms mpu lan_ms ▁ni nja ▁dalam_ms ▁perjalanan ▁ke_ms ▁sini_ms .
▁- ▁Kalau ▁ba_ms lik_ms , to long ▁u cap ▁ter_ms ima ▁kasih ▁kepada_ms ▁Re ver end ▁Do w d ▁bagi ▁pi ha k ▁saya_ms .
▁Ada ▁banyak_ms ▁cara ▁saya_ms ▁boleh ▁lakukan_ms nya_ms .
▁- Di a ▁ba_ms ca_ms ▁blog ▁awak_ms .
▁Terima ▁kasih ▁kerana ▁pri hat in_ms .
▁- ▁Pre eti !
▁Link s ▁2
▁Sir , ▁saya_ms ▁menemukan ▁p ember on tak ▁9 ▁sektor .
▁Bah awa ▁baj ing_ms an_ms ▁bukan_ms ▁meng hen tak ▁wa_ms lau pun_ms ▁ber_ms ni lai ▁pada_ms
▁Adakah ▁anda ▁yakin ▁tidak_ms ▁ingin_ms ▁co ba_ms ▁sekolah ▁lain ?
▁Baiklah , ▁terus ▁berjalan .
▁Per anti
▁Apa_ms ▁imp ian ▁awak_ms ?
▁- ▁En . ▁L ung ren .
▁A kan_ms ▁lebih ▁heb at_ms ▁jika_ms ▁kawan - ka_ms wan ▁semua_ms ▁datang .
▁Kami_ms ▁hanya_ms ▁mendapat ▁li ma_ms ▁dan_ms ▁se_ms ten ga_ms h ▁mi nggu ▁sehingga ▁anda ▁me_ms la_ms wan ▁Bra ga_ms , ▁dan_ms ▁kami_ms ▁mendapat ▁banyak_ms ▁tan ah_ms ▁untuk_ms ▁membuat .
▁Se_ms baik ▁sahaja ▁ber_ms ke lip ▁nama ▁Che vali er ▁Si va ji ▁dalam_ms ▁ta juk ▁Anda_ms ▁akan_ms ▁mu la_ms ▁ter_ms es ak_ms - es ak_ms
▁Saya_ms ▁harus ▁ber_ms tu_ms kar ▁untuk_ms ▁parti .
▁Anda_ms ▁takut ▁ya , ▁penge cut ?
▁- ▁Aku_ms ▁ken cing ▁seluruh ▁per_ms mu_ms ka_ms annya .
▁U til iti ▁DE BI AN
▁Jangan , ▁Barry . ▁Kau_ms ▁akan_ms ▁selamat .
▁Apa_ms ▁yang_ms ▁boleh ▁buat ▁awak_ms ▁ke_ms kal ▁wara s ▁di_ms ▁sini_ms ▁?
▁Se_ms karan ▁saya_ms ▁hanya_ms ▁perlu ▁let akkan ▁dalam_ms ▁ini_ms ▁dan_ms ▁re bus kannya , ▁bukan_ms ?
▁Saya_ms ▁ada_ms ▁wa_ms wan cara ▁dengan_ms ▁ jir annya .
▁- ▁Ben da_ms ▁tu_ms ▁ber_ms fung si_ms ▁ke_ms ?
▁Eh , ▁Ko
▁Baiklah , ▁jadi , ▁dari_ms ▁se_ms gi ▁pe_ms mas aran ▁kita_ms ▁dapat_ms ▁men_ms jim atkan ▁ko s ...
▁Mereka ▁ menyu mbang kan_ms ▁sebuah ▁li lin ▁per_ms ak_ms ▁pada_ms ▁seorang_ms ▁anak ▁ya tim ▁di_ms ▁rumah ▁anak - anak ▁ya tim . ▁Itu_ms ▁sangat_ms ▁ indah !
▁W ang_ms ▁bukan_ms ▁masalah .
▁Ya_ms , ▁kamu_ms ▁semua_ms ▁dah ▁sa ksi kannya ?
▁Du it ▁mak ▁ada_ms ▁di_ms ▁dalam_ms , ▁jag a ▁baik_ms - baik .
▁Aku_ms ▁meny uru h nya_ms ▁untuk_ms ▁menunggu ▁di_ms ▁Ku il ▁Lo tus .
▁- ▁Itu_ms ▁mena rik ...
▁Sekarang ▁mereka_ms ▁sudah ▁lakukan_ms !
▁Saint ifik
▁Baik , ▁ba_ms lik_ms lah_ms ▁du lu_ms ...
▁Mereka ▁akan_ms ▁membuat mu_ms ▁ter_ms ken al_ms .
▁- ▁Ma ster ▁si_ms la_ms
▁K , ▁kamu_ms ▁tahu_ms , ▁20 ▁tahun ▁yang_ms ▁lalu ▁ibu ▁ba_ms pa_ms ▁my ▁ber_ms le pas ▁ke_ms ▁Lu ck now ▁pada_ms ▁hari ▁Bak ri ▁E id , ▁pen_ms er b angan_ms ▁mereka_ms ▁belum ▁men_ms ca_ms pai ▁lagi_ms ,
▁Ini_ms ▁meninggalkan ▁saya_ms ▁5 ▁tahun ▁yang_ms ▁lalu .
▁Hei , ▁Ray ? ▁Kenapa ?
▁Rasul ul lah_ms ▁telah_ms ▁beriman ▁kepada_ms ▁apa_ms ▁yang_ms ▁ditu run kan_ms ▁kepada_ms nya_ms ▁dari_ms ▁Tuhan nya_ms , ▁dan_ms ▁juga_ms ▁orang_ms - orang ▁yang_ms ▁beriman ; ▁semuanya ▁beriman ▁kepada_ms ▁Allah_ms , ▁dan_ms ▁Mala ikat - ma_ms la_ms ikat Nya , ▁dan_ms ▁Kitab - ki_ms tab Nya , ▁dan_ms ▁Rasul - ras ul Nya . ▁( M ere ka_ms ▁berkata ): ▁" Ka mi_ms ▁tidak_ms ▁me_ms mbe za kan_ms ▁antara ▁seorang_ms ▁dengan_ms ▁yang_ms ▁lain ▁Rasul - ras ul nya_ms ".
▁Font
▁- ▁Em ile ▁Ana fa no os ?
▁Mitchell , ▁ti nda kan_ms ▁pertama ▁ber_ms mu_ms la_ms .
▁Aku_ms ▁sudah ▁tengo k ▁semua_ms ▁papa ran ▁ke_ms se_ms lama tan_ms .
▁Anda_ms ▁tak_ms ▁mempunyai ▁ke_ms izi nan ▁di_ms per lu_ms kan_ms ▁untuk_ms ▁melihat ▁kan dung an_ms ▁bagi ▁"% s ".
▁Le ngan ▁saya_ms ▁adalah_ms ▁pada_ms ▁leng an_ms mu_ms .
▁Jag a ▁diri_ms ▁baik_ms - baik ▁Mit ten s .
▁Ber_ms mu_ms la_ms ▁dengan_ms ▁ber_ms bor ak_ms ▁dengan_ms ▁mereka_ms
▁Ke_ms mana ▁sahaja ▁itu_ms ▁bukan_ms ▁masalah ▁buat ▁saya_ms . ▁Hanya ...
▁Ya_ms , s aya ▁minta ▁semua_ms - akse s , ▁Jika ▁anda ▁akan_ms ▁pe_ms ep ▁la_ms mina ▁ini_ms , oka y ?
▁%.1 f ▁k H z
▁Tapi_ms , ▁dia_ms ▁tak_ms ▁pernah_ms ▁pun ▁berjaya ▁t angkap ▁apa_ms - apa_ms
▁Jadi , ▁ya , ▁kau_ms ▁membuat ku_ms ▁ter_ms ta_ms wa_ms , ▁tapi ▁itu_ms ▁tak_ms ▁cukup .
▁Itu_ms ▁akan_ms ▁lebih ▁membantu , ▁ter_ms ima ▁kasih ▁be ba_ms ny_ms ak_ms .
▁Na nas ▁yang_ms ▁ada_ms ▁di_ms ▁sini_ms , ▁Member ikan_ms ▁rasa ▁masa_ms m ▁dan_ms ▁rasa ▁mani s ▁dari_ms ▁Tim ur .
▁Bi ar_ms ▁saya_ms ▁ tunjukkan ▁siapa ▁si_ms ▁pena kut ▁itu_ms !
▁Ber_ms ca_ms kap ▁untuk_ms ▁diri_ms ▁sendiri .
▁Aku_ms ▁tahu_ms ▁dia_ms ▁ingin_ms ▁ka ki_ms ▁arna b ▁untuk_ms ▁ny awa ▁juli a .
▁Kalau ▁i_ms a ▁sampai ▁kepada_ms ▁polis , ▁hab is lah_ms ▁saya_ms .
▁Pas ti_ms ▁ada_ms ▁sebab ▁dia_ms ▁se_ms but ▁tentang ▁cinc in_ms ▁saya_ms , ▁Te d .
▁Ba lik_ms lah_ms ▁re hat .
▁tidak_ms ▁dapat_ms ▁ja na_ms ▁pri me ▁ kurang ▁dari_ms ▁% d ▁bit
▁Ha pus kan_ms ▁fail
▁Pa da_ms ▁masa_ms ▁ini_ms ▁saya_ms ▁sedang ▁di_ms tahan ▁oleh ▁ten tera ▁I raq ,
▁Aku_ms ▁ber_ms ja_ms nji ▁tidak_ms ▁akan_ms ▁berhenti ▁ber_ms u saha ▁bahkan ▁di_ms ▁hari ▁li bur ku_ms .
▁OK , ▁bere hat !
▁Kau_ms ▁tak_ms ▁tahu_ms ▁ra nc angan_ms ▁Tuhan .
▁Aku_ms ▁tak_ms ▁ber_ms maksu d ▁nak ▁bunu h ▁dia_ms !
▁Lo mpat an_ms ▁heb at_ms !
▁ Sesungguhnya ▁Kami_ms ▁telah_ms ▁pun ▁mener angkan ▁a_ms yat - a yat ▁ke_ms ter angan_ms ▁( yang ▁menjadi_ms ▁dal il ▁dan_ms ▁bu kti ) ▁kepada_ms ▁kau_ms m ▁yang_ms ▁mahu ▁percaya ▁dengan_ms ▁yakin .
▁Aku_ms ▁mengambil ▁itu_ms ▁dari_ms ▁se_ms pu pu ▁ket iga mu_ms ▁yang_ms ▁punya ▁to ko ▁elektron ik .
▁Tentu ▁ru mit ▁... ▁kau_ms ▁perlu ▁bere hat .
▁- ▁ke_ms ▁planet ▁lain .
▁A man_ms ... ?
▁Saya_ms ▁boleh ▁memang gil ▁dia_ms , ▁tetapi ▁saya_ms ▁don ' t - ▁yang_ms ▁ber_ms bun yi ▁seperti_ms ▁per_ms mul aan ▁yang_ms ▁baik_ms .
▁Ini_ms ▁Del ta_ms ▁98 4, ▁di_ms ▁sini_ms ▁berlaku ▁le tu_ms pan_ms , ▁kami_ms . .
▁Saya_ms ▁harus ▁memberitahu kan_ms ▁hal ▁itu_ms .
▁O leh ▁itu_ms , ▁jangan lah_ms ▁kamu_ms ▁menga_ms da_ms kan_ms ▁sesuatu_ms ▁yang_ms ▁se_ms band ing_ms ▁dengan_ms ▁Allah_ms , ▁kerana ▁sesungguhnya ▁Allah_ms ▁mengetahui ▁( se_ms ta_ms kat ▁mana_ms ▁buruk nya_ms ▁perbuatan ▁sy i rik ▁kamu_ms ) ▁sedang ▁kamu_ms ▁tidak_ms ▁mengetahui nya_ms .
▁Kami_ms ▁tak_ms ▁mengu mu_ms m kan_ms ▁orang_ms ▁hi lang_ms ▁sehingga ▁cukup ▁24 ▁jam , ▁tapi ▁de_ms mi_ms ▁Way ne ▁Enterprise s ...
▁untuk_ms ▁berhenti ▁se_ms ke tika ▁Saya_ms ▁ber_ms ta_ms nya_ms .
▁sha ru zza man_ms @ ▁my real box . ▁com
▁Yeah , ▁itu_ms ▁ lah_ms ▁C in_ms dy .
▁Sy e , ▁i_ms a ▁adalah_ms ▁okay .
▁Maaf , ▁kami_ms ▁tut up ▁untuk_ms ▁p ember si_ms han_ms .
▁Saya_ms ng_ms , ▁awak_ms ...
▁Per isti wa_ms ▁dija ng_ms ka_ms
▁Masa lah_ms nya_ms , ▁Ty , ▁saya_ms ▁faha m .
▁Data ng_ms ▁sem_ms ula ▁bila ▁kamu_ms ▁dah ▁besar .
▁Dia_ms ▁cakap ▁o tak mu_ms ▁seperti_ms ▁komputer .
▁Anda_ms ▁di_ms ▁dalam_ms ▁keadaan ▁ma buk .
▁Ke_ms tur un an_ms ▁Mann ▁ini_ms . . ▁mereka_ms ▁adalah_ms ▁kawan ▁lama ▁keluarga ▁saya_ms .
▁Dan_ms ▁pen_ms yang ga_ms han_ms .
▁Kes eron ok kan_ms !
▁Mari , ▁minu m ▁untuk_ms ▁si_ms ▁ayah .
▁Dia_ms ▁boleh ▁jadi ▁kawan ▁di_ms ▁a_ms cara ▁per_ms kah_ms win an_ms mu_ms .
▁Anda_ms ▁mahu ▁me_ms lat ih_ms ▁atau ▁anda ▁mahu ▁ber_ms gura u ?
▁Baiklah , ▁macam ▁ni .
▁Aku_ms ▁tahu_ms ▁kau_ms ▁boleh ▁lakukan_ms nya_ms .
▁Anna ▁dan_ms ▁aku_ms ▁sangat_ms ▁sen ang_ms ▁bersama - s ama .
▁Kita_ms ▁telah_ms ▁bekerja ▁untuk_ms ▁lakukan_ms
▁Saya_ms hara pa_ms wa_ms k da_ms pat me lihat ini .
▁Seperti ▁di_ms dalam ▁file m ▁apabila ▁seorang_ms ▁ayah ▁ber_ms lut ut_ms ▁di_ms ▁de_ms pan_ms ▁anak nya_ms ▁A nak nya_ms ▁akan_ms ▁ber_ms asa_ms ▁pe_ms ning
▁Awak ▁let akkan ▁saya_ms ▁betul - be tul ▁dalam_ms ▁loka p .
▁Se_ms mbu ny_ms i ▁du lu_ms ▁dan_ms ▁aku_ms ▁akan_ms ▁cari ▁kamu_ms ▁sele pas ▁semuanya ▁selesai .
▁Cum a ▁main an_ms .
▁Kemudian ▁ma kanlah ▁dari_ms ▁segala ▁je_ms nis ▁bu nga - bung aan ▁dan_ms ▁bu ah_ms - bu ahan ▁( yang ▁engkau ▁suka i ) , ▁ser ta_ms ▁tur ut_ms lah_ms ▁jalan - ja_ms lan_ms ▁per_ms atura n ▁Tuhan mu_ms ▁yang_ms ▁di_ms il ham kan_ms ▁dan_ms ▁di_ms mu_ms dah kannya ▁kepada_ms mu_ms ".
▁Saya_ms ▁rend ahkan ▁kamu_ms , ▁betul , ▁kan ?
▁Itu_ms ▁sebuah ▁peng_ms khi ana tan_ms . / ▁Dia_ms m lah_ms .
▁La lu_ms ▁be liau ▁berkata , ▁" bo leh ▁anda ▁hanya_ms ▁men_ms amba t ▁saya_ms ?"
▁Kau_ms ▁lu pa_ms , ▁ba_ms ha sa_ms ▁C ina ▁aku_ms ▁Lebih ▁baik_ms ▁dari_ms ▁ba_ms ha sa_ms ▁l ng_ms geri s .
▁Kamu ▁membuat ▁aku_ms ▁ker as .
▁Pen a mat ▁yang_ms ▁ge mbi ra_ms ?
▁Saya_ms ▁membawa ▁jen ama ▁kami_ms ▁kembali ▁dari_ms ▁antara ▁orang_ms ▁mati .
▁Sekarang ▁ini_ms ▁semua_ms ▁dah ▁berak hir .
▁- ▁Ge mbi ra_ms ▁bertemu ▁dengan_ms mu_ms .
▁Aku_ms ▁ingat ▁kita_ms ▁dah ▁se_ms las ai ▁tentang ▁tu_ms .
▁- ▁Awak ▁nak ▁cari ▁minu m ?
▁" T ing_ms gal kanlah ▁semua_ms ▁har a pan_ms , ▁siapa pun_ms ▁yang_ms ▁masuk ▁ke_ms ▁sini_ms ."
▁Itu_ms ▁sebab nya_ms ▁dia_ms ▁tidak_ms ▁pernah_ms ▁mene le fon ku_ms .
▁G n ect
▁Bis ing_ms ▁sangat_ms .
▁Saya_ms ▁cinta kan_ms ▁Stefan ▁se_ms panja ng_ms ▁masa_ms .
▁- ▁Saya_ms ▁nak ▁to long .
▁Kem ari lah_ms ▁atau ▁kau_ms ▁tidak_ms ▁akan_ms ▁aku_ms ▁ anggap ▁a_ms dik .
▁Untuk ▁itu_ms , ▁pa tik ▁ mohon ▁am pun_ms .
▁Saya_ms ▁akan_ms ▁bunu h ▁awak_ms , ▁anak ▁haram .
▁Kalau ▁tidak_ms , ▁Har le en ▁yang_ms ▁akan_ms ▁menang g ung ▁kes a kit annya .
▁_ I ndeks paper ▁size
▁ah li_ms ▁sihir ▁dari_ms ▁Sel atan .
▁Bi ar_ms ▁betul , ▁mereka_ms ▁ada_ms ▁senjata ▁a_ms pi !
▁Su mpah lah_ms ▁diri_ms ▁awak_ms , ▁su mpah lah_ms ▁kepada_ms ▁de_ms wa_ms - de wa_ms .
▁Ara han_ms ▁ RS ET ▁ga gal : ▁% s
▁Ny a man_ms ▁ nya_ms !
▁ Sesungguhnya ▁kami_ms ▁telah_ms ▁tinggal ▁dalam_ms ▁keadaan ▁yang_ms ▁mel ala ikan_ms ▁kami_ms ▁daripada ▁me_ms mi_ms kir kan_ms ▁perkara ▁ini_ms , ▁bahkan ▁kami_ms ▁telah_ms ▁menjadi_ms ▁orang_ms - orang ▁yang_ms ▁menga_ms nia ya ▁diri_ms ▁sendiri ".
▁Apa_ms ▁yang_ms ▁kamu_ms ▁fikir ▁tentang ▁P - 31 ?
▁Okay . ▁aku_ms ▁tidak_ms ▁apa_ms .
▁Program ▁ini_ms ▁adalah_ms ▁per_ms isi an_ms ▁be bas ; ▁anda ▁boleh ▁menge dar kan_ms ▁sem_ms ula ▁di_ms ba_ms wa_ms h ▁term a ▁GNU ▁General ▁Public ▁License ▁vers i ▁3 ▁atau ▁( pi li_ms han_ms ▁anda ) ▁vers i ▁ter_ms da_ms hulu . ▁Program ▁ini_ms ▁sama ▁sekali ▁tiada ▁memberikan ▁ja min an_ms .
▁Ke_ms can ti_ms kan_ms ▁kamu_ms ▁u mpa ma_ms ▁em as
▁Kenapa ▁tak_ms ▁cakap ▁apa_ms - apa_ms ?
▁Dia_ms ▁telah_ms ▁membunuh ▁semua_ms ▁mata ▁pela ja_ms ran .
▁Adakah ▁anda ▁fikir ▁mereka_ms ▁me_ms mah ami ▁apa_ms ▁yang_ms ▁aku_ms ▁katakan ?
▁Pen uh_ms ▁[ 25 ]
▁Terima ▁kasih .
▁Tidak_ms , ▁dan_ms ▁saya_ms ▁betul - be tul ▁tidak_ms ▁peduli .
▁- ▁Aku_ms ▁mahu ▁memiliki ▁sesuatu_ms ▁yang_ms ▁aku_ms ▁gun akan_ms .
▁Le tu_ms pan_ms ▁Gal a ksi !
▁Aku_ms ▁perlu ▁bi lik_ms ▁10 20 .
▁Oh ▁Ayah , ▁ada_ms ▁apa_ms ▁dengan_ms mu_ms !
▁itu_ms lah_ms ▁has il ▁ju alan ▁pu an_ms ▁Β l о ѕ ѕ о m .
▁Apa_ms ▁maksud ▁kamu_ms ?
▁Kamu ▁semua_ms ▁hanya_ms ▁makan ▁saja . ▁hanya_ms ▁orang_ms - orang ▁yang_ms ▁tak_ms ▁ber_ms guna ▁saja .
▁Ka rena , ▁tak_ms ▁boleh ▁ma bok ▁saat ▁menge mu_ms di_ms .
▁Pe mas ang_ms ▁De bug info ▁Pac ka_ms ge K it
▁Bila ▁ku_ms ▁memba nta h , ▁pe_ms luk lah_ms ▁aku_ms . .
▁Per min taan ▁ini_ms ▁tidak_ms ▁pernah_ms ▁di_ms ter ima .
▁Kita_ms ▁berada ▁dalam_ms ▁li f .
▁Ke_ms ba_ms nya_ms kan_ms ▁Industri es , ▁apa_ms ▁yang_ms ▁boleh ▁saya_ms ▁lakukan_ms ▁untuk_ms ▁anda ?
▁Tidak_ms ▁ada_ms ▁ker anda , ▁atau ▁plot , ▁i_ms a ▁benar - benar ▁sem_ms ula ▁jadi .
▁Ia ▁pa ng_ms gang ▁panta t ▁hai wan ▁kecil ▁anda , ▁si_ms la_ms .
▁Go P i , ▁dengar kan_ms ▁aku_ms !
▁Kem bali lah_ms ▁ke_ms ▁sana ▁dan_ms ▁ber_ms main .
▁- ▁Bila ▁kamu_ms ▁melihat nya_ms ?
▁Tidak_ms , ▁i_ms a ▁adalah_ms ▁beberapa ▁je_ms nis ▁he lah_ms .
▁Dan_ms ▁sebelum ▁me_ms layan i ▁ hukum an_ms ▁seu mur ▁hidup , ▁itu_ms ▁adalah_ms ▁ke_ms put us_ms an_ms ▁ha_ms kim ▁Ol af ▁di_ms bu at_ms ▁men_ms der ita ▁setiap ▁kes ul itan
▁Saya_ms ▁me_ms mah ami ▁bahawa
▁Tengo k lah_ms ▁apa_ms ▁yang_ms ▁jadi ▁ak hir nya_ms .
▁Mari ▁si_ms ▁kecil , ▁ jom ▁cari ▁Mama ▁kau_ms .
▁" Ta mu_ms ▁telah_ms ▁datang ▁dan_ms ▁a_ms pi ▁telah_ms ▁di_ms nya_ms la_ms kan_ms ."
▁se_ms baik ▁a_ms je ▁selamat , ▁Kita_ms ▁harus ▁gera k .
▁Awak ▁pernah_ms ▁na ik ▁kap al_ms ▁ter_ms bang ?
▁% s \ t \ t \ t P en anda t angan_ms ▁ OC SP .
▁Jangan ▁i_ms kut ▁cakap ▁dia_ms !
▁Te ta_ms pi ▁pe_ms mu_ms ja_ms an_ms ▁tu_ms an_ms ▁sahaja ▁boleh ▁me_ms mus n ahkan ▁Cha ndra mu_ms khi ▁se_ms pen uh_ms nya_ms .
▁Nama ▁kh as ▁@ DE FA UL T _ SIN K @ , ▁@ DE FA UL T _ S OUR CE @ ▁and ▁@ DE FA UL T _ M ONI TOR @ ▁boleh ▁digunakan ▁untuk_ms ▁ny ata kan_ms ▁sin ki_ms , ▁su m ber ▁dan_ms ▁monitor ▁la_ms lai .
▁Jess e , ▁anak ▁aku_ms .
▁Oh , ▁kata nya_ms ▁Anda_ms ▁benar - benar ▁cer dik , ▁Shell ey .
▁Tiada ▁siapa ▁yang_ms ▁di_ms p ang_ms gil ▁mereka_ms .
▁Tam b ahkan ▁ke_ms ▁Pro jek
▁Terima ▁kasih ▁kerana ▁lu angkan ▁masa_ms .
▁Media ▁tidak_ms ▁pernah_ms ▁di_ms peri ksa ▁lebih ▁tel iti , ▁bahawa ▁banyak_ms ▁daripada ▁para ▁pe_ms mi_ms mpi n ▁ini_ms ▁bagaimana ▁orang_ms ▁boleh ▁lo los .
▁Orang ▁yang_ms ▁up ah_ms ▁awak_ms ▁dia_ms ▁akan_ms ▁lakukan_ms ▁perkara ▁yang_ms ▁sama ▁pada_ms ▁awak_ms .
▁Mereka ▁semua_ms ▁ anggap ▁aku_ms ▁sebagai ▁lelaki .
▁- ▁Kami_ms ▁pun ▁dah ▁se_ms dia .
▁Hey , ▁saya_ms ▁akan_ms ▁mengambil ▁mereka_ms ▁dan_ms ▁me_ms let akkan ▁mereka_ms ▁di_ms ▁belakang ▁untuk_ms ▁anda .
▁Mac am ▁apa_ms , ▁Jim mie ?
▁Dengar ▁sini_ms , ▁ayah
▁Mar ty , ▁must a hil lah_ms .
▁Tan da_ms kan_ms ▁sebagai ▁_ P en ting
▁- ▁Ga dis ▁kas ar_ms , ▁bera mbu t ▁hita m .
▁& ▁Lihat
▁Kata ▁dia_ms , ▁tunggu ▁ke_ms wanga n ▁dia_ms ▁stabil ▁du lu_ms .
▁Dit er jem ahkan ▁oleh ▁Ha zu ka_ms ▁Him ura ... ▁Apa_ms ▁kai tan_ms ▁ nya_ms ▁dengan_ms ▁wata k ▁ut ama ▁ce rita ▁ini_ms ?
▁- ▁Em m . ▁-
▁Kenapa ?
▁Dia_ms ▁ber_ms hutan g ▁dengan_ms ▁saya_ms . ▁Maaf .
▁Kami_ms ▁berse dia ▁untuk_ms ▁memba yar ▁de_ms nda .
▁Tolong lah_ms ▁jangan ▁ber_ms kah_ms win , ▁Vi rat
▁Mungkin ▁dia_ms ▁bawah ▁nama ▁yang_ms ▁ber_ms be za .
▁Ini_ms ▁mi lik_ms ▁awak_ms , ▁ambil lah_ms .
▁Malcolm ▁jadi kannya ▁5, ▁tapi ▁sem_ms asa_ms ▁19 03 , ▁ada_ms ▁6 ▁orang_ms , ▁ber_ms mak na_ms ▁ada_ms ▁seorang_ms ▁lagi_ms .
▁Saya_ms ▁mahu ▁saya_ms ▁berada ▁di_ms ▁rumah .
▁Bo ome rang ▁yang_ms ▁can tik .
▁Dia_ms ▁ber_ms ja_ms nji , ▁jika_ms ▁aku_ms ▁sun yi ▁dia_ms ▁akan_ms ▁meng i rim ▁mala ikat ▁untuk_ms ▁me_ms me luk ▁aku_ms .
▁Kes eron ok kan_ms ▁sal uran ▁per_ms cu ma_ms ▁seperti_ms ▁imp ian ▁reng gang .
▁Kau_ms ▁nampak ▁tak_ms ▁bud ak_ms ▁ge mu_ms k ▁yang_ms ▁be lari ▁ka t ▁sini_ms ▁ta di_ms ?
▁Jangan ▁ber_ms lag ak_ms ▁bija k .
▁Be lum ▁se_ms mpat ▁kami_ms ▁ber_ms ka_ms bung ▁atas ▁kehilangan ▁anak ▁kami_ms , ▁mereka_ms ▁dah ▁men_ms ahan nya_ms . .
▁Jangan ▁mengatakan ▁saya_ms ▁tidak_ms ▁mendapat ▁lagi_ms .
▁Aku_ms ▁tak_ms ▁maksud kan_ms ▁makan an_ms .
▁A va tar ▁tu_ms ▁selamat ?
▁Kami_ms ▁ada_ms ▁untuk_ms ▁awak_ms .
▁Se_ms bab ▁aku_ms , ▁kau_ms ▁ter_ms le pas ▁dari_ms ▁pen_ms ja_ms ra_ms .
▁Saya_ms ▁u lat ▁ini_ms ?
▁Ke_ms pada ▁Allah_ms ▁ju a lah_ms ▁tempat ▁kembali ▁kamu_ms ▁semuanya , ▁kemudian ▁Ia ▁akan_ms ▁mener angkan ▁kepada_ms ▁kamu_ms ▁( bala san ) ▁apa_ms ▁yang_ms ▁kamu_ms ▁telah_ms ▁lakukan_ms .
▁Skri n ▁sent uh_ms .
▁Ini_ms kah_ms ▁Russia ?
▁Tapi_ms ▁jika_ms ▁i_ms a ▁tak_ms ... ▁ha_ms pus kannya .
▁Ia ▁adalah_ms ▁ha_ms dia h .
▁Data ng_ms ▁ke_ms ▁hospital ▁jam ▁3 :30 , ▁dan_ms ▁Vin , ▁jangan ▁ro sak kannya ▁lagi_ms .
▁Ya_ms ▁sayang , ▁aku_ms ▁disini .
▁Te ta_ms pi ▁parti ▁di_ms ▁London ▁yang_ms ▁besar .
▁- ▁O key - ▁- ▁o key - .
▁Eric a , ▁awak_ms ▁harus ▁bang ga_ms ▁pada_ms nya_ms .
▁Ya_ms , ▁saya_ms ▁salah ▁seorang_ms ▁dari_ms ▁mereka_ms .
▁Aku_ms ▁tak_ms ▁boleh ▁tahan ▁lagi_ms .
▁" R asa_ms ▁aman ▁ini_ms ."
▁Saya_ms ▁tak_ms ▁merasa i ▁sihir ▁pada_ms nya_ms .
▁Kau_ms ▁masih ▁mamp u ▁menga_ms lah_ms kan_ms ▁semua_ms ▁mereka_ms .
▁Saya_ms ▁tahu_ms ▁saya_ms ▁pat ut_ms ▁beritahu ▁kamu_ms , ▁tapi .
▁Mungkin ▁ta nya_ms ▁sebab ▁sakit ▁per_ms ut_ms .
▁A nak ▁lelaki ▁saya_ms .
▁Itu_ms ▁bis nes ▁haram , ▁To dd !
▁Ama tir ▁bodoh , ▁orang_ms ▁bodoh , ▁idiot !
▁Se_ms ja_ms uh_ms ▁yang_ms ▁saya_ms ▁tahu_ms , ▁mereka_ms ▁masih ▁lagi_ms ▁pen_ms jena yah .
▁Du nia ▁ini_ms ▁le lah_ms , ▁tapi ▁kami_ms ▁adalah_ms ▁kekuatan
▁This ▁guy ▁is ▁going ▁to ▁have ▁a_ms ▁lot ▁of ▁surveillance .
▁Re kod ▁polis ▁menunjukkan , ▁Ge ng_ms ▁Cu le bra ▁leng kap ▁berse nja ta_ms . .
▁" ▁Saya_ms ▁ke_ms bas ."
▁Ber_ms s ama ▁aku_ms ▁ada_ms ▁Kap ten ▁yang_ms ▁ter_ms ced era .
▁10 ▁saat ▁lagi_ms , ▁tu_ms an_ms .
▁U sah ▁bi mbang , ▁kita_ms ▁akan_ms ▁lin dung i ▁kau_ms
▁Saya_ms ▁akan_ms ▁menunjukkan ▁kepada_ms ▁anda !
▁sudah ▁pasti ▁kami_ms ▁telah_ms ▁mencari ▁ibu ▁ba_ms pa_ms ▁kamu_ms . ▁Pas ti_ms ▁kami_ms ▁telah_ms ▁cuba ▁mengha ntar ▁kamu_ms ▁kembali .
▁Ter ak_ms hir ▁kali ▁aku_ms ▁lakukan_ms ▁itu_ms .
▁Mr . ▁Pi bb ... ▁Ce laka .
▁Jika ▁ada_ms ▁seorang_ms ▁wanita ▁di_ms ▁keluarga ▁an gara ... ▁Mereka ▁akan_ms ▁su lit ▁menang an_ms inya .
▁- M ere ka_ms ▁orang_ms tua mu_ms ?
▁Dan_ms ▁di_ms ▁mana_ms ▁peng_ms hor ma_ms tan_ms ▁di_ms ▁meng khi ana ti_ms ▁rak yat nya_ms ▁sendiri ?
▁Short ie , ▁ingat ▁ren ca_ms na_ms ▁kita_ms .
▁Dan_ms ▁lakukan_ms ▁perkara ▁gi la_ms ▁yang_ms ▁orang_ms ▁lain ▁tak_ms ▁mungkin ▁lakukan_ms .
▁Keluar kan_ms ▁fail ▁sem_ms asa_ms ▁dari_ms ▁re posit ori
▁Saya_ms ▁di_ms ▁sini_ms ▁bersama ▁awak_ms . ▁Untuk ▁apa_ms ▁saya_ms ▁memang gil ▁awak_ms ?
▁Tiada ▁lagi_ms ▁tra ge di_ms ▁seperti_ms ▁ini_ms .
▁Apa_ms ▁lagi_ms , ▁a_ms bang ?
▁Kata ▁Kun ci ▁XMP .
▁Sudah ▁menjadi_ms ▁perkara ▁biasa ▁bagi ▁seseorang ▁untuk_ms ▁meninggalkan ▁aman ah_ms ▁anda i ▁kata ▁bak al_ms ▁terjadi ▁pen_ms jel maan ▁sem_ms ula .
▁Wal au pun_ms ▁per_ms bin c angan_ms ▁di_ms ▁luar ▁ca ta_ms tan_ms ?
▁La mpi ran ▁tidak_ms ▁menga_ms n dung i ▁mes ej ▁kal en dar ▁yang_ms ▁sah
▁Kamu ▁akan_ms ▁selamat .
▁Dengar , ▁saya_ms ▁akan_ms ▁ rela kan_ms ▁ny awa ku_ms ▁de_ms mi_ms ▁men_ms ja_ms ga_ms ▁ke_ms se_ms lama tan_ms mu_ms .
▁Itu_ms ▁per_ms be za an_ms ▁antara ▁su ks es ▁dan_ms ▁ga gal .
▁Dengar , ▁saya_ms ▁juga_ms ▁mencari ▁War d .
▁Aku_ms ▁mendapatkan ▁sedikit ...
▁" Se se_ms orang ▁telah_ms ▁menggunakan ▁telefon ▁awak_ms ."
▁Isi h ▁Men a ik
▁Per ge langan ▁tangan ▁pat ah_ms .
▁Ay uh_ms !
▁Oh , ▁jangan ▁bi mbang , ▁A lain !
▁Pi s au ▁bela ti_ms ▁ini_ms ▁untuk_ms ▁apa_ms ?
▁Aku_ms ▁takut ▁aku_ms ▁mungkin ▁berak hir ▁dengan_ms ▁sakit ▁ha_ms ti_ms .
▁Kamu ▁baik_ms - o key ?
▁Tapi_ms , ▁saya_ms ▁tahu_ms ▁ayah lah_ms ▁di_ms ▁se_ms ba_ms lik_ms nya_ms .
▁- ▁54 82 . ▁- ▁Ya_ms ?
▁kamu_ms ▁ingin_ms ▁tahu_ms ▁apa_ms ▁yang_ms ▁berlaku ▁antara ▁aku_ms ▁dan_ms ▁Matt y ?
▁Ya_ms , ▁se_ms la_ms gi ▁awak_ms ▁tidak_ms ▁berada ▁di_ms ▁panta inya , ▁boleh ▁saja .
▁Hy ung ▁sudah ▁ber_ms su sah - pa_ms yah ▁bekerja ▁se_ms mata - mata ▁mahu ▁mengha ntar ▁saya_ms ▁ke_ms ▁sekolah .
▁Kami_ms ▁telah_ms ▁di_ms lat ih_ms ▁apabila ▁pe_ms mand u ▁telah_ms ▁me_ms mand u ▁la_ms ju , ▁untuk_ms ▁mendapatkan ▁se_ms benar ▁ra pat ▁dan_ms ▁kemudian ▁menga_ms k tif kan_ms ▁la_ms mpu ▁me_ms rah_ms ▁dan_ms ▁bir u .
▁Dia_ms m lah_ms , ▁En zo .
▁Kemudian ▁bagaimana ▁cinta ▁nak ▁berjaya ?
▁Bagaimana , ▁Emily ?
▁Mana ▁tahu_ms ▁jika_ms ▁ada_ms ▁pintu ▁belakang .
▁Saya_ms ▁tak_ms ▁ada_ms ▁cakap ▁apa_ms - apa_ms . ▁Tapi_ms ▁saya_ms ▁boleh ▁cakap ▁dengan_ms ▁dia_ms ▁kalau ▁kamu_ms ▁mahu .
▁Tapi_ms ▁kau_ms ▁pil ih_ms ▁Mak , ▁bukan_ms ▁aku_ms ...
▁Terima ▁kasih , ▁tetapi ▁saya_ms ▁akan_ms ▁cuba ▁dan_ms ▁melakukan ▁pen_ms ul isan ▁sem_ms asa_ms ▁dia_ms ▁sedang ▁tidur .
▁Ia ▁ paka ian .
▁Su sah ▁di_ms den gar ▁kalau ▁kau_ms ▁ber_ms teri ak_ms .
▁Max , ▁und ur ▁per_ms lah_ms an_ms - lah_ms an_ms .
▁Ten dang ▁lagi_ms !
▁Kami_ms ▁harus ▁pergi_ms ▁apabila ▁kamu_ms ▁sedang ▁me_ms mer hati kan_ms
▁" B ible ▁saya_ms ▁Per le mba gaan "?
▁- ▁C enda wan ▁sem_ms ing_ms gu ▁sebelum .
▁Da lam ▁kes ▁ini_ms , ▁saya_ms .
▁S yar at_ms ▁saya_ms ▁hanya_ms lah_ms ▁dia_ms ▁perlu ▁ha_ms dir ▁lagi_ms ▁untuk_ms ▁meny aks ikan_ms ▁awak_ms ▁menga_ms ku_ms ... ▁pada_ms ▁kesalahan ...
▁Ber_ms hati - hati ▁ , ▁ayah .
▁Cum a ▁sedikit ▁bera t .
▁Baiklah , ▁mari ▁saya_ms ▁to long .
▁Baiklah , ▁hidup kan_ms ▁en jin !
▁Awak ▁telah_ms ▁membunuh ▁musu h ▁dia_ms ... ▁dan_ms ▁juga_ms ▁per_ms asa_ms an_ms ▁sy ak_ms ▁was angkan ya .
▁- ▁N isha , ▁dia_ms m !
▁Pe gang ▁be g ▁itu_ms , ▁bodoh .
▁Lu pa_ms kan_ms ▁kereta ▁dia_ms . ▁Lu pa_ms kan_ms ▁semua_ms ▁tu_ms .
▁Adakah ▁kamu_ms ▁pernah_ms ▁pergi_ms ▁ke_ms ▁aka de mi_ms ▁per_ms tu_ms tur an_ms ?
▁Ia ▁akan_ms ▁hi lang_ms ▁se_ms ba_ms ny_ms ak_ms ▁saya_ms , ▁jadi ▁i_ms a ▁adalah_ms ▁sem_ms pur na_ms .
▁Saya_ms ▁tak_ms ▁suka ▁menge ce wa_ms kan_ms ▁kamu_ms ▁tapi ▁di_ms ▁sini_ms lah_ms ▁habit at_ms ▁sem_ms ula ja_ms di_ms ▁kita_ms .
▁Kau_ms ▁tak_ms ▁tahu_ms ▁pun ▁apa_ms ▁ha_ms jat ▁aku_ms ...
▁Ber_ms si_ms ul , ▁Aku_ms ▁berjalan ▁menge jar mu_ms
▁Ba a hu bali ▁perlu ▁di_ms bun uh_ms
▁E p son ▁S ty lus ▁T X 4 10
▁Jika ▁anda ▁masih ▁mahu ▁makan , ▁minta ▁kas ta_ms ▁kami_ms ▁makan ▁du lu_ms
▁25 ▁ki lo ▁itu_ms ▁adalah_ms ▁rang ka_ms ian ▁ke_ms se_ms lama tan_ms ▁aku_ms .
▁Ta han_ms ▁Te s oro !
▁je_ms nis ▁fail ▁tak_ms ▁di_ms keta hui ▁% s
▁Terima ▁kasih , ▁Mor o es .
▁Kel aju an_ms ▁ISO ▁berubah
▁Ker ana ▁tu_ms an_ms ▁pu teri ▁meno lak ▁la_ms mar annya , ▁dia_ms ▁telah_ms ▁memberi ▁ arahan ▁kerana ▁ma rah_ms
▁Tak_ms ▁masalah , ▁kau_ms ▁pergi_ms lah_ms , ▁jangan ▁kh awa tir kan_ms ▁aku_ms .
▁Bi ar_ms ▁betul !
▁Dia_ms ▁bukan_ms ▁per_ms isi k ▁India .
▁Saya_ms ▁menga_ms na_ms lisi s ▁za rah_ms ▁ini_ms ▁Bah awa ▁C lay Par ker ▁dan_ms ▁Shaw na_ms ▁Ba ez ▁ket ing_ms ga_ms lan_ms , ▁dan_ms ▁saya_ms ▁telah_ms ▁men_ms jum pai ▁sesuatu_ms ▁yang_ms ▁sangat_ms ▁mena rik .
▁Ia ▁tidak_ms ▁ber_ms tu_ms kar ▁jadi ▁apa_ms - apa_ms , ▁Ia ▁hanya_ms ▁bar angan_ms ▁kole ksi , ▁ibu .
▁1 64 ▁x ▁1 64
▁l mpe rial ▁Je pun_ms ▁tidak_ms ▁akan_ms ▁meninggalkan ▁kamu_ms !
▁Dan_ms ▁bera tus ▁anak ▁mu da_ms ▁yang_ms ▁ber_ms har ga_ms ▁masih ▁hidup ▁su sah ▁di_ms ▁jalan an_ms .
▁Saya_ms ▁rasa ▁awak_ms ▁perlu ▁buat ▁pilihan .
▁Kur angkan ▁bercakap .
▁Se_ms te lah_ms ▁Na bi ▁meny ata kan_ms ▁hal ▁itu_ms ▁kepada_ms ▁ ister inya , ▁ ister inya ▁ber_ms ta_ms nya_ms : ▁" Si apa_ms kah_ms ▁yang_ms ▁memberi ▁tahu_ms ▁hal ▁ini_ms ▁kepada_ms ▁tu_ms an_ms ? ▁"
▁- ▁Be tul , ▁i_ms a ▁hanya_ms ▁saya_ms ▁dapat_ms ▁...
▁Ke_ms tika ▁dia_ms ▁mening gal , ▁saya_ms ▁ada_ms ▁ke_ms wa_ms ji ban ▁untuk_ms ▁mener us_ms kan_ms ▁mi lik_ms nya_ms ▁seperti_ms ▁kamu_ms .
▁Sub s ▁oleh :
▁Bukan kah_ms ▁lebih ▁mu dah ▁untuk_ms ▁me_ms mas u ki_ms ▁di_ms ▁sebe lah_ms ?
▁Jadi ▁kenapa ▁war ta_ms wan ▁tempat an_ms ▁seperti_ms ▁awak_ms ▁ter_ms ta_ms rik ▁pada_ms ▁kes ▁sebe gin i ?
▁Dan_ms ▁siapa kah_ms ▁lagi_ms ▁yang_ms ▁lebih ▁ani aya ▁dari_ms ▁orang_ms ▁yang_ms ▁menga_ms da_ms - ada kan_ms ▁perkara - per kara ▁yang_ms ▁du sta ▁terhadap ▁Allah_ms , ▁atau ▁yang_ms ▁mend usta kan_ms ▁a_ms yat - a yat ▁ke_ms ter angan_ms Nya ?
▁Be liau ▁adalah_ms ▁salah ▁satu_ms ▁yang_ms ▁akan_ms ▁membawa ▁ke_ms gem bir aan ▁kepada_ms ▁kehidupan ▁anak ▁saya_ms .
▁Kau_ms ▁jadi ▁seperti_ms ▁ayah mu_ms .
▁Rich ie , ▁ini_ms lah_ms ▁yang_ms ▁saya_ms ▁akan_ms ▁buat ▁untuk_ms ▁kamu_ms .
▁Hent ikan_ms , ▁Mer lyn .
▁Bagaimana ▁aku_ms ▁mel up akan_ms ▁orang_ms ▁yang_ms ▁begitu ▁heb at_ms
▁Saya_ms ▁sangat_ms ▁ber_ms du_ms ka_ms ▁atas ▁keluarga ▁awak_ms ...
▁Kau_ms ▁boleh ▁sur uh_ms ▁aku_ms ▁dia_ms m ▁tapi ▁kau_ms ▁tak_ms ▁boleh ▁ha_ms lang_ms ▁aku_ms ...
▁cuba ▁un tak ▁menu n juk ▁lag ak_ms kah_ms ?
▁- ▁Itu_ms ▁adalah_ms ▁ce rita ▁besar .
▁Wal au pun_ms ▁siapa ▁tahu_ms , ▁mungkin ▁kali ▁ini_ms ▁kita_ms ▁akan_ms ▁bela jar .
▁Be liau ▁mahu ▁bertemu ▁dengan_ms ▁anda .
▁Sen ja_ms ta_ms ▁akan_ms ▁di_ms han_ms tar ▁ke_ms ▁U tara ▁Ur k ▁pat a ▁te_ms nga h ▁malam .
▁Well , itu ▁adalah_ms ▁van ▁yang_ms ▁pergi_ms ▁Jika ▁anda ▁tidak_ms ▁jalan ▁ke_ms ▁bawah ▁dengan_ms ▁per_ms kata an_ms ▁yang_ms ▁me_ms ros akkan .
▁Aku_ms ▁tak_ms ▁pernah_ms ▁bi ar_ms ▁dia_ms ▁ke_ms lap aran .
▁Dan_ms ▁saya_ms ▁har ap ▁ini_ms ▁hanya_ms ▁waktu ▁di_ms ▁mana_ms ▁dia_ms ▁salah ▁membuat ▁ke_ms put us_ms an_ms , ▁dan_ms ▁bukan_ms ▁seperti_ms ▁cinta .
▁Okay , ▁maka ▁di_ms ▁mana_ms ▁kita_ms ▁akan_ms ▁pergi_ms ▁ke_ms ▁mana_ms ?
▁Ri je ka_ms
▁Ke_ms ta_ms hui lah_ms ! ▁Sem asa_ms ▁mereka_ms ▁ber_ms sel ubung ▁dengan_ms ▁ paka ian ▁mereka_ms ▁sekali pun_ms , ▁Allah_ms ▁mengetahui ▁apa_ms ▁yang_ms ▁mereka_ms ▁se_ms mbu ny_ms ikan_ms ▁dan_ms ▁apa_ms ▁yang_ms ▁mereka_ms ▁za hir kan_ms ; ▁sesungguhnya ▁Ia ▁Maha ▁Men ge ta_ms hui ▁akan_ms ▁segala ▁( isi ▁ha_ms ti_ms ) ▁yang_ms ▁ada_ms ▁di_ms ▁dalam_ms ▁da da_ms .
▁Oliver , ▁kamu_ms ▁juga_ms .
▁aku_ms ▁sangat_ms ▁ma rah_ms ▁dan_ms ▁cuba ▁menga_ms n cam ▁a_ms gar ▁pe_ms ny_ms eli dika nku ▁boleh ▁ku_ms sam bung .
▁Di bela kan_ms g ▁air - con , ▁ada_ms ▁beberapa ▁ AK ,
▁- Ju mpa ▁lagi_ms ▁ge mu_ms k .
▁Jangan ▁salah ▁gun akan_ms ▁kekuatan ▁awak_ms .
▁Baiklah .
▁Anda_ms ▁tidak_ms ▁perlu ▁untuk_ms ▁me_ms lib atkan ▁diri_ms ▁be liau
▁Dan_ms ▁seperti_ms ▁yang_ms ▁kamu_ms ▁kata ▁kamu_ms ▁selamat .
▁Bu dak ▁baik_ms .
▁Dan_ms ▁kata nya_ms , ▁Pra y ?
▁Su atu ▁pe_ms tang , ▁beberapa ▁cal on ▁me_ms lan_ms tik ▁saya_ms ▁untuk_ms ▁go long an_ms ▁pe_ms nya_ms ir , ▁kerana ▁saya_ms ▁baru ▁saja ▁me_ms men ang_ms inya ▁...
▁Itu_ms ▁sangat_ms ▁must a hil , ▁sayang .
▁Ro x anne , ▁ini_ms ▁adalah_ms ▁Ibu ▁saya_ms
▁Ye ong ▁Do . ▁o key kah_ms ?
▁Jangan , ▁nak , ▁masuk lah_ms .
▁Saya_ms ▁senti asa_ms ▁mengha r gai ▁per_ms saha ba_ms tan_ms ▁kita_ms ▁dan_ms ▁senti asa_ms ▁mengingat i ▁awak_ms ... ▁dengan_ms ▁ingat an_ms ▁yang_ms ▁ indah , ▁per_ms asa_ms an_ms ▁yang_ms ▁tu_ms lus ▁dan_ms ▁is time wa_ms .
▁Dan_ms ▁saya_ms ▁to long ▁menye les ai kannya !
▁Bila ▁si_ms alan ▁itu_ms ▁masuk , ▁aku_ms ▁nak ▁dengar ▁te_ms mba kan_ms , ▁dan_ms ▁aku_ms ▁nak ▁dengar ▁" Sa s aran ▁di_ms mus n ahkan ".
▁Ga gal ▁men_ms ca_ms pai ▁kan dung an_ms ▁ime j ▁%( image ) s .
▁_ T eks ▁sebe lah_ms ▁ikon
▁Aku_ms ▁nak ▁cakap ▁' A ku_ms ▁cinta kan_ms ▁kau_ms ' !
▁Oh , ▁Tuhan , ▁li mo ▁ini_ms ▁begitu ▁o bat ▁bi us_ms , ▁du de .
▁Siapa ▁jumpa , ▁dia_ms ▁punya . .
▁Kau_ms ▁dah ▁ada_ms ▁kehidupan ▁yang_ms ▁baik_ms .
▁Jika ▁Gab bar ▁tahu_ms , ▁Saya_ms ▁akan_ms ▁di_ms hukum .
▁Mas ih_ms ▁ada_ms ▁yang_ms ▁belum ▁datang .
▁Kamu ▁juga_ms ▁kata ▁mahu ▁menggunakan ▁sera gam ▁Red ha w ks .
▁Ayah ▁Ge eta ▁dan_ms ▁Ba bit a ▁Kuma ri ▁dan_ms ▁se_ms pu pu ▁ra pat nya_ms .
▁Ke_ms hi du_ms pan_ms ▁dia_ms ▁bagus , ▁kan ▁?
▁Awak ▁se_ms dar ▁tak_ms ▁yang_ms ▁dia_ms ▁tak_ms ▁pernah_ms ▁berhenti ▁melihat ▁diri_ms ▁awak_ms .
▁- ▁Tidak_ms ▁perlu ▁di_ms ba_ms wa_ms ▁ke_ms ▁sud ut_ms .
▁Dia_ms ▁terlalu ▁kecil .
▁Kau_ms ▁ba_ms wa_ms ▁aku_ms ▁ke_ms ▁sini_ms ▁dan_ms ▁tinggal kan_ms ▁aku_ms .
▁- A kan_ms ▁ku_ms ▁ja uhkan ▁dari_ms mu_ms .
▁Aku_ms ▁tak_ms ▁jumpa ▁apa_ms - apa_ms ▁pun .
▁- ▁Leon id ▁Sa vy ch , ▁tak_ms ▁perlu .
▁Band ar_ms ▁Ayo dh ya
▁Dia_ms ▁cakap ▁masuk !
▁Saya_ms ▁di_ms per ta_ms nggu ng_ms ja_ms wa_ms b kan_ms ▁ke_ms ▁atas ▁kamu_ms .
▁Muka nya_ms ▁can tik ▁itu_ms ▁memang ▁pasti ▁Tapi_ms ▁begitu ▁juga_ms ▁ra mai ▁pela cur ▁lain ▁di_ms ▁sini_ms
▁Ber_ms an_ms inya ▁lu pa_ms ▁status mu_ms ▁untuk_ms ▁meminta ▁Yang ▁Mul ia ▁menye rah_ms ▁begitu ▁saja ?
▁Pa _ dam ▁% s
▁Saya_ms ▁datang ▁ber_ms la_ms wan ▁de_ms mi_ms ▁kawan .
▁Apa_ms ▁yang_ms ▁kamu_ms ▁cuba ▁untuk_ms ▁me_ms mbu kti kan_ms , ▁Sur ly ?
▁- ▁Tak_ms , ▁Lisa , ▁tunggu .
▁P US ING AN ▁ AK H IR ▁Sa tu_ms ▁pus ing_ms an_ms ▁lagi_ms ▁dan_ms ▁Mc Que en ▁jauh ▁di_ms ▁de_ms pan_ms .
▁Opera si_ms
▁Yang ▁penting , ▁ce rita mu_ms ▁akan_ms ▁tetap ▁hidup ▁di_ms dalam ▁diri_ms nya_ms .
▁Bo do h ▁... ▁ja lang_ms .
▁ Sesungguhnya ▁orang_ms - orang ▁yang_ms ▁memba nta h ▁mengenai ▁maksud ▁a_ms yat - a yat ▁Tuhan mu_ms ▁dengan_ms ▁tidak_ms ▁ber_ms das ar_ms kan_ms ▁se_ms bar ang_ms ▁bu kti ▁yang_ms ▁sampai ▁kepada_ms ▁mereka_ms ▁( dari ▁pi ha k ▁yang_ms ▁dia_ms ku_ms i ▁benar nya_ms ) , ▁tidak_ms ▁ada_ms ▁dalam_ms ▁da da_ms ▁mereka_ms ▁melainkan ▁per_ms asa_ms an_ms ▁mahu kan_ms ▁ke_ms bes aran ▁( untu k ▁menga_ms tas i mu_ms ) , ▁ke_ms mah uan ▁yang_ms ▁mereka_ms ▁tidak_ms ▁sekali - kali ▁akan_ms ▁dapat_ms ▁men_ms ca_ms pa_ms inya .
▁tidak_ms ▁dapat_ms ▁ci pta ▁so ket ▁D H CP ▁B PF : ▁% s
▁Saya_ms ▁rasa ▁saya_ms ▁menunggu ▁sesuatu_ms ▁yang_ms ▁luar ▁biasa .
▁Baby ▁Fa ti_ms ma_ms , ▁tak_ms ▁aku_ms ▁sang ka_ms .
▁Ta hni ah_ms , ▁Anda_ms ▁menjadi_ms ▁sar jan
▁Mi lik_ms ▁pe_ms gua m ▁atau ▁doktor ?
▁Dia_ms ▁menggunakan ▁gara m ▁la_ms ut_ms ▁untuk_ms ▁mene balk an_ms ▁ku_ms lit , ▁supaya ▁dapat_ms ▁men_ms ahan ▁pu ku_ms lan_ms ▁yang_ms ▁lebih ▁lama .
▁Se_ms mbu ny_ms ikan_ms ▁_ Me s ej ▁yang_ms ▁Di pada m
▁Baiklah . ▁cakap ▁berhenti , ▁kalau ▁kau_ms ▁lihat ▁sesuatu_ms ▁yang_ms ▁kau_ms ▁suka .
▁Mari lah_ms ▁Mi riam , ▁jangan ▁jadi ▁pena kut .
▁Ia ▁benar - benar ▁kamu_ms .
▁- x ▁n , ▁-- n th ▁n ▁Ma in_ms kan_ms ▁setiap ▁blok ▁ke_ms - n
▁Ama t ▁suka r ▁untuk_ms ▁dik esan , ▁must a hil ▁untuk_ms ▁dira mal .
▁Chris ▁Ryan ▁ma lah_ms ▁me_ms lut ut_ms .
▁Saya_ms ▁telah_ms ▁melakukan ▁sedikit ▁saya_ms ▁ber_ms tin dak ▁untuk_ms ▁anda .
▁Ku ▁har ap ▁tidak_ms , ▁En .
▁Dan_ms ▁anda ▁tidak_ms ▁tahu_ms ▁sama ▁ada_ms ▁dia_ms ▁akan_ms ▁i_ms a itu -
▁- ▁Ya_ms , ▁dia_ms ▁cer dik . ▁Dia_ms ▁yang_ms ▁selamat kan_ms ▁kami_ms .
▁Saya_ms ▁hanya_ms ▁i_ms kut ▁ arahan ▁pe_ms mi_ms lik_ms ▁saya_ms
▁O key , ▁saya_ms ▁perlu ▁pergi_ms ▁ke_ms ▁sana .
▁Hei , ▁parti ▁itu_ms .
▁Kenapa ?
▁En ci k ▁Whi ta_ms ker , ▁yang_ms ▁hal us_ms .
▁Tak_ms ▁boleh ▁me_ms mu_ms atkan ▁ring kas an_ms ▁bagi ▁% s
▁Se_ms o lah_ms - o lah_ms ▁orang_ms - orang ▁Jer man_ms ▁masih ▁belum ▁melihat ▁i_ms a ▁dari_ms ▁atas .
▁Su sah ▁nak ▁hidup kannya ▁kembali
▁Di ▁sini_ms , ▁En ci k ▁De ng_ms .
▁Aku_ms ▁rasa ▁lebih ▁baik_ms ▁kau_ms ▁ber_ms ga_ms bung ▁dengan_ms ▁kami_ms ▁apabila ▁kerja ▁kau_ms ▁dah ▁selesai .
▁mengg eli tik !
▁Se_ms ti_ms dak nya_ms ▁ada_ms ▁8 ▁tahan an_ms ▁yang_ms ▁ber_ms ta_ms nggu ng_ms ja_ms wa_ms b ▁untuk_ms ▁itu_ms .
▁Selamat ▁tinggal , ▁si_ms put ▁kecil .
▁Kita_ms ▁dapat_ms ▁per_ms ger akan_ms .
▁Se_ms si_ms apa_ms ▁yg ▁ingin_ms ▁sent uh_ms ▁kau_ms ?
▁Me ma_ms ng_ms , ▁kau_ms ▁tak_ms ▁dapat_ms ▁h ubung i ▁dia_ms !
▁Jika ▁seperti_ms ▁ini_ms ...
▁Dan_ms ▁apabila ▁Kami_ms ▁ber_ms i ▁manusia ▁merasa i ▁sesuatu_ms ▁ rah_ms mat , ▁mereka_ms ▁ber_ms ge mbi ra_ms ▁dengan_ms nya_ms ▁( se_ms hin gga ▁lu pa_ms ▁dara tan_ms ); ▁dan_ms ▁jika_ms ▁mereka_ms ▁di_ms ti_ms mpa ▁sesuatu_ms ▁ben ca_ms na_ms ▁di_ms se_ms bab kan_ms ▁apa_ms ▁yang_ms ▁telah_ms ▁dilakukan ▁oleh ▁tangan ▁mereka_ms ▁sendiri , ▁ti ba_ms - ti_ms ba_ms ▁mereka_ms ▁ber_ms put us_ms ▁asa .
▁Bagaimana ▁kalau ▁Taylor ▁adalah_ms ▁bu kti ▁yang_ms ▁kau_ms ▁perlu kan_ms ?
▁Hanya ▁mereka_ms ▁boleh ▁ber_ms ko ng_ms si_ms ▁ke_ms ajai ban ▁Tuhan .
▁Lebih ▁baik_ms ▁aku_ms ▁tinggal kan_ms ▁band ar_ms .
▁Ker ja_ms ▁cepat . ▁Kami_ms ▁dalam_ms ▁perjalanan .
▁Tidak_ms ▁jika_ms ▁tiada ▁pas aran ▁yang_ms ▁ingin_ms ▁men_ms ju al_ms nya_ms .
▁Adakah ▁ke_ms per ca_ms ya an_ms ▁dari_ms mu_ms , ▁cinta .
▁Gu ra_ms u ▁saja ▁.. He i , ▁apa_ms ▁ini_ms ▁dengan_ms ▁be zel ▁yang_ms ▁ada_ms ▁disini ?
▁- ▁Kem bali ▁ke_ms ▁Sy ur ga_ms , ▁ku_ms kira .
▁Ayah , ▁berse dia .
▁La lu_ms ▁Bu gs ▁ ck p , ▁" E h , ▁kenapa ▁kau_ms ▁menu angkan ▁mi ny_ms ak_ms ▁di_ms ▁kepala ku_ms ?"
▁* ▁Aku_ms ▁tak_ms ▁mahu ▁kau_ms ▁meninggalkan ku_ms ▁*
▁Se_ms gala nya_ms ▁ok
▁Pu sat ▁internet ▁dunia ▁di_ms ▁Os lo .
▁Tapi_ms ▁apa_ms ▁yang_ms ▁saya_ms ▁tahu_ms ▁sekarang ▁Itu_ms ▁( Be cker ) ▁mahu , ▁Ma ti_ms ▁dan_ms ▁tidak_ms ▁akan_ms ▁ke_ms ber atan ▁kalau ▁kita_ms ▁membunuh ▁dia_ms ▁juga_ms
▁Joe , ▁apa_ms ▁yang_ms ▁kau_ms ▁har apkan ▁kami_ms ▁nak ▁buat , ▁kawan ?
▁Band uan ▁pada_ms ▁ja ng_ms ka_ms ▁telah_ms ▁dik esan ▁dalam_ms ▁platform ▁6, ▁i_ms a ▁adalah_ms ▁dengan_ms ▁seorang_ms ▁lelaki .
▁Saya_ms ▁me_ms mbe li_ms ▁bahagia n ▁untuk_ms ▁Ra bbi t .
▁Ju ru tek nik ▁tak_ms ▁ guna .
▁Saya_ms ▁me_ms nger ja_ms kan_ms ▁itu_ms ▁untuk_ms ▁diri_ms ▁saya_ms ▁sendiri .
▁Anda_ms ▁ken al_ms ▁lelaki ▁Bon d , ▁inte l ▁lelaki
▁Ra tu_ms ▁hita m .
▁Con to h : ▁se_ms bol @ ja_ms b ber . org
▁Kami_ms ▁ter_ms lu_ms pa_ms ▁yang_ms ▁kamu_ms ▁ialah ▁Po oja , ▁dan_ms ▁kamu_ms ▁ada_ms ▁kehidupan ▁per_ms iba di_ms ▁kamu_ms . . ▁.. ▁dan_ms ▁h ubung an_ms ▁dan_ms ▁kom it men ▁yang_ms ▁lebih ▁penting
▁Se_ms kali ▁lagi_ms ! ▁100 ! ▁- ▁100 !
▁- ▁Tidak_ms .
▁Men er usi ▁la_ms mpu ▁me_ms rah_ms ▁dan_ms ▁me_ms lang_ms gar ▁belakang ▁kereta .
▁Hai , ▁kawan - ka_ms wan .
▁Saya_ms ▁melihat ▁C risti ano ▁seperti_ms ▁anak . ▁Seperti ▁anak ▁yang_ms ▁se_ms benar .
▁Kita_ms ▁kena ▁ lari ▁dari_ms ▁orang_ms ▁ini_ms , ▁siapa ▁pun ▁dia_ms ▁itu_ms !
▁Aku_ms ▁bersama ▁Cu tter .
▁Dengan ▁bang ga_ms ▁ nya_ms ▁saya_ms ▁per_ms sem b ahkan ▁lelaki ▁bu di_ms man_ms ▁ini_ms , ▁Yang ▁tidak_ms ▁lain ▁lagi_ms ▁dari_ms ▁lag enda ▁maha ra_ms ja_ms ▁We i wu ▁gener asi ▁moj in_ms ▁yang_ms ▁ke_ms ▁82 ▁Tiada ▁lain ▁lagi_ms ▁pen_ms curi ▁maka m
▁Pen yun ting an_ms ▁skr in_ms ▁se_ms akan_ms - E mac s ▁minimum ▁diso ko ng_ms . ▁Pel eng ka_ms pan_ms ▁sena rai ▁TA B . ▁Te kan_ms ▁Ctrl - x ▁atau ▁F 10 ▁untuk_ms ▁but , ▁Ctrl - c ▁atau ▁F 2 ▁untuk_ms ▁bar is - p erintah ▁atau ▁E SC ▁untuk_ms ▁ sing kir kan_ms ▁sunt ing_ms an_ms ▁dan_ms ▁kembali ▁ke_ms ▁menu ▁ GR UB .
▁Jadi ▁sele pas ▁Yo m ▁Ki pp ur ▁selesai , ▁kita_ms ▁pergi_ms ▁dari_ms ▁sini_ms .
▁Sul tan_ms , ▁kamu_ms ▁akan_ms ▁di_ms bela sah ▁hari ▁ini_ms .
▁Dia_ms ▁Krist ian i .
▁Anda_ms ▁tahu_ms , ▁s qui r ming , ▁seperti_ms , ▁" apa_ms ▁yang_ms ▁pa lang_ms ▁pintu ▁itu_ms ?"
▁Tapi_ms , ▁masih ▁tak_ms ▁jumpa .
▁Ia ▁besar , ▁ge lap .
▁Boleh ▁awak_ms ▁p indah kan_ms ▁mereka_ms ?
▁Ia ▁ke_ms put us_ms an_ms ▁suka r ▁tapi ▁buat lah_ms .
▁Sekarang dia ha nya_ms per lu_ms 1 to uch down ▁lagi_ms ▁untuk_ms ▁mem ec ahkan ▁re kod .
▁Lu i , ▁macam ▁mana_ms ▁dengan_ms ▁Ka la_ms ?
▁Aku_ms ▁ingat ▁ada_ms ▁sesuatu_ms ▁di_ms ▁dalam_ms nya_ms .
▁Gun ▁bisa ▁menggunakan ▁ini_ms ▁ke_ms ra_ms cun an_ms ▁makan an_ms ▁untuk_ms ▁Ma ster ▁Hu o ▁...
▁Pergi ▁ke_ms ▁la_ms man_ms ▁ter_ms da_ms hulu
▁Apa_ms ▁awak_ms ▁buat ▁pada_ms ▁dia_ms ?
▁Ia nya_ms ▁di_ms ▁ge lar ▁As ce ndan t .
▁Awak ▁telah_ms ▁melalui ▁tu_ms ju h ▁pe_ms mbe da_ms han_ms , ▁betul ?
▁Dengar ▁sini_ms ...
▁Saya_ms ▁tak_ms ▁tahu_ms ▁nas ib ▁saya_ms ▁pada_ms ▁masa_ms ▁akan_ms ▁datang .
▁Jika ▁awak_ms ▁fikir ▁saya_ms ▁tak_ms ▁wara s , ▁saya_ms ▁faha m .
▁Kami_ms ▁akan_ms ▁mun cul ▁di_ms ▁si_ms si_ms ▁kan an_ms ▁seja rah_ms .
▁U U ID ▁untuk_ms ▁per_ms anti ▁yang_ms ▁digunakan .
▁" A da_ms lah_ms ▁suka r ▁untuk_ms ▁ber_ms und ing_ms ▁dengan_ms ▁ nya_ms "
▁Aku_ms ▁tak_ms ▁akan_ms ▁meno long ▁kamu_ms
▁ ♫ Lo ve is ▁ . ♫
▁Kau_ms ▁ada_ms ▁nampak ▁dia_ms ▁di_ms ▁mana_ms - mana ?
▁Yo ng_ms - se_ms ok !
▁Sekarang ▁waktu nya_ms ▁kita_ms ▁perlu ▁ber_ms hati ▁- ▁ha_ms ti_ms .
▁Kau_ms ▁boleh ▁memilih ▁untuk_ms ▁meno lak ku_ms ▁ .
▁Tak_ms ▁boleh ▁begitu !
▁- ▁Bi ar_ms kan_ms ▁saya_ms ▁berse orang an_ms .
▁Kir a - kira ▁satu_ms ▁bat u ▁se_ms ten ga_ms h .
▁Pel in_ms dung mu_ms !
▁O key , ▁sangat_ms ▁baik_ms .
▁Ak tif kan_ms ▁but ang_ms ▁peng_ms u bah ? ▁Mas uk kan_ms ▁y ▁atau ▁n :
▁Pe sur uh_ms ja_ms ya ▁Da vis , ▁New ▁York ▁Post ▁me_ms la_ms por kan_ms ▁seorang_ms ▁pe_ms mu_ms da_ms ▁20 ▁tahun ▁dari_ms ▁Arab ▁Sa udi ▁telah_ms ▁di_ms tahan .
▁Ia ▁bukan_ms ▁ber_ms si_ms fat ▁per_ms ka_ms u man_ms ▁jika_ms ▁aku_ms ▁mengatakan nya_ms .
▁Saya_ms ▁me_ms lar ikan_ms ▁diri_ms ▁bersama nya_ms , ▁maka ▁ayah ▁dia_ms ▁ma rah_ms .
▁Aku_ms ▁banyak_ms ▁kerja , ▁jadi . ...
▁Sekarang ▁saya_ms ▁sedang ▁mencari ▁sam bung an_ms ▁yang_ms ▁lebih ▁em osi .
▁Ia ▁sangat_ms ▁men_ms ak_ms ju b kan_ms .
▁Saya_ms ▁tidak_ms ▁perlu ▁lagi_ms ▁orang_ms ▁menunggu ▁di_ms ▁me_ms - - ▁Orang - orang ▁yang_ms ▁saya_ms ▁akan_ms ▁los e - ▁- ▁Me lain kan_ms ▁anda ▁manusia ▁dan_ms ▁mendapatkan ▁beberapa ▁Co jon es , ▁comprend e ?
▁Tak_ms kanlah ▁kita_ms ▁saja ▁yang_ms ▁masih ▁hidup .
▁Semua ▁per_ms atura n ▁per_ms sat uan ▁ter_ms tul is ▁di_ms ▁si_ms tu_ms .
▁Dan_ms ▁Ayah ▁fikir ▁i_ms a ▁akan_ms ▁membuat ▁Ibu ▁kamu_ms ▁ber_ms asa_ms ▁sele sa_ms ▁disini .
▁Yeah .
▁Dan_ms ▁kamu_ms , ▁mi mpi kan_ms ▁seseorang , ▁yang_ms ▁kamu_ms ▁tak_ms ▁pernah_ms ▁jumpa !
▁Ata u ▁Cor n - D og ▁Per anci s ?
▁Ay uh_ms , ▁da f tar ▁gera i ▁itu_ms , ▁dia_ms ▁berada ▁di_ms ▁sini_ms .
▁Kau_ms ▁cakap ▁pada_ms ▁dia_ms . ▁kau_ms ▁kena ▁tahan ▁kerana ▁menjadi_ms ▁sus pek ▁ke_ms curi an_ms ▁kereta .
▁An tara ▁Facebook , ▁In sta gram , ▁dan_ms ▁Flickr , ▁orang_ms - orang ▁menga_ms wa_ms si_ms ▁diri_ms ▁mereka_ms .
▁- ▁" K en apa_ms ?
▁Nick ber hen ti_ms untu k me mbe li_ms untu kka mu_ms .
▁Kamu ▁cuba ▁gert ak_ms ▁aku_ms ?
▁Kau_ms lah_ms ▁yang_ms ▁akan_ms ▁berada ▁dalam_ms ▁masalah .
▁Awak ▁se_ms pat ut_ms nya_ms ▁pergi_ms , ▁tu_ms an_ms , ▁sebelum ▁dia_ms ▁menembak ▁lagi_ms .
▁Saya_ms ▁minta ▁maaf ▁bahawa ▁anda ▁ter_ms ke jut ▁lang kah_ms ▁dis ip lin ▁ini_ms .
▁Saya_ms ▁nak ▁uru s kan_ms ▁pe_ms ja_ms bat ▁du lu_ms .
▁Da lam ▁air , ▁sebe lah_ms ▁sana .
▁Kau_ms ▁tahu_ms ▁kenapa ▁ku_ms da_ms ▁yang_ms ▁bagus ▁tidak_ms ▁mahu ▁makan ▁rum put ▁yang_ms ▁tu_ms mbu h ▁kembali ?
▁So alan ▁Men a rik , ▁wa_ms lau pun_ms .
▁Lee ▁Jung - ja_ms , ▁Jung ▁Ko ok - s up , ▁Kim ▁You ng_ms - shin .
▁- ▁I kut ▁na ik ▁kereta ▁saya_ms .
▁Le wat ▁e mpat ▁pul uh_ms ▁tahun ?
▁Be lum ▁pernah_ms ▁aku_ms ▁melakukannya ▁da hulu .
▁- ▁Ke_ms pada ▁Dan_ms e law .
▁Ra lat ▁memba ca_ms ▁fail ▁'% s ' : ▁% s
▁So alan ▁penting .
▁Be liau ▁telah_ms ▁berubah ▁wa_ms jah ▁dan_ms ▁ba_ms dan .
▁Men cu ba_ms ▁sesuatu_ms ▁yang_ms ▁baru ?
▁Awak ▁seorang_ms ▁pe_ms lang_ms gan , ▁bukan_ms ?
▁Se_ms gala ▁sesuatu_ms nya_ms ▁penting ▁sekarang
▁Sekarang ▁kau_ms ▁menjadi_ms ▁som bo ng_ms .
▁Aku_ms ▁mengha bis kan_ms ▁banyak_ms ▁u ang_ms ▁untuk_ms ▁itu_ms .
▁Tapi_ms ▁mani s ▁ sungguh ▁ce rita nya_ms .
▁Aku_ms ▁pun ▁suka ▁kau_ms .
▁- ▁Is teri ▁Siapa ? ▁- ▁Ya_ms .
▁Mereka ▁akan_ms ▁menjadi_ms ▁lebih ▁ku_ms at_ms ▁hin gga ▁hari ▁mend ek ati ▁ak hir .
▁- ▁Ini_ms ▁e - mel ▁dari_ms ▁La ura .
▁Ta hni ah_ms ▁saudara ku_ms . ▁Sem oga ▁di_ms ber ka_ms ti_ms , ▁pergi_ms lah_ms ▁berse ron ok . .
▁Jadi , ▁set uju ?
▁Dia_ms ▁beritahu ▁pada_ms ▁saya_ms ▁sem_ms asa_ms ▁makan ▁malam .
▁Charlie ▁Wa x .
▁Kita_ms ▁harus ▁pergi_ms . .
▁Ia itu ▁hari ▁mereka_ms ▁keluar ▁( dari ▁ku_ms bur ▁mas ing_ms - mas ing_ms ) ▁dengan_ms ▁je_ms las ▁ny ata ; ▁tidak_ms ▁akan_ms ▁ter_ms se_ms mbu ny_ms i ▁kepada_ms ▁Allah_ms ▁sesuatu_ms pun_ms ▁dari_ms ▁hal ▁keadaan ▁mereka_ms .
▁Apa_ms ▁kata ▁awak_ms ▁kembali ▁kepada_ms ▁hidup ▁dan_ms ▁me_ms ja_ms ▁awak_ms ▁yang_ms ▁kecil ▁itu_ms ?
▁- ▁M mm .
▁Aba ikan_ms ▁semua_ms ▁atau ▁( jika ▁di_ms spesif ika s ikan_ms ) ▁n ▁bar is ▁pertama ▁pada_ms ▁ST DER R ▁[ pi li_ms han_ms ]
▁Saya_ms ▁ba_ms wa_ms ▁50 ▁dolar .
▁- ▁Dia_ms ▁mis kin .
▁Mungkin ▁ini_ms ▁je_ms las ▁ter_ms lihat ▁apa_ms ▁kalian ▁yakin ▁ini_ms ▁bukan_ms lah_ms ▁per_ms angkap ?
▁- ▁Da lam ▁kereta pi !
▁Itu_ms ▁bukan_ms ▁per_ms mul aan ▁yang_ms ▁kita_ms ▁pat ut_ms ▁ra nc angkan .
▁Okay , ▁memang ▁boleh ▁tahan .
▁Sudah ▁ber_ms ta_ms hun ▁kita_ms ▁bersama - s ama ▁me_ms mbang un kannya .
▁Hanya ▁apabila ▁anda ▁mendapat ▁lebih ▁a_ms wal ▁ , ▁seseorang ▁senti asa_ms ▁berubah ▁kem ung kin an_ms .
▁Dia_ms ▁kata ▁kita_ms ▁tak_ms ▁boleh ▁ada_ms ▁anak .
▁Ber_ms na_ms fas !
▁Saya_ms ▁tahu_ms ▁kamu_ms ▁suka kan_ms ▁saya_ms .
▁Kami_ms ▁dengan_ms ▁Me tro ▁ DC .
▁Kita_ms ▁tak_ms ▁lakukan_ms ▁apa_ms - apa_ms .
▁Saya_ms ▁bukan_ms ▁Rom .
▁Kada ng_ms - ka_ms dang ▁gi la_ms . .
▁Apa_ms ▁yang_ms ▁dia_ms ▁buat ▁du lu_ms ?
▁Ya_ms , ▁Will .
▁Kau_ms ▁buat ▁aku_ms ▁nak ▁la_ms m bung ▁masuk ▁dalam_ms ▁tin fo il , ▁dan_ms ▁ma kannya
▁Nama ▁Di beri
▁B ahkan ber ja_ms ya men unda s aya ▁men_ms dat angkan ▁pe_ms gua m .
▁Pa da_ms ▁tahun ▁ke_ms lah_ms iran ▁awak_ms , ▁ada_ms ▁satu_ms ▁ram alan ▁yang_ms ▁pe_ms mi_ms mpi n ▁kami_ms ▁akan_ms ▁di_ms lah_ms ir kan_ms ▁untuk_ms ▁me_ms mbe bas kan_ms ▁kami_ms ▁daripada ▁per_ms hamba an_ms ▁ini_ms .
▁Nah , ▁ini_ms ▁semua_ms ▁yang_ms ▁kita_ms ▁mili ki_ms .
▁Ми р ный
▁Dan_ms ▁ter_ms uta ma_ms ▁sekali , ▁cara ▁anda ▁mengg ali ▁hi dung ▁anda ... ▁saya_ms ▁mencintai ▁itu_ms ▁juga_ms !
▁Jangan ▁cuba ▁untuk_ms ▁menga_ms jar ▁saya_ms .
▁ kej adian ▁luar ▁ka wa_ms lan_ms ?
▁- ▁Ayah , ▁saya_ms ▁baik_ms ▁saja , ▁betul .
▁Le la_ms ki_ms ▁ber_ms dir i ▁di_ms ▁sebe lah_ms ▁kiri ▁dan_ms ▁wanita ▁kan an_ms
▁- ▁Tidak_ms , ▁itu_ms ▁bukan_ms ▁sama ▁sekali ▁apa_ms ▁yang_ms ▁saya_ms ▁mahu .
▁di_ms ▁sini_ms ▁untuk_ms ▁members ih_ms kan_ms ▁nama nya_ms ▁daripada ▁tu_ms du_ms han_ms ▁pal su
▁Adakah ▁kita_ms ▁re bus ▁tel ur ▁untuk_ms ▁di_ms ku_ms pas ?
▁- ▁Hei , ▁Angel a .
▁Se_ms benar nya_ms ▁Chu g ▁Run ▁adalah_ms ▁idea ▁aku_ms .
▁Da h , ▁berhenti ...
▁Kap al_ms ▁mo yang ▁kau_ms ▁ka ram ▁atau ▁ter_ms s ada i ?
▁- ▁Saya_ms ▁nampak ▁dia_ms ▁sekali ▁lagi_ms ▁hari ▁ini_ms .
▁_ G el apkan ▁ket elu san ▁dan_ms ▁la_ms tar bela kan_ms g ▁ime j :
▁Adakah ▁itu_ms ▁akan_ms ▁berlaku ?
▁Be tul . ▁Itu_ms ▁dah ▁lama ▁berlaku .
▁Awak ▁bercakap ▁dengan_ms ▁Fir a un .
▁Anim a table
▁Se_ms ba_ms gai ▁be kas ▁peng_ms a wal ▁Bir o ▁Pe m buru ▁Ra ksa sa_ms ▁ist ana ▁pertama
▁B < \ - \ - reg ex \ = > I
▁Mas uk ▁kembali ▁dengan_ms ▁selamat .
▁Ata u ▁aku_ms ▁akan_ms ▁memilih ▁e mpat ▁orang_ms .
▁Apa_ms ▁ter_ms aj di_ms ▁sini_ms .
▁A tuk ▁juga_ms ▁pes an_ms ▁jangan ▁pergi_ms ▁ke_ms ▁sana .
▁Chi ps , ▁dia_ms m lah_ms !
▁Tuan , ▁orang_ms - orang ▁kita_ms ▁ada_ms ▁di_ms ▁sana ! ▁- ▁- ▁Aku_ms ▁tidak_ms ▁peduli !
▁Uh ... ▁saya_ms ▁suka kan_ms ▁" The ▁Note book ".
▁Ke_ms kas ih_ms ku_ms ▁dah ▁kembali . .
▁- ▁Mak , ▁dia_ms m lah_ms !
▁Te man_ms ▁W ren ?
▁_ T anda kan_ms ▁mes ej ▁sebagai ▁telah_ms ▁di_ms ba_ms ca_ms ▁sele pas
▁Kamu ▁tahu_ms ▁apa_ms ▁peng_ms or ban an_ms ▁kami_ms ?
▁Pu teri ▁Chan d rika ▁panggil ▁saya_ms
▁Mengapa ▁awak_ms ▁pe_ms si_ms mis ?
▁- ▁Maka . ... ▁macam ▁mana_ms ▁mungkin ?
▁- ▁Ja hat ▁ba_ms bi ▁anda ▁Len ny_ms !
▁Maks ud ▁saya_ms ▁adalah_ms . ... ▁... . ken apa_ms ▁tak_ms ▁ada_ms ▁yang_ms ▁beritahu ▁bahawa ▁saya_ms ▁ada_ms ▁a_ms bang ?
▁Kalau ▁begitu , ▁u cap ▁he lo ▁kepada_ms ▁ah li_ms ▁keluarga ▁ter_ms bar u .
▁_ Ka tal alu an_ms :
▁- P elu ang_ms ▁makan ▁malam ▁awak_ms ▁hi lang_ms ▁juga_ms .
▁Te t apkan ▁makan an_ms ▁ring an_ms mu_ms ▁di_ms ▁da pur / B ye , ▁ibu
▁Saya_ms ▁akan_ms ▁men_ms cam pak kan_ms ▁du it ▁ke_ms ▁wa_ms jah ▁awak_ms ▁semua_ms .
▁Anda_ms ▁akan_ms ▁mem ec ahkan ▁gegen dang ▁tel inga ▁anda .
▁- ▁Aku_ms ▁tak_ms ▁tahu_ms . P en er b angan_ms ▁pertama ▁yang_ms ▁ada_ms ▁keluar ▁dari_ms ▁Jer man_ms .
▁ DEN ICE :
▁Pen on ton ▁sekali ▁ter_ms uja ▁dengan_ms ▁per_ms tan_ms ding an_ms ▁ini_ms .
▁Saya_ms ▁sedikit ▁ klaus tro fo bia , ▁rasa nya_ms , ▁... ja_ms di_ms ▁saya_ms ▁mungkin ▁ada_ms ▁masalah .
▁Oh ▁Tuhan ku_ms , ▁jangan .
▁Oh , ▁si_ms al_ms . ▁Kau_ms ▁apa_ms ▁hal , ▁si_ms al_ms ?
▁- ▁Di ▁sini_ms ▁mereka_ms .
▁Uh , ▁uh , ▁uh , ▁tunggu ▁ke_ms ja_ms p , ▁jangan ▁takut .
▁Kau_ms ▁ber_ms mus uh_ms ▁dengan_ms ▁aku_ms .
▁Pe ker ja_ms an_ms ▁kau_ms ▁mem ung ut_ms ▁sa mpah .
▁Ah , ▁mereka_ms ▁orang_ms ▁yang_ms ▁baik_ms .
▁Hei , ▁ RD .
▁Per ta_ms ma_ms , ▁me_ms mand u . ▁Let akkan ▁tangan ▁pada_ms ▁ ster eng . ▁- ▁Okay .
▁Bagaimana ▁keadaan ▁ibu mu_ms ▁?
▁... s aya ▁ber_ms ca_ms dang ▁untuk_ms ▁keluar ...
▁Kami_ms ▁sedang ▁u lang_ms ka_ms ji ▁di_ms ▁sini_ms .
▁Ma lah_ms ▁rumah ▁pak ci k ▁pun ▁ber_ms kun ci .
▁Men gam bil ▁e kor .
▁Will ie , ▁kau_ms ▁tak_ms ▁harus ▁bunu h ▁orang_ms ▁ni , ▁kawan .
▁Kita_ms ▁akan_ms ▁dapat_ms kan_ms ▁S mur fett e .
▁Boleh ▁saya_ms ▁tahu_ms ▁siapa ▁anda ▁bercakap ▁dengan_ms ?
▁Anda_ms ▁ter_ms ke san ▁ayah ku_ms , ▁yang_ms ▁tidak_ms ▁mu dah .
▁Dan_ms ▁bukan_ms lah_ms ▁engkau ▁( wa_ms hai ▁Muhammad ) ▁yang_ms ▁mele mpar ▁ketika ▁engkau ▁mele mpar , ▁akan_ms ▁tetapi ▁Allah_ms ▁ju a lah_ms ▁yang_ms ▁mele mpar ▁( untu k ▁mem bina s akan_ms ▁orang_ms - orang ▁kafir ) , ▁dan_ms ▁untuk_ms ▁mengu rni akan_ms ▁orang_ms - orang ▁yang_ms ▁beriman ▁dengan_ms ▁peng_ms ur nia an_ms ▁yang_ms ▁baik_ms ▁( ke men angan_ms ) ▁daripada Nya .
▁Tapi_ms ▁saya_ms ▁tak_ms ▁boleh ▁bunu h ▁orang_ms .
▁Saya_ms ▁akan_ms ▁minta ▁pi ha k ▁bank ▁buat kan_ms ▁satu_ms ▁untuk_ms ▁saya_ms .
▁A la_ms mat ▁E mail
▁Kamu ▁hampi r ▁kehilangan ▁tangan mu_ms ▁ ayo lah_ms , ▁Su nggu h ?
▁Selamat ▁datang ▁di_ms ▁keluarga ▁kami_ms
▁Mel ina ▁tahu_ms ▁tentang ▁Od essa . ▁Dia_ms ▁dalam_ms ▁perjalanan ▁ke_ms ▁sana .
▁Kami_ms ▁ambil ▁bis nes ▁ini_ms ▁untuk_ms ▁pen_ms didi kan_ms
▁Anda_ms ▁menga_ms la_ms mi_ms ▁O SD , ▁yang_ms ▁me_ms rup akan_ms ▁kein gin an_ms ▁seks ual ▁ke_ms ter la_ms lu_ms an_ms .
▁Tidak_ms ▁tidak_ms ▁... ▁Awak ▁tak_ms ▁pa yah ▁pergi_ms ▁...
▁Dia_ms ▁tak_ms ▁cakap .
▁Pod rac ing_ms .
▁Kami_ms ▁berse mbu ny_ms i ▁dalam_ms ▁rok et ▁peng_ms ga_ms lak ▁dan_ms ▁tunggu ▁i_ms a ▁ter_ms pis ah_ms ▁dan_ms ▁jatuh ▁ke_ms ▁la_ms u tan_ms ▁Atlant ik ▁seperti_ms ▁yang_ms ▁dira nc angkan .
▁Saya_ms ▁nak ▁katakan ▁itu_ms lah_ms .
▁Awak ▁nak ▁minu man_ms ?
▁Anda_ms ▁tidak_ms ▁ge mbi ra_ms ▁melihat ▁dia_ms ?
▁Ke_ms pada ▁saudara ▁Henry ... ▁kehidupan ▁di_ms ▁Spring field ▁tak_ms lah_ms ▁begitu ▁se_ms ron ok .
▁Jadi ▁i_ms a ▁adalah_ms ▁' Ba ju ▁mati ' .
▁Plan k ton ▁sangat_ms ▁ spesif ik .
▁Ke_ms pul a uan ▁Ca y man_ms ▁Name
▁Bru no ▁64 ▁akan_ms ▁menu run kan_ms ▁tal i .
▁Awak ▁kena ▁ke_ms mas kan_ms ▁bara ng_ms ▁awak_ms ▁dan_ms ▁ba_ms wa_ms ▁semuanya ▁ke_ms ▁mana_ms ▁pun ▁awak_ms ▁pergi_ms .
▁Dan_ms ▁saya_ms ▁ada_ms ▁sa ksi ▁yang_ms ▁mengatakan ▁dia_ms ▁nampak ▁je_ms rung ▁berjalan ▁atas ▁jalan , ▁manusia ▁je_ms rung .
▁Kalau ▁apa_ms ▁Ga ito nde ▁cakap ▁betul , ▁mak na_ms nya_ms ▁semua_ms ▁bil ▁tu_ms ▁pal su .
▁Me riam ▁besar !
▁Dia_ms ▁ok ▁ke_ms ?
▁" S ela lu_ms ▁melihat ▁ke_ms ▁de_ms pan_ms ."
▁Hel zi nger .
▁< name > ▁< data _ de vice > ▁< ha sh _ de vice > ▁< ro ot _ ha sh >
▁' D esti ny_ms ' , ▁ke_ms ▁de_ms pan_ms ▁hi bur kan_ms ▁kami_ms ▁dengan_ms ▁je_ms na_ms ka_ms ▁kamu_ms ▁berdua !
▁Dan_ms ▁mereka_ms ▁di_ms ti_ms mpa ▁la_ms k nat ▁( yang ▁tidak_ms ▁putu s - put us_ms ) ▁dalam_ms ▁dunia ▁ini_ms ▁dan_ms ▁pada_ms ▁hari ▁kiam at_ms .
▁Aku_ms ▁mengerti ▁kita_ms ▁berada ▁dalam_ms ▁per_ms ang_ms ▁untuk_ms ▁ber_ms tahan ▁hidup .
▁Dia_ms ▁tak_ms ▁tahu_ms ▁dengan_ms ▁siapa ▁ger angan_ms ▁dia_ms ▁bercakap .
▁Stat us_ms
▁- ▁Dia_ms ▁adalah_ms ▁di_ms ▁dalam_ms ▁kereta ▁ti ga_ms .
▁Tapi_ms ▁tunggu ▁saja ▁bila ▁saya_ms ▁keluar ▁nan ti_ms ,
▁Ka ke k , ▁me_ms mbu ang_ms ▁u ang_ms ▁di_ms ▁wa_ms jah ▁mereka_ms !
▁Max ie , ▁saya_ms ▁mahu ▁memberitahu ▁anda ▁banyak_ms ▁kali , ▁tetapi ▁i_ms a ▁adalah_ms ▁terlalu ▁berba haya .
▁Peng ga_ms lak
▁Aku_ms ▁tak_ms ▁pernah_ms ▁Lihat ▁John ▁Stock ton ▁se_ms ge mbi ra_ms ▁sebe gin i .
▁Ada ▁yang_ms ▁ingin_ms ▁ber_ms tu_ms kar ▁wata k ?
▁Per law anan ▁pe_ms mbu kaan ▁gus ti_ms ▁Pro ▁Tak_ms e - Down .
▁awak_ms ▁mem ging atkan ▁saya_ms ▁bahawa ▁akan_ms ▁ada_ms ▁kes an_ms ▁yang_ms ▁tidak_ms ▁di_ms ing_ms in_ms kan_ms , ▁dan_ms ▁saya_ms ▁menghi ra_ms u kannya .
▁" I t ▁is ▁a_ms ▁new ▁feel ing_ms ."
▁- I ' m ▁sebenarnya ▁mati ▁se_ms rius ▁tentang ▁itu_ms .
▁ba_ms si_ms kal ▁me_ms rah_ms , ▁to pi ▁ kele dar ▁me_ms rah_ms .
▁Bay ang_ms - ba_ms yang ▁ber_ms tam bah ▁ panja ng_ms , ▁begitu lah_ms ▁mata hari ▁men_ms ci um ▁u fu k ▁bara t ▁peng_ms u bah ▁ca haya ▁menye ram kan_ms ▁atas ▁ke_ms ber ania n ▁kami_ms ▁dan_ms ▁begitu ▁juga_ms ▁Pat chi .
▁$ IM _ C ON FI G _ MS G ▁Pil ih_ms ▁konfigur asi ▁automat ik : ▁$ IM _ C ON FI G _ A UT OM ATI C ▁$ IM _ C ON FI G _ A UT OM ATI C _ LO NG ▁$ IM _ C ON FI G _ RT FM
▁Kau_ms ▁tidak_ms ▁boleh ▁mena kut kan_ms ▁aku_ms ▁sekarang .
▁Tengo k lah_ms , ▁siapa ▁yang_ms ▁cepat ▁dia_ms ▁yang_ms ▁dapat_ms .
▁Aku_ms ▁suka ▁kereta ▁ni .
▁Dia_ms ▁kata ▁mak ▁cik ▁Maggie ▁perempuan ▁ja lang_ms ▁dan_ms ▁pada_ms n ▁muka ▁dia_ms .
▁- ▁Ada ▁s orang ▁a_ms we k , ▁" ber ry " ▁sex y ▁( san gat ▁se_ms ksi ) .
▁Aku_ms ▁yakin ▁rumah ▁yang_ms ▁jatuh ▁pada_ms ▁anda ▁yang_ms ▁akan_ms ▁menjadi_ms ▁rumah ▁yang_ms ▁se_ms ksi .
▁Ya_ms , ▁ter_ms ima ▁kasih ... ▁kita_ms ▁akan_ms ▁mena ik kan_ms ... ▁hor mon ▁ke_ms ker asan ▁dalam_ms ▁diri_ms ▁mereka_ms .
▁O key , ▁bagi ▁nom bor ▁mereka_ms .
▁Thu mb na_ms il
▁Awak ▁belum ▁pernah_ms ▁buat ▁seks ▁selama ▁90 ▁mini t .
▁Kamu ▁me_ms sti ▁me_ms mul angkan ▁untuk_ms ▁tempat ▁anda . .
▁Ibu ▁ba_ms pa_ms ▁Ele na_ms .
▁Merc ado ?
▁Seperti nya_ms ▁peng_ms a du_ms ▁ter_ms ima ▁bala san .
▁Saya_ms ▁akan_ms ▁mendapat ▁semua_ms ▁em as ▁di_ms ▁ini_ms .
▁Saya_ms ▁tak_ms ▁boleh ▁hidup ▁dengan_ms ▁itu_ms .
▁Kau_ms ▁yang_ms ▁tuli s ▁tu_ms ?
▁# ▁Then ▁I ▁would ▁thank ▁that ▁star
▁Ra mai ▁orang_ms ▁yang_ms ▁ta mpan .
▁Aku_ms ▁mahu ▁mus na_ms h kannya .
▁Le la_ms ki_ms ▁dengan_ms ▁tu_ms bu h ▁ba_ms ja_ms ...
▁Aku_ms ▁tahu_ms . ▁Dan_ms ▁kita_ms ▁mengatakan ▁kita_ms ▁akan_ms ▁melakukan ▁semuanya ▁bersama - s ama .
▁Dia_ms ▁berada ▁di_ms ▁dalam_ms ▁keadaan ▁menu run .
▁tiada ▁apa_ms . ▁saya_ms ▁cuma ▁-- ▁saya_ms - s aya ▁maksud kan_ms ... ▁kalau ▁ada_ms ▁sesuatu_ms ▁yang_ms ▁tak_ms ▁kena ...
▁- ▁Se_ms ron ok , ▁bukan_ms ?
▁Kau_ms ▁me_ms sti ▁fikir ▁aku_ms ▁ni ▁perempuan ▁mur ahan .
▁Ed ▁fikir ▁aku_ms ▁Al f . ▁dan_ms ▁i_ms a ▁terus ▁terus - mene rus ▁dengan_ms ▁komen ▁anti ▁se_ms mi_ms tic .
▁Saya_ms ▁salah . . ▁sangat_ms ▁salah
▁Se_ms benar nya_ms ▁aku_ms ▁juga_ms ▁mamp u ▁merasa kan_ms ▁saya_ms p ▁itu_ms . ▁/ ▁Le i .
▁Jika ▁dia_ms ▁mati , ▁aku_ms ▁mati .
▁Saya_ms ▁nak ▁be li_ms ▁kopi ▁untuk_ms ▁6 ▁orang_ms
▁Ra dar ▁dari_ms ▁dia_ms ?
▁Oh , ▁kau_ms ▁akan_ms ▁bera yun ... ▁tidak_ms , ▁tidak_ms , ▁tidak_ms , ▁nan ti_ms , ▁nan ti_ms
▁Bu at_ms ▁pu ku_ms lan_ms ▁sa al_ms tu_ms .
▁Awak ▁pernah_ms ▁dengar ▁Tri ton ?
▁6 ▁[ jum lah_ms ▁pen_ms uh_ms ▁6 ]
▁Vi rus ▁dan_ms ▁bak teria ▁ ang_ms kas a ▁yang_ms ▁membawa ▁ma ut_ms .
▁Jadi , ▁apa_ms ▁yang_ms ▁dia_ms ▁lihat ?
▁Sekarang ▁kita_ms ▁hi lang_ms ▁25 ▁ ribu .
▁- ▁Tidak_ms , ▁awak_ms ▁dengar lah_ms .
▁Andre a , ▁Ku ch ta_ms , ▁awak_ms ▁putu s kannya ?
▁Dia_ms ▁sudah ▁mene mu_ms i ▁pe_ms nye les ai annya .
▁Stop !
▁Ia ▁mu dah ▁untuk_ms ▁lihat ▁tun gga kan_ms ... ▁kadar ▁as as ▁te_ms nga h ▁mening kat ▁sekarang ▁ni !
▁Dan_ms ▁saya_ms ▁memberitahu nya_ms ▁bagaimana ▁kita_ms ▁boleh ▁men_ms angkap ▁mereka_ms ▁pe_ms ga_ms wa_ms i ▁yang_ms ▁di_ms tana m ▁da dah ▁di_ms ▁Yo landa .
▁Kami_ms ▁me_ms sti ▁meng i kut ...
▁Bara t ▁dan_ms ▁U tara .
▁Hei , ▁tahu_ms , ▁la_ms ki_ms - la_ms ki_ms .
▁Orang ▁itu_ms ▁ke_ms can du_ms an_ms .
▁dengan_ms ▁objekt if ▁untuk_ms ▁menu mpa s kan_ms ▁Esc o bar .
▁- ▁Tu ju an_ms ▁ke_ms dat angan_ms ▁kamu_ms , ▁doktor ?
▁Jadi ▁saya_ms . ... ▁Awak ▁tahu_ms - ta_ms hu lah_ms .
▁Itu_ms ▁bahagia n ▁terakhir ▁dari_ms ▁ ratu ▁yang_ms ▁saya_ms ...
▁Rum ah_ms ▁ini_ms ▁bukan_ms ▁lagi_ms ▁untuk_ms ▁law atan ▁go long an_ms ▁bawah an_ms .
▁- ▁Saya_ms ▁boleh ▁mengu ji .
▁- ▁Maafkan ▁saya_ms . ▁- ▁Sil vana ▁bera ni nya_ms ▁awak_ms ▁ba_ms wa_ms ▁dia_ms ▁dalam_ms ▁rumah ▁ini_ms .
▁Aku_ms ▁bisa ▁me_ms lat ih_ms ▁banyak_ms ▁dengan_ms ▁te_ms man_ms - te man_ms ku_ms .
▁Saya_ms ▁kena ▁bekerja ▁dengan_ms nya_ms .
▁A kan_ms ▁ada_ms ▁jam uan ▁besar an_ms .
▁- ▁Bukan ▁ber_ms ken aan ▁ba_ms ju nya_ms .
▁Aku_ms ▁benar - benar ▁men_ms anda inya ▁ tang gal , ▁8 ▁Oktober ▁2002 , ▁Dan_ms ▁sisa nya_ms ▁adalah_ms ▁seja rah_ms ...
▁fly er ▁yang_ms ▁anda ▁menunjukkan ▁kepada_ms ▁saya_ms
▁Se_ms jak ▁itu_ms ▁kami_ms ▁tak_ms ▁pernah_ms ▁ber_ms bu al_ms .
▁Saat ▁aku_ms ▁meninggalkan ▁des a ▁dan_ms ▁i_ms kut ▁ber_ms per ang_ms ▁bersama mu_ms , ▁aku_ms ▁sudah ▁pernah_ms ▁bilang .
▁.. apa_ms bila ▁mereka_ms ▁tahu_ms ▁yang_ms ▁ibu ▁akan_ms ▁kembali .
▁- ▁Me sti lah_ms ▁saya_ms ▁ge ment ar_ms .
▁Ben ar_ms kah_ms ▁ingin_ms ▁keluar ▁daripada ▁Lyn x ?
▁Nama :
▁Bog gar t , ▁mereka_ms ▁tidak_ms ▁ge mar ▁air .
▁_ Li hat
▁Ke_ms ▁rumah ▁sakit , ▁untuk_ms ▁melihat ▁ayah ▁Lu cky .
▁Ya_ms , ▁aku_ms ▁mene mu_ms i ▁dia_ms ▁ kel mar in_ms ▁di_ms ▁ste sen ... ▁boleh kah_ms ▁anda ▁men_ms ja_ms ga_ms nya_ms ▁sehingga ...
▁Si la_ms ▁jag a ▁bag asi ▁awak_ms .
▁Dar i ▁S lo an_ms . ▁dari_ms ▁ku_ms mpu lan_ms , ▁dari_ms ▁Ja nice , ▁dari_ms ▁la_ms por an_ms ▁ke_ms wanga n , ▁dari_ms ▁ keyboard ▁er go nom ik , ▁dari_ms ▁te_ms man_ms ▁wanita ▁cur ang_ms ▁dan_ms ▁kawan ▁tak_ms ▁ guna .
▁[ o ] ▁- ▁ke_ms kal ▁ta rik h ▁as al_ms
▁saya_ms ▁fikir ▁begitu .
▁Sem oga ▁kamu_ms ▁boleh ▁tidur .
▁Oh , ▁tu_ms han_ms ▁ku_ms .
▁- ▁Do ry , ▁ini_ms ▁saya_ms , ▁De sti ny_ms .
▁Nan dini !
▁Saya_ms ▁mahu ▁lihat ▁ke_ms ▁mana_ms ▁i_ms a ▁menga_ms li_ms r ... ▁Oh , ▁ada_ms ▁sebuah ▁gun ung ▁yang_ms ▁tidak_ms ▁pernah_ms ▁di_ms ta_ms wan ...
▁Tu ju h ▁blok ▁u tara , ▁dua ▁blok ▁tim ur .
▁Ke_ms tika ▁saya_ms ▁dit emp atkan ▁di_ms ▁sini_ms , ▁kami_ms ▁gun akan_ms ▁bawah ▁tan ah_ms ▁sebagai ▁guda ng_ms ▁senjata .
▁" He i , ▁Charlie ."
▁Dan_ms ▁mereka_ms ▁tahu_ms ▁bahwa . . ▁ya h , ▁kau_ms ▁tahu_ms . .
▁- ▁Aku_ms ▁sedang ▁bercakap ▁tentang ▁Al var o !
▁Ada ▁yang_ms ▁me_ms mas ang_ms ▁tar u han_ms ▁untuk_ms ▁The ▁G lo be ?
▁Sa lah_ms ▁satu_ms ▁waktu ▁pa ling ▁si_ms buk ▁satu_ms ▁ben ca_ms na_ms ▁a_ms lam ... ▁untuk_ms ▁lelaki ▁macam ▁awak_ms ▁dan_ms ▁saya_ms .
▁Di ▁tempat ▁dia_ms ▁selalu ▁berada .
▁ ** GA GAL ** ▁Peng eko dan Ba ha sa_ms ▁% s ▁ter_ms uk ▁- ▁me_ms sti ▁dalam_ms ▁ISO La tin 1 .
▁Kami_ms ▁jumpa ▁dia_ms ▁bawah ▁lub ang_ms ▁dia_ms ▁The ▁Pi pe line .
▁Mereka ▁masih ▁per_ms ja_ms nji an_ms ▁itu_ms .
▁Ini_ms ▁adalah_ms ▁ tang kal ▁Som de j , ▁i_ms a nya_ms ▁ber_ms ni lai ▁ju taan ▁Bah t .
▁Pat ut_ms kah_ms ▁kita_ms ▁ ikat ▁dia_ms ?
▁-- no - gui ▁Jangan ▁ guna ▁GUI ▁GTK ▁wa_ms lau pun_ms ▁i_ms a ▁ter_ms se_ms dia .
▁Baik , ▁aku_ms ▁kembali ▁bes ok .
▁Dan_ms ▁saat ▁kau_ms ▁pulang , ▁Kau_ms ▁tidak_ms ▁membawa ▁per_ms ma_ms sala han_ms ▁ ts b ▁ke_ms ▁keluarga mu_ms .
▁- I tu_ms ▁sy a mpu .
▁Ini_ms ▁Rock ste ady .
▁Saya_ms ▁tak_ms ▁tahu_ms ▁kenapa ▁saya_ms ▁cakap ▁dengan_ms ▁begitu ▁berse manga t , ▁tapi ▁i_ms a nya_ms ▁heb at_ms ▁kita_ms ▁di_ms ▁sini_ms ▁bersama , ▁betul ?
▁Ya_ms , ▁d gn ▁lan car , ▁u ja_ms ng_ms .
▁Se_ms bab ▁itu_ms lah_ms ▁saya_ms ▁me_ms mand u ▁per_ms lah_ms an_ms ...
▁Tengo k , ▁saya_ms ▁pasti ▁kamu_ms ▁tak_ms ▁mahu ▁si_ms as atan ▁ini_ms ▁mendapat ▁per_ms hati an_ms ▁a_ms wa_ms m ▁dari_ms ▁sekarang ▁ini_ms , ▁bukan_ms ▁begitu , ▁doktor ?
▁Ini_ms ▁me_ms rup akan_ms ▁pen_ms em uan ▁ter_ms bes ar_ms ▁se_ms jak ▁pen_ms em uan ▁" K ing_ms ▁Tu t "
▁- ▁Katakan ▁pada_ms ▁saya_ms , ▁kenapa ▁dia_ms ▁di_ms ▁sini_ms ?
▁Ini_ms lah_ms ▁video ▁yang_ms ▁pa ling ▁menga_ms n cam .
▁Ca haya ▁hija u ▁terjadi ▁masa_ms ▁mata hari ▁ter_ms ben am , ▁bukan_ms ▁masa_ms ▁ter_ms bit .
▁- ▁Itu_ms ▁peng_ms a wal ▁kau_ms .
▁Dia_ms ▁me_ms la_ms mpa u lah_ms !
▁Ia ▁ada_ms ▁pe_ms mas a .
▁Inga t ▁se_ms ku_ms mpu lan_ms ▁perempuan ▁tua ▁ta di_ms ?
▁Mari ▁sini_ms ▁apa_ms kah_ms ▁dia_ms ▁anti - in_ms fla mma tori es , ▁menye mbu h ▁ambil ▁hari ▁ , ▁bukan_ms ▁mi nggu ▁ .
▁Ay uh_ms lah_ms , ▁apa_ms nya_ms ▁yang_ms ▁menye ron ok kan_ms ▁dari_ms ▁itu_ms ?
▁Sekarang , ▁jika_ms ▁awak_ms ▁meminta ▁maaf ▁pada_ms ▁saya_ms ▁Saya_ms ▁ada_ms ▁sesuatu_ms ▁untuk_ms ▁digunakan ▁bi lik_ms ▁anak ▁lelaki ▁kecil ▁we e - we e
▁- ▁Aku_ms ▁dah ▁beritahu ▁yang_ms ▁aku_ms ▁sayang kan_ms ▁kau_ms .
▁- ▁Orang ▁yang_ms ▁ber_ms dika ri .
▁Apa_ms ▁yang_ms ▁kau_ms ▁lakukan_ms ?
▁hipo ten us_ms , ▁satu_ms ▁yang_ms ▁baik_ms .
▁- ▁Ya_ms , ▁ayah ▁kita_ms ▁sangat_ms ▁ kela kar .
▁Ia nya_ms ▁adalah_ms ▁sebuah ▁be kas ▁tan ah_ms ▁per_ms ku_ms bur an_ms .
▁Ya_ms , ▁aku_ms ▁dan_ms ▁kawan - ka_ms wan ▁akan_ms ▁ke_ms ▁sana .
▁Ba wa_ms ▁Pen guin ▁ke_ms ▁sini_ms .
▁Ke_ms la_ms kar ▁bu ny_ms inya ▁dia_ms ▁bercakap .
▁Me maka i ▁ paka ian ▁jin gga , ▁ku_ms ▁menjadi_ms ▁pe_ms mu_ms ja_ms ...
▁- ▁Aku_ms ▁akan_ms ▁melakukan ▁up aya ▁terbaik ▁saya_ms
▁Jangan ▁te_ms kan_ms ▁terlalu ▁ku_ms at_ms , ▁baik_ms ?
▁dan_ms ▁mengu rung ▁saya_ms ▁dalam_ms ▁bone t , ▁dan_ms ▁kemudian ▁dia_ms ▁nak ▁ber_ms baik , ▁mul akan_ms ▁sem_ms ula .
▁Pe lang_ms gan ▁( Re ese ) ▁Saya_ms ▁punya ▁kein gin an_ms ▁Ke_ms per ca_ms ya an_ms ▁sebelum ▁menye r ahkan ▁wa_ms ng_ms
▁A bang ▁I p .
▁Oh , ▁É mili en !
▁~ ▁Isi ▁ha_ms ti_ms ▁kamu_ms ▁dengan_ms ▁war na_ms .
▁Tu n juk kan_ms ▁mereka_ms ▁apa_ms ▁yang_ms ▁kita_ms ▁ada_ms .
▁Kau_ms ▁terlalu ▁me_ms mi_ms kir kan_ms ▁ben da_ms ▁yang_ms ▁tak_ms ▁w uju d
▁Bi ar_ms ▁dia_ms ▁di_ms pen ja_ms ra_ms ▁sebe ntar .
▁Se_ms se_ms orang ▁di_ms p ang_ms gil ▁Long ▁Q i ▁telah_ms ▁mening kat ▁melalui ▁pa ngkat .
▁Anti ji rim ▁hanya_ms ▁per_ms mul aan .
▁Dim ula i ▁dari_ms ▁per_ms i ngkat ▁satu_ms ▁dunia ▁as al_ms ▁Oklahoma , ▁Ja red ▁Mid dle ton !
▁- ▁Ada ▁aku_ms ▁sur uh_ms ▁kau_ms ▁ buka ▁mu lut ?
▁Kau_ms ▁menyukai ▁ini_ms !
▁Ci pta ▁vers i ▁simbol ▁la_ms lai ▁untuk_ms ▁simbol ▁ter_ms import
▁Dan_ms ▁besar ▁lelaki , ▁Le la_ms ki_ms ▁yang_ms ▁mem bina ▁ lega si_ms , ▁mereka_ms ▁tidak_ms ▁senti asa_ms ▁baik_ms .
▁N SA ▁ini_ms ▁mene t apkan ▁anda .
▁Kau_ms ▁tak_ms ▁sa nggu p ▁sebab ▁di_ms ▁bawah ▁ku_ms asa_ms ▁itu_ms , ▁masih ▁ada_ms ▁diri_ms ▁kau_ms .
▁Kenapa ▁kamu_ms ▁ter_ms ima ▁ arahan ▁saya_ms ?
▁Saya_ms ▁cakap ... ▁ba_ms lik_ms !
▁- ▁Tak_ms , ▁akan_ms ▁ada_ms ▁orang_ms ▁jag a ▁kan ak_ms - kan_ms ak_ms ▁itu_ms .
▁.. and ▁Saya_ms ▁bi mbang
▁Ci ri - ▁cir i
▁Jika ▁ada_ms ▁ber_ms ita ▁dari_ms nya_ms , ▁aku_ms ▁lang s ung ▁pergi_ms .
▁Du a ▁orang_ms , ▁aku_ms ▁akan_ms ▁ ganda kan_ms ▁up ah_ms mu_ms , ▁tetapi ▁harus ▁selesai kan_ms ▁pagi ▁es ok .
▁Aku_ms ▁masih ▁ingin_ms ▁mati . ▁Tapi_ms ▁aku_ms ▁ingin_ms ▁kembali ▁dan_ms ▁menyelamatkan ▁pen_ms u mpan g ▁kereta ▁a_ms pi ▁du lu_ms .
▁Co ba_ms ▁Anda_ms ▁pikir ...
▁- ▁Tak_ms , ▁dua ▁orang_ms ▁sudah ▁mati .
▁Yeah .
▁Ta han_ms , ▁tak_ms ▁perlu ▁ke_ms ker asan .
▁Helen a , ▁Saya_ms ▁su mpah ...
▁Ter uta ma_ms ▁awak_ms , ▁Ve ge ta_ms - san , ▁terlalu ▁sangat_ms ▁cu ai .
▁Katakan lah_ms ▁( wa_ms hai ▁Muhammad ): ▁" Se mu_ms a nya_ms ▁itu_ms ▁( ke ba_ms ikan_ms ▁dan_ms ▁ben ca_ms na_ms ) ▁adalah_ms ▁( ber pun_ms ca_ms ) ▁dari_ms ▁si_ms si_ms ▁Allah_ms ".
▁Ce tak ▁re kod ▁tidak_ms ▁boleh ▁di_ms pas ang_ms ▁dari_ms ▁fail ▁yang_ms ▁di_ms nya_ms ta_ms kan_ms ▁( s ama ▁ada_ms ▁1 ▁atau ▁2)
▁A tuk ▁dah ▁kata , ▁tak_ms ▁pa yah ▁datang ▁setiap ▁hari .
▁- ▁Nah , ▁apa_ms kah_ms ▁itu_ms ▁anda ?
▁Wal au pun_ms ▁dunia ▁mengha lang_ms mu_ms ...
▁Inga t lah_ms ▁itu_ms , ▁Pete .
▁Sa la_ms am ▁Al ai kum , ▁pak ci k
▁Mu m , ▁anda ▁menge na_ms li_ms ▁saya_ms ?
▁Ka wan , ▁saya_ms ▁kena ▁bay angkan ▁awak_ms ▁tak_ms ▁boleh ▁menyelamatkan ▁hari ▁ini_ms ▁tanpa ▁membuat ▁hur u - hara .
▁- ▁Ayah ▁seorang_ms ▁yang_ms ▁ja hat ?
▁kun ci ▁kli en
▁Ka li_ms ▁ini_ms ▁ada_ms ▁boleh ▁menjadi_ms ▁tidak_ms ▁sy ak_ms ▁lagi_ms ▁... ▁Bu dak ▁itu_ms ▁tidak_ms ▁menga_ms la_ms mi_ms , ▁Tuhan ku_ms , ▁yang_ms ▁saya_ms ▁boleh ▁men_ms ja_ms min .
▁Ay uh_ms !
▁Hent ikan_ms !
▁Ke_ms ga_ms ga_ms lan_ms
▁Kami_ms ▁memang gil nya_ms ▁karena ▁i_ms a ▁selalu ▁mengatakan : ▁- ▁Lihat ▁ke_ms ▁mata ku_ms .
▁Anda_ms ▁harus ▁tahu_ms ▁sekarang ▁bahawa ▁anda ▁tidak_ms ▁boleh ▁memiliki ▁segala ▁sesuatu_ms ▁yang_ms ▁anda ▁ingin_ms kan_ms .
▁Kau_ms ▁akan_ms ▁melihat ▁semuanya ▁nan ti_ms .
▁Tunggu , ▁apa_ms ▁sekarang ?
▁Te ta_ms pi jika anda ada lah_ms s atu ▁an ca_ms man_ms ?
▁Ayah , ▁dah ▁tam bah ▁air .
▁- ▁Itu_ms pun_ms ▁dia_ms .
▁Bila ▁aku_ms ▁se_ms but ▁nama ▁maj ikan_ms ▁kau_ms , ▁kau_ms ▁kata ▁" Ya ".
▁La mpu ▁jalan ▁itu_ms ▁ro sak ▁lagi_ms .
▁" Ja di_ms ▁kami_ms ▁pergi_ms ▁ke_ms ▁bi lik_ms ▁saya_ms , ▁dan_ms ▁te_ms ka_ms ▁apa_ms ▁yang_ms ▁dia_ms ▁ tunjukkan ▁kepada_ms ▁saya_ms ?"
▁sha ru zza man_ms @ ▁my real box . ▁com
▁Te t apkan ▁lalu an_ms ▁gel in_ms tar ▁pus taka ▁ter_ms ko ng_ms si_ms ▁masa_ms ▁pa u tan_ms
▁Ada ▁bi da_ms an_ms ▁pe_ms mbu kaan ?
▁Anda_ms ▁di_ms ▁ko bo i ▁dan_ms ▁anda ▁mahu ▁ga za kov .
▁se_ms bat ian ▁get ah_ms ▁berjalan ▁melalui ▁u rat .
▁Sekarang ▁ba_ms kar lah_ms ▁tangan - t angan_ms ▁itu_ms .
▁- ▁Yeah .
▁Ky oc era ▁K M - 18 20
▁Bag i ▁kau_ms ▁de_ms mi_ms ▁masa_ms ▁de_ms pan_ms .
▁- ▁Saya_ms ▁tak_ms ▁akan_ms ▁beritahu .
▁- ▁Se_ms jak ▁bila ▁kita_ms ▁jadi ▁ra kan_ms ▁se_ms per ju angan_ms ?
▁T N - A 1
▁Di mana ▁dia_ms ▁berse mbu ny_ms i ▁selama ▁60 ▁ju ta_ms ▁tahun ▁terakhir ?
▁Yah udi ▁me_ms ram pas ▁ Palestin , ▁tan ah_ms ▁air ▁kami_ms .
▁Dan_ms ▁( se_ms ba_ms lik_ms nya_ms ▁a_ms mat lah_ms ▁der haka nya_ms ) ▁orang_ms ▁yang_ms ▁berkata ▁kepada_ms ▁kedua ▁ibu ▁ba_ms pa_ms nya_ms ▁( ke tika ▁mereka_ms ▁menga_ms jak nya_ms ▁beriman ): ▁" A h ! ▁Bos an_ms ▁per_ms asa_ms an_ms ku_ms ▁terhadap ▁kamu_ms ▁berdua !
▁Hello ?
▁Di mana ▁krist al_ms ▁itu_ms ?
▁Dia_ms na_ms , ▁Tri cia , ▁Na dine ▁dan_ms ▁Rose ▁dalam_ms ▁perjalanan . ▁Bag us_ms ▁kamu_ms ▁semua_ms .
▁- ▁( GI G GL ES ) ▁tak_ms ▁ada_ms ▁ik lan_ms , ▁itu_ms ▁di_ms lar ang_ms .
▁Ya_ms , ▁aku_ms ▁boleh ▁to long ▁kau_ms , ▁ter_ms uta ma_ms ▁setelah ▁apa_ms ▁yang_ms ▁Te d ▁lakukan_ms ▁pada_ms ▁kau_ms .
▁- ▁Dar i ▁mana_ms ▁dia_ms ▁datang ?
▁La in_ms ▁kali ▁jangan ▁te_ms gang kan_ms ▁ba_ms dan , ▁tena ng_ms ▁saja .
▁Hello , ▁Li ak_ms .
▁Tak_ms ▁apa_ms ▁beritahu lah_ms .
▁Ia ▁adalah_ms ▁mi ny_ms ak_ms ▁digunakan ▁untuk_ms ▁me_ms mbu ang_ms ▁bol t ▁ter_ms uta ma_ms nya_ms ▁de_ms gil .
▁Dan_ms ▁awak_ms ▁tak_ms ▁mengha ntar ▁mes ej ▁kepada_ms nya_ms .
▁Katakan lah_ms ▁( wa_ms hai ▁Muhammad ): ▁" Ba gai mana ▁fikir an_ms ▁kamu_ms , ▁jika_ms ▁Allah_ms ▁mele ny_ms apkan ▁pen_ms den gar an_ms ▁ser ta_ms ▁peng_ms lihat an_ms ▁kamu_ms , ▁dan_ms ▁Ia ▁pula ▁me_ms meter a ikan_ms ▁atas ▁ha_ms ti_ms ▁kamu_ms ? ▁Siapa kah_ms ▁Tuhan ▁se_ms lain ▁Allah_ms ▁yang_ms ▁ber_ms ku_ms asa_ms ▁menge mba li_ms kannya ▁kepada_ms ▁kamu_ms ?"
▁Jika ▁kau_ms ▁meny ak_ms iti nya_ms , ▁maka ▁aku_ms ▁ber_ms su mpah ▁kau_ms ▁tak_ms ▁akan_ms ▁mendapatkan ▁gadis ▁kecil ▁ini_ms !
▁Pi s ang_ms ▁bur ung ▁un ta_ms !
▁Aku_ms ▁yakin ▁ibu ▁kamu_ms ▁juga_ms ▁ber_ms su ara ▁seperti_ms ▁ke_ms lda i , ▁sem_ms asa_ms ▁menga_ms n dung kan_ms ▁kamu_ms .
▁O key ? ▁- ▁Sem oga ▁berjaya
▁Apa_ms ▁yang_ms ▁kau_ms ▁cuba ▁nak ▁bu kti kan_ms ?
▁Ba ny_ms ak_ms nya_ms ▁jum lah_ms ▁simbol ▁kombin asi , ki_ms ta_ms ▁akan_ms ▁di_ms ▁sini_ms ▁ber_ms hari 2 . / ▁Tidak_ms ▁juga_ms ...
▁Ber_ms kah_ms win ▁dengan_ms ▁ja ri ▁saya_ms ▁untuk_ms ▁men_ms ce tus kan_ms - re hat .
▁Ge mbi ra_ms ▁bertemu ▁dengan_ms ▁kamu_ms !
▁Tapi_ms - - ▁buat ▁de_ms mi_ms ▁dia_ms .
▁Kata ▁ak hir ▁dalam_ms ▁su mpah ▁se_ms tia .
▁- ▁Ker ry , ▁kita_ms ▁dalam_ms ▁rumah ▁yang_ms ▁salah !
▁sunt ikan_ms ▁yang_ms ▁berjaya .
▁Saya_ms ▁kena ▁nampak ▁mena rik ▁di_ms ▁tempat ▁kerja .
▁Ku sam ▁+ 5
▁Saya_ms ▁dan_ms ▁Ka t nis s ▁mahu ▁ber_ms ko ng_ms si_ms ▁ke_ms men angan_ms ▁kami_ms ▁dengan_ms ▁kamu_ms ▁dan_ms ▁kes y uku ran ▁pada_ms ▁Cap ito l , ▁yang_ms ▁meny atu kan_ms ▁kami_ms ▁berdua .
▁Kal en dar
▁[ Bi lly ] ▁Kata ▁ak h bar ▁Pat ▁Gar rett ▁je_ms jak ▁saya_ms jat uh_ms .
▁Okay , ▁okay ▁membantu ▁anda ▁me_ms meli hara ▁ke_ms du_ms du_ms kannya ▁du duk ▁di_ms ▁te_ms nga h - ten ga_ms h ▁anda
▁Baiklah , ▁jumpa ▁awak_ms ▁di_ms ▁luar .
▁Saya_ms ▁dengar ▁kamu_ms ▁akan_ms ▁masuk ▁ke_ms lay akan_ms ▁ren ang_ms ▁mi nggu ▁de_ms pan_ms ?
▁Saya_ms ▁kembali ▁kepada_ms ▁kehidupan ▁yang_ms ▁pat ut_ms ▁saya_ms ▁mili ki_ms ▁sekarang .
▁Ju mpa ▁lagi_ms !
▁Yah , ▁Ch ur ch ▁benar .
▁Dia_ms ▁tentu ▁datang
▁Itu_ms ▁baru ▁yang_ms ▁pertama .
▁Tapi_ms ▁tu_ms gas ▁aku_ms .
▁aku_ms ▁dah ▁tak_ms ▁ingat cer ita ▁se_ms benar .
▁_ Per main an_ms
▁baik_ms lah_ms , ▁i_ms a ▁mungkin ▁membantu ▁untuk_ms ▁mengetahui ▁siapa ▁mahu kan_ms ▁O leg ▁mati
▁ba_ms wa_ms k ▁aku_ms ▁sekali
▁Yang ▁anda ▁perlu ▁melakukan ▁adalah_ms ▁me_ms mu_ms kul nya_ms .
▁Ke_ms ka_ms dang ▁sakit ▁me_ms mul ih_ms kan_ms ▁kes ak_ms itan ▁yang_ms ▁lebih ▁men_ms dalam .
▁Z ON ▁K ANA K - K ANA K
▁Awak ▁akan_ms ▁i_ms kut ▁ arahan ▁saya_ms , ▁Gi de on , ▁saya_ms ▁Kap ten ▁awak_ms !
▁Folder ▁destina si_ms ▁tidak_ms ▁w uju d . ▁Ada kan_ms ▁anda ▁ingin_ms ▁men_ms cip ta_ms nya_ms ?
▁Mari ▁kita_ms ▁pergi_ms .
▁Dia_ms ▁cuma ▁kehilangan ▁da rah_ms .
▁Dan_ms ▁aku_ms ▁tant ang_ms ▁kamu_ms ▁masuk ▁ke_ms ▁dalam_ms ... ▁Dan_ms ...
▁Kenapa ▁kamu_ms ▁perlu ▁ber_ms ge gas ▁mahu ▁pergi_ms ?
▁Ber_ms ita ▁menge jut kan_ms .
▁- ▁Di ▁la_ms nta i ▁4.
▁Ayo lah_ms ▁ber_ms ges er !
▁Yeah .
▁Sa tu_ms ▁pe_ms nya_ms kit .
▁ra lat ▁dalam_ms an_ms : ▁to ken ▁% d ▁tidak_ms ▁di_ms keta hui
▁Ar gum en ▁% s : ▁Me rup akan_ms ▁ arahan ▁format ▁dengan_ms ▁sa iz ▁tidak_ms ▁di_ms benar kan_ms ▁disini .
▁- ▁yang_ms ▁datang ▁sehingga ▁ paha .
▁P ing_ms gang ▁ra mping !
▁Pa da_ms ▁masa_ms ▁de_ms pan_ms , ▁dia_ms ▁bersama ▁dengan_ms ▁aku_ms , ▁I ris ▁dan_ms ▁Sa vi tar .
▁- ▁En tah lah_ms ▁ .
▁Mengapa ▁wa_ms jah mu_ms ▁sed ih_ms ?
▁Si buk ▁waktu ▁ni ?
▁Lar s , ▁ini_ms ▁aku_ms .
▁- ▁Kau_ms ▁Jangan ▁sent uh_ms ▁itu_ms
▁Kau_ms ▁uru s kan_ms ▁ini_ms , ▁dan_ms ▁aku_ms ▁akan_ms ▁minta ▁ha_ms kim ▁be bas kan_ms ▁anak mu_ms .
▁Sudah ▁9 ▁bul an_ms .
▁Co yo tes ▁digunakan ▁te_ms row ong ▁ini_ms ▁menye lu_ms du_ms p ▁se_ms ba_ms ha gian ▁daripada ▁kita_ms ▁keluar ▁dari_ms ▁loro ng_ms ▁... ▁ber_ms das ar_ms kan_ms ▁peng_ms hara pan_ms ▁akan_ms ▁hidup ▁yang_ms ▁lebih ▁baik_ms .
▁Saya_ms ▁berkata ▁ter_ms hen ti_ms .
▁Kau_ms ▁harus ▁tahu_ms ▁hal - hal ▁di_ms ▁K now , ▁seperti_ms ▁kau_ms ▁tahu_ms ▁di_ms ▁now .
▁Dar i ▁yang_ms ▁aku_ms ▁ba_ms ca_ms , ▁tuli s annya ▁tak_ms ▁terlalu ▁bez a ▁dengan_ms ▁ga m bar nya_ms .
▁Tidak_ms ▁boleh ▁men_ms af sir kan_ms ▁fail
▁- ▁Ber_ms pul uh_ms - pul uh_ms ▁u ji ▁baka t .
▁" I a itu ▁orang_ms - orang ▁yang_ms ▁meng i kut ▁Rasul ul lah_ms ▁( Mu ham mad ▁s . a . w ) ▁Na bi ▁yang_ms ▁Um mi_ms , ▁yang_ms ▁mereka_ms ▁dapat_ms i ▁ter_ms tul is ▁( na_ms ma_ms nya_ms ▁dan_ms ▁si_ms fat - si_ms fat nya_ms ) ▁di_ms ▁dalam_ms ▁Ta ura t ▁dan_ms ▁In j il ▁yang_ms ▁ada_ms ▁di_ms ▁si_ms si_ms ▁mereka_ms . ▁Ia ▁meny uru h ▁mereka_ms ▁dengan_ms ▁perkara - per kara ▁yang_ms ▁baik_ms , ▁dan_ms ▁me_ms lar ang_ms ▁mereka_ms ▁daripada ▁melakukan ▁perkara - per kara ▁yang_ms ▁ke_ms ji ; ▁dan_ms ▁i_ms a ▁mengha la_ms l kan_ms ▁bagi ▁mereka_ms ▁segala ▁ben da_ms ▁yang_ms ▁baik_ms , ▁dan_ms ▁mengha ram kan_ms ▁kepada_ms ▁mereka_ms ▁segala ▁ben da_ms ▁yang_ms ▁buruk ; ▁dan_ms ▁i_ms a ▁juga_ms ▁mengha pus kan_ms ▁dari_ms ▁mereka_ms ▁be ban - be ban ▁dan_ms ▁bele nggu - bele nggu ▁yang_ms ▁ada_ms ▁pada_ms ▁pada_ms ▁mereka_ms .
▁Tentu ▁tidak_ms , ▁itu_ms ▁tidak_ms ▁panta s .
▁Data ng_ms , ▁cinta !
▁Sel uru h ▁wil a yah ▁ini_ms ▁hanya_ms ▁ada_ms ▁satu_ms ▁pintu ▁keluar ▁masuk
▁Sekarang , ▁kita_ms ▁kena ▁cari ▁dia_ms ▁sebelum ▁Chuck y ▁jumpa ▁dia_ms .
▁Kau_ms ▁adalah_ms ▁kepala ▁ba_ms jak ▁la_ms ut_ms ▁Ye o ▁W ol ? ▁ada_ms ▁ke_ms per lu_ms an_ms ▁apa_ms ▁datang ▁ke_ms ▁la_ms ut_ms ▁yang_ms ▁berba haya ▁ini_ms ?
▁Dan_ms ▁aku_ms ▁melihat nya_ms , ▁mereka_ms ... ▁melihat ...
▁San gat ▁bagus .
▁Awak ▁tidak_ms ▁pernah_ms ▁ber_ms ta_ms nya_ms ▁kepada_ms ▁saya_ms ▁apa_ms ▁berlaku ▁dengan_ms ▁Wall ace ▁malam ▁itu_ms ▁ .
▁Ma klu mat ▁i_ms Calendar
▁" Ma s uk kanlah ▁tangan mu_ms ▁melalui ▁bela han_ms ▁da da_ms ▁ba_ms jumu , ▁nes ca_ms ya ▁keluar lah_ms ▁i_ms a ▁put ih_ms ▁ber_ms sin ar_ms - sin ar_ms ▁dengan_ms ▁tiada ▁ca cat ; ▁dan_ms ▁ke_ms pit lah_ms ▁tangan mu_ms ▁di_ms ▁ce lah_ms ▁ke_ms ti_ms ak_ms mu_ms ▁ketika ▁merasa ▁takut ▁( nes ca_ms ya ▁hi lang_ms lah_ms ▁takut mu_ms ) .
▁Saya_ms ▁bukan_ms ▁ber_ms maksu d ▁bersama ▁awak_ms .
▁Ak hir nya_ms ▁ce rah_ms .
▁- ▁Ama t ▁me_ms lega kan_ms .
▁T angan_ms ▁ni ▁ber_ms ma_ms gi s ▁tau .
▁saya_ms ▁ada_ms ▁sebab ▁untuk_ms ▁percaya ▁bahawa ▁gang ▁yang_ms ▁menye r bu ▁bala i ▁polis ▁untuk_ms ▁men_ms curi ▁may at_ms ▁penge rus i ▁Ma ▁ada_ms ▁kai tan_ms ▁ ngan ▁is teri ▁dia_ms ▁sendiri
▁Fa il ▁dalam_ms ▁loka si_ms ▁direktori ▁ca che : ▁% s
▁Ke_ms rap ▁kali ▁Kami_ms ▁melihat ▁engkau ▁( wa_ms hai ▁Muhammad ) , ▁ber_ms u lang_ms - u lang_ms ▁mene nga dah ▁ke_ms ▁lang it , ▁maka ▁Kami_ms ▁benar kan_ms ▁engkau ▁ber_ms pa_ms ling ▁menga_ms da_ms p ▁ki bla t ▁yang_ms ▁engkau ▁suka i .
▁Ber_ms apa_ms ▁banyak_ms ▁lagi_ms ▁ke_ms ke ce wa_ms an_ms ▁yang_ms ▁aku_ms ▁perlu ▁ha_ms da_ms pi ▁a_ms gar ▁kau_ms ▁pu as ▁ha_ms ti_ms ?
▁Tidak_ms ▁ kah_ms ▁sesiapa ▁menga_ms jar ▁kau_ms ?
▁( De ngan ▁si_ms kap nya_ms ▁itu_ms ) ▁ru gi lah_ms ▁i_ms a ▁akan_ms ▁dunia ▁dan_ms ▁a_ms khi rat , ▁itu_ms lah_ms ▁ker u gian ▁yang_ms ▁ter_ms ang_ms ▁ny ata .
▁Do kter ▁Do , ▁bisa ▁to long ▁ber_ms ikan_ms ▁com pression ? ▁Aku_ms ▁minta ▁to long .
▁Alice , ▁apa_ms ▁yang_ms ▁anda ▁lakukan_ms ?
▁Ele an_ms or ▁membuat kannya ▁untuk_ms ku_ms .
▁Bas i , ▁kan ?
▁Ba wa_ms ▁dia_ms ▁dan_ms ▁pergi_ms ▁ke_ms ▁ne raka !
▁Shar u zza man_ms ▁Ah mat ▁Ra s lan_ms EMAIL ▁OF ▁TRANSLATORS
▁Hadi rin ▁sekali an_ms , ▁Sa vo y ▁Management ▁menga_ms lu_ms - al_ms ukan ▁anda ▁ke_ms ▁per_ms tunjukkan ▁is time wa_ms ▁pada_ms ▁malam ▁ini_ms .
▁Tu n _ juk kan_ms ▁per_ms ing_ms atan
▁Qa zi ▁adalah_ms ▁an ca_ms man_ms ▁ter_ms bes ar_ms , ▁sekarang ▁dia_ms ▁sudah ▁tidak_ms ▁ada_ms
▁Har i ▁ini_ms ▁ber_ms pis ah_ms ▁untuk_ms ▁se_ms ment ara , ▁Su atu ▁hari ▁pasti ▁akan_ms ▁be ju mpa ▁kembali .
▁Ci pta ▁ke_ms kun ci ▁baru
▁Mar vin , ▁a_ms trop ine ▁tu_ms , ▁sekarang !
▁Dan_ms ▁i_ms a ▁adalah_ms ▁je_ms nis ▁seperti_ms ▁tu_ms mpu an_ms ▁ke_ms - ker ja_ms ▁dan_ms ▁kehidupan ▁pertama ▁anda ▁perkara ▁seperti_ms .
▁- ▁Kalau mata ▁menga_ms n tuk ?
▁... ▁Camp uran !
▁Pergi .
▁Ta hun ▁yang_ms ▁heb at_ms .
▁Per atura n ▁pertama ▁saya_ms ▁adalah_ms ▁" har apkan ▁yang_ms ▁terbaik , ▁ra nc angkan ▁untuk_ms ▁yang_ms ▁ter_ms buru k ."
▁Ia ▁meny uru h ▁mereka_ms ▁dengan_ms ▁perkara - per kara ▁yang_ms ▁baik_ms , ▁dan_ms ▁me_ms lar ang_ms ▁mereka_ms ▁daripada ▁melakukan ▁perkara - per kara ▁yang_ms ▁ke_ms ji ; ▁dan_ms ▁i_ms a ▁mengha la_ms l kan_ms ▁bagi ▁mereka_ms ▁segala ▁ben da_ms ▁yang_ms ▁baik_ms , ▁dan_ms ▁mengha ram kan_ms ▁kepada_ms ▁mereka_ms ▁segala ▁ben da_ms ▁yang_ms ▁buruk ; ▁dan_ms ▁i_ms a ▁juga_ms ▁mengha pus kan_ms ▁dari_ms ▁mereka_ms ▁be ban - be ban ▁dan_ms ▁bele nggu - bele nggu ▁yang_ms ▁ada_ms ▁pada_ms ▁pada_ms ▁mereka_ms .
▁Jika ▁kamu_ms ▁mahu ▁menjadi_ms ▁pembunuh ▁dan_ms ▁hidup , ▁kamu_ms ▁mendapat ▁menjadi_ms ▁satu_ms ▁yang_ms ▁pi ntar .
▁Da lam ▁pada_ms ▁itu_ms , ▁jika_ms ▁kamu_ms ▁me_ms mbe lak angkan ▁juga_ms ▁ser uan ku_ms , ▁maka ▁tidak_ms lah_ms ▁menjadi_ms ▁hal ▁kepada_ms ku_ms ▁kerana ▁aku_ms ▁telah_ms ▁sampai kan_ms ▁kepada_ms ▁kamu_ms ▁apa_ms ▁yang_ms ▁telah_ms ▁di_ms utus ▁oleh ▁Allah_ms ▁untuk_ms ▁meny amp ai kannya , ▁dan_ms ▁Tuhan ku_ms ▁akan_ms ▁mengg anti kan_ms ▁kamu_ms ▁dengan_ms ▁su atu ▁kau_ms m ▁yang_ms ▁lain ▁( se_ms te lah_ms ▁kamu_ms ▁di_ms bina s akan_ms ); ▁dan_ms ▁kamu_ms ▁pula ▁tidak_ms ▁akan_ms ▁dapat_ms ▁memba haya kan_ms Nya ▁sedikit pun_ms .
▁Ini_ms ▁adalah_ms ▁bud aya ▁ku_ms mpu lan_ms ▁Dan_ms ▁ini_ms lah_ms ▁yang_ms ▁ayah ▁awak_ms ▁minta
▁Dan_ms ▁rumah ▁itu_ms ▁adalah_ms ▁mi lik_ms ▁kamu_ms .
▁Kalau ▁begitu ▁kau_ms ▁se_ms baik nya_ms ▁ber_ms si_ms ap , ▁Ker ana ▁kau_ms ▁akan_ms ▁mendapatkan ▁begitu ▁banyak_ms ▁makan ▁malam ▁mele bi hi ▁makan ▁malam ▁hin gga ▁kau_ms ▁tak_ms ▁tahu_ms ▁harus ▁apa_ms ▁lagi_ms .
▁Tidak_ms ▁perlu , ▁tapi ▁de_ms mi_ms ▁memba las ▁den dam ▁terhadap ▁ibu ▁ba_ms pa_ms nya_ms ▁...
▁Ta di_ms ▁awak_ms ▁katakan ▁awak_ms ▁la_ms par .
▁Siapa ▁nama ▁ nya_ms ?
▁Awak ▁pat ut_ms ▁tengo k ▁saya_ms ▁sem_ms asa_ms ▁saya_ms ▁ma rah_ms ▁mereka_ms .
▁Kalian ▁berdua , ▁dan_ms ▁akan_ms ▁saya_ms ▁ tunjukkan - -
▁* ▁anda ▁mu la_ms ▁ber_ms main . ▁*
▁Saya_ms ▁takkan ▁ter_ms le pas ▁dari_ms ▁awak_ms , ▁kan ?
▁Dan_ms ▁yang_ms ▁war na_ms ▁bir u ▁adalah_ms ▁kita_ms r ▁sem_ms ula . ▁Dan_ms ▁yang_ms ▁war na_ms ▁hita m ▁adalah_ms ▁sa mpah .
▁Tuhan , ▁semua_ms ▁saya_ms ▁tahu_ms ▁adalah_ms ▁bahwa ▁Tidak_ms ▁ada_ms ▁meny ang_ms kal ▁Per asa_ms an_ms ▁saya_ms ▁untuk_ms ▁Anda_ms .
▁La ti_ms han_ms ▁bukan_ms lah_ms ▁il mu_ms ▁dan_ms ▁penge tah uan ▁tidak_ms ▁ku_ms asa_ms .
▁Se_ms bab ▁Per ta_ms ma_ms ▁ .
▁Ka wan ▁baik_ms ▁awak_ms ▁ter_ms per angkap ▁di_ms ▁dunia ▁lain . ▁Awak ▁di_ms ▁sini_ms ▁cuba ▁per_ms be tul kan_ms ▁segala nya_ms ▁- ▁dengan_ms ▁mencari ▁bi na_ms tang ▁ber_ms bul u ?
▁Ta rik ▁ge ar_ms ▁pen_ms dar atan ! ▁Me la_ms ku_ms kannya !
▁Dan_ms ▁telah_ms ▁mele mas kan_ms ▁mang sa_ms ▁mereka_ms ▁di_ms ▁sini_ms
▁Kau_ms ▁boleh , ▁kawan .
▁Tapi_ms ▁saya_ms ▁tahu_ms ▁yang_ms ▁pasti nya_ms ▁saya_ms ▁cinta kan_ms ▁kamu_ms . .
▁Orang ▁pertama ▁di_ms ▁tal i .
▁Jadi , ▁kerja ▁disini .
▁Al - Q uran ▁sebuah ▁Kitab ▁yang_ms ▁ter_ms sus un ▁a_ms yat - a yat nya_ms ▁dengan_ms ▁tetap ▁te_ms gu h , ▁kemudian ▁dije las kan_ms ▁pula ▁kan dung annya ▁satu_ms ▁per_ms s atu .
▁Saya_ms ▁akan_ms ▁ bantu ▁awak_ms ▁ber_ms s ih_ms kannya ▁jika_ms ▁awak_ms ▁mahu kan_ms .
▁Aku_ms ▁menye dia kan_ms ▁beberapa ▁orang_ms ▁terbaik ku_ms ▁di_ms ▁sini_ms .
▁Aku_ms ▁perlu ▁buat ▁sesuatu_ms ▁untuk_ms ▁kembali ▁kepada_ms ▁se_ms dia kala . ▁Tolong , ▁tetap ▁di_ms ▁sini_ms .
▁Sen ti_ms asa_ms ▁mengambil ▁jalan ▁yang_ms ▁ting gi .
▁So alan ▁yang_ms ▁sangat_ms ▁bagus ▁Ada ▁so alan ▁lain ▁lagi_ms ▁tak_ms ? ▁ , ▁Siapa ▁dalam_ms ▁mind a nya_ms ▁mempunyai ▁so alan ▁yang_ms ▁sama ?
▁Dan_ms ▁jika_ms ▁kebenaran ▁itu_ms ▁membuat mu_ms ▁bahagia . ▁Aku_ms ▁akan_ms ▁ bantu .
▁... ▁Stor kie ▁Stor - le ngan .
▁Se_ms bab ▁aku_ms ▁adalah_ms ▁Ca stor ▁Tro y !
▁Se_ms an_ms . ▁Kita_ms ▁kawan . ▁Aku_ms ▁mahu ▁beritahu ▁kau_ms ▁secara ▁ber_ms de pan_ms .
▁Saya_ms ▁mungkin ▁seorang_ms ▁yang_ms ▁ber_ms dos a , ▁tetapi ▁tidak_ms ▁bi ada b .
▁Tidak_ms , ▁kau_ms ▁tidak_ms ▁faha m .
▁Dar i mana ▁kau_ms ? ▁Jika ▁kau_ms ▁tahu_ms , ▁kenapa ▁ber_ms ta_ms nya_ms ?
▁Let akan_ms ▁Te ting kap ▁Te ta_ms p
▁-- s ince = < version > ▁ja ng_ms ka_ms ▁hanya_ms ▁lalu an_ms ▁ke_ms ▁ . de b
▁Dan_ms ▁lihat , ▁lihat .
▁Saya_ms ▁akan_ms ▁beritahu ▁kamu_ms ▁seperti_ms ▁saya_ms ▁beritahu ▁yg ▁lain .
▁- ▁Ada ▁me_ms ja_ms ▁di_ms ▁ha_ms da_ms pan_ms ▁nan ti_ms .
▁Tidak_ms ▁dapat_ms ▁mem buka ▁sal uran ▁yang_ms ▁di_ms pil ih_ms ▁dengan_ms ▁format ▁video ▁yang_ms ▁di_ms pil ih_ms .
▁Mungkin , ▁Seperti ▁permainan ▁" Me ne bak ▁9 ▁sampai ▁5 ", ▁di_ms lihat ▁dari_ms ▁pen_ms ampi lan_ms mu_ms ▁apa_ms ▁kau_ms ▁pi ntar ?
▁Se_ms baik ▁saja ▁kita_ms ▁jumpa , ▁kita_ms ▁mati kan_ms ▁untuk_ms ▁selama nya_ms ▁dengan_ms ▁ BS - US B ▁yang_ms ▁sangat_ms ▁ber_ms har ga_ms .
▁Can on ▁B J C - 21 10
▁Hei ▁kau_ms ▁tahu_ms ▁Nick , ▁ini_ms ▁tidak_ms ▁lu cu ▁Bagaimana ▁kad ang_ms - ka_ms dang ▁kita_ms ▁tidak_ms ▁boleh ▁melihat ▁Itu_ms ▁adalah_ms ▁ti nda kan_ms ▁yang_ms ▁akan_ms ▁membantu ▁kita_ms ▁wa_ms lau pun_ms ▁itu_ms ▁mengha dang ▁te_ms pat ▁di_ms ha da_ms pan_ms ▁kita_ms
▁Jangan ▁buat ▁D H CP ▁untuk_ms ▁hos ▁de_ms nga ▁tag ▁di_ms tet apkan .
▁Ayo ▁masuk , ▁akan_ms ▁ku_ms ▁je_ms las kan_ms ▁padamu ▁a_ms gar ▁kau_ms ▁mengerti .
▁Se_ms baik ▁saja ▁awak_ms ▁selesai kan_ms ▁tu_ms gas , ▁kami_ms ▁akan_ms ▁ tang gal kan_ms ▁semua_ms ▁per_ms enja t ▁elektri k ▁itu_ms .
▁Bay angkan ▁-
▁Anda_ms , ▁sudah ▁tentu , ▁tidak_ms ▁mempunyai ▁pilihan .
▁Sekarang , ▁hanya_ms ▁kita_ms ▁yang_ms ▁ber_ms dir i ▁di_ms ▁antara ▁si_ms ▁ho do h ▁tu_ms ▁dan_ms ▁band ar_ms ▁10 ▁ju ta_ms ▁pen_ms du_ms duk .
▁Dia_ms ▁pasti ▁menyukai nya_ms .
▁Saya_ms ▁baru ▁mem bel inya ▁ kel mar in_ms .
▁Awak ▁terlalu ▁mu da_ms ▁untuk_ms ▁faha m .
▁- ▁Saya_ms ▁nak ▁pergi_ms .
▁Ata u ▁Mark ▁dan_ms ▁All an_ms ▁?
▁Tidak_ms ▁boleh ▁tapi s ▁menggunakan ▁ju lat ▁yang_ms ▁di_ms nya_ms ta_ms kan_ms .
▁Dengar lah_ms ▁beberapa ▁ki sah ▁heb at_ms .
▁Aku_ms ▁ingin_ms ▁mengatakan ▁ini_ms ▁ke_ms dat angan_ms ▁kedua .
▁Anda_ms ▁tahu_ms , ▁apabila ▁saya_ms ▁bang un ▁pagi ▁ini_ms ,
▁Ak ses ▁terminal ▁Uni x / Linux
▁Jika ▁aku_ms ▁boleh ▁sent uh_ms ... ▁mungkin ▁aku_ms ▁boleh ▁ja wa_ms b ▁so alan ▁kau_ms .
▁Cho o ▁mening gal ▁pe_ms tang ▁ta di_ms ?
▁Saya_ms ▁akan_ms ▁masa_ms k ▁untuk_ms ▁makan ▁malam .
▁Pas ukan ▁del ta_ms , ▁mu at_ms ▁tur un ▁selesai
▁Tapi_ms ▁must a hil ▁bagi ▁kami_ms ▁untuk_ms ▁bersama ▁kamu_ms ▁di_ms ▁sana
▁Jika ▁tidak_ms , ▁ten tera ▁Je pun_ms ▁tidak_ms ▁akan_ms ▁menye rah_ms ▁dalam_ms ▁hal ▁ini_ms .
▁Semua ▁orang_ms ▁di_ms ▁se_ms ki_ms tar ▁sini_ms ▁akan_ms ▁membantu ▁awak_ms ▁tak_ms ▁peduli ▁apa_ms ▁pun ▁yang_ms ▁terjadi .
▁ci pta ▁at las - lu_ms ar_ms - tali an_ms ▁untuk_ms ▁aplik asi ▁telefon ▁bi mbi t / G PS
▁- ▁Kemudian ▁dia_ms ▁akan_ms ▁mem oto ng_ms ▁za kar ▁pada_ms ▁cu ti_ms ▁kami_ms , ▁betul ?
▁Kau_ms ▁akan_ms ▁seg era ▁ber_ms uru san ▁dengan_ms ▁dia_ms .
▁Awak ▁bi ar_ms ▁pintu ▁ter_ms buka .
▁Ar o , ▁Ca ius , ▁Marcus , ▁Pas u kannya
▁Patrick . ▁Ini_ms ▁tun angan_ms ▁saya_ms .
▁Ju ara ▁Masa ▁De pan_ms ▁tangan ▁besi ?
▁Char t ▁tak_ms ▁boleh ▁melihat .
▁Tak_ms zia h ▁kamu_ms ▁di_ms har gai ▁tetapi ▁bantuan ▁kamu_ms ▁tidak_ms ▁perlu ▁melainkan ▁kamu_ms ▁boleh ▁men_ms ama kan_ms ▁rak yat ▁Amerika ▁yang_ms ▁ber_ms ta_ms nggu ng_ms ja_ms wa_ms b .
▁Tidak_ms lah_ms ▁su sah ▁mana_ms ▁Kalau ▁kau_ms ▁i_ms kut ▁cara nya_ms
▁Sam ▁tidak_ms ▁akan_ms ▁ingat ▁apa_ms - apa_ms .
▁Saya_ms ▁rasa ▁dunia ▁akan_ms ▁rasa ▁ber_ms mina t ▁untuk_ms ▁mendengar ▁peng_ms ak_ms uan ▁anak ▁perempuan ▁Matthias .
▁Jika ▁saya_ms ▁bercakap , ▁saya_ms ▁orang_ms ▁yang_ms ▁sudah ▁mati .
▁Ini_ms ▁boleh ▁menjadi_ms ▁masalah .
▁Se_ms ko lah_ms ▁ta mat , ▁tak_ms ▁ guna .
▁Se_ms ba_ms gai ▁gant inya , ▁di_ms bang un lah_ms ▁sebuah ▁pa tung ... ▁rak s asa_ms ▁sebagai ▁la_ms mbang ▁pel in_ms dung ▁ke_ms ra_ms ja_ms an_ms ▁kami_ms . ▁Sei ring ▁berjalan nya_ms ▁masa_ms , ▁ ip tek ▁pun ▁ber_ms ke mbang ▁pes at_ms , ▁tapi ... ▁ke_ms se_ms jah tera an_ms ▁ke_ms ra_ms ja_ms an_ms ▁pun ▁i_ms kut ▁tur un .
▁" O leh ▁itu_ms , ▁pergi_ms lah_ms ▁kamu_ms ▁berdua ▁kepada_ms nya_ms , ▁kemudian ▁katakan lah_ms : ▁" Ba ha wa_ms ▁sesungguhnya ▁kami_ms ▁ini_ms ▁Rasul - ras ul ▁dari_ms ▁Tuhan mu_ms , ▁maka ▁be bas kanlah ▁kau_ms m ▁Ba ni ▁l s ra_ms il ▁meng i kut ▁kami_ms , ▁dan_ms ▁jangan lah_ms ▁engkau ▁menye ksa kan_ms ▁mereka_ms .
▁Mana ▁Que en ?
▁Apa_ms ... ▁Apa_ms ▁maksud ▁kamu_ms ?
▁Ia ▁sangat_ms ▁ber_ms isi ko .
▁Jika ▁Bon nie ▁dapat_ms ▁ba_ms lik_ms ... ▁Awak ▁orang_ms ▁pertama ▁yang_ms ▁saya_ms ▁telefon .
▁Mak ▁cik ▁awak_ms ▁kata ▁awak_ms ▁yang_ms ▁ambil ▁dan_ms ▁si_ms mpan ▁bu ku_ms ▁itu_ms .
▁[ Me ngel uh_ms ] ▁mungkin ▁ini_ms ▁bukan_ms ▁je_ms nis ▁anda ▁kes .
▁Shi eld ▁ PE MB ENT UK AN !
▁Saya_ms ▁ben ci ▁untuk_ms ▁mengatakan ▁i_ms a .
▁Dar i ▁ya itu ▁ke_ms ger a man_ms ▁North men , ▁le pas kan_ms ▁kami_ms .
▁♪ ▁B right ▁light ▁♪
▁Dengan ▁ser ba_ms ▁ke_ms kurang an_ms , ▁saya_ms p ku_ms ▁ter_ms ikat .
▁Lihat ▁destina si_ms ▁dalam_ms ▁mind a .
▁Apa_ms ▁ini_ms , ▁Charlie ?
▁Jangan ▁putu s ▁asa ▁se_ms la_ms gi ▁belum ▁sampai ▁ke_ms ▁pun cak .
▁Aku_ms ▁tak_ms ▁mahu ▁Ju dy ▁Mon cada ▁mu la_ms ▁ber_ms ta_ms nya_ms ▁ber_ms und ing_ms ▁tentang ▁bahagia n nya_ms .
▁Si hat ▁ke_ms ▁se_ms men jak ▁dua ▁ni ?
▁Bi lik_ms ▁Ti dur ... ▁sebe lah_ms ▁kan an_ms .
▁Dia_ms ▁tidak_ms ▁mahu ▁mele pas kannya .
▁Be liau ▁mempunyai ▁vil a ▁lama ▁ini_ms ▁dari_ms ▁19 08 ▁dan_ms ▁bi lik_ms ▁bawah ▁tan ah_ms ▁yang_ms ▁men_ms ak_ms ju b kan_ms ▁ini_ms ▁dengan_ms ▁wa_ms in_ms ▁ini_ms ▁...
▁Saya_ms ▁perlu ▁ku_ms asa_ms i ▁tempat ▁mereka_ms .
▁Apa_ms ▁awak_ms ▁buat ?
▁Dia_ms ▁ber_ms u tang ▁kepada_ms nya_ms ▁sesuatu_ms ▁yang_ms ▁sah ▁secara ▁ hukum ... ▁Untuk ▁merasa ▁aman .
▁Aku_ms ▁merasa kan_ms ▁Sen at_ms ▁akan_ms ▁bun tu_ms ▁dalam_ms ▁pro se_ms dur ▁ini_ms .
▁Na nti ▁ke_ms ja_ms p , ▁kau_ms ▁maksud kan_ms ▁yang_ms ▁aku_ms ▁dalam_ms ▁per_ms bi cara an_ms ?
▁I zin kan_ms ▁saya_ms ▁membawa ▁anda ▁ke_ms ▁Co ch on .
▁Sam ▁tak_ms ▁peduli !
▁Mereka lah_ms ▁ah li_ms ▁ne raka , ▁mereka_ms ▁tetap ▁ke_ms kal ▁di_ms ▁dalam_ms nya_ms .
▁Pu tri nya_ms . .
▁Awak ▁yang_ms ▁ter_ms uk ▁menga_ms mu_ms k .
▁Jangan ▁salah kan_ms ▁aku_ms ▁kalau ▁Si d ▁han cur kan_ms ▁kamu_ms !
▁- ▁Kita_ms ▁ca but ▁und i .
▁B ing_ms kai ▁ut ama ▁adalah_ms ▁lebih an_ms ▁kap as iti
▁Cer min nya_ms ▁selalu ▁ko tor .
▁_ To ol bar
▁Ra sa_ms nya_ms ▁ka ca_ms ng_ms ▁la_ms .
▁Don nie ▁dan_ms ▁saya_ms , ▁kami_ms ▁me_ms la_ms bur ▁dalam_ms ▁pro jek ▁kon do ▁di_ms ▁Ve nice .
▁Adakah ▁kamu_ms ▁se_ms dar ▁tentang ▁aktiv iti ▁pen_ms ip uan ▁yg ▁di_ms uru s kan_ms ▁bagi ▁pi ha k ▁Ul ti_ms ma_ms ▁National ▁Re source s ? ▁- ▁Ban tahan .
▁Aku_ms ▁tak_ms ▁tahu_ms ▁bagaimana ▁nak ▁cakap ▁tapi ▁se_ms jak ▁ kej adian ▁di_ms ▁Pu lau ▁Liber ty ...
▁Ini_ms ▁S acha ▁Pfeiffer .
▁Jadi ▁tak_ms ▁ada_ms ▁seorang_ms ▁pun ▁mahu ▁cakap ▁apa_ms ▁yang_ms ▁sedang ▁berlaku ?
▁- ▁' Ma tter ' ▁Sam bung an_ms !
▁Kalau ▁begitu , ▁bagus .
▁Apa_ms ▁ guna nya_ms ▁pergi_ms ▁ke_ms ▁Florida ... ▁kalau ▁awak_ms ▁pak ai ▁kri m ▁pel in_ms dung ?
▁Mungkin ▁nama ▁awak_ms .
▁je_ms t ▁itu_ms ▁sudah ▁mendapat ▁sur at_ms ▁aku_ms an_ms .
▁- ▁Kita_ms ▁mana_ms ▁ada_ms ▁radio .
▁Mengapa ▁i_ms a ▁di_ms luk ai ?
▁Se_ms ba_ms gai ▁wa_ms kil ▁Stark ▁Industri es ,
▁MiB
▁Se_ms ti_ms ap ▁kali ▁ada_ms ▁kamera ▁mengha la_ms ▁ke_ms ▁a_ms rah_ms ▁saya_ms ...
▁Saya_ms ▁akan_ms ▁ta nya_ms ▁awak_ms ▁sekali ▁lagi_ms .
▁Kami_ms ▁ingin_ms ▁anda ▁sa bo taj ▁kem uda han_ms ▁peng_ms awa san ▁pus at_ms ▁Good chi ld ▁ini_ms .
▁Aku_ms ▁har ap ▁kau_ms ▁betul ▁Ka veri .
▁- Ka mi_ms ▁yang_ms ▁di_ms per ca_ms ya i ▁pe_ms gua m ▁kami_ms .
▁Semua nya_ms ▁to long ▁ke_ms bela kan_ms g ▁du lu_ms , ▁ber_ms hati - hati .
▁Da lam ▁ti ga_ms ▁jam .
▁Big fo ot ▁di_ms ▁O zar ks .
▁Ia ▁me_ms let up , ▁dan_ms ▁bang sal ▁itu_ms ▁hampi r ▁ter_ms ba_ms kar ▁di_ms se_ms bab kan_ms ▁ kej adian ▁itu_ms .
▁Aku_ms ▁nak ▁cakap ▁d gn ▁kau_ms ▁Mei ▁L ing_ms .
▁Nama ste ▁( sala m ) , ▁Sim ran
▁Yeah .
▁Se_ms ta_ms kat ▁ni , ▁sangat_ms ▁je_ms las .
▁( M US IC ▁D RAM ATI K )
▁Si al_ms ▁yeah , ▁James .
▁Se_ms orang ▁wanita ▁biasa nya_ms ▁akan_ms ▁menunjukkan ▁per_ms asa_ms annya ▁lebih ▁banyak_ms ▁dari_ms ▁yang_ms ▁dia_ms ▁rasa kan_ms .
▁- ▁Kami_ms ▁model ▁ram but ▁dari_ms ▁Belgi um .
▁En tah lah_ms .
▁Thank s ▁lagi_ms ▁untuk_ms ▁semuanya . ▁Sara .
▁Itu_ms ▁sebab nya_ms ▁saya_ms ▁mengambil nya_ms .
▁Kita_ms ▁ter_ms pak sa_ms ▁bergerak ▁ke_ms ▁ha_ms da_ms pan_ms , ▁ser ta_ms - mer ta_ms .
▁- ▁Mas uk kan_ms ▁log ik ▁ke_ms ▁dalam_ms ▁o tak nya_ms .
▁- ▁Dan_ms ▁untuk_ms ▁tempo h ▁40 ▁tahun ▁akan_ms ▁datang ...
▁Te ta_ms pi ▁dia_ms ▁menga_ms wal ▁per_ms dag angan_ms ▁senjata ▁haram ▁di_ms ▁Con go ▁selama ▁ber_ms ta_ms hun - ta_ms hun .
▁Dan_ms ▁aku_ms ▁mahu ▁kau_ms ▁ambil ▁ini_ms ▁untuk_ms ▁kalau ▁ada_ms ▁ke_ms cem asan .
▁- ▁A ▁si_ms far ▁gra viti ▁'
▁- ▁salah ▁kau_ms ▁karena ▁menga_ms ba_ms ikan_ms ▁aku_ms !
▁C loud , ▁di_ms ▁mana_ms ▁awak_ms ?
▁Se_ms be lah_ms ▁kan an_ms ▁saja .
▁Dia_ms ▁sudah ▁pergi_ms , ▁Barry .
▁OK , ▁nas ib ▁baik_ms
▁Et n ologi , ▁sebenarnya .
▁Dan_ms ▁kau_ms , ▁Pak , ▁telah_ms ▁dia_ms m bil ▁ter_ms ke jut .
▁Kami_ms ▁pergi_ms ▁ke_ms ▁Hong ▁Kong , ▁Sep any ol , ▁Bueno s ▁Air es , ▁ke_ms ▁mana_ms ▁saja ▁yang_ms ▁di_ms ar_ms ahkan ▁oleh ▁bo s ▁kami_ms .
▁- ▁Saya_ms ▁hanya_ms ▁pe_ms mand u .
▁Awak ▁mungkin ▁mati ▁hari ▁ini_ms .
▁Nam pak nya_ms , ▁kerja ▁saya_ms ▁yang_ms ▁jadi kan_ms ▁Ron nie ▁begin i . ▁dan_ms ▁jadi kan_ms ▁Martin ▁Ste in_ms ▁begin i .
▁Kami_ms ▁juga_ms ▁akan_ms ▁membawa ▁pulang ▁per_ms ka_ms kas mu_ms .
▁Ke_ms dat angan_ms ▁awak_ms ▁ini_ms ▁membuat kan_ms ▁ha_ms ti_ms ▁saya_ms ▁ber_ms bung a - bung a .
▁" Ja wa_ms b lah_ms : ▁" Ya , ▁de_ms mi_ms ▁Tuhan ku_ms ! ▁ Sesungguhnya ▁adalah_ms ▁i_ms a ▁benar !
▁Sekarang ▁le tak ▁kepala ▁atas ▁ba_ms hu ▁mereka_ms .
▁Dengar , ▁saya_ms ▁nak ▁tahu_ms ▁ra nc angan_ms ▁romp akan_ms ▁se_ms ter us_ms nya_ms . ▁Bila ?
▁Hi du_ms p kan_ms ▁bun yi ▁permainan
▁Se_ms su ci nya_ms ... ▁dan_ms ▁le mbu t ▁seperti_ms ▁a_ms wan .
▁Dia_ms ▁mengg oda ▁aku_ms ▁seperti_ms ▁orang_ms ▁as ing_ms .
▁Jangan ▁masuk ▁camp ur , ▁Ha ley .
▁Okay , ▁ali h kan_ms ▁per_ms hati an_ms . ▁apa_ms ?
▁Ia ▁tak_ms ▁boleh ▁di_ms ter ba_ms lik_ms kan_ms .
▁Katakan lah_ms ▁lagi_ms : ▁" Ba gai mana ▁fikir an_ms ▁kamu_ms ▁jika_ms ▁Al - Q uran ▁ini_ms ▁( yang ▁datang nya_ms ) ▁dari_ms ▁Allah_ms ▁dan_ms ▁kamu_ms ▁meng ing_ms kari nya_ms , ▁pada_ms ▁hal ▁ada_ms ▁seorang_ms ▁sa ksi ▁dari_ms ▁Ba ni ▁Is ra_ms il ▁memberi ▁ke_ms ter angan_ms ▁menga_ms ku_ms i ▁( sah nya_ms ▁Kitab ) ▁yang_ms ▁sama ▁seperti_ms ▁Al - Q uran ▁ini_ms , ▁lalu ▁i_ms a ▁percaya kan_ms ▁( Al - Q uran ▁ini_ms ▁dari_ms ▁Allah_ms ) , ▁sedang ▁kamu_ms ▁dengan_ms ▁som bo ng_ms ▁ ang_ms ku_ms h ▁meng ing_ms kari nya_ms ? ▁( Ti dak kah_ms ▁dengan_ms ▁yang_ms ▁demikian ▁kamu_ms ▁ber_ms si_ms fat ▁za lim ) ?
▁Maaf , ▁bergerak ▁di_ms ▁atas .
▁Katakan ▁pada_ms ▁mereka_ms ▁musi m ▁din gin ▁mengha m piri ▁kla n ▁Fre y .
▁Ju rus ▁ke_ms ▁10 , ▁Se_ms pul uh_ms ▁ ribu ▁Bu dd ha .
▁Tek n ologi ▁peng_ms awa san ▁ini_ms ▁memang ▁heb at_ms .
▁- A paka h ▁Maj lis ▁itu_ms ?
▁Am bil ▁file m ▁si_ms al_ms ▁itu_ms .
▁Bar u lah_ms ▁boleh ▁pu kul ▁bola .
▁Kau_ms ▁tahu_ms ▁apa_ms ▁yang_ms ▁aku_ms ▁ingat ?
▁Kita_ms ▁kena ▁per_ms tahan kan_ms ▁diri_ms .
▁Oh , ▁God . Lo ok ▁saya_ms ▁di_ms ▁ini_ms !
▁" O h , ▁put era ▁ku_ms , ▁datang ▁untuk_ms ▁aku_ms !
▁Aku_ms ▁akan_ms ▁memberitahu ▁bi bi ▁bahawa ▁anda ▁pergi_ms ▁ke_ms ▁Masa ke i ▁dengan_ms ▁ra kan_ms ▁mi nggu ▁lalu .
▁Mereka ▁adalah_ms ▁te_ms ta_ms mu_ms ▁kami_ms .
▁Awak ▁ber_ms hara p ▁dia_ms ▁akan_ms ▁mati .
▁- ▁Ber_ms s yu kur lah_ms , ▁dia_ms ▁menyelamatkan ▁awak_ms .
▁Aku_ms ▁nampak ▁banyak_ms ▁pen_ms ja_ms ga_ms , ▁berse nja ta_ms ▁can ggi h .
▁Ay uh_ms !
▁- ▁Saya_ms ▁rasa ▁ber_ms tu_ms ah_ms .
▁Jadi ▁mari ▁kita_ms ▁ken al_ms ▁pasti .
▁Yeah .
▁Apa_ms ▁yang_ms ▁salah nya_ms ?
▁Dar i ▁apa_ms ▁yang_ms ▁kami_ms ▁datang ▁kem ari .
▁ Sesungguhnya ▁sem_ms uli a - mu_ms lia ▁kamu_ms ▁di_ms ▁si_ms si_ms ▁Allah_ms ▁ialah ▁orang_ms ▁yang_ms ▁lebih ▁ta q wa_ms nya_ms ▁di_ms ▁antara ▁kamu_ms , ▁( bu kan_ms ▁yang_ms ▁lebih ▁ket uru nan ▁atau ▁bang sa_ms nya_ms ) .
▁Ma lah_ms ▁awak_ms ▁tidak_ms ▁mempunyai ▁po ko k .
▁Orang ▁Amerika ▁menghi m pun_ms ▁a_ms set ▁a_ms ngkat an_ms ▁la_ms ut_ms ▁di_ms ▁Pas ifik .
▁Ata u ▁saya_ms ▁dapat_ms ▁buat ▁akan_ms ▁ tang gal kan_ms ▁sel uar ▁di_ms ▁ha_ms da_ms pan_ms ▁pas ukan ▁bola ▁ta mpar ▁wanita .
▁Ke_ms kas ih_ms ▁kau_ms ▁orang_ms ▁lain
▁Orang ▁band ar_ms ▁ini_ms ▁perlu kan_ms ▁per_ms lin dung an_ms , ▁dan_ms ▁kalau ▁kamu_ms ▁tak_ms ▁dapat_ms ▁ke_ms pan_ms tas an_ms ▁kamu_ms , ▁bagaimana ▁kamu_ms ▁nak ▁pasti kan_ms ▁mereka_ms ▁selamat ?
▁Bila ▁awak_ms ▁mu la_ms kannya , ▁tiada ▁jalan ▁untuk_ms ▁pat ah_ms ▁ba_ms lik_ms .
▁Apa_ms ▁awak_ms ▁buat ?
▁Kami_ms ▁mendengar ▁ber_ms u lang_ms ▁kali ▁daripada ▁N F L , ▁anda ▁senti asa_ms ▁meng ka_ms ji , ▁anda ▁senti asa_ms ▁men_ms cu ba_ms .
▁Hanya ▁anak - anak ▁org ▁Je pun_ms ▁yg ▁mendapat ▁pel u ang_ms ▁ini_ms
▁Aku_ms ▁mengu bur ▁ paka ian ▁dan_ms ▁se_ms pat u nya_ms ▁men_ms dir ikan_ms ▁bat u ▁ni san ▁ini_ms . ▁Se_ms kurang - kurang nya_ms ...
▁" Da pat kan_ms ▁de_ms gu pan_ms ▁ jan tung ▁saya_ms ▁untuk_ms ▁menge lu_ms h ."
▁Awak ▁meno lak ▁melakukan ▁apa_ms - apa_ms ▁yang_ms ▁ada_ms ▁di_ms ▁luar ▁zon ▁sele sa_ms ▁awak_ms .
▁Jika ▁ada_ms ▁kem ung kin an_ms ▁mereka_ms ▁mengatakan ▁yang_ms ▁sebenarnya ▁--
▁Seperti ▁yang_ms ▁baik_ms ▁sebagai ▁em as ▁sin ga_ms ▁ini_ms , ▁ti ba_ms - ti_ms ba_ms "
▁Siapa ▁kita_ms ▁di_ms ▁sm ji e Â  i ?
▁Ten tang ▁ku_ms li_ms ah_ms
▁Adakah ▁saya_ms ▁kelihatan ▁se_ms parti ▁gadis ▁re ma_ms ja_ms ?
▁Awak ▁hanya_ms ▁pergi_ms ▁dan_ms ▁lakukan_ms ya ?
▁Sam pul ▁7 x 9 paper ▁size
▁Keluar ga_ms ▁saya_ms ▁akan_ms ▁cari ▁saya_ms .
▁Jangan ▁buat ▁begin i ▁lagi_ms .
▁Si la_ms ▁ny ata kan_ms ▁Kom en ▁kamu_ms ,
▁Saya_ms ▁akan_ms ▁pergi_ms ▁ke_ms ▁D . A . ▁ ,
▁Di ▁mana_ms kah_ms ▁i_ms a ?
▁Mer oko k ▁di_ms ▁se_ms ki_ms tar ▁bud ak_ms - bud ak_ms ▁na ga_ms ?
▁- ▁Aku_ms ▁tak_ms ▁percaya ▁ini_ms !
▁Peng hina an_ms ▁apa_ms kah_ms ▁ini_ms ▁hanya_ms ▁untuk_ms ▁kesalahan ▁kecil ?
▁- ▁Saya_ms ▁nak ▁vod ka_ms ▁mar tini , ▁to long .
▁Fe a ther , ▁kami_ms ▁ingin_ms ▁mena nya_ms kan_ms mu_ms ▁beberapa ▁per_ms tany aan ▁tentang ▁De an_ms ▁Mun sh .
▁Kami_ms ▁li mpah kan_ms ▁ rah_ms mat ▁Kami_ms ▁kepada_ms ▁sesiapa ▁sahaja ▁yang_ms ▁Kami_ms ▁ke_ms hen daki , ▁dan_ms ▁Kami_ms ▁tidak_ms ▁menghi lang_ms kan_ms ▁bala san ▁baik_ms ▁orang_ms - orang ▁yang_ms ▁berbuat ▁ke_ms ba_ms ikan_ms .
▁Tuhan ▁yang_ms ▁mengu asa_ms i ▁segala ▁a_ms lam ▁lang it ▁dan_ms ▁bu mi_ms .
▁- ▁Kenapa ▁sekarang ▁baru ▁se_ms dar ?
▁$ ▁20 0,000 , ▁di_ms ▁sini_ms ▁i_ms a ▁adalah_ms
▁Se_ms be lum ▁mu lut ▁awak_ms ▁me_ms let up , ▁Mi ck .
▁Ya_ms , ▁Michael , ▁se_ms ju jur nya_ms , ▁aku_ms ▁juga_ms ▁ter_ms ke jut ▁dengan_ms ▁ke_ms bo le han_ms mu_ms .
▁Sa ke ▁hu jah , ▁seseorang ▁se_ms lain ▁daripada ▁dengan_ms ▁be liau ?
▁Pi ha k ▁Ke_ms mente rian ▁mengha ntar ▁abu ▁dia_ms ▁pada_ms ▁saya_ms .
▁Bag us_ms , ▁jadi ▁ini_ms lah_ms ▁has il nya_ms ▁bekerja s ama .
▁Sen ara i ▁item text attr
▁Mala m ▁men_ms jel ma_ms ;
▁La du_ms ▁u dang .
▁Saya_ms ng_ms , ▁kau_ms ▁mem anja kan_ms ku_ms .
▁Saya_ms ▁ingin_ms ▁kembali kan_ms ▁ini_ms ▁pada_ms ▁kamu_ms ▁tad inya , ▁tapi ▁saya_ms ▁lihat ▁hal ▁men_ms curi ga_ms kan_ms ▁di_ms ▁ ling karan ▁kamera ▁kamu_ms .
▁Dia_ms ▁tak_ms ▁boleh ▁bela jar ▁menga_ms wal ▁ke_ms tag ih_ms nya_ms ▁terhadap ▁da rah_ms ▁jika_ms ▁dia_ms ▁tidak_ms ▁merasa ▁ket agi han_ms nya_ms ▁terhadap ▁da rah_ms .
▁" Ka mi_ms ▁sedang ▁mencari ▁Var ian , " ▁kemudian ▁saya_ms ▁kata ,
▁- ▁Awak ▁cuma ▁perlu ▁ber_ms ten ang_ms .
▁Di ▁sebuah ▁ke_ms da_ms i ▁pa jak ▁gada i ▁buruk ▁sekali ▁di_ms ▁te_ms nga h .
▁Ka rena ▁aku_ms ▁tidak_ms ▁ingin_ms ▁mengetahui ▁kita_ms ▁punya ▁per_ms a hu ▁pen_ms uh_ms ▁nu gge t ▁di_ms ▁te_ms nga h ▁keadaan ▁dar ura t .
▁Aku_ms ▁ber_ms ja_ms nji ▁akan_ms ▁mengha ntar ▁kepada_ms ▁kamu_ms .
▁Saya_ms ▁buat ▁kerja ▁sia - sia ▁tanpa ▁up ah_ms .
▁Ra cun ▁tik us_ms ▁dapat_ms ▁bere a ksi ▁karena ▁tik us_ms ▁tidak_ms ▁memiliki ▁refl eks ▁me_ms mbu al_ms .
▁Tapi_ms ▁kau_ms ▁tak_ms ▁akan_ms ▁meng hen tika nku ?
▁Ju te , ▁pergi_ms !
▁ Sesungguhnya , ▁hanya_ms ▁se_ms la_ms gi ▁saya_ms ▁tidak_ms ▁le wat ...
▁Car a ▁hidup ?
▁Am bil ▁ke_ms nya_ms taan ▁mereka_ms .
▁Anda_ms ▁akan_ms ▁me_ms landa ▁kami_ms ?
▁Kamu ▁semua_ms , ▁ay uh_ms !
▁aku_ms ▁selalu ▁ber_ms fik ir ▁bahawa ▁kau_ms ▁boleh ▁mungkin ▁menggunakan ▁bur ung ▁mati ▁Da lam ▁sup ▁atau ▁sesuatu_ms .
▁Kamu ▁ tum buk ▁si_ms ▁ga y ▁ne gro ▁tu_ms ▁te_ms pat ▁di_ms ▁muka , ▁dan_ms ▁itu_ms ▁bukan_ms ▁kali ▁kedua ▁berlaku .
▁Ca i ▁Ma o ▁dan_ms ▁Z hang ▁Y un , ▁Di ▁sini_ms ,
▁Pa da_ms ▁masa_ms ▁ini_ms , ▁mak hlu k ▁yang_ms ▁akan_ms ▁ke_ms ▁ hulu ▁sun gai ▁No mi_ms ▁itu_ms .
▁Nama kan_ms ▁sem_ms ula ▁te_ms ting kap ▁'% s ' ▁ke_ms ▁(1 -3 ▁ aks ara )
▁♪ ▁Di ▁mana_ms ▁ju a ▁kamu_ms ▁berada ▁♪
▁Mereka ▁me_ms sti ▁men_ms di_ms am kan_ms .
▁Na ina , ▁anda ▁dan_ms ▁saya_ms ▁akan_ms ▁menye r bu ▁guda ng_ms ▁pe_ms nia ga_ms .
▁Bagaimana ▁saya_ms ▁boleh ▁ber_ms i ▁dia_ms ▁ jan tung ▁yang_ms ▁le mah ▁ini_ms , ▁mak ?
▁Saya_ms ▁menga_ms r ahkan ▁DNA ▁be liau ▁di_ms mus n ahkan .
▁Men ung gang ▁ hina , ▁ rank est , ▁yang_ms ▁ku_ms da_ms ▁na sti est .
▁# ▁Ter da_ms pat ▁bu nga ▁tun as ▁dan_ms ▁saya_ms ▁gi la_ms ▁pada_ms nya_ms ▁#
▁- ▁Tak_ms ▁ada_ms ▁apa_ms .
▁- Ma mpu s lah_ms .
▁Saya_ms ▁ben ci ▁untuk_ms ▁pay uda ra_ms ▁gele m bung ▁anda , ▁tetapi ▁jika_ms ▁anda ▁mem bina ▁rumah ▁ini_ms ▁kecil , ▁siapa ▁yang_ms ▁akan_ms ▁hidup ▁dalam_ms ▁' em ?
▁Saya_ms ▁telah_ms ▁dua ▁kali ▁untuk_ms ▁album ▁itu_ms ▁untuk_ms ▁mendengar .
▁Apa_ms , ▁awak_ms ▁lu pa_ms ▁nak ▁per_ms i ksa ▁jika_ms ▁tu_ms dung ▁kepala ▁dia_ms ▁tak_ms ▁ter_ms buka ?
▁Shu t ▁per_ms nia gaan ▁da dah ▁ke_ms ▁bawah . ▁Pot ong ▁i_ms a ▁mati , ▁dan_ms ▁saya_ms ▁akan_ms ▁melakukan ▁apa_ms ▁sahaja ▁yang_ms ▁anda ▁mahu .
▁ Sesungguhnya ▁engkau ▁( wa_ms hai ▁Muhammad ) ▁hanya_ms lah_ms ▁memberi ▁per_ms ing_ms atan ▁kepada_ms ▁orang_ms - orang ▁yang_ms ▁takut ▁( me lang_ms gar ▁ hukum - hukum ) ▁Tuhan ▁sem_ms asa_ms ▁mereka_ms ▁tidak_ms ▁di_ms lihat ▁orang_ms ▁dan_ms ▁sem_ms asa_ms ▁mereka_ms ▁tidak_ms ▁melihat ▁azab ▁Tuhan , ▁ser ta_ms ▁mereka_ms ▁men_ms dir ikan_ms ▁sem_ms bah yang . ▁Dan_ms ▁sesiapa ▁yang_ms ▁members ih_ms kan_ms ▁diri_ms nya_ms ▁( dari ▁segala ▁yang_ms ▁di_ms lar ang_ms ) ▁maka ▁sesungguhnya ▁i_ms a ▁melakukan ▁p ember si_ms han_ms ▁itu_ms ▁untuk_ms ▁ke_ms ba_ms ikan_ms ▁diri_ms nya_ms ▁sendiri ▁dan_ms ▁( ing_ms at_ms lah_ms ) , ▁kepada_ms ▁Allah_ms ▁ju a lah_ms ▁tempat ▁kembali .
▁Taylor , ▁aku_ms ▁ mohon !
▁Kita_ms ▁akan_ms ▁to lak ▁mereka_ms ▁di_ms ▁hu jung ▁jalan !
▁- ▁Dan_ms ▁tunggu ▁panggil an_ms ▁saya_ms .
▁Tam b ahkan ▁ke_ms ▁Pro jek
▁Kan _ dung an_ms
▁Ada ▁lagi_ms ▁ter_ms uk .
▁Maks ud ▁kamu_ms . .
▁Ali h ▁ke_ms ▁hala man_ms ▁pertama ▁do ku_ms men
▁Ini_ms ▁yang_ms ▁pertama ▁kali ▁kami_ms ▁temu i ▁di_ms ▁sini_ms .
▁Sa kit ▁ke_ms ?
▁tidak_ms ▁dapat_ms ▁gen ▁pri me ▁dengan_ms ▁p bit s =% u ▁q bit s =% u
▁Kau_ms ▁jangan ▁bay ar_ms ▁kepada_ms ▁seorang_ms ▁lelaki ▁yang_ms ▁di_ms hor mati .
▁Be liau ▁telah_ms ▁takut ▁se_ms jak ▁malam ▁itu_ms .
▁Mala m ▁itu_ms , ▁satu_ms ▁ke_ms ba_ms ikan_ms ▁sudah ▁mem pen gar u hi ▁yang_ms ▁lain .
▁[ OPTION ... ] ▁< de vice >
▁Pel u ang_ms ▁ak hir , ▁To zi er .
▁X iau ▁He , ▁sampai ▁mati pun_ms ▁akan_ms ▁melindungi ▁X ian yang . ▁Ke_ms pala ▁boleh ▁putu s , ▁da rah_ms ▁boleh ▁menga_ms li_ms r , ▁me_ms ski pun_ms ▁mati ▁tidak_ms ▁akan_ms ▁menye rah_ms !
▁Ram pas an_ms ▁ba_ms jak ▁la_ms ut_ms !
▁- ▁Hanya ▁menu angkan nya_ms ▁ .
▁' ▁Terima ▁kasih .
▁Yeah .
▁bukan_ms ▁kita_ms ▁sahaja . ▁Kita_ms ▁tahu_ms ▁tentang ▁itu_ms ▁kan ?
▁Aku_ms ▁suka ▁per_ms tar ung an_ms ▁yang_ms ▁bagus , ▁tapi ▁ini_ms ▁sangat_ms ▁buruk ▁untuk_ms ▁bis nes ▁aku_ms .
▁Fi ji z aire 2006 . ▁kgm
▁Lebih ▁baik_ms ▁saya_ms ▁sendiri .
▁Ya_ms , ▁kita_ms ▁be bas .
▁Ada ▁semua_ms ▁orang_ms ▁dari_ms ▁go long an_ms ▁Wall ▁Street ▁kepada_ms ▁rak yat ▁di_ms ▁jalan - ja_ms lan_ms , ▁kepada_ms ▁anak - anak ▁akan_ms ▁ke_ms ▁kon sert , ▁yang_ms ▁sto ner s .
▁Untuk ▁di_ms paka i ▁di_ms ▁jam uan ▁makan ▁malam .
▁Ad rian , ▁di_ms ▁mana_ms ▁mereka_ms ? ▁!
▁Dis e ba_ms lik_ms ▁per_ms saha ba_ms tan_ms ▁ini_ms ▁ter_ms se_ms mbu ny_ms i ▁per_ms cin taan .
▁Dia_ms ▁datang ▁es ok .
▁Nam pak ▁seperti_ms ▁Da tuk ▁Band ar_ms ▁tahu_ms ▁beberapa ▁perkara ▁yang_ms ▁le pas ▁dan_ms ▁ber_ms sungguh - sungguh ▁untuk_ms ▁menye mbu ny_ms ikan_ms ▁fakt a ▁itu_ms , ▁bahkan ▁dari_ms ▁ SC PD .
▁Kamu ▁ lari ▁ke_ms ▁ting kap ▁dan_ms ▁aku_ms ▁keluar ▁melalui ▁pintu
▁Ata u ▁pat ut_ms kah_ms ▁mereka_ms ▁de_ms ng_ms ki_ms ▁kepada_ms ▁manusia ▁( Na bi ▁Muhammad ▁dan_ms ▁uma t nya_ms ) ▁di_ms se_ms bab kan_ms ▁nik mat ▁( pa_ms ngkat ▁Na bi ▁dan_ms ▁u gama ▁Islam ) ▁yang_ms ▁telah_ms ▁di_ms ber ikan_ms ▁oleh ▁Allah_ms ▁kepada_ms ▁mereka_ms ▁dari_ms ▁li mpah ▁kur nia Nya ?
▁Tidak_ms , ▁Mr ▁Per ret . ▁saya_ms ▁tidak_ms ▁faha m .
▁Awak ▁sudah ▁gi la_ms , ▁De v ?
▁makan ▁si_ms kit ▁je_ms !
▁Tolong lah_ms ▁jangan ▁bu ang_ms ▁masa_ms , ▁Moj in_ms ▁X ia owe i , ▁Ja mba tan_ms ▁ nya_ms ▁re tak
▁Pe mu_ms kul , ▁pe_ms mu_ms kul . ▁Ne ▁ne ▁ne ▁ne .
▁♪ ▁- ▁A ngkat ▁tangan mu_ms . ▁- ▁Ben ar_ms !
▁saya_ms ▁tak_ms ▁tahu_ms ▁apa_ms ▁lagi_ms ▁yang_ms ▁lebih ▁bagus ▁se_ms lain ▁ini_ms .
▁Saya_ms ▁akan_ms ▁let up kan_ms ▁kereta ▁ke_ms bal ▁mereka_ms ▁atau ▁ba_ms wa_ms kan_ms ▁kepada_ms ▁kamu_ms ▁komand er ▁mereka_ms .
▁Awak ▁orang_ms ▁baru ▁di_ms ▁Famil a , ▁kan ?
▁Adakah ▁dia_ms ▁macam ▁King ▁Kong ?
▁Tapi_ms ▁apa_ms ▁yang_ms ▁Pre m ▁tahu_ms ?
▁Tidak_ms ▁boleh ▁mendapatkan ▁sem_ms ula ▁mes ej : ▁% s
▁ga gal ▁untuk_ms ▁un lock pt : ▁% s
▁Kamu ▁ada_ms I ah_ms ▁pe_ms ga_ms Wa i ▁atas an_ms ▁pada_ms ▁kes ▁ini_ms .
▁ya ▁ lah_ms ▁!
▁Ber_ms ita hu ▁aku_ms ▁apa_ms ▁yang_ms ▁berlaku ▁di_ms ▁pas ar_ms ▁ta di_ms .
▁Tak_ms rif ▁la_ms jur ▁"% ▁1" ▁tak_ms ▁sah
▁Anda_ms ▁ingin_ms ▁ber_ms do a ▁untuk_ms ▁per_ms lin dung an_ms ?
▁Dan_ms ▁Ayah ▁begitu ▁ keta ku_ms tan_ms .
▁A nak ▁itu_ms ▁men_ms ja_ms wa_ms b . ... ▁kerana ▁saya_ms ▁ya tim ▁sekarang .
▁Hent ikan_ms ▁ber_ms kela ku_ms an_ms ▁seperti_ms ▁' G abb ar_ms ▁Sin gh ' ▁( wa_ms tak ▁file m ▁l ndi a ) .
▁B ELL A TOR :
▁Anda_ms ▁gonna ▁membawa ▁ke_ms lda i ▁saya_ms ▁se_ms panja ng_ms ▁jalan ▁fuck ▁rumah .
▁Lebih ▁baik_ms ▁kita_ms ▁jadi kan_ms ▁dia_ms ▁sebagai ▁con to h ▁daripada ▁Du rant ▁yang_ms ▁jadi kan_ms ▁kita_ms ▁con to h .
▁Se_ms ti_ms ap ▁kali ▁i_ms a ▁sama ▁untuk_ms ▁dia_ms .
▁Dia_ms ▁akan_ms ▁memba yar ▁kita_ms ▁kembali ▁apabila ▁dia_ms ▁boleh .
▁Bila ▁kepala ▁seseorang ▁yang_ms ▁hi lang_ms ▁ingat an_ms ▁di_ms han_ms tuk , ▁ingat an_ms ▁dia_ms ▁akan_ms ▁pul ih_ms .
▁Ka wa_ms san ▁pen_ms cem aran ▁yang_ms ▁se_ms ma_ms kin ▁mening kat .
▁Ada ▁FBI ▁di_ms dalam . ▁Kamu ▁harus ▁tena ng_ms .
▁ GenericName
▁Saya_ms ▁tahu_ms , ▁Margaret .
▁- ▁Be lum ▁sem_ms ing_ms gu .
▁Dis e bab kan_ms ▁ka ka_ms k , ▁aku_ms ▁ak hir nya_ms ▁ber_ms kah_ms win . ▁Tiada ▁apa_ms ▁yang_ms ▁berlaku ▁di_ms se_ms bab kan_ms ▁a_ms bang .
▁Ada ▁kes ila pan_ms ▁dalam_ms ▁temp ahan ▁saya_ms .
▁Anda_ms ▁tahu_ms ▁apa_ms ?
▁Itu_ms ▁tidak_ms ▁' di_ms am ' .
▁- ▁Hi , ▁D . J !
▁L kan_ms ▁tak_ms ▁banyak_ms , ▁har ga_ms nya_ms ▁ kurang . ▁Har ga_ms ▁bor ong ▁jatuh .
▁Sem oga ▁ber_ms ge mbi ra_ms ▁di_ms ▁hu jung ▁mi nggu , ▁Ni na_ms ...
▁Saya_ms ▁tidak_ms ▁mahu ▁untuk_ms ▁mengatakan ▁i_ms a , ▁tetapi ▁saya_ms ▁mempunyai ▁per_ms asa_ms an_ms ▁yang_ms ▁tidak_ms - be gi tu_ms - se_ms gar .
▁Ber_ms tat ahkan ▁ber_ms li_ms an_ms ▁dalam_ms ▁ sorb annya ▁Anda_ms ▁ter_ms lihat ▁menga_ms gum kan_ms !
▁Se_ms benar nya_ms ▁bukan_ms ▁itu_ms ▁yang_ms ▁saya_ms ▁lakukan_ms .
▁Ada ▁senjata ▁bera t ▁tak_ms ?
▁Wo i , ▁dia_ms ▁bilang .
▁Mengapa ▁kau_ms ▁tidak_ms ▁meng iku ti_ms ▁kata ▁ha_ms ti_ms ?
▁Profesor , ▁teh ▁Ti bet ▁ini_ms ▁har um .
▁Jadi ▁kawan - ka_ms wan ".
▁Da hulu ▁seperti_ms ▁itu_ms
▁- ▁Hey . ▁Awak ▁dah ▁ba_ms lik_ms . ▁- ▁Sy u kur lah_ms .
▁Klik ▁sini_ms ▁untuk_ms ▁menu kar ▁ke_ms ▁ru ang_ms ker ja_ms ▁% s
▁Tidak_ms , ▁aku_ms ▁men_ms cu ba_ms .
▁Kamu ▁semua_ms ▁pernah_ms ▁ter_ms fik ir ▁tentang ▁ ikan_ms ?
▁Boleh kah_ms ▁saya_ms ▁membantu ▁anda ?
▁Ber_ms apa_ms ▁kali ▁Saya_ms ▁katakan ▁bahwa . .
▁Bukan ▁masa_ms ▁yang_ms ▁se_ms su ai untu k ▁pela nc aran ?
▁- I a ▁bergerak ▁seperti_ms ▁ri but .
▁Apa_ms ▁yang_ms ▁dia_ms ▁tengo k ?
▁Angel a ▁pe_ms tre lli ... ▁dia_ms ▁tahu_ms .
▁- ▁Ya_ms , ▁hi dung ... ▁da da_ms ...
▁Unit Al pha , anda di_ms benar kan_ms
▁di_ms ▁dalam_ms nya_ms -
▁- ▁Saya_ms ▁benar kan_ms ▁kamu_ms ▁masuk ▁rumah ▁saya_ms !
▁Apa_ms ▁yang_ms ▁boleh ▁saya_ms ▁katakan , ▁dia_ms ▁adalah_ms ▁sebagai ▁character less , ▁kerana ▁anak ▁perempuan nya_ms ▁adalah_ms ▁...
▁Ca kap ▁tu_ms an_ms . ▁- K esan ▁panggil an_ms ▁ini_ms ▁dan_ms ▁men_ms angkap nya_ms . ▁O key ▁tu_ms an_ms .
▁Na thi r ▁sedang ▁me_ms mer hati ▁kita_ms .
▁Ya_ms ▁Tuhan , ▁ini_ms ▁gi la_ms .
▁Hanya ▁supaya ▁anda ▁tahu_ms , ▁Bobby ,
▁Da rah_ms ▁kita_ms lah_ms ▁yang_ms ▁ditu mpah kan_ms , ▁orang_ms - orang ▁kita_ms lah_ms ▁yang_ms ▁mati .
▁Maks ud ku_ms , ▁kenapa ▁mereka_ms ▁tak_ms ▁membawa ▁ben da_ms ▁itu_ms ▁ke_ms ▁tempat ▁lain . ...
▁Dia_ms ▁jatuh ▁peng_ms san ▁sem_ms asa_ms ▁me_ms mas ak_ms ▁makan an_ms ▁untuk_ms ▁hari ▁jadi ▁mak !
▁Kami_ms ▁tidak_ms ▁akan_ms ▁me_ms mer lu_ms kan_ms ▁lagi_ms .
▁Ja na_ms ▁ime j ▁ber_ms dir i ▁sendiri ▁( men gan dung i ▁semua_ms ▁modul ) ▁dalam_ms ▁format ▁ter_ms pil ih_ms
▁Masa ▁pe_ms mu_ms li_ms han_ms ?
▁Per tu_ms tur an_ms ▁di_ms benar kan_ms .
▁Be tul ▁ke_ms , ▁aku_ms ▁tak_ms ▁akan_ms ▁ guna ▁ru ang_ms ▁yang_ms ▁banyak_ms ?
▁Men amp ung ▁% s ▁menggunakan ▁% s
▁Ya_ms , ▁maaf . ▁Saya_ms ▁per_ms asan ▁sem_ms asa_ms ▁saya_ms ▁me_ms meri ksa ▁awak_ms .
▁Ayah ▁lang s ung ▁tak_ms ▁ingat ▁me_ms me luk ▁Tan , ▁sebab ▁ayah ▁tak_ms ▁mahu ▁kamu_ms ▁ter_ms lu_ms ka_ms .
▁Saya_ms ▁boleh ▁melihat ▁awak_ms .
▁Saya_ms ▁melihat ▁anda ▁mempunyai ▁beberapa ▁masalah ▁bercakap ▁dengan_ms ▁sa s sy ▁kembali ▁ke_ms ▁sana , ▁kan ?
▁- Ge org ie .
▁Mr In gram , To be y Mar s hall ▁saya_ms per lum e min jam M usta ng_ms ▁anda ▁ber_ms lum ba_ms ▁De ▁Leon
▁- ▁Kevin , ▁itu_ms ▁Go mez .
▁Well , ▁saya_ms ▁tidak_ms ▁pernah_ms ▁melakukannya ▁sebelum ▁ini_ms ▁...
▁Ini_ms ▁ga m bar ▁saya_ms ▁ .
▁Boleh ▁awak_ms ▁to long ▁dia_ms ?
▁Dia_ms ▁nak ▁tidur , ▁pergi_ms lah_ms
▁Ten tang ▁ka ca_ms ▁mata ▁ini_ms .
▁Jadi ▁apa_ms ▁ke_ms du_ms du_ms kan_ms ?
▁Aku_ms ▁har ap ▁kau_ms ▁tak_ms ▁pergi_ms .
▁- ▁Apa_ms ▁pun ▁yang_ms ▁terjadi , ▁tak_ms ▁ada_ms ▁jalan ▁keluar .
▁Keluar kan_ms ▁fail ▁sem_ms asa_ms ▁dari_ms ▁re posit ori
▁- ▁Di jum pai ▁dalam_ms ▁to ng_ms ▁sa mpah .
▁Bagaimana ▁jika_ms ▁tiada ▁siapa ▁yang_ms ▁berjaya ?
▁Por . ▁Ini_ms ▁untuk_ms ▁awak_ms .
▁Apa_ms ▁ke_ms put us_ms an_ms mu_ms ?
▁' S wa_ms mi_ms ▁Var a dan anda ▁akan_ms ▁datang ▁ke_ms ▁Ten ka_ms si_ms '
▁Ang ▁Lee ▁adalah_ms ▁men_ms tor ▁saya_ms ▁dan_ms ▁juga_ms ▁keluarga ▁saya_ms
▁Park ▁Ha ...
▁Semua nya_ms ▁a_ms dil ▁ketika ▁ber_ms cin ta_ms !
▁tak_ms ▁berba lo i ▁lang s ung ▁jika_ms ▁nak ▁melindungi ▁kawan ▁kawan ▁awak_ms ▁awak_ms ▁ter_ms des ak_ms ▁sekarang ▁ni ▁dan_ms ▁jangan ▁fikir ▁awak_ms ▁akan_ms ▁ter_ms le pas
▁Dia_ms ▁akan_ms ▁gun akan_ms ▁per_ms mata ▁itu_ms ▁untuk_ms ▁diri_ms nya_ms ▁sendiri .
▁Jadi ▁i_ms a ▁adalah_ms ▁selamat ▁untuk_ms ▁membawa ▁masuk ▁Bis ho p ▁sekarang ?
▁Jangan ▁ber_ms bel anja , ▁per_ms lah_ms an_ms - lah_ms an_ms .
▁Saya_ms ▁akan_ms ▁mem bel ikan_ms ▁anda ▁sebuah ▁rumah ▁baru .
▁Awak ▁pat ut_ms ▁ber_ms bin ca_ms ng_ms ▁dengan_ms nya_ms ▁seperti_ms ▁orang_ms ▁de_ms wa_ms sa_ms ▁dan_ms ▁selesai kan_ms ▁masalah ▁kamu_ms .
▁- ▁Normal ▁la_ms ▁kalau ▁macam ▁tu_ms
▁Tolong lah_ms ▁keluar ▁dari_ms ▁sini_ms .
▁Har i ▁ini_ms ▁saya_ms ▁dapat_ms ▁pel u ang_ms ▁lakukan_ms ▁terbaik ▁dalam_ms ▁kerja ya .
▁- O ka_ms y , And y , me me luk ▁be liau .
▁Terima ▁kasih , ▁Sir ▁Gra ham .
▁Te ta_ms pan_ms ▁Ku ki_ms
▁Jika ▁Australia ▁ gol , ▁pen_ms al_ms ti_ms ▁ini_ms ▁akan_ms ▁di_ms ter us_ms kan_ms .
▁Kami_ms ▁mene mu_ms i ▁mereka_ms ▁me_ms man_ms jat ▁cenu ram .
▁Kamu ▁memang ▁polis , ▁kamu_ms ▁cuma ▁me_ms nya_ms mar ▁saja !
▁Ada ▁yang_ms ▁1 0,000 ▁dolar ▁?
▁Adakah ▁kau_ms ▁lu lus kan_ms ▁romp akan_ms ▁J eneral ?
▁Awak ▁pun ▁nampak ▁can tik .
▁Saya_ms lah_ms ▁yang_ms ▁mengha ntar ▁Sar jan ▁Ma jor ▁Se_ms o ▁keluar .
▁Tu tu_ms p - K er ja_ms ▁tidak_ms ▁meny oko ng_ms ▁a_ms tribut ▁ uri - ker ja_ms .
▁Na mun ▁demikian , ▁Terima ▁kasih .
▁Ter pu ji lah_ms ▁De wa_ms ▁Ke_ms ku_ms atan !
▁Ja rak ▁sebelum ▁ga ris ▁gri d ▁mene ga_ms k ▁pertama
▁Ini_ms ▁akan_ms ▁berlaku ▁pada_ms ▁bud ak_ms ▁ni .
▁Ser ta_ms ▁memberi nya_ms ▁re zek i ▁dari_ms ▁jalan ▁yang_ms ▁tidak_ms ▁ter_ms lin tas ▁di_ms ▁hat inya .
▁Bukan ▁ber_ms mak na_ms ▁dia_ms ▁pembunuh nya_ms .
▁saya_ms ▁membunuh ▁a_ms dik ▁saya_ms , ▁Oliver ...
▁Doktor ▁dah ▁pes an_ms ▁yang_ms ▁kamu_ms ▁tak_ms ▁boleh ▁keluar ▁dari_ms ▁rumah
▁Dan_ms ▁( ing_ms at_ms lah_ms ) ▁Allah_ms ▁senti asa_ms ▁melihat ▁apa_ms ▁yang_ms ▁kamu_ms ▁lakukan_ms .
▁- ▁Jika ▁itu_ms ▁berlaku ▁ ,
▁Na s ib ▁baik_ms ▁kau_ms ▁mena wan .
▁Jadi , ▁apa_ms ▁maksud ▁arti ▁dari_ms . . ... ▁kematian ?
▁Apa_ms ▁yang_ms ▁berlaku ... ?
▁Ko thanda m , ▁saya_ms ▁telah_ms ▁di_ms si_ms mpan ▁Ra do ▁men_ms on ton ▁bersama - s ama ▁dengan_ms ▁ge lang_ms ▁saya_ms , ▁membawa ▁yang_ms ▁terlalu
▁Dan_ms ▁tiada ▁seorang_ms pun_ms ▁orang_ms ▁Georgia ▁menjadi_ms ▁mang sa_ms .
▁- ▁ BAR RY :
▁Sau , ▁se_ms ma_ms lam ▁aku_ms ▁ada_ms ▁hal .
▁Sekarang ▁dia_ms ▁me_ms lang_ms gar ▁bat as !
▁Ayah ▁tunggu ▁kamu_ms ▁beritahu ▁ayah . ▁Tapi_ms ▁kamu_ms ▁tak_ms ▁juga_ms ▁beritahu ▁ayah ▁apa_ms ▁masalah nya_ms .
▁Kap al_ms ▁ter_ms bang ▁itu_ms , ▁Kau_ms ▁fikir ▁i_ms a ▁masih ▁boleh ▁ter_ms bang ?
▁Ama hle ▁ guna ▁el et rik ▁untuk_ms ▁t angkap ▁ca cing .
▁Pres iden , ▁kamu_ms ▁o key ?
▁Tuan ku_ms , ▁saya_ms ▁dah ▁berjaya ▁dapat_ms kan_ms ▁se_ms li_ms par ▁sebe lah_ms ▁lagi_ms .
▁Dar i ▁Don at_ms ello .
▁Te ta_ms pi ▁lang kah_ms ▁harus ▁punya i ▁Jika ▁perlu ▁ , ▁menye mai ▁aku_ms an_ms .
▁- ▁Oh , ▁Tuhan ▁saya_ms , ▁i_ms a itu ▁begitu ▁besar .
▁" 42 ..."
▁As al_ms nya_ms ▁dari_ms ▁Re vol usi ▁Ru sia , ▁19 17 .
▁Lihat ▁kedua - du_ms a ▁a_ms rah_ms ▁sebelum ▁me_ms lin tas ▁jalan
▁Saya_ms ▁ke_ms ▁sini_ms ▁untuk_ms ▁bertemu ▁tu_ms an_ms ▁kamu_ms
▁Mari ▁kita_ms ▁pergi_ms .
▁Tiada ▁apa_ms ▁yang_ms ▁ber_ms mu_ms la_ms .
▁Tak_ms , ▁beritahu ▁mereka_ms ▁yang_ms ▁se_ms benar .
▁Ber_ms ita ▁baik_ms , ▁Caroline .
▁Pel uru ▁itu_ms ▁melalui ▁Cor ky ▁yang_ms ▁ha_ms iran , ▁dan_ms ▁dia_ms ▁melakukan ▁sesuatu_ms ▁yang_ms ▁salah .
▁Maks ud ▁saya_ms , ▁kamu_ms ▁tidak_ms ▁tidak_ms ▁suka ▁seorang_ms ▁wanita ▁jika_ms ▁kamu_ms ▁telah_ms ▁membuat ▁yang_ms ▁banyak_ms ▁la_ms karan ▁untuk_ms nya_ms .
▁Aku_ms ▁menge ndar ai ▁tu_ms pai .
▁Ki las
▁Anda_ms ▁ber_ms nas ib ▁baik_ms ▁dan_ms ▁membunuh ▁seorang_ms ▁yang_ms ▁bodoh .
▁- ▁Ke_ms du_ms kaan .
▁- ▁saya_ms ▁tidak_ms ▁suka ▁ trakt ir .
▁Para ▁wanita ▁di_ms ▁rumah ▁ini_ms , ▁to long ▁jag a ▁gadis ▁ini_ms .
▁Ke_ms dia man_ms ▁2 11 ▁dalam_ms ▁kem aju an_ms .
▁Men ge ta_ms hui ▁bahawa ▁Pas i pha e ▁adalah_ms ▁ibu nya_ms ▁telah_ms ▁berubah ▁kepada_ms nya_ms .
▁Bos ▁saya_ms ▁akan_ms ▁bunu h ▁saya_ms . ▁Kamu ▁gi la_ms ▁ke_ms ▁Jer ?
▁Sekarang ▁berhenti ▁ber_ms ta_ms nya_ms ▁begitu ▁banyak_ms ▁so alan ▁dan_ms ▁mari ▁kita_ms ▁pergi_ms .
▁Bah asa_ms
▁Ha ti_ms - hati , ▁a_ms wa_ms s
▁Saya_ms ▁dari_ms ▁orang_ms - orang ▁China , ▁mereka_ms ▁ber_ms dir i ▁di_ms ▁sana .
▁Elle n ▁a_ms mat ▁meny us_ms ahkan , ▁Pat ty .
▁Di ▁sini_ms , ▁saya_ms ▁di_ms ▁sini_ms .
▁Saya_ms ▁har ap ▁kamu_ms ▁tidak_ms ▁let ih_ms .
▁Pu an_ms , ▁nom bor ▁aka un ▁yang_ms ▁pu an_ms ▁bagi ▁telah_ms ▁di_ms akse s ▁jam ▁10 : 00 ▁pagi ▁pada_ms ▁2 h b ▁Oktober ▁di_ms ▁A TM ▁di_ms ▁Pa na_ms ji .
▁Sen ara i ▁Mes ej ▁Ber_ms be ben ang_ms
▁Saya_ms ▁sebenarnya ▁rasa ▁kasih an_ms ▁dengan_ms ▁awak_ms .
▁- ▁Ia ▁hanya_ms ▁untuk_ms ▁dua ▁orang_ms .
▁Ad rian , ▁memberi ▁saya_ms ▁ime j ▁o tak .
▁Mereka ti_ms dak ▁pernah_ms ▁mem uja ▁untuk_ms ▁waktu ▁yang_ms ▁lama .
▁Tapi_ms ▁ada_ms ▁satu_ms ▁hal ▁yang_ms ▁penting .
▁Ha ti_ms - hati ▁dengan_ms ▁na ga_ms ▁itu_ms .
▁Dia_ms ▁ lah_ms ▁Pel in_ms dung ▁kamu_ms .
▁Dia_ms m lah_ms ▁di_ms ▁sini_ms , ▁jangan ▁bergerak .
▁Ga bung an_ms ▁TLS / LD AP S ▁tidak_ms ▁sah
▁Saya_ms ▁tiada ▁se_ms bar ang_ms ▁nit rat ▁jadi ▁saya_ms ▁ter_ms pak sa_ms ▁minta ▁dari_ms ▁ji ran ▁lain .
▁Saya_ms ▁perlu ▁ber_ms fik ir .
▁Yeah .
▁Apa_ms ▁ kha bar , ▁Tuan ?
▁Dr . ▁Fi s her ▁telefon .
▁Han tu_ms ▁keluar ▁dari_ms ▁mana_ms - mana !
▁Kalau ▁sele pas ▁waktu ▁sekolah ▁kau_ms ▁perlu ▁terus kan_ms ▁sehingga ▁7 : 00 ▁pagi . ▁Ke_ms tika ▁itu_ms , ▁baru ▁aku_ms ▁datang ▁selamat kan_ms ▁kau_ms .
▁Saya_ms ▁dengar ▁ada_ms ▁yang_ms ▁ter_ms ced era .
▁Saya_ms ▁hanya_ms ▁ingin_ms ▁hidup ▁macam ▁biasa .
▁Kenapa ? ▁Apa_ms ▁masalah nya_ms ?
▁Pergi ▁ber_ms main ▁dengan_ms ▁ibu ▁kau_ms .
▁Baiklah , ▁mari ▁ter_ms bang ▁An t - T ho ny_ms .
▁La ku_ms kan_ms ▁seperti_ms ▁yang_ms ▁aku_ms ▁katakan , ▁5 ▁ka ki_ms ▁tidak_ms ▁lebih , ▁tidak_ms ▁ kurang .
▁tapi ▁sebagai ▁polis , ▁saya_ms ▁ter_ms pak sa_ms ▁mengha da_ms pi ▁per_ms asa_ms an_ms ▁takut ▁tu_ms ▁itu_ms ▁ta nggu ng_ms ja_ms wa_ms b ▁kami_ms
▁Kem bali ▁ke_ms ▁la_ms dang ▁lu cu .
▁Jangan ▁sekali - kali ▁wa_ms lau pun_ms ▁si_ms as atan .
▁" ▁Dan_ms ▁wa_ms hai ▁kau_ms m ku_ms !
▁- ▁Ku pi kir ▁kau_ms ▁bilang ▁kau_ms ▁me_ms lar ikan_ms ▁diri_ms .
▁Ini_ms ▁bukan_ms ▁so al_ms ▁China , ▁kan ?
▁Na nti ▁mereka_ms ▁akan_ms ▁per_ms asan ▁kita_ms ▁bukan_ms ▁polis .
▁Saya_ms ▁tahu_ms ▁... ▁tetapi ▁saya_ms ▁mempunyai ▁satu_ms ▁lagi_ms ▁perkara ▁untuk_ms ▁memberi nya_ms .
▁Charlie , ▁panggil kan_ms ▁En rique :
▁Yo on ▁Do !
▁- ▁Car i ▁i_ms Po d ▁itu_ms .
▁Tu n juk kanlah ▁kepada_ms ku_ms ▁apa_ms ▁yang_ms ▁mereka_ms ▁telah_ms ▁ci pta kan_ms ▁dari_ms ▁bahagia n ▁bu mi_ms ▁ini_ms ? .
▁Ya_ms , ▁dia_ms ▁baru ▁lalu ▁sini_ms .
▁Mis a ▁meninggalkan ▁hak ▁pose s if ▁dari_ms ▁De ath ▁Note
▁Ma ▁Ri ... ▁kau_ms ▁ada_ms ▁di_ms ▁sana .
▁Mari ▁tinggal kan_ms ▁kap a ▁ini_ms !
▁Ker ana ▁awak_ms ▁dengan_ms ▁se_ms nga ja_ms ▁mengha n cur kan_ms ▁ke_ms bah agi aan ▁a_ms dik ▁saya_ms ▁yang_ms ▁ter_ms cin ta_ms .
▁Tiada ▁sesiapa ▁pernah_ms ▁ member us_ms ▁di_ms ▁sini_ms ▁selama ▁ber_ms ta_ms hun - ta_ms hun .
▁( M ere ka_ms ▁bukan_ms ▁sahaja ▁tidak_ms ▁percaya ▁tentang ▁hidup ▁sem_ms ula ) ▁bahkan ▁mereka_ms ▁tidak_ms ▁percaya ▁tentang ▁per_ms tem uan ▁dengan_ms ▁Tuhan nya_ms .
▁Se_ms ben tar . ▁Kita_ms ▁bunu h ▁seseorang , ▁kita_ms ▁dapat_ms ▁ny awa ▁mereka_ms ?
▁Dan_ms ▁kalau lah_ms ▁tidak_ms ▁kerana ▁kali mah ▁ket eta pan_ms ▁yang_ms ▁menjadi_ms ▁pe_ms m utus ▁( dari ▁Allah_ms , ▁untuk_ms ▁menang g uhkan ▁ hukum an_ms ▁hin gga ▁ke_ms ▁su atu ▁masa_ms ▁yang_ms ▁ter_ms ten tu_ms ) , ▁tentu lah_ms ▁dija t uhkan ▁azab ▁dengan_ms ▁ser ta_ms - mer ta_ms ▁kepada_ms ▁mereka_ms ▁( yang ▁berbuat ▁demikian ) .
▁Se_ms mi_ms nggu ▁sele pas ▁ser angan_ms ▁szám os ▁h ír ▁szó lt ▁ar ról , ▁gé pra b ló k nak ▁bahawa ▁banyak_ms ▁ra kan_ms - ra_ms kan_ms ▁berada ▁di_ms ▁Amerika ▁S yari kat .
▁- ▁Cum a ▁mereka_ms ▁ber_ms ti_ms ga_ms .
▁Kamu ▁ber_ms pel uh_ms .
▁Ka rena ▁aku_ms ▁mau ▁bilang , ▁jika_ms ▁kau_ms ▁akan_ms ▁mengatakan ▁iya , ▁Aku_ms ▁akan_ms ...
▁Okay ▁... ▁okay ▁Per ta_ms ma_ms ▁... ▁pertama ▁... ▁pertama !
▁- ▁Su ite ▁Pres iden .
▁Tidak_ms , ▁Kur asa_ms ▁dia_ms ▁sedang ▁non ton ▁sesuatu_ms ▁yang_ms ▁ ile gal
▁Saya_ms ▁akan_ms ▁jumpa ▁kamu_ms ▁sele pas ▁selesai .
▁Has bul lah_ms ▁Bin ▁Pi t ▁< se_ms bol \ @ ik hlas \ . com > , M er lim au . ▁Ber_ms ser ta_ms ▁do r ongan ▁daripada ▁ra kan_ms - ra_ms kan_ms .
▁Aku_ms ▁akan_ms ▁memang gil ▁untuk_ms ▁meminta ▁mereka_ms ▁untuk_ms ▁ber_ms si_ms ap - si_ms ap .
▁Baiklah , ▁10 ▁saat ▁untuk_ms ▁pergi_ms .
▁Saya_ms ▁boleh ▁mati ▁dalam_ms ▁cu aca ▁se_ms juk ▁ini_ms .
▁Seperti ▁hal nya_ms ▁O z ▁untuk_ms ▁Do ro thy .
▁Kau_ms ▁nak ▁men_ms en tang ▁aku_ms ?
▁Muhammad ▁Naj mi_ms ▁bin ▁Ah mad ▁Za bi di_ms , ▁Shar u zza man_ms ▁Ah mat ▁Ra s lan_ms EMAIL ▁OF ▁TRANSLATORS
▁( CH U C KL ES ) ▁Adakah ▁anda ▁kid din ▁' s aya ?
▁Ini_ms ▁adalah_ms ▁benar - benar ▁de_ms kat ▁di_ms ▁ha_ms ti_ms ▁saya_ms .
▁Ada ▁re rant ing_ms ▁dan_ms ▁da un .
▁- ▁D . J . ▁Kita_ms ▁akan_ms ▁le wat !
▁- ▁Tapi_ms , ▁tentu ▁awak_ms ▁sudah ▁tahu_ms .
▁Mac am ▁mana_ms ▁aku_ms ▁nak ▁menang ▁per_ms ang_ms ... ▁sedang kan_ms ▁aku_ms ▁tak_ms ▁d pt ▁melindungi ▁keluarga ▁aku_ms ?
▁ok , ▁pergi_ms ▁le tak ▁kereta ▁kamu_ms .
▁- ▁Kamu ▁akan_ms ▁suka ▁ada_ms ▁keluarga .
▁Saya_ms ▁tahu_ms ▁i_ms a ▁ke_ms den gar an_ms ▁seperti_ms ▁satu_ms ▁idea ▁yang_ms ▁pe_ms lik_ms .
▁Aku_ms ▁akan_ms ▁pu kul ▁kau_ms ▁dengan_ms ▁se_ms li_ms par . ▁Jangan ▁ ros akkan .
▁David , ▁si_ms la_ms ▁tur un kan_ms ▁dia_ms ▁di_ms ▁mana_ms ▁sahaja ▁di_ms ▁sini_ms
▁Apa_ms ▁yang_ms ▁kita_ms ▁pela jar i ▁hari ▁ini_ms ?
▁- ▁Oh , ▁Ca stor ▁Tro y !
▁North ▁2 -0 .
▁Adakah ▁dari_ms ▁kamu_ms ▁yang_ms ▁pernah_ms ▁ber_ms tu_ms kar ?
▁Tak_ms ▁ber_ms ju dul windows - action
▁Christ ina , ▁awak_ms ▁kena ▁ lari , ▁sayang ▁!
▁Saya_ms ▁masih ▁mencari ▁pekerjaan ...
▁- ▁I kut ▁aku_ms ▁ke_ms ▁LA
▁Aku_ms ▁ber_ms i ▁kau_ms ▁masa_ms ▁10 - 15 ▁mini t .
▁Sen si_ms ▁Kata
▁Dan_ms ▁untuk_ms ▁me_ms masti kan_ms ▁kita_ms ▁dapat_ms ▁in vo is ▁kita_ms , ▁Awak ▁akan_ms ▁mengha ntar ▁mereka_ms ▁kepada_ms ▁saya_ms .
▁Kenapa ▁tidak_ms !
▁- A ku_ms ▁dah ▁ter_ms ken al_ms ▁sekarang .
▁Konfigur asi ▁pro ksi ▁_ man_ms ual
▁To ▁shi eld ▁her ▁pretty ▁e yes ... ♫ ▁ ♫ ... ▁Because ▁these ▁are ▁things ▁she ▁should n ' t ▁see ... ♫
▁Baiklah , ▁dia_ms m . ▁Dia_ms m .
▁- ▁Oh , ▁awak_ms ▁sudah ▁ber_ms ju mpa ?
▁Art inya ▁dia_ms ▁tak_ms ▁mamp u ▁bay ar_ms . ▁Kata nya_ms ▁semua_ms ▁har ta_ms ▁ben da_ms ▁ nya_ms ▁telah_ms ▁di_ms ▁ram pas .
▁Ke_ms te ng_ms ahkan ▁panel ▁pada_ms ▁pak si_ms - x
▁Tapi_ms ▁se_ms jak ▁beberapa ▁hari ... ▁.. kami ▁si_ms buk ▁mengu rus ▁visa ▁dan_ms ▁pas s port .
▁Semua ▁dalam_ms ▁hija u , ▁las er ▁je_ms las .
▁Go vin d , ▁orang_ms ▁tua ▁itu_ms ▁tiada ▁wa_ms ng_ms ▁tik et .
▁Kau_ms ▁tam pak ▁ta jam , ▁Tom .
▁Baiklah , ▁mari ▁pergi_ms .
▁Saya_ms ▁Dig by .
▁Itu_ms ▁adalah_ms ▁tahun ▁yang_ms ▁baik_ms .
▁Se_ms benar nya_ms , . .
▁Se_ms si_ms apa_ms ▁yang_ms ▁mahu kan_ms ▁kem uli aan ▁( maka ▁hendak lah_ms ▁i_ms a ▁ber_ms u saha ▁mencari nya_ms ▁dengan_ms ▁jalan ▁me_ms matu hi ▁p erintah ▁Allah_ms ) , ▁kerana ▁bagi ▁Allah_ms ▁ju a lah_ms ▁segala ▁kem uli aan .
▁Itu_ms ▁hanya_ms ▁k haya lan_ms .
▁Oh , ▁asta ga_ms . ▁l ni ▁gi la_ms .
▁- ▁Aku_ms ▁She ik h ▁Al - O be idi .
▁Saya_ms ▁tak_ms ▁akan_ms ▁sed ih_ms ▁kehilangan nya_ms .
▁Tra sh can , ▁pan du_ms ▁lebih ▁la_ms ju !
▁Mes ej ▁sebelum nya_ms
▁Lihat ▁vari ans ▁ba_ms yang - ba_ms yang ?
▁Hanya ▁kau_ms ▁har a pan_ms ▁yang_ms ▁tinggal ▁di_ms ▁dunia ▁ini_ms .
▁Tidak_ms ▁di_ms keta hui
▁Kamu ▁me_ms sti ▁a_ms bang ▁Mia .
▁Saya_ms ▁akan_ms ▁di_ms ▁li pat ▁Si mpan .
▁Ber_ms hen ti_ms ! ▁Ra bbi t , ▁hen ti_ms kan_ms !
▁Ya_ms , ▁ indah ▁sekali ▁Do c .
▁Saya_ms ▁banyak_ms ▁melakukan ▁seks .
▁Per lu_ms kah_ms ▁saya_ms ▁cakap ▁sekali ▁lagi_ms ▁yang_ms ▁saya_ms ▁ada_ms ▁te_ms ta_ms mu_ms ?
▁Dan_ms ▁de_ms mi_ms ▁sesungguhnya !
▁Boleh ▁aku_ms ▁cuba ?
▁Let akan_ms ▁di_ms ▁sini_ms , ▁enam ▁ka ki_ms ▁di_ms ▁bawah .
▁Aku_ms ▁yang_ms ▁membunuh ▁Rich ie ▁W hel an_ms , ▁Faha m ?
▁Ayah ▁kata ▁tidak_ms , ▁mak na_ms nya_ms ▁tidak_ms !
▁Mungkin ▁kami_ms ▁boleh ▁ bantu , ▁cik .
▁Kamu ▁tahu_ms ▁apa_ms ▁p erintah ▁klik ▁ini_ms ? ▁- ▁Sudah , ▁tu_ms an_ms .
▁Mereka ▁pa car nya_ms ▁Eddie !
▁Apa_ms ▁yg ▁orang_ms ▁seperti_ms ▁dia_ms ▁lakukan_ms ▁dengan_ms ▁wa_ms ng_ms nya_ms ▁?
▁aku_ms ▁nampak ▁kau_ms ▁ber_ms i ▁mereka_ms ▁bom .
▁Kita_ms ▁hidup ▁begitu ▁lama ▁sebelum ▁kita_ms ▁me_ms mah ami ▁apa_ms ▁yang_ms ▁benar - benar ▁perkara .
▁a_ms ▁baru
▁Tiada ▁siapa ▁yang_ms ▁bera ni ▁nak ▁cu lik_ms ▁penge dar ▁da dah ?
▁Ra sa_ms nya_ms ▁ber_ms ja_ms u han_ms ▁dari_ms ▁aku_ms ▁buat ▁kau_ms ▁jadi ▁gi la_ms - gi la_ms .
▁Sekarang ▁ne gara ▁ini_ms ▁jadi ▁con to h ▁bagi ▁ne gara ▁- ▁ne gara ▁E ropa h ▁Bara t ▁!
▁De mi_ms ▁sesungguhnya , ▁aku_ms ▁akan_ms ▁mem oto ng_ms ▁tangan ▁dan_ms ▁ka ki_ms ▁kamu_ms ▁dengan_ms ▁ber_ms si_ms lang_ms ▁kemudian ▁aku_ms ▁akan_ms ▁me_ms ma_ms lang_ms ▁kamu_ms ▁semuanya ".
▁- ▁Mana ▁Len ny_ms ?
▁Maaf , ▁aku_ms ▁tak_ms ▁ber_ms ni at_ms ▁nak ▁si_ms nggu ng_ms ▁per_ms asa_ms an_ms ▁dia_ms .
▁Itu_ms ▁du it ▁saya_ms ▁dan_ms ▁mereka_ms ▁dah ▁ambil , ▁dan_ms ▁saya_ms ▁ga gal ▁jumpa !
▁Ia nya_ms ▁akan_ms ▁bergerak ▁ke_ms ▁ta pak ▁9 , ▁yang_ms ▁ini_ms .
▁Kita_ms ▁pas ukan ▁U . S ▁terakhir ▁di_ms ▁ne geri ▁ini_ms ?
▁Sekarang , ▁semua_ms ▁orang_ms ▁ber_ms ke mas ▁tanpa ▁ada_ms ▁buat ▁apa_ms - apa_ms ... ▁Tapi_ms ▁pembunuh an_ms ▁Mary ▁Wort h ington ... ▁Ia ▁masih ▁mengha nt ui ▁aku_ms .
▁Per kara ▁yang_ms ▁anda ▁meminta ▁ke_ms ▁jalan ▁yang_ms ▁benar .
▁" Bi ar_ms kan_ms ▁ku_ms ▁me_ms mah ami ."
▁Tidak_ms ▁dapat_ms ▁tuli s ▁ke_ms ▁% s
▁En i !
▁Saya_ms ▁ter_ms ta_ms nya_ms - ta_ms nya_ms ▁jika_ms ▁awak_ms ▁ada_ms ▁pel u ang_ms ▁untuk_ms ▁han tar ▁la_ms por an_ms ▁saya_ms ▁ke_ms ▁Ja mba tan_ms ▁Sa a bir ▁K han_ms ▁kepada_ms ▁sesiapa ▁dalam_ms ▁per_ms isi kan_ms .
▁- Be liau ▁adalah_ms ▁blo tto .
▁- ▁Oh , ▁Saya_ms ▁maksud kan_ms .
▁Saya_ms ▁rasa ▁hanya_ms ▁itu_ms ▁sahaja ▁kes aba ran ▁yang_ms ▁is teri ▁awak_ms ▁ada_ms ▁pada_ms ▁diri_ms nya_ms .
▁Saya_ms ▁pernah_ms ▁dengar ▁ini_ms ▁sebelum nya_ms .
▁Ada ▁bud ak_ms ▁ber_ms i kannya ▁pada_ms ▁saya_ms .
▁Ada ▁apa_ms ▁dengan_ms ▁Mun ni ?
▁Aku_ms ▁akan_ms ▁berbicara ▁dengan_ms ▁ka ka_ms k nya_ms .
▁Kami_ms ▁a_ms dik - ber a dik ▁ , ▁Joe y ▁ .
▁La lu_ms ▁kenapa ▁kau_ms ▁me_ms ra_ms wat ▁S SP ▁K han_ms ?
▁Kent ang_ms ▁bere mpah ...
▁Jangan ▁biarkan ▁ayah ▁minu m ▁terlalu ▁banyak_ms .
▁Kemudian ▁apabila ▁Tal ut_ms ▁keluar ▁bersama - s ama ▁ten tera nya_ms , ▁berkata lah_ms ▁i_ms a : ▁" Sesungguhnya ▁Allah_ms ▁akan_ms ▁mengu ji ▁kamu_ms ▁dengan_ms ▁se_ms ba_ms tang ▁sun gai , ▁oleh ▁itu_ms ▁sesiapa ▁di_ms ▁antara ▁kamu_ms ▁yang_ms ▁me_ms min um ▁air nya_ms ▁maka ▁bukan_ms lah_ms ▁i_ms a ▁dari_ms ▁peng_ms i kut ku_ms , ▁dan_ms ▁sesiapa ▁yang_ms ▁tidak_ms ▁merasa i ▁air nya_ms ▁maka ▁sesungguhnya ▁i_ms a ▁dari_ms ▁peng_ms i kut ku_ms , ▁kecuali ▁orang_ms ▁yang_ms ▁men_ms ce duk ▁satu_ms ▁ce du_ms kan_ms ▁dengan_ms ▁tangan nya_ms ".
▁Saya_ms ▁nak ▁keluar ▁untuk_ms ▁dapat_ms kan_ms ▁ha_ms dia h ▁per_ms kah_ms win an_ms ▁kamu_ms !
▁jika_ms ▁kau_ms ▁harus ▁menjadi_ms ▁baby si_ms tter ▁( pen gas uh_ms ▁bay i ) , ▁ini_ms ▁bukan_ms ▁a_ms wal ▁yang_ms ▁buruk .
▁Pen guna an_ms : ▁og g de c ▁[ pi li_ms han_ms ] ▁fail 1 . og g ▁[ fa il 2 . og g ▁... ▁fail N . og g ]
▁.. se_ms hin gga ▁dia_ms ▁bahkan ▁mungkin ▁menu n juk ▁jar inya ▁ke_ms ▁a_ms rah_ms mu_ms .
▁Kemudian ▁saya_ms ▁fikir ▁untuk_ms ▁kali ▁kedua ▁dalam_ms ▁diri_ms ▁saya_ms .
▁Ia ▁memberi ▁ke_ms men angan_ms ▁kepada_ms ▁sesiapa ▁yang_ms ▁di_ms ke hen daki Nya , ▁dan_ms ▁Dia_ms ▁ lah_ms ▁ju a ▁yang_ms ▁Maha ▁Ku asa_ms , ▁lagi_ms ▁Maha ▁Men gas ih_ms ani .
▁Jangan ▁ambil ▁a_ms yat ▁saya_ms .
▁Kami_ms ▁telah_ms ▁menga_ms da_ms kan_ms ▁dialog ▁penting ▁yang_ms ▁akan_ms ▁membantu ▁kami_ms ▁men_ms ja_ms ga_ms ▁pe_ms main .
▁Jadi , ▁i_ms a ▁dah ▁tidak_ms ▁jauh .
▁" O h , ▁ga ya ▁ram but nya_ms ."
▁Saya_ms ▁tahu_ms , ▁dan_ms ▁saya_ms ▁tahu_ms ▁bahawa ▁saya_ms ▁telah_ms ▁out vo ted , ▁tetapi ▁itu_ms ▁tidak_ms ▁mengu bah ▁fakt a ▁bahawa ▁kita_ms ▁out mann ed .
▁Da pat ▁awak_ms , ▁si_ms ▁ce laka .
▁" To wer ", ▁sebe ntar ▁lagi_ms ▁kita_ms ▁tidak_ms ▁ber_ms opera si_ms ... , ▁Tapi_ms ▁" D ron e " ▁sudah ▁ke_ms ▁sana ▁dan_ms ▁se_ms dia ▁di_ms sem pur na_ms kan_ms .
▁Tengo k , ▁tengo k .
▁VI NC ENT : ▁Apa_ms ▁itu_ms ?
▁Awak ▁sudah ▁berjaya ▁bahkan ▁hari ▁ini_ms .
▁Ya_ms , ▁jadi ▁mereka_ms ▁mengha ntar ▁Ibu ▁Mac G y ver ▁di_ms ▁sini_ms ▁untuk_ms ▁mendapatkan ▁anda .
▁Kin i ▁saya_ms ▁e jen ▁awak_ms , ▁saya_ms ▁perlu ▁men_ms di_ms dik ▁awak_ms ▁pada_ms ▁how to ▁menjadi_ms ▁pembunuh ▁pembunuh ▁A ▁tidak_ms ▁perlu ▁untuk_ms ▁membunuh ▁semua_ms ▁masa_ms ▁yang_ms
▁\ t Ver si_ms : ▁% d
▁Ker eta ▁ini_ms ▁T angan_ms ▁kedua ▁akan_ms ▁lakukan_ms ?
▁bukan_ms lah_ms ▁pilihan ▁yang_ms ▁sah
▁Se_ms ti_ms ap ▁orang_ms ▁harus ▁tetap ▁tena ng_ms
▁Ke_ms du_ms a ▁sau dari ▁di_ms ti_ms pu ▁oleh ▁pri a ▁yang_ms ▁sama !
▁- ▁Tidak_ms .
▁Saya_ms ▁rasa ...
▁Kalau ▁aku_ms ▁ada_ms ▁ji wa_ms ▁nur ani .
▁[ S h h h ▁... ]
▁Aku_ms ▁tahu_ms .
▁ Personal isa si_ms ▁Papa ran ▁Sem asa_ms
▁Bu ng_ms le - bung le ?
▁Pe layan , ▁to long ▁saya_ms .
▁- ▁Per lu_ms kah_ms ▁kita_ms ▁tu_ms nda ?
▁Saya_ms ▁bi mbang ▁kita_ms ▁tak_ms ▁ber_ms ken alan ▁dengan_ms ▁betul ▁se_ms ma_ms lam .
▁Tak_ms ▁boleh kah_ms ▁cakap ▁yang_ms ▁baik_ms - baik ?
▁- ▁Minu m lah_ms ▁sedikit ▁vod ka_ms .
▁- A wa_ms k ▁dengar ▁dalam_ms ▁kereta ?
▁Ken alan ▁Pen ting
▁Jadi ▁jangan ▁panggil ▁kami_ms ▁wir a .
▁back ground , ▁ style
▁awak_ms ▁yakin ▁awak_ms ▁tidak_ms ▁mahu ▁minu m ▁du lu_ms ?
▁Adakah ▁anda ▁tahu_ms ▁ne fri t ?
▁Jangan ▁tengo k . .
▁Awak ▁dah ▁pak sa_ms ▁kami_ms ▁bekerja ▁terlalu ▁ku_ms at_ms .
▁Mereka ▁me_ms lar ikan_ms ▁diri_ms !
▁Hei , ▁tentang ▁da da_ms ▁Ji b ▁tu_ms ▁saya_ms ▁tak_ms ▁pernah_ms ▁per_ms asan ▁pun , ▁OK !
▁Boleh ▁saya_ms ▁bersama ▁mereka_ms ▁dari_ms ▁A had ▁hin gga ▁Ju ma_ms at_ms ?
▁Se_ms su ai ▁dengan_ms ▁diri_ms ▁sendiri , ▁tetapi ▁masih ▁i_ms a ▁tidak_ms ▁boleh ▁ditu kar .
▁Aku_ms ▁akan_ms ▁bunu h ▁dia_ms !
▁Untuk ▁pe_ms mbe da_ms han_ms ▁ko s me tik ▁ke_ms ?
▁Bill ▁ke_ms rap ▁me_ms la_ms wat ku_ms , ▁setiap ▁hari .
▁Mac am ▁satu_ms ▁an u ▁leng kap ▁seperti_ms ▁se_ms bij i ▁bat u ▁yang_ms ▁ber_ms go lek ?
▁Katakan lah_ms ▁( wa_ms hai ▁Muhammad ): ▁" A ku_ms ▁tidak_ms ▁ber_ms ha k ▁menu kar kannya ▁dengan_ms ▁ke_ms mah uan ku_ms ▁sendiri , ▁aku_ms ▁hanya_ms ▁tetap ▁menurut ▁apa_ms ▁yang_ms ▁di_ms wa_ms hy ukan ▁kepada_ms ku_ms ▁sahaja .
▁Kami_ms ▁ta nya_ms ▁ada_ms kah_ms ▁dia_ms ▁ingin_ms ▁bersama ▁dengan_ms ▁kami_ms , ▁jadi ▁begitu lah_ms ▁dia_ms ▁ada_ms ▁di_ms ▁sini_ms .
▁Dan_ms ▁de_ms mi_ms ▁sesungguhnya !
▁Yu ▁Ni ang_ms , ▁kamu_ms ▁ini_ms ▁seorang_ms ▁yang_ms ▁bija k ▁dan_ms ▁can tik .
▁Dan_ms ▁kami_ms ▁di_ms ▁dalam_ms ▁lelaki ▁yang_ms ▁tidak_ms ▁baik_ms ▁ne gara
▁Saya_ms ▁tidak_ms ▁peduli ▁jika_ms ▁mereka_ms ▁rasa ▁seperti_ms ▁bel uga ▁ka vi ar_ms ▁ , ▁saya_ms ▁tidak_ms ▁makan ▁ci cak ▁ .
▁Kau_ms ▁ingat ▁kau_ms ▁ka t ▁mana_ms ? ▁Mos co w ? ▁Paris ?
▁Ma ster ▁Tie ▁...
▁Kenapa ▁pula ?
▁Tapi_ms ... ▁Aku_ms ▁mau ▁kau_ms ▁i_ms kut ▁dengan_ms ku_ms ▁malam ▁ini_ms
▁Aku_ms ▁takkan ▁hanya_ms ▁pot ong ▁kau_ms , ▁aku_ms ▁akan_ms ▁pot ong ▁anak ▁kau_ms .
▁Jika ▁i_ms a ▁adalah_ms ▁kes ila pan_ms ▁sesiapa , ▁i_ms a ▁adalah_ms ▁kita_ms .
▁Ju ara , ▁belum ▁ada_ms ▁yang_ms ▁menye but kan_ms ▁mengenai ▁hal ▁ini_ms , ▁Tapi_ms ▁ber_ms apa_ms ▁banyak_ms ▁yang_ms ▁Kamu ▁has il kan_ms ▁untuk_ms ▁per_ms tan_ms ding an_ms ▁ini_ms ?
▁Ma ta_ms ▁yang_ms ▁can tik .
▁Tie ▁me_ms ▁kan gar o o ▁down ...
▁Oh , ▁saya_ms , ▁a_ms a a ... ▁ya , ▁saya_ms ▁tak_ms ▁ba_ms wa_ms ▁pula .
▁is teri ▁kamu_ms ▁orang_ms ▁yang_ms ▁sangat_ms ▁baik_ms
