▁Di je_bs te_bs , ▁a_bs ▁tek ▁je_bs ▁u_bs šla ▁u_bs ▁tri de se tu ?
▁I_bs ▁či m ▁završi š ▁sa_bs ▁pra njem ▁sud ova_bs , ▁ho ću_bs ▁da_bs ▁od_bs eš ▁iz_bs ▁moje ▁ku_bs će_bs .
▁Vaš a ▁je_bs , ▁i_bs ▁samo_bs ▁vaš a .
▁Pri đi te_bs ▁im ▁s_bs ▁ boka ▁kod ▁ste_bs pe nica !
▁Ni ste ▁do_bs bri , ▁ali_bs ▁misli li_bs ▁ste_bs ▁da_bs ▁ce te_bs ... ▁i_bs pak ▁otići ▁na_bs ▁taj ▁škol ski ▁iz_bs let , ▁je_bs ▁li_bs ?
▁- ▁O_bs , ▁Bo ze .
▁- ▁John u ▁ste_bs ▁veoma ▁drag i .
▁Kao ▁da_bs ▁mi_bs ▁je_bs ▁pred ▁no som , ▁ali_bs ...
▁Treba ce_bs ▁vremena ▁da_bs ▁nau ci_bs š ▁da_bs ▁to_bs ▁kontroli še š .
▁Bilo ▁je_bs ▁m ra_bs čno ... ▁samo_bs ▁sam_bs ▁sta ja_bs la_bs ▁tamo ▁do_bs ▁ju tra ... ▁na_bs ▁pl ju_bs sku ...
▁Eu phe ge nia ▁Do_bs ub t fi re_bs .
▁Oh , ▁Lu ize . ▁Pa_bs zi_bs ▁na_bs ▁ovaj ▁pištolj .
▁Cal av ius ▁bi_bs ▁bio_bs ▁mrtav ▁prije ▁nego ▁ti_bs .
▁- V re_bs me_bs ▁za_bs ▁u_bs ba ci_bs vanje ▁star o mod nog ▁š pi ju_bs na_bs .
▁l ▁ ova_bs ko_bs ▁do_bs la_bs ze ▁te_bs ški ▁da_bs ni_bs ▁za_bs ▁mlad un ča d .
▁Ovo ▁je_bs ▁is_bs pit .
▁Je_bs ▁li_bs ▁to_bs ▁vaš a ▁briga ▁za_bs ▁njegov u ▁ta šti nu_bs ?
▁Reci ▁mi_bs ...
▁Če sti_bs tam , ▁otkri li_bs ▁ste_bs ▁or už ije .
▁Možda , ▁uh ...
▁Vrati ▁se_bs ▁na_bs ▁Mar u , ▁i_bs ▁spre mi ▁se_bs ▁za_bs ▁ eva ku_bs aciju . ▁Dy lan ▁od_bs java .
▁Je_bs ben o ▁smo_bs ▁za_bs rob ljeni ?
▁- Ni je_bs ▁bit no_bs , ▁i_bs ▁dalje ▁moraš ▁razgovara ti_bs ▁sa_bs ▁polici jom .
▁Neka ▁tim ▁za_bs ▁s_bs pušta nje ▁radi ▁u_bs ▁grup ama ▁po_bs ▁dvoj e . ▁Ne_bs ▁želim ▁da_bs ▁niko ▁ovde ▁osta ne_bs ▁sam_bs .
▁Jesi ▁li_bs ▁tu , ▁Mark ?
▁Do_bs k ▁ne_bs ▁budem o ▁sazna li_bs ▁više_bs , ▁pazi ▁se_bs .
▁- ▁To_bs ▁je_bs ... ▁če sti_bs tka .
▁Ti_bs ▁si_bs ▁već i .
▁Šta_bs ▁si_bs ▁bio_bs ▁uradio ?
▁I_bs ▁vidi o ▁sam_bs ▁ih ▁u_bs ▁krevet u .
▁Šta_bs ▁radiš ?
▁Kad ▁si_bs ▁kod ▁ku_bs će_bs , ▁koristi ▁ovaj ▁dal jin ski .
▁Luci a ▁ka ze ▁da_bs ▁vas_bs em ▁ti_bs mu ▁treba_bs ▁pomoc , ▁zato ▁sam_bs ▁ovde .
▁Ob ično , ▁kod ▁policaj aca ▁pi ja_bs telja , ▁jedan ▁je_bs ▁is_bs prav na_bs ▁ cje pi d laka , ▁a_bs ▁drugi ▁od_bs met nik .
▁La ku_bs ▁noć .
▁A_bs ▁da_bs ▁ga_bs ▁ob javljuje mo_bs ▁i_bs ▁ne_bs kom ▁ne_bs ara pu
▁Ma lo_bs ▁u_bs š to g ljena .
▁Živ ▁je_bs , ▁ali_bs ▁je_bs ▁na_bs ▁aparat ima_bs . ▁Doktor i ▁ka žu ▁da_bs ▁ima_bs ▁50 / 50 ▁šans i ▁za_bs ▁život , ▁i_bs ako ▁ima_bs ▁samo_bs ▁10 % ▁šans i ▁za_bs ▁to_bs .
▁Los a ▁informacija , ▁nije_bs ▁bilo_bs ▁ag res iv nog ▁ot por a .
▁U_bs zor kova ce_bs mo_bs , ▁a_bs ▁onda ▁mo zem o ▁da_bs ▁joj ▁pomogne mo_bs .
▁Ma ▁u_bs ▁čemu ▁se_bs ▁raz i lazi li_bs , ▁treba_bs ▁pres udu ▁dati ▁Allah .
▁Ko s tolo mac !
▁Za_bs bavi ćemo ▁se_bs ▁u_bs ▁Lisa bon u , ▁mom ci_bs !
▁Ne_bs ćemo ▁samo_bs ▁da_bs ▁sed imo ▁ovde ▁radi ▁de_bs kor acije , ▁u_bs ▁redu ?
▁Ja_bs ▁se_bs ▁po_bs nek ad ▁pret var am ▁da_bs ▁su_bs ▁stvari ▁bolje ▁čak ▁i_bs ▁kad_bs ▁nisu .
▁Vo don ošo !
▁Pro sto ▁ko ▁pas ul j .
▁Tvoj ▁auto ▁klub ▁ima_bs ▁par ▁Por sche ▁Spe ed ster a ▁iz_bs ▁19 56 .
▁Vi ▁ste_bs ▁sin ▁Ja_bs nar dan ▁Gan gul ija ?
▁Zašto ▁ne_bs bi_bs ?
▁Mislim ▁da_bs ▁ćeš ▁mi_bs ▁oprosti ti_bs ▁kad_bs ▁završi š ▁ psi ho ▁terapi ju_bs .
▁Mu ška rac , ▁prvi ▁raz red , ▁podaci ▁se_bs ▁ne_bs ▁pod uda ra_bs ju_bs .
▁Da_bs . ▁Moj ▁ba lon ▁je_bs ▁na_bs i šao ▁na_bs ▁ temperatur nu_bs ▁in ver zi_bs ju_bs .
▁- ▁Če ga , ▁ged ore ?
▁Zašto ▁ne_bs ▁traži mo_bs ▁od_bs ▁Wall ▁Street a ▁da_bs ▁po_bs či_bs sti_bs ▁svoj ▁v last iti_bs ▁ne_bs red ?
▁Stvarno ▁?
▁Nije dan ▁go lub ▁pis mono ša ▁nije_bs ▁ oz li_bs je_bs đen ▁za_bs ▁vrijeme ▁s_bs nim_bs anja .
▁- ▁DA , ▁B IV ?
▁Ne_bs ▁pri_bs lazi , ▁molim ▁te_bs !
▁Mc G ill , ▁Pod sjeća m ▁vas_bs ▁da_bs ▁ste_bs ▁još ▁pod ▁za_bs klet vom .
▁Zašto ▁ti_bs ▁uvek ▁od_bs usta ješ_bs ?
▁Izvini , ▁Bil i .
▁Osta vio ▁je_bs ▁ovo_bs .
▁En o ▁jedne .
▁Ja_bs ▁ću_bs ▁se_bs ▁posta rati ▁za_bs ▁njih .
▁Da_bs ▁bi_bs ▁Bil ▁i_bs ▁S_bs lim ▁bili ▁place ni_bs .
▁Kao ▁ze či_bs ći_bs .
▁Ma lo_bs ▁si_bs ▁nerv o zan , ▁šta_bs ▁ne_bs ?
▁Polic aj ce_bs , ▁policaj ce_bs . .
▁A_bs ▁rekao ▁sam_bs ▁cu dne , ▁jer ▁one ▁za_bs ista ▁ne_bs ▁izgleda ju_bs ▁ljudsk i .
▁- ▁Jako ▁dobro .
▁D je_bs ča ci_bs ▁iz_bs ▁hora ?
▁Ovo ▁je_bs ▁Victor ▁Steven s , ▁glavni ▁sa_bs vije t nik ▁u_bs ▁Bi jelo j ▁Ku ći_bs .
▁Moj ▁Bože .
▁R ha ps odi ze .
▁Jedno stav no_bs ▁i_bs ▁čist o ▁... ▁i_bs ▁uku s no_bs .
▁- B ili_bs ▁ste_bs ▁2 ▁godine ▁u_bs ▁interna tu ?
▁Bru se , ▁tako_bs ▁je_bs ▁pis alo ▁u_bs ▁članku .
▁- Da .
▁Imam ▁motor e ▁u_bs ▁gara ži .
▁I_bs gor ...
▁Ovo ▁je_bs ▁bilo_bs ▁lepo , ▁bud alo .
▁Šta_bs ▁do_bs đa vola ▁ti_bs ▁radiš ▁ovdje ?
▁Stan i !
▁Izgleda ▁da_bs ▁ga_bs ▁je_bs ▁O_bs skar ▁uz eo .
▁Mi ▁smo_bs ▁ovdje ▁zbog ▁mr .
▁Do_bs , ▁po_bs đi ▁sa_bs ▁mnom .
▁Koliko ▁je_bs ▁u_bs dalje n ▁zal jev ▁Mor gus ?
▁Samo ▁gleda jte ▁ra vno ▁is_bs pred .
▁S_bs red nje v je_bs kov na_bs ▁bo san ska ▁država ▁je_bs ▁jedna ▁od_bs ▁naj s tari jih ▁u_bs ▁Evrop i ▁i_bs ▁dat ira ▁još ▁iz_bs ▁11. ▁stol je_bs ća_bs .
▁- Ne ću_bs .
▁- ▁Da_bs , ▁dana s ▁mi_bs ▁je_bs ▁29 ▁ .
▁Na_bs po lje , Š tab ni_bs .
▁Dor oti ▁ne_bs ▁bi_bs ▁nikada ▁s_bs kin ula ▁tak vu ▁hal jin u .
▁- Ho tel ▁je_bs ▁pod ▁s_bs tica jem .
▁Što ?
▁Da_bs ▁vidim o ▁sla že_bs ▁li_bs ▁se_bs ▁s_bs ▁ovim ▁što_bs ▁imamo .
▁Sta ▁radi s ?
▁NE ▁ZA ▁K AI .
▁- N aj glu p lja ▁odluka ▁u_bs ▁po_bs vijesti .
▁# Ne ki ▁ljudi ▁čeka ju_bs ▁ce o ▁život # ▁# na_bs ▁ ova_bs kav ▁trenutak #
▁Po_bs stavi ▁le đa .
▁- ▁Treba o ▁sam_bs ▁da_bs ▁znam_bs !
▁Šta_bs ▁ti_bs ▁je_bs ▁to_bs ?
▁Bro j ▁dva na_bs est . ▁1 ▁5. 70 ▁fra na_bs ka_bs .
▁Ve če_bs raš nju ▁mis u ▁tijekom ▁za_bs m ra_bs čen ja_bs ▁drži ▁ra bin ▁Tri bbi ani .
▁Bilo ▁bi_bs ▁prav ed no_bs ▁da_bs ▁me_bs ▁uh vate ▁i_bs ▁kazn e .
▁Šta_bs ▁se_bs ▁čeka ?
▁ lli ▁možda ▁gre ši m .
▁I_bs ▁tu ▁je_bs ▁i_bs ▁zen a ▁sa_bs ▁tobom .
▁Moramo ▁biti_bs ▁pa_bs ž ljivi .
▁Što ▁je_bs ▁on_bs dje ▁radio ?
▁Bio ▁je_bs ▁u_bs ▁drugo j ▁so bi_bs .
▁Ne_bs će_bs ▁biti_bs ▁gore ▁od_bs ▁sa_bs sluš anja ▁O_bs bal ske ▁stra že_bs .
▁Ja_bs ▁post avljam ▁pitanja .
▁Ne_bs tko ▁me_bs ▁vu če_bs ▁prema ▁zemlji .
▁Ako ▁ima_bs ▁sreć e ▁da_bs ▁u_bs ▁škol i ▁ima_bs ▁dobre ▁profesor e , ▁pre_bs pozna će_bs ▁simptom e ...
▁- P u sti_bs ▁me_bs ▁u_bs ▁et er , ▁neka ▁me_bs ▁vidi .
▁- H ej , ▁kako_bs ▁si_bs ?
▁Ima te_bs ▁samo_bs ▁jednu ▁minut u ▁da_bs ▁ga_bs ▁neutral izi rate .
▁Sk inimo ▁I_bs ja_bs gu ▁s_bs ▁naš ih ▁I_bs ju_bs di_bs .
▁Šta_bs ▁je_bs ▁s_bs ▁tobom ? ▁Šta_bs ▁ti_bs ▁je_bs ?
▁Pokuša o ▁sam_bs ▁da_bs ▁razgovara m ▁s_bs ▁n jom , ▁ali_bs ... ▁samo_bs ▁bi_bs ▁nešto ▁pro_bs m r m lja la_bs .
▁Do_bs re_bs en , ▁g . ▁Green .
▁- ▁C ista ▁zem lja .
▁- Ka ko_bs ▁ste_bs ?
▁" ▁Let ▁je_bs ▁i_bs šao ▁za_bs ▁ni_bs geri jski ▁glavni ▁grad ▁Ab uja - u ▁i_bs ▁smatra ▁se_bs ▁da_bs ▁je_bs ▁u_bs ▁njemu ▁bilo_bs ▁nekoliko ▁ni_bs ge rij skih ▁u_bs gled nika ."
▁Jer ▁sad ▁je_bs ▁za_bs sta ▁lo š ▁trenutak ▁za_bs ▁šal e . ▁V jer uj ▁mi_bs .
▁ TR G ▁ VE TER ANA , ▁22 : 50 h .
▁Da_bs ▁je_bs ▁moj_bs ▁muž ▁učini o ▁ona ko_bs ▁nešto , ▁mogao ▁bi_bs ▁da_bs ▁mo li_bs ▁na_bs ▁kol en ima_bs , ▁u_bs bila ▁bih ▁ga_bs ▁na_bs ▁me_bs stu .
▁Jeste ▁li_bs ▁u_bs bili ▁kar dina la_bs , ▁Chap o ?
▁Ali_bs ▁zar ▁se_bs ▁ne_bs ▁bri neš ▁za_bs ▁Fil a ?
▁Kako ▁to_bs ▁od_bs bi_bs ti_bs ?
▁- ▁Temp irano ▁u_bs bi_bs stvo ?
▁To_bs lika ▁in tu i cija ▁me_bs ▁pokr e ce_bs . ▁Hajde ▁sa_bs ▁mnom .
▁Za_bs h val ju_bs jući ▁gosp . ▁La bi_bs fu , ▁pro_bs ma_bs ši li_bs ▁smo_bs .
▁Je_bs ▁li_bs ▁to_bs ▁ne_bs služ ben o ▁mišljenje ▁ili ▁ga_bs ▁smije m ▁po_bs no_bs viti ?
▁- Si gur no_bs ▁ce te_bs ▁uz i vati ▁u_bs ▁ njima ▁kad_bs ▁se_bs ▁bude te_bs ▁vra ca_bs li_bs .
▁Po_bs ne_bs ću_bs ▁ti_bs ▁ tor bu .
▁Ob eć ava š ▁da_bs ▁me_bs ▁ne_bs ćeš ▁dir nuti ?
▁To_bs ▁više_bs ▁znam_bs
▁Mislim ▁da_bs ▁je_bs ▁presta lo_bs .
▁- ▁Da_bs , ▁vrij edi ▁2 ▁mili ju_bs na_bs .
▁Slu s aj ▁me_bs . ▁Ovo ...
▁Ko je_bs ▁je_bs ▁tvoje ▁om i ljeno ▁mjesto ▁za_bs ▁ru čak ?
▁- Ho ćemo .
▁Vi še ▁bih ▁voli o ▁ne_bs ...
▁Kor del iji ?
▁V jer u jte ▁u_bs ▁Allaha ▁i_bs ▁Pos la_bs nika ▁Njegov og ▁i_bs ▁tro ši te_bs ▁od_bs ▁on_bs og ▁čemu ▁vas_bs ▁je_bs ▁učini o ▁na_bs sljed ni_bs cima .
▁Na_bs pad ▁je_bs ▁za_bs vrš en .
▁To_bs ▁je_bs ▁Mal va_bs do .
▁ili ▁iza đe .
▁Znaš ▁da_bs ▁je_bs ▁mušk o ▁jer ...
▁Invest i tori ▁invest iraju ▁- ▁i_bs ▁ja_bs ▁od_bs lu c ujem ▁kom e ▁da_bs ▁se_bs ▁poz aj mi ▁novac .
▁Po_bs nek ad , ▁ cak ▁i_bs ▁a_bs stro na_bs uti ▁nav rate .
▁Kon rade , ▁obe ca_bs o ▁si_bs ▁pitanja ▁i_bs ▁odgovor e .
▁Moram ▁priv u ci_bs ▁njihov u ▁pa_bs ž nju , ▁moraju ▁zna ti_bs ▁da_bs ▁sam_bs ▁bud na_bs !
▁V re_bs me_bs ▁her oja ▁je_bs ▁pro_bs šlo , ▁Wi gla fe .
▁Sa ▁za_bs d ovolj stvo m , ▁gospodine .
▁Ili ▁pro_bs val nik ▁koji_bs ▁voli ▁slik e .
▁Hajde , ▁Š il jo !
▁Možda ▁ovo_bs ▁pomogne . ▁Moj ▁koleg a ▁s_bs ▁fa ksa ▁radi ▁u_bs ▁banc i ▁Kelly ▁Union .
▁Ne_bs ▁volim ▁či z me_bs .
▁Ili ▁samo_bs ▁ja_bs ▁tako_bs ▁mislim ?
▁Up isa o ▁sam_bs ▁fa ks ▁kao_bs ▁se_bs bi_bs c ni_bs ▁samo_bs t nja k , ▁ali_bs ▁vi ▁ste_bs ▁me_bs ▁po_bs u cili ▁prijatelj stvu .
▁Možete ▁da_bs ▁se_bs ▁raz boli te_bs .
▁- ▁U_bs či_bs ni_bs ću_bs ▁kako_bs ▁otac ▁želi . ▁- ▁Hoćeš ▁li_bs !
▁Moj ▁Bog ▁se_bs ▁br ine ▁za_bs ▁mene .
▁Sa ▁moj_bs im_bs ▁solid nim_bs ▁pozna vanje m ▁um jet nosti ▁rekao ▁bih ▁da_bs ▁je_bs ▁ovo_bs ▁od_bs li_bs čan ▁rad .
▁Mora ▁da_bs ▁je_bs ▁bilo_bs ▁mu čenje . ▁Ok .
▁To_bs ▁je_bs ▁ne_bs ob ično , ▁is_bs tina .
▁S_bs red ili_bs ▁ste_bs ▁mi_bs ▁od_bs elo .
▁Ron al do , ▁se_bs ća_bs m ▁se_bs ▁t vog ▁prvo g ▁dana ▁na_bs ▁pos lu , ▁bio_bs ▁si_bs ▁toliko ▁up laš en ▁da_bs ▁si_bs ▁se_bs ▁us ra_bs o .
▁Ti_bs ▁si_bs ▁crn ac .
▁Hvala . ▁Je_bs su ▁li_bs ▁nos oro zi_bs ▁mono gam ni_bs ?
▁- Re ci_bs ▁ , ▁mom če_bs ▁!
▁O_bs vi_bs ▁su_bs ? ▁- ▁Da_bs .
▁Ne_bs l son ▁je_bs ▁na_bs ▁ce kan ju_bs .
▁Te ško ▁da_bs ▁ćeš ▁ne_bs g dje ▁to_bs ▁na_bs ći_bs .
▁Nije ▁tako_bs ▁mlad a ▁kao_bs ▁što_bs ▁misli .
▁Ovo ▁je_bs ▁naš a ▁žrtv a .
▁Svi ▁su_bs ▁zajedno ▁i_bs ▁svi ▁se_bs ▁pozna ju_bs . ▁Raz ume š ? ▁Da_bs .
▁Sa ▁te_bs ški m ▁ kora cima ▁klo mp .
▁Da_bs ▁potroš im_bs ▁posledn jih ▁par ▁dana ▁života ?
▁Gdje ▁drži š ▁tu ▁glup u ▁stvar ?
▁Za_bs s pala ▁sam_bs .
▁# ▁Da_bs ▁ti_bs ▁ka ze ▁da_bs ▁se_bs ▁s_bs n ovi
▁- ▁U_bs ▁redu ... ▁Kako ▁je_bs ?
▁Pol je_bs ▁je_bs ▁puno ▁o_bs klop a .
▁- ▁Vo zi_bs cu_bs ▁se_bs ▁oko ▁po_bs lu o str va_bs .
▁To_bs ▁je_bs ▁... ▁to_bs ▁je_bs ▁samo_bs ▁nije_bs ▁jasno .
▁- Ko ju_bs ▁ne_bs ćeš ▁koristiti .
▁Ne_bs ko_bs ▁je_bs ▁u_bs kra o ▁Če ster a ?
▁29. ▁av g usta ▁1981 . , ▁oko ▁150 ▁km ▁u_bs ▁unutra š njo sti_bs ▁Ang ole , ▁bili ▁smo_bs ▁u_bs ▁operacij i ▁i_bs ... ▁Bio ▁sam_bs ▁u_bs ▁la ko_bs ▁o_bs klop ljeno m ▁vozi lu , ▁To_bs jo ti_bs ▁le nd ▁kru zer u , ▁koja ▁je_bs ▁ima_bs la_bs ▁platform u ▁za_bs ▁te_bs ški ▁mi_bs tra lje z ▁kali bra ▁250 ▁Bro ving .
▁Dan as ▁se_bs ▁u_bs god no_bs ▁od_bs ije vamo ?
▁- ▁Sad ▁su_bs ▁svi ▁njihov i ▁s_bs n ovi ... ▁- ▁Kako ▁je_bs ▁di vno ▁biti_bs ▁maj ka_bs ! ▁Nema ▁bolje g ▁posla .
▁Je_bs ▁li_bs ▁u_bs šao ?
▁Za_bs mišljen a , ▁pra g mati čna , ▁str pl j l va_bs .
▁Pr va_bs ▁noć ▁je_bs ▁te_bs ška .
▁D je_bs voj ke , ▁ho će_bs te_bs ▁li_bs ▁biti_bs ▁dobro ▁same ?
▁Oh , ▁vidi , ▁to_bs ▁nije_bs ▁naš a ▁kriv ica ▁nam ▁je_bs ▁potreba n ▁domov inu .
▁Ba ci_bs ▁ga_bs , ▁je_bs be m ti_bs .
▁Kad ▁se_bs ▁izgubi š , ▁najbolje ▁se_bs ▁vratiti ▁na_bs ▁počet ak .
▁Onda ▁im ▁je_bs ▁ovo_bs ▁pro_bs mak lo_bs .
▁Moraš ▁da_bs ▁budeš ▁koncentr iran ▁na_bs ▁i_bs gru
▁Tako đ er ▁u_bs ▁okviru ▁novo sti_bs ▁iz_bs ▁na_bs uke : ▁Beograd ▁doma ći_bs n ▁ konferenc iji ▁min ista ra_bs ▁obraz ovanja ▁zemalja ▁za_bs pad nog ▁Bal kana , ▁a_bs ▁u_bs ▁Ru muni ji_bs ▁op ala ▁proda ja_bs ▁personal nih ▁komp ju_bs tera .
▁Idemo , ▁pod ign ite ▁ci jev ▁za_bs ▁dis anje .
▁To_bs ▁ste_bs ▁u_bs radi li_bs ▁i_bs ▁za_bs ▁moju ▁ma mu ▁jos ▁196 2, ▁pa_bs ▁su_bs ▁nas_bs ▁pre_bs sel ili_bs ▁ovamo !
▁Ken ny , ▁samo_bs ▁proba j ▁da_bs ▁se_bs ▁s_bs miri š .
▁Ali_bs ▁Den ny ija ▁nije_bs ▁bilo_bs ▁briga .
▁Franc u zi_bs ▁su_bs ▁su_bs djel ovali ▁u_bs ▁u_bs vo đen ju_bs ▁ten kova ▁i_bs ▁zrakoplov a , ▁ali_bs ▁učini li_bs ▁su_bs ▁ned ovolj no_bs ▁za_bs ▁pro_bs ši ren je_bs ▁njihove ▁upotreb e .
▁Šta_bs ▁radi ▁tvoj ▁otac ?
▁Rekla ▁je_bs ▁da_bs ▁će_bs ▁do_bs ći_bs .
▁Od mah ▁te_bs ▁obr iš em .
▁Naravno , ▁u_bs bed ljiva ▁osoba ▁bi_bs ▁mogla ▁da_bs ▁ot klon i ▁bilo_bs ▁ka k ve_bs ▁formal ne_bs ▁za_bs vr z la_bs me_bs .
▁- ▁Plan ira te_bs ▁li_bs ▁da_bs ▁uh ap site ▁E isen heim a ?
▁- ▁Chuck ?
▁- He II o !
▁Ti_bs ▁bol es ni_bs ▁ku_bs čki n ▁sine !
▁Zašto ▁se_bs ▁zama raš ▁ , ▁Bro ck man ?
▁Pr va_bs ▁spre m ljena ▁por uka .
▁Da_bs ▁to_bs ▁više_bs ▁nikad ▁nisi ▁u_bs radi la_bs !
▁Kar ta_bs ▁po_bs ker . ▁– Sa če_bs kaj .
▁Pu no_bs ▁si_bs ▁me_bs ▁iz_bs ner vir ao , ▁Ray .
▁Uh , ▁ovdje ▁sam_bs .
▁Te mel j ni_bs ▁u_bs stav ▁Kar o line , ▁autor a ▁fil o zo fa ▁John a ▁Lo cke a ▁trebao ▁je_bs ▁do_bs vesti ▁red ▁u_bs ▁ovu ▁novo na_bs se ljen u ▁div lji nu_bs .
▁Pa_bs ▁da_bs ▁to_bs ▁su_bs ▁nam ▁obe ća_bs li_bs .
▁Treba ▁ CT ▁gla ve_bs , ▁ EK G ▁i_bs ▁prov jer u ▁pr sa .
▁Is pri čaj ▁mi_bs ▁o_bs ▁prvo m ▁putu ▁kad_bs ▁si_bs ▁spava la_bs ▁sa_bs ▁James om_bs .
▁Gre sis , ▁postoji ▁neko ▁za_bs ▁svakog , ▁neko ▁sa_bs ▁ki me_bs ▁ti_bs ▁je_bs ▁su_bs dje no_bs ▁da_bs ▁prove des ▁osta tak ▁zi vo ta_bs .
▁Ne_bs sto ▁sto ▁ze lim ?
▁S_bs jedi os am cije I i dan .
▁Zašto ▁se_bs ▁ne_bs ▁ oka neš ▁tog ▁slik anja ▁i_bs ▁odluči š ▁nešto ▁za_bs ▁svoju ▁budu ć nost ?
▁Sve ▁više_bs ▁djevoj či_bs ca_bs ▁jednostavno ▁ne_bs ▁je_bs de .
▁Č a ša ▁ti_bs ▁je_bs ▁prazn a .
▁Poč i njem ▁misli ti_bs ▁da_bs ▁je_bs ▁vrijeme ▁da_bs ▁iza đem o ▁iz_bs ▁posla ▁Bol en .
▁- Da .
▁Ho ću_bs ▁prizna nje , ▁i_bs ▁uz ima_bs m ▁ga_bs .
▁I_bs ▁kada ▁ki ši .
▁Za_bs ▁vas_bs , ▁on_bs ▁je_bs ▁samo_bs ▁mašin a ▁za_bs ▁r ješ_bs avanje ▁zlo cina .
▁Jesi ▁li_bs ▁je_bs ▁ti_bs ▁na_bs ruč ila ?
▁- ▁ili ▁nešto ▁tak vo .
▁U_bs ▁bor bi_bs ▁do_bs ▁posledn je_bs g ▁čo ve_bs ka_bs , ▁po_bs bed nik je_bs ▁on_bs aj ▁koji_bs ▁posledn ji_bs ▁osta ne_bs ▁na_bs ▁no gama .
▁I_bs ▁ ovi ▁ trag ovi ▁su_bs ▁s_bs vjež i .
▁I_bs ▁bude ▁re čen o : ▁" Ko ▁je_bs ▁vra č ?"
▁Ni sta ▁od_bs ▁ovog a ▁se_bs ▁ne_bs ▁bi_bs ▁des ilo ▁da_bs ▁smo_bs ▁ostali ▁ku_bs ci_bs ▁na_bs ▁Dan ▁Za_bs h val nosti ▁kako_bs ▁Bog ▁i_bs ▁za_bs poved a !
▁O_bs ▁moj_bs ▁Bože , ▁Em ili_bs . ▁Žao ▁mi_bs ▁je_bs .
▁Samo ... bud i ▁pa_bs ž ljiva .
▁Da_bs ▁li_bs ▁ti_bs ▁to_bs ▁pre_bs is pit uješ ▁general ove ▁odluke , ▁kap etan e ?
▁- S r ce_bs ▁se_bs ▁za_bs ple te_bs ▁oko ▁sje či_bs va_bs .
▁nev jer ni_bs cima , ▁neće ▁biti_bs ▁lag ahan .
▁I_bs ▁kaže ▁da_bs ▁neće ▁presta ti_bs .
▁Maj ko_bs , ▁ako_bs ▁opet ▁do_bs dje te_bs ▁u_bs ▁To_bs ki jo , ▁molim ▁te_bs ▁da_bs ▁do_bs dje s ▁u_bs ▁pose tu .
▁Nije .
▁Pa_bs , ▁bilo_bs ▁pravo ▁ili ▁ne_bs , ▁kriv o ▁mi_bs ▁je_bs ▁ ą to ▁nisam ▁poz van ▁na_bs ▁ven čan je_bs .
▁Slu šal a ▁si_bs , ▁zar ▁ne_bs ?
▁Osta ni_bs te_bs ▁na_bs ▁Sul li_bs .
▁Izvini te_bs
▁Se dam ▁dolara ▁dne vno .
▁Možete ▁li_bs ▁plak ati ▁na_bs šao ▁na_bs ▁pravo m ▁mje stu ?
▁Got ovi ▁smo_bs ▁s_bs ▁čeka njem .
▁- Ni je_bs ▁te_bs ▁zna la_bs ▁od_bs ga jati .
▁Bi ćemo ▁na_bs ▁p ješ_bs a čko m ▁most u ▁par ▁sto tina ▁meta ra_bs ▁dalje .
▁- ▁Šta_bs ▁ti_bs ▁je_bs , ▁kom bat ?
▁Čuo ▁sam_bs ▁da_bs ▁spre ma_bs š ▁su_bs tra š nju ▁mem ori jal nu_bs ▁pro_bs s la_bs vu .
▁Ne_bs , ▁ali_bs ▁me_bs ▁po_bs vije st ▁fa s cin ira .
▁Kad ▁je_bs ▁maj ka_bs ▁o_bs ti_bs šla , ▁moj_bs ▁otac ▁je_bs ▁ri ješ_bs io ▁da_bs ▁nikad ▁više_bs ▁ne_bs ▁igra ▁ko ša rku .
▁Reci ▁joj ▁kako_bs ▁mi_bs ▁ide , ▁Alan e .
▁Pro ci_bs tali ▁ste_bs ▁je_bs ▁i_bs ▁da_bs li_bs ▁mi_bs ▁sti pend iju .
▁Be ši ka_bs ▁mu ▁je_bs ▁bila ▁vel ici ne_bs ▁rezerv o ara .
▁U_bs dar ▁od_bs ▁2 ▁meg ato ne_bs ▁nad ▁Se at tle om_bs ▁i_bs ▁1 ▁meg ato ne_bs ▁nad ▁Det ro i tom ▁u_bs ▁ovoj ▁m rac noj ▁v je_bs z bi_bs ▁katastrof e .
▁Neka ▁vaše ▁kar te_bs ▁spremn e , ▁da_bs me_bs .
▁Ne_bs ću_bs ▁to_bs ▁da_bs ▁uradim .
▁Ne_bs ▁želim ▁biti_bs ▁dio ▁ovog a .
▁To_bs ▁mora ▁da_bs ▁je_bs ▁polici ja_bs !
▁Po_bs sljed nja ▁večer a .
▁Hajde !
▁A_bs ▁od_bs ▁tebe ▁nikada ▁ne_bs ću_bs ▁od_bs usta ti_bs .
▁Da_bs ▁vidim o ▁šta_bs ▁će_bs ▁ti_bs ▁večer aš nji ▁san ▁otkri ti_bs .
▁Ova ▁olu ja_bs ▁se_bs ▁nije_bs ▁razvi la_bs ▁u_bs ▁torna do , ▁ali_bs ▁kad_bs ▁to_bs ▁u_bs ci_bs ni_bs ▁stvarno ▁možete ▁da_bs ▁vidi te_bs ▁o_bs cu_bs vanje ▁moment a ▁ koli cine ▁ kret anja ▁u_bs ▁akcij i .
▁Mislim ▁da_bs ▁si_bs ▁ovog a ▁malo ▁previše ▁is_bs p lju vala .
▁Zar ▁on_bs ▁ne_bs ▁spava ▁s_bs ▁drugim a ?
▁- I ▁ja_bs ▁tako_bs dje .
▁Pro pis i ▁o_bs ▁ob la_bs čen ju_bs ?
▁Koliko ▁već ▁uz ima_bs š ▁te_bs ?
▁Ho dat ▁ću_bs .
▁Ne_bs , Ka ish ...
▁Nije ▁sm jela ▁da_bs ▁koristi ▁ni_bs ▁internet .
▁Ar lo_bs ▁će_bs ▁osta ti_bs ▁kod ▁nas_bs ▁na_bs ▁nekoliko ▁dana , ▁ako_bs ▁nema š ▁ništa ▁protiv .
▁Mo ć no_bs ▁mom če_bs ▁me_bs ▁nikada ▁ne_bs ▁bi_bs ▁tako_bs ▁proda o .
▁ze lim ▁da_bs ▁ne_bs sto ▁zna s .
▁- ▁Šta_bs ▁nije_bs ▁u_bs ▁redu ?
▁Imam ▁mnogo ▁proizvoda ▁unutra .
▁Onda ▁bi_bs ▁mogao ▁na_bs let iti_bs ▁kasnije ▁večer as .
▁Pan ter ▁je_bs ▁sa_bs kup lja o ▁informacije ▁o_bs ▁svim a ▁nama , ▁ha kova o ▁je_bs ▁od_bs ▁D Ž AR V ISA ▁naše ▁fa j love .
▁Ja_bs ▁ću_bs ▁ka fu .
▁Prov ući ▁ću_bs ▁je_bs ▁kroz ▁če lo_bs .
▁Zna ▁on_bs ▁kako_bs ▁se_bs ▁osjeća m , ▁ali_bs ▁tako_bs đe ▁zna ▁da_bs ▁ne_bs ▁postoji ▁ništa ▁što_bs ▁možemo ▁u_bs radi ti_bs ▁da_bs ▁to_bs ▁pro_bs m jen imo , ▁tako_bs ▁da_bs ▁nema ▁po_bs ente ▁u_bs ▁priča nju ▁o_bs ▁tome .
▁Uz ▁tebe ▁nije_bs ▁la ko_bs .
▁Muka ▁mi_bs ▁je_bs ▁bilo_bs ▁od_bs ▁tebe ▁mnogo ▁pre_bs ▁toga .
▁Mislim ▁da_bs ▁si_bs ▁ti_bs ▁sada ▁vod nik , ▁D ž ok .
▁Pre zen t acija ▁će_bs ▁mora ti_bs ▁da_bs ▁čeka .
▁Osim ▁u_bs obra že_bs ne_bs ▁ra vno du š nosti .
▁Znam ▁da_bs ▁je_bs ▁malo ▁po_bs vu čen a , ▁ali_bs ▁sme ši ▁se_bs , ▁gr li_bs ▁me_bs ▁i_bs ▁ljubi ▁kao_bs ▁sva ka_bs ▁de_bs voj či_bs ca_bs .
▁O_bs ve_bs ▁reform e ▁le git imiz oval e ▁su_bs ▁Men ema ▁koji_bs ▁je_bs ▁done o ▁više_bs ▁od_bs ▁300 ▁ured bi_bs , ▁10 ▁puta ▁više_bs ▁nego ▁u_bs ▁celo j ▁is_bs tori ji_bs ▁Argent ine .
▁cita la_bs ▁si_bs ▁moj_bs ▁dos je_bs .
▁Je_bs ▁li_bs ▁u_bs ▁redu ?
▁O_bs t kri o ▁sam_bs ▁da_bs ▁je_bs ▁up le_bs ten ▁u_bs ▁proda ju_bs ▁povjer ljivi h ▁podataka .
▁Tim ▁1, ▁videl i ▁smo_bs ▁os um nji ce_bs nog .
▁Međutim ▁ima_bs ▁jedna , ▁sa_bs ▁normal ni_bs jim ▁dogovor om_bs .
▁Z vala ▁sam_bs ▁ih ▁zbog ▁tebe .
▁Jeste ▁li_bs ▁razmišlja li_bs ▁o_bs ▁tome ?
▁Kaž u ▁da_bs ▁je_bs ▁pob ega o ▁zatvoren ik .
▁– On ▁je_bs ▁la ž ov .
▁Gro zan ▁za_bs data k ▁za_bs ▁pre_bs uze t .
▁Ako ▁su_bs ▁van zem al j ci_bs ▁bili ▁ovde ▁u_bs ▁da_bs leko j ▁pro_bs šlo sti_bs , ▁postoji ▁više_bs ▁vrsta ▁tamo ▁ne_bs g de , ▁da_bs ▁li_bs ▁je_bs ▁moguće ▁da_bs ▁mogu_bs ▁da_bs ▁izgleda ju_bs ▁na_bs lik ▁gu š ter ima_bs ▁i_bs ▁m rav ima_bs ?
▁- ▁Šta_bs ▁se_bs ▁dešava ? ▁Po_bs žu ri .
▁Li je_bs po ▁i_bs ▁po_bs lako ▁u_bs ▁po_bs lje .
▁- ▁O_bs ba ▁pal ca_bs ▁en tu zija sti_bs ch ki ▁pod ign uta .
▁Sigur an_bs ▁sam_bs ▁da_bs ▁će_bs ▁J . L . ▁Hall ▁biti_bs ▁vrlo ▁impre sion iran ▁tvoj oj ▁stra š ću_bs ▁za_bs ▁is_bs ku_bs stvo m ▁na_bs ▁Dar t mouth u .
▁Pre t post avljam ▁da_bs ▁naš a ▁sreć a ▁i_bs ▁dalje ▁drži .
▁- ▁Ide š ▁s_bs ▁nama ▁na_bs ▁do_bs ruč ak ?
▁Tri , ▁četiri ▁ ča še ?
▁O_bs vi_bs ▁mali ▁ro đa ci_bs ▁slo nova , ▁samo_bs ▁su_bs ▁de_bs o ▁dugo g ▁lan ca_bs ▁is_bs hra ne_bs .
▁Po_bs bri nut ▁ću_bs ▁se_bs ▁za_bs ▁to_bs . ▁Tre ner u , ▁smi rite ▁svoje ▁de_bs čke .
▁Mogu ▁te_bs ▁vidjeti , ▁Han a !
▁Ti_bs ▁me_bs ▁o_bs stavlja š ▁ra vno du š nim_bs .
▁Do_bs bio ▁je_bs ▁po_bs mil ovanje .
▁Osta vio ▁je_bs ▁ka put ▁kod ▁mene .
▁Pa_bs ▁ako_bs ▁is_bs ▁i_bs spod ▁50 ▁ , ▁mora s ▁malo ▁bolje ▁da_bs ▁se_bs ▁br ines ▁o_bs ▁se_bs bi_bs .
▁Ja_bs ▁sam_bs ▁Charlie ▁You ng .
▁Ne_bs ▁bih ▁dira o ▁ovaj ▁za_bs hod ▁ni_bs ▁sa_bs ▁se_bs stri nim_bs ▁pal cem .
▁Telefon , ▁g đ o ▁Ma tur in .
▁To_bs ula ▁ga_bs ▁voli .
▁Na_bs ▁ovom ▁planet u ▁je_bs ▁uvijek ▁noć .
▁Raz ve_bs o ▁sam_bs ▁se_bs ▁prije ▁mje s ec ▁dana .
▁Zbog ▁toga ▁smo_bs ▁pov eć ali ▁cenu ▁za_bs ▁10 ▁cent i , ▁pa_bs ▁ka fa ▁ko šta ▁50 ▁cent i .
▁Č uj , ▁i_bs ▁kad_bs ▁vas_bs ▁od_bs vez em ▁tamo , ▁moram ▁se_bs ▁vratiti ▁i_bs ▁poslova ti_bs ▁s_bs ▁tom ▁lu kom .
▁Hajde , ▁Ri t chie , ▁ha jde , ▁čovjek , ▁ma ▁da_bs j .
▁Am ita bh ▁mi_bs ▁ga_bs ▁je_bs ▁da_bs o !
▁Ve oma ▁je_bs ▁br z .
▁Onda ▁ignor i raj ▁zakon .
▁Kada ▁sam_bs ▁bio_bs ▁de_bs te_bs ▁ona ▁mi_bs ▁je_bs ▁bila ▁naj dra ža ... ▁i_bs ▁sada ▁vidim ▁da_bs ▁je_bs ▁najlepš a ▁stvar ▁koju ▁sam_bs ▁ik ada ▁video .
▁Hoćeš ▁na_bs stava k ? ▁ . ▁- Po z ovi ▁si_bs ▁koleg e .
▁- ▁Ne_bs . ▁Ve čer as ▁ću_bs ▁razgovara ti_bs ▁s_bs ▁n jom .
▁- ▁Pa_bs , ▁ja_bs ... ▁ne_bs ▁bih ▁to_bs ▁nu ž no_bs ▁tako_bs ▁na_bs zava o .
▁Hvala ▁što_bs ▁si_bs ▁do_bs šla ▁da_bs ▁me_bs ▁vidiš .
▁Gad no_bs ▁sam_bs ▁po_bs gri ješ_bs io .
▁- Ka o ▁da_bs ▁imam ▁pet ▁godina .
▁Je_bs di_bs no_bs ▁o_bs ▁čemu ▁mislim ▁upravo ▁sada ▁je_bs ▁tvoja ▁maj ka_bs , ▁i_bs ▁ ova_bs ▁por o dica .
▁- Pro m jena ▁plan a ▁put ovanja , ▁ze ko_bs .
▁- Mo ž da_bs ▁godina .
▁- A ▁to_bs ▁je_bs ▁oči to ▁bilo_bs ▁dovoljno ▁jako ... ▁da_bs ▁o_bs stavi ▁ trag ove ▁ma gnet ne_bs ▁si_bs le_bs ▁na_bs ▁metal nim_bs ▁objekt ima_bs ▁u_bs ▁bli zini .
▁Znaš , ▁ja_bs ▁sve_bs ▁ovo_bs ▁mogu_bs ▁ku_bs piti ▁preko ▁ne_bs ta_bs .
▁All y ▁je_bs ▁li_bs ▁tvoj ▁drag i ▁sin o ć ▁is_bs me_bs vao ▁moju ▁situa ciju ▁sa_bs ▁Kim i ?
▁Či me_bs ▁se_bs ▁vi ▁ba vite ? ▁- ▁Za_bs prav o ▁sam_bs ▁spis a telj ica .
▁- ▁Kako ▁ste_bs ▁- ▁mama .
▁slo m ljen !
▁Ste ne_bs ▁nam ▁ govor e ▁kako_bs ▁je_bs ▁ovo_bs ▁kop no_bs ▁na_bs sta lo_bs ▁i_bs ▁kako_bs ▁je_bs ▁njihov a ▁ge ologi ja_bs ▁učini la_bs ▁da_bs ▁ovo_bs ▁posta ne_bs ▁gus to ▁na_bs se ljen ▁i_bs ▁na_bs pre dan ▁grad ▁koji_bs ▁pul s ira .
▁- ▁Samo ▁trenutak .
▁- ▁Ko ▁kaže ▁da_bs ▁i_bs ▁ti_bs ▁ne_bs ▁od_bs lu č uješ ?
▁U_bs ▁su_bs prot nom , ▁nema ▁dogovor a .
▁Uz ▁ imit aciju ▁Christ op her ▁Wal ken a ...
▁Pa_bs ▁si_bs ▁prove la_bs ▁noć ▁sa_bs ▁neki m ▁mušk ar cem ?
▁Go s po đi ce_bs , ▁ko ▁je_bs ▁ona ▁žena ?
▁U_bs ▁ima_bs ▁o_bs ca_bs ▁i_bs ▁sina ▁i_bs ▁svet g ▁du ha , ▁a_bs men .
▁Ne_bs ćemo ▁ti_bs ▁dozvoli ti_bs ▁da_bs ▁uz me_bs š ▁Vi bran i jums ku_bs ▁Plan inu !
▁To_bs ▁je_bs ▁bilo_bs ▁jedno ▁u_bs op sten o ▁pis mo_bs .
▁I_bs ▁bio_bs ▁je_bs ▁obje šen .
▁Ci jeli ▁specijal ni_bs ▁tim ▁se_bs ▁s_bs jati o ▁gore .
▁I_bs ▁ne_bs ▁plan i ram ▁biti_bs .
▁Ali_bs ▁to_bs ▁je_bs ▁samo_bs ▁za_bs ▁prijatelj e ▁koji_bs ▁me_bs ▁neće ▁u_bs vre di_bs ti_bs .
▁Dosta ▁si_bs ▁se_bs ▁nas_bs pa vala ▁na_bs ▁satu .
▁Pr vo ▁ti_bs ▁reci ▁meni .
▁Tako ▁se_bs ▁toga ▁ sjeća š ?
▁Po_bs ja_bs vit ▁će_bs ▁se_bs .
▁Mo gli ▁bi_bs ▁ staviti ▁naše ▁ljude ▁izvan ▁lokal nih ▁drog er ija , ▁neka ▁do_bs đu ▁do_bs ▁nas_bs .
▁Kom bin acija ▁Dol ores i nih ▁i_bs ▁Han kovi h ▁meta ka_bs ▁su_bs ▁u_bs bili ▁Ed - a .
▁Ne_bs zna m ...
▁Ni tko ▁nas_bs ▁ne_bs ▁bi_bs ču je_bs .
▁Kuka vice .
▁Tak va_bs ▁me_bs ▁politika , ▁ne_bs ▁zanima !
▁Neka ▁se_bs ▁za_bs piš e ▁da_bs ▁je_bs ▁svjedo k ▁napravi o ▁gest u ▁nosa - tru be .
▁I_bs ▁Sha kes .
▁Ovdje , ▁nema mo_bs ▁mobil ne_bs , ▁ni_bs ▁tv iter , ▁nema ▁om etan ja_bs ▁iz_bs ▁vanjsk og ▁svijet a .
▁Pa_bs , ▁znam_bs o ▁kako_bs ▁izgleda , ▁i_bs ▁znam_bs o ▁da_bs ▁je_bs ▁z la_bs .
▁Iz gu bi_bs ćemo ▁sve_bs jedno .
▁Dobro ▁ga_bs ▁pogleda j !
▁Iz ▁jednog ▁mjesta ▁na_bs ▁drugo .
▁Ti_bs š ina , ▁ti_bs š ina , ▁ti_bs š ina , ▁ti_bs š ina !
▁Du van ske ▁komp a nije ▁vas_bs ▁la žu ▁u_bs ▁vezi ▁op as nosti ▁pu š enja .
▁Stan oda vac ▁me_bs ▁iz_bs ba cio ▁iz_bs ▁stan a .
▁Molim ▁sve_bs ▁za_bs ▁pa_bs ž nju , ▁gospod in ▁T wit che ll ▁bi_bs ▁žele o ▁da_bs ▁kaže ▁par ▁re či_bs .
▁Ver uj ▁mi_bs , ▁izgleda će_bs ▁kao_bs ▁da_bs ▁nisam ▁ni_bs ▁o_bs ti_bs šla .
▁Po_bs kaz ach u ▁vam_bs ▁kako_bs ▁se_bs ▁radi .
▁Vi ski ▁molim .
▁Bol es na_bs ▁si_bs ? ▁Če mu ▁toliko ▁c ve_bs će_bs ?
▁Kako ▁je_bs ▁Li ?
▁... 10 1, ▁10 2, ▁103 ... ▁104 , ▁105 , ▁106 ... ▁107 , ▁108 , ▁10 9, ▁110 ...
▁Znači ▁plan ira te_bs ▁pro_bs vesti ▁puno ▁vremena ▁sa_bs ▁Mer rill ovima .
▁R ačun ala ▁je_bs ▁da_bs ▁će_bs te_bs ▁pris tati .
▁Jesi ▁li_bs ?
▁Manuel ▁Ru iz ! ▁Ha ▁visto ▁este ▁hombre ?
▁Do_bs bi_bs će_bs ▁drugo ▁de_bs te_bs .
▁Film ▁O_bs ri jent acije ▁D har ma_bs ▁broj ▁dva , ▁prvi ▁put .
▁Znaš , ▁ako_bs ▁je_bs ▁u_bs op će_bs ▁moguće , ▁izgleda š ▁još ▁bolje ▁nego ▁prije .
▁Vi ... ▁plan ira te_bs ▁da_bs ▁se_bs ▁vrati te_bs ▁u_bs ▁svoju ▁kolon iju ... ▁na_bs ▁dve , ▁možda ▁i_bs ▁tri , ▁četiri ▁godine .
▁I_bs ▁svaki ▁ru čak .
▁To_bs ▁joj ▁je_bs ▁bila ▁za_bs d nja ▁mol ba .
▁Pro vodi š ▁previše ▁vremena ▁razmišlja jući ▁o_bs ▁pro_bs šlo sti_bs .
▁Spa vam ▁bolje , ▁a_bs ▁također ▁i_bs ▁oko ▁stre lja ne_bs , ▁kad_bs ▁sam_bs ▁se_bs ▁tek ▁vrati o ...
▁Dobro ▁je_bs .
▁Hoćeš ▁pošt ovanje ?
▁- Mi s lim ▁da_bs ▁to_bs ▁ne_bs ▁mogu_bs ▁sredi ti_bs .
▁E , ▁tu ▁je_bs ▁on_bs ▁u_bs ▁pravu .
▁Dobro ▁jutro .
▁En o , ▁to_bs ▁je_bs ▁Sa ul ▁Tar sus .
▁M je_bs sto ▁oku pl janja ▁je_bs ▁na_bs ▁be j z bol ▁ter en u ▁800 ▁m ▁sje ver no_bs - sje ver o isto čno ▁od_bs ▁vas_bs .
▁Na_bs dam ▁se_bs ▁da_bs ▁če te_bs ▁se_bs ▁svi ▁vratiti ▁nazad ▁bez bed no_bs .
▁Mislim ▁da_bs ▁ti_bs ▁od_bs ▁svih ▁ljudi ▁ne_bs ćeš ▁napravi ti_bs ▁nešto ▁ako_bs ▁ne_bs ▁odluči š .
▁Fo x ▁tim , ▁pokr et .
▁N ismo ▁bas ▁bile ▁ti_bs he .
▁Dobro ▁izgleda š , ▁Hu ard .
▁- ▁Da_bs , ▁č ujem ▁vas_bs .
▁" V oli ▁te_bs , ▁ta ta_bs ."
▁Mislim ▁da_bs ▁su_bs ▁nauči li_bs ▁ lek ciju .
▁Iz la_bs z nost ▁na_bs ▁izbor ima_bs ▁za_bs ▁Evropsk i ▁parlament ▁u_bs ▁ju nu_bs , ▁zadnje m ▁glas an_bs ju_bs ▁koje ▁je_bs ▁organiz irano ▁u_bs ▁Ru muni ji_bs , ▁bila ▁je_bs ▁tek ▁27 % .
▁Ko ji_bs ▁dio ▁dugo g ▁ zim skog ▁sna ▁nisi ▁razum io ?
▁- V ani ▁je_bs ▁tako_bs ▁lijepo !
▁Kakv o ▁s_bs ranje ."
▁To_bs ▁ti_bs ▁garant ujem .
▁Da_bs ▁te_bs ▁po_bs ve_bs žem ?
▁" Ka kav ▁je_bs ▁ose ća_bs j ▁kad_bs ▁vas_bs ▁tele port uju ?"
▁Tek ▁je_bs ▁prv a ▁če tvrt ina .
▁Radi m ▁za_bs ▁Gospod ina ▁Bar kle ya .
▁O_bs ma_bs tica ye ▁su_bs ▁nauči li_bs ▁o_bs ▁nama , ▁ono liko ▁koliko ▁im ▁treba_bs .
▁Pa_bs ... ▁među ▁nama ...
▁Treba m ▁ ključ ▁za_bs ▁vrata .
▁- O va_bs kva ▁od_bs je_bs ća_bs ▁se_bs ▁nos ila ▁ra nih ▁' 90 - ih .
▁- ▁Ho ću_bs ▁sud bin u !
▁Treba ▁nam ▁rezerv ni_bs ▁plan .
▁Ali_bs ▁šta_bs ▁ako_bs ▁su_bs ▁mu ▁de_bs ca_bs ▁ važ nija ▁od_bs ▁da_bs di_bs lja ?
▁Sad ▁kad_bs ▁je_bs ▁Oliver ▁za_bs uze o ▁svoju ▁pozicij u ▁kao_bs ▁na_bs sljed nik ▁Demo na_bs , ▁do_bs ći_bs ▁će_bs ▁po_bs ▁mene , ▁sa_bs ▁koliko ▁god ▁ljudi ▁bude ▁potrebno ▁da_bs ▁me_bs ▁ubije .
▁Pu no_bs ▁ga_bs ▁volim . ▁I_bs ▁ja_bs .
▁Doug , ▁dosta ▁tip ovima ▁je_bs ▁moje ▁oko ▁od_bs boj no_bs .
▁Mislim ▁da_bs ▁je_bs ▁u_bs ▁kan tini .
▁Kur vin ▁sine !
▁Moram ▁biti_bs ▁na_bs ▁dužn osti ▁i_bs ▁no ću_bs ▁i_bs ▁dan ju_bs .
▁Pa_bs , ▁reci mo_bs , ▁koje ▁bo je_bs ▁želiš ▁da_bs ▁bude ?
▁Stvarno ▁smo_bs ▁kre nu_bs li_bs , ▁je_bs l ' ▁da_bs , ▁komp i ću_bs ?
▁O_bs , ▁Bar ney !
▁Ti_bs ▁si_bs ▁pre_bs var ant ▁i_bs ▁ lop ov , ▁kao_bs ▁i_bs ▁ja_bs , ▁kao_bs ▁i_bs ▁svi ▁ostali .
▁Raz umi o ▁sam_bs , ▁čuva t ▁ćemo ▁ih .
▁Ce ka_bs ▁is_bs pred .
▁Do_bs ne_bs site ▁shi zz le_bs !
▁ KO ng res ▁je_bs ▁done o ▁zakon ▁o_bs ▁od_bs bran i ▁bra ka_bs .
▁Molim ▁vas_bs ▁učini te_bs ▁mi_bs ▁čas t ▁i_bs ▁prihvat ite ▁moju ▁ru ku_bs .
▁Ta mo_bs , ▁vrati te_bs ▁se_bs , ▁skoro ▁ste_bs ▁ uspje li_bs .
▁Dan as ▁se_bs ▁o_bs bil je_bs ? ▁av a ▁kraj ▁global ne_bs ▁katastrof e .
▁Je_bs ▁si_bs ▁li_bs ▁dobi la_bs ?
▁Zdravo , ▁Mur p hy .
▁Pr va_bs ▁i_bs spod ▁c rte .
▁Radi ▁se_bs ▁o_bs ▁ne_bs čem u ▁što_bs ▁ste_bs ▁na_bs pis ali ▁prije ▁o_bs sam ▁godina , ▁o_bs ▁u_bs krš ten oj ▁D N K .
▁Na_bs ▁visi ni_bs ▁o_bs ciju .
▁Francusk i ▁fil oz of ▁Ro land ▁Bar the s ▁opis ao ▁je_bs ▁tra umu ▁kao_bs ▁foto graf sku ▁ vije st ▁bez ▁fotografi je_bs .
▁Pre uze o ▁sam_bs ▁tu ▁so bu ▁kada ▁je_bs ▁otišao .
▁Imaš ▁pravo . ▁Dobro , ▁šta_bs ▁mogu_bs ▁učiniti ▁da_bs ▁pomogne m ?
▁Nisam ▁ga_bs ▁ja_bs ▁na_bs t jera o ▁da_bs ▁is_bs kora ci_bs ▁pred ▁autobus , ▁Sam .
▁To_bs ▁se_bs ▁re do vno ▁dešava .
▁Polic aj ci_bs .
▁Sad ▁pov jes nica ri ▁revi zioni sti_bs ▁ka zu ▁da_bs ▁je_bs ▁bomb a ▁prest ras ila ▁Rus e .
▁Šta_bs ▁će_bs ▁se_bs ▁des iti_bs ▁bez ▁operacij e ?
▁Se stra ▁Hu ghe s , ▁da_bs ▁se_bs ▁ja_bs vi_bs ▁Hi tan ▁prije m .
▁Na_bs ▁primer , ▁D žu li_bs jan ▁Ma ster s .
▁Be ▁my ▁ white ▁kn ight .
▁Hvala .
▁Osim ▁toga , ▁u_bs ▁izvještaj ima_bs ▁se_bs ▁na_bs gov ješ_bs tava ▁da_bs ▁je_bs ▁tur ska ▁komp a nija ▁pri_bs sta la_bs ▁da_bs ▁investi ra_bs ▁20 ▁milion a ▁e ura ▁u_bs ▁njen ▁razvoj .
▁- ▁Da_bs . ▁K nji ga ▁o_bs ▁kojoj ▁sam_bs ▁ti_bs ▁priča o ▁je_bs ▁na_bs ▁moj_bs oj ▁kom odi .
▁Ro đa ci_bs ▁ljudi ▁koje ▁je_bs ▁u_bs bio ...
▁Bu d že_bs tom ▁se_bs ▁poziv a ▁na_bs ▁de_bs fici t ▁od_bs ▁200 m ▁e ura , ▁za_bs ▁koji_bs ▁se_bs ▁kaže ▁da_bs ▁iznos i ▁ukupn o ▁0, 6% ▁od_bs ▁B DP - a .
▁Ne_bs ▁želi ▁Allah ▁da_bs ▁vam_bs ▁učini ▁ik ak vu ▁teško ću_bs , ▁nego ▁želi ▁da_bs ▁vas_bs ▁oči sti_bs ▁i_bs ▁da_bs ▁vam_bs ▁u_bs pot pun i ▁bla go dat ▁S_bs voj u , ▁da_bs ▁bi_bs ste ▁vi ▁zahval ji_bs vali .
▁ OD G OV OR ▁JE ▁D RA KK AR ▁NO IR , ▁V INT AGE ▁19 88 . - A .
▁Ta mo_bs ▁su_bs .
▁Da_bs ▁te_bs ▁pokr i jem .
▁Mislim ▁da_bs ▁bi_bs ▁ti_bs ▁i_bs ▁ja_bs ▁mogli ▁da_bs ▁nauči mo_bs ▁jedno ▁drugo ▁mnogo ▁čemu , ▁pa_bs ... ▁da_bs ▁li_bs ▁si_bs ▁s_bs lobo dan ▁za_bs ▁večer u ▁su_bs tra ▁u_bs ve_bs če_bs ?
▁I_bs ▁koliko ▁se_bs ▁pro_bs si rio ▁taj ▁ose ca_bs j ?
▁- ▁Što ▁si_bs ▁rekao , ▁ tko ▁ba ca_bs ?
▁# ▁Samo ▁smo_bs ▁ja_bs , ▁ti_bs ▁i_bs ▁ljubav ▁# ▁# ▁u_bs ▁K ▁A_bs ▁D ▁I_bs . ▁#
▁To_bs ▁nije_bs ▁način ▁na_bs ▁koji_bs ▁si_bs ▁me_bs ▁nauči o ▁živ jeti .
▁U_bs ▁redu , ▁do_bs šta ▁o_bs ▁Su t ton .
▁Za_bs d iranje ▁u_bs ▁privat nost , ▁da_bs .
▁- ▁Jedno ▁crn o ▁is_bs ku_bs stvo .
▁Za_bs ista ?
▁Sigur na_bs ▁sam_bs ▁da_bs ▁se_bs ▁možemo ▁neka ko_bs ▁dogovor iti_bs .
▁Zbog ▁toga ▁si_bs ▁ hte o ▁da_bs ▁se_bs ▁vrati š .
▁Mia , ▁samo_bs ▁još ▁jedna .
▁Č uj , ▁ion ako ▁bi_bs ▁te_bs ▁h tio ▁ubiti .
▁Ne_bs ... ▁samo_bs ▁se_bs ▁sme ši la_bs .
▁Ali_bs ...
▁Ne_bs ▁bu dite ▁zlo b ne_bs .
▁Val ja_bs ju_bs ▁drog u ▁por ed ▁kli nike , ▁čovječe .
▁Z go dan .
▁Fra k ture ▁po_bs či_bs nju ▁45 ▁cm ▁od_bs ▁stop ala .
▁Ne_bs ▁još .
▁- DA . ▁DO KA Z U JE ▁O_bs NO ▁S_bs TO ▁JE ▁Z IVA ▁S_bs UM N JA LA .
▁Kako ▁znate ▁da_bs ▁je_bs ▁to_bs ▁naš ▁diz ajn ?
▁Mislim ▁da_bs ▁je_bs ▁Rand ▁bi_bs ▁bili ▁s_bs ret ni_bs ▁da_bs ▁se_bs ▁uspostav i ▁... ▁su_bs sje d stvu ▁don acija ▁poboljša nje ▁da_bs ▁se_bs ▁tro ši ▁i_bs pak ▁ste_bs ▁od_bs a bra li_bs .
▁Znaš , ▁kao_bs ▁jo ge .
▁Rekao ▁sam_bs ▁da_bs ▁mr zim ▁ovakv o ▁do_bs vi_bs ki vanje .
▁Sve ▁sam_bs i ▁ke če_bs vi_bs .
▁Do_bs bio ▁si_bs , ▁Pa_bs ddy !
▁Dakle , ▁ako_bs ▁nije_bs ▁ništa ▁radio ▁kriv o , on da_bs ▁datum ▁na_bs ▁ovim ▁dokument ima_bs ▁nije_bs ▁is_bs prav an_bs . ▁I_bs ▁prema ▁use ljeni čki m ▁zakon ima_bs ▁ove ▁zemlje ▁čini ▁ih ▁ne_bs val ja_bs nim_bs ▁i_bs ▁ništa v nim_bs . ▁- ▁Ne_bs !
▁G la_bs z be nik ... ▁sluša j !
▁Kaž eš ▁da_bs ▁me_bs ▁voli š , ▁da_bs ▁ce š ▁me_bs ▁uvijek ▁vol jeti ...
▁Ti_bs ▁si_bs .
▁- ▁Ti_bs ▁si_bs ▁o_bs vis nica ! ▁Slušaj !
▁Kako ▁ide , ▁Greg ?
▁Bil e ▁su_bs ▁Lucy ▁i_bs ▁Claire .
▁Ovo ▁će_bs ▁biti_bs ▁savršen ▁bra k ... ▁ad rena lina ▁i_bs ▁op as nosti .
▁A_bs ... ne_bs ▁svi đa ▁mi_bs ▁se_bs ▁kako_bs ▁izgleda m ▁sa_bs ▁c vi_bs ker ima_bs .
▁Pres v la_bs či_bs ▁Za_bs cha , ▁por ed ▁baz ena .
▁Ne_bs ▁znam_bs .
▁- Ti ▁to_bs ▁ozbiljn o ?
▁Ne_bs ▁u_bs ci_bs ▁dije te_bs ▁tak vom ▁ govor u , ▁ cov je_bs ce_bs .
▁Bože , ▁kako_bs ▁ti_bs ▁mora ▁da_bs ▁pati š .
▁Zato ▁moram ▁da_bs ▁ga_bs ▁vidim .
▁- O be ća_bs j ▁da_bs ▁me_bs ▁ne_bs ćeš ▁pre_bs bi_bs ti_bs . ▁Jer ▁me_bs ▁može ▁pre_bs bi_bs ti_bs .
▁To_bs ▁je_bs ... ▁nepo že_bs l j no_bs ? ▁- ▁Ve oma .
▁To_bs ▁ob jas nja va_bs ▁pov rede ▁koje ▁lice ▁na_bs ▁na_bs si lje .
▁Tre nut no_bs ▁se_bs ▁Si ri jski ▁ar sen al ▁sa_bs stoj i ▁od_bs ▁nekoliko ▁hil ja_bs da_bs ▁So vjet skih ▁br zi_bs h ▁projekt ila . ▁U_bs ▁su_bs šti ni_bs ▁bomb e ▁u_bs ▁ci jevi ma_bs ▁pri_bs ka_bs čen e ▁na_bs ▁veoma ▁ne_bs sigur no_bs ▁gor ivo .
▁Pokuša t ▁ću_bs ▁diplom at sko ▁ rje šenje .
▁Onu ▁drug u ▁des nu_bs .
▁Bila ▁bi_bs ▁ste_bs ta_bs .
▁Ona ▁je_bs ▁za_bs ▁bu dale ▁koje ▁ne_bs ▁zna ju_bs ▁gleda ti_bs ▁slik u , ▁pa_bs ▁po_bs nav lja ju_bs ▁ono ▁što_bs ▁druge ▁bu dale ▁ govor e .
▁- ▁Ju ana , ▁tebi ▁govori m .
▁On ▁je_bs ▁kralj ▁org ija .
▁Ka ranje ▁u_bs ▁pak su .
▁Sve ▁je_bs ▁povez ano .
▁Osim ▁toga , ▁vidim ▁da_bs ▁ion ako ▁je_bs d va_bs ▁ce ka_bs š ▁da_bs ▁mi_bs ▁kažeš .
▁Sto ji_bs ▁69 ▁$ .
▁" T re_bs nut ni_bs ▁prostor ▁mogućnost i ▁nije_bs ▁ne_bs og rani čen , ▁a_bs ▁malo ▁toga ▁govori ▁da_bs ▁će_bs ▁budu ć nost ▁donijeti ▁p ovolj nije ▁okolnosti ▁za_bs ▁na_bs god bu , " ▁izjavi o ▁je_bs ▁on_bs .
▁Znam ▁da_bs ▁sve_bs ▁izgleda ▁bez na_bs de ž no_bs ▁sada , ▁ali_bs ▁ob eć avam ▁ti_bs ▁ima_bs ▁puno ▁stvari ▁za_bs ▁koje ▁moraš ▁živ jeti .
▁Drago ▁mi_bs ▁je_bs ▁da_bs ▁smo_bs ▁na_bs i šli ▁kad_bs ▁ste_bs ▁kod ▁ku_bs će_bs
▁Hajde ▁da_bs ▁proba mo_bs ▁ovo_bs , ▁pomoći ▁će_bs ." ▁Ne_bs , ▁neće .
▁Šta_bs ▁to_bs ▁znači ?
▁Šta_bs ▁je_bs ▁sadržaj ▁že lu ca_bs ?
▁Ne_bs da_bs vni ▁događa ji_bs ▁su_bs ▁da_bs li_bs ▁novo ▁svet lo_bs ▁na_bs ▁osnov u ▁činjenic a ▁i_bs ▁fizičk ih ▁dokaz a ▁koji_bs ▁bi_bs ▁trebali ▁da_bs ▁pomo g nu_bs ▁dokaz i vanju ▁posto janja ▁van zem al j skog ▁života ▁što_bs ▁je_bs ▁osnov a ▁Mol der ove ▁ve like ▁pos ve_bs će_bs nosti ▁svo m ▁rad u
▁Kli nci , ▁u_bs glav nom , ▁tra že_bs ▁let nji ▁posao ▁po_bs ▁resto ran ima_bs .
▁Trebal a ▁bi_bs ▁da_bs ▁do_bs d jem ▁do_bs ▁za_bs m ka_bs .
▁Naravno , ▁kli na_bs c .
▁Dobro , ▁idemo , ▁idemo !
▁Do_bs z voli ćeš ▁da_bs ▁ stavi ▁je_bs zik ▁u_bs ▁tvoja ▁usta .
▁Moramo ▁ih ▁gr li_bs ti_bs ▁i_bs ▁ljubi ti_bs ▁na_bs ▁u_bs lica ma_bs ▁u_bs ▁ku_bs ća_bs ma_bs , ▁u_bs ▁kan cela rija ma_bs , ▁u_bs ▁njihov im_bs ▁um ovima .
▁Svi ▁se_bs ▁č vrst o ▁Allah ova_bs ▁už eta ▁drži te_bs ▁i_bs ▁ nika ko_bs ▁se_bs ▁ne_bs ▁raz jedi nju jte ! ▁I_bs ▁s_bs jeti te_bs ▁se_bs ▁Allah ove ▁mil osti ▁prema ▁vam_bs a ▁kada ▁ste_bs ▁bili ▁ jedni ▁drugim a ▁nepri ja_bs telj i , ▁pa_bs ▁je_bs ▁On ▁s_bs loži o ▁s_bs r ca_bs ▁vaš a ▁i_bs ▁vi ▁ste_bs ▁postal i , ▁mi_bs lo_bs š ću_bs ▁Njegov om_bs , ▁prijatelji ; ▁i_bs ▁bili ▁ste_bs ▁na_bs ▁i_bs vi_bs ci_bs ▁ vat rene ▁ja_bs me_bs , ▁pa_bs ▁vas_bs ▁je_bs ▁On ▁nje ▁spasi o . ▁Tako ▁vam_bs ▁Allah ▁ob jašnj ava ▁S_bs voj e ▁dokaz e , ▁da_bs ▁bi_bs ste ▁na_bs ▁Prav om_bs ▁putu ▁is_bs tra jali .
▁To_bs ▁je_bs ▁zbog ▁stvari ▁na_bs ▁tra ci_bs .
▁Na_bs bavi ću_bs .
▁Ci jeli ▁grad ▁je_bs ▁došao .
▁Bo ze ▁moj_bs .
▁- La ski . ▁Pr vo , ▁nisam ▁že lje la_bs ▁da_bs ▁budem ▁čas nik ▁za_bs ▁obu ku_bs , ▁ali_bs ▁je_bs ▁bolje ▁od_bs ▁vampir a .
▁Auto put ▁pro_bs sje čen ▁pravo ▁kroz ▁ki š nu_bs ▁š umu .
▁Slušaj , ▁moram ▁da_bs ▁vidim ▁tebe ▁i_bs ▁Hej li_bs . ▁Zato ▁što_bs ▁ja_bs ▁radim ▁i_bs ▁sa_bs vet ovanje ▁par ova_bs .
▁Zato ▁što_bs ▁ti_bs ▁na_bs ši ▁val ovi ▁više_bs ▁neće ▁biti_bs ▁taj na_bs .
▁Mo že_bs ▁se_bs ▁reći ▁da_bs ▁joj ▁je_bs ▁ovaj ▁grad ▁slo mi o ▁du h .
▁Dr . ▁Di x on , ▁hvala ▁vam_bs ▁puno .
▁U_bs pa o ▁je_bs ▁u_bs ▁ ša htu ▁od_bs ▁li_bs f ta_bs .
▁U_bs ▁redu , ▁ako_bs ▁ce ▁biti_bs ▁tako_bs , ▁ja_bs ▁cu ▁samo_bs , ▁uh ...
▁Niko ▁me_bs ▁nije_bs ▁osta vio .
▁Za_bs ba van ▁dan ?
▁Što ▁se_bs ▁ti_bs če_bs ▁Ben a , ▁rekao ▁si_bs ▁da_bs ▁ću_bs ▁ga_bs ▁ubiti ▁kad_bs ▁č ujem ▁šta_bs ▁ima_bs ▁za_bs ▁reći .
▁Moja ▁žena ▁u_bs bi_bs ću_bs ▁je_bs !
▁Pe tak ▁več e , ▁a_bs ▁tip ▁koji_bs ▁ima_bs ▁go mi lu ▁rub ina ▁sentiment alan ▁je_bs ▁oko ▁jednog ▁ma log ▁bis era ?
▁A_bs , ▁po_bs če_bs li_bs ▁smo_bs ...
▁Gi ba j ▁se_bs ▁uz ▁muzik u .
▁Zna s ▁bilo_bs ▁sta ▁posebno ▁za_bs ▁so bu ▁za_bs ▁bri dz .
▁Pu c nja va_bs ▁u_bs ▁sud nici , ▁pokuša li_bs ▁da_bs ▁u_bs bi_bs ju_bs ▁Hor ej ši ja_bs ▁us red ▁bela ▁dana ...
▁Za_bs prav o ▁imam ▁tamo ▁neko g ▁posla .
▁Na_bs pa š ćemo ▁veliko m ▁br zi_bs nom ▁kako_bs ▁bi_bs ▁neutral is ali ▁njihovo ▁ jon sko ▁oružje .
▁- ▁Ako ▁osta ne_bs , ▁posta će_bs ▁sumnj ič av .
▁Moz da_bs ▁cu ▁treba_bs ti_bs ▁in tu b irati .
▁Gor e ▁na_bs ▁počet ak , ▁g . ▁San til li_bs .
▁- ▁Bri neš ▁se_bs ▁o_bs ▁mom ▁" mesi ću_bs " ▁?
▁- Ho ćeš ▁na_bs grad u ?
▁Plat io ▁je_bs ▁kroz ▁nos ▁za_bs ▁za_bs d ovolj stvo .
▁- Su sti_bs že_bs ▁nas_bs .
▁Bu da_bs lo_bs , ▁zašto ▁ne_bs ▁puc aš ?
▁Poz na_bs ješ_bs ▁La ▁Qui cu_bs ?
▁O_bs tvor i ▁vrata !
▁Jer , ▁ako_bs ▁dozvoli š ▁da_bs ▁bude ▁zbog ▁tebe , ▁onda ▁pro_bs pada š .
▁Bio ▁sam_bs ▁pri_bs govara č ▁sav je_bs sti_bs !
▁On ▁bi_bs ▁usko čio ▁i_bs ▁odgovara o ▁ili ▁is_bs pravlja o ▁ljude .
▁Zna o ▁sam_bs ▁da_bs ▁će_bs ▁s_bs ▁tom ▁ pti com ▁biti_bs ▁problema .
▁Kako ▁to_bs ▁radiš ?
▁Allah ▁svjedo či_bs ▁da_bs ▁je_bs ▁is_bs tina ▁ono ▁što_bs ▁ti_bs ▁ob javljuje , ▁ob javljuje ▁ono ▁što_bs ▁On ▁jedini ▁zna , ▁a_bs ▁i_bs ▁mele ki ▁svjedo če_bs ; ▁– ▁a_bs ▁dovolj an_bs ▁je_bs ▁Allah ▁kao_bs ▁svjedo k .
▁Jane ▁Val ▁je_bs ▁je_bs li_bs ▁dos ao
▁Bila ▁je_bs ▁tako_bs ▁le pa .
▁- Ti ▁si_bs ▁iz_bs uze t no_bs ▁ljudsk o ▁bi_bs će_bs .
▁Nema ▁te_bs ▁na_bs ▁pos lu , ▁do_bs dje s ▁ta kav , ▁i_bs ▁o_bs ce_bs ku_bs jes ▁da_bs ▁te_bs ▁ne_bs ▁pi tam ▁sta ▁se_bs ▁des ava ?
▁Sam ▁Win che ster ▁je_bs ▁sigurno ▁ovdje ▁bio_bs .
▁- U ▁redu , ▁kod ▁Bu tter mana .
▁To_bs ▁je_bs ▁bilo_bs ▁gru bo , ▁g . ▁Har per u .
▁Ovo ▁je_bs ▁ob i can ▁ne_bs do stoj an_bs st ven o .
▁Ti_bs ▁mora ▁da_bs ▁si_bs ▁Ram se y .
▁G . ▁Th omp son ...
▁Ova ▁na_bs ka_bs za ▁nije_bs ▁u_bs op šte ▁iz_bs bri sala ▁video ...
▁Možda ▁će_bs ▁ga_bs ▁to_bs ▁nauči ti_bs ▁da_bs ▁ubu du će_bs ▁drži ▁je_bs zik ▁za_bs ▁zu bi_bs ma_bs .
▁- ▁Meg an_bs ▁misli ▁da_bs ▁Joe ▁u_bs bio ▁svog ▁brat a ▁previše .
▁Ne_bs ▁mogu_bs ▁pod nije ti_bs ▁ce ndra nje !
▁I_bs ▁oni ▁su_bs ▁se_bs ▁po_bs vrat ili_bs ▁oba s uti ▁Allah ovi m ▁bla go dat ima_bs ▁i_bs ▁o_bs bil jem , ▁nik ak vo ▁ih ▁zlo ▁nije_bs ▁za_bs des ilo ▁i_bs ▁post i gli ▁su_bs ▁da_bs ▁Allah ▁bude ▁ njima ▁za_bs d ovolj an_bs ▁– ▁a_bs ▁Allah ▁je_bs ▁ne_bs iz m jer no_bs ▁dobar .
▁Bol io ▁me_bs ▁je_bs ▁sto mak .
▁Na_bs dam ▁se_bs ▁da_bs ▁si_bs ▁glad an_bs .
▁Ako ▁je_bs ▁to_bs ▁jedini ▁koji_bs ▁ima_bs te_bs , ▁pop uni ćemo ▁ga_bs .
▁Bit ▁ćeš ▁ti_bs ▁dobro .
▁Izgleda ▁kao_bs ▁jedna ▁od_bs ▁o_bs nih ▁scen a ▁kada ▁star e ▁z grade ▁min iraju ▁din ami tom .
▁Ho češ ▁li_bs ▁mi_bs ▁ik ada ▁oprosti ti_bs , ▁Pa_bs d mé ?
▁Imamo ▁malo ▁vremena .
▁Vaš a ▁hra bro st ▁i_bs ▁žrtv a ▁će_bs ▁biti_bs ▁za_bs u vek ▁za_bs pam će_bs ni_bs .
▁Ko ▁je_bs ▁le čio ▁vaše g ▁sina ?
▁Nije ▁tako_bs ▁bit no_bs . ▁Maj ka_bs ▁je_bs ▁pro_bs na_bs šla ▁hal jin u ▁skr oz ▁po_bs kis nut u ▁kod ▁pr lja vi_bs h ▁od_bs ela .
▁O_bs ček ujem ▁da_bs ▁živi m ▁d vo stru ki ▁život .
▁On ▁je_bs ▁bio_bs ▁i_bs ▁iz_bs ▁Bell e view ...
▁Zašto ▁si_bs ▁se_bs ▁moral a ▁ud ati ▁za_bs ▁njega ?
▁- Ne ▁želim ▁ga_bs .
▁Mo gli ▁bismo ▁da_bs ▁ba ci_bs mo_bs ▁B . L . F . ▁kan ister ▁jednom ▁kad_bs ▁smo_bs ▁na_bs ▁prijatelj skoj ▁teritorij i .
▁Ja_bs ▁sam_bs ▁bio_bs ▁uz bu đen ▁kad_bs ▁sam_bs ▁pro_bs na_bs šao ▁ma mu .
▁Nema ▁kost iju .
▁O_bs ko_bs ▁1 ▁500 ▁dolara .
▁Bila ▁si_bs ▁temelj an_bs ▁i_bs ▁pa_bs ž ljiv ▁detektiv !
▁Kaž ete ▁da_bs ▁je_bs ▁kriv ac ▁neko ▁iz_bs ▁moje ▁por o dice ?
▁Osim ▁sto ▁su_bs ▁raz ine ▁glu ko_bs ze ▁normal ne_bs ▁i_bs ▁spo menu o ▁bi_bs ▁da_bs ▁je_bs ▁dija be tica r . ▁A_bs ▁ul ce_bs roz ni_bs ▁kol iti_bs s ?
▁- J ed no_bs stav no_bs ▁je_bs sam , ▁El lie .
▁El ▁Os o ▁uvijek ▁ud ara ▁Sa la_bs zara ▁po_bs ▁gla vi_bs ▁sa_bs ▁sva ci_bs me_bs , ▁a_bs ▁neka da_bs ▁obu ku_bs ▁i_bs ▁hal ji_bs ne_bs .
▁C ime ▁se_bs ▁ti_bs ▁stvarno ▁ba viš ?
▁Pokuša vala ▁sam_bs ▁da_bs ▁iz_bs be gne m ▁gas nu_bs ▁kom or u , ▁a_bs ▁ne_bs ▁da_bs ▁se_bs ▁u_bs šu nja m ▁u_bs ▁neki ▁škol ski ▁ok rug .
▁Ako ▁ne_bs ▁budem o ▁i_bs mali ▁bor ca_bs , ▁Ako ▁će_bs ▁biti_bs ▁os ra_bs mo_bs će_bs n .
▁10 ▁hil ja_bs da_bs . ▁Želiš ▁li_bs ▁da_bs ▁na_bs đe š ▁neko ga ▁drugog a ▁ko ▁će_bs ▁do_bs ći_bs ▁ovde ▁da_bs ▁kop a ? ▁Il aj ?
▁I_bs di_bs ▁i_bs ▁traži ▁ih .
▁Ka kav ▁savršen ▁plan !
▁Bo jim ▁se_bs , ▁mislim ▁na_bs ▁sve_bs .
▁Sa ▁svim e ▁što_bs ▁tr pa š ▁u_bs ▁sebe ?
▁Ovdje ?
▁Gospod ine ▁Vil son .
▁U_bs ▁redu , ▁vidim ▁gde ▁ovo_bs ▁ide .
▁Ako ▁se_bs ▁ne_bs ▁mogu_bs ▁sa_bs s vim ▁sj etiti ▁Nick a , ▁onda ▁cu ▁ga_bs ▁radi je_bs ▁sa_bs s vim ▁zaboravi ti_bs !
▁To_bs ▁nema ▁nik ak ve_bs ▁veze ▁sa_bs ▁on_bs im_bs ▁što_bs ▁se_bs ▁dogodilo ▁Dže fu .
▁- I ▁ako_bs ▁ga_bs ▁posluša te_bs ... ▁svi ▁ćemo ▁se_bs ▁u_bs vali ti_bs ▁u_bs ▁ne_bs vol ju_bs .
▁Uh ap še na_bs ▁zbog ▁napad a ▁u_bs ▁Ga m la_bs ▁Stan u ▁1998 . ▁kada ▁smo_bs ▁joj ▁uz eli ▁ot iske .
▁Zašto ?
▁- ▁Ona ▁me_bs ▁pod se ca_bs ▁na_bs ...
▁To_bs ▁je_bs ▁za_bs ▁ tje sko bu ... ▁de_bs pres iju , ▁bol .
▁Ja_bs ▁ njima ▁treba_bs m .
▁Mora te_bs ▁biti_bs ▁jaki ▁i_bs ▁hit ri .
▁A_bs ▁onda ... ▁Na_bs z vao ▁me_bs ▁ta ta_bs .
▁To_bs ▁je_bs ▁posebno .
▁- ▁The ▁Ca ve_bs .
▁U_bs ▁redu , ▁dosta ▁raz gla ban ja_bs .
▁- ▁To_bs ▁je_bs ▁ono ▁sto ▁se_bs ▁nada mo_bs .
▁Stvarno ▁vam_bs ▁ne_bs ▁mogu_bs ▁reći .
▁C isto s kopi ja_bs ▁ne_bs ▁pa_bs li_bs .
▁Ali_bs ▁ako_bs ▁mo zes , ▁treba_bs ▁mi_bs ▁tvoja ▁pomoc .
▁Kakv a ▁je_bs ▁to_bs ▁je_bs bi_bs ga ▁ne_bs prav da_bs ?
▁Moj ▁ bož ić ni_bs ▁po_bs klon ▁za_bs ▁vas_bs ...
▁" Po s lo_bs da_bs vac ." ▁Da_bs ▁na_bs piš em ▁bilo_bs ▁šta_bs ?
▁Da_bs ▁li_bs ▁si_bs ▁ik ada ▁bio_bs ▁sa_bs ▁že nom ?
▁- ▁O_bs stavi ▁me_bs ▁na_bs ▁mir u !
▁[ dr ve_bs ta_bs ▁š kri pa ]
▁Na_bs vig acija ▁je_bs ▁ot ka_bs zala .
▁- U ▁iz_bs v ješ_bs ću_bs ▁pi še ▁105 ▁km / h .
▁Nema te_bs ▁izbor :
▁U_bs običajen o , ima_bs li_bs ▁smi ▁mali ▁pr ble m ▁s_bs ▁provi zi_bs jom .
▁Jeste ▁li_bs ▁u_bs ▁moj_bs oj ▁so bi_bs ?
▁Bez ▁br ige , ▁još ▁malo .
▁Hoćeš ▁reći ... ▁O_bs kri v ljiva nje ▁pred ▁Se na_bs tom ?
▁Mo g lo_bs ▁bi_bs ▁posta ti_bs ▁ru ž no_bs .
▁Ti_bs ... ▁Govori la_bs ▁si_bs ▁da_bs ▁ne_bs ▁bi_bs ▁mogla ▁da_bs ▁ga_bs ▁pre_bs boli š .
▁Ja_bs ▁imam ▁jako ▁malo ▁u_bs tica ja_bs ▁na_bs ▁sve_bs ▁ovo_bs . ▁Zašto ▁je_bs ▁tako_bs ?
▁Poč i njem ▁da_bs ▁os eć am ▁bol .
▁Za_bs d ovolj stvo ▁mi_bs ▁je_bs , ▁stvarno .
▁Sad ▁imam ▁samo_bs , ▁misi ju_bs .
▁- Ne , ▁ali_bs ▁ćeš ▁mi_bs ▁se_bs ▁ti_bs ▁možda ▁vratiti .
▁Znaš ▁da_bs ▁nije_bs ▁bilo_bs ▁potrebe ▁da_bs ▁spava š ▁sam_bs nom .
▁Se stra ▁će_bs ▁biti_bs ▁vrlo ▁tu ž na_bs .
▁Njegov ▁rezerv ni_bs ▁polo za j , ▁jos ▁uvek ▁je_bs ▁ne_bs pozna t .
▁Za_bs tim ▁se_bs ▁mil ord ▁po_bs ja_bs vio ▁izvan ▁sebe ▁od_bs ▁bij es a .
▁Poz vao ▁sam_bs ▁ih ▁da_bs ▁u_bs đu .
▁- Ma ma_bs ▁pravi ▁s_bs ja_bs jan ▁ro lat ▁od_bs ▁mesa .
▁Ima o ▁je_bs ▁puno ▁sreć e .
▁- Bo že_bs !
▁Ne_bs zna m , ▁oko ▁30 ▁ki lom etara ▁od_bs ▁Gun nis ona .
▁Ne_bs ▁" ka_bs o ", ▁je_bs su .
▁I_bs ▁vi ▁bi_bs ▁trebali , ▁ad mira le_bs .
▁- ▁Oni ▁su_bs ▁ovo_bs ▁posla li_bs ?
▁- I ▁vam_bs a .
▁On ▁svet lu ca_bs .
▁Pa_bs ž nja !
▁Moj i ▁ciljevi ?
▁Gu bi_bs ci_bs ▁u_bs ▁ ratu .
▁- ▁Za_bs prav o ▁ne_bs ▁znam_bs . ▁Vidi te_bs , ▁njen ▁ugovor ▁ist ice ▁sto ▁zna ci_bs ▁sto ▁zna ci_bs ▁da_bs ▁ce ▁se_bs ▁izgubi ti_bs ▁svi ▁njen i ▁podaci ...
▁Pa_bs ▁onda ▁pret post avljam ▁da_bs ▁je_bs ▁dobro ▁što_bs ▁sam_bs ▁na_bs šla ▁ru pu .
▁E j , ▁je_bs ba či_bs .
▁Dobro . ▁Ide š ▁li_bs ▁sada ▁doma ?
▁Vidi o ▁sam_bs ▁da_bs ▁u_bs da_bs raš ▁u_bs ▁vrata .
▁Po_bs tro ša čke ▁cijene ▁su_bs ▁u_bs ▁april u ▁u_bs ▁odnosu ▁na_bs ▁april ▁2010. ▁por as le_bs ▁za_bs ▁bli zu ▁11 % , ▁a_bs ▁pre_bs hra mbe ni_bs ▁artikli ▁poput ▁h lje ba ▁i_bs ▁ži ta_bs rica ▁posebno ▁su_bs ▁po_bs go đen i .
▁Samo ▁sto jim ▁i_bs ▁gleda m ▁u_bs ▁sve_bs mir ... ▁i_bs ▁pi tam ▁se_bs ▁da_bs ▁li_bs ▁će_bs ▁se_bs ▁vratiti .
▁Ovo ▁je_bs ▁s_bs ram ot no_bs .
▁Ne_bs , ▁ali_bs ▁se_bs ▁može ▁reći ▁da_bs ▁smo_bs ▁vrlo ▁sigur ni_bs ▁u_bs ▁to_bs .
▁Jedno ▁de_bs te_bs ▁manje , ▁za_bs ce_bs to ▁od_bs ▁mor ona .
▁Možda ▁ho će_bs .
▁Ovo ▁je_bs ▁o_bs ti_bs šlo ▁pred a leko .
▁Za_bs h val an_bs ▁sam_bs ▁sto ▁ce mo_bs ▁mo ci_bs ▁ovo_bs ▁gleda ti_bs ▁za_bs ▁25 ▁godina .
▁I_bs sa ac ▁do_bs vodi ▁ne_bs ku_bs ▁djevoj ku_bs ?
▁Samo ▁sa_bs če_bs kaj , ▁na_bs ▁trenutak .
▁Na_bs šao ▁sam_bs ▁vaše g ▁čovjek a .
▁Nije ▁le pa ▁kao_bs ▁ti_bs .
▁Da_bs ▁mi_bs ▁pomogne ▁da_bs ▁pri_bs kup im_bs ▁zrak e ▁ žu to g ▁sun ca_bs ▁dok ▁budem ▁le tio ▁ka ▁tamo .
▁Kad ▁jednom ▁u_bs đe te_bs ▁u_bs ▁njegov u ▁obitelj , ▁on_bs ▁vas_bs ▁pos je_bs du je_bs .
▁Tako ▁si_bs ▁visok , ▁tako_bs ▁ve lik , ▁ali_bs ▁imaš ▁malo ▁s_bs r ce_bs .
▁U_bs ▁li_bs ft u , ▁u_bs ▁ho lu .
▁Mislim ▁da_bs ▁je_bs ▁tvoj ▁brat ▁po_bs ma_bs lo_bs ▁ ljub om_bs oran ▁na_bs ▁tebe .
▁Z bil ja_bs ▁do_bs bru ▁do_bs đu .
▁Misliš ▁da_bs ▁je_bs ▁Vo ken ▁bio_bs ▁negativ ac ?
▁Baba ▁ima_bs ▁problem ▁već ▁godina ma_bs .
▁Ne_bs do pusti ▁ovoj ▁va tri ▁da_bs ▁se_bs ▁za_bs pali , ▁Gu ru !
▁Marie tta ?
▁- ▁Gil li_bs an_bs , ▁bilo_bs ▁mi_bs ▁je_bs ▁drag o .
▁- ▁" T ed , ▁ne_bs ▁mogu_bs ▁da_bs ▁mir no_bs ▁sto jim ▁i_bs ..."
▁Tako ▁možemo ▁is_bs cr tati ▁izvor ▁boli ▁i_bs ▁onda ▁je_bs ▁pro_bs živ lja vati , ▁znaš .
▁Pri ca_bs li_bs ▁ste_bs ▁s_bs ▁g . ▁La mping to nom ?
▁Mislim , ▁da_bs ▁li_bs ▁to_bs ▁za_bs ista ▁toliko ▁važno , ▁to_bs ▁je_bs ▁samo_bs ▁seks .
▁Pro vali o ▁mi_bs ▁je_bs ▁u_bs ▁ku_bs ću_bs .
▁Jedno m ▁sam_bs ▁mu ▁to_bs ▁spo menu o .
▁Ja_bs ▁ne_bs ▁znam_bs .
▁Još ▁malo !
▁- ▁Što ▁su_bs ▁re kli ?
▁D ž ung la_bs .
▁Za_bs ljub is ▁se_bs ▁jer ▁misli s ▁da_bs ▁ako_bs ▁ga_bs ▁upozna s ▁bi_bs ce_bs ▁drug aciji .
▁O_bs že_bs nice š ▁moju ▁k ci_bs . ▁Ko ▁kaže ▁da_bs ▁želim ▁da_bs ▁se_bs ▁že nim_bs ?
▁Bilo ▁je_bs ▁mnogo ▁svet a .
▁Kao ▁bil j ku_bs . ▁Ili ▁c rte ž ▁plan ine .
▁Gdje ▁su_bs ▁ti_bs ▁k lju ce_bs vi_bs ?
▁Gde ▁je_bs ▁Santa ▁Maria ▁del ▁Po_bs polo , ▁prvi ▁ol tar ▁na_bs uke ?
▁Ne_bs ▁smije š ▁ni_bs kom ▁priča ti_bs ▁o_bs ▁ovom .
▁Kako ▁si_bs ?
▁Na_bs red nice , ▁kas ni_bs mo_bs .
▁Ne_bs ce_bs ▁ti_bs ▁pri_bs pas ti_bs ▁muka ▁u_bs ▁moj_bs im_bs ▁kol ima_bs ?
▁Kako ▁se_bs ▁vi ▁zove te_bs ?
▁Misliš ▁da_bs ▁bih ▁dva put ▁po_bs nov ila ▁ istu ▁po_bs gre š ku_bs ?
▁- ▁Još ▁ka fe , ▁profesor e ?
▁- ▁Idemo . ▁Ovo ▁mesto ▁je_bs ▁je_bs zi_bs vo .
▁Možda ▁Mi cu_bs bi_bs ši .
▁Za_bs kas ni_bs ćeš ... ▁na_bs ▁svoj ▁reci tal !
▁On ▁ga_bs ▁ne_bs ▁za_bs služ uje !
▁Možda ▁bi_bs ▁mama ▁trebala ▁da_bs ▁po_bs čne ▁da_bs ▁pi še ▁de_bs č je_bs ▁knjig e .
▁Reci ▁mu ▁da_bs ▁ću_bs ▁mu ▁se_bs ▁ja_bs viti .
▁I_bs ▁na_bs red nik ▁Wall ace . ▁Ona ▁će_bs ▁biti_bs ▁tvoj ▁partner ▁za_bs ▁obu ku_bs .
▁Da_bs ▁li_bs ▁bi_bs ste ▁i_bs kad ▁mogli ▁od_bs usta ti_bs ▁od_bs ▁El lie ?
▁Možda ▁bi_bs ▁ti_bs ▁mogao ▁pokuša ti_bs ▁vodi ti_bs ? ▁!
▁Em ire , ▁John ▁Anthony ▁ovdje .
▁- Ne ▁pozna jem ▁osta le_bs .
▁Nama ▁plati ▁sit ni_bs š , ▁a_bs ▁se_bs bi_bs ▁po_bs ud vo stru či_bs ▁des et ▁mili ju_bs na_bs ?
▁- Ho će_bs te_bs ▁li_bs ▁iza ći_bs ▁sa_bs ▁mnom ▁na_bs ▁večer u ?
▁- ▁Ovo ▁su_bs ▁ko la_bs ▁sa_bs ▁vaš ara ▁koja ▁sam_bs ▁ku_bs pio ▁preko ▁e Ba ya .
▁Š te_bs de o ▁sam_bs ▁za_bs ▁prav ni_bs ▁fa kul tet .
▁- O d ▁Li se ▁Don ovan .
▁C inte ▁se_bs ▁kao_bs ▁do_bs bri .
▁U_bs ▁ha os u ▁sam_bs .
▁Ve c ▁sam_bs ▁se_bs ▁pre_bs z noj ila .
▁Kako ▁misli s ?
▁Hoćeš ▁da_bs ▁znaš ▁šta_bs ▁to_bs ▁znači ?
▁Tako ▁ona ▁kaže ▁" zdrav o ".
▁Ja_bs , ▁kao_bs , ▁kao_bs ▁da_bs ▁se_bs ▁malo ▁tres em ▁sada .
▁Samo ...
▁U_bs ▁među vre menu , ▁nemoj te_bs ▁se_bs ▁bri nuti .
▁A_bs ▁ja_bs ▁mogu_bs ▁pop rica ti_bs ▁sa_bs ▁su_bs cem .
▁- Ne ▁vjer ujem ▁u_bs ▁to_bs .
▁Sad ▁mi_bs ▁treba_bs ▁od_bs mor .
▁Z vat ▁ću_bs ▁polici ju_bs .
▁Slušaj , ▁ne_bs ▁znam_bs ▁kako_bs ▁su_bs ▁se_bs ▁stvari ▁obavlja le_bs ▁prije ▁no ▁što_bs ▁sam_bs ▁stig ao , ▁a_bs ▁ja_bs ▁volim ▁misli ti_bs ▁o_bs ▁se_bs bi_bs ▁kao_bs ▁o_bs ▁bez bri ž noj ▁osob i .
▁Č uv ajte ▁Ber teli .
▁" Po sta lo_bs ▁je_bs ▁ne_bs verovatn o ▁jasno ▁da_bs ▁je_bs ▁naš a ▁tehnologij a ▁nad vlad ala ▁na_bs šu ▁ljudsk ost ."
▁Možete ▁li_bs ▁na_bs ▁trenutak ▁presta ti_bs ▁biti_bs ▁ru lja ?
▁- Po ki dali ▁su_bs ▁mi_bs ▁ta š nu_bs ...
▁- Ni sam ▁homo fo b .
▁Tko ▁bi_bs ▁po_bs misli o ▁da_bs ▁bi_bs ▁običn a ▁cur a ▁poput ▁mene
▁- ▁Šta_bs ? ▁Ne_bs ▁vjer uješ ▁nam ?
▁Još ▁se_bs ▁se_bs ća_bs m ▁tog ▁dana ▁kad_bs ▁sam_bs ▁ga_bs ▁upozna o , ▁Na_bs dia .
▁L ov ci_bs ▁ne_bs ▁da_bs ju_bs ▁tako_bs ▁dobre ▁nap oj nice .
▁Mora o ▁sam_bs ▁pomoći ▁prijatelj u ▁poslije ▁posla .
▁Za_bs ba vno ▁mi_bs ▁je_bs . ▁Ovo ▁je_bs ▁najbolj i ▁su_bs dar ▁na_bs ▁kom ▁sam_bs ▁bio_bs ▁pos le_bs ▁dugo ▁vremena .
▁Hej , ▁prvo ▁šo t , ▁pitanja ▁pos le_bs .
▁Radi ▁za_bs ▁škol u ▁u_bs ▁trgov inama ▁bli zu ▁one ▁auto ▁trgov ine .
▁Samo ▁vrlo ▁ tvrd .
▁Treba ▁da_bs ▁pravi mo_bs ▁ko la_bs či_bs će_bs .
▁Um ro ▁je_bs ▁u_bs ▁font ani ▁od_bs ▁pada .
▁Iz dr za vati ▁se_bs ▁mogu_bs ▁sama . ▁- V jer ujem .
▁Zašto ?
▁Ali_bs ▁glavni ▁razlog ▁zbog ▁koje g ▁te_bs ▁volim , ▁Marshall e ▁Eric ks en , ▁je_bs ▁što_bs ▁me_bs ▁čini s ▁sreć nom .
▁Tek ▁sam_bs ▁za_bs gre ba o ▁površin u , ▁ali_bs ▁bi_bs ▁mi_bs ▁bilo_bs ▁mnogo ▁la k še ▁kad_bs ▁bi_bs ste ▁mi_bs ▁dozvoli li_bs ▁da_bs ▁koristi m ...
▁I_bs ▁malo ▁zelen e ▁ja_bs bu ke .
▁- ▁Onda ▁ćeš ▁imati ▁temu ▁za_bs ▁slik anje .
▁Idemo .
▁Nakon ▁što_bs ▁se_bs ▁s_bs miri š .
▁Post oji ▁operacij a ▁za_bs ▁to_bs , ▁znaš ?
▁Iz vin ja_bs vamo ▁se_bs !
▁Su m nja j ▁na_bs ▁svakog .
▁Una jm imo ▁paz itelj icu ▁za_bs ▁njega . ▁Znaš ▁koliko ▁je_bs ▁to_bs ▁skup o ?
▁Ako ▁želi te_bs ▁da_bs ▁osta ne_bs te_bs ▁rob ovi ▁banka ra_bs ▁i_bs ▁da_bs ▁pla ća_bs te_bs ▁ce h ▁rob o vanju , ▁osta vite ▁im ▁da_bs ▁šta_bs mpa ju_bs ▁novac ▁i_bs ▁da_bs ▁kontroli šu ▁kredit e "
▁- Ne ▁zanima ▁me_bs .
▁Idemo ▁da_bs ▁se_bs ▁pre_bs sel imo ▁u_bs ▁Itali ju_bs !
▁Nije ▁važno , ▁T . ▁C .
▁Možda ▁ti_bs ▁pri_bs sluš ku_bs ju_bs ▁telefon , To ny .
▁- N je_bs gov ▁prijatelj ▁u_bs ▁pic u ▁je_bs ▁misli o ▁da_bs ▁je_bs ▁to_bs ▁cu d no_bs .
▁Pogledaj te_bs ▁je_bs .
▁- ▁Jesi ▁me_bs ▁čuo ?
▁Nema ▁der ne_bs ka_bs ▁do_bs ▁man ding o ▁der ne_bs ka_bs .
▁- ▁A_bs ▁hal u cin acije ?
▁Kako ▁se_bs ▁zove š ?
▁I_bs di_bs ▁kasnije .
▁H t jela ▁je_bs ▁da_bs ▁njen ▁sin ▁vlada , ▁tvoj ▁po_bs lub rat .
▁Gdje ▁si_bs ▁bio_bs ▁prije ▁dva ▁ tje d na_bs ?
▁Kada ▁si_bs ▁bio_bs ▁s_bs ▁Ali_bs son , ▁ko ▁je_bs ▁rekao ▁" V o lim ▁te_bs " ▁prvi ?
▁Ali_bs ▁o_bs ▁pos lu ▁na_bs ▁razgovara m ▁na_bs ▁ja_bs v nim_bs ▁mje sti_bs ma_bs .
▁Le po ▁je_bs ▁vide ti_bs ▁te_bs ▁opet , ce_bs lia .
▁Ne_bs će_bs ▁im ▁se_bs ▁svi d jeti .
▁Do_bs k ▁je_bs ▁u_bs ▁redu , ▁v ješ_bs ti_bs ▁hiru rg ▁i_bs ▁dobar ▁čovjek .
▁Onda ▁bolje ▁da_bs ▁ne_bs ▁vidi s .
▁U_bs ▁redu . Ne ma_bs ▁potrebe ▁da_bs ▁se_bs ▁der eš
▁Tra ži la_bs ▁si_bs ▁nešto ▁što_bs ▁nikada ▁ne_bs ▁možeš ▁na_bs ći_bs .
▁Idemo . ▁- ▁Ne_bs ▁za_bs služ uješ ▁to_bs ▁dije te_bs ▁koje ▁nos iš .
▁To_bs ▁neće ▁mo ći_bs .
▁Si sa o ▁bih ▁ti_bs ▁krv . ▁- S isa š ▁moje ▁šta_bs ?
▁Zašto ▁ste_bs ▁to_bs ▁misli li_bs ?
▁- Mo ž da_bs ▁pob eg nu_bs ▁zajedno ▁i_bs ▁ne_bs ▁vra te_bs ▁se_bs .
▁K UP IO ▁S_bs AM ▁O_bs VO ▁M JE S TO ▁NA KON ▁Š TO ▁ SI ▁ UM RL A .
▁Do_bs la_bs ze ▁nam ▁od_bs ▁me_bs ha nica ra_bs , ▁ben zin skih ▁c rp ki .
▁Treba m ▁se_bs ▁ok re_bs nuti ▁na_bs ▁drug u ▁stran u ▁ili ... ?
▁Ne_bs ▁sme ta_bs ▁mi_bs ▁da_bs ▁kup im_bs ▁2 -3 ▁knjig e ▁za_bs ▁ovo_bs .
▁Raz log ▁zbog ▁ko ga ▁sam_bs ▁ pita o ▁je_bs ▁jer ▁ste_bs ▁tr lja li_bs ▁nos ▁kao_bs ...
▁- ▁Okej , ▁se_bs ća_bs m ▁se_bs , ▁ja_bs ...
▁Ali_bs ▁da_bs !
▁Maj k , ▁u_bs đi .
▁Pogledaj ▁mi_bs ▁uniform u ▁... ▁misliš ▁da_bs ▁sam_bs ▁jedan ▁iz_bs ▁banda ▁Vil lage ▁People ?
▁Kit , ▁u_bs đi !
▁Drago ▁mi_bs ▁je_bs ▁da_bs ▁vidim ▁da_bs ▁ima_bs ▁novi h ▁kandidat a ▁za_bs inter es iranih ▁za_bs ▁ple meni ti_bs ▁sport ▁- ▁r vanje .
▁- K ren ite .
▁Nikad ▁ga_bs ▁neces ▁u_bs hvat iti_bs !
▁Samo ▁ima_bs ▁nekoliko ▁riječ i ▁koje ▁ne_bs ▁razum i jem .
▁- ▁Pos la_bs tim ▁od_bs ▁kralj a .
▁Ali_bs ▁to_bs ▁ga_bs ▁ne_bs ▁za_bs u stavlja .
▁Da_bs ▁sam_bs ▁na_bs ▁tv om_bs ▁me_bs stu , ▁dig ao ▁bih ▁ru ke ▁od_bs ▁ovog a .
▁- Č e kaj ▁malo . ▁Zna o ▁si_bs ▁da_bs ▁imaš ▁virus ?
▁Ona ▁je_bs ▁star ica ▁koje ▁je_bs ▁bila ▁dobra ▁prema ▁meni .
▁Mr t vi_bs ▁su_bs .
▁Ne_bs ▁znam_bs ▁kako_bs ▁se_bs ▁zove .
▁- ▁Šta_bs ?
▁Vidi o ▁sam_bs ▁tvoj u ▁cur icu ▁par ▁puta ▁s_bs ▁tim .
▁Zdravo , ▁Pe tsi .
▁Ako ▁razvi je_bs mo_bs ▁no vu ▁tehnologij u , ▁to_bs ▁nam ▁da_bs je_bs ▁pred nost .
▁Ob ično ▁star i jih , ▁bo gati h .
▁Pr vo ▁di ši , ▁onda ▁puc aj .
▁Super ▁smo_bs ▁se_bs ▁prove li_bs .
▁Šta_bs ▁tebe ▁briga ▁šta_bs ▁ja_bs ▁želim ?
▁No ći_bs ma_bs ▁i_bs ▁noć ima_bs ▁sam_bs ▁te_bs ▁čeka o ▁da_bs ▁do_bs đe š ▁i_bs ▁priča š ▁sa_bs ▁mnom ▁sa_bs ▁svojim ▁ću_bs re_bs ći_bs m ▁glas om_bs ...
▁- E pi fa ni_bs ovi ▁ljudi ▁tra že_bs ▁je_bs ▁pos vu da_bs .
▁- ▁Bas ▁ste_bs ta_bs . ▁U_bs kra o ▁je_bs ▁moj_bs ▁pe cat ▁od_bs ▁ci sto g ▁zlat a .
▁Prim jer ice , ▁moja ▁uniform a . .
▁Ovo ▁ne_bs ▁možeš ▁da_bs ▁ku_bs piš ▁u_bs ▁A_bs meri ci_bs .
▁Hajde , ▁sad , ▁nu di_bs ▁li_bs ▁ko ▁dva ▁cent a ? ▁- ▁Iza ▁tebe !
▁Nikad ▁ne_bs ▁priča š ▁o_bs ▁moj_bs oj ▁u_bs lo_bs zi_bs . ▁Kakv i ▁su_bs ▁s_bs nim_bs ci_bs ▁sa_bs ▁pro_bs be ?
▁Svi ▁treba_bs ▁da_bs ▁u_bs radi te_bs ▁ovo_bs ▁kako_bs ▁treba_bs .
▁Do_bs govori li_bs ▁smo_bs ▁se_bs .
▁Nemoj ▁se_bs ▁glup irati .
▁Ne_bs ▁no si ▁ništa ▁ cr ven o !
▁I_bs ▁na_bs t jera lo_bs ▁me_bs ▁da_bs ▁raz misli m ▁o_bs ▁život u . ▁Ho ću_bs ▁najbolje ▁za_bs ▁sebe .
▁- ▁Je_bs s mo_bs ▁li_bs ▁spremn i ?
▁Ti_bs ▁nisi ▁u_bs bio ▁tu ▁djevoj ku_bs .
▁Za_bs tim ▁ćemo ▁za_bs tvor iti_bs ▁vrata ▁i_bs ▁u_bs bac iti_bs ▁zrak .
▁Ne_bs ▁mogu_bs ▁se_bs ▁sj etiti ▁ne_bs če_bs g ▁bit nog ...
▁Da_bs ▁nije_bs ▁bio_bs ▁na_bs ▁operacion om_bs ▁stol u ...
▁Ve ć ▁smo_bs ▁sve_bs ▁pre_bs traži li_bs .
▁Dobro , ▁idemo ▁u_bs ▁nazad .
▁- Po z uri , Te mi !
▁Šta_bs ▁je_bs ▁ovde , ▁šta_bs ▁si_bs ▁to_bs ▁pila ?
▁S_bs me_bs š ten ▁je_bs ▁u_bs ▁Japan u .
▁I_bs ▁ne_bs ▁možete ▁da_bs ▁name sti_bs te_bs ▁da_bs ▁me_bs ▁uh ap se .
▁Ni ▁s_bs ▁kim , ▁dušo .
▁- ▁Mogu ▁li_bs ▁ti_bs ▁dati ▁savjet ? ▁Naravno .
▁Što ▁nam ▁to_bs ▁vaš a ▁vlada ▁ne_bs ▁govori ?
▁pop ili_bs ▁ste_bs ▁4 0,000 ▁li_bs tara ▁vode .
▁Živ jeli ▁u_bs ▁i_bs stoj ▁če tvrt i ▁u_bs ▁Bag dad .
▁- ▁Radi m ▁na_bs ▁tome .
▁Naravno ▁da_bs ▁sam_bs ▁sko cio ▁da_bs ▁je_bs ▁spasi m .
▁- To ▁je_bs ▁najbolje ▁s_bs ranje ▁koje ▁si_bs ▁i_bs kad ▁proba o .
▁- ▁Na_bs če_bs l nik !
▁I_bs ▁za_bs bora van .
▁Gle da_bs mo_bs ▁li_bs ▁dokaz e ▁" ono stra nog ", ▁a_bs ▁ima_bs ▁ih ▁dosta ▁is_bs ku_bs stva ▁bli ske ▁smrti , ▁de_bs ca_bs ▁koja ▁su_bs ▁rod jena ▁sa_bs ▁se_bs ca_bs njem ▁te_bs taka , ▁s_bs trice va_bs , ▁de_bs da_bs , ▁koji_bs ▁su_bs ▁da_bs vno ▁umrl i ▁pre_bs ▁njihovo g ▁rod jen ja_bs ...
▁Gospod ine , ▁misli ▁pose g nuti ▁za_bs ▁vaš im_bs ▁pištolj em .
▁- Pri ko_bs lica ▁je_bs ▁za_bs ▁stat u u .
▁- Ma kni te_bs ▁se_bs ▁s_bs ▁njega !
▁Sve ▁za_bs ▁po_bs ne_bs ti_bs ...
▁- ▁Imamo ▁plan , ▁ali_bs ▁će_bs ▁nam ▁treba_bs ti_bs ▁love .
▁Bir ko_bs fe !
▁Jer ▁mislim ▁da_bs ▁bi_bs ▁to_bs ▁bilo_bs ...
▁Nisi ▁čak ▁ni_bs ▁pozna vao ▁kap etan a ▁Bre j s gir dla .
▁Du š o , ▁je_bs li_bs ▁sve_bs ▁u_bs ▁redu ?
▁Vi ▁? ▁est ▁u_bs ▁lag de ▁u_bs ? ▁et u , ▁ja_bs ▁ , ▁ali_bs ▁je_bs ▁?
▁I_bs gra ▁ne_bs del je_bs .
▁Kako ▁su_bs ▁Ryan ▁i_bs ▁Es posit o ?
▁V rlo ▁dobro , ▁Cass ie .
▁Pa_bs zi_bs te_bs ▁na_bs ▁Si mens a .
▁Sigur nost ▁u_bs ▁dana š njem ▁svijet u ▁ne_bs ▁može ▁se_bs ▁post i ći_bs ▁samo_bs ▁za_bs šti tom ▁gran ica ▁v last ite ▁države , ▁izjavi la_bs ▁je_bs ▁držav na_bs ▁sekret ar ka_bs ▁pri_bs ▁mini star stvu ▁od_bs bra ne_bs ▁Tan ja_bs ▁M išče vi_bs ć .
▁pre_bs tvor i ▁< f rom > ▁[ < norm \ - form > ]
▁Stan i .
▁Over ki ll ▁tako_bs đe ▁može ▁da_bs ▁po_bs ka_bs že_bs ▁svoju ▁ne_bs isku stvo .
▁Naravno . Ka s nije .
▁- ▁La ga o ▁si_bs ▁mi_bs !
▁Hoćeš ▁na_bs ▁kole d ž ?
▁- P e ter , ▁želim ▁da_bs ▁neko ga ▁upozna š .
▁Uvijek ▁se_bs ▁pret po stavlja lo_bs ▁da_bs ▁ce ▁Stephen ▁ ici ▁na_bs ▁O_bs x ford .
▁Do_bs šli ▁smo_bs ... ▁jako ▁da_bs leko .
▁Ali_bs ▁jedna ▁slučaj nost , ▁nije_bs ▁ znak ▁za_bs ▁alarm .
▁Da_bs ▁pogleda mo_bs ▁ponovo ... ▁Evo ▁So krat a , ▁u_bs bac uje ▁gla vom .
▁Svi ▁su_bs ▁živi .
▁Ali_bs ▁čeka ti_bs ▁mora te_bs ▁van i , ▁molim ▁vas_bs .
▁Ne_bs ki ▁od_bs ▁tih ▁broj eva ▁se_bs ▁po_bs nav lja ju_bs . ▁- ▁Molim ? ▁Ne_bs .
▁Ja_bs ▁sam_bs ▁do_bs slov no_bs ▁Pre kli njem ▁te_bs .
▁- ▁Sve ▁su_bs ▁maj ke ▁do_bs š le_bs ▁sem ▁moje .
▁- ▁Jeste ▁li_bs ▁je_bs ▁zato ▁s_bs tvor ili_bs ?
▁Var ao ▁je_bs !
▁" S r ce_bs ▁koje ▁voli ▁ka ze ▁da_bs ▁je_bs ▁ce o ▁svet ▁lu d "
▁Na_bs ▁žal ost , ▁u_bs sled ▁ne_bs mara ▁pri_bs ▁od_bs la_bs gan ju_bs ▁od_bs vrat nog ▁toks ično g ▁nu s ▁proizvoda , ▁jedna ▁dobra ▁Tro ma_bs vil ska ▁ve ver ica ▁mut ira la_bs ▁je_bs ▁u_bs ▁og rom nu_bs ▁od_bs vrat nu_bs ▁sm rd ljiv u , ▁up i šanu ▁čud o viš nu_bs ▁ve ver icu .
▁Ne_bs ▁je_bs bi_bs ▁u_bs če_bs nice . ▁Ne_bs ▁je_bs bi_bs ▁u_bs či_bs telj ice .
▁Po_bs šal ju_bs ▁te_bs ▁na_bs ▁od_bs vik avanje ▁a_bs ▁ja_bs ▁se_bs ▁tamo ▁ne_bs ▁vra ča m .
▁Po_bs š to ▁sam_bs ▁vidi o ▁ka kva ▁ti_bs ▁je_bs ▁pla ća_bs , ▁ vjerojatn o ▁ne_bs ▁bi_bs ▁trebao .
▁- ▁Ja_bs ▁sam_bs ▁u_bs ▁ cr ven om_bs ▁ti_bs mu !
▁Sa če_bs kaj .
▁Ljub av nik ▁sa_bs ▁os lab ljeni m ▁še raf om_bs ?
▁Po_bs tom ▁je_bs ▁u_bs isti nu_bs ▁po_bs vrat ište ▁njihovo ▁d že_bs hi mu .
▁Nema te_bs ▁resursa , ▁nema te_bs ▁obra di_bs le_bs ▁zemlje , ▁nema te_bs ▁ri be , ▁da_bs kle ▁nema te_bs ▁ništa .
▁To_bs ▁ne_bs ce_bs ▁presta ti_bs , ▁ne_bs ▁bez ▁vremena ▁i_bs ▁tre t mana .
▁Jason ▁G . ▁je_bs ▁po_bs be dio ▁na_bs ▁Itali jan skom ▁id olu .
▁Ti_bs ▁si_bs ▁već ▁mrtav .
▁- Ne ▁svi đa ▁joj ▁se_bs !
▁Zar ▁ne_bs ▁znaš
▁Nisam ▁stig ao ▁ni_bs ▁vozi ti_bs .
▁Dobro , ▁samo_bs ▁jedna ▁stvar .
▁Želim ▁ga_bs ▁na_bs trag .
▁- ▁Pro meni o ▁sam_bs ▁postel jin u .
▁To_bs ▁je_bs ▁pa_bs nda , ▁ser .
▁" Ka d ▁si_bs ▁po_bs če_bs la_bs ▁radi ti_bs ▁ovdje ?"
▁" Ne ma_bs ▁tu ▁ništa ▁loše ▁i_bs ▁ne_bs ▁da_bs j ▁da_bs ▁ka žu ▁da_bs ▁si_bs ▁druk či_bs ji_bs "?
▁Da_bs ▁li_bs ▁vas_bs ▁je_bs ▁u_bs bed ila ▁da_bs ▁se_bs ▁use lite ▁ponovo ?
▁Sam ▁si_bs ▁to_bs ▁traži o .
▁I_bs ▁Mi ▁mu ▁na_bs ▁ploč ama ▁na_bs pis as mo_bs ▁po_bs uku ▁za_bs ▁sve_bs , ▁i_bs ▁ob jašnj en je_bs ▁za_bs ▁sva šta . ▁" Pri mi ▁ih ▁svoj ski , ▁a_bs ▁narod u ▁svo me_bs ▁zapo vije di_bs ▁da_bs ▁se_bs ▁pri_bs država ▁on_bs oga ▁što_bs ▁je_bs ▁u_bs ▁ njima ▁ lje p še !"
▁Vrati o ▁se_bs ▁her oj ▁- ▁os va_bs ja_bs č .
▁Še rif e , ▁prim je_bs će_bs n ▁je_bs .
▁Ili ▁po_bs či_bs nje ▁kao_bs ▁počet nik ▁ili ▁kao_bs ▁za_bs me_bs nik ▁še fa .
▁Bobby , ▁želiš ▁li_bs ▁vidjeti ▁šta_bs ▁sam_bs ▁ti_bs ▁do_bs ni_bs jela ?
▁Nema ▁potrebe ▁da_bs ▁izi gra vas ▁socijaln og ▁rad nika .
▁Evo ▁moje ▁vizit ke ▁ako_bs ▁se_bs ▁s_bs jeti te_bs ▁ne_bs če_bs ga .
▁Ne_bs ▁osjeća š ▁bol .
▁Par ▁iz_bs ▁Vir gi nije ?
▁Maj ore , ▁šta_bs ▁to_bs ▁radi te_bs ?
▁I_bs ▁to_bs ▁mi_bs ▁je_bs ▁neki ▁rod jak .
▁Zdravo , ▁ stvo ren je_bs ▁sa_bs ▁drugog ▁svet a .
▁Ve ć ▁je_bs ▁video ▁mnogo ▁šta_bs .
▁Li je_bs po ▁je_bs , ▁zar ▁ne_bs ?
▁Už i vaj ▁u_bs ▁u_bs bila čko m ▁po_bs ho du .
▁Znam ▁da_bs ▁ti_bs ▁sve_bs ▁analiz i raš ▁svaki h ▁des et ▁minuta . ▁U_bs zor ke , ▁odnose , ▁indeks e , ▁cele ▁ma pe ▁informacija .
▁H t jela ▁sam_bs ▁da_bs ▁pogleda š ▁moj_bs ▁sta s .
▁Ali_bs ▁treba_bs ju_bs ...
▁- ▁Ovo ▁je_bs ▁nov ▁dan .
▁We n dy ▁ne_bs ▁može ▁ništa ▁dokaz ati .
▁Oni ▁oče ku_bs ju_bs ▁tvoj ▁poziv . ▁Pa_bs ▁iz_bs voli .
▁- ▁Misliš ▁da_bs ▁želim ▁um rije ti_bs ?
▁Što ▁ako_bs ▁opet ▁završi š ▁tamo ?
▁Da_bs li_bs ▁pozna ješ_bs ▁tog ▁um et nika ?
▁Bez ▁tebe , ▁oni ▁ne_bs ▁bi_bs ▁mogli ▁sam_bs i ▁da_bs ▁re še ▁u_bs bi_bs stvo ▁tvoje ▁por o dice .
▁U_bs gr izao ▁si_bs ▁ga_bs ?
▁Je_bs li_bs ▁su_bs ▁isto ▁što_bs ▁i_bs ▁mi_bs ▁i_bs ▁niko ▁više_bs ▁se_bs ▁nije_bs ▁raz boli o .
▁Ali_bs ▁oni ▁su_bs ▁ljudi .
▁Na_bs lazi mo_bs ▁ta jan st veni ▁Z lat ni_bs ▁ ključ ▁koji_bs ▁ot ključ ava ▁evolu ci_bs jske ▁si_bs le_bs ▁pri_bs ro de .
▁Ne_bs ▁kažem o ▁da_bs ▁Bog ▁bla go slov i ▁Amerik u , ▁već ▁pro_bs klet a ▁da_bs ▁je_bs ▁Amerika ...
▁- ▁Una tra ške , ▁Al !
▁To_bs ▁nije_bs ▁a_bs me_bs rick i ▁narod .
▁Bu di_bs ▁dobar ▁i_bs ▁dones i ▁ma mi ▁sok .
▁Pusti ću_bs ▁vas_bs ▁da_bs ▁na_bs stavi te_bs .
▁" Re pu blik a ▁Sr p ska ▁mora ▁u_bs ▁ cje lini ▁pošt i vati ▁De j ton ski ▁mi_bs rov ni_bs ▁sporazum ▁i_bs ▁ne_bs ▁smije ▁o_bs spor a vati ▁rad nje ▁poduzet e ▁na_bs ▁osnov u ▁De j tona ▁i_bs ▁rezo lu cija ▁Vijeća ▁sigurnosti ▁UN - a , " ▁kaže ▁se_bs ▁u_bs ▁In zko vom ▁sa_bs op će_bs nju ▁od_bs ▁u_bs tor ka_bs .
▁Kad ▁budu ▁ba čeni ▁u_bs ▁njega , ▁ću_bs t ▁će_bs ▁ga_bs , ▁h rop ta_bs će_bs ▁i_bs ▁on_bs ▁će_bs ▁v riti .
▁Kaž e ▁da_bs ▁je_bs ▁on_bs ▁" ljub av ".
▁Zna s ▁sta ▁je_bs ▁meni ▁te_bs sko ▁za_bs ▁povjer ovati ?
▁tre ning ▁Ph y llis ▁mora ▁imati ▁stvarno ▁iz_bs ne_bs mo_bs gli ▁je_bs .
▁- ▁Samo ▁pre_bs ter uje s , ▁to_bs ▁je_bs ▁sve_bs .
▁Do_bs šla ▁sam_bs ▁ovdje ▁sa_bs ▁dvije ▁misli ▁u_bs ▁gla vi_bs .
▁Sad ▁kad_bs ▁to_bs ▁formul iš eš ▁tako_bs ...
▁I_bs ▁niko ▁ti_bs ▁ništa ▁ne_bs ▁može .
▁- ▁Kuva ni_bs ▁maka ron i !
▁Od ▁ovog ▁tre nut ka_bs , ▁program ▁G UP ▁je_bs ▁suspend ovan ... ▁do_bs ▁za_bs vrš et ka_bs ▁is_bs trag e .
▁Pa_bs , ▁ljudi ▁imamo ▁veoma ▁te_bs š ku_bs ▁ma čku ▁za_bs ▁z bu nji vanje ▁dana s . ▁Pa_bs , ▁idemo ▁odmah ▁na_bs ▁posao . ▁Dobro .
▁Sad ▁p je_bs vam ▁i_bs ▁pov r će_bs .
▁Za_bs ▁100 ▁godina , ▁još ▁će_bs ▁ga_bs ▁radi ti_bs .
▁Ona ▁pret vara ▁ci jeli ▁izlaz nu_bs ▁snagu ▁na_bs ą em ▁prostor u ▁stanic e ▁u_bs ▁jednom ▁kad_bs ru .
▁Zna o ▁sam_bs ▁da_bs ▁ćeš ▁shvati ti_bs .
▁Prote gni ▁no ge .
▁- ▁Znam ▁to_bs . ▁Ali_bs ▁prije t nja ▁je_bs ▁up u će_bs na_bs ▁federal noj ▁z grad i ▁preko ▁puta .
▁Jesi ▁li_bs ▁čuo ▁o_bs ▁on_bs om_bs ▁golf er u ?
▁Bare m ▁znam_bs o ▁šta_bs ▁se_bs ▁des ilo ▁s_bs ▁Henry jem .
▁Ana ▁čeka ▁u_bs ▁Opera cija ma_bs .
▁Zašto ▁to_bs ▁radiš ?
▁Sko ro ▁mi_bs ▁je_bs ▁ot kin u o ▁gla vu ; ▁mora ▁da_bs ▁je_bs ▁bio_bs ▁baš ▁nez go dan ▁rask id .
▁Nema ▁mnogo ▁vo za ča ▁En gle za ▁u_bs ▁Pra gu .
▁On ▁je_bs ▁bio_bs ▁u_bs ▁ voj s ci_bs .
▁Što ▁je_bs ▁to_bs ▁bilo_bs , ▁Roy , ▁tvoja ▁za_bs d nja ▁bit ka_bs ?
▁Do_bs k ▁pi ješ_bs , ▁taj ▁kami on ▁le vo - -
▁I_bs ▁po_bs ▁prvi ▁put . . ▁Pos le_bs ▁dugo g ▁vremena . .
▁Sada ▁možemo ▁da_bs ▁završi mo_bs ▁naše ▁pro_bs ton ▁anti - pro ton ▁istraživa nje .
▁Hvala ▁vam_bs .
▁Pre viš e ▁je_bs ▁važno .
▁Drž a vne ▁polici je_bs ▁i_bs ▁High way ▁Pat rol ▁su_bs ▁na_bs ▁op re_bs zu ▁kao_bs ▁dobro .
▁U_bs ▁sva kom ▁slučaju , ▁u_bs spor ed ili_bs ▁smo_bs ▁te_bs ▁podatke ▁sa_bs ▁tre nut nim_bs ▁lokacij ama , ▁adres ama ▁i_bs ▁nama ▁dostupni m ▁informacija ma_bs .
▁Ali_bs ▁on_bs ▁je_bs ...
▁Ko ▁ti_bs ▁je_bs ▁na_bs dle zni ?
▁Ima ▁sa_bs obra ća_bs ja_bs , ▁ali_bs ▁je_bs ▁za_bs nim_bs ljivo . To ▁je_bs ▁glavni ▁grad .
▁Daj ▁tu ▁map u .
▁Ima ▁gri pu .
▁Ti_bs ▁si_bs ▁tu ▁gde ▁i_bs ▁je_bs si , ▁ali_bs ▁ja_bs ▁sam_bs ▁ponovo ▁na_bs ▁vr hu .
▁I_bs ▁vidi ▁kako_bs ▁ti_bs ▁is_bs pa o ▁To_bs ▁nije_bs ▁ni_bs sta , st var no_bs
▁- ▁Vidiš , ▁rekao ▁sam_bs ▁ti_bs .
▁Znam ▁da_bs ▁me_bs ▁mr zi_bs š , ▁i_bs ▁znam_bs ▁da_bs ▁te_bs ▁ne_bs ▁kriv im_bs ▁zbog ▁toga .
▁Internet , ▁maj s tore .
▁Des et ▁si_bs ▁joj ▁već ▁s_bs man ji_bs la_bs .
▁Sve ▁dok ▁mis le_bs ▁da_bs ▁te_bs ▁Steve ▁Re m ington ▁pos je_bs du je_bs , ▁siguran ▁si_bs .
▁Samo ▁bes m rt ni_bs .
▁Jedno m ▁da_bs vno , ▁bile ▁su_bs ▁tri ▁mlad e ▁že ne_bs , ▁koje ▁su_bs ▁bile ▁u_bs ▁veliki m ▁problem ima_bs .
▁Živ i ▁na_bs ▁Mal lor ci_bs ▁i_bs ▁radi ▁za_bs ▁š pan jo l sku ▁terorist i čku ▁grup u ▁Ver dad ▁Su prem a .
▁Rekao ▁sam_bs ▁joj ▁da_bs ▁može ▁biti_bs ▁smrt ono s no_bs .
▁O_bs no_bs ▁na_bs ▁pozor nici ▁je_bs ▁moj_bs ▁kli jent . ▁Poz vao ▁me_bs ▁je_bs ▁da_bs ▁do_bs đem . .
▁U_bs ▁ce mu ▁je_bs ▁problem , ▁imamo ▁15 ▁minuta .
▁A_bs ▁ja_bs ▁posta nem ▁smrt an_bs .
▁Ta ▁je_bs ▁pob je_bs da_bs ▁bila ▁mu nje vita ▁i_bs ▁pot pun a .
▁I_bs ▁posto ▁je_bs ▁po_bs ▁Sch ne_bs ide ru , ▁rezultat ▁je_bs ▁ud vo stru cen .
▁Vis e ▁od_bs ▁ra se , ▁to_bs ▁je_bs ▁sir oko ▁otvoren ▁su_bs ko_bs b ▁ide ja_bs ▁materijal iz ovan e ▁če lika .
▁Pa_bs zi_bs ▁se_bs , ▁Ben .
▁Zar ▁te_bs ▁ovdje ▁nisu ▁ni_bs sta ▁nau cili ?
▁Mi ▁ovdje ▁spre ma_bs mo_bs ▁vaše ▁sam_bs rt ni_bs čke ▁ govor e , ▁de_bs čki .
▁- Ko liko ▁sam_bs ▁posledn ji_bs ▁put ▁uradio ?
▁I_bs ▁ govor e : ▁" Z ar ▁ćemo ▁kad_bs ▁budem o ▁kost i ▁i_bs ▁koma di_bs ći_bs , ▁- ▁ho ćemo ▁li_bs ▁u_bs isti nu_bs ▁mi_bs ▁biti_bs ▁po_bs dig nuti ▁( ka_bs o ) ▁ stvo ren je_bs ▁novo ?"
▁- ▁Sa ro , ▁kas nis ▁jedan ▁sat . ▁- ▁Rekla ▁sam_bs ▁da_bs ▁mi_bs ▁je_bs ▁za_bs o .
▁Ah .
▁Kra du ▁ti_bs ▁cara pe .
▁Želim ▁da_bs ▁znam_bs ▁kako_bs ▁će_bs ▁zvuč ati .
▁Sj ajn o .
▁Gdje ▁je_bs ▁on_bs ?
▁- ▁Hajde . ▁Ima ▁li_bs je_bs pe ▁si_bs s ice ?
▁Je_bs beni ▁Joe !
▁Spa si o ▁si_bs ▁me_bs ▁od_bs ▁vil e njaka .
▁Kad ▁do_bs đe te_bs ▁među ▁kamp ▁pri_bs koli ce_bs :
▁- O vo ▁je_bs ▁los e .
▁Izgleda ▁li_bs ▁to_bs ▁tebi ▁kao_bs ▁samo_bs obra na_bs ?
▁Ta da_bs ▁se_bs ▁sve_bs ▁pro_bs meni lo_bs .
▁Ova ▁žena ▁je_bs ▁u_bs ▁više_bs ▁nav rata ▁iz_bs b je_bs gla ... ▁moj_bs i ▁agent i ▁su_bs ▁u_bs ▁pot razi ▁za_bs ▁formul om_bs .
▁- cov jek ▁koji_bs ▁je_bs ▁došao ▁u_bs ▁vezi ▁po_bs ko_bs pa ▁svog ▁o_bs ca_bs .
▁Još ▁de_bs vet ▁sa_bs ti_bs ▁i_bs ▁dolazi , ▁je_bs l ?
▁Tru d na_bs ▁sam_bs , ▁a_bs ▁tebe ▁baš ▁briga !
▁Mo ć ▁da_bs ▁pre_bs pozna m ▁man u , ▁slab ost ,
▁No sim ▁k nji ži cu_bs .
▁I_bs ... ▁nauči ▁nešto ▁odavde .
▁Lu ke , ▁s_bs miri ▁se_bs , ▁znam_bs ▁kako_bs ▁ti_bs ▁je_bs ▁mislim ▁da_bs ▁se_bs ▁možemo ▁dogovor iti_bs .
▁Vi na_bs ▁za_bs ▁le di_bs ▁Sa nsu !
▁A_bs ▁u_bs isti nu_bs , ▁m nog i ▁od_bs ▁ljudi ▁su_bs ▁gr ješ_bs nici .
▁Jesi ▁li_bs ▁ku_bs pio ▁tu ▁gara žu ▁već ?
▁Naravno , ▁oni ▁su_bs ▁sla li_bs ▁son de ▁na_bs ▁sva ku_bs ▁planet u , ▁sem ▁P lu tona .
▁Rekao ▁sam_bs ▁bez ▁sme t nje .
▁Kako ▁je_bs ▁bio_bs ▁ sposob an_bs ▁da_bs ▁se_bs ▁pro_bs bije ▁kroz ▁op sa du , ▁gospodar ▁gran ice ▁bi_bs ▁trebao ▁da_bs ▁razgovara ▁sa_bs ▁njim .
▁Po_bs min ju_bs ▁naše ▁ cip ele . ▁- ▁Šta_bs ▁je_bs ▁s_bs ▁naš im_bs ▁ci pe lama ?
▁Pro klet stvo , ▁zna o ▁sam_bs ▁da_bs ▁možeš !
▁Možete ▁li_bs ▁da_bs ▁mi_bs ▁proč itate ▁ove ▁pod vu čen e ▁nas_bs love ... ▁u_bs ▁od_bs el j ku_bs ▁za_bs ▁Me tro ?
▁Va ? ▁a_bs ▁maj ka_bs ▁vol jela ▁taj ▁po_bs gled .
▁Vrati t ▁će_bs te_bs ▁motor ▁tamo ▁gdje ▁ste_bs ▁ga_bs ▁na_bs šli , ▁i_bs ▁osob no_bs ▁ćeš ▁se_bs ▁is_bs pri ča ti_bs ▁čovjek u ▁od_bs ▁koje g ▁ste_bs ▁u_bs kra li_bs .
▁Ne_bs ▁znam_bs , ▁da_bs ▁je_bs de mo_bs , ▁u_bs ▁bio_bs s kop ...
▁Ob jašnj en je_bs : ▁Za_bs ▁tri jum f ▁Uh uru a , ▁koji_bs ▁su_bs ▁izbor ili_bs ▁crn ci_bs , ▁a_bs ▁o_bs spor avaju ▁bij el ci_bs , ▁u_bs bili ▁su_bs ▁27 ▁bi_bs jela ca_bs ▁i_bs ▁ 5000 ▁crn aca .
▁Slušaj ▁me_bs .
▁D ve_bs ▁hil ja_bs de ▁dolara ▁ne_bs ▁mogu_bs ▁da_bs ▁zaboravi m ▁tako_bs ▁la ko_bs .
▁Sad ▁sam_bs ▁ose tio ▁kako_bs ▁nešto ▁ gori .
▁- Da kle , ▁re šenje ▁je_bs ▁da_bs ▁me_bs ▁una pred ite ▁i_bs ▁is_bs pla ć ujete ▁me_bs ▁više_bs ▁da_bs ▁bih ▁svoje ▁zna nje ▁pruža o ▁budu ć oj ▁gener aciji ▁nau čni ka_bs ?
▁Nova c ▁nije_bs ▁bi_bs tan .
▁Do_bs ▁da_bs ske ▁sam_bs ▁u_bs ▁man ji_bs ni_bs .
▁On ▁uvek ▁izgleda ▁kao_bs ▁da_bs ▁ništa ▁nije_bs ▁uradio .
▁- B ila ▁si_bs ▁mu ▁naj bliž a .
▁" ako ▁napravi m , ▁do_bs ći_bs ▁će_bs " ▁trenutak .
▁Pro šlo ▁je_bs ▁skoro ▁15 ▁godina ▁od_bs ▁11. 09 .
▁Ra šči sti_bs la_bs ▁si_bs ▁svoj ▁rasp o red ▁da_bs ▁bi_bs ▁se_bs ▁ponovo ▁videl a ▁sa_bs ▁tim ▁čud es nim_bs ▁mom kom ▁koji_bs ▁je_bs ▁u_bs bio ▁O_bs sam u ▁Bin ▁La den a , ▁a_bs ▁ti_bs ▁si_bs ▁ga_bs ▁o_bs stavi la_bs ▁us red ▁New ▁York a ?
▁" V id jet ▁će_bs ▁uvijek ▁biti_bs ▁moj_bs ▁z vije z da_bs ." ▁O_bs ▁moj_bs ▁bo ze ... ▁( O BA ▁sme h )
▁Što ▁je_bs ▁s_bs ▁kapsul om_bs ?
▁Gde ▁bi_bs ▁mogli ▁da_bs ▁idemo ?
▁- ▁Ve ć ▁znam_bs ▁šta_bs ▁ću_bs ▁na_bs ruč iti_bs . ▁- ▁Hej , ▁do_bs daj te_bs ▁me_bs nije .
▁U_bs dalje nost ▁60 .
▁Ven ca_bs li_bs ▁su_bs ▁se_bs ▁19 55 .
▁Pa_bs , ▁kako_bs ▁ćemo ▁otvori ti_bs ▁to_bs ▁bez ▁ši fre ?
▁Dobro tvor na_bs ▁vec era ...
▁Ti_bs ▁si_bs ▁naj z god ni_bs ji_bs ▁lik ▁u_bs ▁svo m ▁ti_bs mu .
▁Na_bs ▁vr h ovima ▁moj_bs ih ▁kan d že_bs .
▁Ne_bs . ▁Zna te_bs . ▁Mislim ▁da_bs ▁jednostavno ▁ne_bs ▁voli te_bs ▁njihov u ▁vr stu .
▁Ne_bs ▁idi ▁na_bs ▁ul icu , ▁Mar lo_bs ne_bs ▁Kru z !
▁- Ma ▁jako ▁je_bs ▁dobra
▁Ona ▁ide ▁s_bs ▁njim .
▁- I ▁ho ćeš ▁da_bs ▁priča m ▁s_bs ▁ njima ▁s_bs ▁ovim ?
▁Svi ▁vi ▁ne_bs ▁možete ▁prihvat iti_bs ▁činjenic u ▁da_bs ▁smo_bs ▁možda ▁sje ban i .
▁Treba o ▁bi_bs ▁se_bs ▁dobro ▁osjeća ti_bs .
▁Us prav an_bs ! ▁Pa_bs ž nja !
▁Kako ▁to_bs ?
▁Bli ži ▁si_bs ▁nego ▁što_bs ▁misliš .
▁Sada ▁idemo ▁kući !
▁V re_bs me_bs ▁je_bs ▁da_bs ▁nauči š ▁da_bs ▁či tas .
▁- ▁Misliš ▁li_bs ▁da_bs ▁ima_bs ▁rak ?
▁- ▁W im_bs , ▁de_bs voj ka_bs ▁je_bs ▁opet ▁ovde .
▁- ▁Ž rt va_bs ▁je_bs ▁pozna vala ▁u_bs bi_bs cu_bs .
▁- Ha jde , ▁Jake !
▁Tri ▁godine ▁sam_bs ▁bila ▁savjet nica ▁tv om_bs ▁o_bs cu_bs .
▁Nisi ▁mogao ▁sta jati ▁da_bs ▁niko me_bs ▁reci ▁ono ▁sto ▁nije_bs ▁mogao ▁učiniti .
▁- Š ta_bs ▁si_bs ▁ti_bs , ▁ci gan ska ▁kur ti_bs zana ?
▁Zar ▁ne_bs ▁vidiš ▁ništa ?
▁Ne_bs , ▁nada o ▁sam_bs ...
▁Plan ira o ▁sam_bs ▁to_bs .
▁Ta mo_bs ▁je_bs ▁jedan ▁veterinar ▁sa_bs ▁koji_bs m ▁se_bs ▁viđ am ...
▁B org ▁kontroli ra_bs ▁više_bs ▁od_bs ▁polo vice ▁brod a .
▁Šta_bs ▁je_bs ▁sli je_bs de ce_bs , ▁nema ▁TV ▁dok ▁ne_bs ▁završi mo_bs ▁za_bs da_bs ce_bs ?
▁Tak va_bs ▁dra ma_bs ?
▁Možda ▁te_bs ▁to_bs ▁vozi lo_bs ▁hit ne_bs ▁pomoći ▁nije_bs ▁od_bs voz ilo ▁u_bs ▁bolnic u .
▁- S am ▁od_bs ▁sebe .
▁- ▁Iz abel , ▁ne_bs ▁sme š ▁da_bs ▁dozvoli š ... ▁tom ▁tip u ▁da_bs ▁un i šti ▁tvoj ▁život .
▁Ja_bs ▁sam_bs ▁ne_bs vin , ▁previše .
▁O_bs ve_bs ▁stvari ▁treba_bs mo_bs ▁za_bs ▁škol u .
▁Ona ▁je_bs ▁je_bs dina ▁žena ▁koju ▁si_bs ▁upozna o ▁a_bs ▁koja ▁ne_bs ▁mari ▁za_bs ▁tvoj u ▁pro_bs šlo st .
▁Mislim ▁da_bs ▁je_bs ▁sve_bs ▁ovo_bs ▁moja ▁gre ska .
▁Bo ja_bs ▁font a ▁= ▁" # ▁ ff ff 00 " ▁Nikad ▁nisam ▁vjer ova_bs o ▁u_bs ▁bana lo_bs sti_bs ▁koji_bs ▁pred vi_bs đa ju_bs ▁svoju ▁sud bin u ▁sa_bs ▁određenim ▁osoba ▁.. ▁Bo ja_bs ▁font a ▁= ▁" # ▁ ff ff 00 " ▁Ali_bs ▁moje ▁vi zi_bs je_bs ▁su_bs ▁tako_bs ▁jasno ▁i_bs ▁tako_bs ▁pravi ▁osjeća je_bs .
▁- ▁Še fer o vog ▁sve_bs do čen ja_bs .
▁Gu rni ▁gla vu ▁u_bs ▁ru pu ▁i_bs ▁reci ▁J . ▁He a ther ton .
▁To_bs ▁je_bs ▁li_bs jek ▁protiv ▁bolo va_bs .
▁D va_bs ▁du pla , ▁dodatni ▁so s ... ▁sala ta_bs , ▁sir , ▁kra stav či_bs ći_bs , ▁luk ... ▁na_bs ▁zem i čki ▁sa_bs ▁su_bs sam om_bs .
▁Ne_bs ▁previše ▁bli zu , ▁Al er gi can ▁sam_bs ▁na_bs ▁v unu .
▁Poč ni_bs te_bs ▁sa_bs ▁mal im_bs ▁stvari ma_bs , ▁stvari ma_bs ▁sa_bs ▁polic a , ▁la dica , ▁gri cka lica ma_bs , ▁su_bs venir ima_bs .
▁Da_bs , ▁ima_bs ▁veze ▁sa_bs ▁jutro š nji m ▁terorist ič kim ▁pret nja ma_bs .
▁Jeste ▁li_bs ▁u_bs ▁s_bs rod stvu ▁sa_bs ▁gospod i nom ▁O_bs x ly em ?
▁Do_bs bar ▁vojn ik , ▁taj ▁Co dy .
▁Ima ▁preko ▁10 0.000 .
▁Možda ▁je_bs ste ▁malo ▁i_bs ▁ cr ven o , ▁ali_bs ▁ ova_bs ▁uz ica ▁nije_bs ▁ništa ▁bolj a ▁od_bs ▁Bur ke ▁( a rap ski ▁po_bs krov ▁za_bs ▁lice ▁i_bs ▁tijelo ) !
▁Jaz z ▁mo mak .
▁On ▁misli ▁da_bs ▁je_bs ▁osta nak ▁njegov a ▁ide ja_bs .
▁To_bs ▁je_bs ▁bilo_bs ▁nev jer ovat no_bs !
▁A_bs ▁kad_bs ▁ti_bs ▁je_bs ▁sve_bs jedno , ▁ta ▁je_bs ▁pravo du š nost ▁priv la_bs čna .
▁Misliš ▁da_bs ▁smo_bs ▁u_bs kra li_bs ▁Re je_bs vu ▁ku_bs ti_bs ju_bs ?
▁- ▁Ko ▁si_bs ▁ti_bs ▁u_bs op šte ?
▁O_bs du vek ▁sam_bs ▁zna la_bs ▁da_bs ▁će_bs ▁tvoj ▁ rit ual ▁us peti ▁i_bs ▁om og ući ti_bs ▁mi_bs ▁da_bs ▁razgovara m ▁sa_bs ▁Klar kom .
▁James , ▁još ▁uvijek ▁ima_bs ▁vremena ▁da_bs ▁dobi ješ_bs ▁sve_bs ▁što_bs ▁si_bs ▁želi o .
▁Mo m ci_bs ▁u_bs ▁stanic i ... ▁Su ▁me_bs ▁jednostavno ▁iz_bs je_bs d na_bs či_bs li_bs ▁sa_bs ▁njim ... ▁Jer ▁sam_bs ▁ja_bs ▁bio_bs ▁ge j , ▁da_bs ?
▁Z vala ▁sam_bs ▁medicin skog ▁ispitn ika , ▁mrtv o zor nika .
▁Svi ▁ćemo ▁um rije ti_bs ▁ovdje .
▁Oni ▁su_bs ▁student i ▁sa_bs ▁univerz itet a ▁Tu son .
▁- Ka d ▁ste_bs ▁je_bs ▁pred ali ?
▁- ▁Pro lep ša će_bs ▁se_bs . ▁Kada ▁do_bs đe ▁pli ma_bs , ▁bi_bs će_bs ▁od_bs lično .
▁U_bs či_bs nio ▁vas_bs ▁je_bs ▁nes re_bs ć nom .
▁Hvala .
▁To_bs ▁nije_bs ▁iz_bs govor .
▁Sada ▁idi ▁odgovor iti_bs ▁na_bs ▁njihov a ▁pitanja .
▁To_bs ▁je_bs ▁društv eni ▁program ▁noć nog ▁stra ž aren ja_bs .
▁- Hva la_bs .
▁Po_bs nek ad ▁mi_bs ▁je_bs ▁priča o ▁o_bs ▁pro_bs šlo sti_bs ▁i_bs ▁o_bs ▁maj ci_bs .
▁Hvala .
▁Ja_bs ▁se_bs ▁ni_bs ▁o_bs cu_bs ▁nisam ▁iz_bs vin java o ▁kada ▁po_bs gre ši m .
▁Du š o , ▁zor a ▁je_bs ▁još ▁da_bs leko .
▁Vi ▁joj ▁u_bs op će_bs ▁ne_bs ▁da_bs je_bs te_bs ▁pri_bs liku ▁da_bs ▁je_bs ▁upozna te_bs .
▁Zato ▁što_bs ▁sam_bs ▁Ko di_bs , ▁on_bs aj ▁koji_bs ▁ti_bs ▁je_bs ▁posla o ▁c ve_bs će_bs .
▁Znaš , ▁nikada ▁nisam ▁misli la_bs ▁da_bs ▁ću_bs ▁ovo_bs ▁reći ... ▁ buk val no_bs ▁nikada , ▁ali_bs ▁mislim ▁da_bs ▁si_bs ▁bio_bs ▁ap solu t no_bs ▁u_bs ▁pravu ▁u_bs ▁vezi ▁nas_bs .
▁Ne_bs ▁juri m ▁kući ▁da_bs ▁š kra ba m ▁po_bs ▁svo m ▁dne v niku ▁kako_bs ▁si_bs ▁ti_bs ▁možda ▁vampir .
▁Gu bi_bs te_bs ▁ose ća_bs j ▁o_bs ▁tome ▁vi ▁iz_bs ▁USA ... ▁samo_bs u vere nost .
▁G . ▁Kol in ova_bs ▁seks ual na_bs ▁ ori jent acija ▁nema ▁ništa ▁sa_bs ▁ovim ▁slučaj em .
▁Od si je_bs ci_bs te_bs ▁te_bs ▁republi čke ▁brod ove ▁sa_bs ▁zal ih ama .
▁... ▁To_bs ▁je_bs ▁jos ▁jedan ▁brut al ni_bs ▁po_bs ne_bs djel jak ▁tamo ▁sa_bs obra ca_bs ja_bs - mu dar .
▁Ovaj ▁datum ▁mi_bs ▁je_bs ▁posebno ▁za_bs nim_bs ljiv .
▁- ▁Da_bs , ▁ali_bs ... ▁Pri v la_bs či_bs š ▁pa_bs ž nju . ▁Pri v la_bs či_bs š ▁pa_bs ž nju .
▁Ne_bs ▁mogu_bs ▁da_bs ▁na_bs pusti m ▁svoju ▁proda v nicu .
▁- ▁Što ▁ste_bs ▁vid jeli ▁kada ▁su_bs ▁iz_bs vad ili_bs ▁pištolj ?
▁Idem ▁kući .
▁H tio ▁je_bs ▁da_bs ▁je_bs ▁vidi .
▁- ▁Oh no_bs hy a ▁je_bs ▁OK , ▁zato ▁jer ▁Ta eko ▁nije_bs ▁nikad ▁tamo ▁bila .
▁Za_bs d nji ▁i_bs ▁najbolj i .
▁Da_bs ▁li_bs ▁ste_bs ▁upravo ▁re kli ▁" hi pi ji_bs " ▁i_bs ▁" meri d že_bs jn "?
▁Ne_bs ▁želim ▁to_bs ▁č uti ▁od_bs ▁tebe ,
▁On ▁će_bs ▁nas_bs ▁primi ti_bs ▁preko ▁no ći_bs , ▁a_bs ▁do_bs ▁Balti mor a ▁ćemo ▁sti ći_bs ▁su_bs tra .
▁Č EK AM ▁ TE ▁NA ▁PO B JE D NI Č KOM ▁P OST OL JU !
▁Kun em ▁ti_bs ▁se_bs ▁samo_bs ▁nam ▁se_bs ▁vrati .
▁Bilo ▁je_bs ▁već ▁vreme ▁da_bs ▁se_bs ▁skr asi ... ▁Pos le_bs ▁svih ▁žena ▁kroz ▁koje ▁je_bs ▁prolaz io .
▁Ti_bs ▁i_bs ▁ja_bs ▁na_bs ruč imo ▁taj lan sku ▁hra nu_bs , ▁po_bs je_bs de mo_bs ▁je_bs ▁u_bs ▁krevet u ▁i_bs ▁za_bs sp imo .
▁Pa_bs ▁od_bs ak le_bs ▁ti_bs ▁ovaj ▁Bar ?
▁Pri čaj ▁mi_bs ▁o_bs ▁ njo j .
▁Ri jet ko_bs ▁sam_bs ▁ga_bs ▁viđ ao , ▁pa_bs ▁je_bs ▁teško ▁vidjeti ▁raz liku .
▁K no_bs x ville ▁and ▁Tre ma_bs ine ▁su_bs ▁re kli ▁da_bs ▁im ▁se_bs ▁ide ja_bs ▁svi dja ▁je_bs di_bs no_bs ▁ako_bs ▁neko ▁ga_bs dja ▁stre lica ma_bs ▁iz_bs ▁svoje ▁gu zi_bs ce_bs ▁kroz ▁du val j ku_bs .
▁U_bs ▁ pita nju ▁je_bs ▁neka kva ▁igra , ▁ali_bs ▁r ješ_bs avam ▁to_bs .
▁- ▁Bi će_bs ▁sve_bs ▁u_bs ▁redu .
▁I_bs ▁pov la_bs či_bs m ▁se_bs ▁od_bs ▁vas_bs ▁i_bs ▁on_bs og ▁šta_bs ▁za_bs zi_bs vate ▁mi_bs mo_bs ▁Allaha , ▁a_bs ▁pri_bs zi_bs vat ▁ću_bs ▁Gospod ara ▁svog .
▁- N išta ▁on_bs ▁neće ▁sazna ti_bs .
▁Un u tra ▁je_bs ▁oko ▁20 - tak ▁ljudi .
▁Gdje ▁prav e ▁sat ove .
▁Mislim , ▁neki ▁u_bs ▁koje m ▁joj ▁se_bs ▁ništa ▁ne_bs ▁može ▁des iti_bs .
▁Ovdje ▁sam_bs ▁jer ▁treba_bs m ▁tvoj u ▁pomoć .
▁Vi še ▁ga_bs ▁nema m .
▁Je_bs dan ▁los ▁in tron ▁mo ze ▁sve_bs ▁da_bs ▁za_bs br lja .
▁Mo gla ▁si_bs ▁da_bs ▁po_bs šal ješ_bs ▁tele gram ▁da_bs ▁ćeš ▁do_bs ći_bs .
▁Gle da_bs o ▁sam_bs ▁u_bs ▁njega ▁a_bs ▁video ▁sam_bs ▁tebe .
▁Nemoj ▁ni_bs ▁po_bs misli ti_bs ▁da_bs ▁im ▁za_bs ku_bs ca_bs š ▁na_bs ▁vrata , ▁Mi c . ▁Ne_bs će_bs ▁razgovara ti_bs ▁s_bs ▁tobom .
▁- ▁Možda ▁se_bs ▁samo_bs ▁po_bs ig r avaju ▁s_bs ▁nama .
▁Znam .
▁O_bs ženi o ▁sam_bs ▁Ro su , ▁mis le_bs ći_bs ▁da_bs ▁ćeš ▁se_bs ▁ti_bs ▁za_bs mon aš iti_bs .
▁E ▁pa_bs , ▁malo ▁si_bs ▁za_bs kas nio .
▁Ne_bs ▁znam_bs .
▁ IMA ▁NE Š TO ▁J AKO ▁ VA Ž NO , Š TO ▁ SU ▁ME ▁N AU Č ILI ▁MO JI ▁PRE CI , ▁U_bs Č IT EL JU :
▁Šta_bs ▁je_bs ▁bilo_bs ▁kap etan e ▁?
▁Zo ve_bs ▁se_bs ▁Mad ison ▁Sin cla ir .
▁Molim ▁po_bs že_bs lite ▁dobro do šli cu_bs ▁Santa na_bs ▁Meg kan s ▁iz_bs ▁od_bs jela ▁za_bs ▁zaštitu ▁dje ce_bs .
▁Ne_bs ?
▁Rod it ▁ću_bs ▁ti_bs ▁dije te_bs .
▁U_bs ▁stvari , ▁on_bs ▁je_bs ▁bio_bs ▁na_bs ▁tvoj oj ▁strani ▁u_bs ▁on_bs om_bs ▁malo m ▁problem u .
▁- ▁By e , ▁oli via .
▁Kad ▁god ▁se_bs ▁vrati m .
▁Gledaj , ▁čovječe . ▁Do_bs šao ▁sam_bs ▁da_bs ▁ti_bs ▁kažem ▁lice m ▁u_bs ▁lice , ▁čovječe .
▁To_bs ▁nije_bs ▁za_bs ▁mene ?
▁- ▁Bu nde va_bs ▁i_bs ▁čo kol ada .
▁U_bs ▁ku_bs pati lu ▁iz_bs nad ▁radi ja_bs tora ▁se_bs ▁na_bs lazi ▁pro_bs zor .
▁Samo ▁ću_bs ▁pret po staviti ▁da_bs ▁si_bs ▁ga_bs ▁posla o ▁jednom ▁od_bs ▁star ih ▁Ben et tov ih ▁di ler a . ▁Ali_bs ▁ne_bs ▁moram ▁ga_bs ▁tamo ▁traži ti_bs , ▁zar ▁ne_bs ?
▁Na_bs ▁koji_bs ▁je_bs ▁način ▁samo_bs ▁o_bs stavljen .
▁Os lobo di_bs ćemo ▁se_bs .
▁Ca bot ▁me_bs ▁sam_bs ▁z vao ▁zbog ▁toga , ▁dan ▁prije ▁nego ▁je_bs ▁um ro .
▁George , ▁ka mo_bs ▁ces ?
▁Transport er ▁so bu .
▁Idem ▁pro_bs na_bs ći_bs ▁Helen .
▁sta ▁s_bs ▁ga_bs d nim_bs ▁raz vo dom ▁i_bs ▁gor kom ▁zatvoren om_bs ▁bit kom ▁i_bs ▁sve_bs ▁to_bs .
▁To_bs ▁nisu ▁ot pus ni_bs ▁papir i .
▁Ne_bs , ▁moj_bs ▁de_bs čko ▁me_bs ▁je_bs ▁ot ka_bs čio ▁na_bs ▁F lo_bs - Ri di_bs nom ▁kon cer tu .
▁I_bs ako ▁je_bs ▁moja ▁ljubav ▁sul uda , ▁razum ▁s_bs mir uje ▁bol ▁u_bs ▁mom ▁s_bs r cu_bs .
▁Samo ▁mi_bs ▁reci ▁šta_bs ▁se_bs ▁događa .
▁Žao ▁mi_bs ▁je_bs ▁ , ▁samo_bs ▁sam_bs ... ▁uh ...
▁Nisam ▁že lje la_bs ▁biti_bs ▁sljedeć a ▁na_bs ▁popis u ▁svog ▁muž a .
▁O_bs vu da_bs ▁prolaz e ▁ti_bs su će_bs ▁turi sta ▁i_bs ▁ljudi ▁u_bs ▁kup nji . ▁- Za š to ▁nije_bs ▁bilo_bs ▁svjedo ka_bs ? ▁Da_bs .
▁U_bs ▁kra co j ▁ver zi_bs ji_bs ▁sve_bs ▁je_bs ▁is_bs tina .
▁Do_bs la_bs ze ▁iz_bs ▁Par iza ▁dana s ▁poslije pod ne_bs .
▁Pot pun o ▁novi ▁ple s . . ▁... ▁koji_bs ▁sigurno ▁znaš .
▁- Mo raš , ▁Josh .
▁Ali_bs ▁vjer ujem ▁da_bs ▁si_bs ▁pošt ena ▁bu dala .
▁Tako ▁je_bs , ▁protiv o trov .
▁Pre ▁možete ▁ba ci_bs ti_bs ▁one ▁druge ▁u_bs bi_bs stva ▁na_bs ▁mene ?
▁- S vi_bs ▁se_bs ▁seks aju .
▁Želiš ▁da_bs ▁mi_bs ▁rast uri š ▁por odi cu_bs ▁samo_bs ▁zato ▁što_bs ▁su_bs ▁tvoj i ▁mrtv i .
▁- ▁Ne_bs ▁znam_bs ▁za_bs ▁ovo_bs ▁drugo , ▁možda ▁je_bs ▁rekao ▁ono ▁prvo . ▁- ▁S_bs lom ila ▁sam_bs ▁ga_bs ▁na_bs ▁name šta ju_bs .
▁Ski ni_bs ▁ga_bs ▁s_bs ▁mene !
▁Put ▁je_bs ▁ja_bs san
▁- Z bo g ▁tebe ▁sam_bs ▁postal a ▁policaj ka_bs .
▁Ima ▁živ e ▁u_bs ▁vodi ."
▁Šta_bs ▁sam_bs ▁ti_bs ▁rekla ▁o_bs ▁sk la_bs nja ju_bs ▁te_bs ▁od_bs je_bs ce_bs ?
▁- Mo ra_bs mo_bs ▁ih ▁poz vati .
▁Ni ti_bs ▁ išta ▁o_bs ▁Bog u ▁prev rata . ▁- ▁Mislim ▁da_bs ▁ ova_bs ko_bs ▁radi .
▁Znam ! ▁Ti_bs ▁si_bs ▁moj_bs ▁za_bs me_bs nik .
▁G . ▁Clark e ?
▁Na_bs ša ▁su_bs ▁te_bs la_bs ▁fa s ci_bs nant na_bs , ▁ali_bs ▁i_bs ▁glup a .
▁Ni ste ▁odavde ?
▁Pre gled ▁pra će_bs nja ▁vremena
▁Misli s ▁da_bs ▁si_bs ▁sa_bs vlad ao ▁v jes tinu , ▁zar ▁ne_bs ?
▁Znam .
▁Zna jući ▁da_bs ▁bi_bs ▁mogli ▁biti_bs ▁optuž eni ▁za_bs ▁u_bs boj stvo , ▁moj_bs i ▁su_bs ▁se_bs ▁kli jenti ▁u_bs span ič ar ili_bs ▁i_bs ▁si_bs ješ_bs ili_bs ▁se_bs ▁tijela .
▁Ili ▁postoje ▁ili ▁ne_bs ▁postoje .
▁Ku ša t ▁ću_bs ▁je_bs ▁i_bs ▁ja_bs .
▁Ako ▁si_bs ▁bu dan , tre ba o ▁bi_bs ▁da_bs ▁proba š ▁da_bs ▁ho da_bs š .
▁I_bs ▁nije_bs ▁on_bs ▁ govor ▁p jes nika ; ▁malo ▁što_bs ▁vjer ujete !
▁Er nes tine !
▁Kako ▁se_bs ▁po_bs nas aju ▁prema ▁Va ma_bs ▁u_bs ▁za_bs tvor u ?
▁U_bs isti nu_bs !
▁Či ni_bs ▁se_bs ▁da_bs ▁je_bs ▁sve_bs ▁čist o ▁pa_bs ▁kre će_bs m ▁tamo ▁da_bs ▁od_bs bac im_bs ▁ovu ▁be bi_bs cu_bs ▁kod ▁mog ▁have ra_bs ▁u_bs ▁ba zi_bs .
▁Up rk os ▁njegovo j ▁nes re_bs ći_bs , ▁nauči o ▁je_bs ▁da_bs ▁se_bs ▁šo ra_bs ... ▁i_bs ▁dobro ▁bor i .
▁Tim ... ▁tipo m .
▁Da_bs ▁li_bs ▁ti_bs ▁je_bs ▁već ▁da_bs o ▁svoj ▁broj ?
▁Pi j .
▁Tako ▁si_bs ▁napad an_bs .
▁Pre t hodno ▁u_bs ▁Co vert ▁A_bs ffa ir s ... ▁Moramo ▁je_bs ▁du b lje ▁u_bs bac iti_bs .
▁U_bs pozor en ▁sam_bs ? ▁A_bs ▁ tko ▁si_bs ▁ti_bs ? ▁Moj ▁u_bs či_bs telj ▁iz_bs ▁prvo g ▁raz re_bs da_bs ?
▁Poč eli ▁su_bs ▁da_bs ▁me_bs ▁pri_bs tiska ju_bs .
▁Bravo ▁plu to ne_bs .
▁- ▁Ho ću_bs ▁da_bs ▁uz mem ▁ovog .
▁Ne_bs ▁bor im_bs ▁se_bs ▁za_bs ▁ljude ▁koje ▁ne_bs ▁znam_bs .
▁To_bs ▁je_bs ▁se_bs man tika .
▁Ti_bs ▁ćeš ▁mi_bs ▁samo_bs ▁dati ▁ši bi_bs cu_bs .
▁Ja_bs ▁mogu_bs ▁imati ▁na_bs ja_bs vu ▁za_bs ▁ste_bs ▁da_bs ▁ce te_bs ▁k no_bs ck ▁Pol k ▁iz_bs ▁vode ▁ .
▁Kao s , ▁pa_bs nika , ▁kon fu zija .
▁Trebal a ▁si_bs ▁presta ti_bs ▁sur a đi vati ▁s_bs ▁civil ima_bs .
▁Hajde ▁Lu en , ▁priča j .
▁Pa_bs , ▁ci ni_bs ▁mi_bs ▁se_bs ▁ci st ▁onda , ▁zar ▁ne_bs ?
▁Da_bs . ▁Ovde ▁sam_bs ▁mesec ima_bs ... ▁bes kra j nim_bs ▁už as nim_bs ▁mesec ima_bs ▁u_bs ▁ovoj ▁mem ljivo j ▁tam nici ... ▁kao_bs ▁iz_bs gla dne la_bs ▁životinja ... ▁nada jući ▁se_bs ▁da_bs ▁ću_bs ▁da_bs ▁um rem ... ▁samo_bs ▁da_bs ▁ne_bs ▁bih ▁ ova_bs ko_bs ▁živ ela .
▁Na_bs stavi , ▁dušo .
▁- Hva la_bs .
▁Ja_bs ▁ću_bs ▁da_bs ▁priča m . ▁Znam ▁da_bs ▁ćeš ▁ hte ti_bs ▁da_bs ▁priča š , ▁ali_bs ▁se_bs ti_bs ▁se_bs , ▁ti_bs ▁si_bs ▁u_bs ▁em oti vno ▁ra nji vom ▁stan ju_bs .
▁Sigur ni_bs ▁ste_bs ?
▁Šta_bs ▁ti_bs ▁radiš ▁ovdje ?
▁Da_bs , ▁do_bs kle ▁god ▁to_bs ▁ne_bs ▁bude ▁kon j , ▁rad ujem ▁se_bs .
▁Sa ... ▁nov ci_bs cem ▁za_bs ▁papir ▁i_bs ▁kan ap ▁mo zes ▁dobiti ▁so p st ven a ▁kri la_bs
▁Ja_bs ▁se_bs ▁ne_bs ▁va tam ▁sa_bs ▁pr lja vim ▁od_bs vrat nim_bs ▁hi pi jem .
▁Pol u dela ▁je_bs .
▁Dobro . ▁Č uj , ▁o_bs pusti ▁se_bs .
▁Gledaj , ▁želim ▁i_bs ći_bs ▁jako ▁po_bs lako ▁s_bs ▁ovim .
▁Ko ga ▁si_bs ▁onda ▁z vala , ▁L orra ine ?
▁To_bs ▁se_bs ▁i_bs ▁tebi ▁baš ▁sada ▁dešava !
▁U_bs ▁po_bs nov ljeno m ▁su_bs đen ju_bs ▁Har a dina ju_bs ▁na_bs ▁površin u ▁iza š le_bs ▁ozbiljn e ▁tvrdnj e
▁Ovo ▁neće ▁i_bs ći_bs ▁da_bs leko , ▁prijatelj u .
▁Mislim , ▁zna la_bs ▁sam_bs ▁da_bs ▁je_bs ▁bio_bs ▁om i ljen ▁ali_bs ▁ovo_bs ▁je_bs ▁ne_bs do ljivo .
▁O_bs pusti ▁se_bs ▁malo , ▁Cre e per .
▁Gu bi_bs ▁se_bs .
▁Molim ▁vas_bs , ▁moram ▁da_bs ▁pod ne_bs sem ▁prijav u ▁ove ▁godine .
▁Pre ko_bs su tra ?
▁Ja_bs ▁po_bs nek ad ▁za_bs mišlja m ▁kako_bs ▁bi_bs ▁reci mo_bs ▁bilo_bs , ▁sa_bs ▁mom cima , ▁na_bs ▁primer , ▁ili ▁život om_bs ▁u_bs op šte .
▁Sada ▁će_bs ▁bar ▁to_bs ▁ri ješ_bs iti_bs .
▁A_bs ▁ja_bs ▁svoj a ▁nisam ▁pre_bs krš io .
▁Za_bs nim_bs ljivo .
▁- Da , ▁komitet ▁je_bs ▁posto ja_bs o ▁i_bs ▁ja_bs ▁sam_bs ▁bio_bs ▁član .
▁Vol jan ▁sam_bs ▁pot pis ati ▁ugovor .
▁Po_bs ko_bs pala ▁si_bs ▁ih ▁na_bs ▁su_bs du ▁prvi ▁puta , ▁ponovno ▁to_bs ▁napravi .
▁O_bs tvor i ▁pro_bs zor ▁u_bs ▁ku_bs hin ji_bs , ▁možda ▁će_bs ▁da_bs ▁pre_bs le_bs ti_bs ▁pravo ▁kroz ▁ku_bs ću_bs .
▁- O pusti ▁se_bs , ▁Bur t .
▁Bio ▁je_bs ▁to_bs ▁pravi ▁por o đa j ▁ljubav i ▁za_bs ▁mene .
▁Do_bs ▁dana s , ▁to_bs ▁mi_bs ▁je_bs ▁om i ljeni ▁sok .
▁Oh , ▁samo_bs ▁ona ko_bs ▁na_bs ga đa m ▁ali_bs ▁zar ▁vi ▁ni_bs ste ▁Liz ▁Bra un , ▁Blu je_bs va_bs ▁žena ?
▁August a !
▁Mali ▁je_bs ▁nap isa o ▁predsjednik u ▁re kav si ▁da_bs ▁kada ▁je_bs ▁u_bs ▁kamp a nji ▁je_bs ▁upozna o ▁njegov ▁pomoc nik ▁ , ▁g . ▁Far ley ▁ .
▁Nei s pun ja_bs vanje ▁norme ▁neće ▁biti_bs ▁to_bs leri s ano .
▁Slušaj , ▁pro_bs ći_bs ▁ćemo ▁kroz ▁ovo_bs ▁zajedno .
▁Je_bs ▁li_bs ▁to_bs ▁stan ▁3 ?
▁- ▁Iz vin java m ▁se_bs .
▁Sigur no_bs , ▁koliko ▁i_bs ▁su_bs nce ▁koje ▁će_bs ▁su_bs tra ▁up e ći_bs ▁do_bs ▁40 .
▁Po_bs nek ad , ▁se_bs dim ▁za_bs ▁komp om_bs , ▁i_bs ▁pani či_bs m .
▁I_bs ▁des et ▁po_bs ▁50 ▁čini ▁$ 5 ,000 .
▁Mora ▁biti_bs ▁nešto .
▁Ako ▁nisu ▁pro_bs meni li_bs ▁pravila ▁po_bs ker a , ▁ot kad ▁sam_bs ▁ovde ... ▁ti_bs ▁si_bs ▁izgubi o .
▁Šta_bs ▁ti_bs ▁radiš ▁u_bs ▁civil stvu ?
▁Mo že_bs ▁da_bs ▁me_bs ▁prvo ▁ubije š , ▁pa_bs ▁onda ▁p jev aš ?
▁Bio ▁je_bs ▁to_bs ▁jedan ▁od_bs ▁naj ca_bs rob ni_bs jih ▁trenutak a ▁u_bs ▁mo me_bs ▁zi vo tu .
▁Kada ▁sam_bs ▁joj ▁se_bs ▁vrati la_bs , ▁već ▁je_bs ▁bila ▁upozna la_bs ▁Maks vela .
▁Pa_bs zi_bs , ▁uvek ▁reci ▁da_bs ▁sam_bs ▁ja_bs ▁Am ede o .
▁Od ▁svih ▁nas_bs , ▁ti_bs ▁si_bs ▁najviše ▁imao .
▁Mi ▁ćemo ▁i_bs ći_bs ▁na_bs pred .
▁Bi cu_bs ▁gotov a ▁za_bs ▁sekund u .
▁I_bs ▁um re_bs ćeš ▁od_bs ▁sme ha , ▁sigur na_bs ▁sam_bs , ▁ako_bs ▁ti_bs ▁kažem ▁da_bs ▁me_bs ▁on_bs aj ▁čud an_bs ▁sus ret ▁s_bs ▁tobom ▁one ▁no ći_bs ▁u_bs ▁ma gli ▁i_bs ▁kas ni_bs ji_bs ▁sus re_bs ti_bs , ▁koji_bs ▁su_bs ▁me_bs ▁dobro ▁uz dr mali ▁da_bs ▁me_bs ▁to_bs ▁na_bs tera lo_bs ▁na_bs ▁razmišlja nje ▁prvi ▁put ▁u_bs ▁život u .
▁Pos u dji vale ▁smo_bs ▁pare ▁ jedni ▁od_bs ▁drugih ▁svo ▁vreme , nije ▁to_bs ▁ni_bs sta ,
▁- É ija ▁je_bs ▁ovo_bs ▁zabav a ?
▁Nikad a ▁ne_bs ću_bs ▁razum eti ▁že ne_bs .
▁- Da , ▁kao_bs ▁idiot ▁koji_bs ▁drži ▁ra žan j .
▁So ba ▁Hen rije te_bs ▁Lu pen ?
▁Kako ▁vam_bs a ▁ide ▁ovde ?
▁Poz vao ▁me_bs ▁van , ▁o_bs tis li_bs ▁smo_bs ▁na_bs ▁vec er u , ▁pri_bs ca_bs li_bs ▁smo_bs ▁i_bs ▁dje lo_bs valo ▁je_bs ▁poput ▁magi je_bs .
▁Šta_bs god ▁da_bs ▁je_bs ▁u_bs ▁ pita nju , ▁veliko ▁je_bs .
▁Tu ▁su_bs ▁tvoje ▁ja_bs pan ke ▁za_bs ▁tu s ▁tvoj ▁li_bs c ni_bs ▁pe skir ▁za_bs ▁tu s iranje , ▁pe skir ▁za_bs ▁ru ke ▁i_bs ▁jedan ▁za_bs ▁lice ▁tvoj ▁sa_bs pun ▁za_bs ▁ru ke , ▁sa_bs pun ▁za_bs ▁lice ▁i_bs ▁om i ljeni ▁sam_bs pon .
▁Zna o ▁sam_bs ▁da_bs ▁sat ▁ot ku_bs ca_bs va_bs ▁i_bs ▁da_bs ▁moje ▁vrijeme ▁dolazi ...
▁Ha d !
▁Kir k , ▁možemo ▁li_bs ▁da_bs ▁po_bs pri ča mo_bs ▁na_bs krat ko_bs ?
▁En o ▁problema .
▁Nisam ▁mu ▁to_bs ▁pred ba ci_bs vala , ▁jer ▁bi_bs ▁mi_bs ▁ina če_bs ▁bio_bs ▁dužn ik .
▁- ▁G . ▁Vol ton , ▁molim ▁Vas !
▁Kara s ...
▁Kaž eš ▁da_bs ▁si_bs ▁me_bs ▁u_bs bac ila ▁na_bs ▁listu ▁pos jeti o ca_bs , ▁jer ▁re kli ▁su_bs ▁ako_bs ▁nisam ▁por o dica ...
▁Ali_bs ▁to_bs ▁ne_bs ▁znači ▁da_bs ▁je_bs ▁tvoja ▁maj ka_bs ▁nesta la_bs .
▁Po_bs lako .
▁... i ▁sada ▁ulaz im_bs ▁u_bs ▁so bu , ▁gde ▁od_bs e ća_bs ▁od_bs lazi ▁um re_bs ti_bs .
▁Sa ▁mnom ▁ste_bs ▁sigur ni_bs .
▁Na_bs ▁drugo m ▁brod u , ▁koji_bs ▁je_bs ▁pri_bs sta o ▁u_bs ▁Sj ever noj ▁A_bs meri ci_bs ▁stol je_bs će_bs ▁kasnije , ▁bili ▁su_bs ▁običn i ▁en gle ski ▁rad nici ▁koji_bs ▁su_bs ▁samo_bs ▁že lje li_bs ▁zaradi ti_bs ▁malo ▁zemlje ▁z no_bs jem ▁svojih ▁ru ku_bs .
▁Jesi ▁li_bs ▁spremn a .
▁Gra b ljiva c ▁iz_bs ▁male ▁ku_bs će_bs ▁s_bs ▁veliko m ▁ sposob no_bs š ću_bs ▁da_bs ▁se_bs ▁spri ja_bs telj i ▁s_bs ▁mo ć nim_bs ▁mušk ar cima ▁i_bs ▁žena ma_bs .
▁Za_bs ve_bs ži , ▁gdje ▁su_bs ▁dija man ti_bs ?
▁Pi ta_bs o ▁sam_bs ▁se_bs ▁da_bs ▁li_bs ▁bih ▁možda ▁mogao ▁da_bs ▁nešto ▁uradim ▁za_bs ▁Maj nd s kej p .
▁- ▁Nisam ▁sigur na_bs / ▁ovaj -
▁To_bs ▁je_bs ▁sve_bs ▁što_bs ▁imamo .
▁Možemo ▁do_bs ći_bs ▁kasnije .
▁Japan ski ▁bomb ard eri ▁slobodn o ▁su_bs ▁napad ali ▁Singap ur ▁jer ▁nije_bs ▁bilo_bs ▁nik ak ve_bs ▁ zračn e ▁obra ne_bs .
▁Samo ▁da_bs ▁znaš , ▁nema ▁nije_bs d nog ▁zar eza ▁na_bs ▁tom ▁papir u .
▁Ob ično ▁bismo ▁ih ▁pos ad ili_bs ▁da_bs ▁se_bs de ▁u_bs ▁sa_bs li_bs ▁i_bs ▁u_bs bija li_bs ▁ stru jom ▁dok ▁gleda ju_bs ▁predstav u .
▁Po_bs lako ▁na_bs prije d .
▁" ali ▁mora ▁da_bs ▁sam_bs ▁bio_bs ▁u_bs ▁pogrešn o ▁vrijeme "
▁Kakv a ▁si_bs ▁ti_bs ▁to_bs ▁žena ?
▁Kau boj .
▁Vidi , ▁znam_bs ▁da_bs ▁bi_bs ▁radi je_bs ▁bio_bs ▁na_bs ▁za_bs dat ku_bs ▁sa_bs ▁Č a kom ▁i_bs ▁Sa rom , ▁ali_bs , ▁ci jeli ▁tvoj ▁život ▁ne_bs ▁moraju ▁da_bs ▁budu ▁samo_bs ▁za_bs da_bs ci_bs .
▁Da_bs , ▁se_bs ko_bs .
▁Zar ▁ni_bs ste ▁malo ▁pre_bs ter ali , ▁kap etan e ?
▁Pokuša j ▁sada .
▁- ▁Oh , ▁da_bs .
▁Pre ma_bs ▁posljednj em ▁poziv u , ▁on_bs ▁ne_bs ▁do_bs lij eva ▁samo_bs ▁u_bs lje ▁na_bs ▁va tru .
▁Jer emia h ▁Mc Le an_bs ▁je_bs ▁u_bs bio ▁Mary .
▁Na_bs dam ▁se_bs ▁da_bs ▁te_bs ▁nikada ▁više_bs ▁ne_bs ću_bs ▁vidjeti !
▁Oni ▁su_bs ▁samo_bs ▁is_bs ec kali ▁Gor mana .
▁Ne_bs ▁sme ju_bs ▁mu ▁se_bs ▁vide ti_bs ▁ni_bs ▁stop ala .
▁- Ko liko ▁vam_bs ▁ja_bs ▁plati o ? ▁- Ja ▁sam_bs ▁plati la_bs ▁njemu !
▁Mislim ▁da_bs ▁bi_bs ▁uz iva o .
▁Ben ▁i_bs ▁ja_bs ... ▁Za_bs vrš ili_bs ▁smo_bs .
▁I_bs ▁uz mem ▁svo ▁sa_bs lo_bs , ▁kao_bs ▁da_bs ▁su_bs ▁sa_bs lo_bs ▁moj_bs i ▁drugo vi_bs ▁iza ▁nepri ja_bs telj skih ▁linij a , ▁znaš .
▁Za_bs kas ni_bs li_bs ▁ste_bs ▁jedan ▁sat .
▁Rekla ▁sam_bs ▁ti_bs ▁da_bs ▁bi_bs ▁tro l ski ▁put ▁bio_bs ▁br zi_bs .
▁? ▁Qu ▁est ▁? ▁?
▁Kako ▁je_bs ▁to_bs ▁dobra ▁ vest ?
▁Pla ća_bs m ▁mu ▁kiri ju_bs , ▁kont aš ?
▁Ne_bs ▁mogu_bs ▁sada ▁priča ti_bs ▁s_bs ▁tobom , ▁na_bs z vat ▁ću_bs ▁te_bs .
▁Ne_bs ▁mo ze ▁se_bs ▁otkri ti_bs , ▁osim ▁pod ▁ljubi cast im_bs ▁svjetlo m , ▁te_bs ▁je_bs ▁pre_bs nos iv ▁na_bs ▁svakog a ▁ tko ▁ga_bs ▁do_bs dir ne_bs .
▁Znaš ▁li_bs ▁kako_bs ▁da_bs ▁se_bs ▁ponaša š .
▁- ▁Nisam ▁mogao .
▁Po_bs ruč ni_bs če_bs .
▁Se si lio ▁je_bs ▁otišao .
▁zen a , ▁ti_bs nej d ž er ▁i_bs ▁sve_bs ▁sto ▁to_bs ▁sa_bs ▁sob om_bs ▁no si .
▁S_bs voj e vre meno ▁je_bs ▁bio_bs ▁jedan ▁od_bs ▁naj mo_bs ć ni_bs jih ▁ljudi ▁u_bs ▁A_bs meri ci_bs .
▁Ba š ▁si_bs ▁se_bs ▁mi_bs moi šao ▁sa_bs ▁svoj om_bs ▁djevoj kom , ▁Bet ty ▁Su a rez .
▁Drž im_bs ▁te_bs ▁na_bs ▁oku , ▁gospodine .
▁Zaboravi la_bs ▁si_bs ▁namaz ati ▁kru h .
▁- ▁Reci ▁is_bs tinu , ▁We nde II .
▁- ▁M amina ▁mi_bs ▁se_bs ▁više_bs ▁svi đa .
▁Moram ▁reci ▁da_bs ▁sam_bs ▁iz_bs ne_bs na_bs đen .
▁# ▁Ali_bs , ▁dok ▁# ▁# ▁Po_bs m r či_bs na_bs ▁#
▁Bio ▁mi_bs ▁je_bs ▁kao_bs ▁otac .
▁U_bs ▁stvari , ▁tre nut no_bs , ▁naj važ ni_bs ji_bs .
▁- Mi s liš ▁da_bs ▁je_bs ▁ru ž na_bs ?
▁Bio ▁bih ▁bolj i ▁i_bs ▁od_bs ▁Char l tona ▁He sto na_bs .
▁Post o ▁su_bs ▁to_bs ▁vec ▁ju cer as nje ▁ vesti , ▁mo zem o ▁li_bs ▁da_bs ▁ih ▁ ost avimo ▁iza ▁sebe ?
▁On ▁je_bs ▁vrij e dio ▁mili ju_bs ne_bs . ▁Ali_bs , ▁znaš , ▁seda m ▁godina ▁nakon ▁nesta nka , ▁sud ▁će_bs ▁ga_bs ▁pro_bs glas iti_bs ▁služb eno ▁mrtv im_bs . ▁U_bs ▁to_bs ▁vrijeme , ▁ona ▁može ▁gla tko ▁da_bs ▁uz me_bs ▁već i ▁dio ▁nov ca_bs .
▁- ▁Zato ▁da_bs ▁bi_bs ▁mogao ▁da_bs ▁se_bs ▁sak rije .
▁- ▁Ne_bs ▁volim , ▁Nick !
▁- ▁To_bs liko ▁o_bs ▁primi r ju_bs .
▁Vol im_bs ▁po_bs gled , ▁znaš .
▁Za_bs tvor ili_bs ▁su_bs ▁joj ▁muž a ▁zato ▁što_bs ▁je_bs ▁imao ▁ve lika ▁usta .
▁Mo že_bs ▁da_bs ▁pokr ije ▁dva ▁mesec a , ▁ili ▁tako_bs ▁nešto .
▁Pri ča le_bs ▁smo_bs ▁o_bs ▁k nji zi_bs ▁Er ike ▁Jo ng ▁" S tra h ▁od_bs ▁let enja ".
▁I_bs mali ▁smo_bs ▁naj du ži ▁lov .
▁G . ▁Web ster , ▁g đa ▁A_bs cker man ▁iz_bs ▁Agencij e ▁za_bs ▁zapošljava nje .
▁- A ▁ga_bs ye vi_bs ▁su_bs ▁odgovor ili_bs ▁čo ko_bs la_bs dom ▁i_bs ▁si_bs rom .
▁Svi ma_bs ▁koje ▁volim .
▁Mal či_bs ce_bs ...
▁Sad ▁to_bs ▁pod ije lite !
▁Mislim , ▁zašto ▁ pita š ?
▁- ▁Zo vi_bs ▁So la_bs ▁" Re š et ku_bs " ▁telefon om_bs .
▁Do_bs bar ▁lov , ▁bra te_bs .
▁Nešto ▁te_bs ▁mu či_bs ?
▁Svi ▁osim ▁nas_bs .
▁Pre viš e ▁kontra di_bs kcija ▁za_bs ▁vaš ▁polici jski ▁mental itet ?
▁Da_bs ▁izravn am ▁sve_bs ▁dugo ve_bs ▁između ▁tebe ▁i_bs ▁mene .
▁Da_bs ▁bi_bs ▁pre_bs ži vela ▁ovde , ▁mora će_bs ▁da_bs ▁se_bs ▁pod či_bs ni_bs ▁tim ▁novi m ▁vlada ri ma_bs .
▁Evo ▁ga_bs ▁i_bs ▁ovde .
▁Od ak le_bs ▁joj ▁ ova_bs ▁s_bs ranja ?
▁Je_bs su ▁li_bs ▁nas_bs ▁na_bs šli ?
▁Molim o ▁vas_bs ▁da_bs ▁osta vite ▁svoje ▁ime ▁i_bs ▁broj ▁a_bs ▁mi_bs ▁ćemo ...
▁Bra k ▁moje ▁kćer ke ▁se_bs ▁rasp ada o , ▁a_bs ▁moj_bs ▁ze t , ▁Va rick ▁Stra us s , ▁je_bs ▁prije tio .
▁Moj ▁rod ni_bs ▁grad ▁u_bs ▁Tre će_bs m ▁ reich u
▁Got ovo ▁je_bs ▁za_bs stra šu ju_bs će_bs ▁koliko ▁s_bs lično sti_bs ▁nas_bs ▁dvoj e ▁imamo .
▁Kor nja če_bs ▁su_bs ▁glu he .
▁D va_bs ▁u_bs če_bs nika ▁nisu ▁dosta ▁da_bs ▁bi_bs ▁se_bs ▁škol a ▁o_bs drž ala .
▁- G i bb se !
▁Ali_bs ▁sad ▁sam_bs ▁se_bs ▁vrati o .
▁Pa_bs , ▁sada ▁se_bs ▁vas_bs ▁dvoj e ▁možete ▁provo za ti_bs .
▁Za_bs pan ju_bs ju_bs će_bs ▁je_bs ▁koliko ▁vremena ▁uz ima_bs ▁pis anje .
▁- ▁Ne_bs ▁radi ▁se_bs ▁o_bs ▁tome .
▁Do_bs đi , ▁ma leni .
▁Di z ajn iranje ▁sredi ne_bs .
▁Kad ▁je_bs ▁od_bs lazi la_bs , ▁za_bs gr lio ▁sam_bs ▁je_bs .
▁Daniel le_bs ▁je_bs ▁samo_bs ▁još ▁jedan ▁dan ▁u_bs ▁ DC - u .
▁- ▁Mo m ci_bs .
▁- ▁Hey , ▁zar ▁to_bs ▁nije_bs ?
▁Želim ▁savršen i ▁ljudsk i ▁život ▁s_bs ▁njim , ▁previše , ▁Stefan e , ▁vjer uj ▁mi_bs ,
▁Mr zim ▁ta ▁s_bs ranja . ▁- l z vin ite .
▁Rekao ▁sam_bs ▁vam_bs ▁da_bs ▁će_bs ▁biti_bs ▁bu dan , ▁zar ▁ne_bs ?
▁To_bs ▁nije_bs ▁ništa .
▁Raz log ▁više_bs ▁za_bs ▁už i vanje ▁u_bs ▁ovim ▁tren u cima ▁rad osti .
▁Teh nic ki ▁nisi .
▁O_bs ti_bs šao ▁sam_bs ▁tog ▁ju tra ▁dok ▁si_bs ▁ti_bs ▁još ▁spava la_bs .
▁Molim ▁te_bs , ▁nemoj ▁učiniti ▁nešto ▁što_bs ▁ćeš ▁pož ali ti_bs , ▁Lu cas .
▁Po_bs bri nu_bs cu_bs ▁se_bs ▁za_bs ▁svet .
▁Ne_bs ▁pokušava j ▁to_bs ▁prijatelj u .
▁V la_bs sti_bs ▁us m jer avaju ▁nap ore ▁na_bs ▁pružanj e ▁usluga ▁građan ima_bs ▁i_bs ▁na_bs ▁zaštitu ▁turi z ma_bs ▁kao_bs ▁vi tal nog ▁sektor a ▁za_bs ▁ovu ▁republi ku_bs .
▁Čo ve_bs če_bs , ▁Ber na_bs det ▁će_bs ▁o_bs bož a vati ▁ovo_bs .
▁Zašto ? ▁Pla ši te_bs ▁se_bs ? ▁Ili ▁dr hti te_bs ▁jer ▁vas_bs ▁ovo_bs ▁boli ?
▁- ▁U_bs ▁biti_bs .
▁D žo šu a ▁je_bs ▁otišao ▁sa_bs ▁o_bs cem ▁u_bs ▁Ar izo nu_bs , ▁Met ju_bs ▁je_bs ▁osta o ▁sa_bs ▁maj kom ▁u_bs ▁Vaš ington u .
▁- ▁Ta ta_bs ...
▁Tko ▁bi_bs ▁povjer ova_bs o ▁da_bs ▁će_bs ▁C lo_bs one y ▁biti_bs ▁sam_bs ▁u_bs ▁tim ▁godina ma_bs ?
▁Bio ▁sam_bs ▁mušk a rac !
▁Martin ▁je_bs ▁bio_bs ▁s_bs lobo dan ▁do_bs ▁po_bs no_bs ći_bs .
▁19 50 ▁si_bs vi_bs ▁for d .
▁Ne_bs , ▁ali_bs ▁je_bs ▁poznat o ▁lice , ▁zar ▁ne_bs , ▁Eric ?
▁L ju_bs di_bs ▁posta ju_bs ▁pred s jedni ci_bs ▁jer ▁su_bs ▁bili ▁na_bs ▁pravo m ▁mje stu ▁u_bs ▁pravo ▁vrijeme .
▁Da_bs ▁li_bs ▁ti_bs ▁je_bs ▁We a ver ova_bs ▁i_bs kad ▁re kala ▁šta_bs ▁joj ▁se_bs ▁des lio ▁tog ▁dana ▁na_bs ▁a_bs ked mi ji_bs ?
▁- JE SI ▁LI ▁V ID JE LA ▁E KO A ? ▁- NIS AM .
▁Do_bs z voli ▁da_bs ▁ti_bs ▁otvori m ...
▁Stav i ▁mu ▁u_bs ▁usta .
▁Mogu ▁li_bs ▁još ▁nešto ▁pi tati ?
▁- P u sti_bs ▁i_bs ▁mene .
▁I_bs ▁ako_bs ▁se_bs ▁kor dini ra_bs ▁sa_bs ▁bes pil ot nom ▁let ili_bs com ▁pred ator ...
▁Samo ▁je_bs ▁ima_bs la_bs ▁pokr et ▁cre vi_bs ma_bs ▁pred ▁svim a ▁sa_bs ▁svojim ▁posledn jim ▁jaki m ▁pri_bs ti_bs skom .
▁Men tal ni_bs ▁por eme ca_bs j ...
▁- Da .
▁Što ▁ćeš ▁sa_bs ▁svim ▁tim ▁nov cem ?
▁Jer ▁ništa ▁ne_bs ▁znam_bs .
▁A_bs ▁Bas tera ▁su_bs ▁po_bs vu kli ▁iz_bs ▁rat ne_bs ▁obu ke .
▁- ▁Is pit uju ▁m nog e . ▁Da_bs ?
▁Onda , ▁s_bs ▁či m ▁se_bs ▁tvoj ▁o_bs ta_bs ▁pre_bs živ lja va_bs ?
▁Možda ▁mi_bs ▁da_bs ju_bs ▁smjer nice .
▁- S vi_bs đa ▁mi_bs ▁se_bs .
▁I_bs ako ▁mi_bs ▁je_bs ▁is_bs pred ▁oči ju_bs , ▁ja_bs ▁još ▁uvek ▁ne_bs ▁ver ujem ...
▁A_bs ▁val cer ?
▁U_bs č la_bs nio ▁sam_bs ▁se_bs ▁u_bs ▁te_bs retan u .
▁S_bs re_bs o ▁sam_bs ▁Bez ub icu .
▁O_bs či_bs ▁ra vno ▁na_bs prije d
▁Dobro , ▁siguran ▁sam_bs ▁da_bs ▁nije_bs ▁ništa ▁strašn o . ▁Hajde ...
▁Molim ▁te_bs , ▁mama , ▁da_bs j ▁mu ▁da_bs ▁osta ne_bs ▁na_bs ▁vec eri !
▁A_bs ▁on_bs ▁je_bs ▁voli ?
▁Od ▁ glav nog ▁komand anta .
▁Zna s , ▁iz_bs med ju_bs ▁nas_bs ih ▁za_bs sed nja ▁div lja c ko_bs ... ▁je_bs ban je_bs , ▁dok ▁ne_bs ▁um remo .
▁Prim ili_bs ▁su_bs ▁me_bs ▁na_bs ▁ispitivan je_bs ▁li_bs je_bs ka_bs ▁za_bs ▁pat ološk u ▁s_bs ra_bs me_bs ž ljivost !
▁- ▁Šta_bs ▁želiš , ▁šta_bs ▁ti_bs ▁za_bs ista ▁želiš ? ▁Nova c !
▁Nešto ▁se_bs ▁dogodilo ▁is_bs pred ▁li_bs je_bs čni čke ▁ordin acije ▁u_bs ▁Pont y pool u . ▁Mogu će_bs ▁da_bs ▁se_bs ▁radi ▁o_bs ▁ne_bs red ima_bs ...
▁Moram ▁sti ci_bs ▁tamo .
▁Stvarno , ▁vrijeme ▁je_bs ▁da_bs ▁dobi jem ▁un uke .
▁7 ▁m ▁is_bs pred ▁tebe .
▁cita va_bs ▁je_bs ▁pro_bs s la_bs va_bs ▁V IP ▁prostor .
▁Uh ... ▁Ross .
▁Mo že_bs ▁dolazi ti_bs ▁od_bs ▁sva ku_bs da_bs .
▁- Ra ši rite ▁se_bs .
▁Pa_bs ▁koju ▁kor ist ▁imam ▁od_bs ▁toga ▁na_bs ▁pus tom ▁ot oku ?
▁Ne_bs ko_bs ▁zove ▁sa_bs ▁D ž ord ž ta_bs un ▁univerz itet a .
▁Sva ki ▁dan ▁mislim ▁o_bs ▁njemu .
▁Post oji ▁jedna ▁alternativ a ▁sa_bs ▁ovakv om_bs ▁ vrst om_bs ▁ raka
▁Da_bs ▁ne_bs ▁bi_bs ste ▁bili ▁u_bs sam ljeni ▁g . ▁Tre he ar n . ▁Si lazi mo_bs ▁naš ▁tro j ca_bs .
▁- Z nam , ▁pred iv na_bs ▁sam_bs .
▁Ale j andro ▁je_bs ▁mrtav .
▁Ovaj ▁svijet ▁će_bs ▁te_bs ▁sa_bs ž vaka ti_bs ▁i_bs ▁is_bs p lju nuti .
▁Ah , ▁prvi ▁sam_bs .
▁Um ro ▁je_bs ▁prije ▁nekoliko ▁ vije kova .
▁Sad ▁smo_bs ▁bo gati . ▁Koliko ▁ćemo ▁zaradi ti_bs ▁samo_bs ▁proda jom ▁škol e !
▁S_bs jedi te_bs ▁ob oje .
▁" Sa mo_bs ▁je_bs ▁tvoje ▁ime ▁na_bs ▁moj_bs im_bs ▁us na_bs ma_bs ."
▁Mak ni_bs ▁me_bs ▁sa_bs ▁svoje ▁pro_bs klet e ▁liste ▁i_bs ▁da_bs ▁me_bs ▁više_bs ▁nikad ▁nisi ▁z vao !
▁Jesi ▁li_bs ▁z bil ja_bs ▁S_bs ▁tim ▁ja_bs pi jev skim ▁sme će_bs m ?
▁Imam ▁svoju , ▁ali_bs ▁nema ▁šans e ▁da_bs ▁je_bs ▁iskoristi m .
▁- ▁Prav e ▁kvalifik acije . ▁- ▁Prav e ▁kvalifik acije . ▁To_bs čno , ▁Jim .
▁Hej , ▁Ed , ▁sa_bs ▁sreć om_bs ▁su_bs tra ▁u_bs ve_bs če_bs .
▁Moramo ▁pri_bs ček ati ▁konačn i ▁rezultat .
▁G . ▁Tak ata ... ▁U_bs ▁vezi ▁vaše g ▁plan a . .
▁Ne_bs , ▁ne_bs , ▁čovječe .
▁Whi ch ' ll ▁nas_bs ▁imaju ▁više_bs ▁do_bs ▁naš ih ▁pod ne_bs - 30 ▁kor jena st - to o ty ▁s_bs vjež e ▁i_bs ▁vo ć ni_bs ▁do_bs ruč ak .
▁Treba m ...
▁Je_bs z ▁bez ▁obzir a ▁što_bs ▁mr zim ▁to_bs ▁prizna ti_bs , ▁imam ▁problem ▁s_bs ▁Claire .
▁Do_bs bija m ▁be bu ▁bez ▁o_bs nih ▁bes a nih ▁no ći_bs ▁i_bs ▁pr lja vi_bs h ▁pel ena .
▁- ▁O_bs oh - o oh !
▁V rata ▁su_bs ▁bila ▁za_bs ključ ana .
▁Mislim ▁da_bs ▁me_bs ▁zo vu .
▁To_bs ▁ga_bs ▁povez uje ▁sa_bs ▁Re my jem , ▁a_bs ▁preko ▁Re my ja_bs ▁sa_bs ▁ot mi ča ri ma_bs .
▁Bruk aš ▁me_bs . ▁Vidi , ▁znam_bs ▁da_bs ▁si_bs ▁uz ne_bs mi ren , ▁ali_bs ...
▁A_bs ▁S_bs ten ▁S_bs mit ▁nije_bs ▁ni_bs ▁na_bs lik ▁tome !
▁Dobro ... ▁Una ▁Ve z ▁mas ... ▁El ▁Bar co .
▁Ne_bs ▁znam_bs ▁kako_bs ▁ću_bs ▁to_bs ▁u_bs radi ti_bs , ▁ali_bs ...
▁Zdravo , ▁Bon i .
▁Dobro .
▁Tako ▁je_bs ▁sve_bs ▁postav ljeno .
▁E va_bs ▁je_bs ▁po_bs pri li_bs čan ▁ku_bs har .
▁Je_bs ▁li_bs ▁to_bs ▁We a ver ?
▁Gospod ina ▁Tak era .
▁Pa_bs zi_bs te_bs ?
▁Žao ▁mi_bs ▁je_bs .
▁Š ali m ▁se_bs .
▁Slušaj , ▁možemo ... ▁da_bs ▁pomogne mo_bs ▁sa_bs ...
▁A_bs ▁rat nici ▁treba_bs ju_bs ▁zna ti_bs ▁zašto ▁ služ e ... ▁i_bs ▁gi nu_bs .
▁- S ve_bs ta_bs ▁krv .
▁Ima ▁let ili_bs cu_bs .
▁Znam ▁dovoljno ▁da_bs ▁raz lik ujem ▁ulaz nu_bs ▁ra nu_bs ▁od_bs ▁izlaz ne_bs .
▁Kako ▁Ele ono re_bs ▁izgleda ?
▁To_bs ▁je_bs ▁moj_bs ▁ta ta_bs . ▁U_bs ▁bolnic i ▁je_bs .
▁Bi će_bs ▁to_bs ▁tvoja ▁priča .
▁S_bs tvor enja ▁se_bs ▁kre ću_bs ▁s_bs ▁pov eć om_bs ▁sigurno š ću_bs .
▁Pro ro can stva ▁govori še ▁o_bs ▁ cov je_bs ku_bs , ▁koji_bs ▁ce ▁jednog ▁dana ▁pokuša ti_bs ▁s_bs klop iti_bs ▁mas ku_bs ▁i_bs ▁vlada ti_bs ▁svijet om_bs .
▁Zar ▁ne_bs ▁znaš ▁da_bs ▁nebo ▁je_bs ▁pla vo
▁Da_bs ▁za_bs mi jen imo ▁prav e ▁ši fre ▁la žni m .
▁Č ula ▁sam_bs ▁glas ine .
▁ TI TL ▁BY ▁R OD JO CO US IN
▁O_bs ti_bs šao ▁sam_bs ▁od_bs ▁ku_bs će_bs ▁sa_bs ▁4 ▁godine ▁i_bs ▁još ▁se_bs ▁nisam ▁vrati o .
▁Gdje ▁si_bs ▁bila ▁jutro s ?
▁Samo ▁ne_bs ▁bih ▁vole o ▁da_bs ▁me_bs ▁taj ▁mor on ▁ubije .
▁Svi ▁su_bs ▁prop a lice !
▁Va zu .
▁Ko ga ▁je_bs ▁briga ▁za_bs ▁muž u .
▁I_bs ako ▁bih ▁mogao ▁op oz vati ▁tvoj ▁pas o š ▁i_bs ▁ staviti ▁ti_bs ▁ime ▁na_bs ▁listu ▁zločin aca . ▁I_bs ▁is_bs je_bs ći_bs ▁ti_bs ▁str uju ▁do_bs ▁kraj a ▁života .
▁Šta_bs ? ▁Je_bs l ▁ovo_bs ▁ka kva ▁šal a ?
▁Pre ure di_bs li_bs ▁su_bs ▁mrtv a čni ce_bs ▁sm ješ_bs tene ▁u_bs ▁pod rum u .
▁Kako ▁je_bs ▁bilo_bs ▁na_bs ▁sa_bs stan ku_bs ?
▁Ne_bs ▁di ram ▁je_bs , ▁i_bs ▁s_bs klon i ▁mi_bs ▁se_bs ▁is_bs pred ▁oči ju_bs .
▁Ako ▁se_bs ▁Ha ley ▁nikada ▁ne_bs ▁pro_bs bud i ▁po_bs lug ola ▁na_bs ▁pla ži ▁u_bs ▁Flor idi ▁napravi la_bs ▁sam_bs ▁svoj ▁posao .
▁No site ▁se_bs .
▁Idemo ▁unutra , ▁va zi_bs ?
▁Sam ▁položaj ▁je_bs ▁noć na_bs ▁mora , ▁Svet osti .
▁Treba ▁da_bs ▁proc isti m ▁misli .
▁I_bs ▁zbog ▁tog ▁bi_bs ▁ovo_bs ▁trebalo ▁biti_bs ▁u_bs ▁redu ?
▁Na_bs z ovi ▁me_bs ▁kada ▁stig neš ▁tamo .
▁Ba š ▁je_bs ▁me_bs kan o .
▁Po_bs kazi ▁mi_bs ▁tvoj ▁prst .
▁Ski da_bs mo_bs ▁s_bs nim_bs ke .
▁51 - godi š nji ▁Albert ▁Jaz ex hi ▁v las nik ▁je_bs ▁ka fe - bara ▁u_bs ▁centr u ▁T irane .
▁U_bs ▁stvari ▁ima_bs ▁og rom ne_bs ▁rezerv e ▁u_bs ▁La os u . ▁Što ▁je_bs ▁i_bs ▁dove lo_bs ▁do_bs ▁in fla cije . ▁A_bs ▁to_bs ▁znači ▁kako_bs ▁stvar aju ▁previše ▁nov ca_bs .
▁I_bs ▁za_bs ▁naš ▁novac .
▁- Ž ao ▁mi_bs ▁je_bs . .
▁- O ▁s_bs ranja !
▁Na_bs z vali ▁smo_bs ▁sebe ▁dva ▁puta ▁mu dri m .
▁Znam ▁jednog ▁što_bs ▁živi ▁ovde .
▁Ba š ▁su_bs prot no_bs .
▁- ▁Šta_bs ?
▁- No gir ali ▁su_bs ▁ga_bs ▁od_bs ▁tamo .
▁Ovo ▁je_bs ▁Wy nn ▁Du ff y . ▁- ▁Zdravo .
▁Gospod ine ▁Ke ču m !
▁Možemo ▁gleda ti_bs ▁sva db ene ▁slik e .
▁Tako ▁sam_bs ▁iz_bs ▁ne_bs pozna t osti ▁došao ▁do_bs ▁plat ina ste ▁ploč e .
▁Sh va_bs ća_bs m ▁da_bs ▁ne_bs ▁rast u ▁na_bs ▁sta bli ma_bs .
▁H ra_bs bri ▁ljudi ▁u_bs bi_bs ju_bs ▁ih .
▁- ▁Moja ▁su_bs pru ga ▁je_bs .
▁On ▁je_bs ▁samo_bs ▁ ljub om_bs oran ▁na_bs ▁tebe .
▁Do_bs du še , ▁ima_bs ▁jedan ▁lokal ▁sa_bs ▁od_bs lično m ▁taj land skom ▁hra nom .
▁Imam ▁10 -2 ▁na_bs ▁kri žan ju_bs ▁35 . ▁i_bs ▁9. ▁u_bs lice .
▁Šta_bs ▁ti_bs ▁radiš ▁ovde ?
▁Če sti_bs tam , ▁dru ška ne_bs .
▁Ba to , ▁gubi m ▁signal .
▁" Mi s lio ▁sam_bs ▁da_bs ▁ste_bs ▁re kli ▁60 ▁minuta ." ▁" 10 ▁minuta , ▁gubi ▁se_bs ."
▁Sve ▁je_bs ▁u_bs ▁podaci ma_bs .
▁Ku pio ▁sam_bs ▁už inu .
▁Pro šli ▁smo_bs ▁milion ▁puta ▁kroz ▁to_bs ,
▁Sad ▁se_bs ▁boj im_bs , ▁da_bs ▁je_bs ▁to_bs ▁ta ▁slik a .
▁O_bs t kaz ?
▁Ti_bs ▁la zes .
▁Ne_bs ▁za_bs meri ▁mi_bs ▁što_bs ▁te_bs ▁pi tam ... ▁Koliko ▁imaš ▁godina , ▁Fil ?
▁Svi đa ▁mi_bs ▁se_bs .
▁Gro zna ▁je_bs ▁to_bs ▁stvar ▁živ jeti ▁u_bs ▁m ra_bs ku_bs , ▁ne_bs ▁biti_bs ▁u_bs ▁mogu_bs čnost i ▁vidjeti ▁ono ▁što_bs ▁drugi ▁uz ima_bs ju_bs ▁zdrav o ▁za_bs ▁gotov o .
▁Na_bs vali te_bs , ▁ma ce_bs .
▁Ja_bs ▁ust vari ▁volim ▁svoj ▁život ▁baš ▁ ova_bs kav ▁ka kav ▁je_bs .
▁- V id imo ▁se_bs ▁mom ci_bs .
▁- Ć ao ▁Emily .
▁To_bs ▁je_bs ▁do_bs vod ▁zrak a ▁za_bs ▁Hi ve_bs . ▁Hajde .
▁Ko ja_bs ▁je_bs ▁Be a trice ?
▁I_bs ▁ja_bs ▁sam_bs ▁to_bs ▁misli la_bs .
▁Ve oma ▁je_bs ▁stvar an_bs ▁mama .
▁Ko ji_bs ▁vam_bs ▁je_bs ▁ponudi o ▁Da_bs ▁se_bs ▁u_bs da_bs .
▁Tko ▁je_bs ▁glas ao ▁za_bs ▁La uru ▁Ro s lin ?
▁Pri prem ili_bs ▁smo_bs ▁obr oke ▁kor iste ći_bs ▁tradi cional ne_bs ▁vojn e ▁sa_bs stoj ke .
▁- ▁Zato ▁što_bs ▁tak vi_bs ▁kao_bs ▁što_bs ▁je_bs ▁on_bs ▁to_bs ▁ rade . ▁Moram ▁da_bs ▁idem .
▁- O d ▁prvo g ▁moment a ▁kad_bs ▁sam_bs ▁te_bs ▁s_bs rela , ▁zna la_bs ▁sam_bs .
▁Bobby ▁ce ▁ti_bs ▁pomoc i , ▁Tess .
▁Pla vi_bs ▁čovjek .
▁Jesi ▁li_bs ▁ik ada ▁radio ▁ išta ▁s_bs lično ?
▁Da_bs , ▁ali_bs ▁to_bs ▁se_bs ▁ stavlja ▁u_bs ▁ uši .
▁Či ni_bs ▁se_bs ▁da_bs ▁je_bs ▁brod ▁pret r pio ▁štet u ▁od_bs ▁me_bs te_bs ora .
▁" Li ter atura ▁je_bs ▁pun a ▁takvih ▁af era ."
▁Ana , ▁jako ▁je_bs ▁lijepo ▁imati ▁neko g ▁ko ▁se_bs ▁op ho di_bs ▁prema ▁tebi ▁Kao ▁da_bs ▁mu ▁je_bs ▁stvarno ▁stalo ▁do_bs ▁tebe .
▁- ▁Mit zi_bs .
▁Ali_bs ▁zaboravi o ▁si_bs ▁jedan ▁detalj .
▁Šta_bs ▁se_bs ▁dogodilo ?
▁Nakon ▁toga ▁sto ▁si_bs ▁uradio ▁The i , ▁Sa ri , ▁Oliver u ?
▁Ne_bs ▁gleda j ▁me_bs ▁tako_bs , ▁Chuck .
▁Onda ▁se_bs ▁vidim o ▁opet , ▁da_bs ?
▁Znam ▁da_bs ▁si_bs ▁fru stri ran , ▁ali_bs ▁ne_bs ▁možemo ▁presta ti_bs ▁sada .
▁Bit ▁ću_bs ▁malo ▁ovdje ▁s_bs ▁vam_bs a , ▁ako_bs ▁može . ▁- Ne ▁može !
▁Tako dje ▁sve_bs ▁mrtv o .
▁Jos ▁prije ▁20 ▁godina ▁dr . ▁Hu b bert ▁je_bs ▁u_bs kazi vao ▁svojim ▁koleg ama ▁u_bs ▁industri ji_bs ▁na_bs fte ▁da_bs ▁ce ▁S_bs AD ▁ vjerojatn o ▁do_bs se ci_bs ▁vr hun ac ▁proizvodnje ▁na_bs fte ▁unutar ▁10 - 15 ▁godina .
▁Sada ▁samo_bs ▁želim ▁biti_bs ▁dobra ▁mama .
▁Ob zi_bs rom ▁da_bs ▁ste_bs ▁ovdje ▁radi ▁osigura nja ▁ tehničk e ▁podršk e ▁glede ▁De fi anta
▁Ne_bs ćemo ▁je_bs ▁la ko_bs ▁u_bs bed iti_bs ▁da_bs ▁pro_bs govori .
▁E ci_bs ▁pe ci_bs ▁pe c ?
▁Za_bs ▁Tek sa ške ▁maj ke .
▁So bi_bs ▁i_bs ▁Lang or ▁su_bs ▁odluči li_bs ▁da_bs ▁vam_bs ▁ga_bs ▁da_bs ju_bs .
▁Moramo ▁ih ▁obavijesti ti_bs ▁da_bs ▁si_bs ▁sigur na_bs .
▁Val j da_bs ▁imam ▁više_bs ▁do_bs nje g ▁veš a ▁od_bs ▁tebe .
▁Don ▁Ty ler ?
▁- ▁Že le_bs ▁nas_bs ▁u_bs hvat iti_bs ▁vu čno m ▁zrak om_bs .
▁- O bo je_bs ▁smo_bs ▁sje ban i .
▁Če ka_bs mo_bs ▁za_bs pis e ▁o_bs ▁ne_bs kret n inama , ▁ali_bs ▁mislim o ▁da_bs ▁je_bs ▁njegovo ▁zemlji šte ▁mesto ▁gde ▁grup a ▁misli ▁da_bs ▁ ču či_bs .
▁Dig ni_bs te_bs ▁ga_bs , ▁mom ci_bs !
▁- Ja ▁ću_bs ▁optuž iti_bs ▁Frank a ▁i_bs ▁pod ije lit ▁ćemo ▁troškove .
▁Trebal o ▁je_bs ▁da_bs ▁se_bs ▁ja_bs vim .
▁Ako ▁pomo li_bs ▁gla vu , ▁sti s nu_bs ću_bs ▁brzo ▁bir anje .
▁- Ne ▁želim ▁o_bs ▁tome .
▁Da_bs ▁mogu_bs ▁osta ti_bs ▁hlad na_bs .
▁Raz govara li_bs ▁su_bs ▁o_bs ▁fot kama ▁u_bs ▁škol skom ▁godišnj a ku_bs . ▁Kako ▁ni_bs tko ▁nije_bs ▁za_bs d ovolj an_bs ▁svojim ▁iz_bs gled om_bs .
▁I_bs ▁ako_bs ▁je_bs ▁ne_bs ▁pi je_bs te_bs , ▁ide te_bs ▁pravo ▁u_bs ▁za_bs tvor .
▁- ▁One s vijesti o ?
▁Možemo ▁ob oji cu_bs ▁od_bs bac iti_bs ▁kao_bs ▁os um nji čen e .
▁Pa_bs , ▁Charles , ▁nazad ▁na_bs ▁tvoj u ▁pis u .
▁" Fi lisi " ▁su_bs ▁po_bs bed ili_bs .
▁V jer ovat no_bs ▁ne_bs ▁bi_bs ▁trebao ▁pi tati ▁da_bs ▁li_bs ▁se_bs ▁je_bs ▁nešto ▁čud no_bs ▁des ilo ▁na_bs ▁ste_bs pen i štu , ▁zar ▁ne_bs ?
▁Ve b sa jt ▁su_bs ▁pokr en uli ▁bu gar ski ▁Ce ntar ▁za_bs ▁ne_bs prof it no_bs ▁pravo ▁i_bs ▁Program sko - an_bs ali ti_bs čki ▁cent ar ▁za_bs ▁evropsk o ▁pravo .
▁Kru go vi_bs .
▁Mer line , ▁stig ao ▁si_bs ▁na_bs ▁vrijeme .
▁I_bs ▁mora te_bs ▁nam ▁vratiti ▁oružje .
▁Mislil a ▁sam_bs ▁da_bs ▁ću_bs ▁se_bs ▁mora ti_bs ▁o_bs staviti ▁pila tes a , ▁tr čan ja_bs , ▁ten isa ▁i_bs ▁sat ova_bs ▁stri pti z ▁a_bs e robi ka_bs .
▁Dobro ▁jutro , ▁Dr . ▁Gordon .
▁- O z bil jan ▁je_bs , ▁Robin e .
▁Post ara će_bs ▁se_bs ▁da_bs ▁živi š ▁kao_bs ▁kralj .
▁Moraš ▁prvo ▁reći ▁da_bs ▁ti_bs ▁je_bs ▁žao .
▁Nemoj ▁ni_bs ▁po_bs mišlja t ▁na_bs ▁to_bs .
▁Je_bs ▁l ' ▁vam_bs ▁treba_bs ▁pre_bs voz ?
▁Po_bs no_bs ć ▁je_bs , ▁i_bs ▁su_bs z država m ▁se_bs ▁od_bs ▁plak anja ▁is_bs pred ▁sina .
▁Ja_bs ▁sao sje æ am , ▁za_bs ista ▁je_bs sam .
▁K r v nik ▁ju ▁je_bs ▁pri_bs é vrst io ▁za_bs ▁po_bs jas , ▁s_bs man ju_bs jući ▁rasp o djel u ▁te_bs ži ne_bs ▁oko ▁str uka ▁o_bs stavlja jući ▁ vrat ▁ne_bs tak nuti m .
▁Znaš ▁li_bs ▁koja ▁će_bs ▁s_bs lede ća_bs ▁a_bs kcija ▁da_bs ▁bude ?
▁Ste ka_bs o ▁si_bs ▁veliko ▁pošt ovanje ▁s_bs mak nu_bs će_bs m ▁bomb a ša ▁Len gli ja_bs .
▁" Ma ma_bs , ▁ja_bs ▁želim ▁ho t ▁dog ."
▁- Mo ja_bs ▁mama ▁gleda .
▁Pre traži o ▁sam_bs ▁mesto ▁od_bs ▁vr ha ▁do_bs ▁d na_bs .
▁- Mi s liš ▁da_bs ▁sam_bs ▁debe o ?
▁Da_bs , ▁ali_bs ▁nisi ▁imao ▁des et ▁godina .
▁Pri vedi te_bs ▁ovo_bs ▁kraju .
▁Sada ▁to_bs ▁zna ci_bs ▁ona .
▁Sa zna j ▁ko ▁je_bs ▁taj ni_bs ▁o_bs bož ava lac . ▁- Za š to ▁ja_bs ?
▁Z bil ja_bs ?
▁Jer ▁sam_bs ▁u_bs kra o ▁star u ▁zen sku ▁to_bs rbi cu_bs .
▁Spe ar s , ▁Spe ar s , ▁da_bs .
▁Moja ▁prijatelji ca_bs ▁Rose mar y ▁Cro s s .
▁- s mi ješ_bs na_bs ▁je_bs ▁ ova_bs ▁cur a ▁ha ▁ljudi ▁?
▁U_bs ▁redu .
▁Do_bs tad ▁je_bs ▁je_bs di_bs no_bs ▁bit no_bs ▁koliko ▁ću_bs ▁potroš iti_bs ▁na_bs ▁hotel ske ▁usluge .
▁Uh vati te_bs ▁ga_bs ▁s_bs ▁mene .
▁ cak ▁ga_bs ▁i_bs ▁oni ▁m rze .
▁" Ta - ra_bs ▁ta - ta_bs , ▁ta - ra_bs ▁ta - ta_bs ▁pro_bs s ja_bs ci_bs ▁se_bs ▁že ne_bs ▁noć as
▁A_bs ▁onda ▁sam_bs ▁se_bs ▁u_bs u dala ▁za_bs ▁tebe . ▁I_bs ▁onda ▁sam_bs ▁sazna la_bs ▁da_bs ▁svaki ▁ima_bs ▁isto ▁s_bs ranje .
▁Da_bs ▁li_bs ▁ti_bs ▁je_bs ▁pot reb na_bs ▁pomoć , ▁Ni na_bs ?
▁- ▁To_bs ▁je_bs ▁mnogo ▁vremena ▁da_bs ▁bio_bs ▁u_bs ▁ku_bs pati lu .
▁Mu za ▁se_bs ▁po_bs javljuje .
▁Ja_bs ▁sam_bs ▁Ja_bs red ▁To_bs l son .
▁Sh va_bs ća_bs m , ▁još ▁jedan ▁prop ali ▁revoluci on ar , ▁os jeti o ▁si_bs ▁pri_bs tis ak .
▁- ▁Drago ▁mi_bs ▁je_bs ▁da_bs ▁sam_bs ▁vas_bs ▁upozna o .
▁On ▁je_bs ▁Patri k ▁Paris i , ▁ok ?
▁O_bs če_bs , ▁treba_bs m ▁te_bs ▁hit no_bs ... ▁jer ▁imam ▁dvoj be ... ▁strašn e ▁sumnj e ▁mu če_bs ▁mi_bs ▁du šu .
▁- O bo je_bs ▁post i zu ▁ isti ▁cilj .
▁Daj ▁mi_bs ▁de_bs ton ator , ▁sine .
▁U_bs ▁redu , ▁mom ci_bs .
▁Ja_bs ▁ću_bs ▁da_bs ▁ih ▁gleda m .
▁Bro š ura ▁je_bs ▁od_bs li_bs čna , ▁ali_bs ▁šta_bs ▁je_bs ▁sa_bs ▁Jean ?
▁Jesi ▁li_bs ▁tu ?
▁Ik ada .
▁To_bs ▁je_bs ▁je_bs di_bs no_bs ▁mesto ▁na_bs ▁kom e ▁ste_bs ▁sigur ne_bs .
▁Ali_bs . '
▁Shar on , ▁njegov ▁lik ▁će_bs ▁um rije ti_bs ▁ako_bs ▁ne_bs ▁do_bs đem o ▁do_bs ▁njega .
▁Govori ▁en gle ski .
▁- ▁On ▁je_bs ▁geni je_bs , ▁zar ▁ne_bs ?
▁Ja_bs ▁mislim ▁da_bs ▁se_bs ▁na_bs loži o ▁na_bs ▁tebe ▁a_bs ▁ti_bs ▁se_bs ▁prima š ▁na_bs ▁to_bs .
▁Hej ▁Em ma_bs .
▁- Ne ma_bs ▁drugog ▁na_bs cina , ▁pla vi_bs ▁de_bs c ko_bs .
▁Di mi try , ▁ne_bs ▁misliš ▁li_bs ▁da_bs ▁je_bs ▁vreme ▁da_bs ▁de_bs ca_bs ▁i_bs du ▁u_bs ▁krevet ?
▁Ovdje ▁nije_bs ▁sigurno . ▁Mora te_bs ▁se_bs ▁što_bs ▁prije ▁s_bs klon iti_bs ▁sa_bs ▁u_bs lica .
▁- ▁Moje ▁je_bs ▁za_bs d ovolj stvo , ▁Charles .
▁Ko ▁je_bs ▁ovo_bs ▁?
▁Hej ▁kap etan e , ▁ho ćeš ▁jedan ▁uz o ?
▁Mora te_bs ▁imati ▁fotografi je_bs ▁nje ma_bs čko g ▁nau čni ka_bs .
▁Da_bs ▁bare m ▁ovo_bs ▁nije_bs ▁is_bs tina , ▁ali_bs ... ▁zvuč i ▁dosta ▁kao_bs ▁Se rena ▁koju ▁sam_bs ▁ja_bs ▁pozna vala .
▁I_bs ▁nije_bs d na_bs ▁životinja ▁ne_bs ▁profit ira ▁na_bs ▁ njima ▁toliko ▁kao_bs ▁gri z li_bs ▁med ved .
▁To_bs ▁bi_bs ▁bilo_bs ▁o_bs stva ren je_bs ▁s_bs nova .
▁Hej , ▁de_bs da_bs !
▁Vaš ▁a_bs meri čki ▁narod ▁će_bs ▁da_bs ▁plati ▁za_bs ▁ovu ▁vaš u ▁gre š ku_bs .
▁CA MER ON ▁M EY ER ▁I_bs ▁ JA RED ▁B REN N ER . ▁- ▁J OS ▁NE KA ▁V EZ A ?
▁Hajde , ▁ha jde , ▁kre ni_bs te_bs .
▁Pi ta_bs o ▁si_bs ▁ma mu ▁za_bs ▁foo t ball ?
▁Problem ▁će_bs ▁se_bs ▁du bo ko_bs ▁sak riti ▁i_bs ▁de_bs koncentr isa ti_bs ▁njegov ▁razum .
▁Od lično ▁je_bs .
▁Zašto ?
▁Ce ntar ▁za_bs ▁mo lek ular nu_bs ▁medicin u ▁i_bs ▁Nacional na_bs ▁genet i čka ▁laboratorij a ▁otvoren i ▁su_bs ▁u_bs ▁So fi ji_bs ▁7. ▁decembra .
▁O_bs čaj ni_bs čki ▁sam_bs ▁te_bs ▁traži o ▁3 ▁godine .
▁Uni šti o ▁si_bs ▁im ▁sku tere ▁za_bs ▁vod u . ▁Is pr s kali ▁su_bs ▁nas_bs .
▁Go s po đa ▁vam_bs ▁živi ▁ovdje ? ▁Za_bs d nji h ▁šest ▁mje se ci_bs .
▁- ▁En di_bs , ▁pazi !
▁Šta_bs ▁je_bs ▁onda ▁potrebno ?
▁Nema s ?
▁Po_bs tegn i ▁van ▁Jack a ▁Carter a ▁i_bs ▁pogleda j .
▁Č ak ▁i_bs ▁uz ▁rekla me_bs .
▁Lo tt , ža o ▁mi_bs ▁je_bs .
▁Mislim ▁da_bs ▁to_bs ▁nije_bs ▁dobro .
▁Možete ▁li_bs ▁da_bs ▁pro_bs ko_bs ment ari še te_bs ▁u_bs bi_bs stvo ▁Anne ▁Scott ?
▁" I ▁lag ano ▁je_bs ▁do_bs šla ▁kraj ▁njega , "
▁- ▁Op et ▁treba_bs š ▁prijevoz ?
▁I_bs ▁za_bs ▁Dže ni_bs ▁je_bs ▁to_bs ▁bilo_bs ▁strašn o .
▁Možemo ▁da_bs ▁vam_bs ▁pomogne mo_bs .
▁La na_bs , ▁tres eš ▁se_bs .
▁Du go ▁nije_bs ▁bila ▁tak va_bs .
▁Da_bs ▁li_bs ▁si_bs ▁siguran ▁na_bs ▁to_bs j ▁lokacij i ?
▁Put ▁je_bs ▁tra ja_bs o ▁du že_bs ▁nego ▁što_bs ▁sam_bs ▁očekiva o .
▁Bar ▁mi_bs ▁dozvoli ▁da_bs ▁ti_bs ▁kup im_bs ▁avion sku ▁kartu .
▁Mogu ▁da_bs ▁ti_bs ▁da_bs m ▁mali ▁sa_bs vet . ▁I_bs di_bs ▁i_bs ▁na_bs đi ▁svoje ▁pri_bs če_bs .
▁Nema mo_bs ▁ništa ▁osim ▁mor nar skih ▁p jes ama .
▁Ta ▁je_bs ▁lu dos t ▁sva ▁do_bs ▁njega .
▁Ako ▁ga_bs ▁ti_bs ▁ne_bs ćeš ▁ubiti , ▁ja_bs ▁ho ću_bs .
▁A_bs ▁čak ▁se_bs ▁ni_bs ▁ne_bs ▁tru dim .
▁Iz vu ci_bs ▁ce mo_bs ▁te_bs ▁odavde , ▁dobro ?
▁U_bs ću_bs ti_bs , ▁Jen n .
▁Možda ▁se_bs ▁ob la_bs či_bs ▁malo ▁ot ka_bs čen o , ▁ali_bs ▁to_bs ▁je_bs ▁ne_bs mo_bs gu će_bs .
▁Ko je_bs ▁že ne_bs ?
▁I_bs ▁šta_bs ▁ti_bs ▁se_bs ▁dogodilo ▁sa_bs ▁se_bs stro m ?
▁Nan sal , ▁do_bs đi ▁da_bs ▁mi_bs ▁pomogne š ▁oko ▁ovog ▁si_bs ra_bs .
▁Z bun jena ▁sam_bs , ▁što_bs ▁se_bs ▁meni ▁ne_bs ▁događa ▁če sto ...
▁Ho cu_bs ▁reci , ▁ako_bs ▁stvari ▁i_bs du ▁loše , ▁Marcus , ▁treba_bs š ▁mi_bs ▁reci .
▁Hvala ▁ti_bs .
▁Dis tor zi_bs je_bs ▁na_bs ▁visok o po jas nim_bs ▁ frekven cija ma_bs .
▁I_bs dio te_bs , ▁zar ▁ne_bs ▁vidiš ▁šta_bs ▁se_bs ▁događa ▁ovde ?
▁I_bs ▁dalje ▁postoji ▁de_bs o ▁Le ksa ▁koji_bs ▁može ▁da_bs ▁se_bs ▁bor i .
▁Još ▁nešto ?
▁zi li_bs jene , ▁sta ▁to_bs ▁radi s ?
▁To_bs ▁ne_bs ▁može ▁biti_bs ▁to_bs .
▁Na_bs pa o ▁ga_bs ▁je_bs ▁mas k irani ▁go la_bs ć ?
▁Evo , ▁30. ▁ sept em bar .
▁U_bs ▁redu , ▁Te de .
▁Hoćeš ▁da_bs ▁molim ?
▁Pi še ▁na_bs ▁njen om_bs ▁zdravstven om_bs ▁kar ton u .
▁70 00 ▁ljudi ▁godišnj e ▁um re_bs ▁zbog ▁doktor ke ▁gre ške .
▁Trebal o ▁bi_bs ▁da_bs ▁nos is ▁vise ▁od_bs ▁jednog ▁dolara ▁De j vide .
▁U_bs ▁redu , ▁ali_bs ▁kad_bs ▁je_bs ▁sredi mo_bs , ▁u_bs ba ci_bs ćeš ▁je_bs ▁u_bs ▁na_bs stup , ▁je_bs ▁li_bs ▁tako_bs ?
▁Plus , ▁por ast ▁van da_bs liz ma_bs , ▁tri ▁u_bs ce_bs nika ▁su_bs ▁nesta la_bs .
▁Ne_bs ▁usu đ ujem ▁se_bs ▁da_bs ▁osta vim ▁pro_bs klet i ▁ma č ▁neza šti će_bs n .
▁Ne_bs sta la_bs ▁je_bs ▁na_bs ▁de_bs vet ▁mje se ci_bs .
▁Ok , ci_bs sto ▁je_bs .
▁- Me ni_bs ▁moj_bs ▁kaže ▁da_bs ▁je_bs ▁pravi .
▁Sebastian ▁Blo od ...
▁Zdravo , Ba di_bs .
▁Moja ▁je_bs ▁ve ca_bs .
▁Uz mite ▁št ito ve_bs , ▁op re_bs mu ▁i_bs ▁sve_bs ▁što_bs ▁možete ▁uzeti .
▁I_bs ▁u_bs šla ▁sam_bs , ▁ok ren ula ▁se_bs ▁i_bs ▁tamo ▁je_bs ▁bila ▁-- ▁savršen a ▁vjen ča nica .
▁Grupo , ▁pov la_bs čenje .
▁" N je_bs go vo ▁ime ▁je_bs ▁bilo_bs ▁policaj ac ▁Ro land ▁Ta ver ner " ▁iz_bs ▁Her mos a ▁Beach , ▁California ..." ▁moj_bs ▁najbolj i ▁prijatelj ."
▁V la_bs da_bs ju_bs ća_bs ▁D PS ▁osjeća ▁se_bs ▁sigur na_bs , ▁jer ▁pre_bs pirk e ▁i_bs ▁apa ti_bs ja_bs ▁pod ri va_bs ju_bs ▁moguće ▁izazov e .
▁Što ▁je_bs ▁to_bs ▁s_bs ▁vam_bs a , ▁mom cima ▁u_bs ▁Charles town u ?
▁Total no_bs ▁po_bs m ra_bs čenje ▁s_bs r ca_bs ." ▁O_bs ▁Bo ? ▁e , ▁...
▁- ▁Zar ▁ne_bs ▁možeš ▁ovdje ▁op rati ?
▁Ti_bs ▁uz mi ▁nos ila , ▁ja_bs ▁cu ▁za_bs ▁radio ▁i_bs ▁da_bs ▁prijav im_bs ▁ovo_bs .
▁Od ras la_bs ▁sam_bs ▁s_bs ▁mi_bs š lju , ▁da_bs ▁moram ▁na_bs por no_bs ▁radi ti_bs , ako ▁želim ▁zaradi ti_bs ▁nešto ▁novac a .
▁Samo ▁želim ▁da_bs ▁sa_bs stavi m ▁test ament . ▁Test ament , ▁ha ?
▁I_bs ▁kao_bs ▁za_bs d nja ▁dana s , ▁miss ▁Ka link a !
▁- ▁V rlo ▁ vjerojatn o .
▁S_bs OL ON , ▁H T JE LA ▁ BI H ▁ RA Z GO VAR ATI ▁S_bs ▁TO B OM .
▁Os ec ace te_bs ▁la gan ▁bol .
▁Zdravo , ▁Van da_bs .
▁- ▁Ne_bs ▁sje ča m ... ▁ . ▁- ▁Ako ▁je_bs ▁mogla ▁pod nije ti_bs ▁ona , ▁mogu_bs ▁i_bs ▁ja_bs !
▁- ▁ Ć ut - a , ▁vas_bs ▁dvoj e !
▁Ne_bs ▁želim ▁da_bs ▁polici ji_bs ▁prijav e ▁moj_bs ▁nesta nak .
▁10 ▁J .
▁Ti_bs ! ▁Ti_bs !
▁Ho ćemo ▁se_bs ▁ven ča ti_bs ▁kad_bs ▁ja_bs ▁na_bs pun im_bs ▁18 ?
▁Pogledaj ▁me_bs .
▁Ja_bs ▁sam_bs ▁iz_bs ▁ju go za pad nog ▁Bro ok ly na_bs !
▁To_bs ▁pri_bs pada ▁ njo j !
▁Od govori !
▁Oh , ▁to_bs ▁bi_bs ▁bilo_bs ▁fino .
▁I_bs ▁mesto ▁da_bs ▁pre_bs uz mem ▁odgovornost ▁za_bs ▁sve_bs ▁moje ▁gre ske , ▁ja_bs ▁sam_bs ▁kriv io ▁tebe .
▁Sranje , ▁čak ▁ni_bs ▁Na_bs tso ▁nije_bs ▁sko čio ▁tako_bs ▁visok o .
▁Izgleda š ▁kao_bs ▁kom pozit or ?
▁- Ko d ▁ku_bs će_bs ▁sam_bs .
▁To_bs ▁je_bs ▁ tor ba ▁dio ▁kole k cije ▁kao_bs ▁i_bs ▁kar te_bs .
▁U_bs vek ▁sam_bs ▁radio ▁sam_bs , ▁niko ▁sem ▁mene ▁nije_bs ▁zna o .
▁- D už nik ▁sam_bs ▁ti_bs ▁što_bs ▁si_bs ▁se_bs ▁sa_bs ž ali la_bs ▁na_bs ▁mene .
▁To_bs ▁je_bs ▁glavni ▁grad ▁cita vog ▁svijet a . ▁Ta mo_bs ▁postoje : ▁ ova_bs ▁Bi jela ▁ku_bs ca_bs . ▁I_bs ▁ ova_bs ▁mental na_bs ▁institucija .
▁Hej , ▁sluša j , ▁dušo , ▁koliko ▁je_bs ▁ovo_bs ▁lu do ?
▁TO ▁JE ▁TO . ▁S_bs ADA ▁LA Z NI ▁N AP AD .
▁Do_bs đi , ▁Na_bs zi_bs .
▁Daj ▁nešto ▁da_bs ▁mu ▁ve žem o ▁oči ! ▁Šta_bs ▁to_bs ... !
▁Ali_bs ▁su_bs ▁za_bs tvor ili_bs ▁studi o .
▁Za_bs kle o ▁si_bs ▁se_bs ▁da_bs ▁ćeš ▁ služ iti_bs ▁i_bs ▁št iti_bs ti_bs .
▁Drago ▁mi_bs ▁je_bs ▁što_bs ▁smo_bs ▁vas_bs ▁na_bs šli .
▁Vi ▁Amerika nci ▁voli te_bs ▁misli ti_bs ▁za_bs ▁sebe ▁da_bs ▁ste_bs ▁direkt ni_bs .
▁- Ne ▁mogu_bs ▁rizik ovati ▁da_bs ▁te_bs ▁izgubi m .
▁- ▁Iz vr s no_bs .
▁Svi ▁su_bs ▁zna li_bs ▁za_bs ▁mene , ▁zar ▁ne_bs ?
▁Žao ▁mi_bs ▁je_bs ▁što_bs ▁sam_bs ▁do_bs šla ▁ ova_bs ko_bs , ▁ali_bs ▁ne_bs ▁ja_bs v lja ▁se_bs ▁na_bs ▁telefon , ▁pa_bs ...
▁O_bs bu stavi ▁pri_bs ču ▁odmah .
▁A_bs jde , ▁hvala ▁ti_bs ...
▁Ba bl sam ▁je_bs ▁10 , ▁Bi f ste j k , ▁7 ▁Vou t ▁Bo j , ▁6, ▁Ker i ▁Pe č , ▁12.
▁O_bs sjeća m ▁da_bs ▁smo_bs ▁s_bs lično g ▁du ha .
▁Nikad ▁nisi ▁bio_bs ▁pro_bs gon jen ▁bak lja ma_bs !
▁Oh , ▁ne_bs , ▁Bi an_bs ca_bs , ▁molim ▁te_bs .
▁Treba ▁oba vesti ti_bs ▁K le_bs opa tru , ▁šta_bs ▁se_bs ▁dešava .
▁Pr vo ▁F isk , ▁onda ▁Co t ton mouth .
▁Zašto ▁stalno ▁la že_bs š ?
▁Ne_bs ću_bs ▁da_bs ▁te_bs ▁pov re_bs dim . ▁Ne_bs ću_bs ▁da_bs ▁te_bs ▁pov re_bs dim .
▁O_bs NA ▁TA MO , ▁JE ▁NA ▁ TR Z IST U ▁O_bs KO ▁ GO DI NU ▁D ANA ▁ZA ▁O_bs KO ▁27. 5 ▁M IL ION A . ▁ AKO ▁S_bs ADA ▁ DATE ▁P ONU DU , ▁ VER OV AT NO ▁ BI STE ▁M OG LI ▁DA ▁JE ▁DO B IJE TE ▁ZA ▁O_bs KO ▁19. 5 ▁M IL .
▁Drug ar , ▁to_bs ▁je_bs ▁proces .
▁Vrati ▁se_bs ▁na_bs ▁spa vanje ▁i_bs ▁dobro ▁raz misli ▁ tko ▁je_bs ▁plati o ▁tu ▁kući cu_bs ▁na_bs ▁ob ali !
▁- ▁Ve ć ▁po_bs či_bs njem ▁da_bs ▁mr zim ▁sam_bs ▁sebe .
▁Pro š le_bs ▁godine , ▁u_bs ▁ovoj ▁regi ji_bs ▁o_bs stva ren o ▁je_bs ▁ 290 ▁milion a ▁e ura ▁na_bs ▁osnov u ▁u_bs plat a ▁putem ▁mobil nih ▁telefon a .
▁D ne_bs vna ▁so ba ▁nam ▁je_bs ▁sin o ć ▁bila ▁kao_bs ▁da_bs ▁je_bs ▁sv rati o ▁Dže k son ▁Po_bs lok .
▁- Ni je_bs ▁h tio ▁reći , ▁ali_bs ▁želi ▁po_bs pri ča ti_bs ▁s_bs ▁vam_bs a ▁lice m ▁u_bs ▁lice .
▁Vrati ▁se_bs .
▁ ALI ▁N JI HO VO ▁N AJ D RA ZE ▁Z LO D JE LO : ▁N AB IJA NJE ▁ SH ELL EY JE VE ▁G LA VE ▁U_bs ▁ NJE G OV U ▁N AP RT N JA C U .
▁Dobro , ▁se_bs st .
▁- ▁Moramo ▁na_bs trag .
▁Od lu čio ▁je_bs ▁da_bs ▁nas_bs ▁po_bs ni_bs zi_bs ▁svojim ▁pre_bs zi_bs rom .
▁Boy , ▁usta ni_bs .
▁Po_bs slov ni_bs ▁pregled : ▁Hrvatsk a ▁će_bs ▁ vrš iti_bs ▁privat iz aciju ▁brod o grad il išta
▁Rich ▁je_bs ▁jos ▁na_bs ▁operacij i .
▁" O ve_bs ▁ću_bs ▁se_bs ▁ist ine ▁Ja_bs ▁ držati " ▁– ▁re če_bs ▁On :
▁Hoćeš ▁da_bs ▁vidim ▁kako_bs ▁je_bs ▁na_bs pol ju_bs ?
▁Pa_bs ▁kad_bs ▁završi te_bs ▁sa_bs lat , ▁tad ▁spo min ji_bs te_bs ▁Allaha ▁sto je_bs ći_bs , ▁i_bs ▁sje de ći_bs ▁i_bs ▁na_bs ▁bok ovima ▁vaš im_bs . ▁Pa_bs ▁kad_bs ▁bude te_bs ▁sigur ni_bs , ▁tad ▁obavlja jte ▁sa_bs lat .
▁G la_bs dan ▁sam_bs .
▁Reci te_bs ▁mi_bs ▁onda ▁ne_bs sto ▁sto ▁je_bs .
▁Kre ni_bs .
▁Č ak ▁i_bs ▁kad_bs ▁nema š ▁šta_bs ▁da_bs ▁izgubi š , ▁ti_bs ▁si_bs ▁slab .
▁Nema ▁ih ▁više_bs .
▁Svi ▁na_bs ▁svoj a ▁mjesta .
▁Chloe , ▁radi ▁samo_bs ▁što_bs ▁br ze ▁mo zes .
▁Samo ▁želi ▁reci ▁nekoliko ▁ rije ci_bs .
▁Sta ću_bs ▁na_bs ▁para liz ovan e ▁no ge ▁već ▁u_bs ▁ sled eć oj ▁scen i .
▁Svet sku ▁pokr ive nost ▁tele vi_bs zi_bs jske ▁intervju e .
▁Za_bs ▁to_bs ▁sam_bs ▁ja_bs ▁kriv a .
▁Je_bs ▁li_bs ▁She ba ▁još ▁uvijek ▁živ a ?
▁- Ho ward e , ▁molim ▁te_bs ...
▁Ob ja_bs v ljeno ▁je_bs ▁u_bs pozor en je_bs ▁na_bs ▁sva ▁i_bs mena ▁kojima ▁se_bs ▁Port er ▁koristi o .
▁Nikad a ▁ne_bs ▁idem ▁tra jek tom .
▁O_bs t ku_bs d ▁ru ke ▁u_bs ▁fri ži der u '
▁Šta_bs ▁ako_bs ▁neko ▁pro_bs govori ?
▁Od bija š ▁i_bs ▁li_bs jek ove ▁protiv ▁boli ?
▁Pa_bs ▁zašto ▁ne_bs ▁mogu_bs ▁da_bs ▁ih ▁č ujem ?
▁Iz v ješ_bs taj ▁Global ne_bs ▁konkurent nosti ▁oc jen ju_bs je_bs ▁ ekonomsk e ▁uvjete ▁u_bs ▁125 ▁zemalja ▁šir om_bs ▁svijet a . ▁[ S EF ]
▁Još ▁malo ▁na_bs prije d .
▁Ali_bs ▁pret post avljam ▁da_bs ▁taj ▁ured ja_bs j ▁koji_bs ▁nas_bs la_bs ▁agent ica ▁Du n ham ... ▁je_bs ▁izvor ▁pul sa !
▁Ne_bs ▁mislim ▁da_bs ▁ću_bs ▁otići ▁kući ▁večer as .
▁A_bs ▁onda , ▁za_bs misli te_bs !
▁Moj ▁pun ac ▁ce ▁biti_bs ▁s_bs retan ▁sto ▁imamo ▁kup ca_bs ▁s_bs ▁A_bs me_bs rick im_bs ▁dolar ima_bs .
▁O_bs prost i , ▁a_bs ▁što_bs ▁ćemo ▁s_bs ▁In gra ssi jom ?
▁Ko ▁ka ze ▁da_bs ▁je_bs ▁ lop ov ?
▁Onda ▁se_bs ▁ne_bs ▁bi_bs ▁raz lik ovali ▁od_bs ▁Um ere njaka .
▁Šta_bs , ▁iz_bs ▁pokr eta ▁ot por a ?
▁- ▁Je_bs sam .
▁Do_bs da_bs š ▁taj ▁rezultat ▁svojim ▁za_bs pa ža njima ▁i_bs ▁pro_bs meni š ▁hipo te_bs zu .
▁Mislil a ▁sam_bs ▁da_bs ▁će_bs ▁ti_bs ▁pri_bs jati ▁hlad no_bs ▁pi će_bs .
▁- ▁Kao ▁po_bs nud u ▁Po_bs moni , ▁i_bs ▁kao_bs ▁gest ▁dobre ▁vol je_bs ▁prema ▁narod u .
▁Pu no_bs ▁kuka š ▁zbog ▁mene , ▁Bru ce_bs . ▁Do_bs s adi lo_bs ▁mi_bs ▁je_bs ▁više_bs .
▁- ▁Sada , ▁da_bs .
▁Mislim ▁da_bs ▁je_bs ▁rec ▁o_bs ▁pre_bs kret nici .
▁Naj isk ren iji dio ▁tijela , koj ine ▁bi_bs ste po godi li_bs ▁su_bs ▁no ge .
▁Je_bs ▁li_bs ▁to_bs ▁bio_bs ▁Con nor ?
▁Možda ▁ja_bs ▁ne_bs ▁želim ▁novi ▁put !
▁Gdje ▁je_bs ▁glavni ▁pi rot ehn ič ar ?
▁Kad ▁sam_bs ▁bila ▁dije te_bs ▁mama ▁mi_bs ▁je_bs ▁rekla ▁da_bs ▁imam ▁veliki ▁pod bra dak . ▁I_bs ▁da_bs ▁se_bs ▁zbog ▁toga ▁ne_bs ▁svi đa m ▁de_bs ch ki ma_bs .
▁- O v dje ▁su_bs ▁i_bs ▁mom ci_bs ▁iz_bs ▁Fre s no_bs a .
▁- ▁Iza ći_bs ću_bs ▁iz_bs ▁Be le_bs ▁ku_bs će_bs ▁sa_bs ▁ovim ▁u_bs ▁ru kama ?
▁Ovo ▁ne_bs ▁ rade ▁ku_bs cep az itelj i .
▁Men i ▁treba_bs ▁pol uv rije me_bs .
▁Možeš ▁li_bs ▁da_bs ▁otvori š ▁neki ▁ulaz ▁u_bs ▁kontrol ni_bs ▁cent ar ?
▁Ako ▁dovoljno ▁dugo ▁gleda š ▁u_bs ▁pro_bs rez ▁učini ćeš ▁da_bs ▁se_bs ▁pla va_bs ▁linij a ▁po_bs ja_bs vi_bs .
▁- ▁Nije ▁stvar ▁u_bs ▁tome ▁kako_bs ▁po_bs čne s ▁i_bs gru ▁nego ▁kako_bs ▁ju ▁za_bs vr sis .
▁Ne_bs ▁znam_bs . ▁" S re_bs ća_bs ▁pre_bs ti_bs ▁hra bre . ▁"
▁Upravo ▁sam_bs ▁prolaz io , ▁a_bs ▁še rif ▁mi_bs ▁je_bs ▁rekao ▁da_bs ▁mogu_bs ▁da_bs ▁s_bs vrat im_bs ... ▁kad_bs ▁pož elim .
▁Kol ica ? ▁Pri je_bs ▁će_bs ▁ ugu ši ti_bs ▁dije te_bs !
▁Mr zim ▁što_bs ▁pre_bs ki dam ▁ovaj ▁než an_bs ▁trenutak , ▁ali_bs ▁zar ▁ti_bs ▁nema š ▁u_bs tak mi cu_bs ▁da_bs ▁o_bs dig raš ?
▁Rekla ▁sam_bs ▁da_bs ▁će_bs ▁nešto ▁už as no_bs ▁da_bs ▁se_bs ▁des i !
▁- ▁Pro pa lica ▁ju ▁ne_bs ▁bi_bs ▁potroš io .
▁Sa t ▁je_bs ▁sat .
▁Moraš ▁sluša ti_bs .
▁- ▁Me kla ude .
▁Zar ▁je_bs ▁po_bs če_bs la_bs ▁noć ▁veš tica ?
▁I_bs ▁ja_bs ▁bi_bs ▁trebao ▁plati ti_bs ▁za_bs ▁to_bs .
▁- Ja ...
▁S_bs vaka ko_bs , ▁sve_bs ▁sto ▁je_bs ▁a_bs meri cka ▁ar mija ▁u_bs cin ila ▁u_bs ▁Av gan istan u ▁i_bs ▁Irak u ▁je_bs ▁mnogo ▁gore ▁od_bs ▁on_bs oga ▁sto ▁je_bs ▁s_bs rp ska ▁vo jska ▁ik ada ▁u_bs cin ila ▁na_bs ▁Ko so vu .
▁- Da .
▁Gdje ▁je_bs ▁Mur iel ?
▁Ti_bs ▁si_bs ▁total no_bs ▁lu da_bs .
▁Osta li_bs ▁smo_bs ▁sam_bs i .
▁bi_bs će_bs ▁u_bs ▁redu .
▁Samo ▁tako_bs .
▁Svi ▁sto peri ▁ ova_bs ko_bs ▁ rade .
▁Ali_bs ▁možda ▁imamo ▁novi ▁ trag .
▁Kaž e ▁da_bs ▁je_bs ▁važno .
▁" U kra de š ▁li_bs ▁mi_bs ▁još ▁jedan ▁rece pt ▁ima_bs ▁da_bs ▁te_bs ▁prov u čem ▁kroz ▁do_bs data k ▁za_bs ▁m lje ven je_bs ▁na_bs ▁tvoj om_bs ▁ku_bs hin j skom ▁profesional nom ▁miks er u ."
▁Sa s vim ▁sam_bs ▁joj ▁do_bs ra_bs sta o , ▁mas ni_bs ▁se_bs ron jo .
▁- H u tten ▁je_bs ▁paz ljiv ▁i_bs ▁pe dan tan ▁profesional ac .
▁Pa_bs , ▁zna ▁li_bs ▁De cker ▁sada ▁da_bs ▁mu ▁je_bs ▁žena ▁ubije na_bs , ▁a_bs ▁dije te_bs ▁o_bs te_bs to ?
▁Da_bs ▁li_bs ▁jos ▁neko ▁zi vi_bs ▁sa_bs ▁vam_bs a ?
▁Že lite , ka_bs o š tos u , ▁ham burg er ... ▁che ese burg er , d vo stru ko_bs
▁Pos le_bs ▁ćemo ▁da_bs ▁igra mo_bs ▁kar te_bs .
▁Slušaj , ▁imaš ▁dobro g ▁partner a .
▁Da_bs . ▁On ▁je_bs ▁pravo , ▁pa_bs ▁le vo .
▁Un u tra , ▁možda . ▁To_bs ▁je_bs ▁to_bs .
▁- Do bili ▁su_bs ▁nas_bs ▁sto .
▁Hu a fu .
▁Ko je_bs ▁iz_bs ne_bs na_bs đen je_bs . ▁Lo ci_bs ra_bs li_bs ▁smo_bs ▁auto ▁koji_bs ▁je_bs ▁Fle ming ▁vozi o .
▁Od ▁koko s ovi h ▁pal mi ▁i_bs ▁smo_bs k vi_bs nih ▁sta bala ▁i_bs ▁kor al j nih ▁p ješ_bs ča nih ▁pla ža ▁i_bs ...
▁Kri lo_bs !
▁Ing eli ▁i_bs ▁Lind i ▁nije_bs ▁dobro .
▁Samo ▁da_bs ▁na_bs zdrav im_bs .
▁U_bs ▁nes vijesti ▁sam_bs ▁i_bs ▁treba_bs ▁mi_bs ▁o_bs živ lja vanje .
▁Kad ▁se_bs ▁be ba ▁rod i , ▁zna ćeš ▁šta_bs ▁treba_bs ▁da_bs ▁radiš .
▁A_bs jde ▁proba j ▁sa_bs ▁vode nim_bs ▁boj ica ma_bs .
▁Var as ▁se_bs ▁ako_bs ▁misli s ▁da_bs ▁poslije ▁nas_bs ▁ne_bs ce_bs ▁prije ci_bs ▁na_bs ▁vas_bs .
▁Že na_bs ▁te_bs ▁izda la_bs .
▁- Š ta_bs ▁god ▁je_bs ▁os vesti .
▁De ly sia ?
▁Ru ke ▁su_bs ▁mi_bs ▁krv ar ile , ▁ali_bs ▁nisam ▁presta ja_bs o .
▁Kaž e ▁da_bs ▁je_bs ▁tip ▁prijav io ▁gubi tak ▁list i ća_bs ▁iz_bs ▁da_bs bro ve_bs ▁bra ne_bs .
▁M la_bs da_bs ▁prost itu tka ▁iz_bs ▁London a ▁bila ▁je_bs ▁novi tet ▁u_bs ▁Na_bs pul ju_bs .
▁Na_bs pos li_bs jet ku_bs , ▁znate , ▁du g ▁je_bs ▁put ▁pred ▁nama ▁Pokuša va_bs jući ▁sti ći_bs ▁Kin u , ▁pa_bs ▁Evrop u ▁Ili , ▁ako_bs ▁već ▁ho će_bs te_bs , ▁a_bs meri čka ▁avion ska ▁komp a nija ▁South - W est ▁ima_bs ▁4 17 ▁avion a
▁Ne_bs ▁zapošljava te_bs ▁dovoljno ▁žena ▁na_bs ▁više_bs ▁pozicij e ▁u_bs ▁kamp a nji .
▁U_bs ▁tom ▁kontekst u , ▁Ab bas ovo ▁put ovanje ▁u_bs ▁Tur sku ▁je_bs ▁od_bs ▁na_bs ro či_bs te_bs ▁važno sti_bs , ▁komen ti_bs ra_bs ▁Euro new s ▁u_bs ▁u_bs tor ak , ▁na_bs vodeći ▁da_bs ▁je_bs ▁Gu l ▁već ▁na_bs ja_bs vio ▁svoju ▁podršk u .
▁Vid jeli ▁su_bs ▁je_bs ▁jutro s ▁na_bs ▁ben zi_bs skoj ▁kod ▁Phil ly ja_bs .
▁Zna ▁dosta ▁na_bs ci_bs sta ▁kru p nih ▁z v jer ki ▁koji_bs ▁vole ▁da_bs ▁se_bs ▁ druž e ▁sa_bs ▁I_bs ju_bs di_bs ma_bs ▁iz_bs ▁pozor išta .
▁- ▁Iz ne_bs na_bs dit ▁če mi ▁ih .
▁Za_bs vrš imo ▁ovo_bs ▁jednom ▁za_bs ▁sva g da_bs .
▁Mora ću_bs ▁da_bs ▁da_bs m ▁ovom ▁idiot u ▁da_bs ▁vodi ▁ vijesti .
