▁Ini ▁sebab nya ▁kau ▁meno lak ▁ke du du kan ▁di ▁Ho s pita l ▁Da e je on ▁dan ▁kem ari ?
▁Ray ▁sedang ▁bekerja .
▁Kamu ▁tak ▁tahu ▁dia ▁takut kan ▁a pi ?
▁Ham pir ▁masa ▁untuk ▁makan ▁malam .
▁Kenapa ▁awak ▁tak ▁cas ▁i a ?
▁- ▁Kelly ▁dah ▁u saha ▁ber sungguh .
▁Ia ▁tidak ▁boleh ▁dilakukan .
▁Papa r ▁kedua - du a ▁ko lum ▁ta juk ▁dan ▁ala mat
▁Sa li _ n ▁Lo ka si ▁Pa u tan ▁Audio
▁Har i ▁ini ▁% l :% M ▁% p
▁- ▁Max ine .
▁Ta di ▁kita ▁seperti ▁ter bang .
▁Ja wa b ▁so alan ▁aku ▁du lu
▁Aku ▁akan ▁meng hen ti kan ▁per nika han ▁ini !
▁Kau ▁dia m . ▁saya ▁bu leh ▁ka wal ▁sendiri
▁Awak ▁ingat ▁saya ▁nak ▁per angkap ▁awak ▁lagi ?
▁Tak ▁boleh , ▁hari ▁si buk .
▁- ▁Tak nak .
▁Dia ▁juga ▁pe mi lik ▁resto ran ▁ni ▁Tapi ▁dia ▁selalu ▁hi lang .
▁Anda ▁mengatakan ▁sesuatu ▁seperti ▁" A pa ▁yang ▁mungkin ▁anda ▁lakukan ▁...
▁Har us ▁ada ▁kedua - du a nya .
▁Mari ▁ta nya ▁dalam ▁pan tri ▁dan ▁kemudian ▁buat ▁ke put us an .
▁Hey , ▁Harry , ▁saya ▁dah ▁dapat .
▁- ▁Kita ▁sudah ▁sa ling ▁ken al .
▁Wa jah mu ▁tidak ▁je lek .
▁Mac am ▁mana ▁mak ▁boleh ▁bercakap ▁tentang ▁dia ▁begitu ?
▁Te mbo k ?
▁Jadi ▁jangan ▁jadi ▁terlalu ▁ge mu k !
▁- ▁... ▁main ▁di ▁se ki tar ▁di ▁radio ▁ham ?
▁paper ▁size
▁Dengar ▁sini ▁baik - baik ▁jika ▁awak ▁tidak ▁dengar ▁saya ▁betul - be tul .
▁Ke ja p , ▁bi ar ▁aku ▁tun juk .
▁U ji ▁jika ▁ daemon ▁win bind d ▁dija lan kan ▁bila ▁pa kej ▁di pas ang .
▁Peng guna an : ▁m klo st + fo und
▁Tapi ▁i a ▁me mpe son akan ▁aku .
▁- ▁Saya ▁dalam ▁keadaan ▁tel anja ng .
▁Men gh ada pi ▁je nis ▁M H OD ▁(% d ) ▁yang ▁tidak ▁di keta hui ▁sem asa ▁meng hur ai ▁i Tu nes DB . ▁Aba ikan .
▁A ▁mu da , ▁kan ak - kan ak ▁yang ▁can tik .
▁Maka ▁Allah ▁menu run kan ▁se manga t ▁tena ng ▁ten ter am ▁kepada ▁( Na bi ▁Muhammad ) ▁dan ▁mengu at kannya ▁dengan ▁bantuan ▁ten tera ▁( ma la ikat ) ▁yang ▁kamu ▁tidak ▁melihat nya . ▁Dan ▁Allah ▁menjadi kan ▁ser uan ▁( s yi rik ) ▁orang - orang ▁kafir ▁ter ke ba wa h ▁( ka lah ▁dengan ▁se hina - hina nya ) , ▁dan ▁Kal ima h ▁Allah ▁( Is lam ) ▁ialah ▁yang ▁ter ting gi ▁( se lama - lama nya ) , ▁kerana ▁Allah ▁Maha ▁Ku asa , ▁lagi ▁Maha ▁Bij aks ana .
▁Te ta pi ▁ada ▁cara ▁lain ▁untuk ▁membuat ▁wa ng , ▁terlalu .
▁Men g gos ok nya ▁semua ▁sekali ▁li ang - li ang ▁ku lit ▁saya , ▁dan ▁an gin ▁antara ▁mata ▁saya ▁menge tuk ▁ma du ▁dalam ▁si kat ▁saya .
▁Ra lat : ▁% s : ▁Bi langan ▁med an ▁tidak ▁men cu kup i ▁dalam ▁bar is ▁% u .
▁Ta man ▁Sel atan ▁ke ▁sun gai .
▁G n ect
▁Jo m ▁!
▁Kita ▁berdua ▁tahu ▁kalau ▁mereka ▁sedang ▁ke ▁sini .
▁Tak ▁dapat ▁menu kar na ma ▁ime j :
▁Su nggu h ▁ kurang ▁a jar .
▁Nama ▁saya ▁A nak - H ong ▁Kong ...
▁Untuk ▁10 ▁bul an ...
▁- ▁Baiklah ▁ , ▁anda ▁tidak ▁si u man .
▁Aku ▁kata ▁tem bak .
▁Th read - Id ▁% d , ▁[ state ] ▁running , ▁det ach ed
▁Aku ▁katakan ▁kepada mu . ▁sebelum ▁fa jar ... ▁engkau ▁akan ▁meny ang kal ▁Aku ▁ti ga ▁kali .
▁Saya ▁nampak ▁dia ▁dalam ▁ber ita !
▁" Sa ya ▁tak ▁boleh ▁lakukan ▁ini ▁tanpa ▁bantuan ▁dan ▁kerja s ama ▁dari ▁wa kil ▁se ki an - sek ian ▁di ▁ja ba tan ▁polis ."
▁Saya ▁um ur ▁20.
▁Ren te tan ▁UTF -8 ▁tak ▁sah ▁dalam ▁fail ▁cor ak ▁'% s ' .
▁saya ▁tak ▁mahu ▁men jal ani ▁hidup ▁seperti ▁masa ▁lalu ▁lagi .
▁Ne nek ▁baru ▁saja ▁di ma kam kan ▁ke mar in !
▁" mah kama h ▁meng anggap ▁para ▁defend an ' ▁ter buk ti ▁ada ▁su mbang an ."
▁Hei , ▁Ar ch !
▁Folder ▁& ▁Sa mpah
▁Saya ▁tur ut ▁menang ▁sebuah ▁pi ala .
▁Anda ▁orang ▁le mah ▁"
▁Ia nya ▁bukan ▁fakt a ▁yang ▁dia ▁ psi ko tik .
▁Masa ▁is teri ,
▁Ke sala han ▁dari ▁Sar man
▁- ▁Call ▁me ▁fa tso .
▁Terima
▁Kalau ▁tak , ▁dia ▁akan ▁ter ima ▁an ca man ▁seperti ▁Ra ke sh .
▁Fa il ▁se ment ara ▁di buka : ▁% s
▁J eneral , ▁la por an ▁a wal ▁yang ▁di kel uar kan ▁oleh ▁SHA EF ▁mengatakan ▁Di vis yen ▁ke -10 1 ▁dah ▁berse pa h .
▁# ▁J ing le ▁ bell s , ▁Bat man ▁sme ll s , ▁Robin ▁la id ▁an ▁e gg !
▁Da lam ▁pada ▁itu ) ▁mereka ▁adalah ▁seperti ▁bat ang - ba tang ▁ka yu ▁yang ▁ter san dar ▁( ti dak ▁ter paka i ▁kerana ▁tidak ▁ada ▁pada nya ▁kekuatan ▁yang ▁di ke hen daki ) . ▁Mereka ▁( ker ana ▁merasa i ▁ber sa lah , ▁senti asa ▁dalam ▁keadaan ▁ce mas ▁sehingga ) ▁meny ang ka ▁ti ap - ti ap ▁je ritan ▁( ata u ▁ri uh ▁rend ah ▁yang ▁mereka ▁dengar ) ▁adalah ▁untuk ▁memba haya kan ▁mereka .
▁Men ang ▁di ▁An u ge rah ▁Ne bula .
▁Apa ▁kau ▁rasa ▁dengan ▁Kau ▁yang ▁" Ba ru " ▁ni ?
▁... ▁untuk ▁bay angkan ▁dengan ▁siapa ▁saya ▁nak ▁hab is kan ▁seu mur ▁hidup ▁saya ▁ini . .
▁Mungkin ▁ini ▁orang nya .
▁Lihat lah ▁... ▁foto ▁anda .
▁Itu ▁ke ▁yang ▁awak ▁katakan ?
▁Saya ▁membawa ▁la por annya .
▁Adakah ▁kita ▁tetap ▁dengan ▁wa ng ▁tun ai ▁?
▁Gu y , ▁dari ▁mu la ▁awak ▁ber lum ba ▁di ▁In dy ▁Light s , ▁pernah kah ▁awak ▁ber mi mpi ▁akan ▁ber dir i ▁di ▁pen tas ▁ini ?
▁Se bab ▁ali en ▁itu ▁datang ▁ke ▁sini ...
▁Dan ▁( ing at lah ) ▁Allah ▁Maha ▁Ku asa ▁atas ▁ti ap - ti ap ▁sesuatu .
▁Kau ▁takkan ▁keluar ▁temu ja nji ▁wa lau ▁ny awa ▁kau ▁ber gan tung ▁pada nya .
▁Ke cil
▁tapi ▁mungkin ▁ada ▁satu ▁pel u ang ▁disini .
▁Pe ny ele ng gara
▁Sel agi ▁ba dan ▁em as ▁Tuan ▁Gu ru ▁masih ▁ut uh ...
▁Kamu ▁kena ▁ter ima ▁saya ▁di ▁ha da pan ▁seluruh ▁dunia
▁Ber ikan ▁kad
▁Per tahan kan ▁Lord ▁Co ty s !
▁De e wan ▁Sa he b !
▁Tu kan g ▁uru t ? ▁- ▁Ya
▁Tuan , ▁kalau ▁di ▁ ang kas ale pas ▁pen ▁found a in ▁pen ▁mata ▁bola ▁tak ▁boleh ▁digunakan , ▁kenapa ▁ ang kas a wan ▁tak ▁gun akan ▁pense l ▁je ?
▁Ay uh , ▁Che t .
▁Saya ▁akan ▁pada m kan ▁ingat an ▁awak ▁dan ▁kembali kan ▁awak ▁ke ▁jalan ▁betul .
▁[ Art hur ] ▁Anda ▁dont ▁mempunyai ▁untuk ▁menu lis ▁sesuatu ▁bawah ▁menjadi ▁seorang ▁pe nya ir .
▁Ya , ▁tetapi ▁saya ▁bay angkan ▁saya ▁sedang ▁du duk ▁di ▁ha da pan ▁anda , ▁dan ▁jika ▁saya , ▁I . ▁..
▁Itu lah ▁ isti lah ▁orang ▁Amerika .
▁Awak ▁berada ▁di ▁tempat ▁yang ▁mena kut kan ▁seperti ▁yang ▁saya ▁bay angkan .
▁Mungkin ▁ini ▁semua ▁hanya ▁peng ali han ▁per hati an .
▁- Se benar nya ▁i a ▁dalam ▁ba hu ▁saya .
▁Dan ▁telah ▁me lib atkan ▁beberapa ▁je nis ▁masalah
▁- ▁Saya ▁boleh ▁tuli s ▁pe mbang kan gan .
▁Hei ▁ , ▁anak ▁la ki ▁- ▁la ki ▁ , ▁jika ▁ini ▁adalah ▁pen dek atan ▁anda ▁untuk ▁perempuan ▁ , ▁Anda ▁tidak ▁akan ▁menjadi ▁sangat ▁jauh ▁ .
▁Kenapa ▁kamp ung ▁ini ?
▁Awak ▁berdua ▁baik ▁jangan ▁ga nggu ▁saya ,
▁- ▁Kita ▁tak ▁tinggal ▁di ▁Bu lan !
▁- ▁Mereka ▁ga m bar ▁!
▁Di al ▁9 99 ?
▁Jangan ▁de kat ▁dengan ▁a we k ▁aku !
▁Si mi , ▁kamu ▁dah ▁mu la ▁menu lis ▁puis i ▁yang ▁bagus , ... ▁.. dan ▁lelaki ▁itu ▁macam ▁betul - be tul ▁w uju d .
▁Mari ▁kita ▁men ak luk ▁dunia
▁Dan ▁selamat ▁datang ▁ke ▁Grand ▁Pa ngo lin ▁Ar ms .
▁Jesus ▁Christ . ▁saya ▁tidak ▁tahu ▁di mana ▁awak ▁ambil ▁pen didi kan ▁awak ▁ini ▁bukan lah ▁dari ▁e jen ▁yang ▁pen uh ▁kad ang - ka dang ▁saya ▁fikir ▁awak ▁tau ▁banyak
▁" I a ▁mungkin ▁salah ▁seorang ▁kawan - ka wan ▁kamu ."
▁Anda ▁selalu ▁me mal ukan ▁saya .
▁Aku ▁sang ka ▁i a ▁dah ▁ter ba kar .
▁Oh , ▁i a ▁bukan ▁hanya ▁sebuah ▁bu ku .
▁W ise . T er ima ▁kasih .
▁Ber ikan ▁satu ▁kad ▁dari ▁de k
▁Aku ▁tak ▁dapat ▁beritahu ▁kau ▁ber apa ▁kali ▁aku ▁ber mi mpi ▁aku ▁na ik ▁li ft ▁ni .
▁Se baik ▁sahaja ▁dia ▁pergi , ▁anda ▁akan ▁ter per angkap ▁di ▁sini ▁selama ▁li ma ▁tahun ▁lagi .
▁Apa ▁yang ▁anda ▁lakukan ?
▁Aku ta hu .
▁W ang ▁yang ▁p ember i ▁pi nja man ▁akan ▁mem bela ▁ke ja hi lan
▁Apa ▁aku ▁ter ti dur ▁ta di ?
▁Kau ▁tak ▁ada ▁anak ▁ke ?
▁katakan ▁tentang ▁mol ly ▁walk er .
▁Bak at ▁yang ▁kamu ▁ada ▁ sungguh ▁besar .
▁Har us kah ▁kita ▁membunuh ▁wanita ▁ini ▁atau ▁bagaimana ?
▁Seperti ▁yang ▁dira nc ang ▁oleh ▁Jo ng ▁Ko ok , ▁Ji ▁Ho on ▁dis ing kir kan ▁kerana ▁buat ▁la por an ▁pal su .
▁A pro x ím ense ▁dan ▁mu la ▁sunt ikan .
▁Kamu ▁telah ▁berubah ▁a rah ▁banyak ▁se men jak ▁tu .
▁Nam pak nya ▁mereka ▁dapat i ▁kami .
▁Itu ▁dari ▁bu ku ▁Ma z mur .
▁/ ▁awak ▁tahu ▁bet apa ▁pe lik nya ▁ini ▁?
▁De ka ti ▁J ANG ▁Do ng - shi k ▁dan ▁cari ▁tahu ▁di mana ▁du it ▁dia .
▁aj ha ▁..
▁Per angkap ▁pela nc ong .
▁Ini lah ▁su mpah an ▁terakhir ▁Victor ▁Frank en stein .
▁Aku ▁mahu ▁kau ▁pergi ▁ambil ▁wa ng ▁itu .
▁Dan ▁tak ▁seorang ▁pun ▁ingin ▁mengatakan ▁apa ▁pun ▁di ▁telefon .
▁Doktor , ▁jika ▁kamu ▁perlu kan ▁se bar ang ▁per ala tan ▁atau ▁apa ▁saja . . ▁.. ▁i a ▁akan ▁di uru s kan ▁ser ta ▁mer ta
▁Be liau ▁baru - bar u ▁ini .
▁Kamu ▁semua ▁datang ▁te pat ▁pada ▁masa nya .
▁Tapi ▁itu ▁tak ▁ber mak na ▁kau ▁perlu ▁biarkan ▁i a ▁berlaku .
▁Dan ▁waktu ▁sub uh ▁apabila ▁i a ▁ter ang - ben der ang ,
▁Kom a nder . ▁/ ▁Re ally ?
▁- Sa ya ▁beritahu ▁lagi . ▁Saya ▁tak ▁ber fik ir .
▁Kir aan ▁berak hir .
▁En kri psi kan ▁fail
▁Bagaimana ▁jika ▁Pre as er ▁boleh ▁tahan ▁di ▁ ping gir ▁jalan ?
▁Kes eron o kan ▁pela jar ▁se ma kin ▁me mun cak
▁Ia ▁hanya ▁ko s me tik .
▁Semua ▁kereta ▁ke bal ▁berhenti .
▁Day ung ▁ke ▁kan an !
▁Peng ika tan ▁ ping gir ▁bila ▁di ser u , ▁akan ▁jalan kan ▁p erintah ▁shell ▁yang ▁di ken al pas ti ▁oleh ▁command 10
▁Tunggu ▁di sela mat kan .
▁Yeah .
▁Kamu ▁mahu ▁saya ▁mengha lau ▁awak .
▁Maks ud ▁saya , ▁s no kel ▁pun ▁dia ▁tak ▁pa nda i .
▁Ini ▁ag ak nya ▁rumah ▁dia .
▁" di ▁rumah , ▁ber bi sik ▁med an ▁un - di se mai .
▁Aku ▁tak ▁kh awa tir ▁tentang ▁tidur ▁atau ▁makan an ku
▁La mpu ▁me rah ▁sedang ▁meny ala .
▁Seperti nya ▁dia ▁perlu kan ▁bantuan ▁pak ar ?
▁Yang ▁men di dik ▁secara ▁ra sional .
▁Tidak ▁perlu ▁bi mbang .
▁Sa tu ▁ke hor ma tan ▁bagi ▁kamu ▁sebagai ▁pe ga wa i ▁polis , ▁hen ti kan ▁mereka !
▁Saya ▁akan ▁membuat ▁anda ▁aka un .
▁Aku ▁tak ▁peduli ▁apa ▁yang ▁Kau ▁ingin kan ▁tapi ▁Kau ▁bersama ▁kami ▁sekarang .
▁Tiada ▁ga m bar ... ▁Hanya ▁ini .
▁Ayah mu ▁adalah ▁war is ▁tak hta .
▁Maks ud ▁saya , ▁kita ▁ada ▁Bord en , ▁Liz zy , ▁sehingga ▁ke ▁Cra ne , ▁Ich ab od .
▁E SU ▁me landa ▁ hang out ▁sebelum ▁sub uh .
▁Kau ▁tahu ▁apa ▁in s ting ku ▁memberitahu ▁aku ?
▁Mereka ▁kata ▁awak ▁melakukan ▁hal ▁baik , ▁bahawa ▁awak ▁ada ▁kekuatan ▁is time wa .
▁Ma in kan ▁bun yi ▁bila ▁mes ej ▁ti ba
▁tiada ▁just ifik asi just ification text attr
▁Adakah ▁mereka ▁akan ▁mem benar kannya ?
▁Ini ▁adalah ▁a zi mat ▁lag enda ▁moj in ,
▁Saya ▁nak ▁minta ▁awak ▁lakukan ▁sesuatu ▁yang ▁mu dah .
▁Awak ▁fikir ▁ce rita ▁saya ▁tip u ?
▁Tapi ▁ak hir nya ▁mereka ▁dapat ▁juga .
▁Dan ▁sekarang , ▁We mble y . ▁Aku ▁juga ▁yang ▁melakukannya .
▁Data ng ▁pada . ▁Ia ▁bukan ▁kesalahan ▁Gun ner , ▁manusia .
▁Saya ▁belum ▁memba las ▁bu di ▁papa ▁dan ▁mama
▁Aku ▁baru ▁sahaja ▁nak ▁beritahu ▁kau , sa yang ku ▁dan ▁kehilangan ▁semua ▁orang ku
▁Kemudian ▁mengapa ▁awak ▁ber main ▁bi ngo ?
▁Saya ▁percaya ▁dengan ▁kebenaran , ▁te man ▁kita ▁akan ▁tahu ▁itu .
▁Kem bali , kem bali
▁Hanya ▁ada ▁satu ▁per atura n : ▁Men gal ahkan ▁untuk ▁di pa dan kan .
▁Saya ▁di mak lum kan ▁bahawa ▁bu aya ▁Man ▁mungkin ▁Mala ikat ▁Me mbu nu h
▁Ke kej angan ▁ot ot ▁pada ▁bahagia n ▁atas ▁tu bu h ▁dan ▁ka ki .
▁Fe e , ▁sy aba s .
▁Ini ▁simbol ▁keluarga ▁Way ne .
▁T UN AI :
▁Aku ▁memilih ▁mengha n cur kan mu .
▁Dan ▁Rub y ▁mempunyai ▁satu ▁sedikit .
▁Tur un , ▁Po ndo lem .
▁Jangan ▁beritahu ▁saya ▁bahawa , ▁pada ▁masa ▁itu ▁kita ▁akan ▁perlu ▁melihat
▁URI ▁S wi ft ▁ter ben tuk ▁ter uk .
▁Tak ▁ada ▁orang ▁yang ▁akan ▁peduli kan ▁cinta ▁kita
▁J eneral , ▁saya ▁tahu ▁apa ▁yang ▁kamu ▁buat ▁di ▁National ▁City .
▁Man if old ▁ku ant um . ▁Tak ▁pernah ▁dengar .
▁Kamu ▁adalah ▁yang ▁pa ling ▁tidak ▁men en tu ▁ , ▁Dan a , ▁tetapi ▁i a ▁adalah ▁kun ci .
▁Mari ▁kita ▁war na i ▁Rad ha
▁Yeah .
▁Awak ▁mungkin ▁I rish .
▁Barry , ▁kita ▁perlu ▁cari ▁Wall y .
▁Dia ▁pe mi mpi n ▁yang ▁ter uk .
▁dan ▁Ram ▁dengan ▁cepat ... ▁mele mpar ▁pe mot ong ▁rum put ▁dan ▁bo ng ka han !
▁Se ych elles , ▁Ru pe e
▁Sa pa ▁kata ▁kita ▁ber ta ma dun ▁lagi ?
▁Name
▁Tidak ▁ada ▁ja min an ▁dalam ▁kehidupan , ▁a bang .
▁- ▁Tak ▁apa , ▁saya ▁pergi ▁pu kul ▁dia .
▁- ▁Danny , ▁h ubung i ▁9 11 !
▁- ▁Ada ▁lagi ▁ke ?
▁Anda ▁lihat , ▁James ▁dan ▁saya ▁kedua - du a nya ▁baru ▁di be li ▁li ma ▁pintu ▁hat ch back ▁Jer man .
▁Kita ▁tak ▁boleh ▁tinggal kan ▁bi lik ▁ini .
▁Aku ▁tidak ▁perlu ▁se hat ▁untuk ▁me mu kul mu .
▁Sa tu , ▁mi mos a ▁tiada ▁alkohol ▁ini ▁hanya lah ▁ju s ▁ oren , ▁dan ▁dua , ▁saya ▁tak ▁boleh ▁minu m .
▁- ▁Saya ▁nak ▁dia ▁me mah ami ...
▁- ▁Kau ▁gi la . ▁mari .
▁Ny ata kan ▁le bar ▁default ▁( dalam ▁pik sel ) ▁bagi ▁not a ▁baru
▁Ra j , ▁orang ▁yang ▁saya ▁suka ▁boleh ▁panggil ▁saya ▁Chu t ki
▁.. bila ▁mereka ▁nampak ▁dik au .
▁/ ▁Ada ▁di ▁di ▁history ▁kau . .
▁Aku ▁juga ▁buat ▁sele pas ▁aku ▁tinggal kan ▁N SA .
▁Ber kela ku an ▁baik ▁dengan ▁pe lang gan .
▁Ka li ▁pertama ▁Saya ▁bertemu ▁dengan ▁kamu ▁kerana ▁saya ▁meninggalkan ▁awak , ▁awak ▁tidak ▁cinta ▁dengan ▁sesiapa ▁sahaja ▁dan ▁saya .
▁Ker ja ▁dah ▁bere s
▁- ▁Baiklah . ▁ay uh .
▁Aku ▁akan ▁menjadi ▁bang kai ▁jika ▁me luk akan ▁ha ti ▁dia ▁lagi
▁Ang in , ▁Aku ▁mengg endo ng mu ▁lama . ▁Mengapa ▁kau ▁tidak ▁bisa ▁tur un ▁dan ▁berjalan ▁dengan ▁ayah .
▁Fakt a , ▁18 ▁bul an ▁lalu ,
▁Dan ▁sesiapa ▁yang ▁memper se kut ukan ▁Allah ▁( den gan ▁sesuatu ▁yang ▁lain ) , ▁maka ▁sesungguhnya ▁i a ▁telah ▁melakukan ▁dos a ▁yang ▁besar .
▁Ba wa ▁juga ▁sena pan !
▁Ay uh !
▁Mo tos i kal nya ▁dah ▁tiada .
▁Bag i ▁kami , ▁awak ▁a mat ▁mu lia .
▁Kamu ▁ter je bak .
▁Jika ▁anda ▁mempunyai ▁apa - apa ▁idea , ▁i ▁saya ▁semua ▁tel inga .
▁Ia ▁bukan ▁apa ▁yang ▁awak ▁dapat ▁me mbu kti kan , ▁i a ▁adalah ▁apa ▁yang ▁orang ▁kata ▁mereka ▁ingat .
▁Aku ▁hanya ▁tidak ▁peduli ▁mati .
▁Maaf ... ▁by e .
▁Mereka ▁pasti ▁lu pa ▁tentang ▁ke ma langan ▁bot ▁itu ▁dua ▁bul an ▁le pas !
▁Kai ten ▁si ap ▁se dia . ▁Adakah ▁awak ▁lan car kan ▁kai ten ▁awak ?
▁la nya ▁me mbo ng kar ▁isi ▁ha ti mu .
▁Kau ▁datang ▁untuk ▁men curi ▁per ala tan ?
▁Ama ran : ▁% s ▁dija lan kan ▁sebagai ▁peng guna ▁"% s " ▁pada ▁hos ▁"% s ". ▁Te ta pi ▁x screen sa ver ▁mengu rus ▁papa ran ▁"% s " ▁yang ▁dija lan kan ▁peng guna ▁"% s " ▁pada ▁hos ▁"% s ". ▁O leh ▁kerana , ▁peng guna ▁yang ▁ber be za , ▁i a ▁tidak ▁akan ▁memba ca / menu lis ▁fail ▁~ / . x screen sa ver ▁yang ▁sama , ▁jadi ▁% s ▁tidak ▁dapat ▁ber fung si ▁dengan ▁baik ▁Anda ▁se pat ut nya ▁sama ▁ada ▁jalan - sem ula ▁% s ▁sebagai ▁"% s ", ▁atau ▁jalan - sem ula ▁x screen sa ver ▁sebagai ▁"% s ". ▁Mul a ▁sem ula ▁ daemon ▁x screen sa ver ▁sekarang ?
▁Anda ▁melakukan ▁hal ▁anda !
▁Ia ▁hidup ...
▁dan ▁mele ng ahkan ▁masa ▁mereka
▁Saya ▁adalah ▁seorang ▁yang ▁tidak ▁si u man .
▁- ▁Maaf ▁ag ak ▁lama . ▁- ▁Tidak .
▁Anda ▁tahu , ▁pen ja ra ▁tidak ▁sele sa .
▁Saya ▁perlu kan ▁bantuan ▁ke wanga n .
▁Aku ▁sangat ▁si buk ▁sekarang ▁ni .
▁In gin ▁anda ▁O RA Â  Ã I Ã ▁  ▁E , ▁H AR RY !
▁Ayah ▁saya , ▁dia ▁beritahu ▁saya ▁kalau ▁dia ▁dah ▁han cur kan ▁band ar ▁ini .
▁Kau ▁gadis ▁yang ▁baik , ▁bukan ?
▁Dia m lah ▁kau , ▁How l ▁tak ▁akan ▁datang
▁Ia nya ▁pe lik ▁untuk ▁beritahu ▁perkara ▁ini ▁pada ▁diri ▁sendiri , ... ... ... . ... ▁tapi . .
▁Dia ▁nom bor ▁satu ▁ki pas ▁gi la .
▁Dan ▁uma t ▁ti ap - ti ap ▁Rasul ▁tidak ▁ber pe ca h ▁be lah ▁dan ▁berse lisi han ▁( dalam ▁men ja lan kan ▁u gama ▁Allah ) ▁melainkan ▁setelah ▁sampai ▁kepada ▁mereka ▁aj aran - aj aran ▁yang ▁memberi ▁mereka ▁mengetahui ▁( apa ▁yang ▁dis uru h ▁dan ▁apa ▁yang ▁di lar ang ); ▁berlaku nya ▁( per sel isi han ▁yang ▁demikian ) ▁se mata - mata ▁kerana ▁has ad ▁de ng ki ▁ses ama ▁sendiri .
▁Peng guna an : ▁% s ▁[ OPTION ] ... ▁[ ▁[ CHAR S ET ] ▁_ BAR _ ▁RE QUE ST ▁[ FILE ] ... ▁]
▁Bukan ▁ta mba han .
▁Sa iz ▁Jack et ▁40 , ▁ fung si ▁biasa ▁dan ▁gi gi ▁yang ▁baik . ▁Apakah ▁kedua ▁terbaik ▁pe main ▁te nis ▁kole j ▁dari ▁Amerika ▁S yari kat .
▁Ya , ▁saya ▁keluar ▁dari ▁ku mpu lan ▁saya .
▁Tapi ▁saya ▁sudah ▁ada ▁kereta . .
▁- ▁Ini ▁adalah ▁ay am ▁ oren ▁yang ▁cukup ▁baik . ▁- ▁Ya , ▁i a ▁dari ▁Chan g .
▁Bagaimana ▁kalau ▁saya ▁meno lak ?
▁Da rah ▁dan ▁segala - gala nya ?
▁Awak ▁dah ▁selesai kan ▁peng inti pan ?
▁Maka ▁kes uda han ▁kedua nya , ▁bahawa ▁mereka ▁dit emp atkan ▁di ▁dalam ▁ne raka , ▁ke kal ▁mereka ▁di ▁dalam nya .
▁Ele an or , ▁ketika ▁aku ▁mengambil ▁sesuatu ▁dari ▁seseorang , ▁Kap al nya , ▁u ang nya , ▁ny awa nya ,
▁- ▁Se rius ▁tu an , ▁saya ▁cuma ▁perlu kan ▁loka si .
▁Awak ▁dah ▁berse tu ju ▁bertemu ▁dengan ▁saya .
▁- ▁Mereka ▁akan ▁mul akan ▁per ang .
▁Saya ▁percaya ▁se ku mpu lan ▁ni nja ▁dalam ▁perjalanan ▁ke ▁sini .
▁- ▁Kalau ▁ba lik , to long ▁u cap ▁ter ima ▁kasih ▁kepada ▁Re ver end ▁Do w d ▁bagi ▁pi ha k ▁saya .
▁Ada ▁banyak ▁cara ▁saya ▁boleh ▁lakukan nya .
▁- Di a ▁ba ca ▁blog ▁awak .
▁Terima ▁kasih ▁kerana ▁pri hat in .
▁- ▁Pre eti !
▁Link s ▁2
▁Sir , ▁saya ▁menemukan ▁p ember on tak ▁9 ▁sektor .
▁Bah awa ▁baj ing an ▁bukan ▁meng hen tak ▁wa lau pun ▁ber ni lai ▁pada
▁Adakah ▁anda ▁yakin ▁tidak ▁ingin ▁co ba ▁sekolah ▁lain ?
▁Baiklah , ▁terus ▁berjalan .
▁Per anti
▁Apa ▁imp ian ▁awak ?
▁- ▁En . ▁L ung ren .
▁A kan ▁lebih ▁heb at ▁jika ▁kawan - ka wan ▁semua ▁datang .
▁Kami ▁hanya ▁mendapat ▁li ma ▁dan ▁se ten ga h ▁mi nggu ▁sehingga ▁anda ▁me la wan ▁Bra ga , ▁dan ▁kami ▁mendapat ▁banyak ▁tan ah ▁untuk ▁membuat .
▁Se baik ▁sahaja ▁ber ke lip ▁nama ▁Che vali er ▁Si va ji ▁dalam ▁ta juk ▁Anda ▁akan ▁mu la ▁ter es ak - es ak
▁Saya ▁harus ▁ber tu kar ▁untuk ▁parti .
▁Anda ▁takut ▁ya , ▁penge cut ?
▁- ▁Aku ▁ken cing ▁seluruh ▁per mu ka annya .
▁U til iti ▁DE BI AN
▁Jangan , ▁Barry . ▁Kau ▁akan ▁selamat .
▁Apa ▁yang ▁boleh ▁buat ▁awak ▁ke kal ▁wara s ▁di ▁sini ▁?
▁Se karan ▁saya ▁hanya ▁perlu ▁let akkan ▁dalam ▁ini ▁dan ▁re bus kannya , ▁bukan ?
▁Saya ▁ada ▁wa wan cara ▁dengan ▁ jir annya .
▁- ▁Ben da ▁tu ▁ber fung si ▁ke ?
▁Eh , ▁Ko
▁Baiklah , ▁jadi , ▁dari ▁se gi ▁pe mas aran ▁kita ▁dapat ▁men jim atkan ▁ko s ...
▁Mereka ▁ menyu mbang kan ▁sebuah ▁li lin ▁per ak ▁pada ▁seorang ▁anak ▁ya tim ▁di ▁rumah ▁anak - anak ▁ya tim . ▁Itu ▁sangat ▁ indah !
▁W ang ▁bukan ▁masalah .
▁Ya , ▁kamu ▁semua ▁dah ▁sa ksi kannya ?
▁Du it ▁mak ▁ada ▁di ▁dalam , ▁jag a ▁baik - baik .
▁Aku ▁meny uru h nya ▁untuk ▁menunggu ▁di ▁Ku il ▁Lo tus .
▁- ▁Itu ▁mena rik ...
▁Sekarang ▁mereka ▁sudah ▁lakukan !
▁Saint ifik
▁Baik , ▁ba lik lah ▁du lu ...
▁Mereka ▁akan ▁membuat mu ▁ter ken al .
▁- ▁Ma ster ▁si la
▁K , ▁kamu ▁tahu , ▁20 ▁tahun ▁yang ▁lalu ▁ibu ▁ba pa ▁my ▁ber le pas ▁ke ▁Lu ck now ▁pada ▁hari ▁Bak ri ▁E id , ▁pen er b angan ▁mereka ▁belum ▁men ca pai ▁lagi ,
▁Ini ▁meninggalkan ▁saya ▁5 ▁tahun ▁yang ▁lalu .
▁Hei , ▁Ray ? ▁Kenapa ?
▁Rasul ul lah ▁telah ▁beriman ▁kepada ▁apa ▁yang ▁ditu run kan ▁kepada nya ▁dari ▁Tuhan nya , ▁dan ▁juga ▁orang - orang ▁yang ▁beriman ; ▁semuanya ▁beriman ▁kepada ▁Allah , ▁dan ▁Mala ikat - ma la ikat Nya , ▁dan ▁Kitab - ki tab Nya , ▁dan ▁Rasul - ras ul Nya . ▁( M ere ka ▁berkata ): ▁" Ka mi ▁tidak ▁me mbe za kan ▁antara ▁seorang ▁dengan ▁yang ▁lain ▁Rasul - ras ul nya ".
▁Font
▁- ▁Em ile ▁Ana fa no os ?
▁Mitchell , ▁ti nda kan ▁pertama ▁ber mu la .
▁Aku ▁sudah ▁tengo k ▁semua ▁papa ran ▁ke se lama tan .
▁Anda ▁tak ▁mempunyai ▁ke izi nan ▁di per lu kan ▁untuk ▁melihat ▁kan dung an ▁bagi ▁"% s ".
▁Le ngan ▁saya ▁adalah ▁pada ▁leng an mu .
▁Jag a ▁diri ▁baik - baik ▁Mit ten s .
▁Ber mu la ▁dengan ▁ber bor ak ▁dengan ▁mereka
▁Ke mana ▁sahaja ▁itu ▁bukan ▁masalah ▁buat ▁saya . ▁Hanya ...
▁Ya , s aya ▁minta ▁semua - akse s , ▁Jika ▁anda ▁akan ▁pe ep ▁la mina ▁ini , oka y ?
▁%.1 f ▁k H z
▁Tapi , ▁dia ▁tak ▁pernah ▁pun ▁berjaya ▁t angkap ▁apa - apa
▁Jadi , ▁ya , ▁kau ▁membuat ku ▁ter ta wa , ▁tapi ▁itu ▁tak ▁cukup .
▁Itu ▁akan ▁lebih ▁membantu , ▁ter ima ▁kasih ▁be ba ny ak .
▁Na nas ▁yang ▁ada ▁di ▁sini , ▁Member ikan ▁rasa ▁masa m ▁dan ▁rasa ▁mani s ▁dari ▁Tim ur .
▁Bi ar ▁saya ▁ tunjukkan ▁siapa ▁si ▁pena kut ▁itu !
▁Ber ca kap ▁untuk ▁diri ▁sendiri .
▁Aku ▁tahu ▁dia ▁ingin ▁ka ki ▁arna b ▁untuk ▁ny awa ▁juli a .
▁Kalau ▁i a ▁sampai ▁kepada ▁polis , ▁hab is lah ▁saya .
▁Pas ti ▁ada ▁sebab ▁dia ▁se but ▁tentang ▁cinc in ▁saya , ▁Te d .
▁Ba lik lah ▁re hat .
▁tidak ▁dapat ▁ja na ▁pri me ▁ kurang ▁dari ▁% d ▁bit
▁Ha pus kan ▁fail
▁Pa da ▁masa ▁ini ▁saya ▁sedang ▁di tahan ▁oleh ▁ten tera ▁I raq ,
▁Aku ▁ber ja nji ▁tidak ▁akan ▁berhenti ▁ber u saha ▁bahkan ▁di ▁hari ▁li bur ku .
▁OK , ▁bere hat !
▁Kau ▁tak ▁tahu ▁ra nc angan ▁Tuhan .
▁Aku ▁tak ▁ber maksu d ▁nak ▁bunu h ▁dia !
▁Lo mpat an ▁heb at !
▁ Sesungguhnya ▁Kami ▁telah ▁pun ▁mener angkan ▁a yat - a yat ▁ke ter angan ▁( yang ▁menjadi ▁dal il ▁dan ▁bu kti ) ▁kepada ▁kau m ▁yang ▁mahu ▁percaya ▁dengan ▁yakin .
▁Aku ▁mengambil ▁itu ▁dari ▁se pu pu ▁ket iga mu ▁yang ▁punya ▁to ko ▁elektron ik .
▁Tentu ▁ru mit ▁... ▁kau ▁perlu ▁bere hat .
▁- ▁ke ▁planet ▁lain .
▁A man ... ?
▁Saya ▁boleh ▁memang gil ▁dia , ▁tetapi ▁saya ▁don ' t - ▁yang ▁ber bun yi ▁seperti ▁per mul aan ▁yang ▁baik .
▁Ini ▁Del ta ▁98 4, ▁di ▁sini ▁berlaku ▁le tu pan , ▁kami . .
▁Saya ▁harus ▁memberitahu kan ▁hal ▁itu .
▁O leh ▁itu , ▁jangan lah ▁kamu ▁menga da kan ▁sesuatu ▁yang ▁se band ing ▁dengan ▁Allah , ▁kerana ▁sesungguhnya ▁Allah ▁mengetahui ▁( se ta kat ▁mana ▁buruk nya ▁perbuatan ▁sy i rik ▁kamu ) ▁sedang ▁kamu ▁tidak ▁mengetahui nya .
▁Kami ▁tak ▁mengu mu m kan ▁orang ▁hi lang ▁sehingga ▁cukup ▁24 ▁jam , ▁tapi ▁de mi ▁Way ne ▁Enterprise s ...
▁untuk ▁berhenti ▁se ke tika ▁Saya ▁ber ta nya .
▁sha ru zza man @ ▁my real box . ▁com
▁Yeah , ▁itu ▁ lah ▁C in dy .
▁Sy e , ▁i a ▁adalah ▁okay .
▁Maaf , ▁kami ▁tut up ▁untuk ▁p ember si han .
▁Saya ng , ▁awak ...
▁Per isti wa ▁dija ng ka
▁Masa lah nya , ▁Ty , ▁saya ▁faha m .
▁Data ng ▁sem ula ▁bila ▁kamu ▁dah ▁besar .
▁Dia ▁cakap ▁o tak mu ▁seperti ▁komputer .
▁Anda ▁di ▁dalam ▁keadaan ▁ma buk .
▁Ke tur un an ▁Mann ▁ini . . ▁mereka ▁adalah ▁kawan ▁lama ▁keluarga ▁saya .
▁Dan ▁pen yang ga han .
▁Kes eron ok kan !
▁Mari , ▁minu m ▁untuk ▁si ▁ayah .
▁Dia ▁boleh ▁jadi ▁kawan ▁di ▁a cara ▁per kah win an mu .
▁Anda ▁mahu ▁me lat ih ▁atau ▁anda ▁mahu ▁ber gura u ?
▁Baiklah , ▁macam ▁ni .
▁Aku ▁tahu ▁kau ▁boleh ▁lakukan nya .
▁Anna ▁dan ▁aku ▁sangat ▁sen ang ▁bersama - s ama .
▁Kita ▁telah ▁bekerja ▁untuk ▁lakukan
▁Saya hara pa wa k da pat me lihat ini .
▁Seperti ▁di dalam ▁file m ▁apabila ▁seorang ▁ayah ▁ber lut ut ▁di ▁de pan ▁anak nya ▁A nak nya ▁akan ▁ber asa ▁pe ning
▁Awak ▁let akkan ▁saya ▁betul - be tul ▁dalam ▁loka p .
▁Se mbu ny i ▁du lu ▁dan ▁aku ▁akan ▁cari ▁kamu ▁sele pas ▁semuanya ▁selesai .
▁Cum a ▁main an .
▁Kemudian ▁ma kanlah ▁dari ▁segala ▁je nis ▁bu nga - bung aan ▁dan ▁bu ah - bu ahan ▁( yang ▁engkau ▁suka i ) , ▁ser ta ▁tur ut lah ▁jalan - ja lan ▁per atura n ▁Tuhan mu ▁yang ▁di il ham kan ▁dan ▁di mu dah kannya ▁kepada mu ".
▁Saya ▁rend ahkan ▁kamu , ▁betul , ▁kan ?
▁Itu ▁sebuah ▁peng khi ana tan . / ▁Dia m lah .
▁La lu ▁be liau ▁berkata , ▁" bo leh ▁anda ▁hanya ▁men amba t ▁saya ?"
▁Kau ▁lu pa , ▁ba ha sa ▁C ina ▁aku ▁Lebih ▁baik ▁dari ▁ba ha sa ▁l ng geri s .
▁Kamu ▁membuat ▁aku ▁ker as .
▁Pen a mat ▁yang ▁ge mbi ra ?
▁Saya ▁membawa ▁jen ama ▁kami ▁kembali ▁dari ▁antara ▁orang ▁mati .
▁Sekarang ▁ini ▁semua ▁dah ▁berak hir .
▁- ▁Ge mbi ra ▁bertemu ▁dengan mu .
▁Aku ▁ingat ▁kita ▁dah ▁se las ai ▁tentang ▁tu .
▁- ▁Awak ▁nak ▁cari ▁minu m ?
▁" T ing gal kanlah ▁semua ▁har a pan , ▁siapa pun ▁yang ▁masuk ▁ke ▁sini ."
▁Itu ▁sebab nya ▁dia ▁tidak ▁pernah ▁mene le fon ku .
▁G n ect
▁Bis ing ▁sangat .
▁Saya ▁cinta kan ▁Stefan ▁se panja ng ▁masa .
▁- ▁Saya ▁nak ▁to long .
▁Kem ari lah ▁atau ▁kau ▁tidak ▁akan ▁aku ▁ anggap ▁a dik .
▁Untuk ▁itu , ▁pa tik ▁ mohon ▁am pun .
▁Saya ▁akan ▁bunu h ▁awak , ▁anak ▁haram .
▁Kalau ▁tidak , ▁Har le en ▁yang ▁akan ▁menang g ung ▁kes a kit annya .
▁_ I ndeks paper ▁size
▁ah li ▁sihir ▁dari ▁Sel atan .
▁Bi ar ▁betul , ▁mereka ▁ada ▁senjata ▁a pi !
▁Su mpah lah ▁diri ▁awak , ▁su mpah lah ▁kepada ▁de wa - de wa .
▁Ara han ▁ RS ET ▁ga gal : ▁% s
▁Ny a man ▁ nya !
▁ Sesungguhnya ▁kami ▁telah ▁tinggal ▁dalam ▁keadaan ▁yang ▁mel ala ikan ▁kami ▁daripada ▁me mi kir kan ▁perkara ▁ini , ▁bahkan ▁kami ▁telah ▁menjadi ▁orang - orang ▁yang ▁menga nia ya ▁diri ▁sendiri ".
▁Apa ▁yang ▁kamu ▁fikir ▁tentang ▁P - 31 ?
▁Okay . ▁aku ▁tidak ▁apa .
▁Program ▁ini ▁adalah ▁per isi an ▁be bas ; ▁anda ▁boleh ▁menge dar kan ▁sem ula ▁di ba wa h ▁term a ▁GNU ▁General ▁Public ▁License ▁vers i ▁3 ▁atau ▁( pi li han ▁anda ) ▁vers i ▁ter da hulu . ▁Program ▁ini ▁sama ▁sekali ▁tiada ▁memberikan ▁ja min an .
▁Ke can ti kan ▁kamu ▁u mpa ma ▁em as
▁Kenapa ▁tak ▁cakap ▁apa - apa ?
▁Dia ▁telah ▁membunuh ▁semua ▁mata ▁pela ja ran .
▁Adakah ▁anda ▁fikir ▁mereka ▁me mah ami ▁apa ▁yang ▁aku ▁katakan ?
▁Pen uh ▁[ 25 ]
▁Terima ▁kasih .
▁Tidak , ▁dan ▁saya ▁betul - be tul ▁tidak ▁peduli .
▁- ▁Aku ▁mahu ▁memiliki ▁sesuatu ▁yang ▁aku ▁gun akan .
▁Le tu pan ▁Gal a ksi !
▁Aku ▁perlu ▁bi lik ▁10 20 .
▁Oh ▁Ayah , ▁ada ▁apa ▁dengan mu !
▁itu lah ▁has il ▁ju alan ▁pu an ▁Β l о ѕ ѕ о m .
▁Apa ▁maksud ▁kamu ?
▁Kamu ▁semua ▁hanya ▁makan ▁saja . ▁hanya ▁orang - orang ▁yang ▁tak ▁ber guna ▁saja .
▁Ka rena , ▁tak ▁boleh ▁ma bok ▁saat ▁menge mu di .
▁Pe mas ang ▁De bug info ▁Pac ka ge K it
▁Bila ▁ku ▁memba nta h , ▁pe luk lah ▁aku . .
▁Per min taan ▁ini ▁tidak ▁pernah ▁di ter ima .
▁Kita ▁berada ▁dalam ▁li f .
▁Ke ba nya kan ▁Industri es , ▁apa ▁yang ▁boleh ▁saya ▁lakukan ▁untuk ▁anda ?
▁Tidak ▁ada ▁ker anda , ▁atau ▁plot , ▁i a ▁benar - benar ▁sem ula ▁jadi .
▁Ia ▁pa ng gang ▁panta t ▁hai wan ▁kecil ▁anda , ▁si la .
▁Go P i , ▁dengar kan ▁aku !
▁Kem bali lah ▁ke ▁sana ▁dan ▁ber main .
▁- ▁Bila ▁kamu ▁melihat nya ?
▁Tidak , ▁i a ▁adalah ▁beberapa ▁je nis ▁he lah .
▁Dan ▁sebelum ▁me layan i ▁ hukum an ▁seu mur ▁hidup , ▁itu ▁adalah ▁ke put us an ▁ha kim ▁Ol af ▁di bu at ▁men der ita ▁setiap ▁kes ul itan
▁Saya ▁me mah ami ▁bahawa
▁Tengo k lah ▁apa ▁yang ▁jadi ▁ak hir nya .
▁Mari ▁si ▁kecil , ▁ jom ▁cari ▁Mama ▁kau .
▁" Ta mu ▁telah ▁datang ▁dan ▁a pi ▁telah ▁di nya la kan ."
▁se baik ▁a je ▁selamat , ▁Kita ▁harus ▁gera k .
▁Awak ▁pernah ▁na ik ▁kap al ▁ter bang ?
▁% s \ t \ t \ t P en anda t angan ▁ OC SP .
▁Jangan ▁i kut ▁cakap ▁dia !
▁Te ta pi ▁pe mu ja an ▁tu an ▁sahaja ▁boleh ▁me mus n ahkan ▁Cha ndra mu khi ▁se pen uh nya .
▁Nama ▁kh as ▁@ DE FA UL T _ SIN K @ , ▁@ DE FA UL T _ S OUR CE @ ▁and ▁@ DE FA UL T _ M ONI TOR @ ▁boleh ▁digunakan ▁untuk ▁ny ata kan ▁sin ki , ▁su m ber ▁dan ▁monitor ▁la lai .
▁Jess e , ▁anak ▁aku .
▁Oh , ▁kata nya ▁Anda ▁benar - benar ▁cer dik , ▁Shell ey .
▁Tiada ▁siapa ▁yang ▁di p ang gil ▁mereka .
▁Tam b ahkan ▁ke ▁Pro jek
▁Terima ▁kasih ▁kerana ▁lu angkan ▁masa .
▁Media ▁tidak ▁pernah ▁di peri ksa ▁lebih ▁tel iti , ▁bahawa ▁banyak ▁daripada ▁para ▁pe mi mpi n ▁ini ▁bagaimana ▁orang ▁boleh ▁lo los .
▁Orang ▁yang ▁up ah ▁awak ▁dia ▁akan ▁lakukan ▁perkara ▁yang ▁sama ▁pada ▁awak .
▁Mereka ▁semua ▁ anggap ▁aku ▁sebagai ▁lelaki .
▁- ▁Kami ▁pun ▁dah ▁se dia .
▁Hey , ▁saya ▁akan ▁mengambil ▁mereka ▁dan ▁me let akkan ▁mereka ▁di ▁belakang ▁untuk ▁anda .
▁Mac am ▁apa , ▁Jim mie ?
▁Dengar ▁sini , ▁ayah
▁Mar ty , ▁must a hil lah .
▁Tan da kan ▁sebagai ▁_ P en ting
▁- ▁Ga dis ▁kas ar , ▁bera mbu t ▁hita m .
▁& ▁Lihat
▁Kata ▁dia , ▁tunggu ▁ke wanga n ▁dia ▁stabil ▁du lu .
▁Dit er jem ahkan ▁oleh ▁Ha zu ka ▁Him ura ... ▁Apa ▁kai tan ▁ nya ▁dengan ▁wata k ▁ut ama ▁ce rita ▁ini ?
▁- ▁Em m . ▁-
▁Kenapa ?
▁Dia ▁ber hutan g ▁dengan ▁saya . ▁Maaf .
▁Kami ▁berse dia ▁untuk ▁memba yar ▁de nda .
▁Tolong lah ▁jangan ▁ber kah win , ▁Vi rat
▁Mungkin ▁dia ▁bawah ▁nama ▁yang ▁ber be za .
▁Ini ▁mi lik ▁awak , ▁ambil lah .
▁Malcolm ▁jadi kannya ▁5, ▁tapi ▁sem asa ▁19 03 , ▁ada ▁6 ▁orang , ▁ber mak na ▁ada ▁seorang ▁lagi .
▁Saya ▁mahu ▁saya ▁berada ▁di ▁rumah .
▁Bo ome rang ▁yang ▁can tik .
▁Dia ▁ber ja nji , ▁jika ▁aku ▁sun yi ▁dia ▁akan ▁meng i rim ▁mala ikat ▁untuk ▁me me luk ▁aku .
▁Kes eron ok kan ▁sal uran ▁per cu ma ▁seperti ▁imp ian ▁reng gang .
▁Kau ▁nampak ▁tak ▁bud ak ▁ge mu k ▁yang ▁be lari ▁ka t ▁sini ▁ta di ?
▁Jangan ▁ber lag ak ▁bija k .
▁Be lum ▁se mpat ▁kami ▁ber ka bung ▁atas ▁kehilangan ▁anak ▁kami , ▁mereka ▁dah ▁men ahan nya . .
▁Jangan ▁mengatakan ▁saya ▁tidak ▁mendapat ▁lagi .
▁Aku ▁tak ▁maksud kan ▁makan an .
▁A va tar ▁tu ▁selamat ?
▁Kami ▁ada ▁untuk ▁awak .
▁Se bab ▁aku , ▁kau ▁ter le pas ▁dari ▁pen ja ra .
▁Saya ▁u lat ▁ini ?
▁Ke pada ▁Allah ▁ju a lah ▁tempat ▁kembali ▁kamu ▁semuanya , ▁kemudian ▁Ia ▁akan ▁mener angkan ▁kepada ▁kamu ▁( bala san ) ▁apa ▁yang ▁kamu ▁telah ▁lakukan .
▁Skri n ▁sent uh .
▁Ini kah ▁Russia ?
▁Tapi ▁jika ▁i a ▁tak ... ▁ha pus kannya .
▁Ia ▁adalah ▁ha dia h .
▁Data ng ▁ke ▁hospital ▁jam ▁3 :30 , ▁dan ▁Vin , ▁jangan ▁ro sak kannya ▁lagi .
▁Ya ▁sayang , ▁aku ▁disini .
▁Te ta pi ▁parti ▁di ▁London ▁yang ▁besar .
▁- ▁O key - ▁- ▁o key - .
▁Eric a , ▁awak ▁harus ▁bang ga ▁pada nya .
▁Ya , ▁saya ▁salah ▁seorang ▁dari ▁mereka .
▁Aku ▁tak ▁boleh ▁tahan ▁lagi .
▁" R asa ▁aman ▁ini ."
▁Saya ▁tak ▁merasa i ▁sihir ▁pada nya .
▁Kau ▁masih ▁mamp u ▁menga lah kan ▁semua ▁mereka .
▁Saya ▁tahu ▁saya ▁pat ut ▁beritahu ▁kamu , ▁tapi .
▁Mungkin ▁ta nya ▁sebab ▁sakit ▁per ut .
▁A nak ▁lelaki ▁saya .
▁Itu ▁bis nes ▁haram , ▁To dd !
▁Ama tir ▁bodoh , ▁orang ▁bodoh , ▁idiot !
▁Se ja uh ▁yang ▁saya ▁tahu , ▁mereka ▁masih ▁lagi ▁pen jena yah .
▁Du nia ▁ini ▁le lah , ▁tapi ▁kami ▁adalah ▁kekuatan
▁This ▁guy ▁is ▁going ▁to ▁have ▁a ▁lot ▁of ▁surveillance .
▁Re kod ▁polis ▁menunjukkan , ▁Ge ng ▁Cu le bra ▁leng kap ▁berse nja ta . .
▁" ▁Saya ▁ke bas ."
▁Ber s ama ▁aku ▁ada ▁Kap ten ▁yang ▁ter ced era .
▁10 ▁saat ▁lagi , ▁tu an .
▁U sah ▁bi mbang , ▁kita ▁akan ▁lin dung i ▁kau
▁Saya ▁akan ▁menunjukkan ▁kepada ▁anda !
▁sudah ▁pasti ▁kami ▁telah ▁mencari ▁ibu ▁ba pa ▁kamu . ▁Pas ti ▁kami ▁telah ▁cuba ▁mengha ntar ▁kamu ▁kembali .
▁Ter ak hir ▁kali ▁aku ▁lakukan ▁itu .
▁Mr . ▁Pi bb ... ▁Ce laka .
▁Jika ▁ada ▁seorang ▁wanita ▁di ▁keluarga ▁an gara ... ▁Mereka ▁akan ▁su lit ▁menang an inya .
▁- M ere ka ▁orang tua mu ?
▁Dan ▁di ▁mana ▁peng hor ma tan ▁di ▁meng khi ana ti ▁rak yat nya ▁sendiri ?
▁Short ie , ▁ingat ▁ren ca na ▁kita .
▁Dan ▁lakukan ▁perkara ▁gi la ▁yang ▁orang ▁lain ▁tak ▁mungkin ▁lakukan .
▁Keluar kan ▁fail ▁sem asa ▁dari ▁re posit ori
▁Saya ▁di ▁sini ▁bersama ▁awak . ▁Untuk ▁apa ▁saya ▁memang gil ▁awak ?
▁Tiada ▁lagi ▁tra ge di ▁seperti ▁ini .
▁Apa ▁lagi , ▁a bang ?
▁Kata ▁Kun ci ▁XMP .
▁Sudah ▁menjadi ▁perkara ▁biasa ▁bagi ▁seseorang ▁untuk ▁meninggalkan ▁aman ah ▁anda i ▁kata ▁bak al ▁terjadi ▁pen jel maan ▁sem ula .
▁Wal au pun ▁per bin c angan ▁di ▁luar ▁ca ta tan ?
▁La mpi ran ▁tidak ▁menga n dung i ▁mes ej ▁kal en dar ▁yang ▁sah
▁Kamu ▁akan ▁selamat .
▁Dengar , ▁saya ▁akan ▁ rela kan ▁ny awa ku ▁de mi ▁men ja ga ▁ke se lama tan mu .
▁Itu ▁per be za an ▁antara ▁su ks es ▁dan ▁ga gal .
▁Dengar , ▁saya ▁juga ▁mencari ▁War d .
▁Aku ▁mendapatkan ▁sedikit ...
▁" Se se orang ▁telah ▁menggunakan ▁telefon ▁awak ."
▁Isi h ▁Men a ik
▁Per ge langan ▁tangan ▁pat ah .
▁Ay uh !
▁Oh , ▁jangan ▁bi mbang , ▁A lain !
▁Pi s au ▁bela ti ▁ini ▁untuk ▁apa ?
▁Aku ▁takut ▁aku ▁mungkin ▁berak hir ▁dengan ▁sakit ▁ha ti .
▁Kamu ▁baik - o key ?
▁Tapi , ▁saya ▁tahu ▁ayah lah ▁di ▁se ba lik nya .
▁- ▁54 82 . ▁- ▁Ya ?
▁kamu ▁ingin ▁tahu ▁apa ▁yang ▁berlaku ▁antara ▁aku ▁dan ▁Matt y ?
▁Ya , ▁se la gi ▁awak ▁tidak ▁berada ▁di ▁panta inya , ▁boleh ▁saja .
▁Hy ung ▁sudah ▁ber su sah - pa yah ▁bekerja ▁se mata - mata ▁mahu ▁mengha ntar ▁saya ▁ke ▁sekolah .
▁Kami ▁telah ▁di lat ih ▁apabila ▁pe mand u ▁telah ▁me mand u ▁la ju , ▁untuk ▁mendapatkan ▁se benar ▁ra pat ▁dan ▁kemudian ▁menga k tif kan ▁la mpu ▁me rah ▁dan ▁bir u .
▁Dia m lah , ▁En zo .
▁Kemudian ▁bagaimana ▁cinta ▁nak ▁berjaya ?
▁Bagaimana , ▁Emily ?
▁Mana ▁tahu ▁jika ▁ada ▁pintu ▁belakang .
▁Saya ▁tak ▁ada ▁cakap ▁apa - apa . ▁Tapi ▁saya ▁boleh ▁cakap ▁dengan ▁dia ▁kalau ▁kamu ▁mahu .
▁Tapi ▁kau ▁pil ih ▁Mak , ▁bukan ▁aku ...
▁Terima ▁kasih , ▁tetapi ▁saya ▁akan ▁cuba ▁dan ▁melakukan ▁pen ul isan ▁sem asa ▁dia ▁sedang ▁tidur .
▁Ia ▁ paka ian .
▁Su sah ▁di den gar ▁kalau ▁kau ▁ber teri ak .
▁Max , ▁und ur ▁per lah an - lah an .
▁Ten dang ▁lagi !
▁Kami ▁harus ▁pergi ▁apabila ▁kamu ▁sedang ▁me mer hati kan
▁" B ible ▁saya ▁Per le mba gaan "?
▁- ▁C enda wan ▁sem ing gu ▁sebelum .
▁Da lam ▁kes ▁ini , ▁saya .
▁S yar at ▁saya ▁hanya lah ▁dia ▁perlu ▁ha dir ▁lagi ▁untuk ▁meny aks ikan ▁awak ▁menga ku ... ▁pada ▁kesalahan ...
▁Ber hati - hati ▁ , ▁ayah .
▁Cum a ▁sedikit ▁bera t .
▁Baiklah , ▁mari ▁saya ▁to long .
▁Baiklah , ▁hidup kan ▁en jin !
▁Awak ▁telah ▁membunuh ▁musu h ▁dia ... ▁dan ▁juga ▁per asa an ▁sy ak ▁was angkan ya .
▁- ▁N isha , ▁dia m !
▁Pe gang ▁be g ▁itu , ▁bodoh .
▁Lu pa kan ▁kereta ▁dia . ▁Lu pa kan ▁semua ▁tu .
▁Adakah ▁kamu ▁pernah ▁pergi ▁ke ▁aka de mi ▁per tu tur an ?
▁Ia ▁akan ▁hi lang ▁se ba ny ak ▁saya , ▁jadi ▁i a ▁adalah ▁sem pur na .
▁Saya ▁tak ▁suka ▁menge ce wa kan ▁kamu ▁tapi ▁di ▁sini lah ▁habit at ▁sem ula ja di ▁kita .
▁Kau ▁tak ▁tahu ▁pun ▁apa ▁ha jat ▁aku ...
▁Ber si ul , ▁Aku ▁berjalan ▁menge jar mu
▁Ba a hu bali ▁perlu ▁di bun uh
▁E p son ▁S ty lus ▁T X 4 10
▁Jika ▁anda ▁masih ▁mahu ▁makan , ▁minta ▁kas ta ▁kami ▁makan ▁du lu
▁25 ▁ki lo ▁itu ▁adalah ▁rang ka ian ▁ke se lama tan ▁aku .
▁Ta han ▁Te s oro !
▁je nis ▁fail ▁tak ▁di keta hui ▁% s
▁Terima ▁kasih , ▁Mor o es .
▁Kel aju an ▁ISO ▁berubah
▁Ker ana ▁tu an ▁pu teri ▁meno lak ▁la mar annya , ▁dia ▁telah ▁memberi ▁ arahan ▁kerana ▁ma rah
▁Tak ▁masalah , ▁kau ▁pergi lah , ▁jangan ▁kh awa tir kan ▁aku .
▁Bi ar ▁betul !
▁Dia ▁bukan ▁per isi k ▁India .
▁Saya ▁menga na lisi s ▁za rah ▁ini ▁Bah awa ▁C lay Par ker ▁dan ▁Shaw na ▁Ba ez ▁ket ing ga lan , ▁dan ▁saya ▁telah ▁men jum pai ▁sesuatu ▁yang ▁sangat ▁mena rik .
▁Ia ▁tidak ▁ber tu kar ▁jadi ▁apa - apa , ▁Ia ▁hanya ▁bar angan ▁kole ksi , ▁ibu .
▁1 64 ▁x ▁1 64
▁l mpe rial ▁Je pun ▁tidak ▁akan ▁meninggalkan ▁kamu !
▁Dan ▁bera tus ▁anak ▁mu da ▁yang ▁ber har ga ▁masih ▁hidup ▁su sah ▁di ▁jalan an .
▁Saya ▁rasa ▁awak ▁perlu ▁buat ▁pilihan .
▁Kur angkan ▁bercakap .
▁Se te lah ▁Na bi ▁meny ata kan ▁hal ▁itu ▁kepada ▁ ister inya , ▁ ister inya ▁ber ta nya : ▁" Si apa kah ▁yang ▁memberi ▁tahu ▁hal ▁ini ▁kepada ▁tu an ? ▁"
▁- ▁Be tul , ▁i a ▁hanya ▁saya ▁dapat ▁...
▁Ke tika ▁dia ▁mening gal , ▁saya ▁ada ▁ke wa ji ban ▁untuk ▁mener us kan ▁mi lik nya ▁seperti ▁kamu .
▁Sub s ▁oleh :
▁Bukan kah ▁lebih ▁mu dah ▁untuk ▁me mas u ki ▁di ▁sebe lah ?
▁Jadi ▁kenapa ▁war ta wan ▁tempat an ▁seperti ▁awak ▁ter ta rik ▁pada ▁kes ▁sebe gin i ?
▁Dan ▁siapa kah ▁lagi ▁yang ▁lebih ▁ani aya ▁dari ▁orang ▁yang ▁menga da - ada kan ▁perkara - per kara ▁yang ▁du sta ▁terhadap ▁Allah , ▁atau ▁yang ▁mend usta kan ▁a yat - a yat ▁ke ter angan Nya ?
▁Be liau ▁adalah ▁salah ▁satu ▁yang ▁akan ▁membawa ▁ke gem bir aan ▁kepada ▁kehidupan ▁anak ▁saya .
▁Kau ▁jadi ▁seperti ▁ayah mu .
▁Rich ie , ▁ini lah ▁yang ▁saya ▁akan ▁buat ▁untuk ▁kamu .
▁Hent ikan , ▁Mer lyn .
▁Bagaimana ▁aku ▁mel up akan ▁orang ▁yang ▁begitu ▁heb at
▁Saya ▁sangat ▁ber du ka ▁atas ▁keluarga ▁awak ...
▁Kau ▁boleh ▁sur uh ▁aku ▁dia m ▁tapi ▁kau ▁tak ▁boleh ▁ha lang ▁aku ...
▁cuba ▁un tak ▁menu n juk ▁lag ak kah ?
▁- ▁Itu ▁adalah ▁ce rita ▁besar .
▁Wal au pun ▁siapa ▁tahu , ▁mungkin ▁kali ▁ini ▁kita ▁akan ▁bela jar .
▁Be liau ▁mahu ▁bertemu ▁dengan ▁anda .
▁Sen ja ta ▁akan ▁di han tar ▁ke ▁U tara ▁Ur k ▁pat a ▁te nga h ▁malam .
▁Well , itu ▁adalah ▁van ▁yang ▁pergi ▁Jika ▁anda ▁tidak ▁jalan ▁ke ▁bawah ▁dengan ▁per kata an ▁yang ▁me ros akkan .
▁Aku ▁tak ▁pernah ▁bi ar ▁dia ▁ke lap aran .
▁Dan ▁saya ▁har ap ▁ini ▁hanya ▁waktu ▁di ▁mana ▁dia ▁salah ▁membuat ▁ke put us an , ▁dan ▁bukan ▁seperti ▁cinta .
▁Okay , ▁maka ▁di ▁mana ▁kita ▁akan ▁pergi ▁ke ▁mana ?
▁Ri je ka
▁Ke ta hui lah ! ▁Sem asa ▁mereka ▁ber sel ubung ▁dengan ▁ paka ian ▁mereka ▁sekali pun , ▁Allah ▁mengetahui ▁apa ▁yang ▁mereka ▁se mbu ny ikan ▁dan ▁apa ▁yang ▁mereka ▁za hir kan ; ▁sesungguhnya ▁Ia ▁Maha ▁Men ge ta hui ▁akan ▁segala ▁( isi ▁ha ti ) ▁yang ▁ada ▁di ▁dalam ▁da da .
▁Oliver , ▁kamu ▁juga .
▁aku ▁sangat ▁ma rah ▁dan ▁cuba ▁menga n cam ▁a gar ▁pe ny eli dika nku ▁boleh ▁ku sam bung .
▁Di bela kan g ▁air - con , ▁ada ▁beberapa ▁ AK ,
▁- Ju mpa ▁lagi ▁ge mu k .
▁Jangan ▁salah ▁gun akan ▁kekuatan ▁awak .
▁Baiklah .
▁Anda ▁tidak ▁perlu ▁untuk ▁me lib atkan ▁diri ▁be liau
▁Dan ▁seperti ▁yang ▁kamu ▁kata ▁kamu ▁selamat .
▁Bu dak ▁baik .
▁Dan ▁kata nya , ▁Pra y ?
▁Su atu ▁pe tang , ▁beberapa ▁cal on ▁me lan tik ▁saya ▁untuk ▁go long an ▁pe nya ir , ▁kerana ▁saya ▁baru ▁saja ▁me men ang inya ▁...
▁Itu ▁sangat ▁must a hil , ▁sayang .
▁Ro x anne , ▁ini ▁adalah ▁Ibu ▁saya
▁Ye ong ▁Do . ▁o key kah ?
▁Jangan , ▁nak , ▁masuk lah .
▁Saya ▁senti asa ▁mengha r gai ▁per saha ba tan ▁kita ▁dan ▁senti asa ▁mengingat i ▁awak ... ▁dengan ▁ingat an ▁yang ▁ indah , ▁per asa an ▁yang ▁tu lus ▁dan ▁is time wa .
▁Dan ▁saya ▁to long ▁menye les ai kannya !
▁Bila ▁si alan ▁itu ▁masuk , ▁aku ▁nak ▁dengar ▁te mba kan , ▁dan ▁aku ▁nak ▁dengar ▁" Sa s aran ▁di mus n ahkan ".
▁Ga gal ▁men ca pai ▁kan dung an ▁ime j ▁%( image ) s .
▁_ T eks ▁sebe lah ▁ikon
▁Aku ▁nak ▁cakap ▁' A ku ▁cinta kan ▁kau ' !
▁Oh , ▁Tuhan , ▁li mo ▁ini ▁begitu ▁o bat ▁bi us , ▁du de .
▁Siapa ▁jumpa , ▁dia ▁punya . .
▁Kau ▁dah ▁ada ▁kehidupan ▁yang ▁baik .
▁Jika ▁Gab bar ▁tahu , ▁Saya ▁akan ▁di hukum .
▁Mas ih ▁ada ▁yang ▁belum ▁datang .
▁Kamu ▁juga ▁kata ▁mahu ▁menggunakan ▁sera gam ▁Red ha w ks .
▁Ayah ▁Ge eta ▁dan ▁Ba bit a ▁Kuma ri ▁dan ▁se pu pu ▁ra pat nya .
▁Ke hi du pan ▁dia ▁bagus , ▁kan ▁?
▁Awak ▁se dar ▁tak ▁yang ▁dia ▁tak ▁pernah ▁berhenti ▁melihat ▁diri ▁awak .
▁- ▁Tidak ▁perlu ▁di ba wa ▁ke ▁sud ut .
▁Dia ▁terlalu ▁kecil .
▁Kau ▁ba wa ▁aku ▁ke ▁sini ▁dan ▁tinggal kan ▁aku .
▁- A kan ▁ku ▁ja uhkan ▁dari mu .
▁Aku ▁tak ▁jumpa ▁apa - apa ▁pun .
▁- ▁Leon id ▁Sa vy ch , ▁tak ▁perlu .
▁Band ar ▁Ayo dh ya
▁Dia ▁cakap ▁masuk !
▁Saya ▁di per ta nggu ng ja wa b kan ▁ke ▁atas ▁kamu .
▁Muka nya ▁can tik ▁itu ▁memang ▁pasti ▁Tapi ▁begitu ▁juga ▁ra mai ▁pela cur ▁lain ▁di ▁sini
▁Ber an inya ▁lu pa ▁status mu ▁untuk ▁meminta ▁Yang ▁Mul ia ▁menye rah ▁begitu ▁saja ?
▁Pa _ dam ▁% s
▁Saya ▁datang ▁ber la wan ▁de mi ▁kawan .
▁Apa ▁yang ▁kamu ▁cuba ▁untuk ▁me mbu kti kan , ▁Sur ly ?
▁- ▁Tak , ▁Lisa , ▁tunggu .
▁P US ING AN ▁ AK H IR ▁Sa tu ▁pus ing an ▁lagi ▁dan ▁Mc Que en ▁jauh ▁di ▁de pan .
▁Opera si
▁Yang ▁penting , ▁ce rita mu ▁akan ▁tetap ▁hidup ▁di dalam ▁diri nya .
▁Bo do h ▁... ▁ja lang .
▁ Sesungguhnya ▁orang - orang ▁yang ▁memba nta h ▁mengenai ▁maksud ▁a yat - a yat ▁Tuhan mu ▁dengan ▁tidak ▁ber das ar kan ▁se bar ang ▁bu kti ▁yang ▁sampai ▁kepada ▁mereka ▁( dari ▁pi ha k ▁yang ▁dia ku i ▁benar nya ) , ▁tidak ▁ada ▁dalam ▁da da ▁mereka ▁melainkan ▁per asa an ▁mahu kan ▁ke bes aran ▁( untu k ▁menga tas i mu ) , ▁ke mah uan ▁yang ▁mereka ▁tidak ▁sekali - kali ▁akan ▁dapat ▁men ca pa inya .
▁tidak ▁dapat ▁ci pta ▁so ket ▁D H CP ▁B PF : ▁% s
▁Saya ▁rasa ▁saya ▁menunggu ▁sesuatu ▁yang ▁luar ▁biasa .
▁Baby ▁Fa ti ma , ▁tak ▁aku ▁sang ka .
▁Ta hni ah , ▁Anda ▁menjadi ▁sar jan
▁Mi lik ▁pe gua m ▁atau ▁doktor ?
▁Dia ▁menggunakan ▁gara m ▁la ut ▁untuk ▁mene balk an ▁ku lit , ▁supaya ▁dapat ▁men ahan ▁pu ku lan ▁yang ▁lebih ▁lama .
▁Se mbu ny ikan ▁_ Me s ej ▁yang ▁Di pada m
▁Baiklah . ▁cakap ▁berhenti , ▁kalau ▁kau ▁lihat ▁sesuatu ▁yang ▁kau ▁suka .
▁Mari lah ▁Mi riam , ▁jangan ▁jadi ▁pena kut .
▁Ia ▁benar - benar ▁kamu .
▁- x ▁n , ▁-- n th ▁n ▁Ma in kan ▁setiap ▁blok ▁ke - n
▁Ama t ▁suka r ▁untuk ▁dik esan , ▁must a hil ▁untuk ▁dira mal .
▁Chris ▁Ryan ▁ma lah ▁me lut ut .
▁Saya ▁telah ▁melakukan ▁sedikit ▁saya ▁ber tin dak ▁untuk ▁anda .
▁Ku ▁har ap ▁tidak , ▁En .
▁Dan ▁anda ▁tidak ▁tahu ▁sama ▁ada ▁dia ▁akan ▁i a itu -
▁- ▁Ya , ▁dia ▁cer dik . ▁Dia ▁yang ▁selamat kan ▁kami .
▁Saya ▁hanya ▁i kut ▁ arahan ▁pe mi lik ▁saya
▁O key , ▁saya ▁perlu ▁pergi ▁ke ▁sana .
▁Hei , ▁parti ▁itu .
▁Kenapa ?
▁En ci k ▁Whi ta ker , ▁yang ▁hal us .
▁Tak ▁boleh ▁me mu atkan ▁ring kas an ▁bagi ▁% s
▁Se o lah - o lah ▁orang - orang ▁Jer man ▁masih ▁belum ▁melihat ▁i a ▁dari ▁atas .
▁Su sah ▁nak ▁hidup kannya ▁kembali
▁Di ▁sini , ▁En ci k ▁De ng .
▁Aku ▁rasa ▁lebih ▁baik ▁kau ▁ber ga bung ▁dengan ▁kami ▁apabila ▁kerja ▁kau ▁dah ▁selesai .
▁mengg eli tik !
▁Se ti dak nya ▁ada ▁8 ▁tahan an ▁yang ▁ber ta nggu ng ja wa b ▁untuk ▁itu .
▁Selamat ▁tinggal , ▁si put ▁kecil .
▁Kita ▁dapat ▁per ger akan .
▁Se si apa ▁yg ▁ingin ▁sent uh ▁kau ?
▁Me ma ng , ▁kau ▁tak ▁dapat ▁h ubung i ▁dia !
▁Jika ▁seperti ▁ini ...
▁Dan ▁apabila ▁Kami ▁ber i ▁manusia ▁merasa i ▁sesuatu ▁ rah mat , ▁mereka ▁ber ge mbi ra ▁dengan nya ▁( se hin gga ▁lu pa ▁dara tan ); ▁dan ▁jika ▁mereka ▁di ti mpa ▁sesuatu ▁ben ca na ▁di se bab kan ▁apa ▁yang ▁telah ▁dilakukan ▁oleh ▁tangan ▁mereka ▁sendiri , ▁ti ba - ti ba ▁mereka ▁ber put us ▁asa .
▁Bagaimana ▁kalau ▁Taylor ▁adalah ▁bu kti ▁yang ▁kau ▁perlu kan ?
▁Hanya ▁mereka ▁boleh ▁ber ko ng si ▁ke ajai ban ▁Tuhan .
▁Lebih ▁baik ▁aku ▁tinggal kan ▁band ar .
▁Ker ja ▁cepat . ▁Kami ▁dalam ▁perjalanan .
▁Tidak ▁jika ▁tiada ▁pas aran ▁yang ▁ingin ▁men ju al nya .
▁Adakah ▁ke per ca ya an ▁dari mu , ▁cinta .
▁Gu ra u ▁saja ▁.. He i , ▁apa ▁ini ▁dengan ▁be zel ▁yang ▁ada ▁disini ?
▁- ▁Kem bali ▁ke ▁Sy ur ga , ▁ku kira .
▁Ayah , ▁berse dia .
▁La lu ▁Bu gs ▁ ck p , ▁" E h , ▁kenapa ▁kau ▁menu angkan ▁mi ny ak ▁di ▁kepala ku ?"
▁* ▁Aku ▁tak ▁mahu ▁kau ▁meninggalkan ku ▁*
▁Se gala nya ▁ok
▁Pu sat ▁internet ▁dunia ▁di ▁Os lo .
▁Tapi ▁apa ▁yang ▁saya ▁tahu ▁sekarang ▁Itu ▁( Be cker ) ▁mahu , ▁Ma ti ▁dan ▁tidak ▁akan ▁ke ber atan ▁kalau ▁kita ▁membunuh ▁dia ▁juga
▁Joe , ▁apa ▁yang ▁kau ▁har apkan ▁kami ▁nak ▁buat , ▁kawan ?
▁Band uan ▁pada ▁ja ng ka ▁telah ▁dik esan ▁dalam ▁platform ▁6, ▁i a ▁adalah ▁dengan ▁seorang ▁lelaki .
▁Saya ▁me mbe li ▁bahagia n ▁untuk ▁Ra bbi t .
▁Ju ru tek nik ▁tak ▁ guna .
▁Saya ▁me nger ja kan ▁itu ▁untuk ▁diri ▁saya ▁sendiri .
▁Anda ▁ken al ▁lelaki ▁Bon d , ▁inte l ▁lelaki
▁Ra tu ▁hita m .
▁Con to h : ▁se bol @ ja b ber . org
▁Kami ▁ter lu pa ▁yang ▁kamu ▁ialah ▁Po oja , ▁dan ▁kamu ▁ada ▁kehidupan ▁per iba di ▁kamu . . ▁.. ▁dan ▁h ubung an ▁dan ▁kom it men ▁yang ▁lebih ▁penting
▁Se kali ▁lagi ! ▁100 ! ▁- ▁100 !
▁- ▁Tidak .
▁Men er usi ▁la mpu ▁me rah ▁dan ▁me lang gar ▁belakang ▁kereta .
▁Hai , ▁kawan - ka wan .
▁Saya ▁melihat ▁C risti ano ▁seperti ▁anak . ▁Seperti ▁anak ▁yang ▁se benar .
▁Kita ▁kena ▁ lari ▁dari ▁orang ▁ini , ▁siapa ▁pun ▁dia ▁itu !
▁Aku ▁bersama ▁Cu tter .
▁Dengan ▁bang ga ▁ nya ▁saya ▁per sem b ahkan ▁lelaki ▁bu di man ▁ini , ▁Yang ▁tidak ▁lain ▁lagi ▁dari ▁lag enda ▁maha ra ja ▁We i wu ▁gener asi ▁moj in ▁yang ▁ke ▁82 ▁Tiada ▁lain ▁lagi ▁pen curi ▁maka m
▁Pen yun ting an ▁skr in ▁se akan - E mac s ▁minimum ▁diso ko ng . ▁Pel eng ka pan ▁sena rai ▁TA B . ▁Te kan ▁Ctrl - x ▁atau ▁F 10 ▁untuk ▁but , ▁Ctrl - c ▁atau ▁F 2 ▁untuk ▁bar is - p erintah ▁atau ▁E SC ▁untuk ▁ sing kir kan ▁sunt ing an ▁dan ▁kembali ▁ke ▁menu ▁ GR UB .
▁Jadi ▁sele pas ▁Yo m ▁Ki pp ur ▁selesai , ▁kita ▁pergi ▁dari ▁sini .
▁Sul tan , ▁kamu ▁akan ▁di bela sah ▁hari ▁ini .
▁Dia ▁Krist ian i .
▁Anda ▁tahu , ▁s qui r ming , ▁seperti , ▁" apa ▁yang ▁pa lang ▁pintu ▁itu ?"
▁Tapi , ▁masih ▁tak ▁jumpa .
▁Ia ▁besar , ▁ge lap .
▁Boleh ▁awak ▁p indah kan ▁mereka ?
▁Ia ▁ke put us an ▁suka r ▁tapi ▁buat lah .
▁Sekarang dia ha nya per lu 1 to uch down ▁lagi ▁untuk ▁mem ec ahkan ▁re kod .
▁Lu i , ▁macam ▁mana ▁dengan ▁Ka la ?
▁Aku ▁ingat ▁ada ▁sesuatu ▁di ▁dalam nya .
▁Gun ▁bisa ▁menggunakan ▁ini ▁ke ra cun an ▁makan an ▁untuk ▁Ma ster ▁Hu o ▁...
▁Pergi ▁ke ▁la man ▁ter da hulu
▁Apa ▁awak ▁buat ▁pada ▁dia ?
▁Ia nya ▁di ▁ge lar ▁As ce ndan t .
▁Awak ▁telah ▁melalui ▁tu ju h ▁pe mbe da han , ▁betul ?
▁Dengar ▁sini ...
▁Saya ▁tak ▁tahu ▁nas ib ▁saya ▁pada ▁masa ▁akan ▁datang .
▁Jika ▁awak ▁fikir ▁saya ▁tak ▁wara s , ▁saya ▁faha m .
▁Kami ▁akan ▁mun cul ▁di ▁si si ▁kan an ▁seja rah .
▁U U ID ▁untuk ▁per anti ▁yang ▁digunakan .
▁" A da lah ▁suka r ▁untuk ▁ber und ing ▁dengan ▁ nya "
▁Aku ▁tak ▁akan ▁meno long ▁kamu
▁ ♫ Lo ve is ▁ . ♫
▁Kau ▁ada ▁nampak ▁dia ▁di ▁mana - mana ?
▁Yo ng - se ok !
▁Sekarang ▁waktu nya ▁kita ▁perlu ▁ber hati ▁- ▁ha ti .
▁Kau ▁boleh ▁memilih ▁untuk ▁meno lak ku ▁ .
▁Tak ▁boleh ▁begitu !
▁- ▁Bi ar kan ▁saya ▁berse orang an .
▁Kir a - kira ▁satu ▁bat u ▁se ten ga h .
▁Pel in dung mu !
▁O key , ▁sangat ▁baik .
▁Ak tif kan ▁but ang ▁peng u bah ? ▁Mas uk kan ▁y ▁atau ▁n :
▁Pe sur uh ja ya ▁Da vis , ▁New ▁York ▁Post ▁me la por kan ▁seorang ▁pe mu da ▁20 ▁tahun ▁dari ▁Arab ▁Sa udi ▁telah ▁di tahan .
▁Ia ▁bukan ▁ber si fat ▁per ka u man ▁jika ▁aku ▁mengatakan nya .
▁Saya ▁me lar ikan ▁diri ▁bersama nya , ▁maka ▁ayah ▁dia ▁ma rah .
▁Aku ▁banyak ▁kerja , ▁jadi . ...
▁Sekarang ▁saya ▁sedang ▁mencari ▁sam bung an ▁yang ▁lebih ▁em osi .
▁Ia ▁sangat ▁men ak ju b kan .
▁Saya ▁tidak ▁perlu ▁lagi ▁orang ▁menunggu ▁di ▁me - - ▁Orang - orang ▁yang ▁saya ▁akan ▁los e - ▁- ▁Me lain kan ▁anda ▁manusia ▁dan ▁mendapatkan ▁beberapa ▁Co jon es , ▁comprend e ?
▁Tak kanlah ▁kita ▁saja ▁yang ▁masih ▁hidup .
▁Semua ▁per atura n ▁per sat uan ▁ter tul is ▁di ▁si tu .
▁Dan ▁Ayah ▁fikir ▁i a ▁akan ▁membuat ▁Ibu ▁kamu ▁ber asa ▁sele sa ▁disini .
▁Yeah .
▁Dan ▁kamu , ▁mi mpi kan ▁seseorang , ▁yang ▁kamu ▁tak ▁pernah ▁jumpa !
▁Ata u ▁Cor n - D og ▁Per anci s ?
▁Ay uh , ▁da f tar ▁gera i ▁itu , ▁dia ▁berada ▁di ▁sini .
▁Kau ▁cakap ▁pada ▁dia . ▁kau ▁kena ▁tahan ▁kerana ▁menjadi ▁sus pek ▁ke curi an ▁kereta .
▁An tara ▁Facebook , ▁In sta gram , ▁dan ▁Flickr , ▁orang - orang ▁menga wa si ▁diri ▁mereka .
▁- ▁" K en apa ?
▁Nick ber hen ti untu k me mbe li untu kka mu .
▁Kamu ▁cuba ▁gert ak ▁aku ?
▁Kau lah ▁yang ▁akan ▁berada ▁dalam ▁masalah .
▁Awak ▁se pat ut nya ▁pergi , ▁tu an , ▁sebelum ▁dia ▁menembak ▁lagi .
▁Saya ▁minta ▁maaf ▁bahawa ▁anda ▁ter ke jut ▁lang kah ▁dis ip lin ▁ini .
▁Saya ▁nak ▁uru s kan ▁pe ja bat ▁du lu .
▁Da lam ▁air , ▁sebe lah ▁sana .
▁Kau ▁tahu ▁kenapa ▁ku da ▁yang ▁bagus ▁tidak ▁mahu ▁makan ▁rum put ▁yang ▁tu mbu h ▁kembali ?
▁So alan ▁Men a rik , ▁wa lau pun .
▁Lee ▁Jung - ja , ▁Jung ▁Ko ok - s up , ▁Kim ▁You ng - shin .
▁- ▁I kut ▁na ik ▁kereta ▁saya .
▁Le wat ▁e mpat ▁pul uh ▁tahun ?
▁Be lum ▁pernah ▁aku ▁melakukannya ▁da hulu .
▁- ▁Ke pada ▁Dan e law .
▁Ra lat ▁memba ca ▁fail ▁'% s ' : ▁% s
▁So alan ▁penting .
▁Be liau ▁telah ▁berubah ▁wa jah ▁dan ▁ba dan .
▁Men cu ba ▁sesuatu ▁yang ▁baru ?
▁Awak ▁seorang ▁pe lang gan , ▁bukan ?
▁Se gala ▁sesuatu nya ▁penting ▁sekarang
▁Sekarang ▁kau ▁menjadi ▁som bo ng .
▁Aku ▁mengha bis kan ▁banyak ▁u ang ▁untuk ▁itu .
▁Tapi ▁mani s ▁ sungguh ▁ce rita nya .
▁Aku ▁pun ▁suka ▁kau .
▁- ▁Is teri ▁Siapa ? ▁- ▁Ya .
▁Mereka ▁akan ▁menjadi ▁lebih ▁ku at ▁hin gga ▁hari ▁mend ek ati ▁ak hir .
▁- ▁Ini ▁e - mel ▁dari ▁La ura .
▁Ta hni ah ▁saudara ku . ▁Sem oga ▁di ber ka ti , ▁pergi lah ▁berse ron ok . .
▁Jadi , ▁set uju ?
▁Dia ▁beritahu ▁pada ▁saya ▁sem asa ▁makan ▁malam .
▁Charlie ▁Wa x .
▁Kita ▁harus ▁pergi . .
▁Ia itu ▁hari ▁mereka ▁keluar ▁( dari ▁ku bur ▁mas ing - mas ing ) ▁dengan ▁je las ▁ny ata ; ▁tidak ▁akan ▁ter se mbu ny i ▁kepada ▁Allah ▁sesuatu pun ▁dari ▁hal ▁keadaan ▁mereka .
▁Apa ▁kata ▁awak ▁kembali ▁kepada ▁hidup ▁dan ▁me ja ▁awak ▁yang ▁kecil ▁itu ?
▁- ▁M mm .
▁Aba ikan ▁semua ▁atau ▁( jika ▁di spesif ika s ikan ) ▁n ▁bar is ▁pertama ▁pada ▁ST DER R ▁[ pi li han ]
▁Saya ▁ba wa ▁50 ▁dolar .
▁- ▁Dia ▁mis kin .
▁Mungkin ▁ini ▁je las ▁ter lihat ▁apa ▁kalian ▁yakin ▁ini ▁bukan lah ▁per angkap ?
▁- ▁Da lam ▁kereta pi !
▁Itu ▁bukan ▁per mul aan ▁yang ▁kita ▁pat ut ▁ra nc angkan .
▁Okay , ▁memang ▁boleh ▁tahan .
▁Sudah ▁ber ta hun ▁kita ▁bersama - s ama ▁me mbang un kannya .
▁Hanya ▁apabila ▁anda ▁mendapat ▁lebih ▁a wal ▁ , ▁seseorang ▁senti asa ▁berubah ▁kem ung kin an .
▁Dia ▁kata ▁kita ▁tak ▁boleh ▁ada ▁anak .
▁Ber na fas !
▁Saya ▁tahu ▁kamu ▁suka kan ▁saya .
▁Kami ▁dengan ▁Me tro ▁ DC .
▁Kita ▁tak ▁lakukan ▁apa - apa .
▁Saya ▁bukan ▁Rom .
▁Kada ng - ka dang ▁gi la . .
▁Apa ▁yang ▁dia ▁buat ▁du lu ?
▁Ya , ▁Will .
▁Kau ▁buat ▁aku ▁nak ▁la m bung ▁masuk ▁dalam ▁tin fo il , ▁dan ▁ma kannya
▁Nama ▁Di beri
▁B ahkan ber ja ya men unda s aya ▁men dat angkan ▁pe gua m .
▁Pa da ▁tahun ▁ke lah iran ▁awak , ▁ada ▁satu ▁ram alan ▁yang ▁pe mi mpi n ▁kami ▁akan ▁di lah ir kan ▁untuk ▁me mbe bas kan ▁kami ▁daripada ▁per hamba an ▁ini .
▁Nah , ▁ini ▁semua ▁yang ▁kita ▁mili ki .
▁Ми р ный
▁Dan ▁ter uta ma ▁sekali , ▁cara ▁anda ▁mengg ali ▁hi dung ▁anda ... ▁saya ▁mencintai ▁itu ▁juga !
▁Jangan ▁cuba ▁untuk ▁menga jar ▁saya .
▁ kej adian ▁luar ▁ka wa lan ?
▁- ▁Ayah , ▁saya ▁baik ▁saja , ▁betul .
▁Le la ki ▁ber dir i ▁di ▁sebe lah ▁kiri ▁dan ▁wanita ▁kan an
▁- ▁Tidak , ▁itu ▁bukan ▁sama ▁sekali ▁apa ▁yang ▁saya ▁mahu .
▁di ▁sini ▁untuk ▁members ih kan ▁nama nya ▁daripada ▁tu du han ▁pal su
▁Adakah ▁kita ▁re bus ▁tel ur ▁untuk ▁di ku pas ?
▁- ▁Hei , ▁Angel a .
▁Se benar nya ▁Chu g ▁Run ▁adalah ▁idea ▁aku .
▁Da h , ▁berhenti ...
▁Kap al ▁mo yang ▁kau ▁ka ram ▁atau ▁ter s ada i ?
▁- ▁Saya ▁nampak ▁dia ▁sekali ▁lagi ▁hari ▁ini .
▁_ G el apkan ▁ket elu san ▁dan ▁la tar bela kan g ▁ime j :
▁Adakah ▁itu ▁akan ▁berlaku ?
▁Be tul . ▁Itu ▁dah ▁lama ▁berlaku .
▁Awak ▁bercakap ▁dengan ▁Fir a un .
▁Anim a table
▁Se ba gai ▁be kas ▁peng a wal ▁Bir o ▁Pe m buru ▁Ra ksa sa ▁ist ana ▁pertama
▁B < \ - \ - reg ex \ = > I
▁Mas uk ▁kembali ▁dengan ▁selamat .
▁Ata u ▁aku ▁akan ▁memilih ▁e mpat ▁orang .
▁Apa ▁ter aj di ▁sini .
▁A tuk ▁juga ▁pes an ▁jangan ▁pergi ▁ke ▁sana .
▁Chi ps , ▁dia m lah !
▁Tuan , ▁orang - orang ▁kita ▁ada ▁di ▁sana ! ▁- ▁- ▁Aku ▁tidak ▁peduli !
▁Uh ... ▁saya ▁suka kan ▁" The ▁Note book ".
▁Ke kas ih ku ▁dah ▁kembali . .
▁- ▁Mak , ▁dia m lah !
▁Te man ▁W ren ?
▁_ T anda kan ▁mes ej ▁sebagai ▁telah ▁di ba ca ▁sele pas
▁Kamu ▁tahu ▁apa ▁peng or ban an ▁kami ?
▁Pu teri ▁Chan d rika ▁panggil ▁saya
▁Mengapa ▁awak ▁pe si mis ?
▁- ▁Maka . ... ▁macam ▁mana ▁mungkin ?
▁- ▁Ja hat ▁ba bi ▁anda ▁Len ny !
▁Maks ud ▁saya ▁adalah . ... ▁... . ken apa ▁tak ▁ada ▁yang ▁beritahu ▁bahawa ▁saya ▁ada ▁a bang ?
▁Kalau ▁begitu , ▁u cap ▁he lo ▁kepada ▁ah li ▁keluarga ▁ter bar u .
▁_ Ka tal alu an :
▁- P elu ang ▁makan ▁malam ▁awak ▁hi lang ▁juga .
▁Te t apkan ▁makan an ▁ring an mu ▁di ▁da pur / B ye , ▁ibu
▁Saya ▁akan ▁men cam pak kan ▁du it ▁ke ▁wa jah ▁awak ▁semua .
▁Anda ▁akan ▁mem ec ahkan ▁gegen dang ▁tel inga ▁anda .
▁- ▁Aku ▁tak ▁tahu . P en er b angan ▁pertama ▁yang ▁ada ▁keluar ▁dari ▁Jer man .
▁ DEN ICE :
▁Pen on ton ▁sekali ▁ter uja ▁dengan ▁per tan ding an ▁ini .
▁Saya ▁sedikit ▁ klaus tro fo bia , ▁rasa nya , ▁... ja di ▁saya ▁mungkin ▁ada ▁masalah .
▁Oh ▁Tuhan ku , ▁jangan .
▁Oh , ▁si al . ▁Kau ▁apa ▁hal , ▁si al ?
▁- ▁Di ▁sini ▁mereka .
▁Uh , ▁uh , ▁uh , ▁tunggu ▁ke ja p , ▁jangan ▁takut .
▁Kau ▁ber mus uh ▁dengan ▁aku .
▁Pe ker ja an ▁kau ▁mem ung ut ▁sa mpah .
▁Ah , ▁mereka ▁orang ▁yang ▁baik .
▁Hei , ▁ RD .
▁Per ta ma , ▁me mand u . ▁Let akkan ▁tangan ▁pada ▁ ster eng . ▁- ▁Okay .
▁Bagaimana ▁keadaan ▁ibu mu ▁?
▁... s aya ▁ber ca dang ▁untuk ▁keluar ...
▁Kami ▁sedang ▁u lang ka ji ▁di ▁sini .
▁Ma lah ▁rumah ▁pak ci k ▁pun ▁ber kun ci .
▁Men gam bil ▁e kor .
▁Will ie , ▁kau ▁tak ▁harus ▁bunu h ▁orang ▁ni , ▁kawan .
▁Kita ▁akan ▁dapat kan ▁S mur fett e .
▁Boleh ▁saya ▁tahu ▁siapa ▁anda ▁bercakap ▁dengan ?
▁Anda ▁ter ke san ▁ayah ku , ▁yang ▁tidak ▁mu dah .
▁Dan ▁bukan lah ▁engkau ▁( wa hai ▁Muhammad ) ▁yang ▁mele mpar ▁ketika ▁engkau ▁mele mpar , ▁akan ▁tetapi ▁Allah ▁ju a lah ▁yang ▁mele mpar ▁( untu k ▁mem bina s akan ▁orang - orang ▁kafir ) , ▁dan ▁untuk ▁mengu rni akan ▁orang - orang ▁yang ▁beriman ▁dengan ▁peng ur nia an ▁yang ▁baik ▁( ke men angan ) ▁daripada Nya .
▁Tapi ▁saya ▁tak ▁boleh ▁bunu h ▁orang .
▁Saya ▁akan ▁minta ▁pi ha k ▁bank ▁buat kan ▁satu ▁untuk ▁saya .
▁A la mat ▁E mail
▁Kamu ▁hampi r ▁kehilangan ▁tangan mu ▁ ayo lah , ▁Su nggu h ?
▁Selamat ▁datang ▁di ▁keluarga ▁kami
▁Mel ina ▁tahu ▁tentang ▁Od essa . ▁Dia ▁dalam ▁perjalanan ▁ke ▁sana .
▁Kami ▁ambil ▁bis nes ▁ini ▁untuk ▁pen didi kan
▁Anda ▁menga la mi ▁O SD , ▁yang ▁me rup akan ▁kein gin an ▁seks ual ▁ke ter la lu an .
▁Tidak ▁tidak ▁... ▁Awak ▁tak ▁pa yah ▁pergi ▁...
▁Dia ▁tak ▁cakap .
▁Pod rac ing .
▁Kami ▁berse mbu ny i ▁dalam ▁rok et ▁peng ga lak ▁dan ▁tunggu ▁i a ▁ter pis ah ▁dan ▁jatuh ▁ke ▁la u tan ▁Atlant ik ▁seperti ▁yang ▁dira nc angkan .
▁Saya ▁nak ▁katakan ▁itu lah .
▁Awak ▁nak ▁minu man ?
▁Anda ▁tidak ▁ge mbi ra ▁melihat ▁dia ?
▁Ke pada ▁saudara ▁Henry ... ▁kehidupan ▁di ▁Spring field ▁tak lah ▁begitu ▁se ron ok .
▁Jadi ▁i a ▁adalah ▁' Ba ju ▁mati ' .
▁Plan k ton ▁sangat ▁ spesif ik .
▁Ke pul a uan ▁Ca y man ▁Name
▁Bru no ▁64 ▁akan ▁menu run kan ▁tal i .
▁Awak ▁kena ▁ke mas kan ▁bara ng ▁awak ▁dan ▁ba wa ▁semuanya ▁ke ▁mana ▁pun ▁awak ▁pergi .
▁Dan ▁saya ▁ada ▁sa ksi ▁yang ▁mengatakan ▁dia ▁nampak ▁je rung ▁berjalan ▁atas ▁jalan , ▁manusia ▁je rung .
▁Kalau ▁apa ▁Ga ito nde ▁cakap ▁betul , ▁mak na nya ▁semua ▁bil ▁tu ▁pal su .
▁Me riam ▁besar !
▁Dia ▁ok ▁ke ?
▁" S ela lu ▁melihat ▁ke ▁de pan ."
▁Hel zi nger .
▁< name > ▁< data _ de vice > ▁< ha sh _ de vice > ▁< ro ot _ ha sh >
▁' D esti ny ' , ▁ke ▁de pan ▁hi bur kan ▁kami ▁dengan ▁je na ka ▁kamu ▁berdua !
▁Dan ▁mereka ▁di ti mpa ▁la k nat ▁( yang ▁tidak ▁putu s - put us ) ▁dalam ▁dunia ▁ini ▁dan ▁pada ▁hari ▁kiam at .
▁Aku ▁mengerti ▁kita ▁berada ▁dalam ▁per ang ▁untuk ▁ber tahan ▁hidup .
▁Dia ▁tak ▁tahu ▁dengan ▁siapa ▁ger angan ▁dia ▁bercakap .
▁Stat us
▁- ▁Dia ▁adalah ▁di ▁dalam ▁kereta ▁ti ga .
▁Tapi ▁tunggu ▁saja ▁bila ▁saya ▁keluar ▁nan ti ,
▁Ka ke k , ▁me mbu ang ▁u ang ▁di ▁wa jah ▁mereka !
▁Max ie , ▁saya ▁mahu ▁memberitahu ▁anda ▁banyak ▁kali , ▁tetapi ▁i a ▁adalah ▁terlalu ▁berba haya .
▁Peng ga lak
▁Aku ▁tak ▁pernah ▁Lihat ▁John ▁Stock ton ▁se ge mbi ra ▁sebe gin i .
▁Ada ▁yang ▁ingin ▁ber tu kar ▁wata k ?
▁Per law anan ▁pe mbu kaan ▁gus ti ▁Pro ▁Tak e - Down .
▁awak ▁mem ging atkan ▁saya ▁bahawa ▁akan ▁ada ▁kes an ▁yang ▁tidak ▁di ing in kan , ▁dan ▁saya ▁menghi ra u kannya .
▁" I t ▁is ▁a ▁new ▁feel ing ."
▁- I ' m ▁sebenarnya ▁mati ▁se rius ▁tentang ▁itu .
▁ba si kal ▁me rah , ▁to pi ▁ kele dar ▁me rah .
▁Bay ang - ba yang ▁ber tam bah ▁ panja ng , ▁begitu lah ▁mata hari ▁men ci um ▁u fu k ▁bara t ▁peng u bah ▁ca haya ▁menye ram kan ▁atas ▁ke ber ania n ▁kami ▁dan ▁begitu ▁juga ▁Pat chi .
▁$ IM _ C ON FI G _ MS G ▁Pil ih ▁konfigur asi ▁automat ik : ▁$ IM _ C ON FI G _ A UT OM ATI C ▁$ IM _ C ON FI G _ A UT OM ATI C _ LO NG ▁$ IM _ C ON FI G _ RT FM
▁Kau ▁tidak ▁boleh ▁mena kut kan ▁aku ▁sekarang .
▁Tengo k lah , ▁siapa ▁yang ▁cepat ▁dia ▁yang ▁dapat .
▁Aku ▁suka ▁kereta ▁ni .
▁Dia ▁kata ▁mak ▁cik ▁Maggie ▁perempuan ▁ja lang ▁dan ▁pada n ▁muka ▁dia .
▁- ▁Ada ▁s orang ▁a we k , ▁" ber ry " ▁sex y ▁( san gat ▁se ksi ) .
▁Aku ▁yakin ▁rumah ▁yang ▁jatuh ▁pada ▁anda ▁yang ▁akan ▁menjadi ▁rumah ▁yang ▁se ksi .
▁Ya , ▁ter ima ▁kasih ... ▁kita ▁akan ▁mena ik kan ... ▁hor mon ▁ke ker asan ▁dalam ▁diri ▁mereka .
▁O key , ▁bagi ▁nom bor ▁mereka .
▁Thu mb na il
▁Awak ▁belum ▁pernah ▁buat ▁seks ▁selama ▁90 ▁mini t .
▁Kamu ▁me sti ▁me mul angkan ▁untuk ▁tempat ▁anda . .
▁Ibu ▁ba pa ▁Ele na .
▁Merc ado ?
▁Seperti nya ▁peng a du ▁ter ima ▁bala san .
▁Saya ▁akan ▁mendapat ▁semua ▁em as ▁di ▁ini .
▁Saya ▁tak ▁boleh ▁hidup ▁dengan ▁itu .
▁Kau ▁yang ▁tuli s ▁tu ?
▁# ▁Then ▁I ▁would ▁thank ▁that ▁star
▁Ra mai ▁orang ▁yang ▁ta mpan .
▁Aku ▁mahu ▁mus na h kannya .
▁Le la ki ▁dengan ▁tu bu h ▁ba ja ...
▁Aku ▁tahu . ▁Dan ▁kita ▁mengatakan ▁kita ▁akan ▁melakukan ▁semuanya ▁bersama - s ama .
▁Dia ▁berada ▁di ▁dalam ▁keadaan ▁menu run .
▁tiada ▁apa . ▁saya ▁cuma ▁-- ▁saya - s aya ▁maksud kan ... ▁kalau ▁ada ▁sesuatu ▁yang ▁tak ▁kena ...
▁- ▁Se ron ok , ▁bukan ?
▁Kau ▁me sti ▁fikir ▁aku ▁ni ▁perempuan ▁mur ahan .
▁Ed ▁fikir ▁aku ▁Al f . ▁dan ▁i a ▁terus ▁terus - mene rus ▁dengan ▁komen ▁anti ▁se mi tic .
▁Saya ▁salah . . ▁sangat ▁salah
▁Se benar nya ▁aku ▁juga ▁mamp u ▁merasa kan ▁saya p ▁itu . ▁/ ▁Le i .
▁Jika ▁dia ▁mati , ▁aku ▁mati .
▁Saya ▁nak ▁be li ▁kopi ▁untuk ▁6 ▁orang
▁Ra dar ▁dari ▁dia ?
▁Oh , ▁kau ▁akan ▁bera yun ... ▁tidak , ▁tidak , ▁tidak , ▁nan ti , ▁nan ti
▁Bu at ▁pu ku lan ▁sa al tu .
▁Awak ▁pernah ▁dengar ▁Tri ton ?
▁6 ▁[ jum lah ▁pen uh ▁6 ]
▁Vi rus ▁dan ▁bak teria ▁ ang kas a ▁yang ▁membawa ▁ma ut .
▁Jadi , ▁apa ▁yang ▁dia ▁lihat ?
▁Sekarang ▁kita ▁hi lang ▁25 ▁ ribu .
▁- ▁Tidak , ▁awak ▁dengar lah .
▁Andre a , ▁Ku ch ta , ▁awak ▁putu s kannya ?
▁Dia ▁sudah ▁mene mu i ▁pe nye les ai annya .
▁Stop !
▁Ia ▁mu dah ▁untuk ▁lihat ▁tun gga kan ... ▁kadar ▁as as ▁te nga h ▁mening kat ▁sekarang ▁ni !
▁Dan ▁saya ▁memberitahu nya ▁bagaimana ▁kita ▁boleh ▁men angkap ▁mereka ▁pe ga wa i ▁yang ▁di tana m ▁da dah ▁di ▁Yo landa .
▁Kami ▁me sti ▁meng i kut ...
▁Bara t ▁dan ▁U tara .
▁Hei , ▁tahu , ▁la ki - la ki .
▁Orang ▁itu ▁ke can du an .
▁dengan ▁objekt if ▁untuk ▁menu mpa s kan ▁Esc o bar .
▁- ▁Tu ju an ▁ke dat angan ▁kamu , ▁doktor ?
▁Jadi ▁saya . ... ▁Awak ▁tahu - ta hu lah .
▁Itu ▁bahagia n ▁terakhir ▁dari ▁ ratu ▁yang ▁saya ...
▁Rum ah ▁ini ▁bukan ▁lagi ▁untuk ▁law atan ▁go long an ▁bawah an .
▁- ▁Saya ▁boleh ▁mengu ji .
▁- ▁Maafkan ▁saya . ▁- ▁Sil vana ▁bera ni nya ▁awak ▁ba wa ▁dia ▁dalam ▁rumah ▁ini .
▁Aku ▁bisa ▁me lat ih ▁banyak ▁dengan ▁te man - te man ku .
▁Saya ▁kena ▁bekerja ▁dengan nya .
▁A kan ▁ada ▁jam uan ▁besar an .
▁- ▁Bukan ▁ber ken aan ▁ba ju nya .
▁Aku ▁benar - benar ▁men anda inya ▁ tang gal , ▁8 ▁Oktober ▁2002 , ▁Dan ▁sisa nya ▁adalah ▁seja rah ...
▁fly er ▁yang ▁anda ▁menunjukkan ▁kepada ▁saya
▁Se jak ▁itu ▁kami ▁tak ▁pernah ▁ber bu al .
▁Saat ▁aku ▁meninggalkan ▁des a ▁dan ▁i kut ▁ber per ang ▁bersama mu , ▁aku ▁sudah ▁pernah ▁bilang .
▁.. apa bila ▁mereka ▁tahu ▁yang ▁ibu ▁akan ▁kembali .
▁- ▁Me sti lah ▁saya ▁ge ment ar .
▁Ben ar kah ▁ingin ▁keluar ▁daripada ▁Lyn x ?
▁Nama :
▁Bog gar t , ▁mereka ▁tidak ▁ge mar ▁air .
▁_ Li hat
▁Ke ▁rumah ▁sakit , ▁untuk ▁melihat ▁ayah ▁Lu cky .
▁Ya , ▁aku ▁mene mu i ▁dia ▁ kel mar in ▁di ▁ste sen ... ▁boleh kah ▁anda ▁men ja ga nya ▁sehingga ...
▁Si la ▁jag a ▁bag asi ▁awak .
▁Dar i ▁S lo an . ▁dari ▁ku mpu lan , ▁dari ▁Ja nice , ▁dari ▁la por an ▁ke wanga n , ▁dari ▁ keyboard ▁er go nom ik , ▁dari ▁te man ▁wanita ▁cur ang ▁dan ▁kawan ▁tak ▁ guna .
▁[ o ] ▁- ▁ke kal ▁ta rik h ▁as al
▁saya ▁fikir ▁begitu .
▁Sem oga ▁kamu ▁boleh ▁tidur .
▁Oh , ▁tu han ▁ku .
▁- ▁Do ry , ▁ini ▁saya , ▁De sti ny .
▁Nan dini !
▁Saya ▁mahu ▁lihat ▁ke ▁mana ▁i a ▁menga li r ... ▁Oh , ▁ada ▁sebuah ▁gun ung ▁yang ▁tidak ▁pernah ▁di ta wan ...
▁Tu ju h ▁blok ▁u tara , ▁dua ▁blok ▁tim ur .
▁Ke tika ▁saya ▁dit emp atkan ▁di ▁sini , ▁kami ▁gun akan ▁bawah ▁tan ah ▁sebagai ▁guda ng ▁senjata .
▁" He i , ▁Charlie ."
▁Dan ▁mereka ▁tahu ▁bahwa . . ▁ya h , ▁kau ▁tahu . .
▁- ▁Aku ▁sedang ▁bercakap ▁tentang ▁Al var o !
▁Ada ▁yang ▁me mas ang ▁tar u han ▁untuk ▁The ▁G lo be ?
▁Sa lah ▁satu ▁waktu ▁pa ling ▁si buk ▁satu ▁ben ca na ▁a lam ... ▁untuk ▁lelaki ▁macam ▁awak ▁dan ▁saya .
▁Di ▁tempat ▁dia ▁selalu ▁berada .
▁ ** GA GAL ** ▁Peng eko dan Ba ha sa ▁% s ▁ter uk ▁- ▁me sti ▁dalam ▁ISO La tin 1 .
▁Kami ▁jumpa ▁dia ▁bawah ▁lub ang ▁dia ▁The ▁Pi pe line .
▁Mereka ▁masih ▁per ja nji an ▁itu .
▁Ini ▁adalah ▁ tang kal ▁Som de j , ▁i a nya ▁ber ni lai ▁ju taan ▁Bah t .
▁Pat ut kah ▁kita ▁ ikat ▁dia ?
▁-- no - gui ▁Jangan ▁ guna ▁GUI ▁GTK ▁wa lau pun ▁i a ▁ter se dia .
▁Baik , ▁aku ▁kembali ▁bes ok .
▁Dan ▁saat ▁kau ▁pulang , ▁Kau ▁tidak ▁membawa ▁per ma sala han ▁ ts b ▁ke ▁keluarga mu .
▁- I tu ▁sy a mpu .
▁Ini ▁Rock ste ady .
▁Saya ▁tak ▁tahu ▁kenapa ▁saya ▁cakap ▁dengan ▁begitu ▁berse manga t , ▁tapi ▁i a nya ▁heb at ▁kita ▁di ▁sini ▁bersama , ▁betul ?
▁Ya , ▁d gn ▁lan car , ▁u ja ng .
▁Se bab ▁itu lah ▁saya ▁me mand u ▁per lah an ...
▁Tengo k , ▁saya ▁pasti ▁kamu ▁tak ▁mahu ▁si as atan ▁ini ▁mendapat ▁per hati an ▁a wa m ▁dari ▁sekarang ▁ini , ▁bukan ▁begitu , ▁doktor ?
▁Ini ▁me rup akan ▁pen em uan ▁ter bes ar ▁se jak ▁pen em uan ▁" K ing ▁Tu t "
▁- ▁Katakan ▁pada ▁saya , ▁kenapa ▁dia ▁di ▁sini ?
▁Ini lah ▁video ▁yang ▁pa ling ▁menga n cam .
▁Ca haya ▁hija u ▁terjadi ▁masa ▁mata hari ▁ter ben am , ▁bukan ▁masa ▁ter bit .
▁- ▁Itu ▁peng a wal ▁kau .
▁Dia ▁me la mpa u lah !
▁Ia ▁ada ▁pe mas a .
▁Inga t ▁se ku mpu lan ▁perempuan ▁tua ▁ta di ?
▁Mari ▁sini ▁apa kah ▁dia ▁anti - in fla mma tori es , ▁menye mbu h ▁ambil ▁hari ▁ , ▁bukan ▁mi nggu ▁ .
▁Ay uh lah , ▁apa nya ▁yang ▁menye ron ok kan ▁dari ▁itu ?
▁Sekarang , ▁jika ▁awak ▁meminta ▁maaf ▁pada ▁saya ▁Saya ▁ada ▁sesuatu ▁untuk ▁digunakan ▁bi lik ▁anak ▁lelaki ▁kecil ▁we e - we e
▁- ▁Aku ▁dah ▁beritahu ▁yang ▁aku ▁sayang kan ▁kau .
▁- ▁Orang ▁yang ▁ber dika ri .
▁Apa ▁yang ▁kau ▁lakukan ?
▁hipo ten us , ▁satu ▁yang ▁baik .
▁- ▁Ya , ▁ayah ▁kita ▁sangat ▁ kela kar .
▁Ia nya ▁adalah ▁sebuah ▁be kas ▁tan ah ▁per ku bur an .
▁Ya , ▁aku ▁dan ▁kawan - ka wan ▁akan ▁ke ▁sana .
▁Ba wa ▁Pen guin ▁ke ▁sini .
▁Ke la kar ▁bu ny inya ▁dia ▁bercakap .
▁Me maka i ▁ paka ian ▁jin gga , ▁ku ▁menjadi ▁pe mu ja ...
▁- ▁Aku ▁akan ▁melakukan ▁up aya ▁terbaik ▁saya
▁Jangan ▁te kan ▁terlalu ▁ku at , ▁baik ?
▁dan ▁mengu rung ▁saya ▁dalam ▁bone t , ▁dan ▁kemudian ▁dia ▁nak ▁ber baik , ▁mul akan ▁sem ula .
▁Pe lang gan ▁( Re ese ) ▁Saya ▁punya ▁kein gin an ▁Ke per ca ya an ▁sebelum ▁menye r ahkan ▁wa ng
▁A bang ▁I p .
▁Oh , ▁É mili en !
▁~ ▁Isi ▁ha ti ▁kamu ▁dengan ▁war na .
▁Tu n juk kan ▁mereka ▁apa ▁yang ▁kita ▁ada .
▁Kau ▁terlalu ▁me mi kir kan ▁ben da ▁yang ▁tak ▁w uju d
▁Bi ar ▁dia ▁di pen ja ra ▁sebe ntar .
▁Se se orang ▁di p ang gil ▁Long ▁Q i ▁telah ▁mening kat ▁melalui ▁pa ngkat .
▁Anti ji rim ▁hanya ▁per mul aan .
▁Dim ula i ▁dari ▁per i ngkat ▁satu ▁dunia ▁as al ▁Oklahoma , ▁Ja red ▁Mid dle ton !
▁- ▁Ada ▁aku ▁sur uh ▁kau ▁ buka ▁mu lut ?
▁Kau ▁menyukai ▁ini !
▁Ci pta ▁vers i ▁simbol ▁la lai ▁untuk ▁simbol ▁ter import
▁Dan ▁besar ▁lelaki , ▁Le la ki ▁yang ▁mem bina ▁ lega si , ▁mereka ▁tidak ▁senti asa ▁baik .
▁N SA ▁ini ▁mene t apkan ▁anda .
▁Kau ▁tak ▁sa nggu p ▁sebab ▁di ▁bawah ▁ku asa ▁itu , ▁masih ▁ada ▁diri ▁kau .
▁Kenapa ▁kamu ▁ter ima ▁ arahan ▁saya ?
▁Saya ▁cakap ... ▁ba lik !
▁- ▁Tak , ▁akan ▁ada ▁orang ▁jag a ▁kan ak - kan ak ▁itu .
▁.. and ▁Saya ▁bi mbang
▁Ci ri - ▁cir i
▁Jika ▁ada ▁ber ita ▁dari nya , ▁aku ▁lang s ung ▁pergi .
▁Du a ▁orang , ▁aku ▁akan ▁ ganda kan ▁up ah mu , ▁tetapi ▁harus ▁selesai kan ▁pagi ▁es ok .
▁Aku ▁masih ▁ingin ▁mati . ▁Tapi ▁aku ▁ingin ▁kembali ▁dan ▁menyelamatkan ▁pen u mpan g ▁kereta ▁a pi ▁du lu .
▁Co ba ▁Anda ▁pikir ...
▁- ▁Tak , ▁dua ▁orang ▁sudah ▁mati .
▁Yeah .
▁Ta han , ▁tak ▁perlu ▁ke ker asan .
▁Helen a , ▁Saya ▁su mpah ...
▁Ter uta ma ▁awak , ▁Ve ge ta - san , ▁terlalu ▁sangat ▁cu ai .
▁Katakan lah ▁( wa hai ▁Muhammad ): ▁" Se mu a nya ▁itu ▁( ke ba ikan ▁dan ▁ben ca na ) ▁adalah ▁( ber pun ca ) ▁dari ▁si si ▁Allah ".
▁Ce tak ▁re kod ▁tidak ▁boleh ▁di pas ang ▁dari ▁fail ▁yang ▁di nya ta kan ▁( s ama ▁ada ▁1 ▁atau ▁2)
▁A tuk ▁dah ▁kata , ▁tak ▁pa yah ▁datang ▁setiap ▁hari .
▁- ▁Nah , ▁apa kah ▁itu ▁anda ?
▁Wal au pun ▁dunia ▁mengha lang mu ...
▁Inga t lah ▁itu , ▁Pete .
▁Sa la am ▁Al ai kum , ▁pak ci k
▁Mu m , ▁anda ▁menge na li ▁saya ?
▁Ka wan , ▁saya ▁kena ▁bay angkan ▁awak ▁tak ▁boleh ▁menyelamatkan ▁hari ▁ini ▁tanpa ▁membuat ▁hur u - hara .
▁- ▁Ayah ▁seorang ▁yang ▁ja hat ?
▁kun ci ▁kli en
▁Ka li ▁ini ▁ada ▁boleh ▁menjadi ▁tidak ▁sy ak ▁lagi ▁... ▁Bu dak ▁itu ▁tidak ▁menga la mi , ▁Tuhan ku , ▁yang ▁saya ▁boleh ▁men ja min .
▁Ay uh !
▁Hent ikan !
▁Ke ga ga lan
▁Kami ▁memang gil nya ▁karena ▁i a ▁selalu ▁mengatakan : ▁- ▁Lihat ▁ke ▁mata ku .
▁Anda ▁harus ▁tahu ▁sekarang ▁bahawa ▁anda ▁tidak ▁boleh ▁memiliki ▁segala ▁sesuatu ▁yang ▁anda ▁ingin kan .
▁Kau ▁akan ▁melihat ▁semuanya ▁nan ti .
▁Tunggu , ▁apa ▁sekarang ?
▁Te ta pi jika anda ada lah s atu ▁an ca man ?
▁Ayah , ▁dah ▁tam bah ▁air .
▁- ▁Itu pun ▁dia .
▁Bila ▁aku ▁se but ▁nama ▁maj ikan ▁kau , ▁kau ▁kata ▁" Ya ".
▁La mpu ▁jalan ▁itu ▁ro sak ▁lagi .
▁" Ja di ▁kami ▁pergi ▁ke ▁bi lik ▁saya , ▁dan ▁te ka ▁apa ▁yang ▁dia ▁ tunjukkan ▁kepada ▁saya ?"
▁sha ru zza man @ ▁my real box . ▁com
▁Te t apkan ▁lalu an ▁gel in tar ▁pus taka ▁ter ko ng si ▁masa ▁pa u tan
▁Ada ▁bi da an ▁pe mbu kaan ?
▁Anda ▁di ▁ko bo i ▁dan ▁anda ▁mahu ▁ga za kov .
▁se bat ian ▁get ah ▁berjalan ▁melalui ▁u rat .
▁Sekarang ▁ba kar lah ▁tangan - t angan ▁itu .
▁- ▁Yeah .
▁Ky oc era ▁K M - 18 20
▁Bag i ▁kau ▁de mi ▁masa ▁de pan .
▁- ▁Saya ▁tak ▁akan ▁beritahu .
▁- ▁Se jak ▁bila ▁kita ▁jadi ▁ra kan ▁se per ju angan ?
▁T N - A 1
▁Di mana ▁dia ▁berse mbu ny i ▁selama ▁60 ▁ju ta ▁tahun ▁terakhir ?
▁Yah udi ▁me ram pas ▁ Palestin , ▁tan ah ▁air ▁kami .
▁Dan ▁( se ba lik nya ▁a mat lah ▁der haka nya ) ▁orang ▁yang ▁berkata ▁kepada ▁kedua ▁ibu ▁ba pa nya ▁( ke tika ▁mereka ▁menga jak nya ▁beriman ): ▁" A h ! ▁Bos an ▁per asa an ku ▁terhadap ▁kamu ▁berdua !
▁Hello ?
▁Di mana ▁krist al ▁itu ?
▁Dia na , ▁Tri cia , ▁Na dine ▁dan ▁Rose ▁dalam ▁perjalanan . ▁Bag us ▁kamu ▁semua .
▁- ▁( GI G GL ES ) ▁tak ▁ada ▁ik lan , ▁itu ▁di lar ang .
▁Ya , ▁aku ▁boleh ▁to long ▁kau , ▁ter uta ma ▁setelah ▁apa ▁yang ▁Te d ▁lakukan ▁pada ▁kau .
▁- ▁Dar i ▁mana ▁dia ▁datang ?
▁La in ▁kali ▁jangan ▁te gang kan ▁ba dan , ▁tena ng ▁saja .
▁Hello , ▁Li ak .
▁Tak ▁apa ▁beritahu lah .
▁Ia ▁adalah ▁mi ny ak ▁digunakan ▁untuk ▁me mbu ang ▁bol t ▁ter uta ma nya ▁de gil .
▁Dan ▁awak ▁tak ▁mengha ntar ▁mes ej ▁kepada nya .
▁Katakan lah ▁( wa hai ▁Muhammad ): ▁" Ba gai mana ▁fikir an ▁kamu , ▁jika ▁Allah ▁mele ny apkan ▁pen den gar an ▁ser ta ▁peng lihat an ▁kamu , ▁dan ▁Ia ▁pula ▁me meter a ikan ▁atas ▁ha ti ▁kamu ? ▁Siapa kah ▁Tuhan ▁se lain ▁Allah ▁yang ▁ber ku asa ▁menge mba li kannya ▁kepada ▁kamu ?"
▁Jika ▁kau ▁meny ak iti nya , ▁maka ▁aku ▁ber su mpah ▁kau ▁tak ▁akan ▁mendapatkan ▁gadis ▁kecil ▁ini !
▁Pi s ang ▁bur ung ▁un ta !
▁Aku ▁yakin ▁ibu ▁kamu ▁juga ▁ber su ara ▁seperti ▁ke lda i , ▁sem asa ▁menga n dung kan ▁kamu .
▁O key ? ▁- ▁Sem oga ▁berjaya
▁Apa ▁yang ▁kau ▁cuba ▁nak ▁bu kti kan ?
▁Ba ny ak nya ▁jum lah ▁simbol ▁kombin asi , ki ta ▁akan ▁di ▁sini ▁ber hari 2 . / ▁Tidak ▁juga ...
▁Ber kah win ▁dengan ▁ja ri ▁saya ▁untuk ▁men ce tus kan - re hat .
▁Ge mbi ra ▁bertemu ▁dengan ▁kamu !
▁Tapi - - ▁buat ▁de mi ▁dia .
▁Kata ▁ak hir ▁dalam ▁su mpah ▁se tia .
▁- ▁Ker ry , ▁kita ▁dalam ▁rumah ▁yang ▁salah !
▁sunt ikan ▁yang ▁berjaya .
▁Saya ▁kena ▁nampak ▁mena rik ▁di ▁tempat ▁kerja .
▁Ku sam ▁+ 5
▁Saya ▁dan ▁Ka t nis s ▁mahu ▁ber ko ng si ▁ke men angan ▁kami ▁dengan ▁kamu ▁dan ▁kes y uku ran ▁pada ▁Cap ito l , ▁yang ▁meny atu kan ▁kami ▁berdua .
▁Kal en dar
▁[ Bi lly ] ▁Kata ▁ak h bar ▁Pat ▁Gar rett ▁je jak ▁saya jat uh .
▁Okay , ▁okay ▁membantu ▁anda ▁me meli hara ▁ke du du kannya ▁du duk ▁di ▁te nga h - ten ga h ▁anda
▁Baiklah , ▁jumpa ▁awak ▁di ▁luar .
▁Saya ▁dengar ▁kamu ▁akan ▁masuk ▁ke lay akan ▁ren ang ▁mi nggu ▁de pan ?
▁Saya ▁kembali ▁kepada ▁kehidupan ▁yang ▁pat ut ▁saya ▁mili ki ▁sekarang .
▁Ju mpa ▁lagi !
▁Yah , ▁Ch ur ch ▁benar .
▁Dia ▁tentu ▁datang
▁Itu ▁baru ▁yang ▁pertama .
▁Tapi ▁tu gas ▁aku .
▁aku ▁dah ▁tak ▁ingat cer ita ▁se benar .
▁_ Per main an
▁baik lah , ▁i a ▁mungkin ▁membantu ▁untuk ▁mengetahui ▁siapa ▁mahu kan ▁O leg ▁mati
▁ba wa k ▁aku ▁sekali
▁Yang ▁anda ▁perlu ▁melakukan ▁adalah ▁me mu kul nya .
▁Ke ka dang ▁sakit ▁me mul ih kan ▁kes ak itan ▁yang ▁lebih ▁men dalam .
▁Z ON ▁K ANA K - K ANA K
▁Awak ▁akan ▁i kut ▁ arahan ▁saya , ▁Gi de on , ▁saya ▁Kap ten ▁awak !
▁Folder ▁destina si ▁tidak ▁w uju d . ▁Ada kan ▁anda ▁ingin ▁men cip ta nya ?
▁Mari ▁kita ▁pergi .
▁Dia ▁cuma ▁kehilangan ▁da rah .
▁Dan ▁aku ▁tant ang ▁kamu ▁masuk ▁ke ▁dalam ... ▁Dan ...
▁Kenapa ▁kamu ▁perlu ▁ber ge gas ▁mahu ▁pergi ?
▁Ber ita ▁menge jut kan .
▁- ▁Di ▁la nta i ▁4.
▁Ayo lah ▁ber ges er !
▁Yeah .
▁Sa tu ▁pe nya kit .
▁ra lat ▁dalam an : ▁to ken ▁% d ▁tidak ▁di keta hui
▁Ar gum en ▁% s : ▁Me rup akan ▁ arahan ▁format ▁dengan ▁sa iz ▁tidak ▁di benar kan ▁disini .
▁- ▁yang ▁datang ▁sehingga ▁ paha .
▁P ing gang ▁ra mping !
▁Pa da ▁masa ▁de pan , ▁dia ▁bersama ▁dengan ▁aku , ▁I ris ▁dan ▁Sa vi tar .
▁- ▁En tah lah ▁ .
▁Mengapa ▁wa jah mu ▁sed ih ?
▁Si buk ▁waktu ▁ni ?
▁Lar s , ▁ini ▁aku .
▁- ▁Kau ▁Jangan ▁sent uh ▁itu
▁Kau ▁uru s kan ▁ini , ▁dan ▁aku ▁akan ▁minta ▁ha kim ▁be bas kan ▁anak mu .
▁Sudah ▁9 ▁bul an .
▁Co yo tes ▁digunakan ▁te row ong ▁ini ▁menye lu du p ▁se ba ha gian ▁daripada ▁kita ▁keluar ▁dari ▁loro ng ▁... ▁ber das ar kan ▁peng hara pan ▁akan ▁hidup ▁yang ▁lebih ▁baik .
▁Saya ▁berkata ▁ter hen ti .
▁Kau ▁harus ▁tahu ▁hal - hal ▁di ▁K now , ▁seperti ▁kau ▁tahu ▁di ▁now .
▁Dar i ▁yang ▁aku ▁ba ca , ▁tuli s annya ▁tak ▁terlalu ▁bez a ▁dengan ▁ga m bar nya .
▁Tidak ▁boleh ▁men af sir kan ▁fail
▁- ▁Ber pul uh - pul uh ▁u ji ▁baka t .
▁" I a itu ▁orang - orang ▁yang ▁meng i kut ▁Rasul ul lah ▁( Mu ham mad ▁s . a . w ) ▁Na bi ▁yang ▁Um mi , ▁yang ▁mereka ▁dapat i ▁ter tul is ▁( na ma nya ▁dan ▁si fat - si fat nya ) ▁di ▁dalam ▁Ta ura t ▁dan ▁In j il ▁yang ▁ada ▁di ▁si si ▁mereka . ▁Ia ▁meny uru h ▁mereka ▁dengan ▁perkara - per kara ▁yang ▁baik , ▁dan ▁me lar ang ▁mereka ▁daripada ▁melakukan ▁perkara - per kara ▁yang ▁ke ji ; ▁dan ▁i a ▁mengha la l kan ▁bagi ▁mereka ▁segala ▁ben da ▁yang ▁baik , ▁dan ▁mengha ram kan ▁kepada ▁mereka ▁segala ▁ben da ▁yang ▁buruk ; ▁dan ▁i a ▁juga ▁mengha pus kan ▁dari ▁mereka ▁be ban - be ban ▁dan ▁bele nggu - bele nggu ▁yang ▁ada ▁pada ▁pada ▁mereka .
▁Tentu ▁tidak , ▁itu ▁tidak ▁panta s .
▁Data ng , ▁cinta !
▁Sel uru h ▁wil a yah ▁ini ▁hanya ▁ada ▁satu ▁pintu ▁keluar ▁masuk
▁Sekarang , ▁kita ▁kena ▁cari ▁dia ▁sebelum ▁Chuck y ▁jumpa ▁dia .
▁Kau ▁adalah ▁kepala ▁ba jak ▁la ut ▁Ye o ▁W ol ? ▁ada ▁ke per lu an ▁apa ▁datang ▁ke ▁la ut ▁yang ▁berba haya ▁ini ?
▁Dan ▁aku ▁melihat nya , ▁mereka ... ▁melihat ...
▁San gat ▁bagus .
▁Awak ▁tidak ▁pernah ▁ber ta nya ▁kepada ▁saya ▁apa ▁berlaku ▁dengan ▁Wall ace ▁malam ▁itu ▁ .
▁Ma klu mat ▁i Calendar
▁" Ma s uk kanlah ▁tangan mu ▁melalui ▁bela han ▁da da ▁ba jumu , ▁nes ca ya ▁keluar lah ▁i a ▁put ih ▁ber sin ar - sin ar ▁dengan ▁tiada ▁ca cat ; ▁dan ▁ke pit lah ▁tangan mu ▁di ▁ce lah ▁ke ti ak mu ▁ketika ▁merasa ▁takut ▁( nes ca ya ▁hi lang lah ▁takut mu ) .
▁Saya ▁bukan ▁ber maksu d ▁bersama ▁awak .
▁Ak hir nya ▁ce rah .
▁- ▁Ama t ▁me lega kan .
▁T angan ▁ni ▁ber ma gi s ▁tau .
▁saya ▁ada ▁sebab ▁untuk ▁percaya ▁bahawa ▁gang ▁yang ▁menye r bu ▁bala i ▁polis ▁untuk ▁men curi ▁may at ▁penge rus i ▁Ma ▁ada ▁kai tan ▁ ngan ▁is teri ▁dia ▁sendiri
▁Fa il ▁dalam ▁loka si ▁direktori ▁ca che : ▁% s
▁Ke rap ▁kali ▁Kami ▁melihat ▁engkau ▁( wa hai ▁Muhammad ) , ▁ber u lang - u lang ▁mene nga dah ▁ke ▁lang it , ▁maka ▁Kami ▁benar kan ▁engkau ▁ber pa ling ▁menga da p ▁ki bla t ▁yang ▁engkau ▁suka i .
▁Ber apa ▁banyak ▁lagi ▁ke ke ce wa an ▁yang ▁aku ▁perlu ▁ha da pi ▁a gar ▁kau ▁pu as ▁ha ti ?
▁Tidak ▁ kah ▁sesiapa ▁menga jar ▁kau ?
▁( De ngan ▁si kap nya ▁itu ) ▁ru gi lah ▁i a ▁akan ▁dunia ▁dan ▁a khi rat , ▁itu lah ▁ker u gian ▁yang ▁ter ang ▁ny ata .
▁Do kter ▁Do , ▁bisa ▁to long ▁ber ikan ▁com pression ? ▁Aku ▁minta ▁to long .
▁Alice , ▁apa ▁yang ▁anda ▁lakukan ?
▁Ele an or ▁membuat kannya ▁untuk ku .
▁Bas i , ▁kan ?
▁Ba wa ▁dia ▁dan ▁pergi ▁ke ▁ne raka !
▁Shar u zza man ▁Ah mat ▁Ra s lan EMAIL ▁OF ▁TRANSLATORS
▁Hadi rin ▁sekali an , ▁Sa vo y ▁Management ▁menga lu - al ukan ▁anda ▁ke ▁per tunjukkan ▁is time wa ▁pada ▁malam ▁ini .
▁Tu n _ juk kan ▁per ing atan
▁Qa zi ▁adalah ▁an ca man ▁ter bes ar , ▁sekarang ▁dia ▁sudah ▁tidak ▁ada
▁Har i ▁ini ▁ber pis ah ▁untuk ▁se ment ara , ▁Su atu ▁hari ▁pasti ▁akan ▁be ju mpa ▁kembali .
▁Ci pta ▁ke kun ci ▁baru
▁Mar vin , ▁a trop ine ▁tu , ▁sekarang !
▁Dan ▁i a ▁adalah ▁je nis ▁seperti ▁tu mpu an ▁ke - ker ja ▁dan ▁kehidupan ▁pertama ▁anda ▁perkara ▁seperti .
▁- ▁Kalau mata ▁menga n tuk ?
▁... ▁Camp uran !
▁Pergi .
▁Ta hun ▁yang ▁heb at .
▁Per atura n ▁pertama ▁saya ▁adalah ▁" har apkan ▁yang ▁terbaik , ▁ra nc angkan ▁untuk ▁yang ▁ter buru k ."
▁Ia ▁meny uru h ▁mereka ▁dengan ▁perkara - per kara ▁yang ▁baik , ▁dan ▁me lar ang ▁mereka ▁daripada ▁melakukan ▁perkara - per kara ▁yang ▁ke ji ; ▁dan ▁i a ▁mengha la l kan ▁bagi ▁mereka ▁segala ▁ben da ▁yang ▁baik , ▁dan ▁mengha ram kan ▁kepada ▁mereka ▁segala ▁ben da ▁yang ▁buruk ; ▁dan ▁i a ▁juga ▁mengha pus kan ▁dari ▁mereka ▁be ban - be ban ▁dan ▁bele nggu - bele nggu ▁yang ▁ada ▁pada ▁pada ▁mereka .
▁Jika ▁kamu ▁mahu ▁menjadi ▁pembunuh ▁dan ▁hidup , ▁kamu ▁mendapat ▁menjadi ▁satu ▁yang ▁pi ntar .
▁Da lam ▁pada ▁itu , ▁jika ▁kamu ▁me mbe lak angkan ▁juga ▁ser uan ku , ▁maka ▁tidak lah ▁menjadi ▁hal ▁kepada ku ▁kerana ▁aku ▁telah ▁sampai kan ▁kepada ▁kamu ▁apa ▁yang ▁telah ▁di utus ▁oleh ▁Allah ▁untuk ▁meny amp ai kannya , ▁dan ▁Tuhan ku ▁akan ▁mengg anti kan ▁kamu ▁dengan ▁su atu ▁kau m ▁yang ▁lain ▁( se te lah ▁kamu ▁di bina s akan ); ▁dan ▁kamu ▁pula ▁tidak ▁akan ▁dapat ▁memba haya kan Nya ▁sedikit pun .
▁Ini ▁adalah ▁bud aya ▁ku mpu lan ▁Dan ▁ini lah ▁yang ▁ayah ▁awak ▁minta
▁Dan ▁rumah ▁itu ▁adalah ▁mi lik ▁kamu .
▁Kalau ▁begitu ▁kau ▁se baik nya ▁ber si ap , ▁Ker ana ▁kau ▁akan ▁mendapatkan ▁begitu ▁banyak ▁makan ▁malam ▁mele bi hi ▁makan ▁malam ▁hin gga ▁kau ▁tak ▁tahu ▁harus ▁apa ▁lagi .
▁Tidak ▁perlu , ▁tapi ▁de mi ▁memba las ▁den dam ▁terhadap ▁ibu ▁ba pa nya ▁...
▁Ta di ▁awak ▁katakan ▁awak ▁la par .
▁Siapa ▁nama ▁ nya ?
▁Awak ▁pat ut ▁tengo k ▁saya ▁sem asa ▁saya ▁ma rah ▁mereka .
▁Kalian ▁berdua , ▁dan ▁akan ▁saya ▁ tunjukkan - -
▁* ▁anda ▁mu la ▁ber main . ▁*
▁Saya ▁takkan ▁ter le pas ▁dari ▁awak , ▁kan ?
▁Dan ▁yang ▁war na ▁bir u ▁adalah ▁kita r ▁sem ula . ▁Dan ▁yang ▁war na ▁hita m ▁adalah ▁sa mpah .
▁Tuhan , ▁semua ▁saya ▁tahu ▁adalah ▁bahwa ▁Tidak ▁ada ▁meny ang kal ▁Per asa an ▁saya ▁untuk ▁Anda .
▁La ti han ▁bukan lah ▁il mu ▁dan ▁penge tah uan ▁tidak ▁ku asa .
▁Se bab ▁Per ta ma ▁ .
▁Ka wan ▁baik ▁awak ▁ter per angkap ▁di ▁dunia ▁lain . ▁Awak ▁di ▁sini ▁cuba ▁per be tul kan ▁segala nya ▁- ▁dengan ▁mencari ▁bi na tang ▁ber bul u ?
▁Ta rik ▁ge ar ▁pen dar atan ! ▁Me la ku kannya !
▁Dan ▁telah ▁mele mas kan ▁mang sa ▁mereka ▁di ▁sini
▁Kau ▁boleh , ▁kawan .
▁Tapi ▁saya ▁tahu ▁yang ▁pasti nya ▁saya ▁cinta kan ▁kamu . .
▁Orang ▁pertama ▁di ▁tal i .
▁Jadi , ▁kerja ▁disini .
▁Al - Q uran ▁sebuah ▁Kitab ▁yang ▁ter sus un ▁a yat - a yat nya ▁dengan ▁tetap ▁te gu h , ▁kemudian ▁dije las kan ▁pula ▁kan dung annya ▁satu ▁per s atu .
▁Saya ▁akan ▁ bantu ▁awak ▁ber s ih kannya ▁jika ▁awak ▁mahu kan .
▁Aku ▁menye dia kan ▁beberapa ▁orang ▁terbaik ku ▁di ▁sini .
▁Aku ▁perlu ▁buat ▁sesuatu ▁untuk ▁kembali ▁kepada ▁se dia kala . ▁Tolong , ▁tetap ▁di ▁sini .
▁Sen ti asa ▁mengambil ▁jalan ▁yang ▁ting gi .
▁So alan ▁yang ▁sangat ▁bagus ▁Ada ▁so alan ▁lain ▁lagi ▁tak ? ▁ , ▁Siapa ▁dalam ▁mind a nya ▁mempunyai ▁so alan ▁yang ▁sama ?
▁Dan ▁jika ▁kebenaran ▁itu ▁membuat mu ▁bahagia . ▁Aku ▁akan ▁ bantu .
▁... ▁Stor kie ▁Stor - le ngan .
▁Se bab ▁aku ▁adalah ▁Ca stor ▁Tro y !
▁Se an . ▁Kita ▁kawan . ▁Aku ▁mahu ▁beritahu ▁kau ▁secara ▁ber de pan .
▁Saya ▁mungkin ▁seorang ▁yang ▁ber dos a , ▁tetapi ▁tidak ▁bi ada b .
▁Tidak , ▁kau ▁tidak ▁faha m .
▁Dar i mana ▁kau ? ▁Jika ▁kau ▁tahu , ▁kenapa ▁ber ta nya ?
▁Let akan ▁Te ting kap ▁Te ta p
▁-- s ince = < version > ▁ja ng ka ▁hanya ▁lalu an ▁ke ▁ . de b
▁Dan ▁lihat , ▁lihat .
▁Saya ▁akan ▁beritahu ▁kamu ▁seperti ▁saya ▁beritahu ▁yg ▁lain .
▁- ▁Ada ▁me ja ▁di ▁ha da pan ▁nan ti .
▁Tidak ▁dapat ▁mem buka ▁sal uran ▁yang ▁di pil ih ▁dengan ▁format ▁video ▁yang ▁di pil ih .
▁Mungkin , ▁Seperti ▁permainan ▁" Me ne bak ▁9 ▁sampai ▁5 ", ▁di lihat ▁dari ▁pen ampi lan mu ▁apa ▁kau ▁pi ntar ?
▁Se baik ▁saja ▁kita ▁jumpa , ▁kita ▁mati kan ▁untuk ▁selama nya ▁dengan ▁ BS - US B ▁yang ▁sangat ▁ber har ga .
▁Can on ▁B J C - 21 10
▁Hei ▁kau ▁tahu ▁Nick , ▁ini ▁tidak ▁lu cu ▁Bagaimana ▁kad ang - ka dang ▁kita ▁tidak ▁boleh ▁melihat ▁Itu ▁adalah ▁ti nda kan ▁yang ▁akan ▁membantu ▁kita ▁wa lau pun ▁itu ▁mengha dang ▁te pat ▁di ha da pan ▁kita
▁Jangan ▁buat ▁D H CP ▁untuk ▁hos ▁de nga ▁tag ▁di tet apkan .
▁Ayo ▁masuk , ▁akan ▁ku ▁je las kan ▁padamu ▁a gar ▁kau ▁mengerti .
▁Se baik ▁saja ▁awak ▁selesai kan ▁tu gas , ▁kami ▁akan ▁ tang gal kan ▁semua ▁per enja t ▁elektri k ▁itu .
▁Bay angkan ▁-
▁Anda , ▁sudah ▁tentu , ▁tidak ▁mempunyai ▁pilihan .
▁Sekarang , ▁hanya ▁kita ▁yang ▁ber dir i ▁di ▁antara ▁si ▁ho do h ▁tu ▁dan ▁band ar ▁10 ▁ju ta ▁pen du duk .
▁Dia ▁pasti ▁menyukai nya .
▁Saya ▁baru ▁mem bel inya ▁ kel mar in .
▁Awak ▁terlalu ▁mu da ▁untuk ▁faha m .
▁- ▁Saya ▁nak ▁pergi .
▁Ata u ▁Mark ▁dan ▁All an ▁?
▁Tidak ▁boleh ▁tapi s ▁menggunakan ▁ju lat ▁yang ▁di nya ta kan .
▁Dengar lah ▁beberapa ▁ki sah ▁heb at .
▁Aku ▁ingin ▁mengatakan ▁ini ▁ke dat angan ▁kedua .
▁Anda ▁tahu , ▁apabila ▁saya ▁bang un ▁pagi ▁ini ,
▁Ak ses ▁terminal ▁Uni x / Linux
▁Jika ▁aku ▁boleh ▁sent uh ... ▁mungkin ▁aku ▁boleh ▁ja wa b ▁so alan ▁kau .
▁Cho o ▁mening gal ▁pe tang ▁ta di ?
▁Saya ▁akan ▁masa k ▁untuk ▁makan ▁malam .
▁Pas ukan ▁del ta , ▁mu at ▁tur un ▁selesai
▁Tapi ▁must a hil ▁bagi ▁kami ▁untuk ▁bersama ▁kamu ▁di ▁sana
▁Jika ▁tidak , ▁ten tera ▁Je pun ▁tidak ▁akan ▁menye rah ▁dalam ▁hal ▁ini .
▁Semua ▁orang ▁di ▁se ki tar ▁sini ▁akan ▁membantu ▁awak ▁tak ▁peduli ▁apa ▁pun ▁yang ▁terjadi .
▁ci pta ▁at las - lu ar - tali an ▁untuk ▁aplik asi ▁telefon ▁bi mbi t / G PS
▁- ▁Kemudian ▁dia ▁akan ▁mem oto ng ▁za kar ▁pada ▁cu ti ▁kami , ▁betul ?
▁Kau ▁akan ▁seg era ▁ber uru san ▁dengan ▁dia .
▁Awak ▁bi ar ▁pintu ▁ter buka .
▁Ar o , ▁Ca ius , ▁Marcus , ▁Pas u kannya
▁Patrick . ▁Ini ▁tun angan ▁saya .
▁Ju ara ▁Masa ▁De pan ▁tangan ▁besi ?
▁Char t ▁tak ▁boleh ▁melihat .
▁Tak zia h ▁kamu ▁di har gai ▁tetapi ▁bantuan ▁kamu ▁tidak ▁perlu ▁melainkan ▁kamu ▁boleh ▁men ama kan ▁rak yat ▁Amerika ▁yang ▁ber ta nggu ng ja wa b .
▁Tidak lah ▁su sah ▁mana ▁Kalau ▁kau ▁i kut ▁cara nya
▁Sam ▁tidak ▁akan ▁ingat ▁apa - apa .
▁Saya ▁rasa ▁dunia ▁akan ▁rasa ▁ber mina t ▁untuk ▁mendengar ▁peng ak uan ▁anak ▁perempuan ▁Matthias .
▁Jika ▁saya ▁bercakap , ▁saya ▁orang ▁yang ▁sudah ▁mati .
▁Ini ▁boleh ▁menjadi ▁masalah .
▁Se ko lah ▁ta mat , ▁tak ▁ guna .
▁Se ba gai ▁gant inya , ▁di bang un lah ▁sebuah ▁pa tung ... ▁rak s asa ▁sebagai ▁la mbang ▁pel in dung ▁ke ra ja an ▁kami . ▁Sei ring ▁berjalan nya ▁masa , ▁ ip tek ▁pun ▁ber ke mbang ▁pes at , ▁tapi ... ▁ke se jah tera an ▁ke ra ja an ▁pun ▁i kut ▁tur un .
▁" O leh ▁itu , ▁pergi lah ▁kamu ▁berdua ▁kepada nya , ▁kemudian ▁katakan lah : ▁" Ba ha wa ▁sesungguhnya ▁kami ▁ini ▁Rasul - ras ul ▁dari ▁Tuhan mu , ▁maka ▁be bas kanlah ▁kau m ▁Ba ni ▁l s ra il ▁meng i kut ▁kami , ▁dan ▁jangan lah ▁engkau ▁menye ksa kan ▁mereka .
▁Mana ▁Que en ?
▁Apa ... ▁Apa ▁maksud ▁kamu ?
▁Ia ▁sangat ▁ber isi ko .
▁Jika ▁Bon nie ▁dapat ▁ba lik ... ▁Awak ▁orang ▁pertama ▁yang ▁saya ▁telefon .
▁Mak ▁cik ▁awak ▁kata ▁awak ▁yang ▁ambil ▁dan ▁si mpan ▁bu ku ▁itu .
▁[ Me ngel uh ] ▁mungkin ▁ini ▁bukan ▁je nis ▁anda ▁kes .
▁Shi eld ▁ PE MB ENT UK AN !
▁Saya ▁ben ci ▁untuk ▁mengatakan ▁i a .
▁Dar i ▁ya itu ▁ke ger a man ▁North men , ▁le pas kan ▁kami .
▁♪ ▁B right ▁light ▁♪
▁Dengan ▁ser ba ▁ke kurang an , ▁saya p ku ▁ter ikat .
▁Lihat ▁destina si ▁dalam ▁mind a .
▁Apa ▁ini , ▁Charlie ?
▁Jangan ▁putu s ▁asa ▁se la gi ▁belum ▁sampai ▁ke ▁pun cak .
▁Aku ▁tak ▁mahu ▁Ju dy ▁Mon cada ▁mu la ▁ber ta nya ▁ber und ing ▁tentang ▁bahagia n nya .
▁Si hat ▁ke ▁se men jak ▁dua ▁ni ?
▁Bi lik ▁Ti dur ... ▁sebe lah ▁kan an .
▁Dia ▁tidak ▁mahu ▁mele pas kannya .
▁Be liau ▁mempunyai ▁vil a ▁lama ▁ini ▁dari ▁19 08 ▁dan ▁bi lik ▁bawah ▁tan ah ▁yang ▁men ak ju b kan ▁ini ▁dengan ▁wa in ▁ini ▁...
▁Saya ▁perlu ▁ku asa i ▁tempat ▁mereka .
▁Apa ▁awak ▁buat ?
▁Dia ▁ber u tang ▁kepada nya ▁sesuatu ▁yang ▁sah ▁secara ▁ hukum ... ▁Untuk ▁merasa ▁aman .
▁Aku ▁merasa kan ▁Sen at ▁akan ▁bun tu ▁dalam ▁pro se dur ▁ini .
▁Na nti ▁ke ja p , ▁kau ▁maksud kan ▁yang ▁aku ▁dalam ▁per bi cara an ?
▁I zin kan ▁saya ▁membawa ▁anda ▁ke ▁Co ch on .
▁Sam ▁tak ▁peduli !
▁Mereka lah ▁ah li ▁ne raka , ▁mereka ▁tetap ▁ke kal ▁di ▁dalam nya .
▁Pu tri nya . .
▁Awak ▁yang ▁ter uk ▁menga mu k .
▁Jangan ▁salah kan ▁aku ▁kalau ▁Si d ▁han cur kan ▁kamu !
▁- ▁Kita ▁ca but ▁und i .
▁B ing kai ▁ut ama ▁adalah ▁lebih an ▁kap as iti
▁Cer min nya ▁selalu ▁ko tor .
▁_ To ol bar
▁Ra sa nya ▁ka ca ng ▁la .
▁Don nie ▁dan ▁saya , ▁kami ▁me la bur ▁dalam ▁pro jek ▁kon do ▁di ▁Ve nice .
▁Adakah ▁kamu ▁se dar ▁tentang ▁aktiv iti ▁pen ip uan ▁yg ▁di uru s kan ▁bagi ▁pi ha k ▁Ul ti ma ▁National ▁Re source s ? ▁- ▁Ban tahan .
▁Aku ▁tak ▁tahu ▁bagaimana ▁nak ▁cakap ▁tapi ▁se jak ▁ kej adian ▁di ▁Pu lau ▁Liber ty ...
▁Ini ▁S acha ▁Pfeiffer .
▁Jadi ▁tak ▁ada ▁seorang ▁pun ▁mahu ▁cakap ▁apa ▁yang ▁sedang ▁berlaku ?
▁- ▁' Ma tter ' ▁Sam bung an !
▁Kalau ▁begitu , ▁bagus .
▁Apa ▁ guna nya ▁pergi ▁ke ▁Florida ... ▁kalau ▁awak ▁pak ai ▁kri m ▁pel in dung ?
▁Mungkin ▁nama ▁awak .
▁je t ▁itu ▁sudah ▁mendapat ▁sur at ▁aku an .
▁- ▁Kita ▁mana ▁ada ▁radio .
▁Mengapa ▁i a ▁di luk ai ?
▁Se ba gai ▁wa kil ▁Stark ▁Industri es ,
▁MiB
▁Se ti ap ▁kali ▁ada ▁kamera ▁mengha la ▁ke ▁a rah ▁saya ...
▁Saya ▁akan ▁ta nya ▁awak ▁sekali ▁lagi .
▁Kami ▁ingin ▁anda ▁sa bo taj ▁kem uda han ▁peng awa san ▁pus at ▁Good chi ld ▁ini .
▁Aku ▁har ap ▁kau ▁betul ▁Ka veri .
▁- Ka mi ▁yang ▁di per ca ya i ▁pe gua m ▁kami .
▁Semua nya ▁to long ▁ke bela kan g ▁du lu , ▁ber hati - hati .
▁Da lam ▁ti ga ▁jam .
▁Big fo ot ▁di ▁O zar ks .
▁Ia ▁me let up , ▁dan ▁bang sal ▁itu ▁hampi r ▁ter ba kar ▁di se bab kan ▁ kej adian ▁itu .
▁Aku ▁nak ▁cakap ▁d gn ▁kau ▁Mei ▁L ing .
▁Nama ste ▁( sala m ) , ▁Sim ran
▁Yeah .
▁Se ta kat ▁ni , ▁sangat ▁je las .
▁( M US IC ▁D RAM ATI K )
▁Si al ▁yeah , ▁James .
▁Se orang ▁wanita ▁biasa nya ▁akan ▁menunjukkan ▁per asa annya ▁lebih ▁banyak ▁dari ▁yang ▁dia ▁rasa kan .
▁- ▁Kami ▁model ▁ram but ▁dari ▁Belgi um .
▁En tah lah .
▁Thank s ▁lagi ▁untuk ▁semuanya . ▁Sara .
▁Itu ▁sebab nya ▁saya ▁mengambil nya .
▁Kita ▁ter pak sa ▁bergerak ▁ke ▁ha da pan , ▁ser ta - mer ta .
▁- ▁Mas uk kan ▁log ik ▁ke ▁dalam ▁o tak nya .
▁- ▁Dan ▁untuk ▁tempo h ▁40 ▁tahun ▁akan ▁datang ...
▁Te ta pi ▁dia ▁menga wal ▁per dag angan ▁senjata ▁haram ▁di ▁Con go ▁selama ▁ber ta hun - ta hun .
▁Dan ▁aku ▁mahu ▁kau ▁ambil ▁ini ▁untuk ▁kalau ▁ada ▁ke cem asan .
▁- ▁A ▁si far ▁gra viti ▁'
▁- ▁salah ▁kau ▁karena ▁menga ba ikan ▁aku !
▁C loud , ▁di ▁mana ▁awak ?
▁Se be lah ▁kan an ▁saja .
▁Dia ▁sudah ▁pergi , ▁Barry .
▁OK , ▁nas ib ▁baik
▁Et n ologi , ▁sebenarnya .
▁Dan ▁kau , ▁Pak , ▁telah ▁dia m bil ▁ter ke jut .
▁Kami ▁pergi ▁ke ▁Hong ▁Kong , ▁Sep any ol , ▁Bueno s ▁Air es , ▁ke ▁mana ▁saja ▁yang ▁di ar ahkan ▁oleh ▁bo s ▁kami .
▁- ▁Saya ▁hanya ▁pe mand u .
▁Awak ▁mungkin ▁mati ▁hari ▁ini .
▁Nam pak nya , ▁kerja ▁saya ▁yang ▁jadi kan ▁Ron nie ▁begin i . ▁dan ▁jadi kan ▁Martin ▁Ste in ▁begin i .
▁Kami ▁juga ▁akan ▁membawa ▁pulang ▁per ka kas mu .
▁Ke dat angan ▁awak ▁ini ▁membuat kan ▁ha ti ▁saya ▁ber bung a - bung a .
▁" Ja wa b lah : ▁" Ya , ▁de mi ▁Tuhan ku ! ▁ Sesungguhnya ▁adalah ▁i a ▁benar !
▁Sekarang ▁le tak ▁kepala ▁atas ▁ba hu ▁mereka .
▁Dengar , ▁saya ▁nak ▁tahu ▁ra nc angan ▁romp akan ▁se ter us nya . ▁Bila ?
▁Hi du p kan ▁bun yi ▁permainan
▁Se su ci nya ... ▁dan ▁le mbu t ▁seperti ▁a wan .
▁Dia ▁mengg oda ▁aku ▁seperti ▁orang ▁as ing .
▁Jangan ▁masuk ▁camp ur , ▁Ha ley .
▁Okay , ▁ali h kan ▁per hati an . ▁apa ?
▁Ia ▁tak ▁boleh ▁di ter ba lik kan .
▁Katakan lah ▁lagi : ▁" Ba gai mana ▁fikir an ▁kamu ▁jika ▁Al - Q uran ▁ini ▁( yang ▁datang nya ) ▁dari ▁Allah ▁dan ▁kamu ▁meng ing kari nya , ▁pada ▁hal ▁ada ▁seorang ▁sa ksi ▁dari ▁Ba ni ▁Is ra il ▁memberi ▁ke ter angan ▁menga ku i ▁( sah nya ▁Kitab ) ▁yang ▁sama ▁seperti ▁Al - Q uran ▁ini , ▁lalu ▁i a ▁percaya kan ▁( Al - Q uran ▁ini ▁dari ▁Allah ) , ▁sedang ▁kamu ▁dengan ▁som bo ng ▁ ang ku h ▁meng ing kari nya ? ▁( Ti dak kah ▁dengan ▁yang ▁demikian ▁kamu ▁ber si fat ▁za lim ) ?
▁Maaf , ▁bergerak ▁di ▁atas .
▁Katakan ▁pada ▁mereka ▁musi m ▁din gin ▁mengha m piri ▁kla n ▁Fre y .
▁Ju rus ▁ke ▁10 , ▁Se pul uh ▁ ribu ▁Bu dd ha .
▁Tek n ologi ▁peng awa san ▁ini ▁memang ▁heb at .
▁- A paka h ▁Maj lis ▁itu ?
▁Am bil ▁file m ▁si al ▁itu .
▁Bar u lah ▁boleh ▁pu kul ▁bola .
▁Kau ▁tahu ▁apa ▁yang ▁aku ▁ingat ?
▁Kita ▁kena ▁per tahan kan ▁diri .
▁Oh , ▁God . Lo ok ▁saya ▁di ▁ini !
▁" O h , ▁put era ▁ku , ▁datang ▁untuk ▁aku !
▁Aku ▁akan ▁memberitahu ▁bi bi ▁bahawa ▁anda ▁pergi ▁ke ▁Masa ke i ▁dengan ▁ra kan ▁mi nggu ▁lalu .
▁Mereka ▁adalah ▁te ta mu ▁kami .
▁Awak ▁ber hara p ▁dia ▁akan ▁mati .
▁- ▁Ber s yu kur lah , ▁dia ▁menyelamatkan ▁awak .
▁Aku ▁nampak ▁banyak ▁pen ja ga , ▁berse nja ta ▁can ggi h .
▁Ay uh !
▁- ▁Saya ▁rasa ▁ber tu ah .
▁Jadi ▁mari ▁kita ▁ken al ▁pasti .
▁Yeah .
▁Apa ▁yang ▁salah nya ?
▁Dar i ▁apa ▁yang ▁kami ▁datang ▁kem ari .
▁ Sesungguhnya ▁sem uli a - mu lia ▁kamu ▁di ▁si si ▁Allah ▁ialah ▁orang ▁yang ▁lebih ▁ta q wa nya ▁di ▁antara ▁kamu , ▁( bu kan ▁yang ▁lebih ▁ket uru nan ▁atau ▁bang sa nya ) .
▁Ma lah ▁awak ▁tidak ▁mempunyai ▁po ko k .
▁Orang ▁Amerika ▁menghi m pun ▁a set ▁a ngkat an ▁la ut ▁di ▁Pas ifik .
▁Ata u ▁saya ▁dapat ▁buat ▁akan ▁ tang gal kan ▁sel uar ▁di ▁ha da pan ▁pas ukan ▁bola ▁ta mpar ▁wanita .
▁Ke kas ih ▁kau ▁orang ▁lain
▁Orang ▁band ar ▁ini ▁perlu kan ▁per lin dung an , ▁dan ▁kalau ▁kamu ▁tak ▁dapat ▁ke pan tas an ▁kamu , ▁bagaimana ▁kamu ▁nak ▁pasti kan ▁mereka ▁selamat ?
▁Bila ▁awak ▁mu la kannya , ▁tiada ▁jalan ▁untuk ▁pat ah ▁ba lik .
▁Apa ▁awak ▁buat ?
▁Kami ▁mendengar ▁ber u lang ▁kali ▁daripada ▁N F L , ▁anda ▁senti asa ▁meng ka ji , ▁anda ▁senti asa ▁men cu ba .
▁Hanya ▁anak - anak ▁org ▁Je pun ▁yg ▁mendapat ▁pel u ang ▁ini
▁Aku ▁mengu bur ▁ paka ian ▁dan ▁se pat u nya ▁men dir ikan ▁bat u ▁ni san ▁ini . ▁Se kurang - kurang nya ...
▁" Da pat kan ▁de gu pan ▁ jan tung ▁saya ▁untuk ▁menge lu h ."
▁Awak ▁meno lak ▁melakukan ▁apa - apa ▁yang ▁ada ▁di ▁luar ▁zon ▁sele sa ▁awak .
▁Jika ▁ada ▁kem ung kin an ▁mereka ▁mengatakan ▁yang ▁sebenarnya ▁--
▁Seperti ▁yang ▁baik ▁sebagai ▁em as ▁sin ga ▁ini , ▁ti ba - ti ba "
▁Siapa ▁kita ▁di ▁sm ji e Â  i ?
▁Ten tang ▁ku li ah
▁Adakah ▁saya ▁kelihatan ▁se parti ▁gadis ▁re ma ja ?
▁Awak ▁hanya ▁pergi ▁dan ▁lakukan ya ?
▁Sam pul ▁7 x 9 paper ▁size
▁Keluar ga ▁saya ▁akan ▁cari ▁saya .
▁Jangan ▁buat ▁begin i ▁lagi .
▁Si la ▁ny ata kan ▁Kom en ▁kamu ,
▁Saya ▁akan ▁pergi ▁ke ▁D . A . ▁ ,
▁Di ▁mana kah ▁i a ?
▁Mer oko k ▁di ▁se ki tar ▁bud ak - bud ak ▁na ga ?
▁- ▁Aku ▁tak ▁percaya ▁ini !
▁Peng hina an ▁apa kah ▁ini ▁hanya ▁untuk ▁kesalahan ▁kecil ?
▁- ▁Saya ▁nak ▁vod ka ▁mar tini , ▁to long .
▁Fe a ther , ▁kami ▁ingin ▁mena nya kan mu ▁beberapa ▁per tany aan ▁tentang ▁De an ▁Mun sh .
▁Kami ▁li mpah kan ▁ rah mat ▁Kami ▁kepada ▁sesiapa ▁sahaja ▁yang ▁Kami ▁ke hen daki , ▁dan ▁Kami ▁tidak ▁menghi lang kan ▁bala san ▁baik ▁orang - orang ▁yang ▁berbuat ▁ke ba ikan .
▁Tuhan ▁yang ▁mengu asa i ▁segala ▁a lam ▁lang it ▁dan ▁bu mi .
▁- ▁Kenapa ▁sekarang ▁baru ▁se dar ?
▁$ ▁20 0,000 , ▁di ▁sini ▁i a ▁adalah
▁Se be lum ▁mu lut ▁awak ▁me let up , ▁Mi ck .
▁Ya , ▁Michael , ▁se ju jur nya , ▁aku ▁juga ▁ter ke jut ▁dengan ▁ke bo le han mu .
▁Sa ke ▁hu jah , ▁seseorang ▁se lain ▁daripada ▁dengan ▁be liau ?
▁Pi ha k ▁Ke mente rian ▁mengha ntar ▁abu ▁dia ▁pada ▁saya .
▁Bag us , ▁jadi ▁ini lah ▁has il nya ▁bekerja s ama .
▁Sen ara i ▁item text attr
▁Mala m ▁men jel ma ;
▁La du ▁u dang .
▁Saya ng , ▁kau ▁mem anja kan ku .
▁Saya ▁ingin ▁kembali kan ▁ini ▁pada ▁kamu ▁tad inya , ▁tapi ▁saya ▁lihat ▁hal ▁men curi ga kan ▁di ▁ ling karan ▁kamera ▁kamu .
▁Dia ▁tak ▁boleh ▁bela jar ▁menga wal ▁ke tag ih nya ▁terhadap ▁da rah ▁jika ▁dia ▁tidak ▁merasa ▁ket agi han nya ▁terhadap ▁da rah .
▁" Ka mi ▁sedang ▁mencari ▁Var ian , " ▁kemudian ▁saya ▁kata ,
▁- ▁Awak ▁cuma ▁perlu ▁ber ten ang .
▁Di ▁sebuah ▁ke da i ▁pa jak ▁gada i ▁buruk ▁sekali ▁di ▁te nga h .
▁Ka rena ▁aku ▁tidak ▁ingin ▁mengetahui ▁kita ▁punya ▁per a hu ▁pen uh ▁nu gge t ▁di ▁te nga h ▁keadaan ▁dar ura t .
▁Aku ▁ber ja nji ▁akan ▁mengha ntar ▁kepada ▁kamu .
▁Saya ▁buat ▁kerja ▁sia - sia ▁tanpa ▁up ah .
▁Ra cun ▁tik us ▁dapat ▁bere a ksi ▁karena ▁tik us ▁tidak ▁memiliki ▁refl eks ▁me mbu al .
▁Tapi ▁kau ▁tak ▁akan ▁meng hen tika nku ?
▁Ju te , ▁pergi !
▁ Sesungguhnya , ▁hanya ▁se la gi ▁saya ▁tidak ▁le wat ...
▁Car a ▁hidup ?
▁Am bil ▁ke nya taan ▁mereka .
▁Anda ▁akan ▁me landa ▁kami ?
▁Kamu ▁semua , ▁ay uh !
▁aku ▁selalu ▁ber fik ir ▁bahawa ▁kau ▁boleh ▁mungkin ▁menggunakan ▁bur ung ▁mati ▁Da lam ▁sup ▁atau ▁sesuatu .
▁Kamu ▁ tum buk ▁si ▁ga y ▁ne gro ▁tu ▁te pat ▁di ▁muka , ▁dan ▁itu ▁bukan ▁kali ▁kedua ▁berlaku .
▁Ca i ▁Ma o ▁dan ▁Z hang ▁Y un , ▁Di ▁sini ,
▁Pa da ▁masa ▁ini , ▁mak hlu k ▁yang ▁akan ▁ke ▁ hulu ▁sun gai ▁No mi ▁itu .
▁Nama kan ▁sem ula ▁te ting kap ▁'% s ' ▁ke ▁(1 -3 ▁ aks ara )
▁♪ ▁Di ▁mana ▁ju a ▁kamu ▁berada ▁♪
▁Mereka ▁me sti ▁men di am kan .
▁Na ina , ▁anda ▁dan ▁saya ▁akan ▁menye r bu ▁guda ng ▁pe nia ga .
▁Bagaimana ▁saya ▁boleh ▁ber i ▁dia ▁ jan tung ▁yang ▁le mah ▁ini , ▁mak ?
▁Saya ▁menga r ahkan ▁DNA ▁be liau ▁di mus n ahkan .
▁Men ung gang ▁ hina , ▁ rank est , ▁yang ▁ku da ▁na sti est .
▁# ▁Ter da pat ▁bu nga ▁tun as ▁dan ▁saya ▁gi la ▁pada nya ▁#
▁- ▁Tak ▁ada ▁apa .
▁- Ma mpu s lah .
▁Saya ▁ben ci ▁untuk ▁pay uda ra ▁gele m bung ▁anda , ▁tetapi ▁jika ▁anda ▁mem bina ▁rumah ▁ini ▁kecil , ▁siapa ▁yang ▁akan ▁hidup ▁dalam ▁' em ?
▁Saya ▁telah ▁dua ▁kali ▁untuk ▁album ▁itu ▁untuk ▁mendengar .
▁Apa , ▁awak ▁lu pa ▁nak ▁per i ksa ▁jika ▁tu dung ▁kepala ▁dia ▁tak ▁ter buka ?
▁Shu t ▁per nia gaan ▁da dah ▁ke ▁bawah . ▁Pot ong ▁i a ▁mati , ▁dan ▁saya ▁akan ▁melakukan ▁apa ▁sahaja ▁yang ▁anda ▁mahu .
▁ Sesungguhnya ▁engkau ▁( wa hai ▁Muhammad ) ▁hanya lah ▁memberi ▁per ing atan ▁kepada ▁orang - orang ▁yang ▁takut ▁( me lang gar ▁ hukum - hukum ) ▁Tuhan ▁sem asa ▁mereka ▁tidak ▁di lihat ▁orang ▁dan ▁sem asa ▁mereka ▁tidak ▁melihat ▁azab ▁Tuhan , ▁ser ta ▁mereka ▁men dir ikan ▁sem bah yang . ▁Dan ▁sesiapa ▁yang ▁members ih kan ▁diri nya ▁( dari ▁segala ▁yang ▁di lar ang ) ▁maka ▁sesungguhnya ▁i a ▁melakukan ▁p ember si han ▁itu ▁untuk ▁ke ba ikan ▁diri nya ▁sendiri ▁dan ▁( ing at lah ) , ▁kepada ▁Allah ▁ju a lah ▁tempat ▁kembali .
▁Taylor , ▁aku ▁ mohon !
▁Kita ▁akan ▁to lak ▁mereka ▁di ▁hu jung ▁jalan !
▁- ▁Dan ▁tunggu ▁panggil an ▁saya .
▁Tam b ahkan ▁ke ▁Pro jek
▁Kan _ dung an
▁Ada ▁lagi ▁ter uk .
▁Maks ud ▁kamu . .
▁Ali h ▁ke ▁hala man ▁pertama ▁do ku men
▁Ini ▁yang ▁pertama ▁kali ▁kami ▁temu i ▁di ▁sini .
▁Sa kit ▁ke ?
▁tidak ▁dapat ▁gen ▁pri me ▁dengan ▁p bit s =% u ▁q bit s =% u
▁Kau ▁jangan ▁bay ar ▁kepada ▁seorang ▁lelaki ▁yang ▁di hor mati .
▁Be liau ▁telah ▁takut ▁se jak ▁malam ▁itu .
▁Mala m ▁itu , ▁satu ▁ke ba ikan ▁sudah ▁mem pen gar u hi ▁yang ▁lain .
▁[ OPTION ... ] ▁< de vice >
▁Pel u ang ▁ak hir , ▁To zi er .
▁X iau ▁He , ▁sampai ▁mati pun ▁akan ▁melindungi ▁X ian yang . ▁Ke pala ▁boleh ▁putu s , ▁da rah ▁boleh ▁menga li r , ▁me ski pun ▁mati ▁tidak ▁akan ▁menye rah !
▁Ram pas an ▁ba jak ▁la ut !
▁- ▁Hanya ▁menu angkan nya ▁ .
▁' ▁Terima ▁kasih .
▁Yeah .
▁bukan ▁kita ▁sahaja . ▁Kita ▁tahu ▁tentang ▁itu ▁kan ?
▁Aku ▁suka ▁per tar ung an ▁yang ▁bagus , ▁tapi ▁ini ▁sangat ▁buruk ▁untuk ▁bis nes ▁aku .
▁Fi ji z aire 2006 . ▁kgm
▁Lebih ▁baik ▁saya ▁sendiri .
▁Ya , ▁kita ▁be bas .
▁Ada ▁semua ▁orang ▁dari ▁go long an ▁Wall ▁Street ▁kepada ▁rak yat ▁di ▁jalan - ja lan , ▁kepada ▁anak - anak ▁akan ▁ke ▁kon sert , ▁yang ▁sto ner s .
▁Untuk ▁di paka i ▁di ▁jam uan ▁makan ▁malam .
▁Ad rian , ▁di ▁mana ▁mereka ? ▁!
▁Dis e ba lik ▁per saha ba tan ▁ini ▁ter se mbu ny i ▁per cin taan .
▁Dia ▁datang ▁es ok .
▁Nam pak ▁seperti ▁Da tuk ▁Band ar ▁tahu ▁beberapa ▁perkara ▁yang ▁le pas ▁dan ▁ber sungguh - sungguh ▁untuk ▁menye mbu ny ikan ▁fakt a ▁itu , ▁bahkan ▁dari ▁ SC PD .
▁Kamu ▁ lari ▁ke ▁ting kap ▁dan ▁aku ▁keluar ▁melalui ▁pintu
▁Ata u ▁pat ut kah ▁mereka ▁de ng ki ▁kepada ▁manusia ▁( Na bi ▁Muhammad ▁dan ▁uma t nya ) ▁di se bab kan ▁nik mat ▁( pa ngkat ▁Na bi ▁dan ▁u gama ▁Islam ) ▁yang ▁telah ▁di ber ikan ▁oleh ▁Allah ▁kepada ▁mereka ▁dari ▁li mpah ▁kur nia Nya ?
▁Tidak , ▁Mr ▁Per ret . ▁saya ▁tidak ▁faha m .
▁Awak ▁sudah ▁gi la , ▁De v ?
▁makan ▁si kit ▁je !
▁Tolong lah ▁jangan ▁bu ang ▁masa , ▁Moj in ▁X ia owe i , ▁Ja mba tan ▁ nya ▁re tak
▁Pe mu kul , ▁pe mu kul . ▁Ne ▁ne ▁ne ▁ne .
▁♪ ▁- ▁A ngkat ▁tangan mu . ▁- ▁Ben ar !
▁saya ▁tak ▁tahu ▁apa ▁lagi ▁yang ▁lebih ▁bagus ▁se lain ▁ini .
▁Saya ▁akan ▁let up kan ▁kereta ▁ke bal ▁mereka ▁atau ▁ba wa kan ▁kepada ▁kamu ▁komand er ▁mereka .
▁Awak ▁orang ▁baru ▁di ▁Famil a , ▁kan ?
▁Adakah ▁dia ▁macam ▁King ▁Kong ?
▁Tapi ▁apa ▁yang ▁Pre m ▁tahu ?
▁Tidak ▁boleh ▁mendapatkan ▁sem ula ▁mes ej : ▁% s
▁ga gal ▁untuk ▁un lock pt : ▁% s
▁Kamu ▁ada I ah ▁pe ga Wa i ▁atas an ▁pada ▁kes ▁ini .
▁ya ▁ lah ▁!
▁Ber ita hu ▁aku ▁apa ▁yang ▁berlaku ▁di ▁pas ar ▁ta di .
▁Tak rif ▁la jur ▁"% ▁1" ▁tak ▁sah
▁Anda ▁ingin ▁ber do a ▁untuk ▁per lin dung an ?
▁Dan ▁Ayah ▁begitu ▁ keta ku tan .
▁A nak ▁itu ▁men ja wa b . ... ▁kerana ▁saya ▁ya tim ▁sekarang .
▁Hent ikan ▁ber kela ku an ▁seperti ▁' G abb ar ▁Sin gh ' ▁( wa tak ▁file m ▁l ndi a ) .
▁B ELL A TOR :
▁Anda ▁gonna ▁membawa ▁ke lda i ▁saya ▁se panja ng ▁jalan ▁fuck ▁rumah .
▁Lebih ▁baik ▁kita ▁jadi kan ▁dia ▁sebagai ▁con to h ▁daripada ▁Du rant ▁yang ▁jadi kan ▁kita ▁con to h .
▁Se ti ap ▁kali ▁i a ▁sama ▁untuk ▁dia .
▁Dia ▁akan ▁memba yar ▁kita ▁kembali ▁apabila ▁dia ▁boleh .
▁Bila ▁kepala ▁seseorang ▁yang ▁hi lang ▁ingat an ▁di han tuk , ▁ingat an ▁dia ▁akan ▁pul ih .
▁Ka wa san ▁pen cem aran ▁yang ▁se ma kin ▁mening kat .
▁Ada ▁FBI ▁di dalam . ▁Kamu ▁harus ▁tena ng .
▁ GenericName
▁Saya ▁tahu , ▁Margaret .
▁- ▁Be lum ▁sem ing gu .
▁Dis e bab kan ▁ka ka k , ▁aku ▁ak hir nya ▁ber kah win . ▁Tiada ▁apa ▁yang ▁berlaku ▁di se bab kan ▁a bang .
▁Ada ▁kes ila pan ▁dalam ▁temp ahan ▁saya .
▁Anda ▁tahu ▁apa ?
▁Itu ▁tidak ▁' di am ' .
▁- ▁Hi , ▁D . J !
▁L kan ▁tak ▁banyak , ▁har ga nya ▁ kurang . ▁Har ga ▁bor ong ▁jatuh .
▁Sem oga ▁ber ge mbi ra ▁di ▁hu jung ▁mi nggu , ▁Ni na ...
▁Saya ▁tidak ▁mahu ▁untuk ▁mengatakan ▁i a , ▁tetapi ▁saya ▁mempunyai ▁per asa an ▁yang ▁tidak - be gi tu - se gar .
▁Ber tat ahkan ▁ber li an ▁dalam ▁ sorb annya ▁Anda ▁ter lihat ▁menga gum kan !
▁Se benar nya ▁bukan ▁itu ▁yang ▁saya ▁lakukan .
▁Ada ▁senjata ▁bera t ▁tak ?
▁Wo i , ▁dia ▁bilang .
▁Mengapa ▁kau ▁tidak ▁meng iku ti ▁kata ▁ha ti ?
▁Profesor , ▁teh ▁Ti bet ▁ini ▁har um .
▁Jadi ▁kawan - ka wan ".
▁Da hulu ▁seperti ▁itu
▁- ▁Hey . ▁Awak ▁dah ▁ba lik . ▁- ▁Sy u kur lah .
▁Klik ▁sini ▁untuk ▁menu kar ▁ke ▁ru ang ker ja ▁% s
▁Tidak , ▁aku ▁men cu ba .
▁Kamu ▁semua ▁pernah ▁ter fik ir ▁tentang ▁ ikan ?
▁Boleh kah ▁saya ▁membantu ▁anda ?
▁Ber apa ▁kali ▁Saya ▁katakan ▁bahwa . .
▁Bukan ▁masa ▁yang ▁se su ai untu k ▁pela nc aran ?
▁- I a ▁bergerak ▁seperti ▁ri but .
▁Apa ▁yang ▁dia ▁tengo k ?
▁Angel a ▁pe tre lli ... ▁dia ▁tahu .
▁- ▁Ya , ▁hi dung ... ▁da da ...
▁Unit Al pha , anda di benar kan
▁di ▁dalam nya -
▁- ▁Saya ▁benar kan ▁kamu ▁masuk ▁rumah ▁saya !
▁Apa ▁yang ▁boleh ▁saya ▁katakan , ▁dia ▁adalah ▁sebagai ▁character less , ▁kerana ▁anak ▁perempuan nya ▁adalah ▁...
▁Ca kap ▁tu an . ▁- K esan ▁panggil an ▁ini ▁dan ▁men angkap nya . ▁O key ▁tu an .
▁Na thi r ▁sedang ▁me mer hati ▁kita .
▁Ya ▁Tuhan , ▁ini ▁gi la .
▁Hanya ▁supaya ▁anda ▁tahu , ▁Bobby ,
▁Da rah ▁kita lah ▁yang ▁ditu mpah kan , ▁orang - orang ▁kita lah ▁yang ▁mati .
▁Maks ud ku , ▁kenapa ▁mereka ▁tak ▁membawa ▁ben da ▁itu ▁ke ▁tempat ▁lain . ...
▁Dia ▁jatuh ▁peng san ▁sem asa ▁me mas ak ▁makan an ▁untuk ▁hari ▁jadi ▁mak !
▁Kami ▁tidak ▁akan ▁me mer lu kan ▁lagi .
▁Ja na ▁ime j ▁ber dir i ▁sendiri ▁( men gan dung i ▁semua ▁modul ) ▁dalam ▁format ▁ter pil ih
▁Masa ▁pe mu li han ?
▁Per tu tur an ▁di benar kan .
▁Be tul ▁ke , ▁aku ▁tak ▁akan ▁ guna ▁ru ang ▁yang ▁banyak ?
▁Men amp ung ▁% s ▁menggunakan ▁% s
▁Ya , ▁maaf . ▁Saya ▁per asan ▁sem asa ▁saya ▁me meri ksa ▁awak .
▁Ayah ▁lang s ung ▁tak ▁ingat ▁me me luk ▁Tan , ▁sebab ▁ayah ▁tak ▁mahu ▁kamu ▁ter lu ka .
▁Saya ▁boleh ▁melihat ▁awak .
▁Saya ▁melihat ▁anda ▁mempunyai ▁beberapa ▁masalah ▁bercakap ▁dengan ▁sa s sy ▁kembali ▁ke ▁sana , ▁kan ?
▁- Ge org ie .
▁Mr In gram , To be y Mar s hall ▁saya per lum e min jam M usta ng ▁anda ▁ber lum ba ▁De ▁Leon
▁- ▁Kevin , ▁itu ▁Go mez .
▁Well , ▁saya ▁tidak ▁pernah ▁melakukannya ▁sebelum ▁ini ▁...
▁Ini ▁ga m bar ▁saya ▁ .
▁Boleh ▁awak ▁to long ▁dia ?
▁Dia ▁nak ▁tidur , ▁pergi lah
▁Ten tang ▁ka ca ▁mata ▁ini .
▁Jadi ▁apa ▁ke du du kan ?
▁Aku ▁har ap ▁kau ▁tak ▁pergi .
▁- ▁Apa ▁pun ▁yang ▁terjadi , ▁tak ▁ada ▁jalan ▁keluar .
▁Keluar kan ▁fail ▁sem asa ▁dari ▁re posit ori
▁- ▁Di jum pai ▁dalam ▁to ng ▁sa mpah .
▁Bagaimana ▁jika ▁tiada ▁siapa ▁yang ▁berjaya ?
▁Por . ▁Ini ▁untuk ▁awak .
▁Apa ▁ke put us an mu ?
▁' S wa mi ▁Var a dan anda ▁akan ▁datang ▁ke ▁Ten ka si '
▁Ang ▁Lee ▁adalah ▁men tor ▁saya ▁dan ▁juga ▁keluarga ▁saya
▁Park ▁Ha ...
▁Semua nya ▁a dil ▁ketika ▁ber cin ta !
▁tak ▁berba lo i ▁lang s ung ▁jika ▁nak ▁melindungi ▁kawan ▁kawan ▁awak ▁awak ▁ter des ak ▁sekarang ▁ni ▁dan ▁jangan ▁fikir ▁awak ▁akan ▁ter le pas
▁Dia ▁akan ▁gun akan ▁per mata ▁itu ▁untuk ▁diri nya ▁sendiri .
▁Jadi ▁i a ▁adalah ▁selamat ▁untuk ▁membawa ▁masuk ▁Bis ho p ▁sekarang ?
▁Jangan ▁ber bel anja , ▁per lah an - lah an .
▁Saya ▁akan ▁mem bel ikan ▁anda ▁sebuah ▁rumah ▁baru .
▁Awak ▁pat ut ▁ber bin ca ng ▁dengan nya ▁seperti ▁orang ▁de wa sa ▁dan ▁selesai kan ▁masalah ▁kamu .
▁- ▁Normal ▁la ▁kalau ▁macam ▁tu
▁Tolong lah ▁keluar ▁dari ▁sini .
▁Har i ▁ini ▁saya ▁dapat ▁pel u ang ▁lakukan ▁terbaik ▁dalam ▁kerja ya .
▁- O ka y , And y , me me luk ▁be liau .
▁Terima ▁kasih , ▁Sir ▁Gra ham .
▁Te ta pan ▁Ku ki
▁Jika ▁Australia ▁ gol , ▁pen al ti ▁ini ▁akan ▁di ter us kan .
▁Kami ▁mene mu i ▁mereka ▁me man jat ▁cenu ram .
▁Kamu ▁memang ▁polis , ▁kamu ▁cuma ▁me nya mar ▁saja !
▁Ada ▁yang ▁1 0,000 ▁dolar ▁?
▁Adakah ▁kau ▁lu lus kan ▁romp akan ▁J eneral ?
▁Awak ▁pun ▁nampak ▁can tik .
▁Saya lah ▁yang ▁mengha ntar ▁Sar jan ▁Ma jor ▁Se o ▁keluar .
▁Tu tu p - K er ja ▁tidak ▁meny oko ng ▁a tribut ▁ uri - ker ja .
▁Na mun ▁demikian , ▁Terima ▁kasih .
▁Ter pu ji lah ▁De wa ▁Ke ku atan !
▁Ja rak ▁sebelum ▁ga ris ▁gri d ▁mene ga k ▁pertama
▁Ini ▁akan ▁berlaku ▁pada ▁bud ak ▁ni .
▁Ser ta ▁memberi nya ▁re zek i ▁dari ▁jalan ▁yang ▁tidak ▁ter lin tas ▁di ▁hat inya .
▁Bukan ▁ber mak na ▁dia ▁pembunuh nya .
▁saya ▁membunuh ▁a dik ▁saya , ▁Oliver ...
▁Doktor ▁dah ▁pes an ▁yang ▁kamu ▁tak ▁boleh ▁keluar ▁dari ▁rumah
▁Dan ▁( ing at lah ) ▁Allah ▁senti asa ▁melihat ▁apa ▁yang ▁kamu ▁lakukan .
▁- ▁Jika ▁itu ▁berlaku ▁ ,
▁Na s ib ▁baik ▁kau ▁mena wan .
▁Jadi , ▁apa ▁maksud ▁arti ▁dari . . ... ▁kematian ?
▁Apa ▁yang ▁berlaku ... ?
▁Ko thanda m , ▁saya ▁telah ▁di si mpan ▁Ra do ▁men on ton ▁bersama - s ama ▁dengan ▁ge lang ▁saya , ▁membawa ▁yang ▁terlalu
▁Dan ▁tiada ▁seorang pun ▁orang ▁Georgia ▁menjadi ▁mang sa .
▁- ▁ BAR RY :
▁Sau , ▁se ma lam ▁aku ▁ada ▁hal .
▁Sekarang ▁dia ▁me lang gar ▁bat as !
▁Ayah ▁tunggu ▁kamu ▁beritahu ▁ayah . ▁Tapi ▁kamu ▁tak ▁juga ▁beritahu ▁ayah ▁apa ▁masalah nya .
▁Kap al ▁ter bang ▁itu , ▁Kau ▁fikir ▁i a ▁masih ▁boleh ▁ter bang ?
▁Ama hle ▁ guna ▁el et rik ▁untuk ▁t angkap ▁ca cing .
▁Pres iden , ▁kamu ▁o key ?
▁Tuan ku , ▁saya ▁dah ▁berjaya ▁dapat kan ▁se li par ▁sebe lah ▁lagi .
▁Dar i ▁Don at ello .
▁Te ta pi ▁lang kah ▁harus ▁punya i ▁Jika ▁perlu ▁ , ▁menye mai ▁aku an .
▁- ▁Oh , ▁Tuhan ▁saya , ▁i a itu ▁begitu ▁besar .
▁" 42 ..."
▁As al nya ▁dari ▁Re vol usi ▁Ru sia , ▁19 17 .
▁Lihat ▁kedua - du a ▁a rah ▁sebelum ▁me lin tas ▁jalan
▁Saya ▁ke ▁sini ▁untuk ▁bertemu ▁tu an ▁kamu
▁Mari ▁kita ▁pergi .
▁Tiada ▁apa ▁yang ▁ber mu la .
▁Tak , ▁beritahu ▁mereka ▁yang ▁se benar .
▁Ber ita ▁baik , ▁Caroline .
▁Pel uru ▁itu ▁melalui ▁Cor ky ▁yang ▁ha iran , ▁dan ▁dia ▁melakukan ▁sesuatu ▁yang ▁salah .
▁Maks ud ▁saya , ▁kamu ▁tidak ▁tidak ▁suka ▁seorang ▁wanita ▁jika ▁kamu ▁telah ▁membuat ▁yang ▁banyak ▁la karan ▁untuk nya .
▁Aku ▁menge ndar ai ▁tu pai .
▁Ki las
▁Anda ▁ber nas ib ▁baik ▁dan ▁membunuh ▁seorang ▁yang ▁bodoh .
▁- ▁Ke du kaan .
▁- ▁saya ▁tidak ▁suka ▁ trakt ir .
▁Para ▁wanita ▁di ▁rumah ▁ini , ▁to long ▁jag a ▁gadis ▁ini .
▁Ke dia man ▁2 11 ▁dalam ▁kem aju an .
▁Men ge ta hui ▁bahawa ▁Pas i pha e ▁adalah ▁ibu nya ▁telah ▁berubah ▁kepada nya .
▁Bos ▁saya ▁akan ▁bunu h ▁saya . ▁Kamu ▁gi la ▁ke ▁Jer ?
▁Sekarang ▁berhenti ▁ber ta nya ▁begitu ▁banyak ▁so alan ▁dan ▁mari ▁kita ▁pergi .
▁Bah asa
▁Ha ti - hati , ▁a wa s
▁Saya ▁dari ▁orang - orang ▁China , ▁mereka ▁ber dir i ▁di ▁sana .
▁Elle n ▁a mat ▁meny us ahkan , ▁Pat ty .
▁Di ▁sini , ▁saya ▁di ▁sini .
▁Saya ▁har ap ▁kamu ▁tidak ▁let ih .
▁Pu an , ▁nom bor ▁aka un ▁yang ▁pu an ▁bagi ▁telah ▁di akse s ▁jam ▁10 : 00 ▁pagi ▁pada ▁2 h b ▁Oktober ▁di ▁A TM ▁di ▁Pa na ji .
▁Sen ara i ▁Mes ej ▁Ber be ben ang
▁Saya ▁sebenarnya ▁rasa ▁kasih an ▁dengan ▁awak .
▁- ▁Ia ▁hanya ▁untuk ▁dua ▁orang .
▁Ad rian , ▁memberi ▁saya ▁ime j ▁o tak .
▁Mereka ti dak ▁pernah ▁mem uja ▁untuk ▁waktu ▁yang ▁lama .
▁Tapi ▁ada ▁satu ▁hal ▁yang ▁penting .
▁Ha ti - hati ▁dengan ▁na ga ▁itu .
▁Dia ▁ lah ▁Pel in dung ▁kamu .
▁Dia m lah ▁di ▁sini , ▁jangan ▁bergerak .
▁Ga bung an ▁TLS / LD AP S ▁tidak ▁sah
▁Saya ▁tiada ▁se bar ang ▁nit rat ▁jadi ▁saya ▁ter pak sa ▁minta ▁dari ▁ji ran ▁lain .
▁Saya ▁perlu ▁ber fik ir .
▁Yeah .
▁Apa ▁ kha bar , ▁Tuan ?
▁Dr . ▁Fi s her ▁telefon .
▁Han tu ▁keluar ▁dari ▁mana - mana !
▁Kalau ▁sele pas ▁waktu ▁sekolah ▁kau ▁perlu ▁terus kan ▁sehingga ▁7 : 00 ▁pagi . ▁Ke tika ▁itu , ▁baru ▁aku ▁datang ▁selamat kan ▁kau .
▁Saya ▁dengar ▁ada ▁yang ▁ter ced era .
▁Saya ▁hanya ▁ingin ▁hidup ▁macam ▁biasa .
▁Kenapa ? ▁Apa ▁masalah nya ?
▁Pergi ▁ber main ▁dengan ▁ibu ▁kau .
▁Baiklah , ▁mari ▁ter bang ▁An t - T ho ny .
▁La ku kan ▁seperti ▁yang ▁aku ▁katakan , ▁5 ▁ka ki ▁tidak ▁lebih , ▁tidak ▁ kurang .
▁tapi ▁sebagai ▁polis , ▁saya ▁ter pak sa ▁mengha da pi ▁per asa an ▁takut ▁tu ▁itu ▁ta nggu ng ja wa b ▁kami
▁Kem bali ▁ke ▁la dang ▁lu cu .
▁Jangan ▁sekali - kali ▁wa lau pun ▁si as atan .
▁" ▁Dan ▁wa hai ▁kau m ku !
▁- ▁Ku pi kir ▁kau ▁bilang ▁kau ▁me lar ikan ▁diri .
▁Ini ▁bukan ▁so al ▁China , ▁kan ?
▁Na nti ▁mereka ▁akan ▁per asan ▁kita ▁bukan ▁polis .
▁Saya ▁tahu ▁... ▁tetapi ▁saya ▁mempunyai ▁satu ▁lagi ▁perkara ▁untuk ▁memberi nya .
▁Charlie , ▁panggil kan ▁En rique :
▁Yo on ▁Do !
▁- ▁Car i ▁i Po d ▁itu .
▁Tu n juk kanlah ▁kepada ku ▁apa ▁yang ▁mereka ▁telah ▁ci pta kan ▁dari ▁bahagia n ▁bu mi ▁ini ? .
▁Ya , ▁dia ▁baru ▁lalu ▁sini .
▁Mis a ▁meninggalkan ▁hak ▁pose s if ▁dari ▁De ath ▁Note
▁Ma ▁Ri ... ▁kau ▁ada ▁di ▁sana .
▁Mari ▁tinggal kan ▁kap a ▁ini !
▁Ker ana ▁awak ▁dengan ▁se nga ja ▁mengha n cur kan ▁ke bah agi aan ▁a dik ▁saya ▁yang ▁ter cin ta .
▁Tiada ▁sesiapa ▁pernah ▁ member us ▁di ▁sini ▁selama ▁ber ta hun - ta hun .
▁( M ere ka ▁bukan ▁sahaja ▁tidak ▁percaya ▁tentang ▁hidup ▁sem ula ) ▁bahkan ▁mereka ▁tidak ▁percaya ▁tentang ▁per tem uan ▁dengan ▁Tuhan nya .
▁Se ben tar . ▁Kita ▁bunu h ▁seseorang , ▁kita ▁dapat ▁ny awa ▁mereka ?
▁Dan ▁kalau lah ▁tidak ▁kerana ▁kali mah ▁ket eta pan ▁yang ▁menjadi ▁pe m utus ▁( dari ▁Allah , ▁untuk ▁menang g uhkan ▁ hukum an ▁hin gga ▁ke ▁su atu ▁masa ▁yang ▁ter ten tu ) , ▁tentu lah ▁dija t uhkan ▁azab ▁dengan ▁ser ta - mer ta ▁kepada ▁mereka ▁( yang ▁berbuat ▁demikian ) .
▁Se mi nggu ▁sele pas ▁ser angan ▁szám os ▁h ír ▁szó lt ▁ar ról , ▁gé pra b ló k nak ▁bahawa ▁banyak ▁ra kan - ra kan ▁berada ▁di ▁Amerika ▁S yari kat .
▁- ▁Cum a ▁mereka ▁ber ti ga .
▁Kamu ▁ber pel uh .
▁Ka rena ▁aku ▁mau ▁bilang , ▁jika ▁kau ▁akan ▁mengatakan ▁iya , ▁Aku ▁akan ...
▁Okay ▁... ▁okay ▁Per ta ma ▁... ▁pertama ▁... ▁pertama !
▁- ▁Su ite ▁Pres iden .
▁Tidak , ▁Kur asa ▁dia ▁sedang ▁non ton ▁sesuatu ▁yang ▁ ile gal
▁Saya ▁akan ▁jumpa ▁kamu ▁sele pas ▁selesai .
▁Has bul lah ▁Bin ▁Pi t ▁< se bol \ @ ik hlas \ . com > , M er lim au . ▁Ber ser ta ▁do r ongan ▁daripada ▁ra kan - ra kan .
▁Aku ▁akan ▁memang gil ▁untuk ▁meminta ▁mereka ▁untuk ▁ber si ap - si ap .
▁Baiklah , ▁10 ▁saat ▁untuk ▁pergi .
▁Saya ▁boleh ▁mati ▁dalam ▁cu aca ▁se juk ▁ini .
▁Seperti ▁hal nya ▁O z ▁untuk ▁Do ro thy .
▁Kau ▁nak ▁men en tang ▁aku ?
▁Muhammad ▁Naj mi ▁bin ▁Ah mad ▁Za bi di , ▁Shar u zza man ▁Ah mat ▁Ra s lan EMAIL ▁OF ▁TRANSLATORS
▁( CH U C KL ES ) ▁Adakah ▁anda ▁kid din ▁' s aya ?
▁Ini ▁adalah ▁benar - benar ▁de kat ▁di ▁ha ti ▁saya .
▁Ada ▁re rant ing ▁dan ▁da un .
▁- ▁D . J . ▁Kita ▁akan ▁le wat !
▁- ▁Tapi , ▁tentu ▁awak ▁sudah ▁tahu .
▁Mac am ▁mana ▁aku ▁nak ▁menang ▁per ang ... ▁sedang kan ▁aku ▁tak ▁d pt ▁melindungi ▁keluarga ▁aku ?
▁ok , ▁pergi ▁le tak ▁kereta ▁kamu .
▁- ▁Kamu ▁akan ▁suka ▁ada ▁keluarga .
▁Saya ▁tahu ▁i a ▁ke den gar an ▁seperti ▁satu ▁idea ▁yang ▁pe lik .
▁Aku ▁akan ▁pu kul ▁kau ▁dengan ▁se li par . ▁Jangan ▁ ros akkan .
▁David , ▁si la ▁tur un kan ▁dia ▁di ▁mana ▁sahaja ▁di ▁sini
▁Apa ▁yang ▁kita ▁pela jar i ▁hari ▁ini ?
▁- ▁Oh , ▁Ca stor ▁Tro y !
▁North ▁2 -0 .
▁Adakah ▁dari ▁kamu ▁yang ▁pernah ▁ber tu kar ?
▁Tak ▁ber ju dul windows - action
▁Christ ina , ▁awak ▁kena ▁ lari , ▁sayang ▁!
▁Saya ▁masih ▁mencari ▁pekerjaan ...
▁- ▁I kut ▁aku ▁ke ▁LA
▁Aku ▁ber i ▁kau ▁masa ▁10 - 15 ▁mini t .
▁Sen si ▁Kata
▁Dan ▁untuk ▁me masti kan ▁kita ▁dapat ▁in vo is ▁kita , ▁Awak ▁akan ▁mengha ntar ▁mereka ▁kepada ▁saya .
▁Kenapa ▁tidak !
▁- A ku ▁dah ▁ter ken al ▁sekarang .
▁Konfigur asi ▁pro ksi ▁_ man ual
▁To ▁shi eld ▁her ▁pretty ▁e yes ... ♫ ▁ ♫ ... ▁Because ▁these ▁are ▁things ▁she ▁should n ' t ▁see ... ♫
▁Baiklah , ▁dia m . ▁Dia m .
▁- ▁Oh , ▁awak ▁sudah ▁ber ju mpa ?
▁Art inya ▁dia ▁tak ▁mamp u ▁bay ar . ▁Kata nya ▁semua ▁har ta ▁ben da ▁ nya ▁telah ▁di ▁ram pas .
▁Ke te ng ahkan ▁panel ▁pada ▁pak si - x
▁Tapi ▁se jak ▁beberapa ▁hari ... ▁.. kami ▁si buk ▁mengu rus ▁visa ▁dan ▁pas s port .
▁Semua ▁dalam ▁hija u , ▁las er ▁je las .
▁Go vin d , ▁orang ▁tua ▁itu ▁tiada ▁wa ng ▁tik et .
▁Kau ▁tam pak ▁ta jam , ▁Tom .
▁Baiklah , ▁mari ▁pergi .
▁Saya ▁Dig by .
▁Itu ▁adalah ▁tahun ▁yang ▁baik .
▁Se benar nya , . .
▁Se si apa ▁yang ▁mahu kan ▁kem uli aan ▁( maka ▁hendak lah ▁i a ▁ber u saha ▁mencari nya ▁dengan ▁jalan ▁me matu hi ▁p erintah ▁Allah ) , ▁kerana ▁bagi ▁Allah ▁ju a lah ▁segala ▁kem uli aan .
▁Itu ▁hanya ▁k haya lan .
▁Oh , ▁asta ga . ▁l ni ▁gi la .
▁- ▁Aku ▁She ik h ▁Al - O be idi .
▁Saya ▁tak ▁akan ▁sed ih ▁kehilangan nya .
▁Tra sh can , ▁pan du ▁lebih ▁la ju !
▁Mes ej ▁sebelum nya
▁Lihat ▁vari ans ▁ba yang - ba yang ?
▁Hanya ▁kau ▁har a pan ▁yang ▁tinggal ▁di ▁dunia ▁ini .
▁Tidak ▁di keta hui
▁Kamu ▁me sti ▁a bang ▁Mia .
▁Saya ▁akan ▁di ▁li pat ▁Si mpan .
▁Ber hen ti ! ▁Ra bbi t , ▁hen ti kan !
▁Ya , ▁ indah ▁sekali ▁Do c .
▁Saya ▁banyak ▁melakukan ▁seks .
▁Per lu kah ▁saya ▁cakap ▁sekali ▁lagi ▁yang ▁saya ▁ada ▁te ta mu ?
▁Dan ▁de mi ▁sesungguhnya !
▁Boleh ▁aku ▁cuba ?
▁Let akan ▁di ▁sini , ▁enam ▁ka ki ▁di ▁bawah .
▁Aku ▁yang ▁membunuh ▁Rich ie ▁W hel an , ▁Faha m ?
▁Ayah ▁kata ▁tidak , ▁mak na nya ▁tidak !
▁Mungkin ▁kami ▁boleh ▁ bantu , ▁cik .
▁Kamu ▁tahu ▁apa ▁p erintah ▁klik ▁ini ? ▁- ▁Sudah , ▁tu an .
▁Mereka ▁pa car nya ▁Eddie !
▁Apa ▁yg ▁orang ▁seperti ▁dia ▁lakukan ▁dengan ▁wa ng nya ▁?
▁aku ▁nampak ▁kau ▁ber i ▁mereka ▁bom .
▁Kita ▁hidup ▁begitu ▁lama ▁sebelum ▁kita ▁me mah ami ▁apa ▁yang ▁benar - benar ▁perkara .
▁a ▁baru
▁Tiada ▁siapa ▁yang ▁bera ni ▁nak ▁cu lik ▁penge dar ▁da dah ?
▁Ra sa nya ▁ber ja u han ▁dari ▁aku ▁buat ▁kau ▁jadi ▁gi la - gi la .
▁Sekarang ▁ne gara ▁ini ▁jadi ▁con to h ▁bagi ▁ne gara ▁- ▁ne gara ▁E ropa h ▁Bara t ▁!
▁De mi ▁sesungguhnya , ▁aku ▁akan ▁mem oto ng ▁tangan ▁dan ▁ka ki ▁kamu ▁dengan ▁ber si lang ▁kemudian ▁aku ▁akan ▁me ma lang ▁kamu ▁semuanya ".
▁- ▁Mana ▁Len ny ?
▁Maaf , ▁aku ▁tak ▁ber ni at ▁nak ▁si nggu ng ▁per asa an ▁dia .
▁Itu ▁du it ▁saya ▁dan ▁mereka ▁dah ▁ambil , ▁dan ▁saya ▁ga gal ▁jumpa !
▁Ia nya ▁akan ▁bergerak ▁ke ▁ta pak ▁9 , ▁yang ▁ini .
▁Kita ▁pas ukan ▁U . S ▁terakhir ▁di ▁ne geri ▁ini ?
▁Sekarang , ▁semua ▁orang ▁ber ke mas ▁tanpa ▁ada ▁buat ▁apa - apa ... ▁Tapi ▁pembunuh an ▁Mary ▁Wort h ington ... ▁Ia ▁masih ▁mengha nt ui ▁aku .
▁Per kara ▁yang ▁anda ▁meminta ▁ke ▁jalan ▁yang ▁benar .
▁" Bi ar kan ▁ku ▁me mah ami ."
▁Tidak ▁dapat ▁tuli s ▁ke ▁% s
▁En i !
▁Saya ▁ter ta nya - ta nya ▁jika ▁awak ▁ada ▁pel u ang ▁untuk ▁han tar ▁la por an ▁saya ▁ke ▁Ja mba tan ▁Sa a bir ▁K han ▁kepada ▁sesiapa ▁dalam ▁per isi kan .
▁- Be liau ▁adalah ▁blo tto .
▁- ▁Oh , ▁Saya ▁maksud kan .
▁Saya ▁rasa ▁hanya ▁itu ▁sahaja ▁kes aba ran ▁yang ▁is teri ▁awak ▁ada ▁pada ▁diri nya .
▁Saya ▁pernah ▁dengar ▁ini ▁sebelum nya .
▁Ada ▁bud ak ▁ber i kannya ▁pada ▁saya .
▁Ada ▁apa ▁dengan ▁Mun ni ?
▁Aku ▁akan ▁berbicara ▁dengan ▁ka ka k nya .
▁Kami ▁a dik - ber a dik ▁ , ▁Joe y ▁ .
▁La lu ▁kenapa ▁kau ▁me ra wat ▁S SP ▁K han ?
▁Kent ang ▁bere mpah ...
▁Jangan ▁biarkan ▁ayah ▁minu m ▁terlalu ▁banyak .
▁Kemudian ▁apabila ▁Tal ut ▁keluar ▁bersama - s ama ▁ten tera nya , ▁berkata lah ▁i a : ▁" Sesungguhnya ▁Allah ▁akan ▁mengu ji ▁kamu ▁dengan ▁se ba tang ▁sun gai , ▁oleh ▁itu ▁sesiapa ▁di ▁antara ▁kamu ▁yang ▁me min um ▁air nya ▁maka ▁bukan lah ▁i a ▁dari ▁peng i kut ku , ▁dan ▁sesiapa ▁yang ▁tidak ▁merasa i ▁air nya ▁maka ▁sesungguhnya ▁i a ▁dari ▁peng i kut ku , ▁kecuali ▁orang ▁yang ▁men ce duk ▁satu ▁ce du kan ▁dengan ▁tangan nya ".
▁Saya ▁nak ▁keluar ▁untuk ▁dapat kan ▁ha dia h ▁per kah win an ▁kamu !
▁jika ▁kau ▁harus ▁menjadi ▁baby si tter ▁( pen gas uh ▁bay i ) , ▁ini ▁bukan ▁a wal ▁yang ▁buruk .
▁Pen guna an : ▁og g de c ▁[ pi li han ] ▁fail 1 . og g ▁[ fa il 2 . og g ▁... ▁fail N . og g ]
▁.. se hin gga ▁dia ▁bahkan ▁mungkin ▁menu n juk ▁jar inya ▁ke ▁a rah mu .
▁Kemudian ▁saya ▁fikir ▁untuk ▁kali ▁kedua ▁dalam ▁diri ▁saya .
▁Ia ▁memberi ▁ke men angan ▁kepada ▁sesiapa ▁yang ▁di ke hen daki Nya , ▁dan ▁Dia ▁ lah ▁ju a ▁yang ▁Maha ▁Ku asa , ▁lagi ▁Maha ▁Men gas ih ani .
▁Jangan ▁ambil ▁a yat ▁saya .
▁Kami ▁telah ▁menga da kan ▁dialog ▁penting ▁yang ▁akan ▁membantu ▁kami ▁men ja ga ▁pe main .
▁Jadi , ▁i a ▁dah ▁tidak ▁jauh .
▁" O h , ▁ga ya ▁ram but nya ."
▁Saya ▁tahu , ▁dan ▁saya ▁tahu ▁bahawa ▁saya ▁telah ▁out vo ted , ▁tetapi ▁itu ▁tidak ▁mengu bah ▁fakt a ▁bahawa ▁kita ▁out mann ed .
▁Da pat ▁awak , ▁si ▁ce laka .
▁" To wer ", ▁sebe ntar ▁lagi ▁kita ▁tidak ▁ber opera si ... , ▁Tapi ▁" D ron e " ▁sudah ▁ke ▁sana ▁dan ▁se dia ▁di sem pur na kan .
▁Tengo k , ▁tengo k .
▁VI NC ENT : ▁Apa ▁itu ?
▁Awak ▁sudah ▁berjaya ▁bahkan ▁hari ▁ini .
▁Ya , ▁jadi ▁mereka ▁mengha ntar ▁Ibu ▁Mac G y ver ▁di ▁sini ▁untuk ▁mendapatkan ▁anda .
▁Kin i ▁saya ▁e jen ▁awak , ▁saya ▁perlu ▁men di dik ▁awak ▁pada ▁how to ▁menjadi ▁pembunuh ▁pembunuh ▁A ▁tidak ▁perlu ▁untuk ▁membunuh ▁semua ▁masa ▁yang
▁\ t Ver si : ▁% d
▁Ker eta ▁ini ▁T angan ▁kedua ▁akan ▁lakukan ?
▁bukan lah ▁pilihan ▁yang ▁sah
▁Se ti ap ▁orang ▁harus ▁tetap ▁tena ng
▁Ke du a ▁sau dari ▁di ti pu ▁oleh ▁pri a ▁yang ▁sama !
▁- ▁Tidak .
▁Saya ▁rasa ...
▁Kalau ▁aku ▁ada ▁ji wa ▁nur ani .
▁[ S h h h ▁... ]
▁Aku ▁tahu .
▁ Personal isa si ▁Papa ran ▁Sem asa
▁Bu ng le - bung le ?
▁Pe layan , ▁to long ▁saya .
▁- ▁Per lu kah ▁kita ▁tu nda ?
▁Saya ▁bi mbang ▁kita ▁tak ▁ber ken alan ▁dengan ▁betul ▁se ma lam .
▁Tak ▁boleh kah ▁cakap ▁yang ▁baik - baik ?
▁- ▁Minu m lah ▁sedikit ▁vod ka .
▁- A wa k ▁dengar ▁dalam ▁kereta ?
▁Ken alan ▁Pen ting
▁Jadi ▁jangan ▁panggil ▁kami ▁wir a .
▁back ground , ▁ style
▁awak ▁yakin ▁awak ▁tidak ▁mahu ▁minu m ▁du lu ?
▁Adakah ▁anda ▁tahu ▁ne fri t ?
▁Jangan ▁tengo k . .
▁Awak ▁dah ▁pak sa ▁kami ▁bekerja ▁terlalu ▁ku at .
▁Mereka ▁me lar ikan ▁diri !
▁Hei , ▁tentang ▁da da ▁Ji b ▁tu ▁saya ▁tak ▁pernah ▁per asan ▁pun , ▁OK !
▁Boleh ▁saya ▁bersama ▁mereka ▁dari ▁A had ▁hin gga ▁Ju ma at ?
▁Se su ai ▁dengan ▁diri ▁sendiri , ▁tetapi ▁masih ▁i a ▁tidak ▁boleh ▁ditu kar .
▁Aku ▁akan ▁bunu h ▁dia !
▁Untuk ▁pe mbe da han ▁ko s me tik ▁ke ?
▁Bill ▁ke rap ▁me la wat ku , ▁setiap ▁hari .
▁Mac am ▁satu ▁an u ▁leng kap ▁seperti ▁se bij i ▁bat u ▁yang ▁ber go lek ?
▁Katakan lah ▁( wa hai ▁Muhammad ): ▁" A ku ▁tidak ▁ber ha k ▁menu kar kannya ▁dengan ▁ke mah uan ku ▁sendiri , ▁aku ▁hanya ▁tetap ▁menurut ▁apa ▁yang ▁di wa hy ukan ▁kepada ku ▁sahaja .
▁Kami ▁ta nya ▁ada kah ▁dia ▁ingin ▁bersama ▁dengan ▁kami , ▁jadi ▁begitu lah ▁dia ▁ada ▁di ▁sini .
▁Dan ▁de mi ▁sesungguhnya !
▁Yu ▁Ni ang , ▁kamu ▁ini ▁seorang ▁yang ▁bija k ▁dan ▁can tik .
▁Dan ▁kami ▁di ▁dalam ▁lelaki ▁yang ▁tidak ▁baik ▁ne gara
▁Saya ▁tidak ▁peduli ▁jika ▁mereka ▁rasa ▁seperti ▁bel uga ▁ka vi ar ▁ , ▁saya ▁tidak ▁makan ▁ci cak ▁ .
▁Kau ▁ingat ▁kau ▁ka t ▁mana ? ▁Mos co w ? ▁Paris ?
▁Ma ster ▁Tie ▁...
▁Kenapa ▁pula ?
▁Tapi ... ▁Aku ▁mau ▁kau ▁i kut ▁dengan ku ▁malam ▁ini
▁Aku ▁takkan ▁hanya ▁pot ong ▁kau , ▁aku ▁akan ▁pot ong ▁anak ▁kau .
▁Jika ▁i a ▁adalah ▁kes ila pan ▁sesiapa , ▁i a ▁adalah ▁kita .
▁Ju ara , ▁belum ▁ada ▁yang ▁menye but kan ▁mengenai ▁hal ▁ini , ▁Tapi ▁ber apa ▁banyak ▁yang ▁Kamu ▁has il kan ▁untuk ▁per tan ding an ▁ini ?
▁Ma ta ▁yang ▁can tik .
▁Tie ▁me ▁kan gar o o ▁down ...
▁Oh , ▁saya , ▁a a a ... ▁ya , ▁saya ▁tak ▁ba wa ▁pula .
▁is teri ▁kamu ▁orang ▁yang ▁sangat ▁baik
