▁Di je te , ▁a ▁tek ▁je ▁u šla ▁u ▁tri de se tu ?
▁I ▁či m ▁završi š ▁sa ▁pra njem ▁sud ova , ▁ho ću ▁da ▁od eš ▁iz ▁moje ▁ku će .
▁Vaš a ▁je , ▁i ▁samo ▁vaš a .
▁Pri đi te ▁im ▁s ▁ boka ▁kod ▁ste pe nica !
▁Ni ste ▁do bri , ▁ali ▁misli li ▁ste ▁da ▁ce te ... ▁i pak ▁otići ▁na ▁taj ▁škol ski ▁iz let , ▁je ▁li ?
▁- ▁O , ▁Bo ze .
▁- ▁John u ▁ste ▁veoma ▁drag i .
▁Kao ▁da ▁mi ▁je ▁pred ▁no som , ▁ali ...
▁Treba ce ▁vremena ▁da ▁nau ci š ▁da ▁to ▁kontroli še š .
▁Bilo ▁je ▁m ra čno ... ▁samo ▁sam ▁sta ja la ▁tamo ▁do ▁ju tra ... ▁na ▁pl ju sku ...
▁Eu phe ge nia ▁Do ub t fi re .
▁Oh , ▁Lu ize . ▁Pa zi ▁na ▁ovaj ▁pištolj .
▁Cal av ius ▁bi ▁bio ▁mrtav ▁prije ▁nego ▁ti .
▁- V re me ▁za ▁u ba ci vanje ▁star o mod nog ▁š pi ju na .
▁l ▁ ova ko ▁do la ze ▁te ški ▁da ni ▁za ▁mlad un ča d .
▁Ovo ▁je ▁is pit .
▁Je ▁li ▁to ▁vaš a ▁briga ▁za ▁njegov u ▁ta šti nu ?
▁Reci ▁mi ...
▁Če sti tam , ▁otkri li ▁ste ▁or už ije .
▁Možda , ▁uh ...
▁Vrati ▁se ▁na ▁Mar u , ▁i ▁spre mi ▁se ▁za ▁ eva ku aciju . ▁Dy lan ▁od java .
▁Je ben o ▁smo ▁za rob ljeni ?
▁- Ni je ▁bit no , ▁i ▁dalje ▁moraš ▁razgovara ti ▁sa ▁polici jom .
▁Neka ▁tim ▁za ▁s pušta nje ▁radi ▁u ▁grup ama ▁po ▁dvoj e . ▁Ne ▁želim ▁da ▁niko ▁ovde ▁osta ne ▁sam .
▁Jesi ▁li ▁tu , ▁Mark ?
▁Do k ▁ne ▁budem o ▁sazna li ▁više , ▁pazi ▁se .
▁- ▁To ▁je ... ▁če sti tka .
▁Ti ▁si ▁već i .
▁Šta ▁si ▁bio ▁uradio ?
▁I ▁vidi o ▁sam ▁ih ▁u ▁krevet u .
▁Šta ▁radiš ?
▁Kad ▁si ▁kod ▁ku će , ▁koristi ▁ovaj ▁dal jin ski .
▁Luci a ▁ka ze ▁da ▁vas em ▁ti mu ▁treba ▁pomoc , ▁zato ▁sam ▁ovde .
▁Ob ično , ▁kod ▁policaj aca ▁pi ja telja , ▁jedan ▁je ▁is prav na ▁ cje pi d laka , ▁a ▁drugi ▁od met nik .
▁La ku ▁noć .
▁A ▁da ▁ga ▁ob javljuje mo ▁i ▁ne kom ▁ne ara pu
▁Ma lo ▁u š to g ljena .
▁Živ ▁je , ▁ali ▁je ▁na ▁aparat ima . ▁Doktor i ▁ka žu ▁da ▁ima ▁50 / 50 ▁šans i ▁za ▁život , ▁i ako ▁ima ▁samo ▁10 % ▁šans i ▁za ▁to .
▁Los a ▁informacija , ▁nije ▁bilo ▁ag res iv nog ▁ot por a .
▁U zor kova ce mo , ▁a ▁onda ▁mo zem o ▁da ▁joj ▁pomogne mo .
▁Ma ▁u ▁čemu ▁se ▁raz i lazi li , ▁treba ▁pres udu ▁dati ▁Allah .
▁Ko s tolo mac !
▁Za bavi ćemo ▁se ▁u ▁Lisa bon u , ▁mom ci !
▁Ne ćemo ▁samo ▁da ▁sed imo ▁ovde ▁radi ▁de kor acije , ▁u ▁redu ?
▁Ja ▁se ▁po nek ad ▁pret var am ▁da ▁su ▁stvari ▁bolje ▁čak ▁i ▁kad ▁nisu .
▁Vo don ošo !
▁Pro sto ▁ko ▁pas ul j .
▁Tvoj ▁auto ▁klub ▁ima ▁par ▁Por sche ▁Spe ed ster a ▁iz ▁19 56 .
▁Vi ▁ste ▁sin ▁Ja nar dan ▁Gan gul ija ?
▁Zašto ▁ne bi ?
▁Mislim ▁da ▁ćeš ▁mi ▁oprosti ti ▁kad ▁završi š ▁ psi ho ▁terapi ju .
▁Mu ška rac , ▁prvi ▁raz red , ▁podaci ▁se ▁ne ▁pod uda ra ju .
▁Da . ▁Moj ▁ba lon ▁je ▁na i šao ▁na ▁ temperatur nu ▁in ver zi ju .
▁- ▁Če ga , ▁ged ore ?
▁Zašto ▁ne ▁traži mo ▁od ▁Wall ▁Street a ▁da ▁po či sti ▁svoj ▁v last iti ▁ne red ?
▁Stvarno ▁?
▁Nije dan ▁go lub ▁pis mono ša ▁nije ▁ oz li je đen ▁za ▁vrijeme ▁s nim anja .
▁- ▁DA , ▁B IV ?
▁Ne ▁pri lazi , ▁molim ▁te !
▁Mc G ill , ▁Pod sjeća m ▁vas ▁da ▁ste ▁još ▁pod ▁za klet vom .
▁Zašto ▁ti ▁uvek ▁od usta ješ ?
▁Izvini , ▁Bil i .
▁Osta vio ▁je ▁ovo .
▁En o ▁jedne .
▁Ja ▁ću ▁se ▁posta rati ▁za ▁njih .
▁Da ▁bi ▁Bil ▁i ▁S lim ▁bili ▁place ni .
▁Kao ▁ze či ći .
▁Ma lo ▁si ▁nerv o zan , ▁šta ▁ne ?
▁Polic aj ce , ▁policaj ce . .
▁A ▁rekao ▁sam ▁cu dne , ▁jer ▁one ▁za ista ▁ne ▁izgleda ju ▁ljudsk i .
▁- ▁Jako ▁dobro .
▁D je ča ci ▁iz ▁hora ?
▁Ovo ▁je ▁Victor ▁Steven s , ▁glavni ▁sa vije t nik ▁u ▁Bi jelo j ▁Ku ći .
▁Moj ▁Bože .
▁R ha ps odi ze .
▁Jedno stav no ▁i ▁čist o ▁... ▁i ▁uku s no .
▁- B ili ▁ste ▁2 ▁godine ▁u ▁interna tu ?
▁Bru se , ▁tako ▁je ▁pis alo ▁u ▁članku .
▁- Da .
▁Imam ▁motor e ▁u ▁gara ži .
▁I gor ...
▁Ovo ▁je ▁bilo ▁lepo , ▁bud alo .
▁Šta ▁do đa vola ▁ti ▁radiš ▁ovdje ?
▁Stan i !
▁Izgleda ▁da ▁ga ▁je ▁O skar ▁uz eo .
▁Mi ▁smo ▁ovdje ▁zbog ▁mr .
▁Do , ▁po đi ▁sa ▁mnom .
▁Koliko ▁je ▁u dalje n ▁zal jev ▁Mor gus ?
▁Samo ▁gleda jte ▁ra vno ▁is pred .
▁S red nje v je kov na ▁bo san ska ▁država ▁je ▁jedna ▁od ▁naj s tari jih ▁u ▁Evrop i ▁i ▁dat ira ▁još ▁iz ▁11. ▁stol je ća .
▁- Ne ću .
▁- ▁Da , ▁dana s ▁mi ▁je ▁29 ▁ .
▁Na po lje , Š tab ni .
▁Dor oti ▁ne ▁bi ▁nikada ▁s kin ula ▁tak vu ▁hal jin u .
▁- Ho tel ▁je ▁pod ▁s tica jem .
▁Što ?
▁Da ▁vidim o ▁sla že ▁li ▁se ▁s ▁ovim ▁što ▁imamo .
▁Sta ▁radi s ?
▁NE ▁ZA ▁K AI .
▁- N aj glu p lja ▁odluka ▁u ▁po vijesti .
▁# Ne ki ▁ljudi ▁čeka ju ▁ce o ▁život # ▁# na ▁ ova kav ▁trenutak #
▁Po stavi ▁le đa .
▁- ▁Treba o ▁sam ▁da ▁znam !
▁Šta ▁ti ▁je ▁to ?
▁Bro j ▁dva na est . ▁1 ▁5. 70 ▁fra na ka .
▁Ve če raš nju ▁mis u ▁tijekom ▁za m ra čen ja ▁drži ▁ra bin ▁Tri bbi ani .
▁Bilo ▁bi ▁prav ed no ▁da ▁me ▁uh vate ▁i ▁kazn e .
▁Šta ▁se ▁čeka ?
▁ lli ▁možda ▁gre ši m .
▁I ▁tu ▁je ▁i ▁zen a ▁sa ▁tobom .
▁Moramo ▁biti ▁pa ž ljivi .
▁Što ▁je ▁on dje ▁radio ?
▁Bio ▁je ▁u ▁drugo j ▁so bi .
▁Ne će ▁biti ▁gore ▁od ▁sa sluš anja ▁O bal ske ▁stra že .
▁Ja ▁post avljam ▁pitanja .
▁Ne tko ▁me ▁vu če ▁prema ▁zemlji .
▁Ako ▁ima ▁sreć e ▁da ▁u ▁škol i ▁ima ▁dobre ▁profesor e , ▁pre pozna će ▁simptom e ...
▁- P u sti ▁me ▁u ▁et er , ▁neka ▁me ▁vidi .
▁- H ej , ▁kako ▁si ?
▁Ima te ▁samo ▁jednu ▁minut u ▁da ▁ga ▁neutral izi rate .
▁Sk inimo ▁I ja gu ▁s ▁naš ih ▁I ju di .
▁Šta ▁je ▁s ▁tobom ? ▁Šta ▁ti ▁je ?
▁Pokuša o ▁sam ▁da ▁razgovara m ▁s ▁n jom , ▁ali ... ▁samo ▁bi ▁nešto ▁pro m r m lja la .
▁Do re en , ▁g . ▁Green .
▁- ▁C ista ▁zem lja .
▁- Ka ko ▁ste ?
▁" ▁Let ▁je ▁i šao ▁za ▁ni geri jski ▁glavni ▁grad ▁Ab uja - u ▁i ▁smatra ▁se ▁da ▁je ▁u ▁njemu ▁bilo ▁nekoliko ▁ni ge rij skih ▁u gled nika ."
▁Jer ▁sad ▁je ▁za sta ▁lo š ▁trenutak ▁za ▁šal e . ▁V jer uj ▁mi .
▁ TR G ▁ VE TER ANA , ▁22 : 50 h .
▁Da ▁je ▁moj ▁muž ▁učini o ▁ona ko ▁nešto , ▁mogao ▁bi ▁da ▁mo li ▁na ▁kol en ima , ▁u bila ▁bih ▁ga ▁na ▁me stu .
▁Jeste ▁li ▁u bili ▁kar dina la , ▁Chap o ?
▁Ali ▁zar ▁se ▁ne ▁bri neš ▁za ▁Fil a ?
▁Kako ▁to ▁od bi ti ?
▁- ▁Temp irano ▁u bi stvo ?
▁To lika ▁in tu i cija ▁me ▁pokr e ce . ▁Hajde ▁sa ▁mnom .
▁Za h val ju jući ▁gosp . ▁La bi fu , ▁pro ma ši li ▁smo .
▁Je ▁li ▁to ▁ne služ ben o ▁mišljenje ▁ili ▁ga ▁smije m ▁po no viti ?
▁- Si gur no ▁ce te ▁uz i vati ▁u ▁ njima ▁kad ▁se ▁bude te ▁vra ca li .
▁Po ne ću ▁ti ▁ tor bu .
▁Ob eć ava š ▁da ▁me ▁ne ćeš ▁dir nuti ?
▁To ▁više ▁znam
▁Mislim ▁da ▁je ▁presta lo .
▁- ▁Da , ▁vrij edi ▁2 ▁mili ju na .
▁Slu s aj ▁me . ▁Ovo ...
▁Ko je ▁je ▁tvoje ▁om i ljeno ▁mjesto ▁za ▁ru čak ?
▁- Ho ćemo .
▁Vi še ▁bih ▁voli o ▁ne ...
▁Kor del iji ?
▁V jer u jte ▁u ▁Allaha ▁i ▁Pos la nika ▁Njegov og ▁i ▁tro ši te ▁od ▁on og ▁čemu ▁vas ▁je ▁učini o ▁na sljed ni cima .
▁Na pad ▁je ▁za vrš en .
▁To ▁je ▁Mal va do .
▁ili ▁iza đe .
▁Znaš ▁da ▁je ▁mušk o ▁jer ...
▁Invest i tori ▁invest iraju ▁- ▁i ▁ja ▁od lu c ujem ▁kom e ▁da ▁se ▁poz aj mi ▁novac .
▁Po nek ad , ▁ cak ▁i ▁a stro na uti ▁nav rate .
▁Kon rade , ▁obe ca o ▁si ▁pitanja ▁i ▁odgovor e .
▁Moram ▁priv u ci ▁njihov u ▁pa ž nju , ▁moraju ▁zna ti ▁da ▁sam ▁bud na !
▁V re me ▁her oja ▁je ▁pro šlo , ▁Wi gla fe .
▁Sa ▁za d ovolj stvo m , ▁gospodine .
▁Ili ▁pro val nik ▁koji ▁voli ▁slik e .
▁Hajde , ▁Š il jo !
▁Možda ▁ovo ▁pomogne . ▁Moj ▁koleg a ▁s ▁fa ksa ▁radi ▁u ▁banc i ▁Kelly ▁Union .
▁Ne ▁volim ▁či z me .
▁Ili ▁samo ▁ja ▁tako ▁mislim ?
▁Up isa o ▁sam ▁fa ks ▁kao ▁se bi c ni ▁samo t nja k , ▁ali ▁vi ▁ste ▁me ▁po u cili ▁prijatelj stvu .
▁Možete ▁da ▁se ▁raz boli te .
▁- ▁U či ni ću ▁kako ▁otac ▁želi . ▁- ▁Hoćeš ▁li !
▁Moj ▁Bog ▁se ▁br ine ▁za ▁mene .
▁Sa ▁moj im ▁solid nim ▁pozna vanje m ▁um jet nosti ▁rekao ▁bih ▁da ▁je ▁ovo ▁od li čan ▁rad .
▁Mora ▁da ▁je ▁bilo ▁mu čenje . ▁Ok .
▁To ▁je ▁ne ob ično , ▁is tina .
▁S red ili ▁ste ▁mi ▁od elo .
▁Ron al do , ▁se ća m ▁se ▁t vog ▁prvo g ▁dana ▁na ▁pos lu , ▁bio ▁si ▁toliko ▁up laš en ▁da ▁si ▁se ▁us ra o .
▁Ti ▁si ▁crn ac .
▁Hvala . ▁Je su ▁li ▁nos oro zi ▁mono gam ni ?
▁- Re ci ▁ , ▁mom če ▁!
▁O vi ▁su ? ▁- ▁Da .
▁Ne l son ▁je ▁na ▁ce kan ju .
▁Te ško ▁da ▁ćeš ▁ne g dje ▁to ▁na ći .
▁Nije ▁tako ▁mlad a ▁kao ▁što ▁misli .
▁Ovo ▁je ▁naš a ▁žrtv a .
▁Svi ▁su ▁zajedno ▁i ▁svi ▁se ▁pozna ju . ▁Raz ume š ? ▁Da .
▁Sa ▁te ški m ▁ kora cima ▁klo mp .
▁Da ▁potroš im ▁posledn jih ▁par ▁dana ▁života ?
▁Gdje ▁drži š ▁tu ▁glup u ▁stvar ?
▁Za s pala ▁sam .
▁# ▁Da ▁ti ▁ka ze ▁da ▁se ▁s n ovi
▁- ▁U ▁redu ... ▁Kako ▁je ?
▁Pol je ▁je ▁puno ▁o klop a .
▁- ▁Vo zi cu ▁se ▁oko ▁po lu o str va .
▁To ▁je ▁... ▁to ▁je ▁samo ▁nije ▁jasno .
▁- Ko ju ▁ne ćeš ▁koristiti .
▁Ne ko ▁je ▁u kra o ▁Če ster a ?
▁29. ▁av g usta ▁1981 . , ▁oko ▁150 ▁km ▁u ▁unutra š njo sti ▁Ang ole , ▁bili ▁smo ▁u ▁operacij i ▁i ... ▁Bio ▁sam ▁u ▁la ko ▁o klop ljeno m ▁vozi lu , ▁To jo ti ▁le nd ▁kru zer u , ▁koja ▁je ▁ima la ▁platform u ▁za ▁te ški ▁mi tra lje z ▁kali bra ▁250 ▁Bro ving .
▁Dan as ▁se ▁u god no ▁od ije vamo ?
▁- ▁Sad ▁su ▁svi ▁njihov i ▁s n ovi ... ▁- ▁Kako ▁je ▁di vno ▁biti ▁maj ka ! ▁Nema ▁bolje g ▁posla .
▁Je ▁li ▁u šao ?
▁Za mišljen a , ▁pra g mati čna , ▁str pl j l va .
▁Pr va ▁noć ▁je ▁te ška .
▁D je voj ke , ▁ho će te ▁li ▁biti ▁dobro ▁same ?
▁Oh , ▁vidi , ▁to ▁nije ▁naš a ▁kriv ica ▁nam ▁je ▁potreba n ▁domov inu .
▁Ba ci ▁ga , ▁je be m ti .
▁Kad ▁se ▁izgubi š , ▁najbolje ▁se ▁vratiti ▁na ▁počet ak .
▁Onda ▁im ▁je ▁ovo ▁pro mak lo .
▁Moraš ▁da ▁budeš ▁koncentr iran ▁na ▁i gru
▁Tako đ er ▁u ▁okviru ▁novo sti ▁iz ▁na uke : ▁Beograd ▁doma ći n ▁ konferenc iji ▁min ista ra ▁obraz ovanja ▁zemalja ▁za pad nog ▁Bal kana , ▁a ▁u ▁Ru muni ji ▁op ala ▁proda ja ▁personal nih ▁komp ju tera .
▁Idemo , ▁pod ign ite ▁ci jev ▁za ▁dis anje .
▁To ▁ste ▁u radi li ▁i ▁za ▁moju ▁ma mu ▁jos ▁196 2, ▁pa ▁su ▁nas ▁pre sel ili ▁ovamo !
▁Ken ny , ▁samo ▁proba j ▁da ▁se ▁s miri š .
▁Ali ▁Den ny ija ▁nije ▁bilo ▁briga .
▁Franc u zi ▁su ▁su djel ovali ▁u ▁u vo đen ju ▁ten kova ▁i ▁zrakoplov a , ▁ali ▁učini li ▁su ▁ned ovolj no ▁za ▁pro ši ren je ▁njihove ▁upotreb e .
▁Šta ▁radi ▁tvoj ▁otac ?
▁Rekla ▁je ▁da ▁će ▁do ći .
▁Od mah ▁te ▁obr iš em .
▁Naravno , ▁u bed ljiva ▁osoba ▁bi ▁mogla ▁da ▁ot klon i ▁bilo ▁ka k ve ▁formal ne ▁za vr z la me .
▁- ▁Plan ira te ▁li ▁da ▁uh ap site ▁E isen heim a ?
▁- ▁Chuck ?
▁- He II o !
▁Ti ▁bol es ni ▁ku čki n ▁sine !
▁Zašto ▁se ▁zama raš ▁ , ▁Bro ck man ?
▁Pr va ▁spre m ljena ▁por uka .
▁Da ▁to ▁više ▁nikad ▁nisi ▁u radi la !
▁Kar ta ▁po ker . ▁– Sa če kaj .
▁Pu no ▁si ▁me ▁iz ner vir ao , ▁Ray .
▁Uh , ▁ovdje ▁sam .
▁Te mel j ni ▁u stav ▁Kar o line , ▁autor a ▁fil o zo fa ▁John a ▁Lo cke a ▁trebao ▁je ▁do vesti ▁red ▁u ▁ovu ▁novo na se ljen u ▁div lji nu .
▁Pa ▁da ▁to ▁su ▁nam ▁obe ća li .
▁Treba ▁ CT ▁gla ve , ▁ EK G ▁i ▁prov jer u ▁pr sa .
▁Is pri čaj ▁mi ▁o ▁prvo m ▁putu ▁kad ▁si ▁spava la ▁sa ▁James om .
▁Gre sis , ▁postoji ▁neko ▁za ▁svakog , ▁neko ▁sa ▁ki me ▁ti ▁je ▁su dje no ▁da ▁prove des ▁osta tak ▁zi vo ta .
▁Ne sto ▁sto ▁ze lim ?
▁S jedi os am cije I i dan .
▁Zašto ▁se ▁ne ▁ oka neš ▁tog ▁slik anja ▁i ▁odluči š ▁nešto ▁za ▁svoju ▁budu ć nost ?
▁Sve ▁više ▁djevoj či ca ▁jednostavno ▁ne ▁je de .
▁Č a ša ▁ti ▁je ▁prazn a .
▁Poč i njem ▁misli ti ▁da ▁je ▁vrijeme ▁da ▁iza đem o ▁iz ▁posla ▁Bol en .
▁- Da .
▁Ho ću ▁prizna nje , ▁i ▁uz ima m ▁ga .
▁I ▁kada ▁ki ši .
▁Za ▁vas , ▁on ▁je ▁samo ▁mašin a ▁za ▁r ješ avanje ▁zlo cina .
▁Jesi ▁li ▁je ▁ti ▁na ruč ila ?
▁- ▁ili ▁nešto ▁tak vo .
▁U ▁bor bi ▁do ▁posledn je g ▁čo ve ka , ▁po bed nik je ▁on aj ▁koji ▁posledn ji ▁osta ne ▁na ▁no gama .
▁I ▁ ovi ▁ trag ovi ▁su ▁s vjež i .
▁I ▁bude ▁re čen o : ▁" Ko ▁je ▁vra č ?"
▁Ni sta ▁od ▁ovog a ▁se ▁ne ▁bi ▁des ilo ▁da ▁smo ▁ostali ▁ku ci ▁na ▁Dan ▁Za h val nosti ▁kako ▁Bog ▁i ▁za poved a !
▁O ▁moj ▁Bože , ▁Em ili . ▁Žao ▁mi ▁je .
▁Samo ... bud i ▁pa ž ljiva .
▁Da ▁li ▁ti ▁to ▁pre is pit uješ ▁general ove ▁odluke , ▁kap etan e ?
▁- S r ce ▁se ▁za ple te ▁oko ▁sje či va .
▁nev jer ni cima , ▁neće ▁biti ▁lag ahan .
▁I ▁kaže ▁da ▁neće ▁presta ti .
▁Maj ko , ▁ako ▁opet ▁do dje te ▁u ▁To ki jo , ▁molim ▁te ▁da ▁do dje s ▁u ▁pose tu .
▁Nije .
▁Pa , ▁bilo ▁pravo ▁ili ▁ne , ▁kriv o ▁mi ▁je ▁ ą to ▁nisam ▁poz van ▁na ▁ven čan je .
▁Slu šal a ▁si , ▁zar ▁ne ?
▁Osta ni te ▁na ▁Sul li .
▁Izvini te
▁Se dam ▁dolara ▁dne vno .
▁Možete ▁li ▁plak ati ▁na šao ▁na ▁pravo m ▁mje stu ?
▁Got ovi ▁smo ▁s ▁čeka njem .
▁- Ni je ▁te ▁zna la ▁od ga jati .
▁Bi ćemo ▁na ▁p ješ a čko m ▁most u ▁par ▁sto tina ▁meta ra ▁dalje .
▁- ▁Šta ▁ti ▁je , ▁kom bat ?
▁Čuo ▁sam ▁da ▁spre ma š ▁su tra š nju ▁mem ori jal nu ▁pro s la vu .
▁Ne , ▁ali ▁me ▁po vije st ▁fa s cin ira .
▁Kad ▁je ▁maj ka ▁o ti šla , ▁moj ▁otac ▁je ▁ri ješ io ▁da ▁nikad ▁više ▁ne ▁igra ▁ko ša rku .
▁Reci ▁joj ▁kako ▁mi ▁ide , ▁Alan e .
▁Pro ci tali ▁ste ▁je ▁i ▁da li ▁mi ▁sti pend iju .
▁Be ši ka ▁mu ▁je ▁bila ▁vel ici ne ▁rezerv o ara .
▁U dar ▁od ▁2 ▁meg ato ne ▁nad ▁Se at tle om ▁i ▁1 ▁meg ato ne ▁nad ▁Det ro i tom ▁u ▁ovoj ▁m rac noj ▁v je z bi ▁katastrof e .
▁Neka ▁vaše ▁kar te ▁spremn e , ▁da me .
▁Ne ću ▁to ▁da ▁uradim .
▁Ne ▁želim ▁biti ▁dio ▁ovog a .
▁To ▁mora ▁da ▁je ▁polici ja !
▁Po sljed nja ▁večer a .
▁Hajde !
▁A ▁od ▁tebe ▁nikada ▁ne ću ▁od usta ti .
▁Da ▁vidim o ▁šta ▁će ▁ti ▁večer aš nji ▁san ▁otkri ti .
▁Ova ▁olu ja ▁se ▁nije ▁razvi la ▁u ▁torna do , ▁ali ▁kad ▁to ▁u ci ni ▁stvarno ▁možete ▁da ▁vidi te ▁o cu vanje ▁moment a ▁ koli cine ▁ kret anja ▁u ▁akcij i .
▁Mislim ▁da ▁si ▁ovog a ▁malo ▁previše ▁is p lju vala .
▁Zar ▁on ▁ne ▁spava ▁s ▁drugim a ?
▁- I ▁ja ▁tako dje .
▁Pro pis i ▁o ▁ob la čen ju ?
▁Koliko ▁već ▁uz ima š ▁te ?
▁Ho dat ▁ću .
▁Ne , Ka ish ...
▁Nije ▁sm jela ▁da ▁koristi ▁ni ▁internet .
▁Ar lo ▁će ▁osta ti ▁kod ▁nas ▁na ▁nekoliko ▁dana , ▁ako ▁nema š ▁ništa ▁protiv .
▁Mo ć no ▁mom če ▁me ▁nikada ▁ne ▁bi ▁tako ▁proda o .
▁ze lim ▁da ▁ne sto ▁zna s .
▁- ▁Šta ▁nije ▁u ▁redu ?
▁Imam ▁mnogo ▁proizvoda ▁unutra .
▁Onda ▁bi ▁mogao ▁na let iti ▁kasnije ▁večer as .
▁Pan ter ▁je ▁sa kup lja o ▁informacije ▁o ▁svim a ▁nama , ▁ha kova o ▁je ▁od ▁D Ž AR V ISA ▁naše ▁fa j love .
▁Ja ▁ću ▁ka fu .
▁Prov ući ▁ću ▁je ▁kroz ▁če lo .
▁Zna ▁on ▁kako ▁se ▁osjeća m , ▁ali ▁tako đe ▁zna ▁da ▁ne ▁postoji ▁ništa ▁što ▁možemo ▁u radi ti ▁da ▁to ▁pro m jen imo , ▁tako ▁da ▁nema ▁po ente ▁u ▁priča nju ▁o ▁tome .
▁Uz ▁tebe ▁nije ▁la ko .
▁Muka ▁mi ▁je ▁bilo ▁od ▁tebe ▁mnogo ▁pre ▁toga .
▁Mislim ▁da ▁si ▁ti ▁sada ▁vod nik , ▁D ž ok .
▁Pre zen t acija ▁će ▁mora ti ▁da ▁čeka .
▁Osim ▁u obra že ne ▁ra vno du š nosti .
▁Znam ▁da ▁je ▁malo ▁po vu čen a , ▁ali ▁sme ši ▁se , ▁gr li ▁me ▁i ▁ljubi ▁kao ▁sva ka ▁de voj či ca .
▁O ve ▁reform e ▁le git imiz oval e ▁su ▁Men ema ▁koji ▁je ▁done o ▁više ▁od ▁300 ▁ured bi , ▁10 ▁puta ▁više ▁nego ▁u ▁celo j ▁is tori ji ▁Argent ine .
▁cita la ▁si ▁moj ▁dos je .
▁Je ▁li ▁u ▁redu ?
▁O t kri o ▁sam ▁da ▁je ▁up le ten ▁u ▁proda ju ▁povjer ljivi h ▁podataka .
▁Tim ▁1, ▁videl i ▁smo ▁os um nji ce nog .
▁Međutim ▁ima ▁jedna , ▁sa ▁normal ni jim ▁dogovor om .
▁Z vala ▁sam ▁ih ▁zbog ▁tebe .
▁Jeste ▁li ▁razmišlja li ▁o ▁tome ?
▁Kaž u ▁da ▁je ▁pob ega o ▁zatvoren ik .
▁– On ▁je ▁la ž ov .
▁Gro zan ▁za data k ▁za ▁pre uze t .
▁Ako ▁su ▁van zem al j ci ▁bili ▁ovde ▁u ▁da leko j ▁pro šlo sti , ▁postoji ▁više ▁vrsta ▁tamo ▁ne g de , ▁da ▁li ▁je ▁moguće ▁da ▁mogu ▁da ▁izgleda ju ▁na lik ▁gu š ter ima ▁i ▁m rav ima ?
▁- ▁Šta ▁se ▁dešava ? ▁Po žu ri .
▁Li je po ▁i ▁po lako ▁u ▁po lje .
▁- ▁O ba ▁pal ca ▁en tu zija sti ch ki ▁pod ign uta .
▁Sigur an ▁sam ▁da ▁će ▁J . L . ▁Hall ▁biti ▁vrlo ▁impre sion iran ▁tvoj oj ▁stra š ću ▁za ▁is ku stvo m ▁na ▁Dar t mouth u .
▁Pre t post avljam ▁da ▁naš a ▁sreć a ▁i ▁dalje ▁drži .
▁- ▁Ide š ▁s ▁nama ▁na ▁do ruč ak ?
▁Tri , ▁četiri ▁ ča še ?
▁O vi ▁mali ▁ro đa ci ▁slo nova , ▁samo ▁su ▁de o ▁dugo g ▁lan ca ▁is hra ne .
▁Po bri nut ▁ću ▁se ▁za ▁to . ▁Tre ner u , ▁smi rite ▁svoje ▁de čke .
▁Mogu ▁te ▁vidjeti , ▁Han a !
▁Ti ▁me ▁o stavlja š ▁ra vno du š nim .
▁Do bio ▁je ▁po mil ovanje .
▁Osta vio ▁je ▁ka put ▁kod ▁mene .
▁Pa ▁ako ▁is ▁i spod ▁50 ▁ , ▁mora s ▁malo ▁bolje ▁da ▁se ▁br ines ▁o ▁se bi .
▁Ja ▁sam ▁Charlie ▁You ng .
▁Ne ▁bih ▁dira o ▁ovaj ▁za hod ▁ni ▁sa ▁se stri nim ▁pal cem .
▁Telefon , ▁g đ o ▁Ma tur in .
▁To ula ▁ga ▁voli .
▁Na ▁ovom ▁planet u ▁je ▁uvijek ▁noć .
▁Raz ve o ▁sam ▁se ▁prije ▁mje s ec ▁dana .
▁Zbog ▁toga ▁smo ▁pov eć ali ▁cenu ▁za ▁10 ▁cent i , ▁pa ▁ka fa ▁ko šta ▁50 ▁cent i .
▁Č uj , ▁i ▁kad ▁vas ▁od vez em ▁tamo , ▁moram ▁se ▁vratiti ▁i ▁poslova ti ▁s ▁tom ▁lu kom .
▁Hajde , ▁Ri t chie , ▁ha jde , ▁čovjek , ▁ma ▁da j .
▁Am ita bh ▁mi ▁ga ▁je ▁da o !
▁Ve oma ▁je ▁br z .
▁Onda ▁ignor i raj ▁zakon .
▁Kada ▁sam ▁bio ▁de te ▁ona ▁mi ▁je ▁bila ▁naj dra ža ... ▁i ▁sada ▁vidim ▁da ▁je ▁najlepš a ▁stvar ▁koju ▁sam ▁ik ada ▁video .
▁Hoćeš ▁na stava k ? ▁ . ▁- Po z ovi ▁si ▁koleg e .
▁- ▁Ne . ▁Ve čer as ▁ću ▁razgovara ti ▁s ▁n jom .
▁- ▁Pa , ▁ja ... ▁ne ▁bih ▁to ▁nu ž no ▁tako ▁na zava o .
▁Hvala ▁što ▁si ▁do šla ▁da ▁me ▁vidiš .
▁Gad no ▁sam ▁po gri ješ io .
▁- Ka o ▁da ▁imam ▁pet ▁godina .
▁Je di no ▁o ▁čemu ▁mislim ▁upravo ▁sada ▁je ▁tvoja ▁maj ka , ▁i ▁ ova ▁por o dica .
▁- Pro m jena ▁plan a ▁put ovanja , ▁ze ko .
▁- Mo ž da ▁godina .
▁- A ▁to ▁je ▁oči to ▁bilo ▁dovoljno ▁jako ... ▁da ▁o stavi ▁ trag ove ▁ma gnet ne ▁si le ▁na ▁metal nim ▁objekt ima ▁u ▁bli zini .
▁Znaš , ▁ja ▁sve ▁ovo ▁mogu ▁ku piti ▁preko ▁ne ta .
▁All y ▁je ▁li ▁tvoj ▁drag i ▁sin o ć ▁is me vao ▁moju ▁situa ciju ▁sa ▁Kim i ?
▁Či me ▁se ▁vi ▁ba vite ? ▁- ▁Za prav o ▁sam ▁spis a telj ica .
▁- ▁Kako ▁ste ▁- ▁mama .
▁slo m ljen !
▁Ste ne ▁nam ▁ govor e ▁kako ▁je ▁ovo ▁kop no ▁na sta lo ▁i ▁kako ▁je ▁njihov a ▁ge ologi ja ▁učini la ▁da ▁ovo ▁posta ne ▁gus to ▁na se ljen ▁i ▁na pre dan ▁grad ▁koji ▁pul s ira .
▁- ▁Samo ▁trenutak .
▁- ▁Ko ▁kaže ▁da ▁i ▁ti ▁ne ▁od lu č uješ ?
▁U ▁su prot nom , ▁nema ▁dogovor a .
▁Uz ▁ imit aciju ▁Christ op her ▁Wal ken a ...
▁Pa ▁si ▁prove la ▁noć ▁sa ▁neki m ▁mušk ar cem ?
▁Go s po đi ce , ▁ko ▁je ▁ona ▁žena ?
▁U ▁ima ▁o ca ▁i ▁sina ▁i ▁svet g ▁du ha , ▁a men .
▁Ne ćemo ▁ti ▁dozvoli ti ▁da ▁uz me š ▁Vi bran i jums ku ▁Plan inu !
▁To ▁je ▁bilo ▁jedno ▁u op sten o ▁pis mo .
▁I ▁bio ▁je ▁obje šen .
▁Ci jeli ▁specijal ni ▁tim ▁se ▁s jati o ▁gore .
▁I ▁ne ▁plan i ram ▁biti .
▁Ali ▁to ▁je ▁samo ▁za ▁prijatelj e ▁koji ▁me ▁neće ▁u vre di ti .
▁Dosta ▁si ▁se ▁nas pa vala ▁na ▁satu .
▁Pr vo ▁ti ▁reci ▁meni .
▁Tako ▁se ▁toga ▁ sjeća š ?
▁Po ja vit ▁će ▁se .
▁Mo gli ▁bi ▁ staviti ▁naše ▁ljude ▁izvan ▁lokal nih ▁drog er ija , ▁neka ▁do đu ▁do ▁nas .
▁Kom bin acija ▁Dol ores i nih ▁i ▁Han kovi h ▁meta ka ▁su ▁u bili ▁Ed - a .
▁Ne zna m ...
▁Ni tko ▁nas ▁ne ▁bi ču je .
▁Kuka vice .
▁Tak va ▁me ▁politika , ▁ne ▁zanima !
▁Neka ▁se ▁za piš e ▁da ▁je ▁svjedo k ▁napravi o ▁gest u ▁nosa - tru be .
▁I ▁Sha kes .
▁Ovdje , ▁nema mo ▁mobil ne , ▁ni ▁tv iter , ▁nema ▁om etan ja ▁iz ▁vanjsk og ▁svijet a .
▁Pa , ▁znam o ▁kako ▁izgleda , ▁i ▁znam o ▁da ▁je ▁z la .
▁Iz gu bi ćemo ▁sve jedno .
▁Dobro ▁ga ▁pogleda j !
▁Iz ▁jednog ▁mjesta ▁na ▁drugo .
▁Ti š ina , ▁ti š ina , ▁ti š ina , ▁ti š ina !
▁Du van ske ▁komp a nije ▁vas ▁la žu ▁u ▁vezi ▁op as nosti ▁pu š enja .
▁Stan oda vac ▁me ▁iz ba cio ▁iz ▁stan a .
▁Molim ▁sve ▁za ▁pa ž nju , ▁gospod in ▁T wit che ll ▁bi ▁žele o ▁da ▁kaže ▁par ▁re či .
▁Ver uj ▁mi , ▁izgleda će ▁kao ▁da ▁nisam ▁ni ▁o ti šla .
▁Po kaz ach u ▁vam ▁kako ▁se ▁radi .
▁Vi ski ▁molim .
▁Bol es na ▁si ? ▁Če mu ▁toliko ▁c ve će ?
▁Kako ▁je ▁Li ?
▁... 10 1, ▁10 2, ▁103 ... ▁104 , ▁105 , ▁106 ... ▁107 , ▁108 , ▁10 9, ▁110 ...
▁Znači ▁plan ira te ▁pro vesti ▁puno ▁vremena ▁sa ▁Mer rill ovima .
▁R ačun ala ▁je ▁da ▁će te ▁pris tati .
▁Jesi ▁li ?
▁Manuel ▁Ru iz ! ▁Ha ▁visto ▁este ▁hombre ?
▁Do bi će ▁drugo ▁de te .
▁Film ▁O ri jent acije ▁D har ma ▁broj ▁dva , ▁prvi ▁put .
▁Znaš , ▁ako ▁je ▁u op će ▁moguće , ▁izgleda š ▁još ▁bolje ▁nego ▁prije .
▁Vi ... ▁plan ira te ▁da ▁se ▁vrati te ▁u ▁svoju ▁kolon iju ... ▁na ▁dve , ▁možda ▁i ▁tri , ▁četiri ▁godine .
▁I ▁svaki ▁ru čak .
▁To ▁joj ▁je ▁bila ▁za d nja ▁mol ba .
▁Pro vodi š ▁previše ▁vremena ▁razmišlja jući ▁o ▁pro šlo sti .
▁Spa vam ▁bolje , ▁a ▁također ▁i ▁oko ▁stre lja ne , ▁kad ▁sam ▁se ▁tek ▁vrati o ...
▁Dobro ▁je .
▁Hoćeš ▁pošt ovanje ?
▁- Mi s lim ▁da ▁to ▁ne ▁mogu ▁sredi ti .
▁E , ▁tu ▁je ▁on ▁u ▁pravu .
▁Dobro ▁jutro .
▁En o , ▁to ▁je ▁Sa ul ▁Tar sus .
▁M je sto ▁oku pl janja ▁je ▁na ▁be j z bol ▁ter en u ▁800 ▁m ▁sje ver no - sje ver o isto čno ▁od ▁vas .
▁Na dam ▁se ▁da ▁če te ▁se ▁svi ▁vratiti ▁nazad ▁bez bed no .
▁Mislim ▁da ▁ti ▁od ▁svih ▁ljudi ▁ne ćeš ▁napravi ti ▁nešto ▁ako ▁ne ▁odluči š .
▁Fo x ▁tim , ▁pokr et .
▁N ismo ▁bas ▁bile ▁ti he .
▁Dobro ▁izgleda š , ▁Hu ard .
▁- ▁Da , ▁č ujem ▁vas .
▁" V oli ▁te , ▁ta ta ."
▁Mislim ▁da ▁su ▁nauči li ▁ lek ciju .
▁Iz la z nost ▁na ▁izbor ima ▁za ▁Evropsk i ▁parlament ▁u ▁ju nu , ▁zadnje m ▁glas an ju ▁koje ▁je ▁organiz irano ▁u ▁Ru muni ji , ▁bila ▁je ▁tek ▁27 % .
▁Ko ji ▁dio ▁dugo g ▁ zim skog ▁sna ▁nisi ▁razum io ?
▁- V ani ▁je ▁tako ▁lijepo !
▁Kakv o ▁s ranje ."
▁To ▁ti ▁garant ujem .
▁Da ▁te ▁po ve žem ?
▁" Ka kav ▁je ▁ose ća j ▁kad ▁vas ▁tele port uju ?"
▁Tek ▁je ▁prv a ▁če tvrt ina .
▁Radi m ▁za ▁Gospod ina ▁Bar kle ya .
▁O ma tica ye ▁su ▁nauči li ▁o ▁nama , ▁ono liko ▁koliko ▁im ▁treba .
▁Pa ... ▁među ▁nama ...
▁Treba m ▁ ključ ▁za ▁vrata .
▁- O va kva ▁od je ća ▁se ▁nos ila ▁ra nih ▁' 90 - ih .
▁- ▁Ho ću ▁sud bin u !
▁Treba ▁nam ▁rezerv ni ▁plan .
▁Ali ▁šta ▁ako ▁su ▁mu ▁de ca ▁ važ nija ▁od ▁da di lja ?
▁Sad ▁kad ▁je ▁Oliver ▁za uze o ▁svoju ▁pozicij u ▁kao ▁na sljed nik ▁Demo na , ▁do ći ▁će ▁po ▁mene , ▁sa ▁koliko ▁god ▁ljudi ▁bude ▁potrebno ▁da ▁me ▁ubije .
▁Pu no ▁ga ▁volim . ▁I ▁ja .
▁Doug , ▁dosta ▁tip ovima ▁je ▁moje ▁oko ▁od boj no .
▁Mislim ▁da ▁je ▁u ▁kan tini .
▁Kur vin ▁sine !
▁Moram ▁biti ▁na ▁dužn osti ▁i ▁no ću ▁i ▁dan ju .
▁Pa , ▁reci mo , ▁koje ▁bo je ▁želiš ▁da ▁bude ?
▁Stvarno ▁smo ▁kre nu li , ▁je l ' ▁da , ▁komp i ću ?
▁O , ▁Bar ney !
▁Ti ▁si ▁pre var ant ▁i ▁ lop ov , ▁kao ▁i ▁ja , ▁kao ▁i ▁svi ▁ostali .
▁Raz umi o ▁sam , ▁čuva t ▁ćemo ▁ih .
▁Ce ka ▁is pred .
▁Do ne site ▁shi zz le !
▁ KO ng res ▁je ▁done o ▁zakon ▁o ▁od bran i ▁bra ka .
▁Molim ▁vas ▁učini te ▁mi ▁čas t ▁i ▁prihvat ite ▁moju ▁ru ku .
▁Ta mo , ▁vrati te ▁se , ▁skoro ▁ste ▁ uspje li .
▁Dan as ▁se ▁o bil je ? ▁av a ▁kraj ▁global ne ▁katastrof e .
▁Je ▁si ▁li ▁dobi la ?
▁Zdravo , ▁Mur p hy .
▁Pr va ▁i spod ▁c rte .
▁Radi ▁se ▁o ▁ne čem u ▁što ▁ste ▁na pis ali ▁prije ▁o sam ▁godina , ▁o ▁u krš ten oj ▁D N K .
▁Na ▁visi ni ▁o ciju .
▁Francusk i ▁fil oz of ▁Ro land ▁Bar the s ▁opis ao ▁je ▁tra umu ▁kao ▁foto graf sku ▁ vije st ▁bez ▁fotografi je .
▁Pre uze o ▁sam ▁tu ▁so bu ▁kada ▁je ▁otišao .
▁Imaš ▁pravo . ▁Dobro , ▁šta ▁mogu ▁učiniti ▁da ▁pomogne m ?
▁Nisam ▁ga ▁ja ▁na t jera o ▁da ▁is kora ci ▁pred ▁autobus , ▁Sam .
▁To ▁se ▁re do vno ▁dešava .
▁Polic aj ci .
▁Sad ▁pov jes nica ri ▁revi zioni sti ▁ka zu ▁da ▁je ▁bomb a ▁prest ras ila ▁Rus e .
▁Šta ▁će ▁se ▁des iti ▁bez ▁operacij e ?
▁Se stra ▁Hu ghe s , ▁da ▁se ▁ja vi ▁Hi tan ▁prije m .
▁Na ▁primer , ▁D žu li jan ▁Ma ster s .
▁Be ▁my ▁ white ▁kn ight .
▁Hvala .
▁Osim ▁toga , ▁u ▁izvještaj ima ▁se ▁na gov ješ tava ▁da ▁je ▁tur ska ▁komp a nija ▁pri sta la ▁da ▁investi ra ▁20 ▁milion a ▁e ura ▁u ▁njen ▁razvoj .
▁- ▁Da . ▁K nji ga ▁o ▁kojoj ▁sam ▁ti ▁priča o ▁je ▁na ▁moj oj ▁kom odi .
▁Ro đa ci ▁ljudi ▁koje ▁je ▁u bio ...
▁Bu d že tom ▁se ▁poziv a ▁na ▁de fici t ▁od ▁200 m ▁e ura , ▁za ▁koji ▁se ▁kaže ▁da ▁iznos i ▁ukupn o ▁0, 6% ▁od ▁B DP - a .
▁Ne ▁želi ▁Allah ▁da ▁vam ▁učini ▁ik ak vu ▁teško ću , ▁nego ▁želi ▁da ▁vas ▁oči sti ▁i ▁da ▁vam ▁u pot pun i ▁bla go dat ▁S voj u , ▁da ▁bi ste ▁vi ▁zahval ji vali .
▁ OD G OV OR ▁JE ▁D RA KK AR ▁NO IR , ▁V INT AGE ▁19 88 . - A .
▁Ta mo ▁su .
▁Da ▁te ▁pokr i jem .
▁Mislim ▁da ▁bi ▁ti ▁i ▁ja ▁mogli ▁da ▁nauči mo ▁jedno ▁drugo ▁mnogo ▁čemu , ▁pa ... ▁da ▁li ▁si ▁s lobo dan ▁za ▁večer u ▁su tra ▁u ve če ?
▁I ▁koliko ▁se ▁pro si rio ▁taj ▁ose ca j ?
▁- ▁Što ▁si ▁rekao , ▁ tko ▁ba ca ?
▁# ▁Samo ▁smo ▁ja , ▁ti ▁i ▁ljubav ▁# ▁# ▁u ▁K ▁A ▁D ▁I . ▁#
▁To ▁nije ▁način ▁na ▁koji ▁si ▁me ▁nauči o ▁živ jeti .
▁U ▁redu , ▁do šta ▁o ▁Su t ton .
▁Za d iranje ▁u ▁privat nost , ▁da .
▁- ▁Jedno ▁crn o ▁is ku stvo .
▁Za ista ?
▁Sigur na ▁sam ▁da ▁se ▁možemo ▁neka ko ▁dogovor iti .
▁Zbog ▁toga ▁si ▁ hte o ▁da ▁se ▁vrati š .
▁Mia , ▁samo ▁još ▁jedna .
▁Č uj , ▁ion ako ▁bi ▁te ▁h tio ▁ubiti .
▁Ne ... ▁samo ▁se ▁sme ši la .
▁Ali ...
▁Ne ▁bu dite ▁zlo b ne .
▁Val ja ju ▁drog u ▁por ed ▁kli nike , ▁čovječe .
▁Z go dan .
▁Fra k ture ▁po či nju ▁45 ▁cm ▁od ▁stop ala .
▁Ne ▁još .
▁- DA . ▁DO KA Z U JE ▁O NO ▁S TO ▁JE ▁Z IVA ▁S UM N JA LA .
▁Kako ▁znate ▁da ▁je ▁to ▁naš ▁diz ajn ?
▁Mislim ▁da ▁je ▁Rand ▁bi ▁bili ▁s ret ni ▁da ▁se ▁uspostav i ▁... ▁su sje d stvu ▁don acija ▁poboljša nje ▁da ▁se ▁tro ši ▁i pak ▁ste ▁od a bra li .
▁Znaš , ▁kao ▁jo ge .
▁Rekao ▁sam ▁da ▁mr zim ▁ovakv o ▁do vi ki vanje .
▁Sve ▁sam i ▁ke če vi .
▁Do bio ▁si , ▁Pa ddy !
▁Dakle , ▁ako ▁nije ▁ništa ▁radio ▁kriv o , on da ▁datum ▁na ▁ovim ▁dokument ima ▁nije ▁is prav an . ▁I ▁prema ▁use ljeni čki m ▁zakon ima ▁ove ▁zemlje ▁čini ▁ih ▁ne val ja nim ▁i ▁ništa v nim . ▁- ▁Ne !
▁G la z be nik ... ▁sluša j !
▁Kaž eš ▁da ▁me ▁voli š , ▁da ▁ce š ▁me ▁uvijek ▁vol jeti ...
▁Ti ▁si .
▁- ▁Ti ▁si ▁o vis nica ! ▁Slušaj !
▁Kako ▁ide , ▁Greg ?
▁Bil e ▁su ▁Lucy ▁i ▁Claire .
▁Ovo ▁će ▁biti ▁savršen ▁bra k ... ▁ad rena lina ▁i ▁op as nosti .
▁A ... ne ▁svi đa ▁mi ▁se ▁kako ▁izgleda m ▁sa ▁c vi ker ima .
▁Pres v la či ▁Za cha , ▁por ed ▁baz ena .
▁Ne ▁znam .
▁- Ti ▁to ▁ozbiljn o ?
▁Ne ▁u ci ▁dije te ▁tak vom ▁ govor u , ▁ cov je ce .
▁Bože , ▁kako ▁ti ▁mora ▁da ▁pati š .
▁Zato ▁moram ▁da ▁ga ▁vidim .
▁- O be ća j ▁da ▁me ▁ne ćeš ▁pre bi ti . ▁Jer ▁me ▁može ▁pre bi ti .
▁To ▁je ... ▁nepo že l j no ? ▁- ▁Ve oma .
▁To ▁ob jas nja va ▁pov rede ▁koje ▁lice ▁na ▁na si lje .
▁Tre nut no ▁se ▁Si ri jski ▁ar sen al ▁sa stoj i ▁od ▁nekoliko ▁hil ja da ▁So vjet skih ▁br zi h ▁projekt ila . ▁U ▁su šti ni ▁bomb e ▁u ▁ci jevi ma ▁pri ka čen e ▁na ▁veoma ▁ne sigur no ▁gor ivo .
▁Pokuša t ▁ću ▁diplom at sko ▁ rje šenje .
▁Onu ▁drug u ▁des nu .
▁Bila ▁bi ▁ste ta .
▁Ona ▁je ▁za ▁bu dale ▁koje ▁ne ▁zna ju ▁gleda ti ▁slik u , ▁pa ▁po nav lja ju ▁ono ▁što ▁druge ▁bu dale ▁ govor e .
▁- ▁Ju ana , ▁tebi ▁govori m .
▁On ▁je ▁kralj ▁org ija .
▁Ka ranje ▁u ▁pak su .
▁Sve ▁je ▁povez ano .
▁Osim ▁toga , ▁vidim ▁da ▁ion ako ▁je d va ▁ce ka š ▁da ▁mi ▁kažeš .
▁Sto ji ▁69 ▁$ .
▁" T re nut ni ▁prostor ▁mogućnost i ▁nije ▁ne og rani čen , ▁a ▁malo ▁toga ▁govori ▁da ▁će ▁budu ć nost ▁donijeti ▁p ovolj nije ▁okolnosti ▁za ▁na god bu , " ▁izjavi o ▁je ▁on .
▁Znam ▁da ▁sve ▁izgleda ▁bez na de ž no ▁sada , ▁ali ▁ob eć avam ▁ti ▁ima ▁puno ▁stvari ▁za ▁koje ▁moraš ▁živ jeti .
▁Drago ▁mi ▁je ▁da ▁smo ▁na i šli ▁kad ▁ste ▁kod ▁ku će
▁Hajde ▁da ▁proba mo ▁ovo , ▁pomoći ▁će ." ▁Ne , ▁neće .
▁Šta ▁to ▁znači ?
▁Šta ▁je ▁sadržaj ▁že lu ca ?
▁Ne da vni ▁događa ji ▁su ▁da li ▁novo ▁svet lo ▁na ▁osnov u ▁činjenic a ▁i ▁fizičk ih ▁dokaz a ▁koji ▁bi ▁trebali ▁da ▁pomo g nu ▁dokaz i vanju ▁posto janja ▁van zem al j skog ▁života ▁što ▁je ▁osnov a ▁Mol der ove ▁ve like ▁pos ve će nosti ▁svo m ▁rad u
▁Kli nci , ▁u glav nom , ▁tra že ▁let nji ▁posao ▁po ▁resto ran ima .
▁Trebal a ▁bi ▁da ▁do d jem ▁do ▁za m ka .
▁Naravno , ▁kli na c .
▁Dobro , ▁idemo , ▁idemo !
▁Do z voli ćeš ▁da ▁ stavi ▁je zik ▁u ▁tvoja ▁usta .
▁Moramo ▁ih ▁gr li ti ▁i ▁ljubi ti ▁na ▁u lica ma ▁u ▁ku ća ma , ▁u ▁kan cela rija ma , ▁u ▁njihov im ▁um ovima .
▁Svi ▁se ▁č vrst o ▁Allah ova ▁už eta ▁drži te ▁i ▁ nika ko ▁se ▁ne ▁raz jedi nju jte ! ▁I ▁s jeti te ▁se ▁Allah ove ▁mil osti ▁prema ▁vam a ▁kada ▁ste ▁bili ▁ jedni ▁drugim a ▁nepri ja telj i , ▁pa ▁je ▁On ▁s loži o ▁s r ca ▁vaš a ▁i ▁vi ▁ste ▁postal i , ▁mi lo š ću ▁Njegov om , ▁prijatelji ; ▁i ▁bili ▁ste ▁na ▁i vi ci ▁ vat rene ▁ja me , ▁pa ▁vas ▁je ▁On ▁nje ▁spasi o . ▁Tako ▁vam ▁Allah ▁ob jašnj ava ▁S voj e ▁dokaz e , ▁da ▁bi ste ▁na ▁Prav om ▁putu ▁is tra jali .
▁To ▁je ▁zbog ▁stvari ▁na ▁tra ci .
▁Na bavi ću .
▁Ci jeli ▁grad ▁je ▁došao .
▁Bo ze ▁moj .
▁- La ski . ▁Pr vo , ▁nisam ▁že lje la ▁da ▁budem ▁čas nik ▁za ▁obu ku , ▁ali ▁je ▁bolje ▁od ▁vampir a .
▁Auto put ▁pro sje čen ▁pravo ▁kroz ▁ki š nu ▁š umu .
▁Slušaj , ▁moram ▁da ▁vidim ▁tebe ▁i ▁Hej li . ▁Zato ▁što ▁ja ▁radim ▁i ▁sa vet ovanje ▁par ova .
▁Zato ▁što ▁ti ▁na ši ▁val ovi ▁više ▁neće ▁biti ▁taj na .
▁Mo že ▁se ▁reći ▁da ▁joj ▁je ▁ovaj ▁grad ▁slo mi o ▁du h .
▁Dr . ▁Di x on , ▁hvala ▁vam ▁puno .
▁U pa o ▁je ▁u ▁ ša htu ▁od ▁li f ta .
▁U ▁redu , ▁ako ▁ce ▁biti ▁tako , ▁ja ▁cu ▁samo , ▁uh ...
▁Niko ▁me ▁nije ▁osta vio .
▁Za ba van ▁dan ?
▁Što ▁se ▁ti če ▁Ben a , ▁rekao ▁si ▁da ▁ću ▁ga ▁ubiti ▁kad ▁č ujem ▁šta ▁ima ▁za ▁reći .
▁Moja ▁žena ▁u bi ću ▁je !
▁Pe tak ▁več e , ▁a ▁tip ▁koji ▁ima ▁go mi lu ▁rub ina ▁sentiment alan ▁je ▁oko ▁jednog ▁ma log ▁bis era ?
▁A , ▁po če li ▁smo ...
▁Gi ba j ▁se ▁uz ▁muzik u .
▁Zna s ▁bilo ▁sta ▁posebno ▁za ▁so bu ▁za ▁bri dz .
▁Pu c nja va ▁u ▁sud nici , ▁pokuša li ▁da ▁u bi ju ▁Hor ej ši ja ▁us red ▁bela ▁dana ...
▁Za prav o ▁imam ▁tamo ▁neko g ▁posla .
▁Na pa š ćemo ▁veliko m ▁br zi nom ▁kako ▁bi ▁neutral is ali ▁njihovo ▁ jon sko ▁oružje .
▁- ▁Ako ▁osta ne , ▁posta će ▁sumnj ič av .
▁Moz da ▁cu ▁treba ti ▁in tu b irati .
▁Gor e ▁na ▁počet ak , ▁g . ▁San til li .
▁- ▁Bri neš ▁se ▁o ▁mom ▁" mesi ću " ▁?
▁- Ho ćeš ▁na grad u ?
▁Plat io ▁je ▁kroz ▁nos ▁za ▁za d ovolj stvo .
▁- Su sti že ▁nas .
▁Bu da lo , ▁zašto ▁ne ▁puc aš ?
▁Poz na ješ ▁La ▁Qui cu ?
▁O tvor i ▁vrata !
▁Jer , ▁ako ▁dozvoli š ▁da ▁bude ▁zbog ▁tebe , ▁onda ▁pro pada š .
▁Bio ▁sam ▁pri govara č ▁sav je sti !
▁On ▁bi ▁usko čio ▁i ▁odgovara o ▁ili ▁is pravlja o ▁ljude .
▁Zna o ▁sam ▁da ▁će ▁s ▁tom ▁ pti com ▁biti ▁problema .
▁Kako ▁to ▁radiš ?
▁Allah ▁svjedo či ▁da ▁je ▁is tina ▁ono ▁što ▁ti ▁ob javljuje , ▁ob javljuje ▁ono ▁što ▁On ▁jedini ▁zna , ▁a ▁i ▁mele ki ▁svjedo če ; ▁– ▁a ▁dovolj an ▁je ▁Allah ▁kao ▁svjedo k .
▁Jane ▁Val ▁je ▁je li ▁dos ao
▁Bila ▁je ▁tako ▁le pa .
▁- Ti ▁si ▁iz uze t no ▁ljudsk o ▁bi će .
▁Nema ▁te ▁na ▁pos lu , ▁do dje s ▁ta kav , ▁i ▁o ce ku jes ▁da ▁te ▁ne ▁pi tam ▁sta ▁se ▁des ava ?
▁Sam ▁Win che ster ▁je ▁sigurno ▁ovdje ▁bio .
▁- U ▁redu , ▁kod ▁Bu tter mana .
▁To ▁je ▁bilo ▁gru bo , ▁g . ▁Har per u .
▁Ovo ▁je ▁ob i can ▁ne do stoj an st ven o .
▁Ti ▁mora ▁da ▁si ▁Ram se y .
▁G . ▁Th omp son ...
▁Ova ▁na ka za ▁nije ▁u op šte ▁iz bri sala ▁video ...
▁Možda ▁će ▁ga ▁to ▁nauči ti ▁da ▁ubu du će ▁drži ▁je zik ▁za ▁zu bi ma .
▁- ▁Meg an ▁misli ▁da ▁Joe ▁u bio ▁svog ▁brat a ▁previše .
▁Ne ▁mogu ▁pod nije ti ▁ce ndra nje !
▁I ▁oni ▁su ▁se ▁po vrat ili ▁oba s uti ▁Allah ovi m ▁bla go dat ima ▁i ▁o bil jem , ▁nik ak vo ▁ih ▁zlo ▁nije ▁za des ilo ▁i ▁post i gli ▁su ▁da ▁Allah ▁bude ▁ njima ▁za d ovolj an ▁– ▁a ▁Allah ▁je ▁ne iz m jer no ▁dobar .
▁Bol io ▁me ▁je ▁sto mak .
▁Na dam ▁se ▁da ▁si ▁glad an .
▁Ako ▁je ▁to ▁jedini ▁koji ▁ima te , ▁pop uni ćemo ▁ga .
▁Bit ▁ćeš ▁ti ▁dobro .
▁Izgleda ▁kao ▁jedna ▁od ▁o nih ▁scen a ▁kada ▁star e ▁z grade ▁min iraju ▁din ami tom .
▁Ho češ ▁li ▁mi ▁ik ada ▁oprosti ti , ▁Pa d mé ?
▁Imamo ▁malo ▁vremena .
▁Vaš a ▁hra bro st ▁i ▁žrtv a ▁će ▁biti ▁za u vek ▁za pam će ni .
▁Ko ▁je ▁le čio ▁vaše g ▁sina ?
▁Nije ▁tako ▁bit no . ▁Maj ka ▁je ▁pro na šla ▁hal jin u ▁skr oz ▁po kis nut u ▁kod ▁pr lja vi h ▁od ela .
▁O ček ujem ▁da ▁živi m ▁d vo stru ki ▁život .
▁On ▁je ▁bio ▁i ▁iz ▁Bell e view ...
▁Zašto ▁si ▁se ▁moral a ▁ud ati ▁za ▁njega ?
▁- Ne ▁želim ▁ga .
▁Mo gli ▁bismo ▁da ▁ba ci mo ▁B . L . F . ▁kan ister ▁jednom ▁kad ▁smo ▁na ▁prijatelj skoj ▁teritorij i .
▁Ja ▁sam ▁bio ▁uz bu đen ▁kad ▁sam ▁pro na šao ▁ma mu .
▁Nema ▁kost iju .
▁O ko ▁1 ▁500 ▁dolara .
▁Bila ▁si ▁temelj an ▁i ▁pa ž ljiv ▁detektiv !
▁Kaž ete ▁da ▁je ▁kriv ac ▁neko ▁iz ▁moje ▁por o dice ?
▁Osim ▁sto ▁su ▁raz ine ▁glu ko ze ▁normal ne ▁i ▁spo menu o ▁bi ▁da ▁je ▁dija be tica r . ▁A ▁ul ce roz ni ▁kol iti s ?
▁- J ed no stav no ▁je sam , ▁El lie .
▁El ▁Os o ▁uvijek ▁ud ara ▁Sa la zara ▁po ▁gla vi ▁sa ▁sva ci me , ▁a ▁neka da ▁obu ku ▁i ▁hal ji ne .
▁C ime ▁se ▁ti ▁stvarno ▁ba viš ?
▁Pokuša vala ▁sam ▁da ▁iz be gne m ▁gas nu ▁kom or u , ▁a ▁ne ▁da ▁se ▁u šu nja m ▁u ▁neki ▁škol ski ▁ok rug .
▁Ako ▁ne ▁budem o ▁i mali ▁bor ca , ▁Ako ▁će ▁biti ▁os ra mo će n .
▁10 ▁hil ja da . ▁Želiš ▁li ▁da ▁na đe š ▁neko ga ▁drugog a ▁ko ▁će ▁do ći ▁ovde ▁da ▁kop a ? ▁Il aj ?
▁I di ▁i ▁traži ▁ih .
▁Ka kav ▁savršen ▁plan !
▁Bo jim ▁se , ▁mislim ▁na ▁sve .
▁Sa ▁svim e ▁što ▁tr pa š ▁u ▁sebe ?
▁Ovdje ?
▁Gospod ine ▁Vil son .
▁U ▁redu , ▁vidim ▁gde ▁ovo ▁ide .
▁Ako ▁se ▁ne ▁mogu ▁sa s vim ▁sj etiti ▁Nick a , ▁onda ▁cu ▁ga ▁radi je ▁sa s vim ▁zaboravi ti !
▁To ▁nema ▁nik ak ve ▁veze ▁sa ▁on im ▁što ▁se ▁dogodilo ▁Dže fu .
▁- I ▁ako ▁ga ▁posluša te ... ▁svi ▁ćemo ▁se ▁u vali ti ▁u ▁ne vol ju .
▁Uh ap še na ▁zbog ▁napad a ▁u ▁Ga m la ▁Stan u ▁1998 . ▁kada ▁smo ▁joj ▁uz eli ▁ot iske .
▁Zašto ?
▁- ▁Ona ▁me ▁pod se ca ▁na ...
▁To ▁je ▁za ▁ tje sko bu ... ▁de pres iju , ▁bol .
▁Ja ▁ njima ▁treba m .
▁Mora te ▁biti ▁jaki ▁i ▁hit ri .
▁A ▁onda ... ▁Na z vao ▁me ▁ta ta .
▁To ▁je ▁posebno .
▁- ▁The ▁Ca ve .
▁U ▁redu , ▁dosta ▁raz gla ban ja .
▁- ▁To ▁je ▁ono ▁sto ▁se ▁nada mo .
▁Stvarno ▁vam ▁ne ▁mogu ▁reći .
▁C isto s kopi ja ▁ne ▁pa li .
▁Ali ▁ako ▁mo zes , ▁treba ▁mi ▁tvoja ▁pomoc .
▁Kakv a ▁je ▁to ▁je bi ga ▁ne prav da ?
▁Moj ▁ bož ić ni ▁po klon ▁za ▁vas ...
▁" Po s lo da vac ." ▁Da ▁na piš em ▁bilo ▁šta ?
▁Da ▁li ▁si ▁ik ada ▁bio ▁sa ▁že nom ?
▁- ▁O stavi ▁me ▁na ▁mir u !
▁[ dr ve ta ▁š kri pa ]
▁Na vig acija ▁je ▁ot ka zala .
▁- U ▁iz v ješ ću ▁pi še ▁105 ▁km / h .
▁Nema te ▁izbor :
▁U običajen o , ima li ▁smi ▁mali ▁pr ble m ▁s ▁provi zi jom .
▁Jeste ▁li ▁u ▁moj oj ▁so bi ?
▁Bez ▁br ige , ▁još ▁malo .
▁Hoćeš ▁reći ... ▁O kri v ljiva nje ▁pred ▁Se na tom ?
▁Mo g lo ▁bi ▁posta ti ▁ru ž no .
▁Ti ... ▁Govori la ▁si ▁da ▁ne ▁bi ▁mogla ▁da ▁ga ▁pre boli š .
▁Ja ▁imam ▁jako ▁malo ▁u tica ja ▁na ▁sve ▁ovo . ▁Zašto ▁je ▁tako ?
▁Poč i njem ▁da ▁os eć am ▁bol .
▁Za d ovolj stvo ▁mi ▁je , ▁stvarno .
▁Sad ▁imam ▁samo , ▁misi ju .
▁- Ne , ▁ali ▁ćeš ▁mi ▁se ▁ti ▁možda ▁vratiti .
▁Znaš ▁da ▁nije ▁bilo ▁potrebe ▁da ▁spava š ▁sam nom .
▁Se stra ▁će ▁biti ▁vrlo ▁tu ž na .
▁Njegov ▁rezerv ni ▁polo za j , ▁jos ▁uvek ▁je ▁ne pozna t .
▁Za tim ▁se ▁mil ord ▁po ja vio ▁izvan ▁sebe ▁od ▁bij es a .
▁Poz vao ▁sam ▁ih ▁da ▁u đu .
▁- Ma ma ▁pravi ▁s ja jan ▁ro lat ▁od ▁mesa .
▁Ima o ▁je ▁puno ▁sreć e .
▁- Bo že !
▁Ne zna m , ▁oko ▁30 ▁ki lom etara ▁od ▁Gun nis ona .
▁Ne ▁" ka o ", ▁je su .
▁I ▁vi ▁bi ▁trebali , ▁ad mira le .
▁- ▁Oni ▁su ▁ovo ▁posla li ?
▁- I ▁vam a .
▁On ▁svet lu ca .
▁Pa ž nja !
▁Moj i ▁ciljevi ?
▁Gu bi ci ▁u ▁ ratu .
▁- ▁Za prav o ▁ne ▁znam . ▁Vidi te , ▁njen ▁ugovor ▁ist ice ▁sto ▁zna ci ▁sto ▁zna ci ▁da ▁ce ▁se ▁izgubi ti ▁svi ▁njen i ▁podaci ...
▁Pa ▁onda ▁pret post avljam ▁da ▁je ▁dobro ▁što ▁sam ▁na šla ▁ru pu .
▁E j , ▁je ba či .
▁Dobro . ▁Ide š ▁li ▁sada ▁doma ?
▁Vidi o ▁sam ▁da ▁u da raš ▁u ▁vrata .
▁Po tro ša čke ▁cijene ▁su ▁u ▁april u ▁u ▁odnosu ▁na ▁april ▁2010. ▁por as le ▁za ▁bli zu ▁11 % , ▁a ▁pre hra mbe ni ▁artikli ▁poput ▁h lje ba ▁i ▁ži ta rica ▁posebno ▁su ▁po go đen i .
▁Samo ▁sto jim ▁i ▁gleda m ▁u ▁sve mir ... ▁i ▁pi tam ▁se ▁da ▁li ▁će ▁se ▁vratiti .
▁Ovo ▁je ▁s ram ot no .
▁Ne , ▁ali ▁se ▁može ▁reći ▁da ▁smo ▁vrlo ▁sigur ni ▁u ▁to .
▁Jedno ▁de te ▁manje , ▁za ce to ▁od ▁mor ona .
▁Možda ▁ho će .
▁Ovo ▁je ▁o ti šlo ▁pred a leko .
▁Za h val an ▁sam ▁sto ▁ce mo ▁mo ci ▁ovo ▁gleda ti ▁za ▁25 ▁godina .
▁I sa ac ▁do vodi ▁ne ku ▁djevoj ku ?
▁Samo ▁sa če kaj , ▁na ▁trenutak .
▁Na šao ▁sam ▁vaše g ▁čovjek a .
▁Nije ▁le pa ▁kao ▁ti .
▁Da ▁mi ▁pomogne ▁da ▁pri kup im ▁zrak e ▁ žu to g ▁sun ca ▁dok ▁budem ▁le tio ▁ka ▁tamo .
▁Kad ▁jednom ▁u đe te ▁u ▁njegov u ▁obitelj , ▁on ▁vas ▁pos je du je .
▁Tako ▁si ▁visok , ▁tako ▁ve lik , ▁ali ▁imaš ▁malo ▁s r ce .
▁U ▁li ft u , ▁u ▁ho lu .
▁Mislim ▁da ▁je ▁tvoj ▁brat ▁po ma lo ▁ ljub om oran ▁na ▁tebe .
▁Z bil ja ▁do bru ▁do đu .
▁Misliš ▁da ▁je ▁Vo ken ▁bio ▁negativ ac ?
▁Baba ▁ima ▁problem ▁već ▁godina ma .
▁Ne do pusti ▁ovoj ▁va tri ▁da ▁se ▁za pali , ▁Gu ru !
▁Marie tta ?
▁- ▁Gil li an , ▁bilo ▁mi ▁je ▁drag o .
▁- ▁" T ed , ▁ne ▁mogu ▁da ▁mir no ▁sto jim ▁i ..."
▁Tako ▁možemo ▁is cr tati ▁izvor ▁boli ▁i ▁onda ▁je ▁pro živ lja vati , ▁znaš .
▁Pri ca li ▁ste ▁s ▁g . ▁La mping to nom ?
▁Mislim , ▁da ▁li ▁to ▁za ista ▁toliko ▁važno , ▁to ▁je ▁samo ▁seks .
▁Pro vali o ▁mi ▁je ▁u ▁ku ću .
▁Jedno m ▁sam ▁mu ▁to ▁spo menu o .
▁Ja ▁ne ▁znam .
▁Još ▁malo !
▁- ▁Što ▁su ▁re kli ?
▁D ž ung la .
▁Za ljub is ▁se ▁jer ▁misli s ▁da ▁ako ▁ga ▁upozna s ▁bi ce ▁drug aciji .
▁O že nice š ▁moju ▁k ci . ▁Ko ▁kaže ▁da ▁želim ▁da ▁se ▁že nim ?
▁Bilo ▁je ▁mnogo ▁svet a .
▁Kao ▁bil j ku . ▁Ili ▁c rte ž ▁plan ine .
▁Gdje ▁su ▁ti ▁k lju ce vi ?
▁Gde ▁je ▁Santa ▁Maria ▁del ▁Po polo , ▁prvi ▁ol tar ▁na uke ?
▁Ne ▁smije š ▁ni kom ▁priča ti ▁o ▁ovom .
▁Kako ▁si ?
▁Na red nice , ▁kas ni mo .
▁Ne ce ▁ti ▁pri pas ti ▁muka ▁u ▁moj im ▁kol ima ?
▁Kako ▁se ▁vi ▁zove te ?
▁Misliš ▁da ▁bih ▁dva put ▁po nov ila ▁ istu ▁po gre š ku ?
▁- ▁Još ▁ka fe , ▁profesor e ?
▁- ▁Idemo . ▁Ovo ▁mesto ▁je ▁je zi vo .
▁Možda ▁Mi cu bi ši .
▁Za kas ni ćeš ... ▁na ▁svoj ▁reci tal !
▁On ▁ga ▁ne ▁za služ uje !
▁Možda ▁bi ▁mama ▁trebala ▁da ▁po čne ▁da ▁pi še ▁de č je ▁knjig e .
▁Reci ▁mu ▁da ▁ću ▁mu ▁se ▁ja viti .
▁I ▁na red nik ▁Wall ace . ▁Ona ▁će ▁biti ▁tvoj ▁partner ▁za ▁obu ku .
▁Da ▁li ▁bi ste ▁i kad ▁mogli ▁od usta ti ▁od ▁El lie ?
▁Možda ▁bi ▁ti ▁mogao ▁pokuša ti ▁vodi ti ? ▁!
▁Em ire , ▁John ▁Anthony ▁ovdje .
▁- Ne ▁pozna jem ▁osta le .
▁Nama ▁plati ▁sit ni š , ▁a ▁se bi ▁po ud vo stru či ▁des et ▁mili ju na ?
▁- Ho će te ▁li ▁iza ći ▁sa ▁mnom ▁na ▁večer u ?
▁- ▁Ovo ▁su ▁ko la ▁sa ▁vaš ara ▁koja ▁sam ▁ku pio ▁preko ▁e Ba ya .
▁Š te de o ▁sam ▁za ▁prav ni ▁fa kul tet .
▁- O d ▁Li se ▁Don ovan .
▁C inte ▁se ▁kao ▁do bri .
▁U ▁ha os u ▁sam .
▁Ve c ▁sam ▁se ▁pre z noj ila .
▁Kako ▁misli s ?
▁Hoćeš ▁da ▁znaš ▁šta ▁to ▁znači ?
▁Tako ▁ona ▁kaže ▁" zdrav o ".
▁Ja , ▁kao , ▁kao ▁da ▁se ▁malo ▁tres em ▁sada .
▁Samo ...
▁U ▁među vre menu , ▁nemoj te ▁se ▁bri nuti .
▁A ▁ja ▁mogu ▁pop rica ti ▁sa ▁su cem .
▁- Ne ▁vjer ujem ▁u ▁to .
▁Sad ▁mi ▁treba ▁od mor .
▁Z vat ▁ću ▁polici ju .
▁Slušaj , ▁ne ▁znam ▁kako ▁su ▁se ▁stvari ▁obavlja le ▁prije ▁no ▁što ▁sam ▁stig ao , ▁a ▁ja ▁volim ▁misli ti ▁o ▁se bi ▁kao ▁o ▁bez bri ž noj ▁osob i .
▁Č uv ajte ▁Ber teli .
▁" Po sta lo ▁je ▁ne verovatn o ▁jasno ▁da ▁je ▁naš a ▁tehnologij a ▁nad vlad ala ▁na šu ▁ljudsk ost ."
▁Možete ▁li ▁na ▁trenutak ▁presta ti ▁biti ▁ru lja ?
▁- Po ki dali ▁su ▁mi ▁ta š nu ...
▁- Ni sam ▁homo fo b .
▁Tko ▁bi ▁po misli o ▁da ▁bi ▁običn a ▁cur a ▁poput ▁mene
▁- ▁Šta ? ▁Ne ▁vjer uješ ▁nam ?
▁Još ▁se ▁se ća m ▁tog ▁dana ▁kad ▁sam ▁ga ▁upozna o , ▁Na dia .
▁L ov ci ▁ne ▁da ju ▁tako ▁dobre ▁nap oj nice .
▁Mora o ▁sam ▁pomoći ▁prijatelj u ▁poslije ▁posla .
▁Za ba vno ▁mi ▁je . ▁Ovo ▁je ▁najbolj i ▁su dar ▁na ▁kom ▁sam ▁bio ▁pos le ▁dugo ▁vremena .
▁Hej , ▁prvo ▁šo t , ▁pitanja ▁pos le .
▁Radi ▁za ▁škol u ▁u ▁trgov inama ▁bli zu ▁one ▁auto ▁trgov ine .
▁Samo ▁vrlo ▁ tvrd .
▁Treba ▁da ▁pravi mo ▁ko la či će .
▁Um ro ▁je ▁u ▁font ani ▁od ▁pada .
▁Iz dr za vati ▁se ▁mogu ▁sama . ▁- V jer ujem .
▁Zašto ?
▁Ali ▁glavni ▁razlog ▁zbog ▁koje g ▁te ▁volim , ▁Marshall e ▁Eric ks en , ▁je ▁što ▁me ▁čini s ▁sreć nom .
▁Tek ▁sam ▁za gre ba o ▁površin u , ▁ali ▁bi ▁mi ▁bilo ▁mnogo ▁la k še ▁kad ▁bi ste ▁mi ▁dozvoli li ▁da ▁koristi m ...
▁I ▁malo ▁zelen e ▁ja bu ke .
▁- ▁Onda ▁ćeš ▁imati ▁temu ▁za ▁slik anje .
▁Idemo .
▁Nakon ▁što ▁se ▁s miri š .
▁Post oji ▁operacij a ▁za ▁to , ▁znaš ?
▁Iz vin ja vamo ▁se !
▁Su m nja j ▁na ▁svakog .
▁Una jm imo ▁paz itelj icu ▁za ▁njega . ▁Znaš ▁koliko ▁je ▁to ▁skup o ?
▁Ako ▁želi te ▁da ▁osta ne te ▁rob ovi ▁banka ra ▁i ▁da ▁pla ća te ▁ce h ▁rob o vanju , ▁osta vite ▁im ▁da ▁šta mpa ju ▁novac ▁i ▁da ▁kontroli šu ▁kredit e "
▁- Ne ▁zanima ▁me .
▁Idemo ▁da ▁se ▁pre sel imo ▁u ▁Itali ju !
▁Nije ▁važno , ▁T . ▁C .
▁Možda ▁ti ▁pri sluš ku ju ▁telefon , To ny .
▁- N je gov ▁prijatelj ▁u ▁pic u ▁je ▁misli o ▁da ▁je ▁to ▁cu d no .
▁Pogledaj te ▁je .
▁- ▁Jesi ▁me ▁čuo ?
▁Nema ▁der ne ka ▁do ▁man ding o ▁der ne ka .
▁- ▁A ▁hal u cin acije ?
▁Kako ▁se ▁zove š ?
▁I di ▁kasnije .
▁H t jela ▁je ▁da ▁njen ▁sin ▁vlada , ▁tvoj ▁po lub rat .
▁Gdje ▁si ▁bio ▁prije ▁dva ▁ tje d na ?
▁Kada ▁si ▁bio ▁s ▁Ali son , ▁ko ▁je ▁rekao ▁" V o lim ▁te " ▁prvi ?
▁Ali ▁o ▁pos lu ▁na ▁razgovara m ▁na ▁ja v nim ▁mje sti ma .
▁Le po ▁je ▁vide ti ▁te ▁opet , ce lia .
▁Ne će ▁im ▁se ▁svi d jeti .
▁Do k ▁je ▁u ▁redu , ▁v ješ ti ▁hiru rg ▁i ▁dobar ▁čovjek .
▁Onda ▁bolje ▁da ▁ne ▁vidi s .
▁U ▁redu . Ne ma ▁potrebe ▁da ▁se ▁der eš
▁Tra ži la ▁si ▁nešto ▁što ▁nikada ▁ne ▁možeš ▁na ći .
▁Idemo . ▁- ▁Ne ▁za služ uješ ▁to ▁dije te ▁koje ▁nos iš .
▁To ▁neće ▁mo ći .
▁Si sa o ▁bih ▁ti ▁krv . ▁- S isa š ▁moje ▁šta ?
▁Zašto ▁ste ▁to ▁misli li ?
▁- Mo ž da ▁pob eg nu ▁zajedno ▁i ▁ne ▁vra te ▁se .
▁K UP IO ▁S AM ▁O VO ▁M JE S TO ▁NA KON ▁Š TO ▁ SI ▁ UM RL A .
▁Do la ze ▁nam ▁od ▁me ha nica ra , ▁ben zin skih ▁c rp ki .
▁Treba m ▁se ▁ok re nuti ▁na ▁drug u ▁stran u ▁ili ... ?
▁Ne ▁sme ta ▁mi ▁da ▁kup im ▁2 -3 ▁knjig e ▁za ▁ovo .
▁Raz log ▁zbog ▁ko ga ▁sam ▁ pita o ▁je ▁jer ▁ste ▁tr lja li ▁nos ▁kao ...
▁- ▁Okej , ▁se ća m ▁se , ▁ja ...
▁Ali ▁da !
▁Maj k , ▁u đi .
▁Pogledaj ▁mi ▁uniform u ▁... ▁misliš ▁da ▁sam ▁jedan ▁iz ▁banda ▁Vil lage ▁People ?
▁Kit , ▁u đi !
▁Drago ▁mi ▁je ▁da ▁vidim ▁da ▁ima ▁novi h ▁kandidat a ▁za inter es iranih ▁za ▁ple meni ti ▁sport ▁- ▁r vanje .
▁- K ren ite .
▁Nikad ▁ga ▁neces ▁u hvat iti !
▁Samo ▁ima ▁nekoliko ▁riječ i ▁koje ▁ne ▁razum i jem .
▁- ▁Pos la tim ▁od ▁kralj a .
▁Ali ▁to ▁ga ▁ne ▁za u stavlja .
▁Da ▁sam ▁na ▁tv om ▁me stu , ▁dig ao ▁bih ▁ru ke ▁od ▁ovog a .
▁- Č e kaj ▁malo . ▁Zna o ▁si ▁da ▁imaš ▁virus ?
▁Ona ▁je ▁star ica ▁koje ▁je ▁bila ▁dobra ▁prema ▁meni .
▁Mr t vi ▁su .
▁Ne ▁znam ▁kako ▁se ▁zove .
▁- ▁Šta ?
▁Vidi o ▁sam ▁tvoj u ▁cur icu ▁par ▁puta ▁s ▁tim .
▁Zdravo , ▁Pe tsi .
▁Ako ▁razvi je mo ▁no vu ▁tehnologij u , ▁to ▁nam ▁da je ▁pred nost .
▁Ob ično ▁star i jih , ▁bo gati h .
▁Pr vo ▁di ši , ▁onda ▁puc aj .
▁Super ▁smo ▁se ▁prove li .
▁Šta ▁tebe ▁briga ▁šta ▁ja ▁želim ?
▁No ći ma ▁i ▁noć ima ▁sam ▁te ▁čeka o ▁da ▁do đe š ▁i ▁priča š ▁sa ▁mnom ▁sa ▁svojim ▁ću re ći m ▁glas om ...
▁- E pi fa ni ovi ▁ljudi ▁tra že ▁je ▁pos vu da .
▁- ▁Bas ▁ste ta . ▁U kra o ▁je ▁moj ▁pe cat ▁od ▁ci sto g ▁zlat a .
▁Prim jer ice , ▁moja ▁uniform a . .
▁Ovo ▁ne ▁možeš ▁da ▁ku piš ▁u ▁A meri ci .
▁Hajde , ▁sad , ▁nu di ▁li ▁ko ▁dva ▁cent a ? ▁- ▁Iza ▁tebe !
▁Nikad ▁ne ▁priča š ▁o ▁moj oj ▁u lo zi . ▁Kakv i ▁su ▁s nim ci ▁sa ▁pro be ?
▁Svi ▁treba ▁da ▁u radi te ▁ovo ▁kako ▁treba .
▁Do govori li ▁smo ▁se .
▁Nemoj ▁se ▁glup irati .
▁Ne ▁no si ▁ništa ▁ cr ven o !
▁I ▁na t jera lo ▁me ▁da ▁raz misli m ▁o ▁život u . ▁Ho ću ▁najbolje ▁za ▁sebe .
▁- ▁Je s mo ▁li ▁spremn i ?
▁Ti ▁nisi ▁u bio ▁tu ▁djevoj ku .
▁Za tim ▁ćemo ▁za tvor iti ▁vrata ▁i ▁u bac iti ▁zrak .
▁Ne ▁mogu ▁se ▁sj etiti ▁ne če g ▁bit nog ...
▁Da ▁nije ▁bio ▁na ▁operacion om ▁stol u ...
▁Ve ć ▁smo ▁sve ▁pre traži li .
▁Dobro , ▁idemo ▁u ▁nazad .
▁- Po z uri , Te mi !
▁Šta ▁je ▁ovde , ▁šta ▁si ▁to ▁pila ?
▁S me š ten ▁je ▁u ▁Japan u .
▁I ▁ne ▁možete ▁da ▁name sti te ▁da ▁me ▁uh ap se .
▁Ni ▁s ▁kim , ▁dušo .
▁- ▁Mogu ▁li ▁ti ▁dati ▁savjet ? ▁Naravno .
▁Što ▁nam ▁to ▁vaš a ▁vlada ▁ne ▁govori ?
▁pop ili ▁ste ▁4 0,000 ▁li tara ▁vode .
▁Živ jeli ▁u ▁i stoj ▁če tvrt i ▁u ▁Bag dad .
▁- ▁Radi m ▁na ▁tome .
▁Naravno ▁da ▁sam ▁sko cio ▁da ▁je ▁spasi m .
▁- To ▁je ▁najbolje ▁s ranje ▁koje ▁si ▁i kad ▁proba o .
▁- ▁Na če l nik !
▁I ▁za bora van .
▁Gle da mo ▁li ▁dokaz e ▁" ono stra nog ", ▁a ▁ima ▁ih ▁dosta ▁is ku stva ▁bli ske ▁smrti , ▁de ca ▁koja ▁su ▁rod jena ▁sa ▁se ca njem ▁te taka , ▁s trice va , ▁de da , ▁koji ▁su ▁da vno ▁umrl i ▁pre ▁njihovo g ▁rod jen ja ...
▁Gospod ine , ▁misli ▁pose g nuti ▁za ▁vaš im ▁pištolj em .
▁- Pri ko lica ▁je ▁za ▁stat u u .
▁- Ma kni te ▁se ▁s ▁njega !
▁Sve ▁za ▁po ne ti ...
▁- ▁Imamo ▁plan , ▁ali ▁će ▁nam ▁treba ti ▁love .
▁Bir ko fe !
▁Jer ▁mislim ▁da ▁bi ▁to ▁bilo ...
▁Nisi ▁čak ▁ni ▁pozna vao ▁kap etan a ▁Bre j s gir dla .
▁Du š o , ▁je li ▁sve ▁u ▁redu ?
▁Vi ▁? ▁est ▁u ▁lag de ▁u ? ▁et u , ▁ja ▁ , ▁ali ▁je ▁?
▁I gra ▁ne del je .
▁Kako ▁su ▁Ryan ▁i ▁Es posit o ?
▁V rlo ▁dobro , ▁Cass ie .
▁Pa zi te ▁na ▁Si mens a .
▁Sigur nost ▁u ▁dana š njem ▁svijet u ▁ne ▁može ▁se ▁post i ći ▁samo ▁za šti tom ▁gran ica ▁v last ite ▁države , ▁izjavi la ▁je ▁držav na ▁sekret ar ka ▁pri ▁mini star stvu ▁od bra ne ▁Tan ja ▁M išče vi ć .
▁pre tvor i ▁< f rom > ▁[ < norm \ - form > ]
▁Stan i .
▁Over ki ll ▁tako đe ▁može ▁da ▁po ka že ▁svoju ▁ne isku stvo .
▁Naravno . Ka s nije .
▁- ▁La ga o ▁si ▁mi !
▁Hoćeš ▁na ▁kole d ž ?
▁- P e ter , ▁želim ▁da ▁neko ga ▁upozna š .
▁Uvijek ▁se ▁pret po stavlja lo ▁da ▁ce ▁Stephen ▁ ici ▁na ▁O x ford .
▁Do šli ▁smo ... ▁jako ▁da leko .
▁Ali ▁jedna ▁slučaj nost , ▁nije ▁ znak ▁za ▁alarm .
▁Da ▁pogleda mo ▁ponovo ... ▁Evo ▁So krat a , ▁u bac uje ▁gla vom .
▁Svi ▁su ▁živi .
▁Ali ▁čeka ti ▁mora te ▁van i , ▁molim ▁vas .
▁Ne ki ▁od ▁tih ▁broj eva ▁se ▁po nav lja ju . ▁- ▁Molim ? ▁Ne .
▁Ja ▁sam ▁do slov no ▁Pre kli njem ▁te .
▁- ▁Sve ▁su ▁maj ke ▁do š le ▁sem ▁moje .
▁- ▁Jeste ▁li ▁je ▁zato ▁s tvor ili ?
▁Var ao ▁je !
▁" S r ce ▁koje ▁voli ▁ka ze ▁da ▁je ▁ce o ▁svet ▁lu d "
▁Na ▁žal ost , ▁u sled ▁ne mara ▁pri ▁od la gan ju ▁od vrat nog ▁toks ično g ▁nu s ▁proizvoda , ▁jedna ▁dobra ▁Tro ma vil ska ▁ve ver ica ▁mut ira la ▁je ▁u ▁og rom nu ▁od vrat nu ▁sm rd ljiv u , ▁up i šanu ▁čud o viš nu ▁ve ver icu .
▁Ne ▁je bi ▁u če nice . ▁Ne ▁je bi ▁u či telj ice .
▁Po šal ju ▁te ▁na ▁od vik avanje ▁a ▁ja ▁se ▁tamo ▁ne ▁vra ča m .
▁Po š to ▁sam ▁vidi o ▁ka kva ▁ti ▁je ▁pla ća , ▁ vjerojatn o ▁ne ▁bi ▁trebao .
▁- ▁Ja ▁sam ▁u ▁ cr ven om ▁ti mu !
▁Sa če kaj .
▁Ljub av nik ▁sa ▁os lab ljeni m ▁še raf om ?
▁Po tom ▁je ▁u isti nu ▁po vrat ište ▁njihovo ▁d že hi mu .
▁Nema te ▁resursa , ▁nema te ▁obra di le ▁zemlje , ▁nema te ▁ri be , ▁da kle ▁nema te ▁ništa .
▁To ▁ne ce ▁presta ti , ▁ne ▁bez ▁vremena ▁i ▁tre t mana .
▁Jason ▁G . ▁je ▁po be dio ▁na ▁Itali jan skom ▁id olu .
▁Ti ▁si ▁već ▁mrtav .
▁- Ne ▁svi đa ▁joj ▁se !
▁Zar ▁ne ▁znaš
▁Nisam ▁stig ao ▁ni ▁vozi ti .
▁Dobro , ▁samo ▁jedna ▁stvar .
▁Želim ▁ga ▁na trag .
▁- ▁Pro meni o ▁sam ▁postel jin u .
▁To ▁je ▁pa nda , ▁ser .
▁" Ka d ▁si ▁po če la ▁radi ti ▁ovdje ?"
▁" Ne ma ▁tu ▁ništa ▁loše ▁i ▁ne ▁da j ▁da ▁ka žu ▁da ▁si ▁druk či ji "?
▁Da ▁li ▁vas ▁je ▁u bed ila ▁da ▁se ▁use lite ▁ponovo ?
▁Sam ▁si ▁to ▁traži o .
▁I ▁Mi ▁mu ▁na ▁ploč ama ▁na pis as mo ▁po uku ▁za ▁sve , ▁i ▁ob jašnj en je ▁za ▁sva šta . ▁" Pri mi ▁ih ▁svoj ski , ▁a ▁narod u ▁svo me ▁zapo vije di ▁da ▁se ▁pri država ▁on oga ▁što ▁je ▁u ▁ njima ▁ lje p še !"
▁Vrati o ▁se ▁her oj ▁- ▁os va ja č .
▁Še rif e , ▁prim je će n ▁je .
▁Ili ▁po či nje ▁kao ▁počet nik ▁ili ▁kao ▁za me nik ▁še fa .
▁Bobby , ▁želiš ▁li ▁vidjeti ▁šta ▁sam ▁ti ▁do ni jela ?
▁Nema ▁potrebe ▁da ▁izi gra vas ▁socijaln og ▁rad nika .
▁Evo ▁moje ▁vizit ke ▁ako ▁se ▁s jeti te ▁ne če ga .
▁Ne ▁osjeća š ▁bol .
▁Par ▁iz ▁Vir gi nije ?
▁Maj ore , ▁šta ▁to ▁radi te ?
▁I ▁to ▁mi ▁je ▁neki ▁rod jak .
▁Zdravo , ▁ stvo ren je ▁sa ▁drugog ▁svet a .
▁Ve ć ▁je ▁video ▁mnogo ▁šta .
▁Li je po ▁je , ▁zar ▁ne ?
▁Už i vaj ▁u ▁u bila čko m ▁po ho du .
▁Znam ▁da ▁ti ▁sve ▁analiz i raš ▁svaki h ▁des et ▁minuta . ▁U zor ke , ▁odnose , ▁indeks e , ▁cele ▁ma pe ▁informacija .
▁H t jela ▁sam ▁da ▁pogleda š ▁moj ▁sta s .
▁Ali ▁treba ju ...
▁- ▁Ovo ▁je ▁nov ▁dan .
▁We n dy ▁ne ▁može ▁ništa ▁dokaz ati .
▁Oni ▁oče ku ju ▁tvoj ▁poziv . ▁Pa ▁iz voli .
▁- ▁Misliš ▁da ▁želim ▁um rije ti ?
▁Što ▁ako ▁opet ▁završi š ▁tamo ?
▁Da li ▁pozna ješ ▁tog ▁um et nika ?
▁Bez ▁tebe , ▁oni ▁ne ▁bi ▁mogli ▁sam i ▁da ▁re še ▁u bi stvo ▁tvoje ▁por o dice .
▁U gr izao ▁si ▁ga ?
▁Je li ▁su ▁isto ▁što ▁i ▁mi ▁i ▁niko ▁više ▁se ▁nije ▁raz boli o .
▁Ali ▁oni ▁su ▁ljudi .
▁Na lazi mo ▁ta jan st veni ▁Z lat ni ▁ ključ ▁koji ▁ot ključ ava ▁evolu ci jske ▁si le ▁pri ro de .
▁Ne ▁kažem o ▁da ▁Bog ▁bla go slov i ▁Amerik u , ▁već ▁pro klet a ▁da ▁je ▁Amerika ...
▁- ▁Una tra ške , ▁Al !
▁To ▁nije ▁a me rick i ▁narod .
▁Bu di ▁dobar ▁i ▁dones i ▁ma mi ▁sok .
▁Pusti ću ▁vas ▁da ▁na stavi te .
▁" Re pu blik a ▁Sr p ska ▁mora ▁u ▁ cje lini ▁pošt i vati ▁De j ton ski ▁mi rov ni ▁sporazum ▁i ▁ne ▁smije ▁o spor a vati ▁rad nje ▁poduzet e ▁na ▁osnov u ▁De j tona ▁i ▁rezo lu cija ▁Vijeća ▁sigurnosti ▁UN - a , " ▁kaže ▁se ▁u ▁In zko vom ▁sa op će nju ▁od ▁u tor ka .
▁Kad ▁budu ▁ba čeni ▁u ▁njega , ▁ću t ▁će ▁ga , ▁h rop ta će ▁i ▁on ▁će ▁v riti .
▁Kaž e ▁da ▁je ▁on ▁" ljub av ".
▁Zna s ▁sta ▁je ▁meni ▁te sko ▁za ▁povjer ovati ?
▁tre ning ▁Ph y llis ▁mora ▁imati ▁stvarno ▁iz ne mo gli ▁je .
▁- ▁Samo ▁pre ter uje s , ▁to ▁je ▁sve .
▁Do šla ▁sam ▁ovdje ▁sa ▁dvije ▁misli ▁u ▁gla vi .
▁Sad ▁kad ▁to ▁formul iš eš ▁tako ...
▁I ▁niko ▁ti ▁ništa ▁ne ▁može .
▁- ▁Kuva ni ▁maka ron i !
▁Od ▁ovog ▁tre nut ka , ▁program ▁G UP ▁je ▁suspend ovan ... ▁do ▁za vrš et ka ▁is trag e .
▁Pa , ▁ljudi ▁imamo ▁veoma ▁te š ku ▁ma čku ▁za ▁z bu nji vanje ▁dana s . ▁Pa , ▁idemo ▁odmah ▁na ▁posao . ▁Dobro .
▁Sad ▁p je vam ▁i ▁pov r će .
▁Za ▁100 ▁godina , ▁još ▁će ▁ga ▁radi ti .
▁Ona ▁pret vara ▁ci jeli ▁izlaz nu ▁snagu ▁na ą em ▁prostor u ▁stanic e ▁u ▁jednom ▁kad ru .
▁Zna o ▁sam ▁da ▁ćeš ▁shvati ti .
▁Prote gni ▁no ge .
▁- ▁Znam ▁to . ▁Ali ▁prije t nja ▁je ▁up u će na ▁federal noj ▁z grad i ▁preko ▁puta .
▁Jesi ▁li ▁čuo ▁o ▁on om ▁golf er u ?
▁Bare m ▁znam o ▁šta ▁se ▁des ilo ▁s ▁Henry jem .
▁Ana ▁čeka ▁u ▁Opera cija ma .
▁Zašto ▁to ▁radiš ?
▁Sko ro ▁mi ▁je ▁ot kin u o ▁gla vu ; ▁mora ▁da ▁je ▁bio ▁baš ▁nez go dan ▁rask id .
▁Nema ▁mnogo ▁vo za ča ▁En gle za ▁u ▁Pra gu .
▁On ▁je ▁bio ▁u ▁ voj s ci .
▁Što ▁je ▁to ▁bilo , ▁Roy , ▁tvoja ▁za d nja ▁bit ka ?
▁Do k ▁pi ješ , ▁taj ▁kami on ▁le vo - -
▁I ▁po ▁prvi ▁put . . ▁Pos le ▁dugo g ▁vremena . .
▁Sada ▁možemo ▁da ▁završi mo ▁naše ▁pro ton ▁anti - pro ton ▁istraživa nje .
▁Hvala ▁vam .
▁Pre viš e ▁je ▁važno .
▁Drž a vne ▁polici je ▁i ▁High way ▁Pat rol ▁su ▁na ▁op re zu ▁kao ▁dobro .
▁U ▁sva kom ▁slučaju , ▁u spor ed ili ▁smo ▁te ▁podatke ▁sa ▁tre nut nim ▁lokacij ama , ▁adres ama ▁i ▁nama ▁dostupni m ▁informacija ma .
▁Ali ▁on ▁je ...
▁Ko ▁ti ▁je ▁na dle zni ?
▁Ima ▁sa obra ća ja , ▁ali ▁je ▁za nim ljivo . To ▁je ▁glavni ▁grad .
▁Daj ▁tu ▁map u .
▁Ima ▁gri pu .
▁Ti ▁si ▁tu ▁gde ▁i ▁je si , ▁ali ▁ja ▁sam ▁ponovo ▁na ▁vr hu .
▁I ▁vidi ▁kako ▁ti ▁is pa o ▁To ▁nije ▁ni sta , st var no
▁- ▁Vidiš , ▁rekao ▁sam ▁ti .
▁Znam ▁da ▁me ▁mr zi š , ▁i ▁znam ▁da ▁te ▁ne ▁kriv im ▁zbog ▁toga .
▁Internet , ▁maj s tore .
▁Des et ▁si ▁joj ▁već ▁s man ji la .
▁Sve ▁dok ▁mis le ▁da ▁te ▁Steve ▁Re m ington ▁pos je du je , ▁siguran ▁si .
▁Samo ▁bes m rt ni .
▁Jedno m ▁da vno , ▁bile ▁su ▁tri ▁mlad e ▁že ne , ▁koje ▁su ▁bile ▁u ▁veliki m ▁problem ima .
▁Živ i ▁na ▁Mal lor ci ▁i ▁radi ▁za ▁š pan jo l sku ▁terorist i čku ▁grup u ▁Ver dad ▁Su prem a .
▁Rekao ▁sam ▁joj ▁da ▁može ▁biti ▁smrt ono s no .
▁O no ▁na ▁pozor nici ▁je ▁moj ▁kli jent . ▁Poz vao ▁me ▁je ▁da ▁do đem . .
▁U ▁ce mu ▁je ▁problem , ▁imamo ▁15 ▁minuta .
▁A ▁ja ▁posta nem ▁smrt an .
▁Ta ▁je ▁pob je da ▁bila ▁mu nje vita ▁i ▁pot pun a .
▁I ▁posto ▁je ▁po ▁Sch ne ide ru , ▁rezultat ▁je ▁ud vo stru cen .
▁Vis e ▁od ▁ra se , ▁to ▁je ▁sir oko ▁otvoren ▁su ko b ▁ide ja ▁materijal iz ovan e ▁če lika .
▁Pa zi ▁se , ▁Ben .
▁Zar ▁te ▁ovdje ▁nisu ▁ni sta ▁nau cili ?
▁Mi ▁ovdje ▁spre ma mo ▁vaše ▁sam rt ni čke ▁ govor e , ▁de čki .
▁- Ko liko ▁sam ▁posledn ji ▁put ▁uradio ?
▁I ▁ govor e : ▁" Z ar ▁ćemo ▁kad ▁budem o ▁kost i ▁i ▁koma di ći , ▁- ▁ho ćemo ▁li ▁u isti nu ▁mi ▁biti ▁po dig nuti ▁( ka o ) ▁ stvo ren je ▁novo ?"
▁- ▁Sa ro , ▁kas nis ▁jedan ▁sat . ▁- ▁Rekla ▁sam ▁da ▁mi ▁je ▁za o .
▁Ah .
▁Kra du ▁ti ▁cara pe .
▁Želim ▁da ▁znam ▁kako ▁će ▁zvuč ati .
▁Sj ajn o .
▁Gdje ▁je ▁on ?
▁- ▁Hajde . ▁Ima ▁li je pe ▁si s ice ?
▁Je beni ▁Joe !
▁Spa si o ▁si ▁me ▁od ▁vil e njaka .
▁Kad ▁do đe te ▁među ▁kamp ▁pri koli ce :
▁- O vo ▁je ▁los e .
▁Izgleda ▁li ▁to ▁tebi ▁kao ▁samo obra na ?
▁Ta da ▁se ▁sve ▁pro meni lo .
▁Ova ▁žena ▁je ▁u ▁više ▁nav rata ▁iz b je gla ... ▁moj i ▁agent i ▁su ▁u ▁pot razi ▁za ▁formul om .
▁- cov jek ▁koji ▁je ▁došao ▁u ▁vezi ▁po ko pa ▁svog ▁o ca .
▁Još ▁de vet ▁sa ti ▁i ▁dolazi , ▁je l ?
▁Tru d na ▁sam , ▁a ▁tebe ▁baš ▁briga !
▁Mo ć ▁da ▁pre pozna m ▁man u , ▁slab ost ,
▁No sim ▁k nji ži cu .
▁I ... ▁nauči ▁nešto ▁odavde .
▁Lu ke , ▁s miri ▁se , ▁znam ▁kako ▁ti ▁je ▁mislim ▁da ▁se ▁možemo ▁dogovor iti .
▁Vi na ▁za ▁le di ▁Sa nsu !
▁A ▁u isti nu , ▁m nog i ▁od ▁ljudi ▁su ▁gr ješ nici .
▁Jesi ▁li ▁ku pio ▁tu ▁gara žu ▁već ?
▁Naravno , ▁oni ▁su ▁sla li ▁son de ▁na ▁sva ku ▁planet u , ▁sem ▁P lu tona .
▁Rekao ▁sam ▁bez ▁sme t nje .
▁Kako ▁je ▁bio ▁ sposob an ▁da ▁se ▁pro bije ▁kroz ▁op sa du , ▁gospodar ▁gran ice ▁bi ▁trebao ▁da ▁razgovara ▁sa ▁njim .
▁Po min ju ▁naše ▁ cip ele . ▁- ▁Šta ▁je ▁s ▁naš im ▁ci pe lama ?
▁Pro klet stvo , ▁zna o ▁sam ▁da ▁možeš !
▁Možete ▁li ▁da ▁mi ▁proč itate ▁ove ▁pod vu čen e ▁nas love ... ▁u ▁od el j ku ▁za ▁Me tro ?
▁Va ? ▁a ▁maj ka ▁vol jela ▁taj ▁po gled .
▁Vrati t ▁će te ▁motor ▁tamo ▁gdje ▁ste ▁ga ▁na šli , ▁i ▁osob no ▁ćeš ▁se ▁is pri ča ti ▁čovjek u ▁od ▁koje g ▁ste ▁u kra li .
▁Ne ▁znam , ▁da ▁je de mo , ▁u ▁bio s kop ...
▁Ob jašnj en je : ▁Za ▁tri jum f ▁Uh uru a , ▁koji ▁su ▁izbor ili ▁crn ci , ▁a ▁o spor avaju ▁bij el ci , ▁u bili ▁su ▁27 ▁bi jela ca ▁i ▁ 5000 ▁crn aca .
▁Slušaj ▁me .
▁D ve ▁hil ja de ▁dolara ▁ne ▁mogu ▁da ▁zaboravi m ▁tako ▁la ko .
▁Sad ▁sam ▁ose tio ▁kako ▁nešto ▁ gori .
▁- Da kle , ▁re šenje ▁je ▁da ▁me ▁una pred ite ▁i ▁is pla ć ujete ▁me ▁više ▁da ▁bih ▁svoje ▁zna nje ▁pruža o ▁budu ć oj ▁gener aciji ▁nau čni ka ?
▁Nova c ▁nije ▁bi tan .
▁Do ▁da ske ▁sam ▁u ▁man ji ni .
▁On ▁uvek ▁izgleda ▁kao ▁da ▁ništa ▁nije ▁uradio .
▁- B ila ▁si ▁mu ▁naj bliž a .
▁" ako ▁napravi m , ▁do ći ▁će " ▁trenutak .
▁Pro šlo ▁je ▁skoro ▁15 ▁godina ▁od ▁11. 09 .
▁Ra šči sti la ▁si ▁svoj ▁rasp o red ▁da ▁bi ▁se ▁ponovo ▁videl a ▁sa ▁tim ▁čud es nim ▁mom kom ▁koji ▁je ▁u bio ▁O sam u ▁Bin ▁La den a , ▁a ▁ti ▁si ▁ga ▁o stavi la ▁us red ▁New ▁York a ?
▁" V id jet ▁će ▁uvijek ▁biti ▁moj ▁z vije z da ." ▁O ▁moj ▁bo ze ... ▁( O BA ▁sme h )
▁Što ▁je ▁s ▁kapsul om ?
▁Gde ▁bi ▁mogli ▁da ▁idemo ?
▁- ▁Ve ć ▁znam ▁šta ▁ću ▁na ruč iti . ▁- ▁Hej , ▁do daj te ▁me nije .
▁U dalje nost ▁60 .
▁Ven ca li ▁su ▁se ▁19 55 .
▁Pa , ▁kako ▁ćemo ▁otvori ti ▁to ▁bez ▁ši fre ?
▁Dobro tvor na ▁vec era ...
▁Ti ▁si ▁naj z god ni ji ▁lik ▁u ▁svo m ▁ti mu .
▁Na ▁vr h ovima ▁moj ih ▁kan d že .
▁Ne . ▁Zna te . ▁Mislim ▁da ▁jednostavno ▁ne ▁voli te ▁njihov u ▁vr stu .
▁Ne ▁idi ▁na ▁ul icu , ▁Mar lo ne ▁Kru z !
▁- Ma ▁jako ▁je ▁dobra
▁Ona ▁ide ▁s ▁njim .
▁- I ▁ho ćeš ▁da ▁priča m ▁s ▁ njima ▁s ▁ovim ?
▁Svi ▁vi ▁ne ▁možete ▁prihvat iti ▁činjenic u ▁da ▁smo ▁možda ▁sje ban i .
▁Treba o ▁bi ▁se ▁dobro ▁osjeća ti .
▁Us prav an ! ▁Pa ž nja !
▁Kako ▁to ?
▁Bli ži ▁si ▁nego ▁što ▁misliš .
▁Sada ▁idemo ▁kući !
▁V re me ▁je ▁da ▁nauči š ▁da ▁či tas .
▁- ▁Misliš ▁li ▁da ▁ima ▁rak ?
▁- ▁W im , ▁de voj ka ▁je ▁opet ▁ovde .
▁- ▁Ž rt va ▁je ▁pozna vala ▁u bi cu .
▁- Ha jde , ▁Jake !
▁Tri ▁godine ▁sam ▁bila ▁savjet nica ▁tv om ▁o cu .
▁Nisi ▁mogao ▁sta jati ▁da ▁niko me ▁reci ▁ono ▁sto ▁nije ▁mogao ▁učiniti .
▁- Š ta ▁si ▁ti , ▁ci gan ska ▁kur ti zana ?
▁Zar ▁ne ▁vidiš ▁ništa ?
▁Ne , ▁nada o ▁sam ...
▁Plan ira o ▁sam ▁to .
▁Ta mo ▁je ▁jedan ▁veterinar ▁sa ▁koji m ▁se ▁viđ am ...
▁B org ▁kontroli ra ▁više ▁od ▁polo vice ▁brod a .
▁Šta ▁je ▁sli je de ce , ▁nema ▁TV ▁dok ▁ne ▁završi mo ▁za da ce ?
▁Tak va ▁dra ma ?
▁Možda ▁te ▁to ▁vozi lo ▁hit ne ▁pomoći ▁nije ▁od voz ilo ▁u ▁bolnic u .
▁- S am ▁od ▁sebe .
▁- ▁Iz abel , ▁ne ▁sme š ▁da ▁dozvoli š ... ▁tom ▁tip u ▁da ▁un i šti ▁tvoj ▁život .
▁Ja ▁sam ▁ne vin , ▁previše .
▁O ve ▁stvari ▁treba mo ▁za ▁škol u .
▁Ona ▁je ▁je dina ▁žena ▁koju ▁si ▁upozna o ▁a ▁koja ▁ne ▁mari ▁za ▁tvoj u ▁pro šlo st .
▁Mislim ▁da ▁je ▁sve ▁ovo ▁moja ▁gre ska .
▁Bo ja ▁font a ▁= ▁" # ▁ ff ff 00 " ▁Nikad ▁nisam ▁vjer ova o ▁u ▁bana lo sti ▁koji ▁pred vi đa ju ▁svoju ▁sud bin u ▁sa ▁određenim ▁osoba ▁.. ▁Bo ja ▁font a ▁= ▁" # ▁ ff ff 00 " ▁Ali ▁moje ▁vi zi je ▁su ▁tako ▁jasno ▁i ▁tako ▁pravi ▁osjeća je .
▁- ▁Še fer o vog ▁sve do čen ja .
▁Gu rni ▁gla vu ▁u ▁ru pu ▁i ▁reci ▁J . ▁He a ther ton .
▁To ▁je ▁li jek ▁protiv ▁bolo va .
▁D va ▁du pla , ▁dodatni ▁so s ... ▁sala ta , ▁sir , ▁kra stav či ći , ▁luk ... ▁na ▁zem i čki ▁sa ▁su sam om .
▁Ne ▁previše ▁bli zu , ▁Al er gi can ▁sam ▁na ▁v unu .
▁Poč ni te ▁sa ▁mal im ▁stvari ma , ▁stvari ma ▁sa ▁polic a , ▁la dica , ▁gri cka lica ma , ▁su venir ima .
▁Da , ▁ima ▁veze ▁sa ▁jutro š nji m ▁terorist ič kim ▁pret nja ma .
▁Jeste ▁li ▁u ▁s rod stvu ▁sa ▁gospod i nom ▁O x ly em ?
▁Do bar ▁vojn ik , ▁taj ▁Co dy .
▁Ima ▁preko ▁10 0.000 .
▁Možda ▁je ste ▁malo ▁i ▁ cr ven o , ▁ali ▁ ova ▁uz ica ▁nije ▁ništa ▁bolj a ▁od ▁Bur ke ▁( a rap ski ▁po krov ▁za ▁lice ▁i ▁tijelo ) !
▁Jaz z ▁mo mak .
▁On ▁misli ▁da ▁je ▁osta nak ▁njegov a ▁ide ja .
▁To ▁je ▁bilo ▁nev jer ovat no !
▁A ▁kad ▁ti ▁je ▁sve jedno , ▁ta ▁je ▁pravo du š nost ▁priv la čna .
▁Misliš ▁da ▁smo ▁u kra li ▁Re je vu ▁ku ti ju ?
▁- ▁Ko ▁si ▁ti ▁u op šte ?
▁O du vek ▁sam ▁zna la ▁da ▁će ▁tvoj ▁ rit ual ▁us peti ▁i ▁om og ući ti ▁mi ▁da ▁razgovara m ▁sa ▁Klar kom .
▁James , ▁još ▁uvijek ▁ima ▁vremena ▁da ▁dobi ješ ▁sve ▁što ▁si ▁želi o .
▁Mo m ci ▁u ▁stanic i ... ▁Su ▁me ▁jednostavno ▁iz je d na či li ▁sa ▁njim ... ▁Jer ▁sam ▁ja ▁bio ▁ge j , ▁da ?
▁Z vala ▁sam ▁medicin skog ▁ispitn ika , ▁mrtv o zor nika .
▁Svi ▁ćemo ▁um rije ti ▁ovdje .
▁Oni ▁su ▁student i ▁sa ▁univerz itet a ▁Tu son .
▁- Ka d ▁ste ▁je ▁pred ali ?
▁- ▁Pro lep ša će ▁se . ▁Kada ▁do đe ▁pli ma , ▁bi će ▁od lično .
▁U či nio ▁vas ▁je ▁nes re ć nom .
▁Hvala .
▁To ▁nije ▁iz govor .
▁Sada ▁idi ▁odgovor iti ▁na ▁njihov a ▁pitanja .
▁To ▁je ▁društv eni ▁program ▁noć nog ▁stra ž aren ja .
▁- Hva la .
▁Po nek ad ▁mi ▁je ▁priča o ▁o ▁pro šlo sti ▁i ▁o ▁maj ci .
▁Hvala .
▁Ja ▁se ▁ni ▁o cu ▁nisam ▁iz vin java o ▁kada ▁po gre ši m .
▁Du š o , ▁zor a ▁je ▁još ▁da leko .
▁Vi ▁joj ▁u op će ▁ne ▁da je te ▁pri liku ▁da ▁je ▁upozna te .
▁Zato ▁što ▁sam ▁Ko di , ▁on aj ▁koji ▁ti ▁je ▁posla o ▁c ve će .
▁Znaš , ▁nikada ▁nisam ▁misli la ▁da ▁ću ▁ovo ▁reći ... ▁ buk val no ▁nikada , ▁ali ▁mislim ▁da ▁si ▁bio ▁ap solu t no ▁u ▁pravu ▁u ▁vezi ▁nas .
▁Ne ▁juri m ▁kući ▁da ▁š kra ba m ▁po ▁svo m ▁dne v niku ▁kako ▁si ▁ti ▁možda ▁vampir .
▁Gu bi te ▁ose ća j ▁o ▁tome ▁vi ▁iz ▁USA ... ▁samo u vere nost .
▁G . ▁Kol in ova ▁seks ual na ▁ ori jent acija ▁nema ▁ništa ▁sa ▁ovim ▁slučaj em .
▁Od si je ci te ▁te ▁republi čke ▁brod ove ▁sa ▁zal ih ama .
▁... ▁To ▁je ▁jos ▁jedan ▁brut al ni ▁po ne djel jak ▁tamo ▁sa obra ca ja - mu dar .
▁Ovaj ▁datum ▁mi ▁je ▁posebno ▁za nim ljiv .
▁- ▁Da , ▁ali ... ▁Pri v la či š ▁pa ž nju . ▁Pri v la či š ▁pa ž nju .
▁Ne ▁mogu ▁da ▁na pusti m ▁svoju ▁proda v nicu .
▁- ▁Što ▁ste ▁vid jeli ▁kada ▁su ▁iz vad ili ▁pištolj ?
▁Idem ▁kući .
▁H tio ▁je ▁da ▁je ▁vidi .
▁- ▁Oh no hy a ▁je ▁OK , ▁zato ▁jer ▁Ta eko ▁nije ▁nikad ▁tamo ▁bila .
▁Za d nji ▁i ▁najbolj i .
▁Da ▁li ▁ste ▁upravo ▁re kli ▁" hi pi ji " ▁i ▁" meri d že jn "?
▁Ne ▁želim ▁to ▁č uti ▁od ▁tebe ,
▁On ▁će ▁nas ▁primi ti ▁preko ▁no ći , ▁a ▁do ▁Balti mor a ▁ćemo ▁sti ći ▁su tra .
▁Č EK AM ▁ TE ▁NA ▁PO B JE D NI Č KOM ▁P OST OL JU !
▁Kun em ▁ti ▁se ▁samo ▁nam ▁se ▁vrati .
▁Bilo ▁je ▁već ▁vreme ▁da ▁se ▁skr asi ... ▁Pos le ▁svih ▁žena ▁kroz ▁koje ▁je ▁prolaz io .
▁Ti ▁i ▁ja ▁na ruč imo ▁taj lan sku ▁hra nu , ▁po je de mo ▁je ▁u ▁krevet u ▁i ▁za sp imo .
▁Pa ▁od ak le ▁ti ▁ovaj ▁Bar ?
▁Pri čaj ▁mi ▁o ▁ njo j .
▁Ri jet ko ▁sam ▁ga ▁viđ ao , ▁pa ▁je ▁teško ▁vidjeti ▁raz liku .
▁K no x ville ▁and ▁Tre ma ine ▁su ▁re kli ▁da ▁im ▁se ▁ide ja ▁svi dja ▁je di no ▁ako ▁neko ▁ga dja ▁stre lica ma ▁iz ▁svoje ▁gu zi ce ▁kroz ▁du val j ku .
▁U ▁ pita nju ▁je ▁neka kva ▁igra , ▁ali ▁r ješ avam ▁to .
▁- ▁Bi će ▁sve ▁u ▁redu .
▁I ▁pov la či m ▁se ▁od ▁vas ▁i ▁on og ▁šta ▁za zi vate ▁mi mo ▁Allaha , ▁a ▁pri zi vat ▁ću ▁Gospod ara ▁svog .
▁- N išta ▁on ▁neće ▁sazna ti .
▁Un u tra ▁je ▁oko ▁20 - tak ▁ljudi .
▁Gdje ▁prav e ▁sat ove .
▁Mislim , ▁neki ▁u ▁koje m ▁joj ▁se ▁ništa ▁ne ▁može ▁des iti .
▁Ovdje ▁sam ▁jer ▁treba m ▁tvoj u ▁pomoć .
▁Vi še ▁ga ▁nema m .
▁Je dan ▁los ▁in tron ▁mo ze ▁sve ▁da ▁za br lja .
▁Mo gla ▁si ▁da ▁po šal ješ ▁tele gram ▁da ▁ćeš ▁do ći .
▁Gle da o ▁sam ▁u ▁njega ▁a ▁video ▁sam ▁tebe .
▁Nemoj ▁ni ▁po misli ti ▁da ▁im ▁za ku ca š ▁na ▁vrata , ▁Mi c . ▁Ne će ▁razgovara ti ▁s ▁tobom .
▁- ▁Možda ▁se ▁samo ▁po ig r avaju ▁s ▁nama .
▁Znam .
▁O ženi o ▁sam ▁Ro su , ▁mis le ći ▁da ▁ćeš ▁se ▁ti ▁za mon aš iti .
▁E ▁pa , ▁malo ▁si ▁za kas nio .
▁Ne ▁znam .
▁ IMA ▁NE Š TO ▁J AKO ▁ VA Ž NO , Š TO ▁ SU ▁ME ▁N AU Č ILI ▁MO JI ▁PRE CI , ▁U Č IT EL JU :
▁Šta ▁je ▁bilo ▁kap etan e ▁?
▁Zo ve ▁se ▁Mad ison ▁Sin cla ir .
▁Molim ▁po že lite ▁dobro do šli cu ▁Santa na ▁Meg kan s ▁iz ▁od jela ▁za ▁zaštitu ▁dje ce .
▁Ne ?
▁Rod it ▁ću ▁ti ▁dije te .
▁U ▁stvari , ▁on ▁je ▁bio ▁na ▁tvoj oj ▁strani ▁u ▁on om ▁malo m ▁problem u .
▁- ▁By e , ▁oli via .
▁Kad ▁god ▁se ▁vrati m .
▁Gledaj , ▁čovječe . ▁Do šao ▁sam ▁da ▁ti ▁kažem ▁lice m ▁u ▁lice , ▁čovječe .
▁To ▁nije ▁za ▁mene ?
▁- ▁Bu nde va ▁i ▁čo kol ada .
▁U ▁ku pati lu ▁iz nad ▁radi ja tora ▁se ▁na lazi ▁pro zor .
▁Samo ▁ću ▁pret po staviti ▁da ▁si ▁ga ▁posla o ▁jednom ▁od ▁star ih ▁Ben et tov ih ▁di ler a . ▁Ali ▁ne ▁moram ▁ga ▁tamo ▁traži ti , ▁zar ▁ne ?
▁Na ▁koji ▁je ▁način ▁samo ▁o stavljen .
▁Os lobo di ćemo ▁se .
▁Ca bot ▁me ▁sam ▁z vao ▁zbog ▁toga , ▁dan ▁prije ▁nego ▁je ▁um ro .
▁George , ▁ka mo ▁ces ?
▁Transport er ▁so bu .
▁Idem ▁pro na ći ▁Helen .
▁sta ▁s ▁ga d nim ▁raz vo dom ▁i ▁gor kom ▁zatvoren om ▁bit kom ▁i ▁sve ▁to .
▁To ▁nisu ▁ot pus ni ▁papir i .
▁Ne , ▁moj ▁de čko ▁me ▁je ▁ot ka čio ▁na ▁F lo - Ri di nom ▁kon cer tu .
▁I ako ▁je ▁moja ▁ljubav ▁sul uda , ▁razum ▁s mir uje ▁bol ▁u ▁mom ▁s r cu .
▁Samo ▁mi ▁reci ▁šta ▁se ▁događa .
▁Žao ▁mi ▁je ▁ , ▁samo ▁sam ... ▁uh ...
▁Nisam ▁že lje la ▁biti ▁sljedeć a ▁na ▁popis u ▁svog ▁muž a .
▁O vu da ▁prolaz e ▁ti su će ▁turi sta ▁i ▁ljudi ▁u ▁kup nji . ▁- Za š to ▁nije ▁bilo ▁svjedo ka ? ▁Da .
▁U ▁kra co j ▁ver zi ji ▁sve ▁je ▁is tina .
▁Do la ze ▁iz ▁Par iza ▁dana s ▁poslije pod ne .
▁Pot pun o ▁novi ▁ple s . . ▁... ▁koji ▁sigurno ▁znaš .
▁- Mo raš , ▁Josh .
▁Ali ▁vjer ujem ▁da ▁si ▁pošt ena ▁bu dala .
▁Tako ▁je , ▁protiv o trov .
▁Pre ▁možete ▁ba ci ti ▁one ▁druge ▁u bi stva ▁na ▁mene ?
▁- S vi ▁se ▁seks aju .
▁Želiš ▁da ▁mi ▁rast uri š ▁por odi cu ▁samo ▁zato ▁što ▁su ▁tvoj i ▁mrtv i .
▁- ▁Ne ▁znam ▁za ▁ovo ▁drugo , ▁možda ▁je ▁rekao ▁ono ▁prvo . ▁- ▁S lom ila ▁sam ▁ga ▁na ▁name šta ju .
▁Ski ni ▁ga ▁s ▁mene !
▁Put ▁je ▁ja san
▁- Z bo g ▁tebe ▁sam ▁postal a ▁policaj ka .
▁Ima ▁živ e ▁u ▁vodi ."
▁Šta ▁sam ▁ti ▁rekla ▁o ▁sk la nja ju ▁te ▁od je ce ?
▁- Mo ra mo ▁ih ▁poz vati .
▁Ni ti ▁ išta ▁o ▁Bog u ▁prev rata . ▁- ▁Mislim ▁da ▁ ova ko ▁radi .
▁Znam ! ▁Ti ▁si ▁moj ▁za me nik .
▁G . ▁Clark e ?
▁Na ša ▁su ▁te la ▁fa s ci nant na , ▁ali ▁i ▁glup a .
▁Ni ste ▁odavde ?
▁Pre gled ▁pra će nja ▁vremena
▁Misli s ▁da ▁si ▁sa vlad ao ▁v jes tinu , ▁zar ▁ne ?
▁Znam .
▁Zna jući ▁da ▁bi ▁mogli ▁biti ▁optuž eni ▁za ▁u boj stvo , ▁moj i ▁su ▁se ▁kli jenti ▁u span ič ar ili ▁i ▁si ješ ili ▁se ▁tijela .
▁Ili ▁postoje ▁ili ▁ne ▁postoje .
▁Ku ša t ▁ću ▁je ▁i ▁ja .
▁Ako ▁si ▁bu dan , tre ba o ▁bi ▁da ▁proba š ▁da ▁ho da š .
▁I ▁nije ▁on ▁ govor ▁p jes nika ; ▁malo ▁što ▁vjer ujete !
▁Er nes tine !
▁Kako ▁se ▁po nas aju ▁prema ▁Va ma ▁u ▁za tvor u ?
▁U isti nu !
▁Či ni ▁se ▁da ▁je ▁sve ▁čist o ▁pa ▁kre će m ▁tamo ▁da ▁od bac im ▁ovu ▁be bi cu ▁kod ▁mog ▁have ra ▁u ▁ba zi .
▁Up rk os ▁njegovo j ▁nes re ći , ▁nauči o ▁je ▁da ▁se ▁šo ra ... ▁i ▁dobro ▁bor i .
▁Tim ... ▁tipo m .
▁Da ▁li ▁ti ▁je ▁već ▁da o ▁svoj ▁broj ?
▁Pi j .
▁Tako ▁si ▁napad an .
▁Pre t hodno ▁u ▁Co vert ▁A ffa ir s ... ▁Moramo ▁je ▁du b lje ▁u bac iti .
▁U pozor en ▁sam ? ▁A ▁ tko ▁si ▁ti ? ▁Moj ▁u či telj ▁iz ▁prvo g ▁raz re da ?
▁Poč eli ▁su ▁da ▁me ▁pri tiska ju .
▁Bravo ▁plu to ne .
▁- ▁Ho ću ▁da ▁uz mem ▁ovog .
▁Ne ▁bor im ▁se ▁za ▁ljude ▁koje ▁ne ▁znam .
▁To ▁je ▁se man tika .
▁Ti ▁ćeš ▁mi ▁samo ▁dati ▁ši bi cu .
▁Ja ▁mogu ▁imati ▁na ja vu ▁za ▁ste ▁da ▁ce te ▁k no ck ▁Pol k ▁iz ▁vode ▁ .
▁Kao s , ▁pa nika , ▁kon fu zija .
▁Trebal a ▁si ▁presta ti ▁sur a đi vati ▁s ▁civil ima .
▁Hajde ▁Lu en , ▁priča j .
▁Pa , ▁ci ni ▁mi ▁se ▁ci st ▁onda , ▁zar ▁ne ?
▁Da . ▁Ovde ▁sam ▁mesec ima ... ▁bes kra j nim ▁už as nim ▁mesec ima ▁u ▁ovoj ▁mem ljivo j ▁tam nici ... ▁kao ▁iz gla dne la ▁životinja ... ▁nada jući ▁se ▁da ▁ću ▁da ▁um rem ... ▁samo ▁da ▁ne ▁bih ▁ ova ko ▁živ ela .
▁Na stavi , ▁dušo .
▁- Hva la .
▁Ja ▁ću ▁da ▁priča m . ▁Znam ▁da ▁ćeš ▁ hte ti ▁da ▁priča š , ▁ali ▁se ti ▁se , ▁ti ▁si ▁u ▁em oti vno ▁ra nji vom ▁stan ju .
▁Sigur ni ▁ste ?
▁Šta ▁ti ▁radiš ▁ovdje ?
▁Da , ▁do kle ▁god ▁to ▁ne ▁bude ▁kon j , ▁rad ujem ▁se .
▁Sa ... ▁nov ci cem ▁za ▁papir ▁i ▁kan ap ▁mo zes ▁dobiti ▁so p st ven a ▁kri la
▁Ja ▁se ▁ne ▁va tam ▁sa ▁pr lja vim ▁od vrat nim ▁hi pi jem .
▁Pol u dela ▁je .
▁Dobro . ▁Č uj , ▁o pusti ▁se .
▁Gledaj , ▁želim ▁i ći ▁jako ▁po lako ▁s ▁ovim .
▁Ko ga ▁si ▁onda ▁z vala , ▁L orra ine ?
▁To ▁se ▁i ▁tebi ▁baš ▁sada ▁dešava !
▁U ▁po nov ljeno m ▁su đen ju ▁Har a dina ju ▁na ▁površin u ▁iza š le ▁ozbiljn e ▁tvrdnj e
▁Ovo ▁neće ▁i ći ▁da leko , ▁prijatelj u .
▁Mislim , ▁zna la ▁sam ▁da ▁je ▁bio ▁om i ljen ▁ali ▁ovo ▁je ▁ne do ljivo .
▁O pusti ▁se ▁malo , ▁Cre e per .
▁Gu bi ▁se .
▁Molim ▁vas , ▁moram ▁da ▁pod ne sem ▁prijav u ▁ove ▁godine .
▁Pre ko su tra ?
▁Ja ▁po nek ad ▁za mišlja m ▁kako ▁bi ▁reci mo ▁bilo , ▁sa ▁mom cima , ▁na ▁primer , ▁ili ▁život om ▁u op šte .
▁Sada ▁će ▁bar ▁to ▁ri ješ iti .
▁A ▁ja ▁svoj a ▁nisam ▁pre krš io .
▁Za nim ljivo .
▁- Da , ▁komitet ▁je ▁posto ja o ▁i ▁ja ▁sam ▁bio ▁član .
▁Vol jan ▁sam ▁pot pis ati ▁ugovor .
▁Po ko pala ▁si ▁ih ▁na ▁su du ▁prvi ▁puta , ▁ponovno ▁to ▁napravi .
▁O tvor i ▁pro zor ▁u ▁ku hin ji , ▁možda ▁će ▁da ▁pre le ti ▁pravo ▁kroz ▁ku ću .
▁- O pusti ▁se , ▁Bur t .
▁Bio ▁je ▁to ▁pravi ▁por o đa j ▁ljubav i ▁za ▁mene .
▁Do ▁dana s , ▁to ▁mi ▁je ▁om i ljeni ▁sok .
▁Oh , ▁samo ▁ona ko ▁na ga đa m ▁ali ▁zar ▁vi ▁ni ste ▁Liz ▁Bra un , ▁Blu je va ▁žena ?
▁August a !
▁Mali ▁je ▁nap isa o ▁predsjednik u ▁re kav si ▁da ▁kada ▁je ▁u ▁kamp a nji ▁je ▁upozna o ▁njegov ▁pomoc nik ▁ , ▁g . ▁Far ley ▁ .
▁Nei s pun ja vanje ▁norme ▁neće ▁biti ▁to leri s ano .
▁Slušaj , ▁pro ći ▁ćemo ▁kroz ▁ovo ▁zajedno .
▁Je ▁li ▁to ▁stan ▁3 ?
▁- ▁Iz vin java m ▁se .
▁Sigur no , ▁koliko ▁i ▁su nce ▁koje ▁će ▁su tra ▁up e ći ▁do ▁40 .
▁Po nek ad , ▁se dim ▁za ▁komp om , ▁i ▁pani či m .
▁I ▁des et ▁po ▁50 ▁čini ▁$ 5 ,000 .
▁Mora ▁biti ▁nešto .
▁Ako ▁nisu ▁pro meni li ▁pravila ▁po ker a , ▁ot kad ▁sam ▁ovde ... ▁ti ▁si ▁izgubi o .
▁Šta ▁ti ▁radiš ▁u ▁civil stvu ?
▁Mo že ▁da ▁me ▁prvo ▁ubije š , ▁pa ▁onda ▁p jev aš ?
▁Bio ▁je ▁to ▁jedan ▁od ▁naj ca rob ni jih ▁trenutak a ▁u ▁mo me ▁zi vo tu .
▁Kada ▁sam ▁joj ▁se ▁vrati la , ▁već ▁je ▁bila ▁upozna la ▁Maks vela .
▁Pa zi , ▁uvek ▁reci ▁da ▁sam ▁ja ▁Am ede o .
▁Od ▁svih ▁nas , ▁ti ▁si ▁najviše ▁imao .
▁Mi ▁ćemo ▁i ći ▁na pred .
▁Bi cu ▁gotov a ▁za ▁sekund u .
▁I ▁um re ćeš ▁od ▁sme ha , ▁sigur na ▁sam , ▁ako ▁ti ▁kažem ▁da ▁me ▁on aj ▁čud an ▁sus ret ▁s ▁tobom ▁one ▁no ći ▁u ▁ma gli ▁i ▁kas ni ji ▁sus re ti , ▁koji ▁su ▁me ▁dobro ▁uz dr mali ▁da ▁me ▁to ▁na tera lo ▁na ▁razmišlja nje ▁prvi ▁put ▁u ▁život u .
▁Pos u dji vale ▁smo ▁pare ▁ jedni ▁od ▁drugih ▁svo ▁vreme , nije ▁to ▁ni sta ,
▁- É ija ▁je ▁ovo ▁zabav a ?
▁Nikad a ▁ne ću ▁razum eti ▁že ne .
▁- Da , ▁kao ▁idiot ▁koji ▁drži ▁ra žan j .
▁So ba ▁Hen rije te ▁Lu pen ?
▁Kako ▁vam a ▁ide ▁ovde ?
▁Poz vao ▁me ▁van , ▁o tis li ▁smo ▁na ▁vec er u , ▁pri ca li ▁smo ▁i ▁dje lo valo ▁je ▁poput ▁magi je .
▁Šta god ▁da ▁je ▁u ▁ pita nju , ▁veliko ▁je .
▁Tu ▁su ▁tvoje ▁ja pan ke ▁za ▁tu s ▁tvoj ▁li c ni ▁pe skir ▁za ▁tu s iranje , ▁pe skir ▁za ▁ru ke ▁i ▁jedan ▁za ▁lice ▁tvoj ▁sa pun ▁za ▁ru ke , ▁sa pun ▁za ▁lice ▁i ▁om i ljeni ▁sam pon .
▁Zna o ▁sam ▁da ▁sat ▁ot ku ca va ▁i ▁da ▁moje ▁vrijeme ▁dolazi ...
▁Ha d !
▁Kir k , ▁možemo ▁li ▁da ▁po pri ča mo ▁na krat ko ?
▁En o ▁problema .
▁Nisam ▁mu ▁to ▁pred ba ci vala , ▁jer ▁bi ▁mi ▁ina če ▁bio ▁dužn ik .
▁- ▁G . ▁Vol ton , ▁molim ▁Vas !
▁Kara s ...
▁Kaž eš ▁da ▁si ▁me ▁u bac ila ▁na ▁listu ▁pos jeti o ca , ▁jer ▁re kli ▁su ▁ako ▁nisam ▁por o dica ...
▁Ali ▁to ▁ne ▁znači ▁da ▁je ▁tvoja ▁maj ka ▁nesta la .
▁Po lako .
▁... i ▁sada ▁ulaz im ▁u ▁so bu , ▁gde ▁od e ća ▁od lazi ▁um re ti .
▁Sa ▁mnom ▁ste ▁sigur ni .
▁Na ▁drugo m ▁brod u , ▁koji ▁je ▁pri sta o ▁u ▁Sj ever noj ▁A meri ci ▁stol je će ▁kasnije , ▁bili ▁su ▁običn i ▁en gle ski ▁rad nici ▁koji ▁su ▁samo ▁že lje li ▁zaradi ti ▁malo ▁zemlje ▁z no jem ▁svojih ▁ru ku .
▁Jesi ▁li ▁spremn a .
▁Gra b ljiva c ▁iz ▁male ▁ku će ▁s ▁veliko m ▁ sposob no š ću ▁da ▁se ▁spri ja telj i ▁s ▁mo ć nim ▁mušk ar cima ▁i ▁žena ma .
▁Za ve ži , ▁gdje ▁su ▁dija man ti ?
▁Pi ta o ▁sam ▁se ▁da ▁li ▁bih ▁možda ▁mogao ▁da ▁nešto ▁uradim ▁za ▁Maj nd s kej p .
▁- ▁Nisam ▁sigur na / ▁ovaj -
▁To ▁je ▁sve ▁što ▁imamo .
▁Možemo ▁do ći ▁kasnije .
▁Japan ski ▁bomb ard eri ▁slobodn o ▁su ▁napad ali ▁Singap ur ▁jer ▁nije ▁bilo ▁nik ak ve ▁ zračn e ▁obra ne .
▁Samo ▁da ▁znaš , ▁nema ▁nije d nog ▁zar eza ▁na ▁tom ▁papir u .
▁Ob ično ▁bismo ▁ih ▁pos ad ili ▁da ▁se de ▁u ▁sa li ▁i ▁u bija li ▁ stru jom ▁dok ▁gleda ju ▁predstav u .
▁Po lako ▁na prije d .
▁" ali ▁mora ▁da ▁sam ▁bio ▁u ▁pogrešn o ▁vrijeme "
▁Kakv a ▁si ▁ti ▁to ▁žena ?
▁Kau boj .
▁Vidi , ▁znam ▁da ▁bi ▁radi je ▁bio ▁na ▁za dat ku ▁sa ▁Č a kom ▁i ▁Sa rom , ▁ali , ▁ci jeli ▁tvoj ▁život ▁ne ▁moraju ▁da ▁budu ▁samo ▁za da ci .
▁Da , ▁se ko .
▁Zar ▁ni ste ▁malo ▁pre ter ali , ▁kap etan e ?
▁Pokuša j ▁sada .
▁- ▁Oh , ▁da .
▁Pre ma ▁posljednj em ▁poziv u , ▁on ▁ne ▁do lij eva ▁samo ▁u lje ▁na ▁va tru .
▁Jer emia h ▁Mc Le an ▁je ▁u bio ▁Mary .
▁Na dam ▁se ▁da ▁te ▁nikada ▁više ▁ne ću ▁vidjeti !
▁Oni ▁su ▁samo ▁is ec kali ▁Gor mana .
▁Ne ▁sme ju ▁mu ▁se ▁vide ti ▁ni ▁stop ala .
▁- Ko liko ▁vam ▁ja ▁plati o ? ▁- Ja ▁sam ▁plati la ▁njemu !
▁Mislim ▁da ▁bi ▁uz iva o .
▁Ben ▁i ▁ja ... ▁Za vrš ili ▁smo .
▁I ▁uz mem ▁svo ▁sa lo , ▁kao ▁da ▁su ▁sa lo ▁moj i ▁drugo vi ▁iza ▁nepri ja telj skih ▁linij a , ▁znaš .
▁Za kas ni li ▁ste ▁jedan ▁sat .
▁Rekla ▁sam ▁ti ▁da ▁bi ▁tro l ski ▁put ▁bio ▁br zi .
▁? ▁Qu ▁est ▁? ▁?
▁Kako ▁je ▁to ▁dobra ▁ vest ?
▁Pla ća m ▁mu ▁kiri ju , ▁kont aš ?
▁Ne ▁mogu ▁sada ▁priča ti ▁s ▁tobom , ▁na z vat ▁ću ▁te .
▁Ne ▁mo ze ▁se ▁otkri ti , ▁osim ▁pod ▁ljubi cast im ▁svjetlo m , ▁te ▁je ▁pre nos iv ▁na ▁svakog a ▁ tko ▁ga ▁do dir ne .
▁Znaš ▁li ▁kako ▁da ▁se ▁ponaša š .
▁- ▁Nisam ▁mogao .
▁Po ruč ni če .
▁Se si lio ▁je ▁otišao .
▁zen a , ▁ti nej d ž er ▁i ▁sve ▁sto ▁to ▁sa ▁sob om ▁no si .
▁S voj e vre meno ▁je ▁bio ▁jedan ▁od ▁naj mo ć ni jih ▁ljudi ▁u ▁A meri ci .
▁Ba š ▁si ▁se ▁mi moi šao ▁sa ▁svoj om ▁djevoj kom , ▁Bet ty ▁Su a rez .
▁Drž im ▁te ▁na ▁oku , ▁gospodine .
▁Zaboravi la ▁si ▁namaz ati ▁kru h .
▁- ▁Reci ▁is tinu , ▁We nde II .
▁- ▁M amina ▁mi ▁se ▁više ▁svi đa .
▁Moram ▁reci ▁da ▁sam ▁iz ne na đen .
▁# ▁Ali , ▁dok ▁# ▁# ▁Po m r či na ▁#
▁Bio ▁mi ▁je ▁kao ▁otac .
▁U ▁stvari , ▁tre nut no , ▁naj važ ni ji .
▁- Mi s liš ▁da ▁je ▁ru ž na ?
▁Bio ▁bih ▁bolj i ▁i ▁od ▁Char l tona ▁He sto na .
▁Post o ▁su ▁to ▁vec ▁ju cer as nje ▁ vesti , ▁mo zem o ▁li ▁da ▁ih ▁ ost avimo ▁iza ▁sebe ?
▁On ▁je ▁vrij e dio ▁mili ju ne . ▁Ali , ▁znaš , ▁seda m ▁godina ▁nakon ▁nesta nka , ▁sud ▁će ▁ga ▁pro glas iti ▁služb eno ▁mrtv im . ▁U ▁to ▁vrijeme , ▁ona ▁može ▁gla tko ▁da ▁uz me ▁već i ▁dio ▁nov ca .
▁- ▁Zato ▁da ▁bi ▁mogao ▁da ▁se ▁sak rije .
▁- ▁Ne ▁volim , ▁Nick !
▁- ▁To liko ▁o ▁primi r ju .
▁Vol im ▁po gled , ▁znaš .
▁Za tvor ili ▁su ▁joj ▁muž a ▁zato ▁što ▁je ▁imao ▁ve lika ▁usta .
▁Mo že ▁da ▁pokr ije ▁dva ▁mesec a , ▁ili ▁tako ▁nešto .
▁Pri ča le ▁smo ▁o ▁k nji zi ▁Er ike ▁Jo ng ▁" S tra h ▁od ▁let enja ".
▁I mali ▁smo ▁naj du ži ▁lov .
▁G . ▁Web ster , ▁g đa ▁A cker man ▁iz ▁Agencij e ▁za ▁zapošljava nje .
▁- A ▁ga ye vi ▁su ▁odgovor ili ▁čo ko la dom ▁i ▁si rom .
▁Svi ma ▁koje ▁volim .
▁Mal či ce ...
▁Sad ▁to ▁pod ije lite !
▁Mislim , ▁zašto ▁ pita š ?
▁- ▁Zo vi ▁So la ▁" Re š et ku " ▁telefon om .
▁Do bar ▁lov , ▁bra te .
▁Nešto ▁te ▁mu či ?
▁Svi ▁osim ▁nas .
▁Pre viš e ▁kontra di kcija ▁za ▁vaš ▁polici jski ▁mental itet ?
▁Da ▁izravn am ▁sve ▁dugo ve ▁između ▁tebe ▁i ▁mene .
▁Da ▁bi ▁pre ži vela ▁ovde , ▁mora će ▁da ▁se ▁pod či ni ▁tim ▁novi m ▁vlada ri ma .
▁Evo ▁ga ▁i ▁ovde .
▁Od ak le ▁joj ▁ ova ▁s ranja ?
▁Je su ▁li ▁nas ▁na šli ?
▁Molim o ▁vas ▁da ▁osta vite ▁svoje ▁ime ▁i ▁broj ▁a ▁mi ▁ćemo ...
▁Bra k ▁moje ▁kćer ke ▁se ▁rasp ada o , ▁a ▁moj ▁ze t , ▁Va rick ▁Stra us s , ▁je ▁prije tio .
▁Moj ▁rod ni ▁grad ▁u ▁Tre će m ▁ reich u
▁Got ovo ▁je ▁za stra šu ju će ▁koliko ▁s lično sti ▁nas ▁dvoj e ▁imamo .
▁Kor nja če ▁su ▁glu he .
▁D va ▁u če nika ▁nisu ▁dosta ▁da ▁bi ▁se ▁škol a ▁o drž ala .
▁- G i bb se !
▁Ali ▁sad ▁sam ▁se ▁vrati o .
▁Pa , ▁sada ▁se ▁vas ▁dvoj e ▁možete ▁provo za ti .
▁Za pan ju ju će ▁je ▁koliko ▁vremena ▁uz ima ▁pis anje .
▁- ▁Ne ▁radi ▁se ▁o ▁tome .
▁Do đi , ▁ma leni .
▁Di z ajn iranje ▁sredi ne .
▁Kad ▁je ▁od lazi la , ▁za gr lio ▁sam ▁je .
▁Daniel le ▁je ▁samo ▁još ▁jedan ▁dan ▁u ▁ DC - u .
▁- ▁Mo m ci .
▁- ▁Hey , ▁zar ▁to ▁nije ?
▁Želim ▁savršen i ▁ljudsk i ▁život ▁s ▁njim , ▁previše , ▁Stefan e , ▁vjer uj ▁mi ,
▁Mr zim ▁ta ▁s ranja . ▁- l z vin ite .
▁Rekao ▁sam ▁vam ▁da ▁će ▁biti ▁bu dan , ▁zar ▁ne ?
▁To ▁nije ▁ništa .
▁Raz log ▁više ▁za ▁už i vanje ▁u ▁ovim ▁tren u cima ▁rad osti .
▁Teh nic ki ▁nisi .
▁O ti šao ▁sam ▁tog ▁ju tra ▁dok ▁si ▁ti ▁još ▁spava la .
▁Molim ▁te , ▁nemoj ▁učiniti ▁nešto ▁što ▁ćeš ▁pož ali ti , ▁Lu cas .
▁Po bri nu cu ▁se ▁za ▁svet .
▁Ne ▁pokušava j ▁to ▁prijatelj u .
▁V la sti ▁us m jer avaju ▁nap ore ▁na ▁pružanj e ▁usluga ▁građan ima ▁i ▁na ▁zaštitu ▁turi z ma ▁kao ▁vi tal nog ▁sektor a ▁za ▁ovu ▁republi ku .
▁Čo ve če , ▁Ber na det ▁će ▁o bož a vati ▁ovo .
▁Zašto ? ▁Pla ši te ▁se ? ▁Ili ▁dr hti te ▁jer ▁vas ▁ovo ▁boli ?
▁- ▁U ▁biti .
▁D žo šu a ▁je ▁otišao ▁sa ▁o cem ▁u ▁Ar izo nu , ▁Met ju ▁je ▁osta o ▁sa ▁maj kom ▁u ▁Vaš ington u .
▁- ▁Ta ta ...
▁Tko ▁bi ▁povjer ova o ▁da ▁će ▁C lo one y ▁biti ▁sam ▁u ▁tim ▁godina ma ?
▁Bio ▁sam ▁mušk a rac !
▁Martin ▁je ▁bio ▁s lobo dan ▁do ▁po no ći .
▁19 50 ▁si vi ▁for d .
▁Ne , ▁ali ▁je ▁poznat o ▁lice , ▁zar ▁ne , ▁Eric ?
▁L ju di ▁posta ju ▁pred s jedni ci ▁jer ▁su ▁bili ▁na ▁pravo m ▁mje stu ▁u ▁pravo ▁vrijeme .
▁Da ▁li ▁ti ▁je ▁We a ver ova ▁i kad ▁re kala ▁šta ▁joj ▁se ▁des lio ▁tog ▁dana ▁na ▁a ked mi ji ?
▁- JE SI ▁LI ▁V ID JE LA ▁E KO A ? ▁- NIS AM .
▁Do z voli ▁da ▁ti ▁otvori m ...
▁Stav i ▁mu ▁u ▁usta .
▁Mogu ▁li ▁još ▁nešto ▁pi tati ?
▁- P u sti ▁i ▁mene .
▁I ▁ako ▁se ▁kor dini ra ▁sa ▁bes pil ot nom ▁let ili com ▁pred ator ...
▁Samo ▁je ▁ima la ▁pokr et ▁cre vi ma ▁pred ▁svim a ▁sa ▁svojim ▁posledn jim ▁jaki m ▁pri ti skom .
▁Men tal ni ▁por eme ca j ...
▁- Da .
▁Što ▁ćeš ▁sa ▁svim ▁tim ▁nov cem ?
▁Jer ▁ništa ▁ne ▁znam .
▁A ▁Bas tera ▁su ▁po vu kli ▁iz ▁rat ne ▁obu ke .
▁- ▁Is pit uju ▁m nog e . ▁Da ?
▁Onda , ▁s ▁či m ▁se ▁tvoj ▁o ta ▁pre živ lja va ?
▁Možda ▁mi ▁da ju ▁smjer nice .
▁- S vi đa ▁mi ▁se .
▁I ako ▁mi ▁je ▁is pred ▁oči ju , ▁ja ▁još ▁uvek ▁ne ▁ver ujem ...
▁A ▁val cer ?
▁U č la nio ▁sam ▁se ▁u ▁te retan u .
▁S re o ▁sam ▁Bez ub icu .
▁O či ▁ra vno ▁na prije d
▁Dobro , ▁siguran ▁sam ▁da ▁nije ▁ništa ▁strašn o . ▁Hajde ...
▁Molim ▁te , ▁mama , ▁da j ▁mu ▁da ▁osta ne ▁na ▁vec eri !
▁A ▁on ▁je ▁voli ?
▁Od ▁ glav nog ▁komand anta .
▁Zna s , ▁iz med ju ▁nas ih ▁za sed nja ▁div lja c ko ... ▁je ban je , ▁dok ▁ne ▁um remo .
▁Prim ili ▁su ▁me ▁na ▁ispitivan je ▁li je ka ▁za ▁pat ološk u ▁s ra me ž ljivost !
▁- ▁Šta ▁želiš , ▁šta ▁ti ▁za ista ▁želiš ? ▁Nova c !
▁Nešto ▁se ▁dogodilo ▁is pred ▁li je čni čke ▁ordin acije ▁u ▁Pont y pool u . ▁Mogu će ▁da ▁se ▁radi ▁o ▁ne red ima ...
▁Moram ▁sti ci ▁tamo .
▁Stvarno , ▁vrijeme ▁je ▁da ▁dobi jem ▁un uke .
▁7 ▁m ▁is pred ▁tebe .
▁cita va ▁je ▁pro s la va ▁V IP ▁prostor .
▁Uh ... ▁Ross .
▁Mo že ▁dolazi ti ▁od ▁sva ku da .
▁- Ra ši rite ▁se .
▁Pa ▁koju ▁kor ist ▁imam ▁od ▁toga ▁na ▁pus tom ▁ot oku ?
▁Ne ko ▁zove ▁sa ▁D ž ord ž ta un ▁univerz itet a .
▁Sva ki ▁dan ▁mislim ▁o ▁njemu .
▁Post oji ▁jedna ▁alternativ a ▁sa ▁ovakv om ▁ vrst om ▁ raka
▁Da ▁ne ▁bi ste ▁bili ▁u sam ljeni ▁g . ▁Tre he ar n . ▁Si lazi mo ▁naš ▁tro j ca .
▁- Z nam , ▁pred iv na ▁sam .
▁Ale j andro ▁je ▁mrtav .
▁Ovaj ▁svijet ▁će ▁te ▁sa ž vaka ti ▁i ▁is p lju nuti .
▁Ah , ▁prvi ▁sam .
▁Um ro ▁je ▁prije ▁nekoliko ▁ vije kova .
▁Sad ▁smo ▁bo gati . ▁Koliko ▁ćemo ▁zaradi ti ▁samo ▁proda jom ▁škol e !
▁S jedi te ▁ob oje .
▁" Sa mo ▁je ▁tvoje ▁ime ▁na ▁moj im ▁us na ma ."
▁Mak ni ▁me ▁sa ▁svoje ▁pro klet e ▁liste ▁i ▁da ▁me ▁više ▁nikad ▁nisi ▁z vao !
▁Jesi ▁li ▁z bil ja ▁S ▁tim ▁ja pi jev skim ▁sme će m ?
▁Imam ▁svoju , ▁ali ▁nema ▁šans e ▁da ▁je ▁iskoristi m .
▁- ▁Prav e ▁kvalifik acije . ▁- ▁Prav e ▁kvalifik acije . ▁To čno , ▁Jim .
▁Hej , ▁Ed , ▁sa ▁sreć om ▁su tra ▁u ve če .
▁Moramo ▁pri ček ati ▁konačn i ▁rezultat .
▁G . ▁Tak ata ... ▁U ▁vezi ▁vaše g ▁plan a . .
▁Ne , ▁ne , ▁čovječe .
▁Whi ch ' ll ▁nas ▁imaju ▁više ▁do ▁naš ih ▁pod ne - 30 ▁kor jena st - to o ty ▁s vjež e ▁i ▁vo ć ni ▁do ruč ak .
▁Treba m ...
▁Je z ▁bez ▁obzir a ▁što ▁mr zim ▁to ▁prizna ti , ▁imam ▁problem ▁s ▁Claire .
▁Do bija m ▁be bu ▁bez ▁o nih ▁bes a nih ▁no ći ▁i ▁pr lja vi h ▁pel ena .
▁- ▁O oh - o oh !
▁V rata ▁su ▁bila ▁za ključ ana .
▁Mislim ▁da ▁me ▁zo vu .
▁To ▁ga ▁povez uje ▁sa ▁Re my jem , ▁a ▁preko ▁Re my ja ▁sa ▁ot mi ča ri ma .
▁Bruk aš ▁me . ▁Vidi , ▁znam ▁da ▁si ▁uz ne mi ren , ▁ali ...
▁A ▁S ten ▁S mit ▁nije ▁ni ▁na lik ▁tome !
▁Dobro ... ▁Una ▁Ve z ▁mas ... ▁El ▁Bar co .
▁Ne ▁znam ▁kako ▁ću ▁to ▁u radi ti , ▁ali ...
▁Zdravo , ▁Bon i .
▁Dobro .
▁Tako ▁je ▁sve ▁postav ljeno .
▁E va ▁je ▁po pri li čan ▁ku har .
▁Je ▁li ▁to ▁We a ver ?
▁Gospod ina ▁Tak era .
▁Pa zi te ?
▁Žao ▁mi ▁je .
▁Š ali m ▁se .
▁Slušaj , ▁možemo ... ▁da ▁pomogne mo ▁sa ...
▁A ▁rat nici ▁treba ju ▁zna ti ▁zašto ▁ služ e ... ▁i ▁gi nu .
▁- S ve ta ▁krv .
▁Ima ▁let ili cu .
▁Znam ▁dovoljno ▁da ▁raz lik ujem ▁ulaz nu ▁ra nu ▁od ▁izlaz ne .
▁Kako ▁Ele ono re ▁izgleda ?
▁To ▁je ▁moj ▁ta ta . ▁U ▁bolnic i ▁je .
▁Bi će ▁to ▁tvoja ▁priča .
▁S tvor enja ▁se ▁kre ću ▁s ▁pov eć om ▁sigurno š ću .
▁Pro ro can stva ▁govori še ▁o ▁ cov je ku , ▁koji ▁ce ▁jednog ▁dana ▁pokuša ti ▁s klop iti ▁mas ku ▁i ▁vlada ti ▁svijet om .
▁Zar ▁ne ▁znaš ▁da ▁nebo ▁je ▁pla vo
▁Da ▁za mi jen imo ▁prav e ▁ši fre ▁la žni m .
▁Č ula ▁sam ▁glas ine .
▁ TI TL ▁BY ▁R OD JO CO US IN
▁O ti šao ▁sam ▁od ▁ku će ▁sa ▁4 ▁godine ▁i ▁još ▁se ▁nisam ▁vrati o .
▁Gdje ▁si ▁bila ▁jutro s ?
▁Samo ▁ne ▁bih ▁vole o ▁da ▁me ▁taj ▁mor on ▁ubije .
▁Svi ▁su ▁prop a lice !
▁Va zu .
▁Ko ga ▁je ▁briga ▁za ▁muž u .
▁I ako ▁bih ▁mogao ▁op oz vati ▁tvoj ▁pas o š ▁i ▁ staviti ▁ti ▁ime ▁na ▁listu ▁zločin aca . ▁I ▁is je ći ▁ti ▁str uju ▁do ▁kraj a ▁života .
▁Šta ? ▁Je l ▁ovo ▁ka kva ▁šal a ?
▁Pre ure di li ▁su ▁mrtv a čni ce ▁sm ješ tene ▁u ▁pod rum u .
▁Kako ▁je ▁bilo ▁na ▁sa stan ku ?
▁Ne ▁di ram ▁je , ▁i ▁s klon i ▁mi ▁se ▁is pred ▁oči ju .
▁Ako ▁se ▁Ha ley ▁nikada ▁ne ▁pro bud i ▁po lug ola ▁na ▁pla ži ▁u ▁Flor idi ▁napravi la ▁sam ▁svoj ▁posao .
▁No site ▁se .
▁Idemo ▁unutra , ▁va zi ?
▁Sam ▁položaj ▁je ▁noć na ▁mora , ▁Svet osti .
▁Treba ▁da ▁proc isti m ▁misli .
▁I ▁zbog ▁tog ▁bi ▁ovo ▁trebalo ▁biti ▁u ▁redu ?
▁Na z ovi ▁me ▁kada ▁stig neš ▁tamo .
▁Ba š ▁je ▁me kan o .
▁Po kazi ▁mi ▁tvoj ▁prst .
▁Ski da mo ▁s nim ke .
▁51 - godi š nji ▁Albert ▁Jaz ex hi ▁v las nik ▁je ▁ka fe - bara ▁u ▁centr u ▁T irane .
▁U ▁stvari ▁ima ▁og rom ne ▁rezerv e ▁u ▁La os u . ▁Što ▁je ▁i ▁dove lo ▁do ▁in fla cije . ▁A ▁to ▁znači ▁kako ▁stvar aju ▁previše ▁nov ca .
▁I ▁za ▁naš ▁novac .
▁- Ž ao ▁mi ▁je . .
▁- O ▁s ranja !
▁Na z vali ▁smo ▁sebe ▁dva ▁puta ▁mu dri m .
▁Znam ▁jednog ▁što ▁živi ▁ovde .
▁Ba š ▁su prot no .
▁- ▁Šta ?
▁- No gir ali ▁su ▁ga ▁od ▁tamo .
▁Ovo ▁je ▁Wy nn ▁Du ff y . ▁- ▁Zdravo .
▁Gospod ine ▁Ke ču m !
▁Možemo ▁gleda ti ▁sva db ene ▁slik e .
▁Tako ▁sam ▁iz ▁ne pozna t osti ▁došao ▁do ▁plat ina ste ▁ploč e .
▁Sh va ća m ▁da ▁ne ▁rast u ▁na ▁sta bli ma .
▁H ra bri ▁ljudi ▁u bi ju ▁ih .
▁- ▁Moja ▁su pru ga ▁je .
▁On ▁je ▁samo ▁ ljub om oran ▁na ▁tebe .
▁Do du še , ▁ima ▁jedan ▁lokal ▁sa ▁od lično m ▁taj land skom ▁hra nom .
▁Imam ▁10 -2 ▁na ▁kri žan ju ▁35 . ▁i ▁9. ▁u lice .
▁Šta ▁ti ▁radiš ▁ovde ?
▁Če sti tam , ▁dru ška ne .
▁Ba to , ▁gubi m ▁signal .
▁" Mi s lio ▁sam ▁da ▁ste ▁re kli ▁60 ▁minuta ." ▁" 10 ▁minuta , ▁gubi ▁se ."
▁Sve ▁je ▁u ▁podaci ma .
▁Ku pio ▁sam ▁už inu .
▁Pro šli ▁smo ▁milion ▁puta ▁kroz ▁to ,
▁Sad ▁se ▁boj im , ▁da ▁je ▁to ▁ta ▁slik a .
▁O t kaz ?
▁Ti ▁la zes .
▁Ne ▁za meri ▁mi ▁što ▁te ▁pi tam ... ▁Koliko ▁imaš ▁godina , ▁Fil ?
▁Svi đa ▁mi ▁se .
▁Gro zna ▁je ▁to ▁stvar ▁živ jeti ▁u ▁m ra ku , ▁ne ▁biti ▁u ▁mogu čnost i ▁vidjeti ▁ono ▁što ▁drugi ▁uz ima ju ▁zdrav o ▁za ▁gotov o .
▁Na vali te , ▁ma ce .
▁Ja ▁ust vari ▁volim ▁svoj ▁život ▁baš ▁ ova kav ▁ka kav ▁je .
▁- V id imo ▁se ▁mom ci .
▁- Ć ao ▁Emily .
▁To ▁je ▁do vod ▁zrak a ▁za ▁Hi ve . ▁Hajde .
▁Ko ja ▁je ▁Be a trice ?
▁I ▁ja ▁sam ▁to ▁misli la .
▁Ve oma ▁je ▁stvar an ▁mama .
▁Ko ji ▁vam ▁je ▁ponudi o ▁Da ▁se ▁u da .
▁Tko ▁je ▁glas ao ▁za ▁La uru ▁Ro s lin ?
▁Pri prem ili ▁smo ▁obr oke ▁kor iste ći ▁tradi cional ne ▁vojn e ▁sa stoj ke .
▁- ▁Zato ▁što ▁tak vi ▁kao ▁što ▁je ▁on ▁to ▁ rade . ▁Moram ▁da ▁idem .
▁- O d ▁prvo g ▁moment a ▁kad ▁sam ▁te ▁s rela , ▁zna la ▁sam .
▁Bobby ▁ce ▁ti ▁pomoc i , ▁Tess .
▁Pla vi ▁čovjek .
▁Jesi ▁li ▁ik ada ▁radio ▁ išta ▁s lično ?
▁Da , ▁ali ▁to ▁se ▁ stavlja ▁u ▁ uši .
▁Či ni ▁se ▁da ▁je ▁brod ▁pret r pio ▁štet u ▁od ▁me te ora .
▁" Li ter atura ▁je ▁pun a ▁takvih ▁af era ."
▁Ana , ▁jako ▁je ▁lijepo ▁imati ▁neko g ▁ko ▁se ▁op ho di ▁prema ▁tebi ▁Kao ▁da ▁mu ▁je ▁stvarno ▁stalo ▁do ▁tebe .
▁- ▁Mit zi .
▁Ali ▁zaboravi o ▁si ▁jedan ▁detalj .
▁Šta ▁se ▁dogodilo ?
▁Nakon ▁toga ▁sto ▁si ▁uradio ▁The i , ▁Sa ri , ▁Oliver u ?
▁Ne ▁gleda j ▁me ▁tako , ▁Chuck .
▁Onda ▁se ▁vidim o ▁opet , ▁da ?
▁Znam ▁da ▁si ▁fru stri ran , ▁ali ▁ne ▁možemo ▁presta ti ▁sada .
▁Bit ▁ću ▁malo ▁ovdje ▁s ▁vam a , ▁ako ▁može . ▁- Ne ▁može !
▁Tako dje ▁sve ▁mrtv o .
▁Jos ▁prije ▁20 ▁godina ▁dr . ▁Hu b bert ▁je ▁u kazi vao ▁svojim ▁koleg ama ▁u ▁industri ji ▁na fte ▁da ▁ce ▁S AD ▁ vjerojatn o ▁do se ci ▁vr hun ac ▁proizvodnje ▁na fte ▁unutar ▁10 - 15 ▁godina .
▁Sada ▁samo ▁želim ▁biti ▁dobra ▁mama .
▁Ob zi rom ▁da ▁ste ▁ovdje ▁radi ▁osigura nja ▁ tehničk e ▁podršk e ▁glede ▁De fi anta
▁Ne ćemo ▁je ▁la ko ▁u bed iti ▁da ▁pro govori .
▁E ci ▁pe ci ▁pe c ?
▁Za ▁Tek sa ške ▁maj ke .
▁So bi ▁i ▁Lang or ▁su ▁odluči li ▁da ▁vam ▁ga ▁da ju .
▁Moramo ▁ih ▁obavijesti ti ▁da ▁si ▁sigur na .
▁Val j da ▁imam ▁više ▁do nje g ▁veš a ▁od ▁tebe .
▁Don ▁Ty ler ?
▁- ▁Že le ▁nas ▁u hvat iti ▁vu čno m ▁zrak om .
▁- O bo je ▁smo ▁sje ban i .
▁Če ka mo ▁za pis e ▁o ▁ne kret n inama , ▁ali ▁mislim o ▁da ▁je ▁njegovo ▁zemlji šte ▁mesto ▁gde ▁grup a ▁misli ▁da ▁ ču či .
▁Dig ni te ▁ga , ▁mom ci !
▁- Ja ▁ću ▁optuž iti ▁Frank a ▁i ▁pod ije lit ▁ćemo ▁troškove .
▁Trebal o ▁je ▁da ▁se ▁ja vim .
▁Ako ▁pomo li ▁gla vu , ▁sti s nu ću ▁brzo ▁bir anje .
▁- Ne ▁želim ▁o ▁tome .
▁Da ▁mogu ▁osta ti ▁hlad na .
▁Raz govara li ▁su ▁o ▁fot kama ▁u ▁škol skom ▁godišnj a ku . ▁Kako ▁ni tko ▁nije ▁za d ovolj an ▁svojim ▁iz gled om .
▁I ▁ako ▁je ▁ne ▁pi je te , ▁ide te ▁pravo ▁u ▁za tvor .
▁- ▁One s vijesti o ?
▁Možemo ▁ob oji cu ▁od bac iti ▁kao ▁os um nji čen e .
▁Pa , ▁Charles , ▁nazad ▁na ▁tvoj u ▁pis u .
▁" Fi lisi " ▁su ▁po bed ili .
▁V jer ovat no ▁ne ▁bi ▁trebao ▁pi tati ▁da ▁li ▁se ▁je ▁nešto ▁čud no ▁des ilo ▁na ▁ste pen i štu , ▁zar ▁ne ?
▁Ve b sa jt ▁su ▁pokr en uli ▁bu gar ski ▁Ce ntar ▁za ▁ne prof it no ▁pravo ▁i ▁Program sko - an ali ti čki ▁cent ar ▁za ▁evropsk o ▁pravo .
▁Kru go vi .
▁Mer line , ▁stig ao ▁si ▁na ▁vrijeme .
▁I ▁mora te ▁nam ▁vratiti ▁oružje .
▁Mislil a ▁sam ▁da ▁ću ▁se ▁mora ti ▁o staviti ▁pila tes a , ▁tr čan ja , ▁ten isa ▁i ▁sat ova ▁stri pti z ▁a e robi ka .
▁Dobro ▁jutro , ▁Dr . ▁Gordon .
▁- O z bil jan ▁je , ▁Robin e .
▁Post ara će ▁se ▁da ▁živi š ▁kao ▁kralj .
▁Moraš ▁prvo ▁reći ▁da ▁ti ▁je ▁žao .
▁Nemoj ▁ni ▁po mišlja t ▁na ▁to .
▁Je ▁l ' ▁vam ▁treba ▁pre voz ?
▁Po no ć ▁je , ▁i ▁su z država m ▁se ▁od ▁plak anja ▁is pred ▁sina .
▁Ja ▁sao sje æ am , ▁za ista ▁je sam .
▁K r v nik ▁ju ▁je ▁pri é vrst io ▁za ▁po jas , ▁s man ju jući ▁rasp o djel u ▁te ži ne ▁oko ▁str uka ▁o stavlja jući ▁ vrat ▁ne tak nuti m .
▁Znaš ▁li ▁koja ▁će ▁s lede ća ▁a kcija ▁da ▁bude ?
▁Ste ka o ▁si ▁veliko ▁pošt ovanje ▁s mak nu će m ▁bomb a ša ▁Len gli ja .
▁" Ma ma , ▁ja ▁želim ▁ho t ▁dog ."
▁- Mo ja ▁mama ▁gleda .
▁Pre traži o ▁sam ▁mesto ▁od ▁vr ha ▁do ▁d na .
▁- Mi s liš ▁da ▁sam ▁debe o ?
▁Da , ▁ali ▁nisi ▁imao ▁des et ▁godina .
▁Pri vedi te ▁ovo ▁kraju .
▁Sada ▁to ▁zna ci ▁ona .
▁Sa zna j ▁ko ▁je ▁taj ni ▁o bož ava lac . ▁- Za š to ▁ja ?
▁Z bil ja ?
▁Jer ▁sam ▁u kra o ▁star u ▁zen sku ▁to rbi cu .
▁Spe ar s , ▁Spe ar s , ▁da .
▁Moja ▁prijatelji ca ▁Rose mar y ▁Cro s s .
▁- s mi ješ na ▁je ▁ ova ▁cur a ▁ha ▁ljudi ▁?
▁U ▁redu .
▁Do tad ▁je ▁je di no ▁bit no ▁koliko ▁ću ▁potroš iti ▁na ▁hotel ske ▁usluge .
▁Uh vati te ▁ga ▁s ▁mene .
▁ cak ▁ga ▁i ▁oni ▁m rze .
▁" Ta - ra ▁ta - ta , ▁ta - ra ▁ta - ta ▁pro s ja ci ▁se ▁že ne ▁noć as
▁A ▁onda ▁sam ▁se ▁u u dala ▁za ▁tebe . ▁I ▁onda ▁sam ▁sazna la ▁da ▁svaki ▁ima ▁isto ▁s ranje .
▁Da ▁li ▁ti ▁je ▁pot reb na ▁pomoć , ▁Ni na ?
▁- ▁To ▁je ▁mnogo ▁vremena ▁da ▁bio ▁u ▁ku pati lu .
▁Mu za ▁se ▁po javljuje .
▁Ja ▁sam ▁Ja red ▁To l son .
▁Sh va ća m , ▁još ▁jedan ▁prop ali ▁revoluci on ar , ▁os jeti o ▁si ▁pri tis ak .
▁- ▁Drago ▁mi ▁je ▁da ▁sam ▁vas ▁upozna o .
▁On ▁je ▁Patri k ▁Paris i , ▁ok ?
▁O če , ▁treba m ▁te ▁hit no ... ▁jer ▁imam ▁dvoj be ... ▁strašn e ▁sumnj e ▁mu če ▁mi ▁du šu .
▁- O bo je ▁post i zu ▁ isti ▁cilj .
▁Daj ▁mi ▁de ton ator , ▁sine .
▁U ▁redu , ▁mom ci .
▁Ja ▁ću ▁da ▁ih ▁gleda m .
▁Bro š ura ▁je ▁od li čna , ▁ali ▁šta ▁je ▁sa ▁Jean ?
▁Jesi ▁li ▁tu ?
▁Ik ada .
▁To ▁je ▁je di no ▁mesto ▁na ▁kom e ▁ste ▁sigur ne .
▁Ali . '
▁Shar on , ▁njegov ▁lik ▁će ▁um rije ti ▁ako ▁ne ▁do đem o ▁do ▁njega .
▁Govori ▁en gle ski .
▁- ▁On ▁je ▁geni je , ▁zar ▁ne ?
▁Ja ▁mislim ▁da ▁se ▁na loži o ▁na ▁tebe ▁a ▁ti ▁se ▁prima š ▁na ▁to .
▁Hej ▁Em ma .
▁- Ne ma ▁drugog ▁na cina , ▁pla vi ▁de c ko .
▁Di mi try , ▁ne ▁misliš ▁li ▁da ▁je ▁vreme ▁da ▁de ca ▁i du ▁u ▁krevet ?
▁Ovdje ▁nije ▁sigurno . ▁Mora te ▁se ▁što ▁prije ▁s klon iti ▁sa ▁u lica .
▁- ▁Moje ▁je ▁za d ovolj stvo , ▁Charles .
▁Ko ▁je ▁ovo ▁?
▁Hej ▁kap etan e , ▁ho ćeš ▁jedan ▁uz o ?
▁Mora te ▁imati ▁fotografi je ▁nje ma čko g ▁nau čni ka .
▁Da ▁bare m ▁ovo ▁nije ▁is tina , ▁ali ... ▁zvuč i ▁dosta ▁kao ▁Se rena ▁koju ▁sam ▁ja ▁pozna vala .
▁I ▁nije d na ▁životinja ▁ne ▁profit ira ▁na ▁ njima ▁toliko ▁kao ▁gri z li ▁med ved .
▁To ▁bi ▁bilo ▁o stva ren je ▁s nova .
▁Hej , ▁de da !
▁Vaš ▁a meri čki ▁narod ▁će ▁da ▁plati ▁za ▁ovu ▁vaš u ▁gre š ku .
▁CA MER ON ▁M EY ER ▁I ▁ JA RED ▁B REN N ER . ▁- ▁J OS ▁NE KA ▁V EZ A ?
▁Hajde , ▁ha jde , ▁kre ni te .
▁Pi ta o ▁si ▁ma mu ▁za ▁foo t ball ?
▁Problem ▁će ▁se ▁du bo ko ▁sak riti ▁i ▁de koncentr isa ti ▁njegov ▁razum .
▁Od lično ▁je .
▁Zašto ?
▁Ce ntar ▁za ▁mo lek ular nu ▁medicin u ▁i ▁Nacional na ▁genet i čka ▁laboratorij a ▁otvoren i ▁su ▁u ▁So fi ji ▁7. ▁decembra .
▁O čaj ni čki ▁sam ▁te ▁traži o ▁3 ▁godine .
▁Uni šti o ▁si ▁im ▁sku tere ▁za ▁vod u . ▁Is pr s kali ▁su ▁nas .
▁Go s po đa ▁vam ▁živi ▁ovdje ? ▁Za d nji h ▁šest ▁mje se ci .
▁- ▁En di , ▁pazi !
▁Šta ▁je ▁onda ▁potrebno ?
▁Nema s ?
▁Po tegn i ▁van ▁Jack a ▁Carter a ▁i ▁pogleda j .
▁Č ak ▁i ▁uz ▁rekla me .
▁Lo tt , ža o ▁mi ▁je .
▁Mislim ▁da ▁to ▁nije ▁dobro .
▁Možete ▁li ▁da ▁pro ko ment ari še te ▁u bi stvo ▁Anne ▁Scott ?
▁" I ▁lag ano ▁je ▁do šla ▁kraj ▁njega , "
▁- ▁Op et ▁treba š ▁prijevoz ?
▁I ▁za ▁Dže ni ▁je ▁to ▁bilo ▁strašn o .
▁Možemo ▁da ▁vam ▁pomogne mo .
▁La na , ▁tres eš ▁se .
▁Du go ▁nije ▁bila ▁tak va .
▁Da ▁li ▁si ▁siguran ▁na ▁to j ▁lokacij i ?
▁Put ▁je ▁tra ja o ▁du že ▁nego ▁što ▁sam ▁očekiva o .
▁Bar ▁mi ▁dozvoli ▁da ▁ti ▁kup im ▁avion sku ▁kartu .
▁Mogu ▁da ▁ti ▁da m ▁mali ▁sa vet . ▁I di ▁i ▁na đi ▁svoje ▁pri če .
▁Nema mo ▁ništa ▁osim ▁mor nar skih ▁p jes ama .
▁Ta ▁je ▁lu dos t ▁sva ▁do ▁njega .
▁Ako ▁ga ▁ti ▁ne ćeš ▁ubiti , ▁ja ▁ho ću .
▁A ▁čak ▁se ▁ni ▁ne ▁tru dim .
▁Iz vu ci ▁ce mo ▁te ▁odavde , ▁dobro ?
▁U ću ti , ▁Jen n .
▁Možda ▁se ▁ob la či ▁malo ▁ot ka čen o , ▁ali ▁to ▁je ▁ne mo gu će .
▁Ko je ▁že ne ?
▁I ▁šta ▁ti ▁se ▁dogodilo ▁sa ▁se stro m ?
▁Nan sal , ▁do đi ▁da ▁mi ▁pomogne š ▁oko ▁ovog ▁si ra .
▁Z bun jena ▁sam , ▁što ▁se ▁meni ▁ne ▁događa ▁če sto ...
▁Ho cu ▁reci , ▁ako ▁stvari ▁i du ▁loše , ▁Marcus , ▁treba š ▁mi ▁reci .
▁Hvala ▁ti .
▁Dis tor zi je ▁na ▁visok o po jas nim ▁ frekven cija ma .
▁I dio te , ▁zar ▁ne ▁vidiš ▁šta ▁se ▁događa ▁ovde ?
▁I ▁dalje ▁postoji ▁de o ▁Le ksa ▁koji ▁može ▁da ▁se ▁bor i .
▁Još ▁nešto ?
▁zi li jene , ▁sta ▁to ▁radi s ?
▁To ▁ne ▁može ▁biti ▁to .
▁Na pa o ▁ga ▁je ▁mas k irani ▁go la ć ?
▁Evo , ▁30. ▁ sept em bar .
▁U ▁redu , ▁Te de .
▁Hoćeš ▁da ▁molim ?
▁Pi še ▁na ▁njen om ▁zdravstven om ▁kar ton u .
▁70 00 ▁ljudi ▁godišnj e ▁um re ▁zbog ▁doktor ke ▁gre ške .
▁Trebal o ▁bi ▁da ▁nos is ▁vise ▁od ▁jednog ▁dolara ▁De j vide .
▁U ▁redu , ▁ali ▁kad ▁je ▁sredi mo , ▁u ba ci ćeš ▁je ▁u ▁na stup , ▁je ▁li ▁tako ?
▁Plus , ▁por ast ▁van da liz ma , ▁tri ▁u ce nika ▁su ▁nesta la .
▁Ne ▁usu đ ujem ▁se ▁da ▁osta vim ▁pro klet i ▁ma č ▁neza šti će n .
▁Ne sta la ▁je ▁na ▁de vet ▁mje se ci .
▁Ok , ci sto ▁je .
▁- Me ni ▁moj ▁kaže ▁da ▁je ▁pravi .
▁Sebastian ▁Blo od ...
▁Zdravo , Ba di .
▁Moja ▁je ▁ve ca .
▁Uz mite ▁št ito ve , ▁op re mu ▁i ▁sve ▁što ▁možete ▁uzeti .
▁I ▁u šla ▁sam , ▁ok ren ula ▁se ▁i ▁tamo ▁je ▁bila ▁-- ▁savršen a ▁vjen ča nica .
▁Grupo , ▁pov la čenje .
▁" N je go vo ▁ime ▁je ▁bilo ▁policaj ac ▁Ro land ▁Ta ver ner " ▁iz ▁Her mos a ▁Beach , ▁California ..." ▁moj ▁najbolj i ▁prijatelj ."
▁V la da ju ća ▁D PS ▁osjeća ▁se ▁sigur na , ▁jer ▁pre pirk e ▁i ▁apa ti ja ▁pod ri va ju ▁moguće ▁izazov e .
▁Što ▁je ▁to ▁s ▁vam a , ▁mom cima ▁u ▁Charles town u ?
▁Total no ▁po m ra čenje ▁s r ca ." ▁O ▁Bo ? ▁e , ▁...
▁- ▁Zar ▁ne ▁možeš ▁ovdje ▁op rati ?
▁Ti ▁uz mi ▁nos ila , ▁ja ▁cu ▁za ▁radio ▁i ▁da ▁prijav im ▁ovo .
▁Od ras la ▁sam ▁s ▁mi š lju , ▁da ▁moram ▁na por no ▁radi ti , ako ▁želim ▁zaradi ti ▁nešto ▁novac a .
▁Samo ▁želim ▁da ▁sa stavi m ▁test ament . ▁Test ament , ▁ha ?
▁I ▁kao ▁za d nja ▁dana s , ▁miss ▁Ka link a !
▁- ▁V rlo ▁ vjerojatn o .
▁S OL ON , ▁H T JE LA ▁ BI H ▁ RA Z GO VAR ATI ▁S ▁TO B OM .
▁Os ec ace te ▁la gan ▁bol .
▁Zdravo , ▁Van da .
▁- ▁Ne ▁sje ča m ... ▁ . ▁- ▁Ako ▁je ▁mogla ▁pod nije ti ▁ona , ▁mogu ▁i ▁ja !
▁- ▁ Ć ut - a , ▁vas ▁dvoj e !
▁Ne ▁želim ▁da ▁polici ji ▁prijav e ▁moj ▁nesta nak .
▁10 ▁J .
▁Ti ! ▁Ti !
▁Ho ćemo ▁se ▁ven ča ti ▁kad ▁ja ▁na pun im ▁18 ?
▁Pogledaj ▁me .
▁Ja ▁sam ▁iz ▁ju go za pad nog ▁Bro ok ly na !
▁To ▁pri pada ▁ njo j !
▁Od govori !
▁Oh , ▁to ▁bi ▁bilo ▁fino .
▁I ▁mesto ▁da ▁pre uz mem ▁odgovornost ▁za ▁sve ▁moje ▁gre ske , ▁ja ▁sam ▁kriv io ▁tebe .
▁Sranje , ▁čak ▁ni ▁Na tso ▁nije ▁sko čio ▁tako ▁visok o .
▁Izgleda š ▁kao ▁kom pozit or ?
▁- Ko d ▁ku će ▁sam .
▁To ▁je ▁ tor ba ▁dio ▁kole k cije ▁kao ▁i ▁kar te .
▁U vek ▁sam ▁radio ▁sam , ▁niko ▁sem ▁mene ▁nije ▁zna o .
▁- D už nik ▁sam ▁ti ▁što ▁si ▁se ▁sa ž ali la ▁na ▁mene .
▁To ▁je ▁glavni ▁grad ▁cita vog ▁svijet a . ▁Ta mo ▁postoje : ▁ ova ▁Bi jela ▁ku ca . ▁I ▁ ova ▁mental na ▁institucija .
▁Hej , ▁sluša j , ▁dušo , ▁koliko ▁je ▁ovo ▁lu do ?
▁TO ▁JE ▁TO . ▁S ADA ▁LA Z NI ▁N AP AD .
▁Do đi , ▁Na zi .
▁Daj ▁nešto ▁da ▁mu ▁ve žem o ▁oči ! ▁Šta ▁to ... !
▁Ali ▁su ▁za tvor ili ▁studi o .
▁Za kle o ▁si ▁se ▁da ▁ćeš ▁ služ iti ▁i ▁št iti ti .
▁Drago ▁mi ▁je ▁što ▁smo ▁vas ▁na šli .
▁Vi ▁Amerika nci ▁voli te ▁misli ti ▁za ▁sebe ▁da ▁ste ▁direkt ni .
▁- Ne ▁mogu ▁rizik ovati ▁da ▁te ▁izgubi m .
▁- ▁Iz vr s no .
▁Svi ▁su ▁zna li ▁za ▁mene , ▁zar ▁ne ?
▁Žao ▁mi ▁je ▁što ▁sam ▁do šla ▁ ova ko , ▁ali ▁ne ▁ja v lja ▁se ▁na ▁telefon , ▁pa ...
▁O bu stavi ▁pri ču ▁odmah .
▁A jde , ▁hvala ▁ti ...
▁Ba bl sam ▁je ▁10 , ▁Bi f ste j k , ▁7 ▁Vou t ▁Bo j , ▁6, ▁Ker i ▁Pe č , ▁12.
▁O sjeća m ▁da ▁smo ▁s lično g ▁du ha .
▁Nikad ▁nisi ▁bio ▁pro gon jen ▁bak lja ma !
▁Oh , ▁ne , ▁Bi an ca , ▁molim ▁te .
▁Treba ▁oba vesti ti ▁K le opa tru , ▁šta ▁se ▁dešava .
▁Pr vo ▁F isk , ▁onda ▁Co t ton mouth .
▁Zašto ▁stalno ▁la že š ?
▁Ne ću ▁da ▁te ▁pov re dim . ▁Ne ću ▁da ▁te ▁pov re dim .
▁O NA ▁TA MO , ▁JE ▁NA ▁ TR Z IST U ▁O KO ▁ GO DI NU ▁D ANA ▁ZA ▁O KO ▁27. 5 ▁M IL ION A . ▁ AKO ▁S ADA ▁ DATE ▁P ONU DU , ▁ VER OV AT NO ▁ BI STE ▁M OG LI ▁DA ▁JE ▁DO B IJE TE ▁ZA ▁O KO ▁19. 5 ▁M IL .
▁Drug ar , ▁to ▁je ▁proces .
▁Vrati ▁se ▁na ▁spa vanje ▁i ▁dobro ▁raz misli ▁ tko ▁je ▁plati o ▁tu ▁kući cu ▁na ▁ob ali !
▁- ▁Ve ć ▁po či njem ▁da ▁mr zim ▁sam ▁sebe .
▁Pro š le ▁godine , ▁u ▁ovoj ▁regi ji ▁o stva ren o ▁je ▁ 290 ▁milion a ▁e ura ▁na ▁osnov u ▁u plat a ▁putem ▁mobil nih ▁telefon a .
▁D ne vna ▁so ba ▁nam ▁je ▁sin o ć ▁bila ▁kao ▁da ▁je ▁sv rati o ▁Dže k son ▁Po lok .
▁- Ni je ▁h tio ▁reći , ▁ali ▁želi ▁po pri ča ti ▁s ▁vam a ▁lice m ▁u ▁lice .
▁Vrati ▁se .
▁ ALI ▁N JI HO VO ▁N AJ D RA ZE ▁Z LO D JE LO : ▁N AB IJA NJE ▁ SH ELL EY JE VE ▁G LA VE ▁U ▁ NJE G OV U ▁N AP RT N JA C U .
▁Dobro , ▁se st .
▁- ▁Moramo ▁na trag .
▁Od lu čio ▁je ▁da ▁nas ▁po ni zi ▁svojim ▁pre zi rom .
▁Boy , ▁usta ni .
▁Po slov ni ▁pregled : ▁Hrvatsk a ▁će ▁ vrš iti ▁privat iz aciju ▁brod o grad il išta
▁Rich ▁je ▁jos ▁na ▁operacij i .
▁" O ve ▁ću ▁se ▁ist ine ▁Ja ▁ držati " ▁– ▁re če ▁On :
▁Hoćeš ▁da ▁vidim ▁kako ▁je ▁na pol ju ?
▁Pa ▁kad ▁završi te ▁sa lat , ▁tad ▁spo min ji te ▁Allaha ▁sto je ći , ▁i ▁sje de ći ▁i ▁na ▁bok ovima ▁vaš im . ▁Pa ▁kad ▁bude te ▁sigur ni , ▁tad ▁obavlja jte ▁sa lat .
▁G la dan ▁sam .
▁Reci te ▁mi ▁onda ▁ne sto ▁sto ▁je .
▁Kre ni .
▁Č ak ▁i ▁kad ▁nema š ▁šta ▁da ▁izgubi š , ▁ti ▁si ▁slab .
▁Nema ▁ih ▁više .
▁Svi ▁na ▁svoj a ▁mjesta .
▁Chloe , ▁radi ▁samo ▁što ▁br ze ▁mo zes .
▁Samo ▁želi ▁reci ▁nekoliko ▁ rije ci .
▁Sta ću ▁na ▁para liz ovan e ▁no ge ▁već ▁u ▁ sled eć oj ▁scen i .
▁Svet sku ▁pokr ive nost ▁tele vi zi jske ▁intervju e .
▁Za ▁to ▁sam ▁ja ▁kriv a .
▁Je ▁li ▁She ba ▁još ▁uvijek ▁živ a ?
▁- Ho ward e , ▁molim ▁te ...
▁Ob ja v ljeno ▁je ▁u pozor en je ▁na ▁sva ▁i mena ▁kojima ▁se ▁Port er ▁koristi o .
▁Nikad a ▁ne ▁idem ▁tra jek tom .
▁O t ku d ▁ru ke ▁u ▁fri ži der u '
▁Šta ▁ako ▁neko ▁pro govori ?
▁Od bija š ▁i ▁li jek ove ▁protiv ▁boli ?
▁Pa ▁zašto ▁ne ▁mogu ▁da ▁ih ▁č ujem ?
▁Iz v ješ taj ▁Global ne ▁konkurent nosti ▁oc jen ju je ▁ ekonomsk e ▁uvjete ▁u ▁125 ▁zemalja ▁šir om ▁svijet a . ▁[ S EF ]
▁Još ▁malo ▁na prije d .
▁Ali ▁pret post avljam ▁da ▁taj ▁ured ja j ▁koji ▁nas la ▁agent ica ▁Du n ham ... ▁je ▁izvor ▁pul sa !
▁Ne ▁mislim ▁da ▁ću ▁otići ▁kući ▁večer as .
▁A ▁onda , ▁za misli te !
▁Moj ▁pun ac ▁ce ▁biti ▁s retan ▁sto ▁imamo ▁kup ca ▁s ▁A me rick im ▁dolar ima .
▁O prost i , ▁a ▁što ▁ćemo ▁s ▁In gra ssi jom ?
▁Ko ▁ka ze ▁da ▁je ▁ lop ov ?
▁Onda ▁se ▁ne ▁bi ▁raz lik ovali ▁od ▁Um ere njaka .
▁Šta , ▁iz ▁pokr eta ▁ot por a ?
▁- ▁Je sam .
▁Do da š ▁taj ▁rezultat ▁svojim ▁za pa ža njima ▁i ▁pro meni š ▁hipo te zu .
▁Mislil a ▁sam ▁da ▁će ▁ti ▁pri jati ▁hlad no ▁pi će .
▁- ▁Kao ▁po nud u ▁Po moni , ▁i ▁kao ▁gest ▁dobre ▁vol je ▁prema ▁narod u .
▁Pu no ▁kuka š ▁zbog ▁mene , ▁Bru ce . ▁Do s adi lo ▁mi ▁je ▁više .
▁- ▁Sada , ▁da .
▁Mislim ▁da ▁je ▁rec ▁o ▁pre kret nici .
▁Naj isk ren iji dio ▁tijela , koj ine ▁bi ste po godi li ▁su ▁no ge .
▁Je ▁li ▁to ▁bio ▁Con nor ?
▁Možda ▁ja ▁ne ▁želim ▁novi ▁put !
▁Gdje ▁je ▁glavni ▁pi rot ehn ič ar ?
▁Kad ▁sam ▁bila ▁dije te ▁mama ▁mi ▁je ▁rekla ▁da ▁imam ▁veliki ▁pod bra dak . ▁I ▁da ▁se ▁zbog ▁toga ▁ne ▁svi đa m ▁de ch ki ma .
▁- O v dje ▁su ▁i ▁mom ci ▁iz ▁Fre s no a .
▁- ▁Iza ći ću ▁iz ▁Be le ▁ku će ▁sa ▁ovim ▁u ▁ru kama ?
▁Ovo ▁ne ▁ rade ▁ku cep az itelj i .
▁Men i ▁treba ▁pol uv rije me .
▁Možeš ▁li ▁da ▁otvori š ▁neki ▁ulaz ▁u ▁kontrol ni ▁cent ar ?
▁Ako ▁dovoljno ▁dugo ▁gleda š ▁u ▁pro rez ▁učini ćeš ▁da ▁se ▁pla va ▁linij a ▁po ja vi .
▁- ▁Nije ▁stvar ▁u ▁tome ▁kako ▁po čne s ▁i gru ▁nego ▁kako ▁ju ▁za vr sis .
▁Ne ▁znam . ▁" S re ća ▁pre ti ▁hra bre . ▁"
▁Upravo ▁sam ▁prolaz io , ▁a ▁še rif ▁mi ▁je ▁rekao ▁da ▁mogu ▁da ▁s vrat im ... ▁kad ▁pož elim .
▁Kol ica ? ▁Pri je ▁će ▁ ugu ši ti ▁dije te !
▁Mr zim ▁što ▁pre ki dam ▁ovaj ▁než an ▁trenutak , ▁ali ▁zar ▁ti ▁nema š ▁u tak mi cu ▁da ▁o dig raš ?
▁Rekla ▁sam ▁da ▁će ▁nešto ▁už as no ▁da ▁se ▁des i !
▁- ▁Pro pa lica ▁ju ▁ne ▁bi ▁potroš io .
▁Sa t ▁je ▁sat .
▁Moraš ▁sluša ti .
▁- ▁Me kla ude .
▁Zar ▁je ▁po če la ▁noć ▁veš tica ?
▁I ▁ja ▁bi ▁trebao ▁plati ti ▁za ▁to .
▁- Ja ...
▁S vaka ko , ▁sve ▁sto ▁je ▁a meri cka ▁ar mija ▁u cin ila ▁u ▁Av gan istan u ▁i ▁Irak u ▁je ▁mnogo ▁gore ▁od ▁on oga ▁sto ▁je ▁s rp ska ▁vo jska ▁ik ada ▁u cin ila ▁na ▁Ko so vu .
▁- Da .
▁Gdje ▁je ▁Mur iel ?
▁Ti ▁si ▁total no ▁lu da .
▁Osta li ▁smo ▁sam i .
▁bi će ▁u ▁redu .
▁Samo ▁tako .
▁Svi ▁sto peri ▁ ova ko ▁ rade .
▁Ali ▁možda ▁imamo ▁novi ▁ trag .
▁Kaž e ▁da ▁je ▁važno .
▁" U kra de š ▁li ▁mi ▁još ▁jedan ▁rece pt ▁ima ▁da ▁te ▁prov u čem ▁kroz ▁do data k ▁za ▁m lje ven je ▁na ▁tvoj om ▁ku hin j skom ▁profesional nom ▁miks er u ."
▁Sa s vim ▁sam ▁joj ▁do ra sta o , ▁mas ni ▁se ron jo .
▁- H u tten ▁je ▁paz ljiv ▁i ▁pe dan tan ▁profesional ac .
▁Pa , ▁zna ▁li ▁De cker ▁sada ▁da ▁mu ▁je ▁žena ▁ubije na , ▁a ▁dije te ▁o te to ?
▁Da ▁li ▁jos ▁neko ▁zi vi ▁sa ▁vam a ?
▁Že lite , ka o š tos u , ▁ham burg er ... ▁che ese burg er , d vo stru ko
▁Pos le ▁ćemo ▁da ▁igra mo ▁kar te .
▁Slušaj , ▁imaš ▁dobro g ▁partner a .
▁Da . ▁On ▁je ▁pravo , ▁pa ▁le vo .
▁Un u tra , ▁možda . ▁To ▁je ▁to .
▁- Do bili ▁su ▁nas ▁sto .
▁Hu a fu .
▁Ko je ▁iz ne na đen je . ▁Lo ci ra li ▁smo ▁auto ▁koji ▁je ▁Fle ming ▁vozi o .
▁Od ▁koko s ovi h ▁pal mi ▁i ▁smo k vi nih ▁sta bala ▁i ▁kor al j nih ▁p ješ ča nih ▁pla ža ▁i ...
▁Kri lo !
▁Ing eli ▁i ▁Lind i ▁nije ▁dobro .
▁Samo ▁da ▁na zdrav im .
▁U ▁nes vijesti ▁sam ▁i ▁treba ▁mi ▁o živ lja vanje .
▁Kad ▁se ▁be ba ▁rod i , ▁zna ćeš ▁šta ▁treba ▁da ▁radiš .
▁A jde ▁proba j ▁sa ▁vode nim ▁boj ica ma .
▁Var as ▁se ▁ako ▁misli s ▁da ▁poslije ▁nas ▁ne ce ▁prije ci ▁na ▁vas .
▁Že na ▁te ▁izda la .
▁- Š ta ▁god ▁je ▁os vesti .
▁De ly sia ?
▁Ru ke ▁su ▁mi ▁krv ar ile , ▁ali ▁nisam ▁presta ja o .
▁Kaž e ▁da ▁je ▁tip ▁prijav io ▁gubi tak ▁list i ća ▁iz ▁da bro ve ▁bra ne .
▁M la da ▁prost itu tka ▁iz ▁London a ▁bila ▁je ▁novi tet ▁u ▁Na pul ju .
▁Na pos li jet ku , ▁znate , ▁du g ▁je ▁put ▁pred ▁nama ▁Pokuša va jući ▁sti ći ▁Kin u , ▁pa ▁Evrop u ▁Ili , ▁ako ▁već ▁ho će te , ▁a meri čka ▁avion ska ▁komp a nija ▁South - W est ▁ima ▁4 17 ▁avion a
▁Ne ▁zapošljava te ▁dovoljno ▁žena ▁na ▁više ▁pozicij e ▁u ▁kamp a nji .
▁U ▁tom ▁kontekst u , ▁Ab bas ovo ▁put ovanje ▁u ▁Tur sku ▁je ▁od ▁na ro či te ▁važno sti , ▁komen ti ra ▁Euro new s ▁u ▁u tor ak , ▁na vodeći ▁da ▁je ▁Gu l ▁već ▁na ja vio ▁svoju ▁podršk u .
▁Vid jeli ▁su ▁je ▁jutro s ▁na ▁ben zi skoj ▁kod ▁Phil ly ja .
▁Zna ▁dosta ▁na ci sta ▁kru p nih ▁z v jer ki ▁koji ▁vole ▁da ▁se ▁ druž e ▁sa ▁I ju di ma ▁iz ▁pozor išta .
▁- ▁Iz ne na dit ▁če mi ▁ih .
▁Za vrš imo ▁ovo ▁jednom ▁za ▁sva g da .
▁Mora ću ▁da ▁da m ▁ovom ▁idiot u ▁da ▁vodi ▁ vijesti .
